;;; First production backend slice. Unsupported acode is refused, never sent to a native pass 2.
(defpackage "WASM32-COMPILER" (:use "CL"))
(defpackage "WASM32-OS" (:use))
(in-package "WASM32-COMPILER")
(defvar *module-result-tag* nil)
(defvar *module-name* nil)
(defvar *required-vars* nil)
(defvar *temporary-count* 0)
(defvar *cons-used* nil)
(define-condition unsupported-wasm32-code (error)
  ((operation :initarg :operation :reader unsupported-operation))
  (:report (lambda (c s) (format s "WASM32 lowering not implemented: ~s" (unsupported-operation c)))))
(defun refuse (operation) (error 'unsupported-wasm32-code :operation operation))
(defvar *primitive-signature* nil)
(defvar *b-call-links* nil)
(defvar *b-call-mode* nil)
(defun wasm32-pass2 (afunc &rest ignored)
  (declare (ignore ignored))
  (unless *module-result-tag* (refuse :native-fasl-publication))
  (when *b-call-mode* (return-from wasm32-pass2 (b-call-pass2 afunc)))
  (when *primitive-signature* (return-from wasm32-pass2 (primitive-pass2 afunc)))
  (let* ((ir (ccl::afunc-acode afunc)) (args (ccl::acode-operands ir)))
    (unless (and (eq (ccl::acode-operator-name (ccl::acode-operator ir)) 'ccl::lambda-list)
                 (null (second args)) (null (third args)) (null (fourth args))
                 (equal (fifth args) '(nil nil)))
      (refuse :lambda-list))
    (let* ((*required-vars* (first args))
           (*temporary-count* 0) (*cons-used* nil)
           (body (emit-expression (sixth args)))
           (arity (length *required-vars*))
           (wat (format nil "(module~% (import ~s ~s (memory 1 32769 shared))~% (import ~s ~s (global $tcr i32))~%~a (func (export ~s) (param $self i32) (param $nargs i32) (result i32 i32) (local $value i32)~a~%  (if (i32.ne (local.get $nargs) (i32.const ~d)) (then unreachable))~%  (local.set $value ~a)~%  (i32.store (i32.load offset=~d (global.get $tcr)) (local.get $value))~%  (i32.store offset=~d (global.get $tcr) (i32.const 1))~%  (local.get $value) (i32.const 1)))~%"
             "env" "memory" "env" "tcr"
             (if *cons-used* " (import \"env\" \"type_error\" (tag $type_error (param i32 i32)))" "")
             "entry" (with-output-to-string (s) (dotimes (i *temporary-count*) (format s " (local $tmp~d i32)" i)))
             arity body wasm32::tcr.mv_base wasm32::tcr.mv_count)))
      (throw *module-result-tag* (list :version 1 :name *module-name* :arity arity :wat wat)))))
(defun emit-expression (ir)
  (unless (ccl::acode-p ir) (refuse :malformed-acode))
  (let ((op (ccl::acode-operator-name (ccl::acode-operator ir)))
        (args (ccl::acode-operands ir)))
    (case op
      ((nil) (format nil "(i32.const ~d)" wasm32::canonical-nil-value))
      ((t) (format nil "(i32.const ~d)" wasm32::canonical-t-value))
      (ccl::fixnum
       (let ((n (first args)))
         (unless (<= wasm32::target-most-negative-fixnum n wasm32::target-most-positive-fixnum) (refuse :fixnum-range))
         (format nil "(i32.const ~d)" (ash n wasm32::fixnumshift))))
      (ccl::immediate
       (cond ((null (first args)) (format nil "(i32.const ~d)" wasm32::canonical-nil-value))
             ((eq (first args) t) (format nil "(i32.const ~d)" wasm32::canonical-t-value))
             (t (refuse :heap-constant))))
      (ccl::lexical-reference
       (let ((index (position (first args) *required-vars* :test #'eq)))
         (unless index (refuse :non-argument-lexical))
         (format nil "(i32.load offset=~d (i32.load offset=~d (global.get $tcr)))" (* 4 index) wasm32::tcr.vsp)))
      ((car cdr ccl::%car ccl::%cdr)
       (emit-cons-read (member op '(car ccl::%car)) (first args)))
      ((rplaca rplacd ccl::%rplaca ccl::%rplacd)
       (emit-cons-write (member op '(rplaca ccl::%rplaca)) (first args) (second args)))
      (ccl::if
       (format nil "(if (result i32) (i32.ne ~a (i32.const ~d)) (then ~a) (else ~a))"
         (emit-expression (first args)) wasm32::canonical-nil-value
         (emit-expression (second args)) (emit-expression (third args))))
      (t (refuse op)))))
;;; Each nested operand owns a separate local. No calls, polls or allocation
;;; occur while these unspilled tagged temporaries are live in this slice.
(defun temporary () (prog1 (format nil "$tmp~d" *temporary-count*) (incf *temporary-count*)))
(defun cons-check (local expected)
  (format nil "(if (i32.ne (i32.and (local.get ~a) (i32.const ~d)) (i32.const ~d)) (then (throw $type_error (local.get ~a) (i32.const ~d))))"
    local wasm32::fulltagmask wasm32::fulltag-cons local expected))
(defun emit-cons-read (car-p operand)
  (setq *cons-used* t)
  (let* ((ptr (temporary)) (value (emit-expression operand))
         (offset (if car-p wasm32::cons.car wasm32::cons.cdr)))
    (format nil "(block (result i32) (local.set ~a ~a) (if (result i32) (i32.eq (local.get ~a) (i32.const ~d)) (then (i32.const ~d)) (else ~a (i32.load (i32.add (local.get ~a) (i32.const ~d))))))"
      ptr value ptr wasm32::canonical-nil-value wasm32::canonical-nil-value
      (cons-check ptr 1) ptr offset)))
(defun emit-cons-write (car-p pair value)
  (setq *cons-used* t)
  (let* ((ptr (temporary)) (new (temporary))
         (pair-code (emit-expression pair)) (value-code (emit-expression value))
         (offset (if car-p wasm32::cons.car wasm32::cons.cdr)))
    (format nil "(block (result i32) (local.set ~a ~a) (local.set ~a ~a) (if (i32.eq (local.get ~a) (i32.const ~d)) (then (throw $type_error (local.get ~a) (i32.const 2)))) ~a (i32.store (i32.add (local.get ~a) (i32.const ~d)) (local.get ~a)) (local.get ~a))"
      ptr pair-code new value-code ptr wasm32::canonical-nil-value ptr
      (cons-check ptr 2) ptr offset new ptr)))
;;; The next unused three-bit CPU discriminator; no existing target changes.
(defconstant ccl::platform-cpu-wasm32 (ash 4 3))
(defconstant ccl::platform-os-wasm 7)
(defvar *backend*
  (ccl::make-backend :name :wasm32 :num-arg-regs 0 :target-arch-name :wasm32
    :target-arch wasm32::*target-arch* :target-platform (logior ccl::platform-cpu-wasm32 ccl::platform-os-wasm ccl::platform-word-size-32) :target-os :wasm
    :target-specific-features '(:wasm-target :wasm32-target :32-bit-target :little-endian-target)
    :target-fasl-pathname (make-pathname :type "w32fsl")
    :p2-dispatch #() :p2-compile 'wasm32-pass2 :p2-vinsn-templates (make-hash-table :test #'eq)
    :target-foreign-type-data (ccl::make-ftd :interface-package-name "WASM32-OS" :attributes '(:bits-per-word 32))))
(when (and (ccl::find-backend :wasm32) (not (eq *backend* (ccl::find-backend :wasm32))))
  (error "Conflicting WASM32 backend"))
(when (find (ccl::backend-target-platform *backend*) ccl::*known-backends* :key #'ccl::backend-target-platform :test #'=)
  (unless (member *backend* ccl::*known-backends*) (error "WASM32 platform discriminator collision")))
(pushnew *backend* ccl::*known-backends* :key #'ccl::backend-name)
(defun call-with-target (thunk)
  (let* ((ccl::*target-backend* *backend*) (ccl::*fasl-target* :wasm32)
         (*features* (ccl::setup-target-features *backend* *features*)))
    (ccl::with-cross-compilation-target (:wasm32) (funcall thunk))))
;;; Until target macro/helper qualification is integrated, the source API admits
;;; only the syntax this leaf slice implements. Pass-2 refusal alone is too late:
;;; a host compiler macro can fold an unsupported call to an apparently safe IR
;;; constant. This is a declared subset boundary, not an implementation of TYPEP.
(defun validate-leaf-source (form)
  (let ((budget 4096) (active (make-hash-table :test #'eq)))
    (labels ((items (x)
               (let ((seen (make-hash-table :test #'eq)) (result nil))
                 (loop while (consp x) do
                   (when (or (gethash x seen) (minusp (decf budget))) (refuse :source-shape))
                   (setf (gethash x seen) t) (push (car x) result) (setq x (cdr x)))
                 (when x (refuse :source-shape)) (nreverse result)))
             (literal (x)
               (or (null x) (eq x t)
                   (and (integerp x) (<= wasm32::target-most-negative-fixnum x wasm32::target-most-positive-fixnum))))
             (walk (x vars depth)
               (when (or (> depth 128) (minusp (decf budget))) (refuse :source-shape))
               (cond ((literal x) t)
                     ((and (symbolp x) (member x vars :test #'eq)) t)
                     ((consp x)
                      (when (gethash x active) (refuse :source-shape))
                      (setf (gethash x active) t)
                      (unwind-protect
                        (let ((xs (items x)))
                          (cond ((and (eq (car xs) 'if) (member (length xs) '(3 4)))
                                 (dolist (part (cdr xs)) (walk part vars (1+ depth))))
                                ((and (member (car xs) '(car cdr)) (= (length xs) 2))
                                 (walk (second xs) vars (1+ depth)))
                                ((and (member (car xs) '(rplaca rplacd)) (= (length xs) 3))
                                 (walk (second xs) vars (1+ depth)) (walk (third xs) vars (1+ depth)))
                                ((and (eq (car xs) 'quote) (= (length xs) 2) (literal (second xs))) t)
                                (t (refuse :source-subset))))
                        (remhash x active)))
                     (t (refuse :source-subset)))))
      (let ((parts (items form)))
        (unless (and (= (length parts) 3) (eq (first parts) 'lambda)) (refuse :source-subset))
        (let ((vars (items (second parts))))
          (unless (and (every (lambda (v) (and (symbolp v) v (not (eq v t)) (not (keywordp v))
                                                (not (member v lambda-list-keywords)))) vars)
                       (= (length vars) (length (remove-duplicates vars :test #'eq))))
            (refuse :source-subset))
          (walk (third parts) vars 0))))))
(defun compile-module (source-text name)
  (unless (and (stringp source-text) (stringp name)) (error "Source and logical name must be strings"))
  (call-with-target
    (lambda ()
      (let* ((*module-result-tag* (gensym "WASM32-PASS2")) (*module-name* name)
             (*package* (find-package "WASM32-COMPILER")) (*read-eval* nil))
        (multiple-value-bind (form end) (read-from-string source-text)
          (unless (every (lambda (c) (find c '(#\Space #\Tab #\Newline #\Return))) (subseq source-text end))
            (error "Trailing source after the lambda"))
          (validate-leaf-source form)
          (catch *module-result-tag*
            (ccl::compile-named-function form :name name :target :wasm32 :policy ccl::*default-compiler-policy*)
            (error "WASM32 pass 2 failed to publish a module")))))))
(provide "WASM32-BACKEND")

;;; Typed internal primitives. These use raw Wasm parameters, not Lisp B's
;;; node stack. Static representation checking happens on the real front-end
;;; IR before any code is published. All checked failures precede writes.
(defparameter *primitive-operations*
  '((%box-s32 (:s32) :node) (%unbox-fixnum (:node) :s32)
    (%address-fixnum (:address) :node) (%fixnum-address (:node) :address)
    (%tag-misc (:address) :node) (%untag-misc (:node) :address)
    (%effective-address (:address :s32) :address)
    (%header-word (:node) :u32) (%array-bytes (:u32 :u32) :u32)
    (%issue-code (:address) :code-id) (%validate-code (:node :address) :code-id)
    (%code-index (:code-id) :u32)
    (%validate-slot (:u32 :u32 :u32 :u32 :address) :slot)
    (%slot-index (:slot) :u32)))
(defun primitive-signature (name) (assoc name *primitive-operations* :test #'eq))
(defun primitive-check (condition reason)
  (format nil "(if ~a (then (throw $conversion_error (i32.const ~d))))" condition reason))
(defun primitive-span (ptr bytes)
  (primitive-check
    (format nil "(i64.gt_u (i64.add (i64.extend_i32_u ~a) (i64.const ~d)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))" ptr bytes) 4))
(defun primitive-op (name values)
  ;; Materialize operands exactly once, left to right, in disjoint locals.
  (let* ((locals (mapcar (lambda (v) (declare (ignore v)) (temporary)) values))
         (v (mapcar (lambda (x) (format nil "(local.get ~a)" x)) locals))
         (a (first v)) (b (second v)) (c (third v)) (d (fourth v)) (e (fifth v)))
    (with-output-to-string (s)
      (write-string "(block (result i32) " s)
      (loop for local in locals for value in values do (format s "(local.set ~a ~a) " local value))
      (labels ((check (condition reason) (write-string (primitive-check condition reason) s))
               (word (base offset) (format nil "(i32.load offset=~d ~a)" offset base)))
        (case name
          (%box-s32
           (check (format nil "(i32.or (i32.lt_s ~a (i32.const -536870912)) (i32.gt_s ~a (i32.const 536870911)))" a a) 1)
           (format s "(i32.shl ~a (i32.const 2))" a))
          (%unbox-fixnum
           (check (format nil "(i32.and ~a (i32.const 3))" a) 2)
           (format s "(i32.shr_s ~a (i32.const 2))" a))
          (%address-fixnum
           (check (format nil "(i32.gt_u ~a (i32.const 536870911))" a) 1)
           (format s "(i32.shl ~a (i32.const 2))" a))
          (%fixnum-address
           (check (format nil "(i32.and ~a (i32.const 3))" a) 2)
           (check (format nil "(i32.lt_s ~a (i32.const 0))" a) 1)
           (format s "(i32.shr_u ~a (i32.const 2))" a))
          (%tag-misc
           (check (format nil "(i32.and ~a (i32.const 7))" a) 3)
           (format s "(i32.add ~a (i32.const 6))" a))
          ((%untag-misc %header-word)
           (check (format nil "(i32.ne (i32.and ~a (i32.const 7)) (i32.const 6))" a) 2)
           (let ((base (format nil "(i32.sub ~a (i32.const 6))" a)))
             (if (eq name '%header-word)
               (progn (write-string (primitive-span base 4) s) (format s "(i32.load ~a)" base))
               (write-string base s))))
          (%effective-address
           (format s "(local.set $wide (i64.add (i64.extend_i32_u ~a) (i64.extend_i32_s ~a)))" a b)
           (check "(i64.gt_u (local.get $wide) (i64.const 4294967295))" 4)
           (write-string "(i32.wrap_i64 (local.get $wide))" s))
          (%array-bytes
           (check (format nil "(i32.ge_u ~a (i32.const 16777216))" a) 1)
           (check (format nil "(i32.eqz ~a)" b) 1)
           (format s "(local.set $wide (i64.mul (i64.extend_i32_u ~a) (i64.extend_i32_u ~a)))" a b)
           (check "(i64.gt_u (local.get $wide) (i64.const 4294967295))" 4)
           (write-string "(i32.wrap_i64 (local.get $wide))" s))
          ((%issue-code %validate-code)
           (let* ((registry (if (eq name '%issue-code) a b))
                  (first (word registry 0)) (next (word registry 4)) (limit (word registry 8)))
             (write-string (primitive-span registry 12) s)
             (check (format nil "(i32.or (i32.gt_u ~a ~a) (i32.or (i32.gt_u ~a ~a) (i32.gt_u ~a (i32.const 536870912))))" first next next limit limit) 7)
             (if (eq name '%issue-code)
               (progn
                 (check (format nil "(i32.ge_u ~a ~a)" next limit) 6)
                 (format s "(local.set $scratch ~a) (i32.store offset=4 ~a (i32.add (local.get $scratch) (i32.const 1))) (i32.shl (local.get $scratch) (i32.const 2))" next registry))
               (progn
                 (check (format nil "(i32.or (i32.and ~a (i32.const 3)) (i32.lt_s ~a (i32.const 0)))" a a) 2)
                 (format s "(local.set $scratch (i32.shr_u ~a (i32.const 2)))" a)
                 (check (format nil "(i32.or (i32.lt_u (local.get $scratch) ~a) (i32.ge_u (local.get $scratch) ~a))" first next) 5)
                 (write-string a s)))))
          (%code-index (format s "(i32.shr_u ~a (i32.const 2))" a))
          (%validate-slot
           ;; Registry: capacity, reserved prefix, then (signature, role) rows.
           ;; The imported table's actual size is authoritative for capacity.
           (write-string (primitive-span e 8) s)
           (check (format nil "(i32.ne ~a (i32.const 3))" b) 9)
           (check (format nil "(i32.or (i32.gt_u ~a (table.size $slots)) (i32.gt_u ~a ~a))" (word e 0) (word e 4) (word e 0)) 7)
           (check (format nil "(i32.ge_u ~a ~a)" a (word e 0)) 7)
           (check (format nil "(i32.lt_u ~a ~a)" a (word e 4)) 8)
           (format s "(local.set $wide (i64.add (i64.extend_i32_u ~a) (i64.add (i64.const 8) (i64.mul (i64.extend_i32_u ~a) (i64.const 8)))))" e a)
           (check "(i64.gt_u (i64.add (local.get $wide) (i64.const 8)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))" 4)
           (write-string "(local.set $scratch (i32.wrap_i64 (local.get $wide)))" s)
           (check (format nil "(i32.or (i32.eqz ~a) (i32.ne ~a ~a))" c (word "(local.get $scratch)" 0) c) 10)
           (check (format nil "(i32.or (i32.eqz ~a) (i32.ne ~a ~a))" d (word "(local.get $scratch)" 4) d) 11)
           (check (format nil "(ref.is_null (table.get $slots ~a))" a) 12)
           (write-string a s))
          (%slot-index (write-string a s))
          (t (refuse :primitive-operation))))
      (write-char #\) s))))
(defun primitive-expression (ir)
  (unless (ccl::acode-p ir) (refuse :primitive-ir))
  (let ((op (ccl::acode-operator-name (ccl::acode-operator ir))) (args (ccl::acode-operands ir)))
    (case op
      (ccl::lexical-reference
       (let ((n (position (first args) *required-vars* :test #'eq)))
         (unless n (refuse :primitive-variable))
         (values (format nil "(local.get $arg~d)" n) (nth n (first *primitive-signature*)))))
      (ccl::call
       (let* ((callee (first args)) (arguments (second args))
              (name (and (ccl::acode-p callee)
                         (eq (ccl::acode-operator-name (ccl::acode-operator callee)) 'ccl::immediate)
                         (first (ccl::acode-operands callee))))
              (sig (primitive-signature name)))
         (unless (and sig (null (second arguments)) (= (length (first arguments)) (length (second sig))))
           (refuse :primitive-call))
         (let ((codes nil))
           (loop for arg in (first arguments) for kind in (second sig) do
             (multiple-value-bind (code actual) (primitive-expression arg)
               (unless (eq kind actual) (refuse (list :representation name kind actual)))
               (push code codes)))
           (values (primitive-op name (nreverse codes)) (third sig)))))
      (t (refuse (list :primitive-ir op))))))
(defun primitive-pass2 (afunc)
  (let* ((ir (ccl::afunc-acode afunc)) (args (ccl::acode-operands ir)))
    (unless (and (eq (ccl::acode-operator-name (ccl::acode-operator ir)) 'ccl::lambda-list)
                 (null (second args)) (null (third args)) (null (fourth args)) (equal (fifth args) '(nil nil))
                 (= (length (first args)) (length (first *primitive-signature*)))) (refuse :primitive-lambda))
    (let ((*required-vars* (first args)) (*temporary-count* 0))
      (multiple-value-bind (body kind) (primitive-expression (sixth args))
        (unless (eq kind (second *primitive-signature*)) (refuse :primitive-result))
        (throw *module-result-tag*
          (list :version 1 :name *module-name* :abi :typed-internal :signature *primitive-signature*
                :wat (format nil "(module (import ~s ~s (memory 1 32769 shared)) (import ~s ~s (table $slots 0 funcref)) (import ~s ~s (tag $conversion_error (param i32))) (func (export ~s) ~a (result i32) (local $wide i64) (local $scratch i32) ~a ~a))~%"
                       "env" "memory" "env" "slots" "env" "conversion_error" "entry"
                       (with-output-to-string (s) (dotimes (i (length *required-vars*)) (format s "(param $arg~d i32)" i)))
                       (with-output-to-string (s) (dotimes (i *temporary-count*) (format s "(local $tmp~d i32)" i))) body)))))))
(defun compile-primitive-module (source-text name argument-kinds result-kind)
  (let ((kinds '(:s32 :u32 :node :address :code-id :slot)))
    ;; Code IDs and slots may only be produced by checked operations, never
    ;; admitted as unvalidated entry parameters.
    (unless (and (every (lambda (x) (member x '(:s32 :u32 :node :address))) argument-kinds)
                 (member result-kind kinds)) (refuse :primitive-signature)))
  (call-with-target
    (lambda ()
      (let* ((*primitive-signature* (list argument-kinds result-kind))
             (*module-result-tag* (gensym "WASM32-PRIMITIVE")) (*module-name* name)
             (*package* (find-package "WASM32-COMPILER")) (*read-eval* nil))
        (multiple-value-bind (form end) (read-from-string source-text)
          (unless (every (lambda (c) (find c '(#\Space #\Tab #\Newline #\Return))) (subseq source-text end))
            (refuse :primitive-source))
          ;; Bounded, no macro/control/type declarations admitted. All calls
          ;; remain ordinary acode CALLs to this exact private symbol set.
          (let ((budget 4096))
            (labels ((items (x)
                       (let ((seen (make-hash-table :test #'eq)) (out nil))
                         (loop while (consp x) do
                           (when (or (gethash x seen) (minusp (decf budget))) (refuse :primitive-source))
                           (setf (gethash x seen) t) (push (car x) out) (setq x (cdr x)))
                         (when x (refuse :primitive-source)) (nreverse out)))
                     (walk (x vars depth)
                       (when (or (> depth 128) (minusp (decf budget))) (refuse :primitive-source))
                       (unless (member x vars :test #'eq)
                         (let* ((xs (items x)) (sig (primitive-signature (first xs))))
                           (unless (and sig (= (length xs) (1+ (length (second sig))))) (refuse :primitive-source))
                           (dolist (v (cdr xs)) (walk v vars (1+ depth))))) t))
              (let* ((parts (items form)) (vars (items (second parts))))
                (unless (and (= (length parts) 3) (eq (first parts) 'lambda)
                             (= (length vars) (length argument-kinds))
                             (every (lambda (v) (and (symbolp v) v (not (constantp v)) (not (member v lambda-list-keywords)))) vars)
                             (= (length vars) (length (remove-duplicates vars))))
                  (refuse :primitive-source))
                (walk (third parts) vars 0))))
          (catch *module-result-tag*
            (ccl::compile-named-function form :name name :target :wasm32 :policy ccl::*default-compiler-policy*)
            (refuse :primitive-no-output)))))))

;;; First B call unit: required arguments, ordered evaluation and complete
;;; multiple values. No polls, allocation, closures or tail-call claim here.
(defvar *b-imports* nil)
(defvar *b-bound-vars* nil)
(defvar *b-keywords* nil)
(defvar *b-symbols* nil)
(defun b-symbol (name)
  (let ((entry (assoc name *b-call-links* :test #'eq)))
    (unless entry (refuse :b-symbol-identity))
    (pushnew (second entry) *b-symbols* :test #'equal)
    (b-wat "(global.get $symbol_~a)" (second entry))))
(defun b-keyword (key)
  (unless (keywordp key) (refuse :b-keyword-identity))
  (let ((name (string-downcase (symbol-name key))))
    (unless (and (string= (symbol-name key) (string-upcase name))
                 (<= 1 (length name) 64)
                 (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyz0123456789_-")) name))
      (refuse :b-keyword-name))
    (pushnew name *b-keywords* :test #'equal)
    (b-wat "(global.get $key_~a)" name)))
(defun b-bound-address (var)
  (let ((n (position var *b-bound-vars* :test #'eq)))
    (unless n (refuse :b-bound-variable))
    (b-wat "(i32.add (local.get $bindings) (i32.const ~d))" (+ 0 (* 4 n)))))
(defun b-bind-value (var value)
  (if var (b-wat "(i32.store ~a ~a)" (b-bound-address var) value) ""))
(defun b-binding-code (required opt keys rest)
  ;; Input values remain in the caller's root record. Bound values and the
  ;; supplied-p flags occupy the callee's published frame before defaults call.
  (with-output-to-string (s)
    (loop for var in (first opt) for init in (second opt) for sp in (third opt)
          for i from required do
      (format s "(if (i32.gt_u (local.get $nargs) (i32.const ~d)) (then ~a ~a) (else ~a ~a))"
        i (b-bind-value var (b-wat "(i32.load offset=~d (local.get $incoming))" (* 4 i)))
        (b-bind-value sp "(i32.const 77838)")
        (b-bind-value var (b-scalar init)) (b-bind-value sp "(i32.const 77825)")))
    (when rest (write-string (b-rest-binding rest (+ required (length (first opt)))) s))
    (when keys
      (destructuring-bind (allow vars supplied inits names) keys
        (let* ((start (+ required (length (first opt)))) (cursor (temporary)) (key (temporary))
               (value (temporary)) (known (temporary)) (unknown (temporary))
               (allow-seen (temporary)) (allow-value (temporary)))
          (format s "(local.set ~a (i32.const ~d)) (local.set ~a (i32.const 0)) (local.set ~a (i32.const 0)) (local.set ~a (i32.const 77825))"
            cursor start unknown allow-seen allow-value)
          (write-string (b-condition (b-wat "(i32.and (i32.gt_u (local.get $nargs) (i32.const ~d)) (i32.and (i32.sub (local.get $nargs) (i32.const ~d)) (i32.const 1)))" start start) 1) s)
          (format s "(block $keys_done (loop $keys_scan (br_if $keys_done (i32.ge_u (local.get ~a) (local.get $nargs))) (local.set ~a (i32.load (i32.add (local.get $incoming) (i32.mul (local.get ~a) (i32.const 4))))) (local.set ~a (i32.load offset=4 (i32.add (local.get $incoming) (i32.mul (local.get ~a) (i32.const 4))))) (local.set ~a (i32.const 0))" cursor key cursor value cursor known)
          (loop for var in vars for sp in supplied for name across names do
            (format s "(if (i32.eq (local.get ~a) ~a) (then (local.set ~a (i32.const 1)) (if (i32.eq (i32.load ~a) (i32.const 77825)) (then ~a ~a))))"
              key (b-keyword name) known (b-bound-address sp)
              (b-bind-value var (b-local value)) (b-bind-value sp "(i32.const 77838)")))
          ;; :ALLOW-OTHER-KEYS is itself a recognized keyword, with first-wins
          ;; semantics even when the lambda also binds that named keyword.
          (format s "(if (i32.eq (local.get ~a) ~a) (then (local.set ~a (i32.const 1)) (if (i32.eqz (local.get ~a)) (then (local.set ~a (i32.const 1)) (local.set ~a (local.get ~a))))))"
            key (b-keyword :allow-other-keys) known allow-seen allow-seen allow-value value)
          (format s "(if (i32.eqz (local.get ~a)) (then (local.set ~a (i32.const 1)))) (local.set ~a (i32.add (local.get ~a) (i32.const 2))) (br $keys_scan)))" known unknown cursor cursor)
          (unless allow
            (write-string (b-condition (b-wat "(i32.and (local.get ~a) (i32.eq (local.get ~a) (i32.const 77825)))" unknown allow-value) 1) s))
        (loop for var in vars for sp in supplied for init in inits do
          (format s "(if (i32.eq (i32.load ~a) (i32.const 77825)) (then ~a))"
            (b-bound-address sp) (b-bind-value var (b-scalar init)))))))))
(defun b-wat (control &rest args) (apply #'format nil control args))
(defun b-load (offset) (b-wat "(i32.load offset=~d (global.get $tcr))" offset))
(defun b-store (offset value) (b-wat "(i32.store offset=~d (global.get $tcr) ~a)" offset value))
(defun b-local (name) (b-wat "(local.get ~a)" name))
(defun b-at (base offset) (b-wat "(i32.add ~a (i32.const ~d))" base offset))
(defun b-condition (test kind)
  (b-wat "(if ~a (then (throw $call_error (i32.const ~d))))" test kind))
(defun b-reserve (bytes)
  (concatenate 'string
    (b-condition (b-wat "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $top)) (i64.const ~d)) (i64.extend_i32_u ~a))" bytes (b-load wasm32::tcr.vsp_limit)) 2)
    (b-wat "(local.set $top (i32.add (local.get $top) (i32.const ~d)))" bytes)))
(defun b-initialize-roots (frame count)
  (with-output-to-string (s)
    (format s "(i32.store ~a ~a) (i32.store offset=4 ~a (i32.const ~d))" frame (b-load wasm32::tcr.root_head) frame count)
    (dotimes (i count) (format s "(i32.store offset=~d ~a (i32.const ~d))" (+ 8 (* 4 i)) frame wasm32::canonical-nil-value))
    (write-string (b-store wasm32::tcr.root_head frame) s)))
(defun b-frame (count body-function)
  (let* ((base (temporary)) (old-root (temporary)) (bytes (* 16 (ceiling (+ 8 (* 4 count)) 16)))
         (body (funcall body-function (b-local base))))
    (b-wat "(local.set ~a (local.get $top)) (local.set ~a ~a) ~a ~a ~a ~a (local.set $top (local.get ~a))"
      base old-root (b-load wasm32::tcr.root_head) (b-reserve bytes)
      (b-initialize-roots (b-local base) count) body
      (b-store wasm32::tcr.root_head (b-local old-root)) base)))
(defun b-reserve-runtime (bytes)
  ;; All extent arithmetic precedes narrowing and any frame write.
  (b-wat "(local.set $wide ~a) ~a (local.set $top (i32.wrap_i64 (i64.add (i64.extend_i32_u (local.get $top)) (local.get $wide))))"
    bytes (b-condition (b-wat "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $top)) (local.get $wide)) (i64.extend_i32_u ~a))" (b-load wasm32::tcr.vsp_limit)) 2)))
(defun b-runtime-roots (frame count)
  (let ((i (temporary)))
    (b-wat "(i32.store ~a ~a) (i32.store offset=4 ~a ~a) (local.set ~a (i32.const 0)) (block $roots_done (loop $roots_fill (br_if $roots_done (i32.ge_u (local.get ~a) ~a)) (i32.store (i32.add ~a (i32.add (i32.const 8) (i32.mul (local.get ~a) (i32.const 4)))) (i32.const 77825)) (local.set ~a (i32.add (local.get ~a) (i32.const 1))) (br $roots_fill))) ~a"
      frame (b-load wasm32::tcr.root_head) frame count i i count frame i i i (b-store wasm32::tcr.root_head frame))))
(defun b-retained-frame (count body-function)
  (let* ((base (temporary)) (root (temporary)) (body (funcall body-function (b-local base))))
    (b-wat "(local.set ~a (local.get $top)) (local.set ~a ~a) ~a ~a ~a ~a (local.set $top (local.get ~a))"
      base root (b-load wasm32::tcr.root_head)
      (b-reserve-runtime (b-wat "(i64.and (i64.add (i64.mul (i64.extend_i32_u ~a) (i64.const 4)) (i64.const 23)) (i64.const -16))" count))
      (b-runtime-roots (b-local base) count) body (b-store wasm32::tcr.root_head (b-local root)) base)))
(defun b-call (callee argument-list)
  (unless (null (second argument-list)) (refuse :b-arguments))
  (let* ((args (first argument-list)) (n (length args)) (arg-slots (* 4 (ceiling n 4)))
         (base (temporary)) (root (temporary)) (mv (temporary)) (owner (temporary)) (vsp (temporary)) (old-count (temporary))
         (out-offset (+ 16 (* 4 arg-slots)))
         (op (ccl::acode-operator-name (ccl::acode-operator callee)))
         (name (and (eq op 'ccl::immediate) (first (ccl::acode-operands callee))))
         (direct (and (symbolp name) (assoc name *b-call-links* :test #'eq)))
         (self (if direct (b-symbol name) (b-scalar callee)))
         (codes (mapcar #'b-scalar args)))
    (when (and name (not direct)) (refuse :b-unlinked-function))
    
    (with-output-to-string (s)
      (format s "(local.set ~a (local.get $top)) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a)"
        base root (b-load wasm32::tcr.root_head) mv (b-load wasm32::tcr.mv_base)
        owner (b-load wasm32::tcr.mv_owner_top) vsp (b-load wasm32::tcr.vsp) old-count (b-load wasm32::tcr.mv_count))
      (write-string (b-reserve-runtime (b-wat "(i64.add (i64.const ~d) (i64.extend_i32_u (local.get $result_bytes)))" out-offset)) s)
      (write-string (b-initialize-roots (b-local base) (+ 2 arg-slots)) s)
      (format s "(i32.store offset=8 (local.get ~a) ~a)" base self)
      (loop for code in codes for i from 0 do (format s "(i32.store offset=~d (local.get ~a) ~a)" (+ 16 (* 4 i)) base code))
      (write-string (b-store wasm32::tcr.vsp (b-at (b-local base) 16)) s)
      (write-string (b-store wasm32::tcr.mv_base (b-at (b-local base) out-offset)) s)
      (write-string (b-store wasm32::tcr.mv_owner_top "(local.get $top)") s)
      (write-string (b-store wasm32::tcr.mv_count "(i32.const 0)") s)
      (format s "(call $resolve (i32.load offset=8 (local.get ~a))) (local.set $dispatch_slot) (local.set $dispatch_self) (i32.store offset=8 (local.get ~a) (local.get $dispatch_self)) (call_indirect (type $b_entry) (i32.load offset=8 (local.get ~a)) (i32.const ~d) (local.get $dispatch_slot))" base base base n)
      (write-string "(local.set $count) (local.set $value)" s)
      (write-string (b-condition "(i32.gt_u (local.get $count) (local.get $capacity))" 3) s)
      (format s "(memory.copy (local.get $results) (i32.add (local.get ~a) (i32.const ~d)) (i32.mul (local.get $count) (i32.const 4)))" base out-offset)
      (write-string (b-store wasm32::tcr.vsp (b-local vsp)) s)
      (write-string (b-store wasm32::tcr.mv_base (b-local mv)) s)
      (write-string (b-store wasm32::tcr.mv_owner_top (b-local owner)) s)
      (write-string (b-store wasm32::tcr.mv_count (b-local old-count)) s)
      (write-string (b-store wasm32::tcr.root_head (b-local root)) s)
      (format s "(local.set $top (local.get ~a))" base))))
(defun b-scalar (ir)
  (let ((op (ccl::acode-operator-name (ccl::acode-operator ir))) (args (ccl::acode-operands ir)))
    (case op
      (ccl::lexical-reference
       (let ((n (position (first args) *required-vars* :test #'eq)))
         (if n (b-wat "(i32.load offset=~d (local.get $incoming))" (* 4 n))
           (b-wat "(i32.load ~a)" (b-bound-address (first args))))))
      (ccl::immediate
       (cond ((keywordp (first args)) (b-keyword (first args)))
             ((assoc (first args) *b-call-links*) (b-symbol (first args)))
             (t (emit-expression ir))))
      (ccl::%function (b-wat "(call $function_value ~a)" (b-symbol (first args))))
      ((ccl::call ccl::values ccl::progn ccl::multiple-value-prog1 ccl::prog1 ccl::if)
       (b-wat "(block (result i32) ~a (if (result i32) (local.get $count) (then (i32.load (local.get $results))) (else (i32.const ~d))))" (b-multiple ir) wasm32::canonical-nil-value))
      ((car cdr ccl::%car ccl::%cdr)
       (let* ((p (temporary)) (code (b-scalar (first args))) (offset (if (member op '(car ccl::%car)) wasm32::cons.car wasm32::cons.cdr)))
         (b-wat "(block (result i32) (local.set ~a ~a) (if (result i32) (i32.eq (local.get ~a) (i32.const ~d)) (then (i32.const ~d)) (else ~a (i32.load (i32.add (local.get ~a) (i32.const ~d))))))" p code p wasm32::canonical-nil-value wasm32::canonical-nil-value (cons-check p 1) p offset)))
      ((rplaca rplacd ccl::%rplaca ccl::%rplacd)
       (let* ((p (temporary)) (v (temporary)) (pair (b-scalar (first args))) (value (b-scalar (second args)))
              (offset (if (member op '(rplaca ccl::%rplaca)) wasm32::cons.car wasm32::cons.cdr)))
         (b-wat "(block (result i32) (local.set ~a ~a) (local.set ~a ~a) (if (i32.eq (local.get ~a) (i32.const ~d)) (then (throw $type_error (local.get ~a) (i32.const 2)))) ~a (i32.store (i32.add (local.get ~a) (i32.const ~d)) (local.get ~a)) (local.get ~a))" p pair v value p wasm32::canonical-nil-value p (cons-check p 2) p offset v p)))
      (t (emit-expression ir)))))
(defun b-multiple (ir)
  (let ((op (ccl::acode-operator-name (ccl::acode-operator ir))) (args (ccl::acode-operands ir)))
    (case op
      (ccl::call (if (third args)
                    (if (eq (third args) t) (b-apply (first args) (second args)) (refuse :b-spread-kind))
                    (b-call (first args) (second args))))
      (ccl::values
       (let* ((forms (first args)) (n (length forms)))
         ;; Capacity is a runtime resource, not a fixed language limit.
         (b-frame n (lambda (base)
           (with-output-to-string (s)
             (loop for f in forms for i from 0 do (format s "(i32.store offset=~d ~a ~a)" (+ 8 (* 4 i)) base (b-scalar f)))
             (write-string (b-condition (b-wat "(i32.gt_u (i32.const ~d) (local.get $capacity))" n) 3) s)
             (format s "(memory.copy (local.get $results) ~a (i32.const ~d)) (local.set $count (i32.const ~d))" (b-at base 8) (* 4 n) n))))))
      (ccl::progn
       (with-output-to-string (s)
         (loop for rest on (first args) do
           (write-string (if (cdr rest) (b-wat "(drop ~a)" (b-scalar (car rest))) (b-multiple (car rest))) s))))
      (ccl::if
       (b-wat "(if (i32.ne ~a (i32.const ~d)) (then ~a) (else ~a))" (b-scalar (first args)) wasm32::canonical-nil-value (b-multiple (second args)) (b-multiple (third args))))
      ((ccl::multiple-value-prog1 ccl::prog1)
       (let ((forms (first args)) (saved (temporary)))
         (concatenate 'string
           (if (eq op 'ccl::prog1)
             (b-wat "(i32.store (local.get $results) ~a) (local.set ~a (i32.const 1))" (b-scalar (first forms)) saved)
             (b-wat "~a (local.set ~a (local.get $count))" (b-multiple (first forms)) saved))
           (b-retained-frame (b-local saved) (lambda (base)
             (with-output-to-string (s)
               (format s "(memory.copy ~a (local.get $results) (i32.mul (local.get ~a) (i32.const 4)))" (b-at base 8) saved)
               (dolist (f (cdr forms)) (format s "(drop ~a)" (b-scalar f)))
               (format s "(local.set $count (local.get ~a)) (memory.copy (local.get $results) ~a (i32.mul (local.get $count) (i32.const 4)))" saved (b-at base 8))))))))
      (t (b-wat "(i32.store (local.get $results) ~a) (local.set $count (i32.const 1))" (b-scalar ir))))))
(defun b-call-pass2 (afunc)
  (let* ((ir (ccl::afunc-acode afunc)) (args (ccl::acode-operands ir)))
    (unless (and (eq (ccl::acode-operator-name (ccl::acode-operator ir)) 'ccl::lambda-list)
                 (not (consp (third args))) (equal (fifth args) '(nil nil))) (refuse :b-lambda))
    (let* ((*required-vars* (first args)) (*temporary-count* 0) (*b-imports* nil) (*b-keywords* nil) (*b-symbols* nil)
           (opt (second args)) (keys (fourth args)) (rest (third args))
           (*b-bound-vars* (remove nil (append (first opt) (third opt) (list rest) (second keys) (third keys))))
           (arity (length *required-vars*)) (maximum (+ arity (length (first opt))))
           (bindings (b-binding-code arity opt keys rest))
           (body (b-multiple (sixth args)))
           (restore (concatenate 'string (b-store wasm32::tcr.vsp "(local.get $incoming)")
                     (b-store wasm32::tcr.mv_base "(local.get $output)") (b-store wasm32::tcr.mv_owner_top "(local.get $owner)")
                     (b-store wasm32::tcr.root_head "(local.get $root)")))
           (entry-roots (b-runtime-roots "(local.get $frame)" (b-wat "(i32.add (local.get $capacity) (i32.const ~d))" (length *b-bound-vars*))))
           (wat (with-output-to-string (s)
             (write-string "(module (type $b_entry (func (param i32 i32) (result i32 i32))) (import \"env\" \"memory\" (memory 1 32769 shared)) (import \"env\" \"tcr\" (global $tcr i32)) (import \"env\" \"table\" (table 0 funcref)) (import \"env\" \"code_registry\" (global $code_registry i32)) (import \"env\" \"call_error\" (tag $call_error (param i32))) (import \"env\" \"type_error\" (tag $type_error (param i32 i32)))" s)
             (dolist (name (sort *b-keywords* #'string<))
               (format s "(import \"keywords\" ~s (global $key_~a i32))" name name))
             (dolist (name (sort *b-symbols* #'string<))
               (format s "(import \"symbols\" ~s (global $symbol_~a i32))" name name))
             (write-string (b-object-runtime) s)
             (write-string "(func (export \"entry\") (type $b_entry) (param $self i32) (param $nargs i32) (result i32 i32) (local $incoming i32) (local $output i32) (local $owner i32) (local $root i32) (local $old_count i32) (local $frame i32) (local $results i32) (local $top i32) (local $count i32) (local $value i32) (local $exception exnref) (local $wide i64) (local $capacity i32) (local $result_bytes i32) (local $bindings i32) (local $dispatch_self i32) (local $dispatch_slot i32)" s)
             (dotimes (i *temporary-count*) (format s "(local $tmp~d i32)" i))
             (format s "(local.set $incoming ~a) (local.set $output ~a) (local.set $owner ~a) (local.set $root ~a) (local.set $old_count ~a) (local.set $top (local.get $owner))"
               (b-load wasm32::tcr.vsp) (b-load wasm32::tcr.mv_base) (b-load wasm32::tcr.mv_owner_top) (b-load wasm32::tcr.root_head) (b-load wasm32::tcr.mv_count))
             (write-string (b-condition (b-wat "(i32.or (i32.lt_u (local.get $nargs) (i32.const ~d)) (i32.gt_u (local.get $nargs) (i32.const ~d)))" arity (if (or keys rest) #xffffffff maximum)) 1) s)
             (write-string (b-condition "(i32.or (i32.lt_u (local.get $incoming) (i32.load offset=68 (global.get $tcr))) (i32.and (i32.or (local.get $incoming) (i32.or (local.get $output) (local.get $owner))) (i32.const 15)))" 2) s)
             (write-string (b-condition "(i32.or (i32.gt_u (local.get $output) (local.get $owner)) (i32.gt_u (local.get $owner) (i32.load offset=72 (global.get $tcr))))" 2) s)
             (write-string (b-condition "(i64.gt_u (i64.extend_i32_u (i32.load offset=72 (global.get $tcr))) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))" 2) s)
             (write-string (b-condition "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $incoming)) (i64.and (i64.add (i64.mul (i64.extend_i32_u (local.get $nargs)) (i64.const 4)) (i64.const 15)) (i64.const -16))) (i64.extend_i32_u (local.get $output)))" 2) s)
             (write-string "(block $caught (result exnref) (try_table (catch_all_ref $caught) (local.set $frame (local.get $top))" s)
             ;; At least four scratch words permit scalar evaluation even with an
             ;; empty final reservation. Child reservations inherit this budget.
             (write-string "(local.set $result_bytes (i32.sub (local.get $owner) (local.get $output))) (if (i32.lt_u (local.get $result_bytes) (i32.const 16)) (then (local.set $result_bytes (i32.const 16)))) (local.set $capacity (i32.div_u (local.get $result_bytes) (i32.const 4)))" s)
             (write-string (b-reserve-runtime (b-wat "(i64.and (i64.add (i64.extend_i32_u (local.get $result_bytes)) (i64.const ~d)) (i64.const -16))" (+ 23 (* 4 (length *b-bound-vars*))))) s)
             (write-string entry-roots s)
             (write-string "(local.set $bindings (i32.add (local.get $frame) (i32.add (i32.const 8) (local.get $result_bytes))))" s)
             (write-string "(local.set $results (i32.add (local.get $frame) (i32.const 8)))" s)
             (write-string bindings s)
             (write-string body s)
             (write-string (b-condition "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $output)) (i64.mul (i64.extend_i32_u (local.get $count)) (i64.const 4))) (i64.extend_i32_u (local.get $owner)))" 3) s)
             (write-string "(local.set $value (if (result i32) (local.get $count) (then (i32.load (local.get $results))) (else (i32.const 77825)))) (memory.copy (local.get $output) (local.get $results) (i32.mul (local.get $count) (i32.const 4)))" s)
             (write-string restore s)
             (write-string (b-store wasm32::tcr.mv_count "(local.get $count)") s)
             (write-string "(return (local.get $value) (local.get $count))) unreachable) (local.set $exception)" s)
             (write-string restore s)
             (write-string (b-store wasm32::tcr.mv_count "(local.get $old_count)") s)
             (write-string "(throw_ref (local.get $exception))))" s))))
      (throw *module-result-tag* (list :name *module-name* :arity arity :wat wat :imports *b-imports*)))))
(defun compile-call-module (source-text name links)
  (unless (and (every (lambda (s) (and (stringp s) (<= 1 (length s) 64)
                                     (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyz0123456789_-")) s))) links)
               (= (length links) (length (remove-duplicates links :test #'equal)))) (refuse :b-link-names))
  (call-with-target
    (lambda ()
      (let* ((*b-call-mode* t) (*b-keywords* nil) (*module-result-tag* (gensym "B-CALL")) (*module-name* name)
             (*package* (find-package "WASM32-COMPILER")) (*read-eval* nil)
             (*b-call-links* (mapcar (lambda (x) (list (intern (string-upcase x) *package*) x)) links)))
        (multiple-value-bind (form end) (read-from-string source-text)
          (unless (every (lambda (c) (find c '(#\Space #\Tab #\Newline #\Return))) (subseq source-text end)) (refuse :b-source))
          (let ((budget 8192))
            (labels ((items (x)
                       (let ((seen (make-hash-table :test #'eq)) (out nil))
                         (loop while (consp x) do (when (or (gethash x seen) (minusp (decf budget))) (refuse :b-source))
                           (setf (gethash x seen) t) (push (car x) out) (setq x (cdr x)))
                         (when x (refuse :b-source)) (nreverse out)))
                     (walk (x vars depth)
                       (when (or (> depth 128) (minusp (decf budget))) (refuse :b-source))
                       (cond ((or (null x) (eq x t) (and (keywordp x) (b-keyword x)) (and (integerp x) (<= -536870912 x 536870911)) (member x vars)) t)
                             ((consp x)
                              (let* ((xs (items x)) (head (car xs)) (n (length (cdr xs))))
                                (when (member head '(quote function))
                                  (unless (and (= n 1) (assoc (second xs) *b-call-links*)) (refuse :b-source))
                                  (return-from walk t))
                                (unless (or (and (member head '(car cdr)) (= n 1)) (and (member head '(rplaca rplacd)) (= n 2))
                                            (and (eq head 'if) (member n '(2 3)))
                                            (member head '(values progn))
                                            (and (member head '(prog1 multiple-value-prog1)) (<= 1 n))
                                            (and (eq head 'funcall) (<= 1 n))
                                            (and (eq head 'apply) (<= 2 n))
                                            (assoc head *b-call-links*)) (refuse :b-source))
                                (dolist (part (cdr xs)) (walk part vars (1+ depth)))))
                             (t (refuse :b-source)))))
              (let* ((parts (items form)) (parameters (items (second parts))) (vars nil) (mode :required) (keys nil))
                (unless (and (= (length parts) 3) (eq (first parts) 'lambda)) (refuse :b-source))
                (labels ((add-var (v)
                           (unless (and (symbolp v) v (not (constantp v))
                                        (not (member v lambda-list-keywords)) (not (member v vars))) (refuse :b-source))
                           (push v vars)))
                  (dolist (parameter parameters)
                    (cond ((eq parameter '&optional)
                           (unless (eq mode :required) (refuse :b-source)) (setq mode :optional))
                          ((eq parameter '&rest)
                           (unless (member mode '(:required :optional)) (refuse :b-source)) (setq mode :rest))
                          ((eq mode :rest) (add-var parameter) (setq mode :after-rest))
                          ((eq parameter '&key)
                           (unless (member mode '(:required :optional :after-rest)) (refuse :b-source)) (setq mode :key))
                          ((eq parameter '&allow-other-keys)
                           (unless (eq mode :key) (refuse :b-source)) (setq mode :end))
                          ((eq mode :required) (add-var parameter))
                          ((member mode '(:optional :key))
                           (let* ((parts (if (consp parameter) (items parameter) (list parameter)))
                                  (v (first parts)) (init (second parts)) (sp (third parts)))
                             (unless (<= 1 (length parts) 3) (refuse :b-source))
                             (when (eq mode :key)
                               (let ((name (if (consp v)
                                             (let ((pair (items v)))
                                               (unless (= (length pair) 2) (refuse :b-source))
                                               (setq v (second pair)) (first pair))
                                             (and (symbolp v) (intern (symbol-name v) "KEYWORD")))))
                                 (unless (and (keywordp name) (not (member name keys))) (refuse :b-source))
                                 (b-keyword name) (push name keys)))
                             (walk init vars 0) (add-var v) (when sp (add-var sp))))
                          (t (refuse :b-source)))))
                (when (eq mode :rest) (refuse :b-source))
                (walk (third parts) vars 0))))
          (catch *module-result-tag*
            (ccl::compile-named-function form :name name :target :wasm32 :policy ccl::*default-compiler-policy*)
            (refuse :b-no-output)))))))

;;; Rest/APPLY sequences execute without calls, polls or collection while
;;; traversing or initializing heap cells. The allocator is a checked bump
;;; pointer in the thread-owned TCR area; exhaustion never publishes a list.
(defun b-rest-binding (var start)
  (let ((n (temporary)) (cursor (temporary)) (head (temporary)) (index (temporary)))
    (with-output-to-string (s)
      (format s "(local.set ~a (if (result i32) (i32.gt_u (local.get $nargs) (i32.const ~d)) (then (i32.sub (local.get $nargs) (i32.const ~d))) (else (i32.const 0)))) (local.set ~a (i32.const 77825))" n start start head)
      (format s "(if (local.get ~a) (then (local.set ~a ~a)" n cursor (b-load wasm32::tcr.alloc_pointer))
      (write-string (b-condition (b-wat "(i32.or (i32.lt_u (local.get ~a) ~a) (i32.and (local.get ~a) (i32.const 7)))" cursor (b-load wasm32::tcr.alloc_base) cursor) 6) s)
      (write-string (b-condition (b-wat "(i64.gt_u (i64.extend_i32_u ~a) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))" (b-load wasm32::tcr.alloc_limit)) 6) s)
      (format s "(local.set $wide (i64.add (i64.extend_i32_u (local.get ~a)) (i64.mul (i64.extend_i32_u (local.get ~a)) (i64.const 8))))" cursor n)
      (write-string (b-condition (b-wat "(i64.gt_u (local.get $wide) (i64.extend_i32_u ~a))" (b-load wasm32::tcr.alloc_limit)) 6) s)
      ;; Allocate backwards through the argument sequence, with CDR first.
      (format s "(local.set ~a (local.get $nargs)) (loop $rest_cells (local.set ~a (i32.sub (local.get ~a) (i32.const 1))) (i32.store (local.get ~a) (local.get ~a)) (i32.store offset=4 (local.get ~a) (i32.load (i32.add (local.get $incoming) (i32.mul (local.get ~a) (i32.const 4))))) (local.set ~a (i32.add (local.get ~a) (i32.const 1))) (local.set ~a (i32.add (local.get ~a) (i32.const 8))) (br_if $rest_cells (i32.gt_u (local.get ~a) (i32.const ~d))))"
        index index index cursor head cursor index head cursor cursor cursor index start)
      (write-string (b-store wasm32::tcr.alloc_pointer (b-local cursor)) s)
      (write-string "))" s)
      (write-string (b-bind-value var (b-local head)) s))))
(defun b-checked-cdr (node)
  (b-wat "(block (result i32) ~a ~a (i32.load (i32.sub ~a (i32.const 1))))"
    (b-condition (b-wat "(i32.ne (i32.and ~a (i32.const ~d)) (i32.const ~d))" node wasm32::fulltagmask wasm32::fulltag-cons) 5)
    (b-condition (b-wat "(i64.gt_u (i64.add (i64.extend_i32_u ~a) (i64.const 7)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))" node) 5) node))
(defun b-apply (callee argument-list)
  (unless (= (length (second argument-list)) 1) (refuse :b-apply-shape))
  (let* ((prefix (first argument-list)) (n (length prefix))
         (evaluated (temporary)) (base (temporary)) (root (temporary))
         (mv (temporary)) (owner (temporary)) (vsp (temporary)) (old-count (temporary))
         (cursor (temporary)) (slow (temporary)) (length (temporary)) (total (temporary))
         (output (temporary)) (roots (temporary)) (index (temporary))
         (op (ccl::acode-operator-name (ccl::acode-operator callee)))
         (name (and (eq op 'ccl::immediate) (first (ccl::acode-operands callee))))
         (direct (and (symbolp name) (assoc name *b-call-links* :test #'eq)))
         (self (if direct (b-symbol name) (b-scalar callee)))
         (codes (mapcar #'b-scalar prefix)) (tail (b-scalar (first (second argument-list)))))
    (when (and name (not direct)) (refuse :b-unlinked-function))
    
    (with-output-to-string (s)
      (format s "(local.set ~a (local.get $top)) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a) (local.set ~a ~a)"
        evaluated root (b-load wasm32::tcr.root_head) mv (b-load wasm32::tcr.mv_base)
        owner (b-load wasm32::tcr.mv_owner_top) vsp (b-load wasm32::tcr.vsp) old-count (b-load wasm32::tcr.mv_count))
      (write-string (b-reserve (* 16 (ceiling (+ 16 (* 4 n)) 16))) s)
      (write-string (b-initialize-roots (b-local evaluated) (+ 2 n)) s)
      (format s "(i32.store offset=8 (local.get ~a) ~a)" evaluated self)
      (loop for code in codes for i from 0 do (format s "(i32.store offset=~d (local.get ~a) ~a)" (+ 16 (* 4 i)) evaluated code))
      (format s "(i32.store offset=12 (local.get ~a) ~a) (local.set ~a (i32.load offset=12 (local.get ~a))) (local.set ~a (local.get ~a)) (local.set ~a (i32.const 0))"
        evaluated tail cursor evaluated slow cursor length)
      ;; One cursor advances on every step, the other on alternate steps.
      ;; Check against the available stack on every step as well as detecting
      ;; cycles: finite malformed input cannot wrap the count or exhaust JS.
      (format s "(block $list_done (loop $list_check (br_if $list_done (i32.eq (local.get ~a) (i32.const 77825))) (local.set ~a ~a) (local.set ~a (i32.add (local.get ~a) (i32.const 1)))"
        cursor cursor (b-checked-cdr (b-local cursor)) length length)
      (write-string (b-condition (b-wat "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $top)) (i64.mul (i64.add (i64.extend_i32_u (local.get ~a)) (i64.const ~d)) (i64.const 4))) (i64.extend_i32_u ~a))" length n (b-load wasm32::tcr.vsp_limit)) 2) s)
      (format s "(if (i32.eqz (i32.and (local.get ~a) (i32.const 1))) (then (local.set ~a ~a)))" length slow (b-checked-cdr (b-local slow)))
      (write-string (b-condition (b-wat "(i32.and (i32.ne (local.get ~a) (i32.const 77825)) (i32.eq (local.get ~a) (local.get ~a)))" cursor cursor slow) 5) s)
      (write-string "(br $list_check)))" s)
      (format s "(local.set ~a (i32.add (local.get ~a) (i32.const ~d))) (local.set ~a (local.get $top)) (local.set $wide (i64.and (i64.add (i64.mul (i64.extend_i32_u (local.get ~a)) (i64.const 4)) (i64.const 31)) (i64.const -16)))" total length n base total)
      ;; $wide is the output offset (header/self/padding plus aligned args).
      (write-string (b-condition (b-wat "(i64.gt_u (i64.add (i64.extend_i32_u (local.get $top)) (i64.add (local.get $wide) (i64.extend_i32_u (local.get $result_bytes)))) (i64.extend_i32_u ~a))" (b-load wasm32::tcr.vsp_limit)) 2) s)
      (format s "(local.set ~a (i32.add (local.get $top) (i32.wrap_i64 (local.get $wide)))) (local.set ~a (i32.div_u (i32.sub (i32.wrap_i64 (local.get $wide)) (i32.const 8)) (i32.const 4))) (local.set $top (i32.add (local.get ~a) (local.get $result_bytes)))"
        output roots output)
      (format s "(i32.store (local.get ~a) ~a) (i32.store offset=4 (local.get ~a) (local.get ~a)) (local.set ~a (i32.const 0)) (loop $apply_roots (i32.store (i32.add (local.get ~a) (i32.add (i32.const 8) (i32.mul (local.get ~a) (i32.const 4)))) (i32.const 77825)) (local.set ~a (i32.add (local.get ~a) (i32.const 1))) (br_if $apply_roots (i32.lt_u (local.get ~a) (local.get ~a))))"
        base (b-load wasm32::tcr.root_head) base roots index base index index index index roots)
      (write-string (b-store wasm32::tcr.root_head (b-local base)) s)
      (format s "(i32.store offset=8 (local.get ~a) (i32.load offset=8 (local.get ~a))) (memory.copy ~a ~a (i32.const ~d)) (local.set ~a (i32.load offset=12 (local.get ~a))) (local.set ~a (i32.const ~d))"
        base evaluated (b-at (b-local base) 16) (b-at (b-local evaluated) 16) (* 4 n) cursor evaluated index n)
      (format s "(block $spread_done (loop $spread_copy (br_if $spread_done (i32.eq (local.get ~a) (i32.const 77825))) (i32.store (i32.add (local.get ~a) (i32.add (i32.const 16) (i32.mul (local.get ~a) (i32.const 4)))) (i32.load offset=3 (local.get ~a))) (local.set ~a (i32.load (i32.sub (local.get ~a) (i32.const 1)))) (local.set ~a (i32.add (local.get ~a) (i32.const 1))) (br $spread_copy)))"
        cursor base index cursor cursor cursor index index)
      (write-string (b-store wasm32::tcr.vsp (b-at (b-local base) 16)) s)
      (write-string (b-store wasm32::tcr.mv_base (b-local output)) s)
      (write-string (b-store wasm32::tcr.mv_owner_top "(local.get $top)") s)
      (write-string (b-store wasm32::tcr.mv_count "(i32.const 0)") s)
      (format s "(call $resolve (i32.load offset=8 (local.get ~a))) (local.set $dispatch_slot) (local.set $dispatch_self) (i32.store offset=8 (local.get ~a) (local.get $dispatch_self)) (call_indirect (type $b_entry) (i32.load offset=8 (local.get ~a)) (local.get ~a) (local.get $dispatch_slot))" base base base total)
      (write-string "(local.set $count) (local.set $value)" s)
      (write-string (b-condition "(i32.gt_u (local.get $count) (local.get $capacity))" 3) s)
      (format s "(memory.copy (local.get $results) (local.get ~a) (i32.mul (local.get $count) (i32.const 4)))" output)
      (write-string (b-store wasm32::tcr.vsp (b-local vsp)) s)
      (write-string (b-store wasm32::tcr.mv_base (b-local mv)) s)
      (write-string (b-store wasm32::tcr.mv_owner_top (b-local owner)) s)
      (write-string (b-store wasm32::tcr.mv_count (b-local old-count)) s)
      (write-string (b-store wasm32::tcr.root_head (b-local root)) s)
      (format s "(local.set $top (local.get ~a))" evaluated))))

;;; Logical callable-object proposal v1. Function fields are tagged; registry
;;; metadata is raw. Symbol layout is D1's seven-slot object. No native code
;;; vector, host pointer or name-based resolver is admitted.
(defun b-object-runtime ()
  "(func $span (param $p i32) (param $n i32)
    (if (i64.gt_u (i64.add (i64.extend_i32_u (local.get $p)) (i64.extend_i32_u (local.get $n))) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))) (then (throw $call_error (i32.const 4)))))
  (func $object_base (param $node i32) (param $bytes i32) (param $header i32) (result i32) (local $p i32)
    (if (i32.ne (i32.and (local.get $node) (i32.const 7)) (i32.const 6)) (then (throw $call_error (i32.const 4))))
    (local.set $p (i32.sub (local.get $node) (i32.const 6)))
    (call $span (local.get $p) (local.get $bytes))
    (if (i32.ne (i32.load (local.get $p)) (local.get $header)) (then (throw $call_error (i32.const 4)))) (local.get $p))
  (func $function_value (param $symbol i32) (result i32) (local $node i32)
    (local.set $node (i32.load offset=12 (call $object_base (local.get $symbol) (i32.const 32) (i32.const 1850))))
    (drop (call $object_base (local.get $node) (i32.const 24) (i32.const 1322))) (local.get $node))
  (func $resolve (param $node i32) (result i32 i32) (local $p i32) (local $id i32) (local $row i32) (local $slot i32) (local $cap i32) (local $version i32) (local $wide i64)
    (if (i32.ne (i32.and (local.get $node) (i32.const 7)) (i32.const 6)) (then (throw $call_error (i32.const 4))))
    (call $span (i32.sub (local.get $node) (i32.const 6)) (i32.const 4))
    (if (i32.eq (i32.load (i32.sub (local.get $node) (i32.const 6))) (i32.const 1850)) (then (local.set $node (call $function_value (local.get $node)))))
    (local.set $p (call $object_base (local.get $node) (i32.const 24) (i32.const 1322)))
    (local.set $id (i32.load offset=4 (local.get $p)))
    (if (i32.or (i32.and (local.get $id) (i32.const 3)) (i32.le_s (local.get $id) (i32.const 0))) (then (throw $call_error (i32.const 4))))
    (local.set $id (i32.shr_u (local.get $id) (i32.const 2)))
    (local.set $version (i32.load offset=12 (local.get $p)))
    (if (i32.or (i32.and (local.get $version) (i32.const 3)) (i32.le_s (local.get $version) (i32.const 0))) (then (throw $call_error (i32.const 4))))
    (if (i32.and (global.get $code_registry) (i32.const 7)) (then (throw $call_error (i32.const 4))))
    (call $span (global.get $code_registry) (i32.const 8))
    (local.set $cap (i32.load (global.get $code_registry)))
    (if (i32.or (i32.ge_u (local.get $id) (local.get $cap)) (i32.ne (i32.load offset=4 (global.get $code_registry)) (i32.const 1))) (then (throw $call_error (i32.const 4))))
    (local.set $wide (i64.add (i64.extend_i32_u (global.get $code_registry)) (i64.add (i64.const 8) (i64.mul (i64.extend_i32_u (local.get $id)) (i64.const 16)))))
    (if (i64.gt_u (i64.add (local.get $wide) (i64.const 16)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))) (then (throw $call_error (i32.const 4))))
    (local.set $row (i32.wrap_i64 (local.get $wide)))
    (if (i32.or (i32.ne (i32.load offset=12 (local.get $p)) (i32.load offset=4 (local.get $row))) (i32.or (i32.ne (i32.load offset=8 (local.get $row)) (i32.const 17)) (i32.ne (i32.load offset=12 (local.get $row)) (i32.const 23)))) (then (throw $call_error (i32.const 4))))
    (local.set $slot (i32.load (local.get $row)))
    (if (i32.or (i32.eqz (local.get $slot)) (i32.ge_u (local.get $slot) (table.size))) (then (throw $call_error (i32.const 4))))
    (if (ref.is_null (table.get (local.get $slot))) (then (throw $call_error (i32.const 4))))
    (local.get $node) (local.get $slot))")
