;;; The unsigned digit operations keep each half in a fixnum.
(defun %wasm-digit-less-p (ah al bh bl)
  (or (< ah bh) (and (= ah bh) (< al bl))))

(defun %wasm-divide-digit (rh rl nh nl dh dl)
  (when (or (and (zerop dh) (zerop dl))
            (not (%wasm-digit-less-p rh rl dh dl)))
    (error "Invalid digit division."))
  (let ((qh 0) (ql 0))
    (dotimes (i 32)
      (let* ((bit (if (< i 16) (if (logbitp (- 15 i) nh) 1 0)
                       (if (logbitp (- 31 i) nl) 1 0)))
             (low (+ (ash rl 1) bit)))
        (setq rh (+ (ash rh 1) (ash low -16))
              rl (logand low #xffff)
              qh (logior (ash qh 1) (ash ql -15))
              ql (logand (ash ql 1) #xffff))
        (unless (%wasm-digit-less-p rh rl dh dl)
          (let ((low (- rl dl)))
            (setq rh (+ (- rh dh) (ash low -16))
                  rl (logand low #xffff)
                  ql (logior ql 1))))))
    (values qh ql rh rl)))

(defun %floor-loop-quo (x result dh dl)
  (let ((rh 0) (rl 0))
    (do ((i (1- (uvsize x)) (1- i)))
        ((< i 0) (values rh rl))
      (multiple-value-bind (nh nl) (%bignum-ref x i)
        (multiple-value-bind (qh ql high low)
            (%wasm-divide-digit rh rl nh nl dh dl)
          (%bignum-set result i qh ql)
          (setq rh high rl low))))))

(defun %floor-loop-no-quo (x dh dl)
  (let ((rh 0) (rl 0))
    (do ((i (1- (uvsize x)) (1- i)))
        ((< i 0) (values rh rl))
      (multiple-value-bind (nh nl) (%bignum-ref x i)
        (multiple-value-bind (qh ql high low)
            (%wasm-divide-digit rh rl nh nl dh dl)
          (declare (ignore qh ql))
          (setq rh high rl low))))))

(defun %floor-99 (x xidx y yidx)
  (multiple-value-bind (rh rl) (%bignum-ref x xidx)
    (multiple-value-bind (dh dl) (%bignum-ref y yidx)
      (if (and (= rh dh) (= rl dl))
        (values #xffff #xffff)
        (multiple-value-bind (nh nl) (%bignum-ref x (1- xidx))
          (multiple-value-bind (qh ql) (%wasm-divide-digit rh rl nh nl dh dl)
            (values qh ql)))))))

(defun truncate-guess-loop (gh gl x xidx y yidx)
  (loop
    (multiple-value-bind (yh yl) (%bignum-ref y yidx)
      (multiple-value-bind (ah al bh bl) (%multiply-and-add-1 gh gl yh yl 0 0)
        (multiple-value-bind (xh xl) (%bignum-ref x (1- xidx))
          (multiple-value-bind (mh ml borrow) (%subtract-with-borrow-1 xh xl bh bl 1)
            (multiple-value-bind (xh xl) (%bignum-ref x xidx)
              (multiple-value-bind (hh hl) (%subtract-with-borrow-1 xh xl ah al borrow)
                (unless (and (zerop hh) (zerop hl))
                  (return (values gh gl)))
                (multiple-value-bind (yh yl) (%bignum-ref y (1- yidx))
                  (multiple-value-bind (ph pl qh ql) (%multiply-and-add-1 gh gl yh yl 0 0)
                    (multiple-value-bind (xh xl) (%bignum-ref x (- xidx 2))
                      (unless (or (%wasm-digit-less-p mh ml ph pl)
                                  (and (= mh ph) (= ml pl)
                                       (%wasm-digit-less-p xh xl qh ql)))
                        (return (values gh gl))))))))))))
    (multiple-value-setq (gh gl) (%subtract-one gh gl))))

(defun %fixnum-gcd (a b)
  (loop until (zerop b) do
    (multiple-value-bind (quotient remainder) (truncate a b)
      (declare (ignore quotient))
      (setq a b b remainder)))
  a)

(defun bignum-add-loop-+ (index a b length)
  (let ((carry 0))
    (dotimes (j length)
      (setq carry (%add-with-carry a index carry a index b j))
      (incf index))
    (%add-with-carry a index carry a index 0 nil))
  0)
