(in-package :ccl)
;; Registration is observed with a strongly reachable object; cancel before
;; releasing it, never invoke GC or allow the probe to schedule a callback.
(let* ((*enable-automatic-termination* nil) (object(cons 17 nil)) (calls 0)
       (fn(lambda(o)(declare(ignore o))(incf calls)))
       (before(length(population.data *termination-population*)))
       (count(hash-table-count *termination-functions*)))
 (unwind-protect
  (progn
   (assert(eq(terminate-when-unreachable object fn)fn))
   (assert(eq(termination-function object)fn))
   (assert(= (length(population.data *termination-population*)) (1+ before)))
   (assert(= (gethash fn *termination-functions*)1))
   (assert(cancel-terminate-when-unreachable object fn)))
  (cancel-terminate-when-unreachable object fn))
 (assert(= before(length(population.data *termination-population*))))
 (assert(= count(hash-table-count *termination-functions*)))
 (assert(zerop calls))
 (format t "NATIVE-REGISTRATION|register,lookup,cancel|callbacks=0|restored~%"))
(let ((pop *termination-population*))
 (format t "TERMINATION-STATE|~d|~d|~d|~s~%" (length(population.data pop))
  (length(population.termination-list pop))(hash-table-count *termination-functions*) *enable-automatic-termination*))
;; Inspect the captured specializer table itself, not just globally named tables.
(let* ((table(second(assoc 'eql-specializers-hash
                       (closure-closed-over-values(fdefinition 'intern-eql-specializer)))))
       (counts(make-hash-table :test #'equal)) (keys nil))
 (assert(hash-table-p table))(assert(eq(hash-table-test table)'eql))
 (maphash(lambda(k v)(declare(ignore v))
  (let((kind(cond((symbolp k)"symbol")((integerp k)"integer")((characterp k)"character")
    ((floatp k)"float")((rationalp k)"ratio")((complexp k)"complex")
    ((consp k)"cons")((stringp k)"string")(t(format nil "~s"(type-of k))))))
   (incf(gethash kind counts 0))
   (when (or(numberp k)(characterp k))(push(format nil "~a|~s|~s"kind(type-of k)k)keys))))table)
 (format t "EQL-TOTAL|~d~%"(hash-table-count table))
 (dolist(k(sort(loop for k being the hash-keys of counts collect k)#'string<))
  (format t "EQL-KIND|~a|~d~%"k(gethash k counts)))
 (dolist(k(sort keys #'string<))(format t "EQL-KEY|~a~%"k)))
(dolist (name '("TERMINATE-WHEN-UNREACHABLE" "CANCEL-TERMINATE-WHEN-UNREACHABLE" "TERMINATION-FUNCTION" "DRAIN-TERMINATION-QUEUE" "DO-AUTOMATIC-TERMINATION"))
 (multiple-value-bind (sym status)(find-symbol name :ccl)
  (assert(and sym(fboundp sym)))
  (format t "BINDING|~a|~a~%" name status)))
(quit)
