(in-package :wasm32-compiler)

(defun selection-function (name)
  (let ((function (gethash name *core-native-functions*)))
    (assert function)
    (setf (gethash function *accessor-function-names*) name)
    function))

(defun selection-inputs (name)
  (cond ((eq name 'core-selection-heap) (values '((nil nil) (t nil) (nil t) (t t)) t))
        ((eq name 'core-selection-error)
         (values (mapcar #'list (list nil 17 (ash 1 90) (list 1 2))) t))
        ((member name '(ccl::%%assq-combined-method-dcode
                        ccl::%%assoc-combined-method-dcode
                        core-selection-generic core-selection-rebind
                        core-selection-lexpr-eq core-selection-lexpr-eql))
         (let ((rows nil))
           (dolist (eqlp (cond ((member name '(ccl::%%assq-combined-method-dcode
                                              core-selection-lexpr-eq)) '(nil))
                             ((member name '(ccl::%%assoc-combined-method-dcode
                                              core-selection-lexpr-eql)) '(t))
                             (t '(nil t))))
             (dolist (index '(0 1))
               (let ((keys (if eqlp (list :key 17 (ash 1 90) 1.5d0)
                              (list :key 17))))
                 (dolist (key keys)
                   (dolist (which '(:first :second :missing))
                     (let* ((other :other)
                            (arg (ecase which (:first (cond ((typep key 'double-float) (ccl::%copy-float key))
                                              ((and eqlp (integerp key) (not (ccl:fixnump key)))
                                               (- (+ key 1) 1))
                                              (t key))) (:second other) (:missing :absent)))
                            (entries (list (cons key (selection-function 'core-selection-first))
                                           (cons other (selection-function 'core-selection-second))
                                           (cons key (selection-function 'core-selection-default))))
                            (stuff (cons index (cons entries (selection-function 'core-selection-default))))
                            (args (if (zerop index) (list arg) (list :prefix arg))))
                       (push (cond ((member name '(core-selection-generic core-selection-rebind))
                                    (list stuff args eqlp))
                                   ((member name '(core-selection-lexpr-eq core-selection-lexpr-eql))
                                    (cons stuff args))
                                   (t (list stuff args))) rows)))))))
           (values (nreverse rows) t)))
        (t (values nil nil))))
