    (defun core-selection-first (&rest args)
      (core-collect)
      (values :first args))
    (defun core-selection-second (&rest args)
      (core-collect)
      (values :second args))
    (defun core-selection-default (&rest args)
      (core-collect)
      (values :default args))
    (defun core-selection-generic (stuff args eqlp)
      (let ((gf (core-dispatch-make
                 (if eqlp
                   (lambda (&rest args) (ccl::%%assoc-combined-method-dcode stuff args))
                   (lambda (&rest args) (ccl::%%assq-combined-method-dcode stuff args))))))
        (core-collect)
        (multiple-value-bind (method values) (apply gf args)
          (core-collect)
          (values method values))))
    (defun core-selection-rebind (stuff args eqlp)
      (let ((gf (core-dispatch-make
                 (if eqlp
                   (lambda (&rest args) (ccl::%%assoc-combined-method-dcode stuff args))
                   (lambda (&rest args) (ccl::%%assq-combined-method-dcode stuff args))))))
        (multiple-value-bind (first first-args) (apply gf args)
          (core-dispatch-set gf #'core-selection-second)
          (core-collect)
          (multiple-value-bind (second second-args) (apply gf args)
            (values first first-args second second-args)))))
    (defun core-selection-lexpr-eq (stuff ccl::&lexpr args)
      (ccl::%%assq-combined-method-dcode stuff args))
    (defun core-selection-lexpr-eql (stuff ccl::&lexpr args)
      (ccl::%%assoc-combined-method-dcode stuff args))
    (defun core-selection-error (datum)
      (let ((effects nil))
        (handler-case
            (unwind-protect
                (ccl::signal-program-error "Dispatch ~s / ~s"
                  (progn (push :first effects) (core-collect) datum)
                  (progn (push :second effects) (core-collect) 17))
              (push :cleanup effects))
          (program-error (condition)
            (core-collect)
            (values (simple-condition-format-control condition)
                    (simple-condition-format-arguments condition) effects)))))
    (defun core-selection-heap (hitp eqlp)
      (let* ((key (cons 1 2))
             (stuff (cons 0 (cons (list (cons key #'core-selection-first))
                                 #'core-selection-default)))
             (arg (if hitp key (cons 1 2))))
        (core-collect)
        (core-selection-generic stuff (list arg) eqlp)))
