"""Native FASL comparison with explicit cross-loader edit sites.

The existing source-location comparator still checks every executable byte and
constant outside the declared definitions, apart from generated uninterned
symbol names. Numeric suffix changes retain their prefix and a file-wide
bijection. Encoded spans distinguish debug names from macro-template constants.
"""
from pathlib import Path
import copy, hashlib, importlib.util, json, re, sys, struct
from functools import lru_cache
HERE=Path(__file__).resolve().parent

@lru_cache(maxsize=1)
def base_comparator():
    # Import the already-qualified decoder, including recursive function refs.
    spec=importlib.util.spec_from_file_location('cross_native_driver',HERE.parent/'bootstrap-generic-dispatch/native.py')
    prior=importlib.util.module_from_spec(spec);spec.loader.exec_module(prior)
    import native_compare
    # The old decoder's 4096 count cap was tailored to a few files. The full
    # compiler has larger reference tables/strings. Keep a byte-length bound.
    class FullCompilerFasl(native_compare.CompilerFasl):
        def expr(self,depth=0):
            start=self.pos;value=super().expr(depth)
            if isinstance(value,str) and self.data[start]&127!=25:self.spans[id(value)]=(start,self.pos)
            return value
        def count(self):
            result=0
            for shift in range(0,35,7):
                b=self.byte();result|=(b&127)<<shift
                if b&128:
                    assert result<=len(self.data),'FASL_COUNT_BOUND'
                    return result
            raise ValueError('FASL_COUNT_BOUND')
        def decode(self):
            # U1 ASDF is 1.16 MB; the former selected-file profile stopped at 1 MB.
            assert len(self.data)<=2*1024*1024,'FASL_SIZE_BOUND'
            assert struct.unpack('>HHII',self.take(12))==(0xff00,1,12,len(self.data)-12),'FASL_HEADER'
            assert self.take(6)==bytes.fromhex('ff6200000000'),'FASL_VERSION'
            assert self.byte()==24,'FASL_TABLE'
            self.capacity=self.count();result=[]
            while self.pos<len(self.data) and self.data[self.pos]!=255:result.append(self.expr())
            assert self.byte()==255 and self.pos==len(self.data),'FASL_END'
            return result
    ns=dict(native_compare.__dict__);ns['CompilerFasl']=FullCompilerFasl
    return ns

def comparator():
    ns=dict(base_comparator())
    text=(HERE.parent/'bootstrap-admission/native_compare.py').read_text()
    text=text.replace("    assert na==nb,'native executable, non-debug constant, or ABI difference'", "    changes=check(na,nb)")
    text=text.replace("scope='Identical code bytes", "declared_changes=changes,scope='Identical code bytes")
    exec(compile(text,'native_compare.py','exec'),ns)
    ns['CompilerFasl']=base_comparator()['CompilerFasl']
    return ns

# No prefix-wide executable exemption: list the original functions changed by
# the backend boundary and the accessors generated by the appended slots.
SLOTS=['LFUN-NAME-FUNCTION','UNIFIED-DYNAMIC-SPACE','INITIALIZE-SYMBOLS-FUNCTION','IMAGE-WRITER-FUNCTION','COMPILE-FILE-FUNCTION']
INTENTIONAL={
 'lib/nfcomp.lisp':{'CCL::FASL-DUMP-DISPATCH','CCL::FASL-DUMP-WASM32-FUNCTION'},
 'xdump/xfasload.lisp':{'CCL::MAKE-BACKEND-XLOAD-INFO','CCL::COPY-BACKEND-XLOAD-INFO','CCL::XFASLOAD','CCL::XLOAD-LFUN-NAME','CCL::TARGET-XCOMPILE-DIRECTORY'} | {'CCL::BACKEND-XLOAD-INFO-'+s for s in SLOTS} | {'(SETF CCL::BACKEND-XLOAD-INFO-'+s+')' for s in SLOTS},
}

def debug_bytes(data,generated_constants=False):
    """Normalize only encoded gensym spellings in native debug symbol maps.

    This iterative path handles enormous literal encoding tables without
    traversing them recursively or discarding their bytes/identity edges.
    """
    decoder=base_comparator()['CompilerFasl'](data);rows=decoder.decode()
    seen=set();nodes=[];functions=[]
    def descend(root):
        work=[root];done=set()
        while work:
            x=work.pop()
            if isinstance(x,(list,dict)):
                if id(x) in done:continue
                done.add(id(x))
                yield x
                work.extend(x.values() if isinstance(x,dict) else x)
    from fasl import elements,symbol
    for x in descend(rows):
        if not isinstance(x,dict) or set(x)!={'function'}:continue
        f=x['function'];cs=f['constants'];bits=cs[-1]
        functions.append(hashlib.sha256(bytes.fromhex(f['code'])).hexdigest())
        if not bits & (1<<23):continue
        slot=-2 if bits & (1<<29) else -3
        props=elements(cs[slot])
        for i in range(0,len(props),2):
            if props[i]!=symbol('CCL::FUNCTION-SYMBOL-MAP'):continue
            for node in descend(props[i+1]):
                if isinstance(node,dict) and set(node)=={'uninterned'} and re.fullmatch(r'.*?[0-9]+',node['uninterned']):
                    if id(node) not in seen:seen.add(id(node));nodes.append(node)
    debug_ids=set(seen)
    if generated_constants:
        for node in descend(rows):
            if isinstance(node,dict) and set(node)=={'uninterned'} and re.fullmatch(r'.*?[0-9]+',node['uninterned']) and id(node) not in seen:
                seen.add(id(node));nodes.append(node)
    result=bytearray(data);changes=[]
    for node in nodes:
        start,end=decoder.spans[id(node)];name=node['uninterned'];encoded=name.encode('ascii')
        assert data[start:end].endswith(encoded),'debug symbol encoding'
        normalized=re.sub(r'[0-9]+$',lambda m:'0'*len(m[0]),name).encode('ascii')
        result[end-len(encoded):end]=normalized
        changes.append(dict(start=start,end=end,name=name,debug=id(node) in debug_ids))
    if generated_constants:
        names={node['uninterned'] for node in nodes}
        for row in rows:
            if 'defmacro' not in row:continue
            info=row['defmacro'][1]
            if not (isinstance(info,dict) and set(info)=={'cons'} and isinstance(info['cons'][1],dict) and set(info['cons'][1])=={'cons'}):continue
            arglist=info['cons'][1]['cons'][1]
            if not isinstance(arglist,str):continue
            def token(m):
                name=m[1]
                if name not in names:return m[0]
                return '#:'+re.sub(r'[0-9]+$',lambda n:'0'*len(n[0]),name)
            normalized=re.sub(r'#:([^ ()]+)',token,arglist)
            if normalized!=arglist:
                start,end=decoder.spans[id(arglist)];encoded=arglist.encode('ascii');assert data[start:end].endswith(encoded)
                result[end-len(encoded):end]=normalized.encode('ascii')
                changes.append(dict(start=start,end=end,name=arglist,debug=True,macro_arglist=True))
    return bytes(result),sorted(changes,key=lambda x:x['start']),functions

def compare(before,after,source_before,source_after,filename):
    if source_before==source_after:
        a,am,af=debug_bytes(before,True);b,bm,bf=debug_bytes(after,True)
        if a==b:
            assert af==bf and len(am)==len(bm)
            forward={};reverse={}
            for x,y in zip(am,bm):
                assert (x['start'],x['end'])==(y['start'],y['end'])
                assert forward.setdefault(x['name'],y['name'])==y['name'] and reverse.setdefault(y['name'],x['name'])==x['name']
            return dict(status='PASS',functions=len(af),code_sha256=af,before_sha256=hashlib.sha256(before).hexdigest(),after_sha256=hashlib.sha256(after).hexdigest(),declared_changes=dict(definitions=[],debug_gensyms=sorted(forward.items())),debug_spans=dict(before=am,after=bm),scope='Unchanged source: all encoded bytes, including FASL reference indices, identical except numeric suffixes of uninterned generated symbols. Native code, interned identities and all other data are byte-identical. Symbol spans, prefixes, debug/constant classification and bijection retained; no raw identity claim.')
    ns=comparator();retained=[];renamings=[]
    decoder=ns['CompilerFasl']
    class DeclaredDecoder(decoder):
        def decode(self):
            rows=super().decode()
            if filename!='xdump/xfasload.lisp':return rows
            source=source_before if self.data==before else source_after
            side='before' if self.data==before else 'after';result=[];declared=False
            for row in rows:
                if 'location' in row:
                    declared=False
                    location=row['location']
                    if location is not None:
                        span=location['vector']['values'][3]
                        start,length=divmod(span,1<<14) if isinstance(span,int) else (span['cons'][0],span['cons'][1]-span['cons'][0])
                        declared=source[start:start+length].lstrip().startswith('(defstruct backend-xload-info')
                # Structure metadata necessarily describes the appended slots.
                # Existing accessor code is still compared, including setters.
                if declared and 'defun' not in row and 'location' not in row:retained.append(dict(side=side,name='DEFSTRUCT BACKEND-XLOAD-INFO metadata',decoded=row))
                elif row=={'defvar-init':[{'symbol':'CCL::*XLOAD-BACKEND-STATE*'},None,None]}:retained.append(dict(side=side,name='*XLOAD-BACKEND-STATE*',decoded=row))
                else:result.append(row)
            return result
    ns['CompilerFasl']=DeclaredDecoder
    def gensyms(a,b,path):
        if isinstance(a,dict) and isinstance(b,dict) and set(a)==set(b)=={'uninterned'} and re.fullmatch(r'.*?[0-9]+',a['uninterned']) and re.fullmatch(r'.*?[0-9]+',b['uninterned']) and re.sub(r'[0-9]+$','',a['uninterned'])==re.sub(r'[0-9]+$','',b['uninterned']):
            renamings.append([a['uninterned'],b['uninterned']]);b['uninterned']=a['uninterned'];return
        if isinstance(a,list) and isinstance(b,list) and len(a)==len(b):
            for i,(x,y) in enumerate(zip(a,b)):gensyms(x,y,path+[i])
        elif isinstance(a,dict) and isinstance(b,dict) and a.keys()==b.keys():
            for k in a:gensyms(a[k],b[k],path+[k])
    def name(row):
        if 'defun' in row:
            constants=row['defun'][0]['function']['constants'];n=constants[-2]
            if isinstance(n,dict) and set(n)=={'symbol'}:return n['symbol']
            if isinstance(n,dict) and set(n)=={'cons'}:
                from fasl import elements,symbol
                parts=elements(n)
                if len(parts)==2 and parts[0]==symbol('COMMON-LISP::SETF') and set(parts[1])=={'symbol'}:
                    return '(SETF '+parts[1]['symbol']+')'
            return json.dumps(n,sort_keys=True)
        return None
    def check(a,b):
        allowed=INTENTIONAL.get(filename,set())
        def remove(rows,side):
            result=[]
            for row in rows:
                n=name(row)
                if n in allowed:
                    retained.append(dict(side=side,name=n,decoded=row));continue
                result.append(row)
            return result
        a=remove(a,'before');b=remove(b,'after')
        # Native compiler gensyms also occur in macro templates. Preserve their
        # prefix and a file-wide bijection; interned identities/code stay exact.
        gensyms(a,b,[])
        forward={};reverse={}
        for x,y in renamings:
            assert forward.setdefault(x,y)==y and reverse.setdefault(y,x)==x,'gensym bijection '+filename+' '+repr((x,y,forward.get(x),reverse.get(y)))
        if a!=b:
            first=next((i for i,(x,y) in enumerate(zip(a,b)) if x!=y),min(len(a),len(b)))
            def difference(x,y,path):
                if type(x)!=type(y):return path,x,y
                if isinstance(x,dict):
                    if x.keys()!=y.keys():return path,x.keys(),y.keys()
                    for k in x:
                        if x[k]!=y[k]:return difference(x[k],y[k],path+[k])
                if isinstance(x,list):
                    if len(x)!=len(y):return path,'length '+str(len(x)),'length '+str(len(y))
                    for i,(u,v) in enumerate(zip(x,y)):
                        if u!=v:return difference(u,v,path+[i])
                return path,x,y
            raise AssertionError('unexplained native difference '+filename+' '+str(difference(a[first],b[first],[first]))[:1600])
        accessors=[name(row) for row in a if name(row) and 'BACKEND-XLOAD-INFO-' in name(row)]
        if filename=='xdump/xfasload.lisp':assert len(accessors)==27,'existing structure accessor coverage'
        return dict(definitions=retained,debug_gensyms=sorted(forward.items()),compared_existing_accessors=accessors)
    ns['check']=check
    result=ns['compare'](before,after,source_before,source_after)
    result['scope']='Decoded code and data equal outside the separately retained shared edit sites, bounded source/debug locations, and bijectively renamed uninterned generated symbols. No whole-file code-identity claim for declared edit sites.'
    return result
