;;; Native oracle: compile and load the same source natively, then observe the
;;; same cases. Values print in the JSON shape boot.mjs decodes from the heap.
(in-package "CCL")
(defun p2-0-json (value stream)
  (cond ((null value) (write-string "null" stream))
        ((eq value t) (write-string "true" stream))
        ((integerp value) (format stream "~d" value))
        ((consp value) (write-char #\[ stream) (p2-0-json (car value) stream) (write-char #\, stream)
         (p2-0-json (cdr value) stream) (write-char #\] stream))
        ((stringp value) (format stream "{\"string\":~s}" value))
        ((symbolp value) (format stream "{\"symbol\":~s}" (concatenate 'string (package-name (symbol-package value)) "::" (symbol-name value))))
        (t (error "Unsupported observation ~s" value))))
(let ((out (getenv "LOADER_OUTPUT")))
  (dolist (name '("p2-0" "p2-0-second"))
    (let* ((*package* (find-package "CCL"))
           (source (concatenate 'string (getenv "LOADER_SOURCE") name ".lisp"))
           (fasl (compile-file source :output-file (concatenate 'string out name ".dx64fsl") :verbose nil :print nil)))
      (load fasl)))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :supersede)
    (let ((cases (with-open-file (c (concatenate 'string (getenv "LOADER_OUTPUT") "cases.lisp")) (read c))))
      (write-string "{\"status\":\"PASS\",\"observations\":[" s)
      (loop for c in cases for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (if (eq (first c) :call)
          (let ((name (find-symbol (third c) (second c))))
            (format s "{\"call\":[~s,~s],\"args\":[~{~d~^,~}],\"values\":[" (second c) (third c) (fourth c))
            (loop for v in (multiple-value-list (apply name (fourth c))) for j from 0 do
              (unless (zerop j) (write-char #\, s)) (p2-0-json v s))
            (write-string "]}" s))
          (let ((name (find-symbol (third c) (second c))))
            (format s "{\"value\":[~s,~s],\"result\":" (second c) (third c))
            (p2-0-json (symbol-value name) s) (write-char #\} s))))
      (write-string "]}" s) (terpri s))))
(quit)
