;;; Whole-file compilation. Reconstruction happens in a separate host process.
(in-package :wasm32-compiler)
(let* ((out (ccl:getenv "LOADER_OUTPUT"))
       (source "ccl:tests;wasm;stage1;loader;")
       (fasls nil)
       (variables ccl::*wasm32-xload-parameter-variables*)
       (before (mapcar #'symbol-value variables)))
  (dolist (name '("p2-0" "p2-0-second"))
    (multiple-value-bind (path modules warnings failure)
        (let ((*package* (find-package "CCL")))
          (wasm32-compile-file (concatenate 'string source name ".lisp")
                              :output-file (concatenate 'string out name ".w32fsl")))
      (declare (ignore warnings))
      (assert (not failure))
      (push path fasls)
      (format t "COMPILE-FILE-PASS ~a ~d modules~%" path (length modules))))
  (format t "FASL-PUBLICATION-PASS~%"))
(ccl:quit)
