(in-package "CL-USER")
(defun s1-tag (value)
  (cond ((null value) wasm32::canonical-nil-value)
        ((eq value t) wasm32::canonical-t-value)
        ((typep value '(signed-byte 30)) (ash value 2))
        (t (error "Smoke oracle cannot encode ~s" value))))
(let* ((out (ccl:getenv "S1_OUTPUT"))
       (host ccl::*target-backend*) (features (copy-list *features*))
       (cases '(("constant" "(lambda () 42)" (() ()))
                ("minimum" "(lambda () -536870912)" (()))
                ("maximum" "(lambda () 536870911)" (()))
                ("nil" "(lambda () nil)" (()))
                ("true" "(lambda () t)" (()))
                ("identity" "(lambda (x) x)" ((0) (-1) (nil) (t) (536870911) (-536870912)))
                ("second" "(lambda (x y) y)" ((7 9) (nil t) (t nil) (-1 0)))
                ("branch" "(lambda (x) (if x 7 9))" ((nil) (t) (0) (-1)))
                ("nested" "(lambda (x y) (if x (if y x 9) y))" ((nil nil) (nil 3) (7 nil) (7 3)))))
       (first t) (refusals 0))
  (with-open-file (s (concatenate 'string out "generated-cases.json") :direction :output :if-exists :error)
    (format s "[")
    (dolist (case cases)
      (destructuring-bind (name source inputs) case
        (let* ((native (compile nil (read-from-string source)))
               (module (wasm32-compiler::compile-module source name)))
          (unless (and (eq host ccl::*target-backend*) (equal features *features*)) (error "Target state leaked"))
          (with-open-file (w (concatenate 'string out name ".wat") :direction :output :if-exists :error)
            (write-string (getf module :wat) w))
          (with-open-file (w (concatenate 'string out name ".lisp") :direction :output :if-exists :error)
            (write-line source w))
          (dolist (args inputs)
            (unless first (format s ",")) (setq first nil)
            (let ((values (multiple-value-list (apply native args))))
              (assert (= (length values) 1))
              (format s "~%{\"name\":~s,\"arity\":~d,\"args\":[~{~d~^,~}],\"expected\":~d,\"count\":1}"
                      name (getf module :arity) (mapcar #'s1-tag args) (s1-tag (car values))))))))
    (format s "~%]~%"))
  (dolist (source '("(lambda (x) (+ x 1))" "(lambda () 536870912)"
                    "(lambda (&optional x) x)" "(lambda () \"heap\")"))
    (handler-case (progn (wasm32-compiler::compile-module source "unsupported") (error "Unsupported accepted"))
      (wasm32-compiler::unsupported-wasm32-code () (incf refusals))))
  (dolist (source '("(lambda () (typep 536870912 'fixnum))"
                    "(lambda () (typep 536870912 'bignum))"
                    "(lambda () (eql 1.0 1.0))"
                    "(lambda () (+ 2 3))"
                    "(lambda () #1=(if t #1# nil))"))
    (handler-case (progn (wasm32-compiler::compile-module source "fold-refusal") (error "Unsupported fold accepted"))
      (wasm32-compiler::unsupported-wasm32-code () (incf refusals))))
  ;; Older registration packets deliberately had no writer. The real loader
  ;; is exercised by cross-load/run.py; do not demand its retired stub refusal.
  (if (fboundp 'ccl::wasm32-fasl-function)
    (progn
      (assert (fboundp 'ccl::wasm32-cross-load))
      (assert (= refusals 9)))
    (progn
      (handler-case (progn (ccl::wasm32-cross-load) (error "Native image writer entered"))
        (wasm32-compiler::unsupported-wasm32-code (c)
          (assert (eq (wasm32-compiler::unsupported-operation c) :coordinated-heap-code-writer)) (incf refusals)))
      (assert (= refusals 10))))
  (assert (equal (ccl::target-compiler-modules :wasm32) '(ccl::wasm32-arch ccl::wasm32-backend)))
  (assert (equal (ccl::target-xload-modules :wasm32) '(ccl::xwasm32fasload ccl::xfasload)))
  (assert (eq (ccl::find-backend :wasm32) wasm32-compiler::*backend*))
  (assert (= (arch::target-nbits-in-word wasm32::*target-arch*) 32))
  (assert (= (arch::target-most-positive-fixnum wasm32::*target-arch*) 536870911))
  (assert (not (boundp 'wasm32::subprims-base)))
  (with-open-file (s (concatenate 'string out "target-checks.json") :direction :output :if-exists :error)
    (format s "{\"refusals\":~d,\"target_state_restored\":true,\"module_registration\":true}~%" refusals)))
(format t "S1-TARGET-PASS~%")
(ccl:quit)
