;;; P2-0's second sentence: enumerate the ordered level-0 inputs of
;;; CROSS-XLOAD-LEVEL-0 for wasm32 and record each file's first stop under
;;; WASM32-COMPILE-FILE. Every file is attempted; nothing is fixed here.
(in-package :wasm32-compiler)
(defun stops-json-string (string stream)
  (write-char #\" stream)
  (loop for c across string do
    (cond ((char= c #\") (write-string "\\\"" stream))
          ((char= c #\\) (write-string "\\\\" stream))
          ((< (char-code c) 32) (format stream "\\u~4,'0x" (char-code c)))
          (t (write-char c stream))))
  (write-char #\" stream))
(let* ((out (ccl:getenv "LOADER_OUTPUT"))
       (backend (ccl::find-xload-backend :wasm32))
       (files (append
               (loop for d in (ccl::backend-xload-info-subdirs backend)
                     append (sort (directory (merge-pathnames "*.lisp" d)) #'string< :key #'namestring))
               (sort (directory "ccl:level-0;*.lisp") #'string< :key #'namestring)))
       (rows nil))
  (dolist (file files)
    (let* ((name (enough-namestring file (truename "ccl:")))
           (started (get-internal-real-time))
           (row (handler-case
                    (multiple-value-bind (path modules)
                        (let ((*package* (find-package "CCL")))
                          (wasm32-compile-file file :output-file (concatenate 'string out "stops-" (pathname-name file) ".w32fsl")))
                      (declare (ignore path))
                      (list name "COMPILED" (length modules) nil nil))
                  (error (c)
                    (list name "STOP" (length *wasm32-fasl-modules*) (string (type-of c))
                          (let ((text (handler-case (format nil "~a" c) (error () "unprintable"))))
                            (subseq text 0 (min 400 (length text)))))))))
      (format t "~a ~a ~a~%" (first row) (second row) (or (fourth row) (third row)))
      (push (append row (list (round (- (get-internal-real-time) started) (/ internal-time-units-per-second 1000)))) rows)))
  (with-open-file (s (concatenate 'string out "stops.json") :direction :output :if-exists :supersede)
    (write-char #\[ s)
    (loop for (file status modules type message ms) in (reverse rows) for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (write-string "{\"file\":" s) (stops-json-string file s)
      (format s ",\"status\":~s,\"modules\":~d,\"condition\":" status modules)
      (if type (stops-json-string type s) (write-string "null" s))
      (write-string ",\"message\":" s)
      (if message (stops-json-string message s) (write-string "null" s))
      (format s ",\"milliseconds\":~d}" ms))
    (write-char #\] s) (terpri s))
  (format t "STOPS-PASS ~d files~%" (length rows)))
(ccl:quit)
