;;; Bootstrap throughput measure (Claude, 2026-09-21). Reviewer instrument, not evidence.
;;; For every top-level DEFUN in level-0 and level-1, read with the Wasm target
;;; features, ask the unchanged compiler (COMPILE-CALL-FORM) whether it admits the
;;; function, supplying every called function as a call link.
;;; Tiers: :a source as written, CCL callees linked; :b also CL functions linked;
;;; :c non-SPECIAL declarations removed; :d MACROEXPAND-ALL first; :e (THE type x) -> x.
;;; :f as :b with VALIDATE-B-SOURCE disabled (what pass 2 itself lowers); :g as :f without declarations.
;;; Also counts acode operator names that appear in wasm32-backend.lisp.
;;; Tier :e refusals are classified by what the function contains (categories overlap).
(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(in-package :ccl)
(defvar *tally* (make-hash-table :test #'equal))
(defvar *real-validate* #'wasm32-compiler::validate-b-source)
(defun set-validator (on)
 (let ((*warn-if-redefine* nil) (*warn-if-redefine-kernel* nil))
  (setf (symbol-function 'wasm32-compiler::validate-b-source) (if on *real-validate* (lambda (form) (declare (ignore form)) nil)))))
(defvar *admitted* nil)
(defvar *counter* 0)
(defvar *link-cl* nil)
(defun strip-declares (x)
 (cond ((atom x) x)
       ((eq (car x) 'quote) x)
       (t (let ((out nil))
           (loop while (consp x) do
            (let ((e (pop x)))
             (if (and (consp e) (eq (car e) 'declare))
               (let ((keep (remove-if-not (lambda (d) (and (consp d) (eq (car d) 'special))) (cdr e)))) (when keep (push (cons 'declare keep) out)))
               (push (strip-declares e) out))))
           (let ((r (nreverse out))) (when x (setf (cdr (last r)) x)) r)))))
(defvar *heads* (make-hash-table))
(defun strip-the (x) (cond ((atom x) x) ((eq (car x) 'quote) x) ((and (eq (car x) 'the) (consp (cdr x)) (consp (cddr x))) (strip-the (caddr x)))
  (t (let ((out nil)) (loop while (consp x) do (push (strip-the (pop x)) out)) (let ((r (nreverse out))) (when x (setf (cdr (last r)) x)) r)))))
(defparameter *ok-specials* '(lambda tagbody go block return-from locally function quote flet labels let let* setq if progn multiple-value-prog1 unwind-protect catch throw progv multiple-value-call))
(defun blame (form)
 (let ((seen nil))
  (labels ((walk (x)
     (cond ((and (symbolp x) x (not (eq x t)) (not (keywordp x)))
            (cond ((constantp x) (pushnew :named-constant-reference seen)) ((proclaimed-special-p x) (pushnew :special-variable-reference seen))))
           ((characterp x) (pushnew :character-literal seen))
           ((and (integerp x) (not (<= -536870912 x 536870911))) (pushnew :integer-beyond-30-bits seen))
           ((consp x)
            (if (eq (car x) 'quote)
              (let ((q (cadr x))) (cond ((and (symbolp q) q (not (eq q t)) (not (keywordp q))) (pushnew :quoted-symbol seen)) ((consp q) (pushnew :quoted-list seen))))
              (let ((h (car x)))
               (when (and (symbolp h) (or (special-operator-p h) (macro-function h)) (not (member h *ok-specials*))) (pushnew :unsupported-operator seen))
               (when (and (eq h 'setq) (symbolp (cadr x)) (proclaimed-special-p (cadr x))) (pushnew :setq-of-special seen))
               (when (eq h 'function) (when (and (consp (cadr x)) (eq (car (cadr x)) 'setf)) (pushnew :setf-function-reference seen)))
               (loop while (consp x) do (walk (pop x)))))))))
   (walk (cddr form)))
  (if seen (dolist (h seen) (incf (gethash h *heads* 0))) (incf (gethash :unclassified *heads* 0)))))
(defun expand-all (form) (or (ignore-errors (if (fboundp 'macroexpand-all) (funcall 'macroexpand-all form) (error "none"))) form))
(defun chunks (path)
 (with-open-file (s path :external-format :utf-8)
  (let ((out nil) (cur nil))
   (loop for line = (read-line s nil) while line do
    (when (and (plusp (length line)) (char= (char line 0) #\() cur) (push (format nil "~{~a~%~}" (reverse cur)) out) (setq cur nil))
    (when (or cur (and (plusp (length line)) (char= (char line 0) #\())) (push line cur)))
   (when cur (push (format nil "~{~a~%~}" (reverse cur)) out))
   (nreverse out))))
(defun link-name (sym table)
 (or (gethash sym table)
     (setf (gethash sym table)
       (let ((n (string-downcase (symbol-name sym))))
        (if (and (<= 1 (length n) 60) (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyz0123456789_-")) n)) (format nil "l_~a" n) (format nil "x~d" (incf *counter*)))))))
(defun callees (form table)
 (let ((alist nil))
  (labels ((walk (x) (when (consp x)
             (let ((h (car x)))
              (when (and (symbolp h) (fboundp h) (not (special-operator-p h)) (not (macro-function h)) (or *link-cl* (not (eq (symbol-package h) (find-package :common-lisp)))))
               (pushnew (cons h (intern (string-upcase (link-name h table)) "WASM32-COMPILER")) alist :key #'car)))
             (when (listp (cdr x)) (ignore-errors (mapc #'walk x))))))
   (walk form))
  alist))
(defun try (lambda-form)
 (let* ((table (make-hash-table)) (alist (callees lambda-form table)))
  (handler-case (progn (wasm32-compiler::compile-call-form (sublis alist lambda-form) "probe" (mapcar (lambda (p) (string-downcase (symbol-name (cdr p)))) alist)) :admitted)
   (error (e) (let ((s (princ-to-string e))) (subseq s 0 (min 90 (length s))))))))
(defun measure (dir tier)
 (let ((total 0) (ok 0) (features (append '(:wasm-target :wasm32-target :32-bit-target :little-endian-target :cross-compiling)
        (set-difference *features* (backend-target-specific-features *host-backend*)))))
  (dolist (path (directory (format nil "~a/~a/*.lisp" (getenv "BT_ROOT") dir)))
   (let ((*package* (find-package :ccl)))
    (dolist (text (chunks path))
     (let ((form (let ((*features* features)) (ignore-errors (read-from-string text)))))
      (cond ((and (consp form) (eq (car form) 'in-package)) (ignore-errors (setq *package* (find-package (cadr form)))) (unless *package* (setq *package* (find-package :ccl))))
            ((and (consp form) (eq (car form) 'defun) (symbolp (cadr form)) (listp (caddr form)))
             (incf total)
             (let ((r (let* ((*link-cl* (not (eq tier :a))) (f `(lambda ,(caddr form) ,@(cdddr form))))
                       (when (member tier '(:c :d :e :g)) (setq f (strip-declares f)))
                       (when (member tier '(:d :e)) (setq f (strip-declares (expand-all f)))) (when (eq tier :e) (setq f (strip-the f)))
                       (let ((res (try f))) (when (and (eq tier :e) (not (eq res :admitted))) (blame f)) res))))
              (if (eq r :admitted) (progn (incf ok) (push (format nil "~a:~a" dir (cadr form)) *admitted*)) (incf (gethash r *tally* 0))))))))))
  (list tier dir total ok)))
(with-open-file (o (getenv "BT_OUTPUT") :direction :output :if-exists :supersede)
 (let* ((text (with-open-file (i (format nil "~a/compiler/WASM32/wasm32-backend.lisp" (getenv "BT_ROOT"))) (let ((str (make-string (file-length i)))) (subseq str 0 (read-sequence str i)))))
        (ops (let ((k nil)) (maphash (lambda (name v) (declare (ignore v)) (when (symbolp name) (push name k))) *nx1-operators*) k))
        (hit (remove-if-not (lambda (op) (let ((n (format nil "ccl::~(~a~)" op)) (start 0) (found nil)) (loop (let ((p (search n text :start2 start :test #'char-equal))) (unless p (return)) (let ((e (+ p (length n)))) (when (or (>= e (length text)) (member (char text e) '(#\Space #\) #\Newline))) (setq found t) (return)) (setq start e)))) found)) ops)))
  (format o "acode operators defined: ~d; named in wasm32-backend.lisp: ~d~%" (length ops) (length hit)))
 (dolist (tier '(:a :b :c :d :e :f :g)) (set-validator (not (member tier '(:f :g)))) (clrhash *tally*) (setq *admitted* nil)
  (dolist (dir '("level-0" "level-1")) (format o "~s~%" (measure dir tier)))
  (let ((rows nil)) (maphash (lambda (k v) (push (cons v k) rows)) *tally*) (dolist (r (subseq (sort rows #'> :key #'car) 0 (min 8 (length rows)))) (format o "   ~6d  ~a~%" (car r) (cdr r)))))
 (let ((rows nil)) (maphash (lambda (k v) (push (cons v k) rows)) *tally*) (dolist (r (subseq (sort rows #'> :key #'car) 0 (min 14 (length rows)))) (format o "~6d  ~a~%" (car r) (cdr r))))
 (let ((rows nil)) (maphash (lambda (k v) (push (cons v k) rows)) *heads*) (format o "HEADS in refused functions (functions using it):~%") (dolist (r (subseq (sort rows #'> :key #'car) 0 (min 25 (length rows)))) (format o "   ~6d  ~s~%" (car r) (cdr r))))
 (format o "ADMITTED: ~{~a ~}~%" (reverse *admitted*)))
(quit)
