(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (native nil)
       (cases '( ("plain" (lambda (x &optional (y 7)) (values x y)))
                 ("keyword" (lambda (x &optional (y 7) &rest r &key ((:alias z) 11) &allow-other-keys) (values x y z)))
                 ("factory" (lambda (x) (lambda (&key ((:alias y) 3)) (setq x y) x)))
                 ("twins" (lambda (x) (values (lambda (&key (y 5)) (setq x y)) (lambda () x))))
                 ("separate" (lambda (x) (lambda () x)))
                 ("multi" (lambda (left right) (lambda (&optional (v left) &key ((:alias z) right)) (values left right v z))))
                 ("empty_keys" (lambda (&key) 17))
                 ("aliases" (lambda (&key ((:x a) 1) ((:x b) 2)) (values a b)))
                 ("driver" (lambda (f x) (funcall f :alias x)))
                 ("get" (lambda (f) (funcall f)))
                 ("set_y" (lambda (f x) (funcall f :y x))) )))
  (dolist (row cases)
    (let* ((name (first row)) (form (second row))
           (result (compile-metadata-call-form form name (mapcar #'first cases)))
           (fn (compile nil form))
           (specimen (cond ((member name '("factory" "separate" "twins" "multi") :test #'equal) (if (equal name "multi") (funcall fn 17 29) (funcall fn 19))) (t fn)))
           (args (multiple-value-list (ccl::function-args (ccl::closure-function specimen))))
           (keyvect (ccl::lfun-keyvect (ccl::closure-function specimen))))
      (push (vector name (coerce (subseq args 0 5) 'vector) (copy-seq (or keyvect #()))) native)
      (dolist (m (cons result (getf result :children)))
        (push m modules)
        (loop for key across (aref (aref (getf m :pool) 0) 6) do
          (pushnew (cons key (concatenate 'string (package-name (symbol-package key)) "::" (symbol-name key))) *pool-symbol-owners* :key #'car :test #'eq))
        (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
  (setq modules (nreverse modules) native (nreverse native))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"top\":~a,\"captures\":~d}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false") (getf m :captures)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (with-open-file (s (concatenate 'string out "native-metadata.json") :direction :output :if-exists :error) (write-pool-graph s native)))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-behavior.json") :direction :output :if-exists :error)
  (let* ((factory (compile nil '(lambda (x) (lambda (&key ((:alias y) 3)) (setq x y) x))))
         (twins (compile nil '(lambda (x) (values (lambda (&key (y 5)) (setq x y)) (lambda () x))))))
    (multiple-value-bind (set get) (funcall twins 19)
      (let* ((a (funcall factory 19)) (b (funcall factory 41)))
        (write-pool-graph s (list
          (vector (funcall a :alias 23) (funcall b) (funcall set :y 31) (funcall get)
                  (eq a b) (eq set get))))))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
