(in-package :wasm32-compiler)
;;; All data uses the existing graph encoder; names retain package identity.
(defun metadata-symbol (s)
  (vector (and (symbol-package s) (package-name (symbol-package s))) (symbol-name s)))
(defun metadata-arity (afunc)
  (let* ((args (ccl::acode-operands (ccl::afunc-acode afunc)))
         (keys (fourth args)))
    (vector 1 (length (first args)) (length (first (second args)))
            (not (null (third args))) (not (null keys)) (not (null (first keys)))
            (copy-seq (or (fifth keys) #())))))
(defun metadata-debug (afunc)
  (let ((entry (assoc afunc *b-functions* :test #'eq))
        (vars (cdr (assoc afunc *b-environments* :test #'eq))))
    (vector 1 (second entry)
            (coerce (loop for v in vars for i from 0 collect
                      (vector i (metadata-symbol (ccl::var-name (ccl::nx-root-var v))))) 'vector))))
(defun metadata-child-load (afunc index)
  (if (not *b-callable-metadata*) "(i32.const 77825)"
    (let ((pool (cdr (assoc afunc *pool-layouts* :test #'eq))))
      (unless (and pool (>= (length pool) 2)) (refuse :callable-metadata-pool))
      (b-wat "(i32.load offset=~d (call $object_base ~a (i32.const ~d) (i32.const ~d)))"
        (+ 4 (* 4 index)) (pool-child-load afunc)
        (* 8 (ceiling (+ 4 (* 4 (length pool))) 8)) (+ 250 (* 256 (length pool)))))))
(defun metadata-entry (afunc)
  (if (not *b-callable-metadata*) ""
    (let* ((pool (cdr (assoc afunc *pool-layouts* :test #'eq)))
           (self (temporary)) (p (temporary)) (arity (temporary)) (debug (temporary))
           (a (metadata-arity afunc)))
      (b-wat "(local.set ~a (call $object_base (i32.load offset=40 (local.get $context)) (i32.const 32) (i32.const 1578)))
        (local.set ~a (call $object_base (i32.load offset=24 (local.get ~a)) (i32.const ~d) (i32.const ~d)))
        (if (i32.or (i32.ne (i32.load offset=16 (local.get ~a)) (i32.load offset=4 (local.get ~a))) (i32.ne (i32.load offset=20 (local.get ~a)) (i32.load offset=8 (local.get ~a)))) (then (throw $call_error (i32.const 4))))
        (local.set ~a (call $object_base (i32.load offset=16 (local.get ~a)) (i32.const 32) (i32.const 2042)))
        (local.set ~a (call $object_base (i32.load offset=20 (local.get ~a)) (i32.const 16) (i32.const 1018)))
        (if (i32.or (i32.ne (i32.load offset=4 (local.get ~a)) (i32.const 4)) (i32.ne (i32.load offset=4 (local.get ~a)) (i32.const 4))) (then (throw $call_error (i32.const 4))))
        (if (i32.or (i32.ne (i32.load offset=8 (local.get ~a)) (i32.const ~d)) (i32.ne (i32.load offset=12 (local.get ~a)) (i32.const ~d))) (then (throw $call_error (i32.const 4))))"
        self p self (* 8 (ceiling (+ 4 (* 4 (length pool))) 8)) (+ 250 (* 256 (length pool)))
        self p self p arity self debug self arity debug arity (* 4 (aref a 1)) arity (* 4 (aref a 2))))))
(defun compile-metadata-call-form (form name links)
  (let ((*b-callable-metadata* t)) (compile-call-form form name links)))
(defun compile-metadata-call-module (source name links)
  (let ((*b-callable-metadata* t)) (compile-call-module source name links)))
