;;; The boot phase is complete before this file loads. Serialization cannot
;;; execute in a cold initializer or in a temporarily unbound helper's window.
(in-package :cl-user)

(defun export-boot-census (&key after-export)
  (unless (boundp 'ccl::*boot-census-state*) (error "Missing boot observation"))
  (let* ((state (ccl::%sym-global-value 'ccl::*boot-census-state*))
         (events (reverse (third state)))
         (identities (make-hash-table :test #'eq)) (next-id 0)
         (bindings (make-hash-table :test #'eq))
         (descriptions (make-hash-table :test #'eql))
         (output (ccl:getenv "CCL_BOOT_CENSUS_OUTPUT")))
    (assert (and (= (length state) 7) (not (first state)) (not (fifth state))))
    (assert (= (length events) (second state)))
    (labels ((id (x)
               (or (gethash x identities) (setf (gethash x identities) (incf next-id))))
             (object (&rest args) (apply #'ccl-startup-census::object args))
             (describe-value (x)
               (let ((i (id x)))
                 (unless (gethash i descriptions)
                   (setf (gethash i descriptions)
                         (cond
                           ((eq x ccl::%unbound-function%) (object "id" i "kind" "unbound-function"))
                           ((symbolp x)
                            (object "id" i "kind" "symbol" "name" (symbol-name x)
                                    "package" (if (symbol-package x) (package-name (symbol-package x)) :null)))
                           ((functionp x)
                            (let ((note (ccl:function-source-note x)))
                              (object "id" i "kind" "function" "code" (id (ccl::closure-function x))
                                      "name" (ccl-startup-census::label-of (ccl:function-name x))
                                      "source" (if note (ccl-startup-census::label-of (ccl::source-note-filename note)) :null)
                                      "position" (if note (ccl::source-note-start-pos note) :null))))
                           (t (object "id" i "kind" "opaque" "type" (ccl-startup-census::label-of (type-of x)))))))
                 i))
             (payload (kind args)
               (case kind
                 (:boot-start (object "queued" (mapcar #'describe-value (first args)) "startup_file" (second args)))
                 ((:cold-enter :cold-return :call-enter :call-return)
                  (object "function" (describe-value (first args))))
                 ((:load-enter :load-return)
                  (object "file" (first args) "table" (id (second args))))
                 (:reader-enter
                  (object "file" (first args) "offset" (second args) "opcode" (third args)
                          "reader" (describe-value (fourth args)) "table" (id (fifth args))))
                 (:reader-return (object "reader" (describe-value (first args))))
                 ((:binding-installed :binding-removing)
                  (setf (gethash (first args) bindings) t)
                  (object "symbol" (describe-value (first args)) "old" (describe-value (second args))
                          "new" (describe-value (third args))))
                 (:handoff (object "phase" "normal-toplevel"))
                 (t (error "Unknown boot event ~s" kind)))))
      (with-open-file (stream output :direction :output :if-exists :error :external-format :utf-8)
        (flet ((emit (row) (ccl-startup-census::json row stream) (terpri stream)))
          (emit (object "version" 1 "kind" "capture" "events" (length events)
                        "owner_thread_only" :true "foreign_thread_observed" :false
                        "original_cold_queue" (mapcar #'describe-value (sixth state))
                        "initial_bindings" (mapcar (lambda (pair)
                          (object "symbol" (describe-value (car pair)) "value" (describe-value (cdr pair))))
                          (reverse (seventh state)))
                        "descriptor_time" "After L1 handoff, image save/restore; retained object references carry identity, not historical mutable metadata."))
          (dolist (event events)
            (emit (object "version" 1 "kind" (string-downcase (symbol-name (second event)))
                          "sequence" (first event) "payload" (payload (second event) (third event))))))
        (let ((final nil))
          (maphash (lambda (name _)
                     (declare (ignore _))
                     (push (object "symbol" (describe-value name)
                                   "value" (describe-value (or (fboundp name) ccl::%unbound-function%))) final)) bindings)
          (ccl-startup-census::json (object "version" 1 "kind" "final-bindings" "bindings" (nreverse final)) stream)
          (terpri stream))
        (loop for i from 1 to next-id for row = (gethash i descriptions) when row do
          (ccl-startup-census::json (object "version" 1 "kind" "object" "object" row) stream) (terpri stream))
        (ccl-startup-census::json (object "version" 1 "kind" "complete" "events" (length events)
                                        "identities" next-id "described_objects" (hash-table-count descriptions)) stream)
        (terpri stream))
      ;; Optional post-export inspection shares the established object IDs.
      ;; It cannot renumber or add records to the already closed legacy stream.
      (when after-export
        (funcall after-export identities descriptions #'describe-value #'id next-id)))
    (format t "BOOT-CENSUS-EXPORTED ~d~%" (length events))))
