;;; Each entry rejects a missing or extra operand at the new accessor boundary.
(in-package "WASM32-COMPILER")
(let* ((out (ccl:getenv "LOADER_OUTPUT"))
       (source "ccl:tests;wasm;stage1;loader-level0;definition-control.lisp")
       (fasl (concatenate 'string out "definition-control.w32fsl"))
       (rows nil))
  (dolist (name '(ccl::%wasm-function-bits ccl::lfun-bits))
    (dolist (arguments '(nil (a b c)))
      (with-open-file (s source :direction :output :if-exists :supersede)
        (let ((*package* (find-package "CCL")))
          (write '(in-package "CCL") :stream s) (terpri s)
          (write `(defun ccl::loader-invalid-bits (a b c)
                    (declare (ignorable a b c)) (,name ,@arguments)) :stream s)))
      (let ((reason
              (handler-case
                  (progn (wasm32-compile-file source :output-file fasl) nil)
                (unsupported-wasm32-code (condition) (unsupported-operation condition)))))
        (assert (eq reason :function-bits-arity))
        (push (list :object (cons "name" (symbol-name name))
                    (cons "arguments" (length arguments))
                    (cons "reason" (string reason))) rows))))
  (with-open-file (s (concatenate 'string out "compiler-controls.json")
                     :direction :output :if-exists :supersede)
    (ccl::wasm32-json (reverse rows) s) (terpri s)))
