;;; Witnesses call the loaded definition cells, including intrinsics' bodies.
(in-package "CCL")

(defun loader-def-add (x) (+ x 17))
(defun loader-def-sub (x) (- x 9))

(defun loader-def-bindings ()
  (let ((name 'loader-def-scratch))
    (funcall (symbol-function '%unfhave) name)
    (let ((absent (null (funcall (symbol-function 'fboundp) name))))
      (funcall (symbol-function '%fhave) name #'loader-def-add)
      (values absent
              (eq (funcall (symbol-function 'fboundp) name) #'loader-def-add)
              (funcall name 5)
              (funcall (symbol-function '%unfhave) name)
              (funcall (symbol-function '%unfhave) name)
              (null (funcall (symbol-function 'fboundp) name))))))

(defun loader-def-names ()
  (let ((fn #'loader-def-add))
    (values (eq (function-name fn) 'loader-def-add)
            (eq (lfun-name fn 'loader-def-renamed) 'loader-def-add)
            (eq (function-name fn) 'loader-def-renamed)
            (eq (lfun-name fn 'loader-def-add) 'loader-def-renamed)
            (eq (function-name fn) 'loader-def-add))))

(defun loader-def-bits ()
  (let* ((fn #'loader-def-add)
         (read-bits (symbol-function 'lfun-bits))
         (bits (funcall read-bits fn)))
    (values (typep bits 'fixnum)
            (= bits (funcall read-bits fn nil))
            (= bits (lfun-bits fn nil))
            (= (ldb $lfbits-numreq bits) 1))))

(defun loader-def-macros ()
  (let ((name 'loader-def-macro))
    (%macro-have name #'loader-def-add)
    (values (not (null (fboundp name)))
            (not (special-operator-p name))
            (eq (macro-function name) #'loader-def-add)
            (progn (%fhave name (vector nil 'loader-def-special))
                   (special-form-p name))
            (%unfhave name))))

(defun loader-def-specials ()
  (let* ((name 'loader-def-special-variable)
         (before (%symbol-bits name)))
    (unwind-protect
         (values (%proclaim-special name t)
                 (logbitp $sym_vbit_special (%symbol-bits name))
                 (%proclaim-special name))
      (%symbol-bits name before))))

(defun loader-def-setf-names ()
  (values (setf-function-name-p '(setf loader-def-add))
          (setf-function-name-p 'loader-def-add)
          (setf-function-name-p '(setf))
          (setf-function-name-p '(setf loader-def-add extra))
          (setf-function-name-p '(setf 3))
          (setf-function-name-p '(car loader-def-add))
          (eq (validate-function-name 'loader-def-add) 'loader-def-add)))

(defun loader-def-bootstrap ()
  (let ((name 'loader-def-scratch))
    (values (eq (bootstrapping-fset name #'loader-def-sub) #'loader-def-sub)
            (funcall name 5)
            (eq (fset-symbol name #'loader-def-add) #'loader-def-add)
            (funcall name 5)
            (eq (bootstrapping-fmakunbound name) name)
            (null (fboundp name))
            (bootstrapping-record-source-file name)
            (encapsulated-function-name #'loader-def-add))))

(defun loader-def-allocation ()
  (let ((fn #'loader-def-add))
    (dotimes (i 200)
      (lfun-name fn (cons 'loader-name i)))
    (let ((name (lfun-name fn)))
      (lfun-name fn 'loader-def-add)
      (values (eq (car name) 'loader-name) (cdr name)
              (eq (function-name fn) 'loader-def-add)))))

(defun loader-float-signs ()
  (values (= (float-sign -2.0d0) -1.0d0)
          (= (float-sign 2.0s0) 1.0s0)
          (= (float-sign -0.0d0 3.0d0) -3.0d0)
          (= (%double-float-abs -3.0d0) 3.0d0)
          (= (%short-float-abs -3.0s0) 3.0s0)
          (%double-float-minusp -0.0d0)
          (%short-float-minusp -0.0s0)))

(defun loader-float-decode ()
  (multiple-value-bind (fraction exponent sign) (decode-float -12.0d0)
    (multiple-value-bind (small small-exponent small-sign) (decode-float 0.75s0)
      (values (= fraction 0.75d0) exponent (= sign -1.0d0)
              (= small 0.75s0) small-exponent (= small-sign 1.0s0)
              (float-precision 12.0d0) (float-precision 0.75s0)))))

(defun loader-float-scale ()
  (values (= (scale-float 1.5d0 12) 6144.0d0)
          (= (scale-float -12.0d0 -4) -0.75d0)
          (= (scale-float 1.5s0 12) 6144.0s0)
          (= (scale-float -12.0s0 -4) -0.75s0)))

(defun loader-float-copy ()
  (let* ((original -12.5d0) (copy (%copy-float original)))
    (values (= copy original) (not (eq copy original))
            (= (%double-float 17) 17.0d0)
            (= (%short-float 17) 17.0s0)
            (nan-or-infinity-p 17.0d0) (infinity-p 17.0s0))))

(defun loader-error-strings ()
  (values (length *error-format-strings*)
          (cdr (assq 1 *error-format-strings*))
          (cdr (assq 121 *error-format-strings*))
          (cdr (assq 200 *error-format-strings*))))

(defun loader-def-funcallable-bits ()
  (let* ((fn #-wasm32-target (make-instance 'standard-generic-function)
             #+wasm32-target
             (%wasm-make-funcallable-instance
              #'loader-def-add (vector nil nil nil nil nil 0 0)))
         (accessor (symbol-function 'lfun-bits))
         (old (funcall accessor fn))
         (new (logxor old #x400)))
    (values (= old (funcall accessor fn new))
            (= new (funcall accessor fn))
            (= new (lfun-bits fn nil))
            (= new (lfun-bits fn old))
            (= old (funcall accessor fn)))))

(defun loader-float-subnormal (kind)
  (let ((number (case kind
                  (0 least-positive-double-float)
                  (1 least-positive-normalized-double-float)
                  (2 #.(- least-positive-double-float))
                  (3 least-positive-single-float)
                  (4 least-positive-normalized-single-float)
                  (5 #.(- least-positive-single-float))
                  (6 0.0d0)
                  (7 -0.0d0)
                  (8 0.0s0)
                   (9 -0.0s0)
                   (10 (scale-float 1.0d0 -1030)))))
    (multiple-value-bind (fraction exponent sign) (decode-float number)
      (values (= fraction 0.5) exponent (= sign -1.0)
              (float-precision number) (zerop fraction)))))

(defun loader-def-definition ()
  (let ((fn #'loader-def-add))
    (%unfhave 'loader-def-add)
    (values (eq (%defun fn) 'loader-def-add)
            (eq (fboundp 'loader-def-add) fn)
            (loader-def-add 5))))

(defun loader-def-hold-name ()
  (lfun-name #'loader-def-add (cons 'loader-name 21))
  t)

(defun loader-def-release-name ()
  (let ((name (lfun-name #'loader-def-add)))
    (lfun-name #'loader-def-add 'loader-def-add)
    (values (eq (car name) 'loader-name) (cdr name)
            (eq (function-name #'loader-def-add) 'loader-def-add))))

#+wasm32-target
(defvar *loader-def-cleanups* 0)

#+wasm32-target
(defun loader-def-boundary (operation)
  (let ((%handlers% nil))
    (unwind-protect
         (case operation
           (0 (nth-catch-frame-tag 0))
           (1 (funcall (symbol-function 'lfun-bits) #'loader-def-add 0)))
      (incf *loader-def-cleanups*))))
