(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("gc_time" (lambda (op ptr symbol done) (multiple-value-prog1 (set symbol (funcall op ptr 0 nil)) (rplaca done 501))))
                ("gc_bytes" (lambda (op ptr symbol done) (multiple-value-prog1 (set symbol (funcall op ptr 1 nil)) (rplaca done 502))))
                ("gc_cleanup" (lambda (fn op ptr symbol done) (unwind-protect (funcall fn op ptr symbol done) (rplaca done 503))))
                ("gc_joined" (lambda (timefn bytesfn optime opbytes pt pb st sb done) (funcall timefn optime pt st done) (funcall bytesfn opbytes pb sb done) (values (symbol-value st) (symbol-value sb)))))))
 (with-open-file(s(concatenate 'string out "native.json") :direction :output :if-exists :error)
  (write-char #\[ s)
  (loop for (symbol position size) in '((ccl::*total-gc-microseconds* 11356 80) (ccl::*total-bytes-freed* 11746 8)) for i from 0 do
   (unless(zerop i)(write-char #\, s))
   (let* ((*package*(find-package "CCL")) (form(with-open-file(f "level-1/l1-init.lisp")(file-position f position)(read f)))
          (matches(remove-if-not(lambda(f)(eq(ccl::function-name f)symbol))ccl::*lisp-system-pointer-functions*)) (pointers nil)(saved(symbol-value symbol)))
    (assert(and(eq(first form)'ccl::defloadvar)(eq(second form)symbol)(= (length matches)1)))
    (if(zerop i)
     (assert(equal(third form)'(let* ((ccl::timeval-size 16)(ccl::p(ccl::malloc(* 5 ccl::timeval-size))))(#_memset ccl::p 0 (* 5 ccl::timeval-size))ccl::p)))
     (assert(equal(third form)'(let* ((ccl::p(ccl::malloc 8)))(setf(ccl::%get-long ccl::p 0)0(ccl::%get-long ccl::p 4)0)ccl::p))))
    (unwind-protect
     (progn
      (dotimes(round 2)
       (let* ((answer(multiple-value-list(funcall(first matches))))(p(first answer)))
        (assert(= (length answer)1))(assert(typep p 'ccl:macptr))(push p pointers)
        (assert(eq p(symbol-value symbol)))
        (dotimes(j size)(assert(zerop(ccl::%get-unsigned-byte p j))))
        (when(cdr pointers)(assert(/= (ccl::%ptr-to-int p)(ccl::%ptr-to-int(second pointers)))))
        (dotimes(j size)(setf(ccl::%get-unsigned-byte p j)165)))))
     (set symbol saved)(dolist(p pointers)(ccl::free p)))
    (format s "{\"name\":~s,\"bytes\":~d,\"zero\":true,\"published_identity\":true,\"fresh_twice\":true}" (symbol-name symbol) size)))
  (write-char #\] s))
 (dolist(row cases)
  (let((m(compile-call-form(second row)(first row)(mapcar #'first cases))))
   (assert(null(getf m :children)))(push m modules)
   (with-open-file(s(concatenate 'string out(first row)".wat") :direction :output :if-exists :error)(write-string(getf m :wat)s))))
 (setq modules(nreverse modules))
 (with-open-file(s(concatenate 'string out"modules.json") :direction :output :if-exists :error)
  (write-char #\[ s)(loop for m in modules for i from 0 do(unless(zerop i)(write-char #\, s))(format s "{\"name\":~s}"(getf m :name)))(write-char #\] s))
 (with-open-file(s(concatenate 'string out"pools.json") :direction :output :if-exists :error)(write-pool-graph s(mapcar(lambda(m)(getf m :pool))modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
