(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("symbol_call" (lambda (op a b c) (funcall op a b c)))
                ("symbol_values" (lambda (op a b c) (multiple-value-bind (v p) (funcall op a b c) (values v p))))
                ("symbol_preserve" (lambda (op a b c) (multiple-value-prog1 (funcall op a b c) (eq a b))))
                ("symbol_apply" (lambda (op a b c) (apply op (cons a (cons b (cons c nil))))))
                ("symbol_dynamic" (lambda (op receiver a b c) (multiple-value-call receiver (funcall op a b c))))
                ("symbol_indirect" (lambda (op receiver a b c) (multiple-value-call receiver (if a (funcall op a b c) (funcall op nil b c)))))
                ("symbol_receiver" (lambda (&optional a b) (values a b)))
                ("symbol_bind_pair" (lambda (a b x y) (progv (cons a (cons b nil)) (cons x (cons y nil)) (values (symbol-value a) (symbol-value b)))))
                ("symbol_eq" (lambda (a b) (eq a b)))
                ("symbol_read" (lambda (a) (symbol-value a)))
                ("symbol_write" (lambda (a b) (set a b)))
                ("symbol_bind" (lambda (a b) (progv (cons a nil) (cons b nil) (symbol-value a))))
                ("symbol_repeat_bind" (lambda (a b c) (progv (cons a (cons a nil)) (cons b (cons c nil)) (symbol-value a)))))))
 (dolist (row cases)
  (let ((result (compile-call-form (second row) (first row) (mapcar #'first cases))))
   (dolist (m (cons result (getf result :children)))
    (push m modules)
    (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
