(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("gctime_port" (lambda (snapshot owner) (let ((v (funcall snapshot owner nil nil))) (values (svref v 0) (svref v 1) (svref v 2) (svref v 3) (svref v 4)))))
                ("gctime_cleanup" (lambda (fn snapshot owner done) (unwind-protect (funcall fn snapshot owner) (rplaca done 611))))
                ("gctime_receiver" (lambda (a b c d e) (values a b c d e)))
                ("gctime_dynamic" (lambda (fn receiver snapshot owner) (multiple-value-call receiver (funcall fn snapshot owner))))
                ("gctime_retained" (lambda (fn snapshot owner collect) (multiple-value-prog1 (funcall fn snapshot owner) (funcall collect owner nil nil))))
                ("gctime" (lambda () (locally (declare (special statistics_descriptor)) (let ((v (gctime_snapshot statistics_descriptor nil nil))) (values (svref v 0) (svref v 1) (svref v 2) (svref v 3) (svref v 4))))))
                ("gctime_named_caller" (lambda () (gctime)))
                )))
 (with-open-file(s(concatenate 'string out "native.json") :direction :output :if-exists :error)
  (write-char #\[ s)
  (loop for micros in '(0 1 499 500 501 1499 1500 1501 2500 999499 999500 1000500 536870911000 536870912000 4294967296000 9223372036854775807000) for i from 0 do
   (unless(zerop i)(write-char #\, s))
   (let ((saved ccl::*total-gc-microseconds*) (buffer (ccl::malloc 80)))
    (unwind-protect
     (progn
      (setq ccl::*total-gc-microseconds* buffer)
      (#_memset ccl::*total-gc-microseconds* 0 80)
      (multiple-value-bind (seconds usecs) (floor micros 1000000)
       (dotimes(j 2)(let((p(ccl::%inc-ptr ccl::*total-gc-microseconds* (* j 16))))
        (setf(ccl::pref p :timeval.tv_sec)seconds(ccl::pref p :timeval.tv_usec)usecs))))
      (let((v(multiple-value-list(ccl:gctime))))
       (assert(= (length v)5))
       (format s "{\"microseconds\":\"~d\",\"units\":~d,\"values\":[~{\"~d\"~^,~}],\"milliseconds\":[~{\"~d\"~^,~}]}" micros cl:internal-time-units-per-second v (loop for j below 5 collect (ccl::timeval->milliseconds (ccl::%inc-ptr buffer (* j 16)))))))
     (setq ccl::*total-gc-microseconds* saved) (ccl::free buffer))))
  (write-char #\] s))
 (dolist(row cases)
  (let((m(compile-call-form(second row)(first row)(cons "gctime_snapshot" (mapcar #'first cases)))))
   (assert(null(getf m :children)))(push m modules)
   (with-open-file(s(concatenate 'string out(first row)".wat") :direction :output :if-exists :error)(write-string(getf m :wat)s))))
 (setq modules(nreverse modules))
 (with-open-file(s(concatenate 'string out"modules.json") :direction :output :if-exists :error)
  (write-char #\[ s)(loop for m in modules for i from 0 do(unless(zerop i)(write-char #\, s))(format s "{\"name\":~s}"(getf m :name)))(write-char #\] s))
 (with-open-file(s(concatenate 'string out"pools.json") :direction :output :if-exists :error)(write-pool-graph s(mapcar(lambda(m)(getf m :pool))modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
