(in-package :cl-user)
(ccl:set-fpu-mode :rounding-mode :nearest :invalid t :division-by-zero t :overflow t :underflow nil :inexact nil)
(defun measure-native (fn a b duration)
 (declare (optimize (safety 1) (speed 1) (debug 1)))
 (let ((start (get-internal-real-time)) (bytes (ccl::total-bytes-allocated)) (gc (ccl::gctime)) (calls 0) (last nil) (elapsed 0))
  (loop
   (dotimes (i 1024) (setf last (funcall fn a b)))
   (incf calls 1024)
   (setq elapsed (- (get-internal-real-time) start))
   (when (>= elapsed (* duration internal-time-units-per-second)) (return)))
  (values (* 1d9 (/ elapsed internal-time-units-per-second calls 64)) calls last elapsed
          (- (ccl::total-bytes-allocated) bytes) (- (ccl::gctime) gc))))
(let* ((directory (ccl:getenv "COST_DIR"))
       (forms (with-open-file (f (concatenate 'string directory "/native-forms.lisp")) (read f)))
       (functions (mapcar (lambda (r) (list (first r) (compile nil (second r)))) forms)))
 (with-open-file (*standard-output* (concatenate 'string directory "/native-disassembly.txt") :direction :output :if-exists :supersede)
  (dolist (r functions) (format t "~%FUNCTION ~a~%" (first r)) (disassemble (second r))))
 (with-open-file (out (concatenate 'string directory "/native.tsv") :direction :output :if-exists :supersede)
  (format out "workload trial ns-per-source-operation calls result ticks bytes gc-ticks~%")
  (dolist (r functions)
   (let ((a (if (string= (first r) "mixed") 7 1.5d0)))
    (measure-native (second r) a 2d0 0.5d0)
    (dotimes (trial 10)
     (multiple-value-bind (ns calls result ticks bytes gc) (measure-native (second r) a 2d0 0.2d0)
      (assert (= result (cond ((string= (first r) "add") 3.5d0) ((string= (first r) "sub") -0.5d0) ((string= (first r) "mul") 3d0) ((string= (first r) "div") 0.75d0) ((string= (first r) "single") 1.5s0) (t 9d0))))
      (format out "~a ~d ~,5f ~d ~s ~d ~d ~d~%" (first r) trial ns calls result ticks bytes gc)))))))
(format t "NATIVE-COST-PASS~%")
(ccl:quit)
