(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (native nil)
       (cases (with-open-file (s (merge-pathnames "runtime.lisp" *load-pathname*)) (second (read s)))))
  (dolist (row cases)
    (let* ((name (first row)) (form (second row))
           (result (compile-integer-call-form form name (append (mapcar #'first cases) '("gd_condition" "gd_condition_gf" "gd_condition_args"))))
           (fn (compile nil form))
           (specimen fn)
           (args (multiple-value-list (ccl::function-args (ccl::closure-function specimen))))
           (keys (ccl::lfun-keyvect (ccl::closure-function specimen))))
      (push (vector name (coerce (subseq args 0 5) 'vector) (copy-seq (or keys #()))) native)
      (dolist (m (cons result (getf result :children)))
        (push m modules)
        (loop for key across (aref (aref (getf m :pool) 0) 6) do
          (pushnew (cons key (concatenate 'string (package-name (symbol-package key)) "::" (symbol-name key))) *pool-symbol-owners* :key #'car :test #'eq))
        (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
  (setq modules (nreverse modules) native (nreverse native))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"top\":~a,\"captures\":~d}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false") (getf m :captures)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (with-open-file (s (concatenate 'string out "native-metadata.json") :direction :output :if-exists :error) (write-pool-graph s native)))
(let* ((rows (with-open-file (s (merge-pathnames "runtime.lisp" *load-pathname*)) (second (read s))))
        (functions (mapcar (lambda (row) (cons (first row) (compile nil (second row)))) rows))
        (cases (with-open-file (s (merge-pathnames "cases.lisp" *load-pathname*)) (read s))))
 (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-results.txt") :direction :output :if-exists :error)
  (dolist (c cases) (format s "~{~d~^,~}~%" (multiple-value-list (apply (cdr (assoc (first c) functions :test #'equal)) (second c)))))))

(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "source-refusals.txt") :direction :output :if-exists :error)
 (dolist (form '((lambda (a) (+ a)) (lambda (a) (- a)) (lambda (a) (+ a 1 2))
                 (lambda (a) (floor a 3)) (lambda () (function +)) (lambda (a) (truncate a))))
  (let ((refused nil))
   (handler-case (compile-integer-call-form form "refused" nil)
    (error (e) (setq refused t) (format s "~a~%" e)))
   (unless refused (error "Numeric source escaped: ~s" form)))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
