;;; Native checkpoint observation only. All IDs belong to this fresh session.
(defpackage :ccl-dispatch-registry (:use :cl)
  (:import-from :ccl-startup-census #:object #:json))
(in-package :ccl-dispatch-registry)

(defvar *identities* (make-hash-table :test #'eq))
(defvar *next-id* 0)
(defvar *functions* nil)
(defvar *function-set* (make-hash-table :test #'eq))

(defun oid (value)
  (or (gethash value *identities*)
      (setf (gethash value *identities*) (incf *next-id*))))

(defun name-data (value)
  ;; Never print a method/class object through PRINT-OBJECT during a snapshot.
  (cond ((null value) :null)
        ((symbolp value) (object "symbol" (symbol-name value)
                                "package" (if (symbol-package value)
                                            (package-name (symbol-package value)) :null)))
        ((consp value) (mapcar #'name-data value))
        ((stringp value) value)
        (t (object "opaque_name" :true))))

(defun name-key (value)
  (with-output-to-string (s) (json (name-data value) s)))

(defun fn (value)
  (unless (functionp value) (error "REGISTRY-NONFUNCTION"))
  (unless (gethash value *function-set*)
    (setf (gethash value *function-set*) t)
    (push value *functions*))
  (oid value))

(defun function-records ()
  (let ((rows nil))
    (loop while *functions* for f = (pop *functions*) do
      (let* ((prototype (ccl::closure-function f))
             (note (ccl:function-source-note f)))
        (push (object "id" (oid f) "prototype" (fn prototype)
                      "name" (name-data (ccl:function-name f))
                      "bits" (ccl::lfun-bits f)
                      "source" (if note (namestring (ccl:source-note-filename note)) :null)
                      "position" (if note (ccl:source-note-start-pos note) :null)) rows)))
    (sort rows #'< :key (lambda (r) (field r "id")))))

(defun field (record key)
  (loop for (k v) on (cdr record) by #'cddr when (string= k key) return v))

(defun method-record (method gf)
  (unless (ccl::standard-method-p method) (error "REGISTRY-NONSTANDARD-METHOD"))
  (let ((owner (ccl::%method.gf method)))
    (unless (eq owner gf) (error "REGISTRY-METHOD-OWNER"))
    (object "id" (oid method) "owner" (oid owner)
            "function" (fn (ccl::%method.function method))
            "qualifiers" (mapcar #'name-data (ccl::%method.qualifiers method))
            "specializers" (mapcar #'oid (ccl::%method.specializers method)))))

(defun snapshot (gf)
  (unless (ccl::standard-generic-function-p gf) (error "REGISTRY-NONSTANDARD-GF"))
  (let* ((methods (copy-list (ccl::%gf-methods gf)))
         (dcode (ccl::%gf-dcode gf))
         (dt (ccl::%gf-dispatch-table gf))
         (combination (ccl::%gf-method-combination gf)))
    (object "status" "INITIALIZED" "gf" (fn gf) "name" (name-data (ccl::sgf.name gf))
            "bits" (ccl::lfun-bits gf)
            "native_standard_gf" :true
            "wrapper" (oid (ccl::gf.instance.class-wrapper gf))
            "slots_owner_matches" (if (eq gf (ccl::%svref (ccl::gf.slots gf) 0)) :true :false)
            "dcode" (fn dcode) "dispatch_table" (oid dt)
            "dispatch_argnum" (ccl::%gf-dispatch-table-argnum dt)
            "precedence" (copy-list (ccl::%gf-dispatch-table-precedence-list dt))
            "combination" (oid combination)
            "standard_combination" (if (eq combination ccl::*standard-method-combination*) :true :false)
            "methods" (mapcar (lambda (m) (method-record m gf)) methods))))

(defun current-p (old gf)
  ;; This is a sequential checkpoint comparison, NOT a concurrent cache guard
  ;; or a proof that class/method-combination internals cannot change.
  (equal old (snapshot gf)))

(defun registry-snapshot ()
  (let* ((population (copy-list (ccl::population-data ccl::%all-gfs%)))
         (seen (make-hash-table :test #'eq))
         (entries (sort population #'string< :key (lambda (f) (name-key (ccl:function-name f)))))
         (rows nil))
    (dolist (gf entries)
      (when (gethash gf seen) (error "REGISTRY-DUPLICATE-GF"))
      (setf (gethash gf seen) t)
      (unless (ccl::standard-generic-function-p gf) (error "REGISTRY-NONSTANDARD-GF"))
      (let ((unbound (loop for slot in (list ccl::sgf.name ccl::sgf.methods ccl::sgf.method-combination)
                           when (eq (ccl::%svref (ccl::gf.slots gf) slot) (ccl::%slot-unbound-marker))
                           collect slot)))
        (push (if unbound
                (object "status" "UNINITIALIZED" "gf" (fn gf)
                        "name" (name-data (ccl:function-name gf))
                        "unbound_slots" unbound "bits" (ccl::lfun-bits gf)
                        "native_standard_gf" :true)
                (snapshot gf)) rows)))
    (nreverse rows)))

(defun call-record (gf argument)
  (handler-case
      (object "status" "RETURN" "values" (multiple-value-list (funcall gf argument)) "condition" :null)
    (error (c) (object "status" "ERROR" "values" nil "condition" (name-data (type-of c))))))

(defun probes ()
  ;; Symbols, generic functions and methods are private to this disposable
  ;; process. U1's actual ENSURE-GENERIC-FUNCTION/DEFMETHOD/REMOVE-METHOD run.
  (let ((gf (ensure-generic-function 'route :lambda-list '(x)))
        (steps nil) (checks nil))
    (labels ((step-at (name argument)
               (let* ((before (snapshot gf)) (call (call-record gf argument))
                      (after (snapshot gf)))
                 (push (object "name" name "before" before "call" call "after" after) steps)
                 after))
             (change (name thunk argument)
               (let ((old (snapshot gf)))
                 (funcall thunk)
                 (let ((same (current-p old gf)))
                   (when same (error "REGISTRY-STALE-STATE ~a" name))
                   (push (object "name" name "stale_refused" :true) checks))
                 (step-at name argument))))
      (step-at "empty" 3)
      (change "base" (lambda () (eval '(defmethod route ((x t)) (declare (ignore x)) (values 10 11)))) 3)
      (step-at "warm-base" 3)
      (change "integer" (lambda () (eval '(defmethod route ((x integer)) (declare (ignore x)) (values 20 21)))) 3)
      (step-at "warm-integer" 3)
      (change "replace-integer" (lambda () (eval '(defmethod route ((x integer)) (declare (ignore x)) (values 30 31)))) 3)
      (change "remove-integer" (lambda () (remove-method gf (find-method gf nil (list (find-class 'integer))))) 3)
      (change "eql" (lambda () (eval '(defmethod route ((x (eql 3))) (declare (ignore x)) (values 40 41)))) 3)
      (step-at "eql-miss" 4)
      (change "around" (lambda () (eval '(defmethod route :around ((x t))
                                           (multiple-value-bind (a b) (call-next-method)
                                             (values (+ 100 a) (+ 100 b)))))) 3)
      (change "remove-around" (lambda () (remove-method gf (find-method gf '(:around) (list (find-class 't))))) 3)
      (change "remove-all" (lambda () (dolist (m (copy-list (ccl::%gf-methods gf))) (remove-method gf m))) 3)
      ;; Independent field omissions must not become an apparently valid bound.
      (eval '(defmethod route ((x t)) (declare (ignore x)) (values 10 11)))
      (let ((m (car (ccl::%gf-methods gf))))
        (dolist (kind '(:function :qualifiers :specializers :dcode))
          (let ((old (snapshot gf))
                (f (ccl::%method.function m)) (q (ccl::%method.qualifiers m))
                (s (ccl::%method.specializers m)) (d (ccl::%gf-dcode gf)))
            (unwind-protect
                (progn
                  (ecase kind
                    (:function (setf (ccl::%method.function m) (lambda (&rest args) (declare (ignore args)) 99)))
                    (:qualifiers (setf (ccl::%method.qualifiers m) '(:before)))
                    (:specializers (setf (ccl::%method.specializers m) (list (find-class 'integer))))
                    (:dcode (setf (ccl::%gf-dcode gf) #'ccl::%%0-arg-dcode)))
                  (let ((fresh (snapshot gf)))
                    (when (equal old fresh) (error "REGISTRY-UNSEEN-FIELD ~a" kind))
                    (push (object "name" (symbol-name kind) "old" old "changed" fresh) checks)))
              (setf (ccl::%method.function m) f (ccl::%method.qualifiers m) q
                    (ccl::%method.specializers m) s (ccl::%gf-dcode gf) d))
            (unless (current-p old gf) (error "REGISTRY-RESTORATION")))))
      (let* ((ordinary (compile nil `(lambda () ',#'ccl::%%one-arg-dcode))) (literals nil)
             (refused (handler-case (progn (snapshot ordinary) nil) (error () t))))
        (ccl::%map-lfimms ordinary (lambda (v) (when (functionp v) (push v literals))))
        (unless (and refused (equal literals (list #'ccl::%%one-arg-dcode)))
          (error "REGISTRY-LITERAL-COUNTEREXAMPLE"))
        (push (object "name" "ordinary-function-with-dcode-literal" "function" (fn ordinary)
                      "literal" (fn (car literals)) "refused" :true) checks))
      (object "steps" (nreverse steps) "checks" (nreverse checks)))))

(defun export-state (path)
  (when ccl::*startup-census-hook* (error "REGISTRY-HOOK-ACTIVE"))
  (let* ((registry (registry-snapshot))
         (probe (probes))
         (functions (function-records)))
    (with-open-file (s path :direction :output :if-exists :error :external-format :utf-8)
      (json (object "version" 1 "namespace" "fresh-native-registry"
                    "scope" "Sequential native checkpoint; no join to original dynamic objects or exhaustive runtime bound"
                    "registry" registry "probes" probe "functions" functions) s)
      (terpri s))
    (format t "DISPATCH-REGISTRY-PASS gfs=~d~%" (length registry))))
