;;; Independent reproduction: no observer or registry inspector is loaded.
(defpackage :ccl-removal-reproduction (:use :cl))
(in-package :ccl-removal-reproduction)
(defgeneric route (x))
(defmethod route ((x t)) (declare (ignore x)) (values 10 11))
(let* ((gf #'route)
       (method (find-method gf nil (list (find-class 't))))
       (dcode (ccl::%gf-dcode gf))
       (before (multiple-value-list (funcall gf 3))))
  (remove-method gf method)
  (let ((methods (ccl:generic-function-methods gf))
        (retained (eq dcode (ccl::%gf-dcode gf)))
        (after (multiple-value-list (funcall gf 3))))
    (unless (and (null methods) retained (equal before '(10 11)) (equal after '(10 11)))
      (error "NATIVE-EMPTY-METHOD-ESCAPE-NOT-REPRODUCED"))
    (format t "NATIVE-EMPTY-METHOD-ESCAPE methods=0 retained-dcode=true before=10,11 after=10,11~%")))
(ccl:quit)
