(module
  (type $entry_type (func (param i32) (result i32)))
  (memory (export "memory") 1 32769)
  (table 8 8 funcref)
  (func $reserved_a (type $entry_type) (param i32) (result i32) local.get 0)
  (func $reserved_b (type $entry_type) (param i32) (result i32) local.get 0)
  (func $entry (type $entry_type) (param i32) (result i32)
    (i32.add (local.get 0) (i32.const @BIAS@)))
  ;; The final binary, not a guessed C reservation, supplies these slots.
  (elem (i32.const 0) $reserved_a $reserved_b)
  (elem declare func $entry)

  ;; Every public operation returns (value, refusal); refusal 0 means success.
  (func $box (export "box") (param $n i32) (result i32 i32)
    (if (i32.or (i32.lt_s (local.get $n) (i32.const -536870912)) (i32.gt_s (local.get $n) (i32.const 536870911)))
      (then (return (i32.const 0) (i32.const 1))))
    (i32.shl (local.get $n) (i32.const 2)) (i32.const 0))
  (func (export "unbox") (param $word i32) (result i32 i32)
    (if (i32.and (local.get $word) (i32.const 3)) (then (return (i32.const 0) (i32.const 2))))
    (i32.shr_s (local.get $word) (i32.const 2)) (i32.const 0))
  (func (export "raw_as_fixnum") (param $raw i32) (result i32 i32)
    (if (i32.gt_u (local.get $raw) (i32.const 536870911)) (then (return (i32.const 0) (i32.const 1))))
    (call $box (local.get $raw)))
  (func $pointer_tag (param $tag i32) (result i32)
    (i32.or (i32.eq (local.get $tag) (i32.const 1)) (i32.eq (local.get $tag) (i32.const 6))))
  (func (export "tag") (param $raw i32) (param $tag i32) (result i32 i32)
    (if (i32.eqz (call $pointer_tag (local.get $tag))) (then (return (i32.const 0) (i32.const 2))))
    (if (i32.and (local.get $raw) (i32.const 7)) (then (return (i32.const 0) (i32.const 3))))
    (i32.or (local.get $raw) (local.get $tag)) (i32.const 0))
  (func (export "untag") (param $ptr i32) (result i32 i32)
    (if (i32.eqz (call $pointer_tag (i32.and (local.get $ptr) (i32.const 7)))) (then (return (i32.const 0) (i32.const 2))))
    (i32.and (local.get $ptr) (i32.const -8)) (i32.const 0))
  (func (export "effective") (param $ptr i32) (param $disp i32) (result i32 i32) (local $sum i64)
    (local.set $sum (i64.add (i64.extend_i32_u (local.get $ptr)) (i64.extend_i32_s (local.get $disp))))
    (if (i64.gt_u (local.get $sum) (i64.const 4294967295)) (then (return (i32.const 0) (i32.const 4))))
    (i32.wrap_i64 (local.get $sum)) (i32.const 0))

  (func $span (param $raw i32) (result i32)
    (i64.le_u (i64.add (i64.extend_i32_u (local.get $raw)) (i64.const 8))
      (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))))
  (func $place (param $raw i32) (result i32)
    (if (i32.and (local.get $raw) (i32.const 7)) (then (return (i32.const 3))))
    ;; Low bytes are owned by the fixture slot registry.
    (if (i32.or (i32.lt_u (local.get $raw) (i32.const 4096)) (i32.eqz (call $span (local.get $raw))))
      (then (return (i32.const 4))))
    (i32.const 0))
  (func (export "cons_store") (param $raw i32) (param $car i32) (param $cdr i32) (result i32 i32) (local $err i32)
    (local.set $err (call $place (local.get $raw)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (i32.store (local.get $raw) (local.get $cdr))
    (i32.store offset=4 (local.get $raw) (local.get $car))
    (i32.add (local.get $raw) (i32.const 1)) (i32.const 0))
  (func $readable (param $ptr i32) (param $tag i32) (result i32)
    (if (i32.ne (i32.and (local.get $ptr) (i32.const 7)) (local.get $tag)) (then (return (i32.const 2))))
    (call $place (i32.and (local.get $ptr) (i32.const -8))))
  (func (export "cons_car") (param $ptr i32) (result i32 i32) (local $err i32)
    (local.set $err (call $readable (local.get $ptr) (i32.const 1)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (i32.load (i32.add (local.get $ptr) (i32.const 3))) (i32.const 0))
  (func (export "cons_cdr") (param $ptr i32) (result i32 i32) (local $err i32)
    (local.set $err (call $readable (local.get $ptr) (i32.const 1)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (i32.load (i32.sub (local.get $ptr) (i32.const 1))) (i32.const 0))
  (func (export "header_store") (param $raw i32) (param $word i32) (result i32 i32) (local $err i32)
    (local.set $err (call $place (local.get $raw)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (i32.store (local.get $raw) (local.get $word))
    (i32.store offset=4 (local.get $raw) (i32.const 287454020))
    (i32.add (local.get $raw) (i32.const 6)) (i32.const 0))
  (func (export "header_load") (param $ptr i32) (result i32 i32) (local $err i32)
    (local.set $err (call $readable (local.get $ptr) (i32.const 6)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (i32.load (i32.sub (local.get $ptr) (i32.const 6))) (i32.const 0))

  (global $first (mut i32) (i32.const 0))
  (global $next (mut i32) (i32.const 0))
  (global $lo (mut i32) (i32.const 0))
  (global $hi (mut i32) (i32.const 0))
  (func (export "ids_reset") (param $start i32) (param $lo i32) (param $hi i32) (result i32 i32)
    (if (i32.or (i32.gt_u (local.get $start) (i32.const 536870912))
        (i32.or (i32.gt_u (local.get $hi) (i32.const 536870912)) (i32.gt_u (local.get $lo) (local.get $hi))))
      (then (return (i32.const 0) (i32.const 1))))
    (global.set $first (local.get $start)) (global.set $next (local.get $start))
    (global.set $lo (local.get $lo)) (global.set $hi (local.get $hi))
    (local.get $start) (i32.const 0))
  (func (export "id_alloc") (result i32 i32) (local $id i32)
    (if (i32.and (i32.ge_u (global.get $next) (global.get $lo)) (i32.lt_u (global.get $next) (global.get $hi)))
      (then (global.set $next (global.get $hi))))
    (if (i32.ge_u (global.get $next) (i32.const 536870912)) (then (return (i32.const 0) (i32.const 6))))
    (local.set $id (global.get $next)) (global.set $next (i32.add (global.get $next) (i32.const 1)))
    (i32.shl (local.get $id) (i32.const 2)) (i32.const 0))
  (func (export "id_encode") (param $id i32) (result i32 i32)
    (if (i32.gt_u (local.get $id) (i32.const 536870911)) (then (return (i32.const 0) (i32.const 1))))
    (i32.shl (local.get $id) (i32.const 2)) (i32.const 0))
  (func (export "id_valid") (param $word i32) (result i32 i32) (local $id i32)
    (if (i32.or (i32.and (local.get $word) (i32.const 3)) (i32.lt_s (local.get $word) (i32.const 0)))
      (then (return (i32.const 0) (i32.const 2))))
    (local.set $id (i32.shr_u (local.get $word) (i32.const 2)))
    (if (i32.or (i32.lt_u (local.get $id) (global.get $first))
        (i32.or (i32.ge_u (local.get $id) (global.get $next))
          (i32.and (i32.ge_u (local.get $id) (global.get $lo)) (i32.lt_u (local.get $id) (global.get $hi)))))
      (then (return (i32.const 0) (i32.const 5))))
    (local.get $id) (i32.const 0))

  (global $capacity (mut i32) (i32.const 0))
  (global $reserved (mut i32) (i32.const 0))
  (func (export "slots_reset") (param $cap i32) (param $reserved i32) (result i32 i32) (local $i i32)
    (if (i32.or (i32.gt_u (local.get $cap) (table.size)) (i32.gt_u (local.get $reserved) (table.size)))
      (then (return (i32.const 0) (i32.const 7))))
    (global.set $capacity (local.get $cap)) (global.set $reserved (local.get $reserved))
    (local.set $i (local.get $reserved))
    (block $done (loop $clear
      (br_if $done (i32.ge_u (local.get $i) (table.size)))
      (table.set (local.get $i) (ref.null func))
      (i32.store (i32.add (i32.const 64) (i32.mul (local.get $i) (i32.const 4))) (i32.const 0))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $clear)))
    (local.get $cap) (i32.const 0))
  (func $slot_check (param $slot i32) (param $kind i32) (result i32)
    (if (i32.ne (local.get $kind) (i32.const 3)) (then (return (i32.const 9))))
    (if (i32.ge_u (local.get $slot) (global.get $capacity)) (then (return (i32.const 7))))
    (if (i32.lt_u (local.get $slot) (global.get $reserved)) (then (return (i32.const 8))))
    (i32.const 0))
  (func (export "slot_check") (param $slot i32) (param $kind i32) (result i32 i32)
    (i32.const 0) (call $slot_check (local.get $slot) (local.get $kind)))
  (func $install (export "slot_install") (param $slot i32) (param $kind i32) (param $sig i32) (param $role i32) (result i32 i32) (local $err i32)
    (local.set $err (call $slot_check (local.get $slot) (local.get $kind)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (if (i32.ne (local.get $sig) (i32.const 1)) (then (return (i32.const 0) (i32.const 10))))
    (if (i32.ne (local.get $role) (i32.const 1)) (then (return (i32.const 0) (i32.const 11))))
    (table.set (local.get $slot) (ref.func $entry))
    (i32.store (i32.add (i32.const 64) (i32.mul (local.get $slot) (i32.const 4))) (i32.const 1))
    (local.get $slot) (i32.const 0))
  (func (export "slot_alloc") (param $sig i32) (param $role i32) (result i32 i32) (local $i i32)
    (local.set $i (global.get $reserved))
    (block $done (loop $scan
      (br_if $done (i32.ge_u (local.get $i) (global.get $capacity)))
      (if (i32.eqz (i32.load (i32.add (i32.const 64) (i32.mul (local.get $i) (i32.const 4)))))
        (then (return (call $install (local.get $i) (i32.const 3) (local.get $sig) (local.get $role)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $scan)))
    (i32.const 0) (i32.const 6))
  (func (export "slot_call") (param $slot i32) (param $kind i32) (param $arg i32) (result i32 i32) (local $err i32)
    (local.set $err (call $slot_check (local.get $slot) (local.get $kind)))
    (if (local.get $err) (then (return (i32.const 0) (local.get $err))))
    (if (i32.eqz (i32.load (i32.add (i32.const 64) (i32.mul (local.get $slot) (i32.const 4)))))
      (then (return (i32.const 0) (i32.const 12))))
    (call_indirect (type $entry_type) (local.get $arg) (local.get $slot)) (i32.const 0))
)
