(in-package :wasm32-compiler)

(defclass dispatch-root () ())
(defclass dispatch-left (dispatch-root) ())
(defclass dispatch-right (dispatch-root) ())
(defclass dispatch-diamond (dispatch-left dispatch-right) ())
(defvar *generic-graphs* (make-hash-table :test #'eq))

(defun generic-image (reversep &optional callable)
  (let* ((root (find-class 'dispatch-root))
         (left (find-class 'dispatch-left))
         (right (find-class 'dispatch-right))
         (diamond (find-class 'dispatch-diamond))
         (instance (make-instance diamond))
         (methods
           (loop for class in (list root right left diamond)
                 for name in '(:root :right :left :diamond)
                 collect (let* ((function (ccl::%copy-function (selection-function 'core-generic-leaf)))
                                (method (make-instance 'standard-method
                                        :qualifiers nil :specializers (list class)
                                        :lambda-list '(object) :function function)))
                           (setf (gethash function *accessor-function-names*) 'core-generic-leaf)
                           (setf (ccl::%method.name method) name)
                           method)))
         (table (make-array 256 :initial-element nil))
         (image nil))
    (setf (svref table 114) (selection-function 'core-generic-class-of-instance)
          (svref table 42) (selection-function 'core-generic-class-of-function))
    (dolist (entry '((0 . fixnum) (7 . bignum) (75 . character) (58 . symbol)
                     (15 . single-float) (23 . double-float) (191 . simple-base-string)
                     (250 . simple-vector) (2 . cons) (4 . null) (6 . function)))
      (setf (svref table (car entry)) (find-class (cdr entry))))
    (setf (svref table 1) (selection-function 'core-generic-class-of-list))
    (setq image (vector table (if reversep (reverse methods) methods)
                        (list instance) (list (ccl::%class.cpl diamond))
                        (find-class 'ccl::eql-specializer)
                        (find-class 'standard-class)))
    (when callable
      (let ((gf (make-instance 'standard-generic-function :name 'core-generic-example :lambda-list '(object))))
        (dolist (method methods) (add-method gf method))
        (setq image (concatenate 'vector image (vector gf)))))
    (setf (gethash image *generic-graphs*) t)
    image))

(defun generic-inputs (name)
  (when (or (find name *generic-method-forms* :key #'second)
            (rassoc name *generic-protocol-methods*)
            (member name '(core-condition-p-t core-condition-p-condition
                           core-class-finalized-class core-class-finalized-std-class
                           core-class-finalized-compile-time-class)))
    ;; Method entries receive a hidden context from the GF; an ordinary
    ;; one-argument predicate recipe cannot call them directly.
    (return-from generic-inputs (values nil t)))
  (case name
    ((core-generic-order core-generic-applicable)
     (values (list (list (generic-image nil)) (list (generic-image t))) t))
    (core-generic-builtin
     (values (loop for (object class) in (list (list nil 'list) (list '(1 . 2) 'list)
                  (list 17 'integer) (list (ash 1 80) 'integer) (list #\a 'character)
                  (list :keyword 'symbol) (list 1.5s0 'float) (list 1.5d0 'float)
                  (list "text" 'string) (list #(1 2) 'vector))
                  collect (list (generic-builtin-image object class))) t))
    (core-generic-arguments
     (values (append
       (loop for args in '(nil (17) (17 nil)) collect (list (generic-arguments-image :optional args)))
       (loop for args in '(nil (1) (1 2 3 4)) collect (list (generic-arguments-image :rest args)))
       (loop for args in '(nil (:amount 9) (:amount 7 :amount 8) (:other 9)
                          (:other 9 :allow-other-keys t) (:amount))
             collect (list (generic-arguments-image :key args)))) t))
    (core-generic-failure
     (values (loop for scenario from 0 to 5 collect (list (generic-failure-image scenario))) t))
    (core-generic-reader-dispatch (values (list (list (generic-reader-image))) t))
    (core-generic-replace (values (list (list (generic-replacement-image))) t))
    (core-generic-create (values (list (list (generic-resume-image))) t))
    ((core-generic-resume core-generic-empty-cycle) (values (list (list (generic-resume-image))) t))
    (core-generic-updates (values (list (list (generic-update-image))) t))
    (core-generic-select (values (loop for scenario from 0 to 5 collect (list (generic-selector-image scenario))) t))
    (core-generic-standard (values (loop for scenario from 0 to 7 collect (list (generic-standard-image scenario))) t))
    (core-generic-call (values (list (list (generic-image nil t))) t))
    (compiled-function-p
     (values (mapcar #'list (list nil 17 :symbol (selection-function 'core-selection-first))) t))
    (t (selection-inputs name))))

(defun generic-standard-image (scenario)
  (let* ((image (generic-image nil))
         (root (find-class 'dispatch-root))
         (left (find-class 'dispatch-left))
         (diamond (find-class 'dispatch-diamond))
         (gf (make-instance 'standard-generic-function :name 'core-generic-standard
                            :lambda-list (if (= scenario 5) '(object &key amount) '(object))))
         (methods nil))
    (flet ((add (name class &optional qualifier)
             (let* ((function (ccl::%copy-function (selection-function name)))
                    (method (make-instance 'standard-method
                              :qualifiers (and qualifier (list qualifier))
                              :specializers (list class)
                              :lambda-list (if (eq name 'core-generic-key) '(object &key amount) '(object))
                              :function function)))
               (setf (gethash function *accessor-function-names*) name)
               (add-method gf method)
               (push method methods))))
      (if (= scenario 5)
        (add 'core-generic-key root)
        (progn
          (add (if (= scenario 6) 'core-generic-escape 'core-generic-root) root)
          (when (= scenario 6) (add 'core-generic-cleanup diamond :around))
          (case scenario
            ((1 2) (add 'core-generic-left left))
            (3 (add 'core-generic-next-twice left))
            (4 (add 'core-generic-next-args left))
            (7 (add 'core-generic-next-bad left)))
          (when (= scenario 2)
            (add 'core-generic-around diamond :around)
            (add 'core-generic-before root :before)
            (add 'core-generic-after root :after)))))
    (setf (svref image 1) methods)
    (when (= scenario 5) (setf (svref image 2) (append (svref image 2) (list :amount 19))))
    (setq image (concatenate 'vector image (vector gf)))
    (when (= scenario 7)
      (setq image (concatenate 'vector image (vector (generic-protocol-image)))))
    (setf (gethash image *generic-graphs*) t)
    image))


(defun generic-selector-image (scenario)
  (let* ((image (generic-image nil))
         (root (find-class 'dispatch-root))
         (left (find-class 'dispatch-left))
         (right (find-class 'dispatch-right))
         (object (car (svref image 2)))
         (lambda-list (cond ((= scenario 5) nil) ((< scenario 2) '(x y)) (t '(object))))
         (gf (apply #'make-instance 'standard-generic-function
                    :name 'core-generic-selector :lambda-list lambda-list
                    (when (= scenario 1) '(:argument-precedence-order (y x)))))
         (methods nil))
    (flet ((add (name specializers)
             (let* ((function (ccl::%copy-function (selection-function name)))
                    (method (make-instance 'standard-method :qualifiers nil
                              :specializers specializers :lambda-list lambda-list :function function)))
               (setf (gethash function *accessor-function-names*) name)
               (add-method gf method)
               (push method methods))))
      (cond ((< scenario 2)
             (add 'core-generic-pair-left (list left root))
             (add 'core-generic-pair-right (list root right))
             (setf (svref image 2) (list object object)))
            ((= scenario 5)
             (add 'core-generic-empty nil)
             (setf (svref image 2) nil))
            (t
             (add 'core-generic-leaf (list root))
             (add 'core-generic-eql (list (ccl::intern-eql-specializer object)))
             (when (= scenario 3)
               (setf (svref image 2) (list (make-instance 'dispatch-diamond))))
             (when (= scenario 4)
               (setf (svref image 2) (list (make-instance 'dispatch-left)))))))
    (setf (svref image 1) methods)
    (setq image (concatenate 'vector image (vector gf)))
    (setf (gethash image *generic-graphs*) t)
    image))

(defvar *generic-bindings* (make-hash-table :test #'eq))

(defun generic-protocol-image ()
  (let ((result
          (loop for (name . entry) in *generic-protocol-methods*
                for gf = (fdefinition name) collect
                (progn
                  (assert (= (length (ccl::%gf-methods gf)) 1))
                  (setf (gethash (ccl::%method-function (car (ccl::%gf-methods gf)))
                                 *accessor-function-names*) entry
                        (gethash gf *generic-bindings*) name)
                  gf)))
        (gf #'ccl::class-finalized-p))
    (dolist (method (ccl::%gf-methods gf))
      (let* ((class (class-name (car (ccl::%method-specializers method))))
             (name (intern (format nil "CORE-CLASS-FINALIZED-~a" class) :wasm32-compiler)))
        (setf (gethash (ccl::%method-function method) *accessor-function-names*) name)))
    (setf (gethash gf *generic-bindings*) 'ccl::class-finalized-p)
    (let ((predicate #'ccl::condition-p))
      (dolist (method (ccl::%gf-methods predicate))
        (let* ((class (class-name (car (ccl::%method-specializers method))))
               (name (intern (format nil "CORE-CONDITION-P-~a" class) :wasm32-compiler)))
          (setf (gethash (ccl::%method-function method) *accessor-function-names*) name)))
      (setf (gethash predicate *generic-bindings*) 'ccl::condition-p)
      (append result (list gf predicate)))))

(defun generic-update-image ()
  (let* ((image (generic-standard-image 0))
         (gf (svref image 6))
         (function (ccl::%copy-function (selection-function 'core-generic-left)))
         (method (make-instance 'standard-method :qualifiers nil
                   :specializers (list (find-class 'dispatch-left))
                   :lambda-list '(object) :function function))
         (classes (list (cons 'ccl::*min-gf-dispatch-table-size* ccl::*min-gf-dispatch-table-size*)
                        (cons 'ccl::*standard-method-class* (find-class 'standard-method))
                        (cons 'ccl::*standard-generic-function-class* (find-class 'standard-generic-function))
                        (cons 'ccl::*generic-function-class* (find-class 'generic-function))
                        (cons 'ccl::*t-class* (find-class t)))))
    (declare (ignore gf))
    (setf (gethash function *accessor-function-names*) 'core-generic-left)
    (setq image (concatenate 'vector image (vector classes (generic-protocol-image) method)))
    (setf (gethash image *generic-graphs*) t)
    image))


(defun generic-failure-image (scenario)
  (let* ((image (generic-update-image))
         (old (svref image 6))
         (gf (make-instance 'standard-generic-function :name 'core-generic-failure
                            :lambda-list '(object))))
    (case scenario
      (1 (let* ((function (ccl::%copy-function (selection-function 'core-generic-before)))
                (method (make-instance 'standard-method :qualifiers '(:before)
                          :specializers (list (find-class 'dispatch-root))
                          :lambda-list '(object) :function function)))
           (setf (gethash function *accessor-function-names*) 'core-generic-before)
           (add-method gf method)))
      (2 (add-method gf (svref image 9)))
      ((3 4 5)
       (setq gf old)
       (setf (svref image 2) (case scenario (3 nil) (4 (append (svref image 2) '(17)))
                                       (5 (svref image 2))))
       (when (= scenario 5)
         (dolist (method (copy-list (ccl::%gf-methods gf))) (remove-method gf method)))))
    (setf (svref image 6) gf (svref image 1) (ccl::%gf-methods gf))
    (setq image (concatenate 'vector image (vector scenario)))
    (setf (gethash image *generic-graphs*) t)
    image))

(defun generic-resume-image ()
  (let* ((image (generic-update-image))
         (gf (make-instance 'standard-generic-function :name 'core-generic-resume
                           :lambda-list '(object)))
         (function (ccl::%copy-function (selection-function 'core-generic-root)))
         (method (make-instance 'standard-method :qualifiers nil
                   :specializers (list (find-class 'dispatch-root))
                   :lambda-list '(object) :function function)))
    (setf (gethash function *accessor-function-names*) 'core-generic-root)
    (setf (svref image 6) gf (svref image 1) nil (svref image 9) method)
    image))

(defun generic-replacement-image ()
  (let* ((image (generic-update-image))
         (function (ccl::%copy-function (selection-function 'core-generic-root)))
         (method (make-instance 'standard-method :qualifiers nil
                   :specializers (list (find-class 'dispatch-left))
                   :lambda-list '(object) :function function)))
    (setf (gethash function *accessor-function-names*) 'core-generic-root)
    (setq image (concatenate 'vector image (vector method)))
    (setf (gethash image *generic-graphs*) t)
    image))

(defun generic-builtin-image (object class)
  (let* ((image (generic-update-image))
         (gf (make-instance 'standard-generic-function :name 'core-builtin-dispatch
                           :lambda-list '(object)))
         (table (svref image 0))
         (methods nil))
    (loop for name in '(core-generic-leaf core-generic-eql)
          for specializer in (list (find-class t) (find-class class)) do
      (let* ((function (ccl::%copy-function (selection-function name)))
             (method (make-instance 'standard-method :qualifiers nil
                       :specializers (list specializer) :lambda-list '(object) :function function)))
        (setf (gethash function *accessor-function-names*) name)
        (add-method gf method)
        (push method methods)))
    (dolist (entry '((0 . fixnum) (7 . bignum) (75 . character) (58 . symbol)
                     (15 . single-float) (23 . double-float) (191 . simple-base-string)
                     (250 . simple-vector) (2 . cons) (4 . null)))
      (setf (svref table (car entry)) (find-class (cdr entry))))
    (setf (svref table 1) (selection-function 'core-generic-class-of-list)
          (svref image 1) methods (svref image 2) (list object) (svref image 6) gf)
    image))

(defun generic-arguments-image (kind arguments)
  (let* ((image (generic-standard-image 0))
         (name (ecase kind (:optional 'core-generic-optional) (:rest 'core-generic-rest)
                          (:key 'core-generic-key)))
         (lambda-list (ecase kind (:optional '(object &optional (value 23 supplied)))
                                 (:rest '(object &rest rest)) (:key '(object &key amount))))
         (gf (make-instance 'standard-generic-function :name 'core-argument-dispatch
                           :lambda-list lambda-list))
         (function (ccl::%copy-function (selection-function name)))
         (method (make-instance 'standard-method :qualifiers nil
                   :specializers (list (find-class 'dispatch-root))
                   :lambda-list lambda-list :function function)))
    (setf (gethash function *accessor-function-names*) name)
    (add-method gf method)
    (setf (svref image 1) (list method) (svref image 6) gf
          (svref image 2) (cons (car (svref image 2)) arguments))
    image))

(defun generic-reader-image ()
  (let* ((image (generic-update-image))
         (selection (generic-selector-image 2))
         (function (ccl::%copy-function (selection-function 'core-generic-reader-around)))
         (method (make-instance 'standard-method :qualifiers '(:around)
                   :specializers (list (find-class 'ccl::eql-specializer))
                   :lambda-list '(object) :function function)))
    (setf (gethash function *accessor-function-names*) 'core-generic-reader-around)
    (dolist (i '(1 2 6)) (setf (svref image i) (svref selection i)))
    (setf (svref image 9) method)
    image))
