(in-package :wasm32-compiler)

;;; Let CCL's own DEFMETHOD front end create the hidden method context and
;;; CALL-NEXT-METHOD bindings. The resulting lambda is the compiler input on
;;; both machines; the method algorithm is not rewritten by the fixture.
(defvar *generic-trace* nil)
(defparameter *generic-method-forms*
  '((defmethod core-generic-root ((object t))
      (declare (ignore object) (special *generic-trace*))
      (core-collect)
      (push :root *generic-trace*)
      (values 10 :second))
    (defmethod core-generic-left ((object t))
      (declare (ignore object) (special *generic-trace*))
      (push :left *generic-trace*)
      (core-collect)
      (multiple-value-bind (n second) (call-next-method)
        (values (1+ n) second)))
    (defmethod core-generic-around ((object t))
      (declare (ignore object) (special *generic-trace*))
      (push :enter *generic-trace*)
      (multiple-value-prog1 (call-next-method)
        (core-collect)
        (push :leave *generic-trace*)))
    (defmethod core-generic-before ((object t))
      (declare (ignore object) (special *generic-trace*))
      (core-collect)
      (push :before *generic-trace*))
    (defmethod core-generic-after ((object t))
      (declare (ignore object) (special *generic-trace*))
      (core-collect)
      (push :after *generic-trace*))
    (defmethod core-generic-next-twice ((object t))
      (declare (ignore object) (special *generic-trace*))
      (list (call-next-method) (call-next-method) (next-method-p)))
    (defmethod core-generic-next-args ((object t))
      (declare (special *generic-trace*))
      (call-next-method object))
    (defmethod core-generic-key ((object t) &key (amount 3))
      (declare (ignore object) (special *generic-trace*))
      (core-collect)
      (values amount :key))
    (defmethod core-generic-pair ((x t) (y t))
      (declare (ignore x y) (special *generic-trace*))
      (core-collect)
      :pair)))

(setq *generic-method-forms*
      (append *generic-method-forms*
        '((defmethod core-generic-eql ((object t))
            (declare (ignore object))
            (core-collect)
            :eql)
          (defmethod core-generic-pair-left ((x t) (y t))
            (declare (ignore x y))
            (core-collect)
            :left)
          (defmethod core-generic-pair-right ((x t) (y t))
            (declare (ignore x y))
            (core-collect)
            :right)
          (defmethod core-generic-empty ()
            (core-collect)
            (values :empty 17)))))

(defun generic-method-forms ()
  (mapcar (lambda (form)
            (let* ((name (second form))
                   (function (ccl::parse-defmethod name (cddr form) nil))
                   (lambda-form (third function)))
              (assert (eq (car function) 'ccl::nfunction))
              `(defun ,name ,@(cdr lambda-form))))
          *generic-method-forms*))

(defparameter *generic-protocol-methods*
  '((ccl::class-precedence-list . core-default-class-precedence-list)
    (add-method . core-default-add-method)
    (remove-method . core-default-remove-method)
    (no-next-method . core-default-no-next-method)
    (no-applicable-method . core-default-no-applicable-method)
    (ccl::no-applicable-primary-method . core-default-no-primary)))

(defun generic-protocol-forms ()
  (let ((*package* (find-package :ccl))
        (forms nil))
    (with-open-file (stream "ccl:level-1;l1-clos-boot.lisp")
      (loop for form = (read stream nil :eof) until (eq form :eof) do
        (when (and (consp form) (eq (car form) 'defmethod)
                   (assoc (second form) *generic-protocol-methods*))
          (let* ((name (second form))
                 (entry (cdr (assoc name *generic-protocol-methods*)))
                 (function (ccl::parse-defmethod name (cddr form) nil)))
            (push `(defun ,entry ,@(cdr (third function))) forms)))))
    (assert (= (length forms) (length *generic-protocol-methods*)))
    (nreverse forms)))

(defun generic-class-forms ()
  (let ((*package* (find-package :ccl)) (forms nil))
    (with-open-file (stream "ccl:level-1;l1-clos.lisp")
      (loop for form = (read stream nil :eof) until (eq form :eof) do
        (when (and (consp form) (eq (car form) 'defmethod)
                   (eq (second form) 'ccl::class-finalized-p))
          (let* ((class (second (first (third form))))
                 (name (intern (format nil "CORE-CLASS-FINALIZED-~a" class) :wasm32-compiler))
                 (function (ccl::parse-defmethod (second form) (cddr form) nil)))
            (push `(defun ,name ,@(cdr (third function))) forms)))))
    (assert (= (length forms) 3))
    (nreverse forms)))


(defun generic-condition-forms ()
  (let ((*package* (find-package :ccl)) (forms nil))
    (with-open-file (stream "ccl:level-1;l1-error-system.lisp")
      (loop for form = (read stream nil :eof) until (eq form :eof) do
        (when (and (consp form) (eq (car form) 'defmethod)
                   (eq (second form) 'ccl::condition-p))
          (let* ((class (second (first (third form))))
                 (name (intern (format nil "CORE-CONDITION-P-~a" class) :wasm32-compiler))
                 (function (ccl::parse-defmethod (second form) (cddr form) nil)))
            (push `(defun ,name ,@(cdr (third function))) forms)))))
    (assert (= (length forms) 2))
    (nreverse forms)))

(setq *generic-method-forms*
      (append *generic-method-forms*
        '((defmethod core-generic-optional ((object t) &optional (value 23 supplied))
            (declare (ignore object))
            (core-collect)
            (values value supplied))
          (defmethod core-generic-rest ((object t) &rest rest)
            (declare (ignore object))
            (core-collect)
            (values rest (length rest))))))

(setq *generic-method-forms*
      (append *generic-method-forms*
        '((defmethod core-generic-reader-around ((object t))
            (declare (ignore object))
            (call-next-method)
            (core-collect)
            (values :reader 17)))))

(setq *generic-method-forms*
      (append *generic-method-forms*
        '((defmethod core-generic-escape ((object t))
            (declare (ignore object) (special *generic-trace*))
            (push :escape *generic-trace*)
            (core-collect)
            (throw :dispatch-exit (values 17 :escaped)))
          (defmethod core-generic-cleanup ((object t))
            (declare (ignore object) (special *generic-trace*))
            (push :enter *generic-trace*)
            (unwind-protect (call-next-method)
              (core-collect)
              (push :cleanup *generic-trace*)))
          (defmethod core-generic-next-bad ((object t))
            (declare (ignore object))
            (core-collect)
            (call-next-method nil)))))
