(in-package :wasm32-compiler)

(defun core-controls (out)
  (let ((rows nil))
    (flet ((expect-refusal (name form result reason)
             (let ((actual
                     (handler-case (progn (core-check-body form result) :admitted)
                       (unsupported-wasm32-code (c) (unsupported-operation c)))))
               (assert (eq actual reason))
               (push (list name actual) rows))))
      (let ((*core-native-forms* (make-hash-table :test #'eq)))
        (setf (gethash 'core-empty *core-native-forms*) '(defun core-empty (x) (consp x)))
        (dolist (row '((:empty-target (defun core-empty (x) "Documentation.") :bootstrap-empty-target-body)
                       (:self-call (defun core-self (x) (core-self x)) :bootstrap-self-only-body)))
          (destructuring-bind (name form reason) row
            (let* ((wire (string-downcase (symbol-name name)))
                   (result (call-with-target (lambda () (compile-bootstrap-form form wire nil)))))
              (with-open-file (s (concatenate 'string out wire ".refused-wat")
                                 :direction :output :if-exists :error)
                (write-string (getf result :wat) s))
              (expect-refusal name form result reason))))
        (expect-refusal :aliased-self-call '(defun core-self (x) (core-self x))
                        '(:dependencies (core-other)) :bootstrap-self-only-body)
        (core-check-body '(defun core-empty (x) nil) nil)
        (core-check-body '(defun core-self (x) (core-self x)) '(:dependencies nil :self-call nil))))
    (dolist (row '((:signal-no-arguments (defun refused () (signal)) :bootstrap-signal-arity)
                   (:unknown-condition-class (defun refused () (error 'warning)) :bootstrap-condition-class)
                   (:odd-condition-initargs (defun refused () (error 'type-error :datum)) :bootstrap-condition-initargs)
                   (:unknown-condition-initarg (defun refused () (error 'type-error :unknown 7)) :bootstrap-condition-initarg)
                   (:condition-reader-arity (defun refused () (type-error-datum)) :bootstrap-condition-reader-arity)
                   (:bit-vector-kind (defun refused (x) (declare (type (simple-array bit (*)) x)) (aref x 0)) :bootstrap-array-kind)))
      (destructuring-bind (name form expected) row
        (let ((actual (handler-case
                          (progn (call-with-target (lambda () (compile-bootstrap-form form "refusal" nil))) :admitted)
                        (unsupported-wasm32-code (c) (unsupported-operation c)))))
          (unless (eq actual expected) (error "~s: wanted ~s, got ~s" name expected actual))
          (push (list name actual) rows))))
    (with-open-file (s (concatenate 'string out "measure-controls.sexp")
                       :direction :output :if-exists :error)
      (prin1 (nreverse rows) s))))
