;;; D1 node indices match the 32-bit CCL object definitions in x8632-arch.lisp.
;;; Describing a lock does not implement its kernel operations.
(cl:in-package :wasm32)
(cl:defconstant subtag-lock 66)
(cl:defconstant lock._value-cell 0)
(cl:defconstant lock.kind-cell 1)
(cl:defconstant lock.writer-cell 2)
(cl:defconstant lock.name-cell 3)
(cl:defconstant lock.whostate-cell 4)
(cl:defconstant lock.whostate-2-cell 5)
(cl:defconstant vectorH.logsize-cell 0)
(cl:defconstant vectorH.physsize-cell 1)
(cl:defconstant vectorH.data-vector-cell 2)
(cl:defconstant vectorH.displacement-cell 3)
(cl:defconstant vectorH.flags-cell 4)
(cl:defconstant arrayH.rank-cell 0)
(cl:defconstant arrayH.physsize-cell 1)
(cl:defconstant arrayH.data-vector-cell 2)
(cl:defconstant arrayH.displacement-cell 3)
(cl:defconstant arrayH.flags-cell 4)
(cl:defconstant arrayH.dim0-cell 5)
(cl:defconstant arrayH.flags-cell-subtag-byte (cl:byte 8 8))
