(in-package :wasm32-compiler)

(defun arch-probe-forms ()
  '((defun core-class-layout (instance)
      (let* ((wrapper (ccl::instance.class-wrapper instance))
             (class (ccl::%wrapper-class wrapper)))
        (core-collect)
        (values (ccl::%class.name class)
                (ccl::%wrapper-instance-slots wrapper)
                (ccl::%svref (ccl::instance.slots instance) 1)
                (eq (ccl::%class.own-wrapper class) wrapper)
                (eq (ccl::slot-vector.instance (ccl::instance.slots instance)) instance))))
    (defun core-key-read (function) (ccl::lfun-keyvect function))
    (defun core-key-none (x) x)
    (defun core-key-rest (&rest args) args)
    (defun core-key-empty (&key) nil)
    (defun core-key-one (&key a) a)
    (defun core-key-alias (&key ((:renamed a)) b &allow-other-keys) (list a b))
    (defun core-key-closure (x)
      (let ((function (lambda (&key a b) (list x a b))))
        (core-collect)
        (values (ccl::lfun-keyvect
                  #+32-bit-target function
                  #+64-bit-target (ccl::closure-function function))
                (funcall function :a 7 :b x))))
    (defun core-key-order (x)
      (let ((order nil))
        (values (ccl::lfun-keyvect (progn (push 1 order) (core-collect) #'core-key-one))
                order x)))
    (defun core-gf-make (function immediates)
      (ccl::%wasm-make-funcallable-instance function immediates))
    (defun core-gf-ref (function index) (ccl::nth-immediate function index))
    (defun core-gf-set (function index value)
      (ccl::set-nth-immediate function index value))
    (defun core-gf-set-moving (function index value)
      (ccl::set-nth-immediate function index (progn (core-collect) value)))
    (defun core-gf-call (function value) (funcall function value))
    (defun core-gf-closure (value) (lambda (x) (cons value x)))
    (defun core-gf-identity (x) x)
    (defun core-arch-ratio (x)
      (let ((n (ccl::%numerator x)))
        (core-collect)
        (values n (ccl::%denominator x))))
    (defun core-arch-identity (x)
      (values (ccl::immediate-p-macro x) (ccl::hashed-by-identity x)))
    (defun core-arch-symbol-identity (x)
      ;; Assert each architecture's own answer, not native equality. D1
      ;; follows x8632's symbol subtag; x8664's macro returns NIL here.
      #+32-bit-target (eq (ccl::hashed-by-identity x) (not (null x)))
      #+64-bit-target (null (ccl::hashed-by-identity x)))
    (defun core-arch-double (x)
      (let ((result (ccl::%make-dfloat)))
        (core-collect)
        (ccl::%setf-double-float result x)
        (core-collect)
        result))
    (defun core-arch-single (x)
      #+32-bit-target
      (let ((result (ccl::%make-sfloat)))
             (core-collect)
             (ccl::%setf-short-float result x)
             (core-collect)
             result)
      #+64-bit-target x)
    (defun core-arch-copy-order (x y)
      (let ((order nil))
        (values
         (ccl::%copy-double-float
          (progn (push 1 order) (core-collect) x)
          (progn (push 2 order) (core-collect) y))
         order)))
    (defun core-arch-stack-single (x)
      #+32-bit-target
      (wasm32::with-stack-short-floats ((result x))
             (core-collect)
             result)
      #+64-bit-target (ccl::%short-float x))))
