;;; Products of eight-bit pieces keep intermediate arithmetic in fixnums.
(defun %wasm-multiply-halves (a b)
  (let* ((al (logand a #xff)) (ah (ash a -8))
         (bl (logand b #xff)) (bh (ash b -8))
         (low (* al bl))
         (middle (+ (* ah bl) (* al bh) (ash low -8))))
    (values (+ (* ah bh) (ash middle -8))
            (logior (ash (logand middle #xff) 8) (logand low #xff)))))

(defun %multiply-and-add-1 (xh xl yh yl ch cl)
  (multiple-value-bind (hh hl) (%wasm-multiply-halves xh yh)
    (multiple-value-bind (mh ml) (%wasm-multiply-halves xh yl)
      (multiple-value-bind (nh nl) (%wasm-multiply-halves xl yh)
        (multiple-value-bind (lh ll) (%wasm-multiply-halves xl yl)
          (let* ((low (+ ll cl))
                 (middle (+ lh ml nl ch (ash low -16)))
                 (high (+ mh nh hl (ash middle -16))))
            (values (+ hh (ash high -16)) (logand high #xffff)
                    (logand middle #xffff) (logand low #xffff))))))))

(defun %multiply-and-add-fixnum-loop (length x y result)
  (multiple-value-bind (yh yl)
      (if (fixnump y)
        (values (logand (ash y -16) #xffff) (logand y #xffff))
        (%bignum-ref y 0))
    (let ((ch 0) (cl 0))
      (dotimes (i length)
        (multiple-value-bind (xh xl) (%bignum-ref x i)
          (multiple-value-bind (high low rh rl) (%multiply-and-add-1 xh xl yh yl ch cl)
            (%bignum-set result i rh rl)
            (setq ch high cl low))))
      (%bignum-set result length ch cl)
      result)))

(defun %multiply-and-add-harder-loop-2 (x y result i ylen)
  (multiple-value-bind (xh xl) (%bignum-ref x i)
    (let ((ch 0) (cl 0))
      (dotimes (j ylen)
        (multiple-value-bind (yh yl) (%bignum-ref y j)
          (multiple-value-bind (high low rh rl) (%multiply-and-add-1 xh xl yh yl ch cl)
            (multiple-value-bind (oldh oldl) (%bignum-ref result (+ i j))
              (let* ((lo (+ rl oldl))
                     (hi (+ rh oldh (ash lo -16)))
                     (carry (+ low (ash hi -16))))
                (%bignum-set result (+ i j) hi lo)
                (setq ch (+ high (ash carry -16)) cl (logand carry #xffff)))))))
      (%bignum-set result (+ i ylen) ch cl)
      0)))
