(module
  (type $integer (func (param i32) (result i32)))
  (type $scalars (func (param i32 i64 f32 f64) (result i32 i64 f32 f64)))
  (type $void (func))
  (memory (export "memory") 1 2)
  (table (export "callbacks") 1 8 funcref)
  (func (export "allocate") (param i32) (result i32) i32.const 16)
  (func (export "release") (param i32))
  (global $saved (mut i32) (i32.const 0))
  (global $after (mut i32) (i32.const 0))
  (func $call (export "call") (export "alias") (param i32 i32) (result i32)
    local.get 0 global.set $saved
    local.get 1 local.get 0 call_indirect (type $integer)
    global.get $after i32.const 1 i32.add global.set $after)
  (func (export "twice") (param i32 i32) (result i32)
    local.get 1 local.get 0 call_indirect (type $integer) drop
    local.get 1 local.get 0 call_indirect (type $integer)
    global.get $after i32.const 1 i32.add global.set $after)
  (func (export "saved") (param i32) (result i32)
    local.get 0 global.get $saved call_indirect (type $integer))
  (func (export "trap") (param i32 i32) (result i32)
    local.get 1 local.get 0 call_indirect (type $integer) drop unreachable)
  (func (export "scalars") (param i32 i32 i64 f32 f64) (result i32 i64 f32 f64)
    local.get 1 local.get 2 local.get 3 local.get 4 local.get 0 call_indirect (type $scalars))
  (func (export "void") (param i32)
    local.get 0 call_indirect (type $void))
  (func (export "after") (result i32) global.get $after)
)
