MODULE = 'foreign-module.mjs'
OWNER = 'collector-owner.mjs'
MUTANTS = [
 (MODULE,'table-export',"m.exports.some(e=>e.kind===1&&e.index===i&&e.name===t.export)",'true','hidden-table-export'),
 (MODULE,'callback-duplicate','!callbackTypes.has(c.name)','true','admission-callback-name-duplicate'),
 (MODULE,'callback-table-name',"d.tables.some(t=>t.export===c.table)",'true','admission-callback-table'),
 (MODULE,'callback-table-type',"typeof c.table==='string'",'true','hidden-table-table-type'),
 (MODULE,'callback-param-type',"[...c.params,...c.results]","[...c.results]",'admission-callback-param-type'),
 (MODULE,'callback-result-type',"[...c.params,...c.results]","[...c.params]",'admission-callback-result-type'),
 (MODULE,'callback-error','argumentsFor(c.error,c.results);',';','admission-callback-error-arity'),
 (MODULE,'slot-overlap','!used.has(s.parameter)','true','admission-slot-range-pointer'),
 (MODULE,'slot-type','callbackTypes.has(s.type)','true','admission-slot-type'),
 (MODULE,'slot-managed','!managedNames.has(e.name)&&!initializerNames.has(e.name)','!initializerNames.has(e.name)','admission-slot-managed'),
 (MODULE,'callback-alias','JSON.stringify(callbackSlots.get(a.name))===JSON.stringify(callbackSlots.get(b.name))','true','admission-slot-alias'),
 (MODULE,'callback-active',"c?.active&&c.type===s.type","c&&c.type===s.type",'tombstone'),
 (MODULE,'callback-kind',"c?.active&&c.type===s.type","c?.active",'affinity-type-raw'),
 (MODULE,'callback-translation','values[s.parameter]=c.index;','values[s.parameter]=0;','scalars'),
 (MODULE,'callback-admission','const result=c.admit(()=>{','const result=(()=>{','moving-0'),
 (MODULE,'callback-root','o.rootCells([root])','o.rootCells([77825])','moving-0'),
 (MODULE,'callback-root-reload','return c.roots.values()[0];','return root;','moving-0'),
 (MODULE,'callback-root-release','c.safepoint(()=>c.roots.release());',';','close'),
 (MODULE,'callback-root-scope',"need(reading,'CALLBACK_ROOT_SCOPE');",';','root-scope'),
 (MODULE,'callback-tombstone','!c.active||pendingCallback','pendingCallback','tombstone'),
 (MODULE,'callback-suppression','!c.active||pendingCallback','!c.active','failure-error'),
 (MODULE,'callback-defer','pendingCallback={error};return fallback();','throw error;','failure-error'),
 (MODULE,'callback-propagation','if(pendingCallback&&!failed)','if(false)','failure-error'),
 (MODULE,'callback-primary','if(pendingCallback&&!failed)','if(pendingCallback)','trap-primary'),
 (MODULE,'callback-fatal','if(pendingCallback?.error instanceof AggregateError)','if(false)','failure-async'),
 (MODULE,'callback-async',"if(result&&typeof result.then==='function')throw new AggregateError([], 'foreign-module: ASYNC_CALLBACK');",';','failure-async'),
 (MODULE,'callback-reset','busy=true;pendingCallback=null;','busy=true;','failure-reset'),
 (MODULE,'callback-trap',"if(error instanceof WebAssembly.RuntimeError)error=new AggregateError([error],'foreign-module: CALLBACK_TRAP',{cause:error});",';','callback-trap'),
 (MODULE,'callback-capacity',"table.length<limit",'true','capacity'),
 (MODULE,'callback-growth-rollback',"catch(error){dropCallback(c);throw error;}","catch(error){throw error;}",'growth-rollback'),
 (MODULE,'callback-install',"table.set(c.index,fn);",';','scalars'),
 (MODULE,'callback-owner-async',"if(result&&typeof result.then==='function')throw new AggregateError([], 'foreign-module: ASYNC_CALLBACK_OWNER');",';','async-owner'),
 (MODULE,'callback-retire','for(const c of liveCallbacks)dropCallback(c);',';','trap-primary'),
 (MODULE,'callback-deregister-once','if(!c.active)return false;',';','moving-0'),
 (OWNER,'callback-foreign-reentry',"!this.#callback&&!this.#boundary&&!this.#busy,'foreign reentry'","!this.#boundary&&!this.#busy,'foreign reentry'",'reentry'),
 (OWNER,'callback-finalizers',"!this.#callback&&!this.#boundary&&!this.#busy&&!this.#drainingFinalizers","!this.#boundary&&!this.#busy&&!this.#drainingFinalizers",'finalizer-drain-refusal'),
 (OWNER,'callback-leave','this.foreignBoundary.leave(frame.token);',';','moving-0'),
 (OWNER,'callback-return-state',"this.#t(32)===2&&this.#t(144)===0","this.#t(144)===0",'fatal-return-state'),
 (OWNER,'callback-return-descriptor',"this.#t(32)===2&&this.#t(144)===0","this.#t(32)===2",'fatal-return-descriptor'),
 (OWNER,'callback-return-checkpoint',"frame.offsets.every((offset,index)=>this.#t(offset)===frame.values[index])",'true','fatal-return-checkpoint'),
 (OWNER,'callback-return-heap',"    this.#validateLive();\n    this.#foreign=frame;","    this.#foreign=frame;",'fatal-return-heap'),
 (OWNER,'callback-return-token','this.#foreign=frame;',';', 'owner-throw'),
 (OWNER,'callback-return-publication','this.#set(this.tcr+144,frame.head);',';', 'owner-throw'),
 (OWNER,'callback-return-foreign','Atomics.store(new Int32Array(this.#memory.buffer),(this.tcr+32)/4,3);',';', 'owner-throw'),
 (OWNER,'callback-async',"if(result&&typeof result.then==='function')throw new AggregateError([], 'collector-owner: asynchronous callback');",';','owner-async'),
]

for offset in [8,12,16,64,76,88,116,120,124,128,132,140,148,152,156,160,164,168]:
    MUTANTS.append((OWNER,'callback-checkpoint-'+str(offset),
        'frame.offsets.every((offset,index)=>this.#t(offset)===frame.values[index])',
        'frame.offsets.every((offset,index)=>offset=='+str(offset)+'||this.#t(offset)===frame.values[index])',
        'owner-callback-checkpoint-'+str(offset)))
