(in-package :ccl)
;; Snapshot before reporting can populate PRINT-OBJECT's combined-method cache.
(setf (get 'equality-corpus :tables)
 (without-gcing
  (let ((rows nil))
   (%map-areas
    (lambda (o)
     (when (and (hash-table-p o) (hash-table-weak-p o)
                (member (hash-table-test o) '(eql equal)))
      (let ((keys nil))
       (maphash (lambda (k v) (declare (ignore v)) (push k keys)) o)
       (push (list (hash-table-test o) (hash-table-count o) keys) rows)))))
   rows)))
;; Logical objects are constructed once, so the native matrix preserves identity.
(let* ((a (copy-seq "same")) (b (copy-seq "same"))
       (sym (make-symbol "identity")) (other (make-symbol "identity"))
       (bits (make-array 9 :element-type 'bit :initial-contents '(1 0 1 1 0 0 1 0 1)))
       (opaque (make-hash-table :test 'eq))
       (objects (vector nil t 0 1 2 30 -1 536870911 -536870912
          (expt 2 80) (+ (expt 2 80) 0) (- (expt 2 80)) (+ (expt 2 80) 1)
          0.0s0 -0.0s0 0.0d0 -0.0d0 1.0s0 1.0d0
          (host-single-float-from-unsigned-byte-32 #x7fc12345)
          (host-single-float-from-unsigned-byte-32 #x7fc12345)
          (host-single-float-from-unsigned-byte-32 #x7fc12346)
          a b a "different" #\A #\a sym other sym
          (cons 7 nil) (cons 7 nil) (list a 1 2) (list b 1 2) (list b 1 3)
          bits (copy-seq bits) (make-array 9 :element-type 'bit :initial-element 1)
          (vector 1 2) (vector 1 2)
          1/3 1/3 2/3 #c(1 2) #c(1 2) #c(1 3))))
 (labels ((val (x)
   (cond ((null x)(write-string "{\"immediate\":77825}"))
         ((eq x t)(write-string "{\"immediate\":77838}"))
         ((and(integerp x)(<= -536870912 x 536870911))(format t "{\"immediate\":~d}"(logand #xffffffff(ash x 2))))
         ((characterp x)(format t "{\"character\":~d}"(char-code x)))
         (t (let((id(position x objects :test #'eq)))
              (if id (format t "{\"ref\":~d}" id) (emit x))))))
          (emit (x)
   (cond ((integerp x)(format t "{\"integer\":\"~d\"}" x))
         ((floatp x)(multiple-value-bind(hi lo)(double-float-bits (if(typep x 'double-float)x 0.0d0))
          (if(typep x 'single-float)(format t "{\"single\":~d}"(logand #xffffffff(single-float-bits x)))
           (format t "{\"double\":[~d,~d]}"(logand #xffffffff lo)(logand #xffffffff hi)))))
         ((symbolp x)(format t "{\"opaque\":~d,\"kind\":\"symbol\"}" (or (gethash x opaque) (setf (gethash x opaque) (hash-table-count opaque)))))
         ((consp x)(write-string "{\"cons\":[")(val(car x))(write-char #\,)(val(cdr x))(write-string "]}"))
         ((typep x 'simple-string)(format t "{\"string\":[~{~d~^,~}]}"(map 'list #'char-code x)))
         ((typep x 'simple-bit-vector)(format t "{\"bits\":[~{~d~^,~}]}"(coerce x 'list)))
         ((typep x 'simple-vector)(write-string "{\"vector\":[")(loop for v across x for i from 0 do(unless(zerop i)(write-char #\,))(val v))(write-string "]}"))
         ((ratiop x)(write-string "{\"ratio\":[")(val(numerator x))(write-char #\,)(val(denominator x))(write-string "]}"))
         ((complexp x)(write-string "{\"complex\":[")(val(realpart x))(write-char #\,)(val(imagpart x))(write-string "]}"))
         ((typep x 'standard-object)(format t "{\"opaque\":~d,\"kind\":\"instance\"}" (or (gethash x opaque) (setf (gethash x opaque) (hash-table-count opaque)))))
         (t(error "unsupported corpus value ~s" (type-of x))))))
  ;; Native EQUAL hashing performs FP arithmetic on NaNs at default mask.
  ;; Preserve that boundary; predicate bits and masked hash values are the
  ;; semantic oracle here. This leaf does not reproduce native hash FP traps.
  (let ((seen nil))
   (handler-case (setf (gethash (aref objects 19) (make-hash-table :test 'equal)) 17)
    (floating-point-invalid-operation () (setf seen t)))
   (assert seen))
  (set-fpu-mode :invalid nil :division-by-zero nil :overflow nil :underflow nil :inexact nil)
  ;; Check the native hash implementation agrees with the predicate matrix.
  (dolist (test '(eql equal))
   (loop for x across objects do
    (loop for y across objects do
     (let ((table (make-hash-table :test test)))
      (setf (gethash x table) 17)
      (multiple-value-bind (value present) (gethash y table)
       (assert (eq present (funcall test x y)))
       (assert (eql value (if present 17 nil))))
      (setf (gethash y table) 21)
      (assert (= (hash-table-count table) (if (funcall test x y) 1 2)))))))
  (write-string "CORPUS|")
  (write-string "{\"objects\":[")
  (loop for x across objects for i from 0 do
   (unless(zerop i)(write-char #\,))
   (let((first(position x objects :test #'eq)))
    (cond ((or(null x)(eq x t)(characterp x)(and(integerp x)(<= -536870912 x 536870911)))(val x))
          ((< first i)(format t "{\"ref\":~d}" first))
          (t(emit x)))))
  (write-string "],\"eql\":[")
  (loop for x across objects for i from 0 do(unless(zerop i)(write-char #\,))(write-char #\[)
   (loop for y across objects for j from 0 do(unless(zerop j)(write-char #\,))(princ(if(eql x y)1 0)))(write-char #\]))
  (write-string "],\"equal\":[")
  (loop for x across objects for i from 0 do(unless(zerop i)(write-char #\,))(write-char #\[)
   (loop for y across objects for j from 0 do(unless(zerop j)(write-char #\,))(princ(if(equal x y)1 0)))(write-char #\]))
  (write-string "],\"bootstrap\":[")
  (loop for row in (get 'equality-corpus :tables) for i from 0 do
   (unless (zerop i) (write-char #\,))
   (format t "{\"test\":\"~(~a~)\",\"count\":~d,\"keys\":[" (first row) (second row))
   (loop for key in (third row) for j from 0 do
    (unless (zerop j) (write-char #\,)) (val key))
   (write-string "],\"copies\":[")
   (loop for key in (third row) for j from 0 do
    (unless (zerop j) (write-char #\,))
    (let ((copy (if (eq (first row) 'equal) (copy-tree key) key)))
     (assert (funcall (first row) key copy)) (val copy)))
   (write-string "]}"))
  (write-string "]}")(terpri)))
(quit)
