(in-package :wasm32-compiler)

(defvar *core-candidates* nil)
(defvar *core-native-forms* nil)
(defvar *core-native-read-skips* nil)

(defun core-body (form)
  (let ((body (cdddr form)))
    (when (stringp (car body)) (pop body))
    (loop while (and (consp (car body)) (eq (caar body) 'declare)) do (pop body))
    body))

(defun core-read-native-forms (chunks)
  (let ((forms (make-hash-table :test #'eq)))
    (dolist (row chunks)
      (let ((*package* (find-package "CCL")) (*read-eval* nil))
        (with-input-from-string (s (third row))
          (loop
            (let ((offset (file-position s)) (end (gensym)))
              (handler-case
                  (let ((form (read s nil end)))
                    (when (eq form end) (return))
                    (when (consp form)
                      (case (car form)
                        (in-package (setq *package* (find-package (second form))))
                        (defun (when (symbolp (second form))
                                 (setf (gethash (second form) forms) form))))))
                (error (c)
                  (push (list (first row) offset (type-of c) (format nil "~a" c)) *core-native-read-skips*)
                  (let ((next (loop for i from (max (1+ offset) (file-position s)) below (length (third row))
                                    when (and (char= (char (third row) i) #\()
                                              (char= (char (third row) (1- i)) #\Newline)) return i)))
                    (unless next (return))
                    (file-position s next)))))))))
    forms))

(defun core-check-body (form result)
  (when (eq (car form) 'defun)
    (let* ((name (second form)) (body (core-body form))
           (native (gethash name *core-native-forms*)))
      (when (and (null body) (or (null native) (core-body native)))
        (refuse :bootstrap-empty-target-body))
      (when (and (= (length body) 1) (consp (car body))
                 (eq (caar body) name)
                 ;; An actual lowering removes the self call from the module.
                 (or (getf result :dependencies) (getf result :self-call)))
        (refuse :bootstrap-self-only-body)))))
