(defpackage :ccl-target-types (:use :cl))
(in-package :ccl-target-types)
(defvar *trace* nil)
(defvar *phase* nil)
(defvar *event* nil)
(defun obj (&rest xs) (apply #'ccl-target-helpers::obj xs))
(defun syntax (x) (ccl-target-helpers::syntax x))
(defun trace-row (helper &rest fields)
  (push (apply #'obj "helper" helper "phase" *phase* "event" *event*
               "context" (ccl-source-traversal::context) fields) *trace*))
(defun definition (form body)
  (list (second form) (third form) `(block ,(second form) ,body)))
(defun build (helper range macro typep-form form-type target-type mode)
  (let* ((leaf (copy-tree (cdr target-type)))
         (eql-local (copy-tree (cdr helper)))
         (typep-local (definition typep-form
           `(let ((requested ccl::type))
              (let ((answers (multiple-value-list (progn ,@(cdddr typep-form)))))
                (trace-row "NX-FORM-TYPEP" "form" (syntax ccl::arg) "requested" (syntax requested)
                           "query" (syntax ccl::type) "answers" (mapcar #'ccl-target-helpers::bool answers))
                (values-list answers)))))
         (form-local (definition form-type
           `(let ((answer (progn ,@(cdddr form-type))))
              (trace-row "NX-FORM-TYPE" "form" (syntax ccl::form) "answer" (syntax answer)) answer))))
    (setf (first leaf) 'leaf-target-type)
    (ccl-census-macros::native-function
      `(lambda (form env)
         (let ((*event* (1- ccl-source-expanders::*next-event*)))
           (flet ((ccl::fixnump ,@(cddr range))
                  ,@(when (equal mode "trust") '((ccl::nx-trust-declarations (env) (declare (ignore env)) t))))
             (labels (,leaf
                      (ccl::nx-target-type (typespec)
                        (let ((answer
                                ,(if (equal mode "shallow") '(leaf-target-type typespec)
                                  `(if (and (consp typespec) (member (car typespec) '(or and not)))
                                     (cons (car typespec) (mapcar #'ccl::nx-target-type (cdr typespec)))
                                     ,(if (equal mode "host-range")
                                        '(if (eq typespec 'fixnum) '(signed-byte 61) (leaf-target-type typespec))
                                        '(leaf-target-type typespec))))))
                          (trace-row "NX-TARGET-TYPE" "input" (syntax typespec) "answer" (syntax answer)) answer))
                      ,form-local ,typep-local ,eql-local)
               (funcall (function ,(ccl::parse-macro-1 (second macro) (third macro) (cdddr macro))) form env))))))))
(defparameter *cases*
  '(("symbol" symbol 0) ("character" character 0) ("fixnum" fixnum 0)
    ("signed-30" (signed-byte 30) 0) ("signed-31" (signed-byte 31) 0)
    ("positive-boxed" (integer 536870912 536870912) 0)
    ("negative-boxed" (integer -536870913 -536870913) 0)
    ("single-float" single-float 0) ("double-float" double-float 0)
    ("mixed-boxed" (or symbol (integer 536870912 536870912)) 0)
    ("mixed-immediate" (or symbol (integer 0 5)) 0)
    ("unknown" t 0) ("symbol-members" (member :foo :bar) 0) ("literal-fixnum" (member fixnum) 0)
    ("untrusted-symbol" symbol 3)))
(defun probe (case)
  (destructuring-bind (name type safety) case
    (let* ((*phase* name) (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
           (form `(lambda (ccl::x ccl::y) (declare (type ,type ccl::x) (optimize (safety ,safety) (speed 3)))
                    (eql ccl::x ccl::y)))
           (afunc (ccl-source-expanders::with-routing
                    (lambda () (ccl-census-stub::capture-lambda form 'ccl::type-probe)))))
      (ccl-target-helpers::obj "name" name "type" (ccl-target-helpers::syntax type) "safety" safety
         "form" (ccl-target-helpers::syntax form) "operators" (ccl-target-helpers::operators (ccl::afunc-acode afunc))
         "function" (ccl-startup-census::function-observation afunc) "events" ccl-source-expanders::*events*))))
(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (ccl-source-expanders::*registry* nil) (ccl-source-expanders::*compiled* nil)
        (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
        (ccl-source-expanders::*literals* nil) (ccl-target-helpers::*sources* nil)
        (ccl-target-helpers::*calls* nil) (*trace* nil)
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
        (globals (mapcar #'fdefinition '(ccl::eql-iff-eq-p ccl::nx-form-typep ccl::nx-form-type ccl::nx-target-type))))
    (ccl-source-expanders::prepare)
    (dolist (r (reverse ccl-source-expanders::*registry*)) (ccl-target-helpers::ident (third r)) (ccl-target-helpers::ident (fourth r)))
    (let* ((helper (ccl-target-helpers::read-form "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
           (range (ccl-target-helpers::read-form "compiler/nx0.lisp" "defun nx1-target-fixnump"))
           (macro (ccl-target-helpers::read-form "compiler/optimizers.lisp" "define-compiler-macro eql"))
           (typep-form (ccl-target-helpers::read-form "compiler/nx0.lisp" "defun nx-form-typep"))
           (form-type (ccl-target-helpers::read-form "compiler/nx0.lisp" "defun nx-form-type"))
           (target-type (ccl-target-helpers::read-form "compiler/nx-basic.lisp" "defun nx-target-type"))
           (lookup (ccl-target-helpers::read-form "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
           (stream-macro (ccl-target-helpers::read-form "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
           (vector-macro (ccl-target-helpers::read-form "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
           (entry (ccl-target-helpers::compiler-entry 'eql))
           (mode (or (ccl:getenv "CCL_TYPE_MODE") "normal")) (functions nil))
      (ccl-source-expanders::with-compiler-observation
        (lambda ()
          (setf functions (cons (cons "prior" (ccl-target-helpers::build-eql helper range macro))
                            (loop for m in '("normal" "shallow" "host-range" "trust")
                                  collect (cons m (build helper range macro typep-form form-type target-type m)))))
          (setf (third (ccl-target-helpers::compiler-entry 'ccl::basic-stream-p)) (ccl-target-helpers::build-stream lookup stream-macro)
                (third (ccl-target-helpers::compiler-entry 'vectorp)) (ccl-target-helpers::build-stream lookup vector-macro))))
      (dolist (pair functions) (ccl-target-helpers::ident (cdr pair)))
      (setf (third entry) (or (cdr (assoc mode functions :test #'equal)) (error "TYPE-MODE")))
      (let ((*phase* "dumplisp")) (ccl-source-expanders::with-routing #'ccl-census-descriptions::run))
      (let ((rows (ccl-census-descriptions::with-descriptions
                    (lambda () (ccl-census-stub::with-target-state
                      (lambda () (mapcar #'probe *cases*)))))))
        (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                     (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                     (every #'eq globals (mapcar #'fdefinition '(ccl::eql-iff-eq-p ccl::nx-form-typep ccl::nx-form-type ccl::nx-target-type))))
          (error "TYPE-STATE-NOT-RESTORED"))
        (with-open-file (out (ccl:getenv "CCL_TYPE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
          (ccl-startup-census::json
            (obj "version" 1 "probes" rows "trace" (reverse *trace*) "sources" (reverse ccl-target-helpers::*sources*)
                 "events" ccl-source-expanders::*events* "selected_id" (ccl-target-helpers::ident (third entry))
                 "compiled" (loop for (name . fn) in functions collect
                              (obj "mode" name "id" (ccl-target-helpers::ident fn)
                                   "function" (cdr (assoc fn ccl-source-expanders::*compiled* :test #'eq))))
                 "restored" :true "macro_environment_qualified" :false "graph_edges_replaced" 0) out)
          (terpri out))))))
