;;; These are collector controls, not additions to the original-definition count.
(in-package :wasm32-compiler)

(defun core-collect () nil)

(defun core-probe-forms ()
   '((defun core-byte-store (v i value)
      (declare (type (simple-array (unsigned-byte 8) (*)) v))
      (setf (aref v i) value))
    (defun core-computed-call (f x) (funcall f x))
    (defun core-computed-inner (f x) (cons (funcall f x) nil))
    (defun core-computed-apply (f x) (apply f (list x)))
    (defun core-computed-inner-apply (f x) (cons (apply f (list x)) nil))
    (defun core-eql (x y) (eql x y))
    (defun core-zero (x) (zerop x))
    (defun core-positive-loop (x)
      (do ((i x (1- i))) ((not (ccl::int>0-p i)) i)))
    (defun core-izerop (x) (ccl::%izerop x))
    (defun core-numeric-ir (x y)
      (values (ccl::+-2 x y) (ccl::--2 x y) (ccl::*-2 x y) (ccl::/-2 x y)
              (ccl::<-2 x y) (ccl::<=-2 x y) (ccl::=-2 x y)
              (ccl::/=-2 x y) (ccl::>=-2 x y) (ccl::>-2 x y)))
    (defun core-byte-order (v)
      (declare (type (simple-array (unsigned-byte 8) (*)) v))
      (let ((effects nil))
        (values (setf (aref (the (simple-array (unsigned-byte 8) (*)) (progn (push 1 effects) v))
                           (progn (push 2 effects) (core-collect) 3))
                      (progn (push 3 effects) (core-collect) 2))
                effects v)))
    (defun core-ilognot (x) (ccl::%ilognot x))
    (defun core-fixnum-less (x y) (declare (fixnum x y)) (< x y))
    (defun core-format-order (x)
      (let ((effects nil))
        (handler-case
            (error (progn (push 1 effects) "~s ~s")
                   (progn (push 2 effects) x)
                   (progn (push 3 effects) (core-collect) x))
          (simple-error (c)
            (values effects (simple-condition-format-arguments c))))))
    (defun core-format-decline (x)
      (let ((seen nil))
        (values (handler-bind ((simple-condition
                                (lambda (c) (setq seen (simple-condition-format-arguments c)))))
                  (signal "~s" x))
                seen)))
    (defun core-simple-initargs (x)
      (handler-case
          (error 'simple-error :format-control "~s" :format-arguments (list x)
                               :format-control "ignored")
        (simple-error (c)
          (values (simple-condition-format-control c) (simple-condition-format-arguments c)))))
    (defun core-format-error (x)
       (handler-case (error "Bad argument: ~s" x)
         (simple-error (c) (values (simple-condition-format-control c)
                                  (simple-condition-format-arguments c)))))
    (defun core-format-signal (x)
      (handler-case (signal "Notice: ~s" x)
        (simple-condition (c) (values (simple-condition-format-control c)
                                     (simple-condition-format-arguments c)))))
    (defun core-format-collect (x)
      (handler-case (error "Bad argument: ~s" (progn (core-collect) x))
        (simple-error (c)
          (core-collect)
          (values (simple-condition-format-control c)
                  (simple-condition-format-arguments c)))))
    (defun core-type-error (x)
      (handler-case (error 'type-error :datum x :expected-type 'integer)
        (type-error (c) (values (type-error-datum c) (type-error-expected-type c)))))
    (defun core-dynamic-format (control x)
      (handler-case (signal control x)
        (simple-condition (c) (values (simple-condition-format-control c)
                                     (simple-condition-format-arguments c)))))
    (defun core-schar (string index) (schar string index))
    (defun core-char-code (char) (char-code char))
    (defun core-code-char (code) (code-char code))
    (defun core-set-char (string index char) (setf (schar string index) char))
    (defun core-access (x i) (ccl::%svref x i))
    (defun core-struct-access (x) (ccl::struct-ref x 0))
    (defun core-slot-access (x) (ccl::%slot-ref x 0))
    (defun core-integer-divide (a b) (/ a b))
    (defun core-divide-order (a b)
      (let ((order nil))
        (let ((answer (/ (progn (push 1 order) a)
                         (progn (core-collect) (push 2 order) b))))
          (values answer order a b))))
    (defun core-divide-zero (a b)
      (let ((clean nil))
        (values (handler-case (unwind-protect (/ a b) (setq clean t))
                  (division-by-zero () :zero)
                  (type-error (c)
                    (list :type (type-error-datum c)
                                (type-error-expected-type c))))
                clean)))
    (defun core-register (name info)
      (let ((ccl::*istruct-cells* nil))
        (let ((cell (ccl::register-istruct-cell name)))
          (ccl::set-istruct-cell-info cell info)
          (core-collect)
          (values (eq cell (ccl::register-istruct-cell name)) (cdr cell)))))
    (defun core-symbol-state (name value)
      (values (boundp name)
              (progn (ccl::%set-sym-value name value) (core-collect)
                     (values (boundp name) (ccl::%sym-value name)))
              (ccl::%sym-global-value name)))
    (defun core-less (a b) (< a b))
    (defun core-ldb (x)
      (values (ldb (byte 8 8) x) (ldb (byte 29 0) x)
              (ldb (byte 4 50) x) (ldb (byte 0 0) x)))
    (defun core-logical-error (x)
      (handler-case (logand x 7)
        (type-error (c) (core-collect)
          (values (type-error-datum c) (type-error-expected-type c)))))
    (defun core-assq (key alist) (ccl::assq key alist))
    (defun core-logical (a b)
      (values (logand a b) (logior a b) (logand a b -1) (logior a b 16)
              (logand) (logior)))
    (defun core-subtract-call (a b c)
      (let ((order nil))
        (values (- (progn (push 1 order) a)
                   (progn (core-collect) (push 2 order) b)
                   (progn (push 3 order) c))
                (- a) order)))
    (defun core-type-tests (x)
      (values (typep x 'integer) (typep x '(integer 0 255))
              (typep x '(or null string)) (typep x '(and integer (not (eql 7))))
              (typep x '(unsigned-byte 8)) (typep x '(member nil t 7))))
    (defun core-require-integer (x)
      (handler-case (ccl::require-type (progn (core-collect) x) 'integer)
        (type-error (c) (values :type (type-error-datum c) (type-error-expected-type c)))))
    (defun core-badarg (x)
      (handler-case (ccl::%badarg x 'integer)
        (type-error (c) (core-collect) (values :type (type-error-datum c) (type-error-expected-type c)))))
    (defun core-node-size () target::node-size)
    (defun core-gvector (x)
      (ccl::%gvector target::subtag-simple-vector x (progn (core-collect) x)))
    (defun core-ref (x)
      (ccl::%svref x (progn (core-collect) 1)))
    (defun core-set (x y)
      (ccl::%svset x (progn (core-collect) 0)
                  (progn (core-collect) y))
      x)
    (defun core-struct (x)
      (let ((structure (ccl::%gvector target::subtag-struct nil x)))
        (core-collect)
        (ccl::struct-ref structure 1)))
    (defun core-slot (x)
      (ccl::%slot-ref (ccl::%gvector target::subtag-slot-vector x)
                     (progn (core-collect) 0)))
    (defun core-cleanup (x)
      (unwind-protect
          (ccl::%gvector target::subtag-simple-vector x x)
        (core-collect)))
    (defun core-transfer (x)
      (catch 'done
        (ccl::%gvector target::subtag-simple-vector
                      x (progn (core-collect) (throw 'done x)))))))

(defun core-add-probes (native-forms)
  (dolist (form (cons '(defun core-collect () nil) (core-probe-forms)))
    (let* ((name (second form))
           (wire (if (eq name 'core-collect) "collector_probe"
                     (string-downcase (substitute #\_ #\- (symbol-name name)))))
           (result (call-with-target (lambda () (compile-bootstrap-form form wire nil)))))
      (setf (getf result :source-name) name)
      (push (list form result) *core-candidates*)
      (setf (gethash name *core-native-functions*)
            (ccl::compile-named-function
             (bootstrap-function-form (if (eq name 'core-collect) form
                                        (find name native-forms :key #'second))) :name name)))))
