;;; Native CCL's UTF-8 codec is the string oracle, independent of the JS codec.
(in-package "CCL")
#-wasm32-target
(progn
  (defvar *fs-native-request* (symbol-function '%wasm-host-process-request))
  (defun fs-native-request (selector operation payload)
    (if (member operation '(10 11))
      (let* ((buffer (gethash (svref payload 0) *fa-tokens*))
             (storage (svref buffer 2)) (offset (svref payload 1)))
        (unless (and (svref buffer 3) (svref (svref buffer 1) 1)
                     (eql (svref payload 3) 0) (typep offset '(integer 0 *)))
          (return-from fs-native-request -1))
        (if (= operation 10)
          (let ((bytes (encode-string-to-octets (svref payload 2) :external-format :utf-8)))
            (if (> (+ offset (length bytes)) (length storage)) -1
              (progn (replace storage bytes :start1 offset) (length bytes))))
          (let ((size (svref payload 2)))
            (if (or (minusp size) (> (+ offset size) (length storage))) -1
              (handler-case
                (let* ((text (decode-string-from-octets storage :start offset :end (+ offset size) :external-format :utf-8))
                       (bytes (encode-string-to-octets text :external-format :utf-8)))
                  (if (and (= size (length bytes))
                           (loop for i below size always (= (aref bytes i) (aref storage (+ offset i)))))
                    (progn (setf (svref payload 4) text) 0) -1))
                (error () -1))))))
      (funcall *fs-native-request* selector operation payload)))
  (setf (symbol-function '%wasm-host-process-request) #'fs-native-request))

(defun fs-row (name value) (format t "FS-ROW ~A ~S~%" name value))
(defun fs-codes (string) (loop for ch across string collect (char-code ch)))
(defun fs-string () (coerce (mapcar #'code-char '(65 0 233 8364 127757 65279 1114111)) 'string))
(let ((library (open-wasm-library "example")))
  (with-wasm-buffer (h library 64)
    (let* ((text (fs-string)) (alias (cons text text)) (closure (lambda () text)) (*fa-binding* text))
      (fs-row 'bytes (write-wasm-string h text :encoding :utf-8 :offset 3))
      (wasm-call library "echo" 1 2 3.0f0 4.0d0)
      (fs-row 'octets (coerce (read-wasm-buffer h 18 3) 'list))
      (fs-row 'unicode (fs-codes (read-wasm-string h 18 :encoding :utf-8 :offset 3)))
      (fs-row 'roots (list (eq text (car alias)) (eq text (cdr alias)) (eq text (funcall closure))
                           (eq text *fa-binding*) (fs-codes text))))
    (fs-row 'empty (list (write-wasm-string h "" :encoding :utf-8 :offset 64)
                         (length (read-wasm-string h 0 :encoding :utf-8 :offset 64))))
    (fs-row 'bom (progn (write-wasm-string h (coerce (list (code-char 65279) #\A) 'string) :encoding :utf-8)
                        (fs-codes (read-wasm-string h 4 :encoding :utf-8))))
    (fs-row 'missing-encoding (handler-case (write-wasm-string h "x") (error () :caught)))
    (fs-row 'wrong-encoding (handler-case (read-wasm-string h 1 :encoding :latin-1) (error () :caught)))
    (fs-row 'write-bounds (handler-case (write-wasm-string h "é" :encoding :utf-8 :offset 63) (error () :caught)))
    (fs-row 'read-bounds (handler-case (read-wasm-string h 2 :encoding :utf-8 :offset 63) (error () :caught)))
    (fs-row 'preserved (fs-codes (read-wasm-string h 4 :encoding :utf-8)))
    (write-wasm-buffer h (make-array 3 :element-type '(unsigned-byte 8) :initial-contents '(237 160 128)))
    (fs-row 'malformed (handler-case (read-wasm-string h 3 :encoding :utf-8) (error () :caught)))
    (fs-row 'recovered (list (write-wasm-string h "ok" :encoding :utf-8)
                             (fs-codes (read-wasm-string h 2 :encoding :utf-8)))))
  (with-wasm-buffer (h library 4097)
    (fs-row 'long (list (write-wasm-string h (make-string 4097 :initial-element #\a) :encoding :utf-8)
                        (length (read-wasm-string h 4097 :encoding :utf-8)))))
  (let ((h (allocate-wasm-buffer library 8)))
    (release-wasm-buffer h)
    (fs-row 'released (handler-case (read-wasm-string h 0 :encoding :utf-8) (error () :caught)))))
(write-line "FS-PASS")
