;;; Isolated LL10 pass-2 extension, appended to the reviewed B backend.
(in-package "WASM32-COMPILER")
(defun pool-literal-p (x)
  (and (not (or (null x) (eq x t)
                (and (integerp x) (<= -536870912 x 536870911))))
       (or (integerp x) (floatp x) (characterp x) (consp x)
           (typep x 'simple-array))))
(defun pool-plan ()
  (setf *pool-layouts* nil)
  (dolist (entry (reverse *b-functions*))
    (let ((values nil) (children nil))
      (labels ((visit (x)
                 (cond ((ccl::acode-p x)
                        (let ((op (ccl::acode-operator-name (ccl::acode-operator x)))
                              (args (ccl::acode-operands x)))
                          (cond ((eq op 'ccl::immediate)
                                 (when (pool-literal-p (first args))
                                   (unless (member (first args) values :test #'eq)
                                     (setq values (append values (list (first args)))))))
                                ((member op '(ccl::closed-function ccl::simple-function))
                                 (pushnew (first args) children :test #'eq))
                                (t (when (member op '(ccl::flet ccl::labels))
                                     (dolist (child (second args)) (pushnew child children :test #'eq)))
                                   (mapc #'visit args)))))
                       ((consp x) (mapc #'visit x)))))
        (visit (ccl::afunc-acode (first entry))))
      (dolist (child children)
        (let ((pool (cdr (assoc child *pool-layouts* :test #'eq))))
          (when pool (setq values (append values (list pool))))))
      (push (cons (first entry) (and values (coerce values 'simple-vector))) *pool-layouts*))))
(defun pool-load (value)
  (let* ((pool (cdr (assoc *pool-current* *pool-layouts* :test #'eq)))
         (index (position value pool :test #'eq)) (tmp (temporary)))
    (unless index (refuse :constant-pool-identity))
    (b-wat "(block (result i32) (local.set ~a (call $object_base (i32.load offset=24 (call $object_base (i32.load offset=40 (local.get $context)) (i32.const 32) (i32.const 1578))) (i32.const ~d) (i32.const ~d))) (i32.load offset=~d (local.get ~a)))"
      tmp (* 8 (ceiling (+ 4 (* 4 (length pool))) 8)) (+ 250 (* 256 (length pool))) (+ 4 (* 4 index)) tmp)))
(defun pool-child-load (afunc)
  (let ((pool (cdr (assoc afunc *pool-layouts* :test #'eq))))
    (if pool (pool-load pool) "(i32.const 77825)")))
(defun compile-call-form (form name links)
  (unless (and (every (lambda (s) (and (stringp s) (<= 1 (length s) 64)
                    (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyz0123456789_-")) s))) links)
               (= (length links) (length (remove-duplicates links :test #'equal)))) (refuse :b-link-names))
  (call-with-target
    (lambda ()
      (let* ((*b-call-mode* t) (*b-special-names* '(ccl::%handlers%)) (*b-keywords* nil)
             (*module-result-tag* (gensym "B-CALL")) (*module-name* name)
             (*package* (find-package "WASM32-COMPILER"))
             (*b-call-links* (mapcar (lambda (x) (list (intern (string-upcase x) *package*) x)) links)))
        (setq form (b-expand-conditions form))
        (validate-b-source form)
        (catch *module-result-tag*
          (ccl::compile-named-function (b-normalize-literal-apply form) :name name :target :wasm32 :policy ccl::*default-compiler-policy*)
          (refuse :b-no-output))))))
(defun compile-call-module (source-text name links)
  (let ((*read-eval* nil) (*package* (find-package "WASM32-COMPILER")))
    (multiple-value-bind (form end) (read-from-string source-text)
      (unless (every (lambda (c) (find c '(#\Space #\Tab #\Newline #\Return))) (subseq source-text end)) (refuse :b-source))
      (compile-call-form form name links))))
