(in-package "WASM32-COMPILER")
(load (merge-pathnames "export.lisp" *load-pathname*))
(setq *pool-symbol-owners* (list (cons (intern "POOL-OWNER") "WASM32-COMPILER::POOL-OWNER")
                                (cons (intern "pool-owner") "WASM32-COMPILER::pool-owner")))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (cycle (cons 7 nil))
       (a (copy-seq "pool")) (b (copy-seq "pool"))
       (shared (vector cycle cycle a b))
       (modules nil) (native nil))
  (setf (cdr cycle) cycle)
  (let ((cases (list
     (cons "tail_pool" `(lambda (xs) (labels ((walk (ys) (if ys (apply (lambda (zs) (if zs (walk zs) ',a)) (cdr ys) nil) ',a))) (walk xs))))
     (cons "mutate_pool" '(lambda (p) (rplaca p 11) p))
     (cons "integer" '(lambda () 536870912))
     (cons "negative" '(lambda () -9223372036854775809))
     (cons "string" `(lambda () ',a))
     (cons "character" `(lambda () ,(code-char #x1f642)))
     (cons "float" `(lambda () ,(ccl::host-single-float-from-unsigned-byte-32 #x7fc12345)))
     (cons "cycle" `(lambda () ',cycle))
     (cons "sharing" `(lambda () ',shared))
     (cons "closure" `(lambda () (lambda () ',a)))
     (cons "captured" `(lambda (x) (lambda () (values x ',a))))
     (cons "apply_literal" `(lambda () (apply (lambda () ',a) nil)))
     (cons "captured_apply" `(lambda (x) (apply (lambda () (values x ',a)) nil)))
     (cons "flet_constant" `(lambda (x) (flet ((f () (values x ',a))) (f))))
     (cons "grandchild" `(lambda () (lambda () (lambda () ',a))))
     (cons "many" `(lambda () (values ',a ',cycle 536870912)))
     (cons "vector" `(lambda () ',(make-array 3 :element-type '(unsigned-byte 16) :initial-contents '(0 65535 256)))))))
    (flet ((add (name value)
             (setq cases (append cases (list (cons name (list 'lambda nil (list 'quote value))))))))
      (add "cold" (vector a cycle (car (first *pool-symbol-owners*))))
      (add "owners" (vector (car (first *pool-symbol-owners*)) (car (second *pool-symbol-owners*)) (car (first *pool-symbol-owners*))))
      (loop for n in '(-536870912 536870911 -536870913 536870912 2147483647 2147483648 -2147483648 -2147483649 4294967295 4294967296 -4294967296 9223372036854775808) for i from 0 do
        (add (format nil "int_~d" i) n))
      (loop for bits in '(#x00000000 #x80000000 #x00000001 #x007fffff #x00800000 #x3f800000 #x7f7fffff #x7f800000 #xff800000 #x7fc12345) for i from 0 do
        (add (format nil "single_~d" i) (ccl::host-single-float-from-unsigned-byte-32 bits)))
      (loop for bits in '(#x0000000000000000 #x8000000000000000 #x0000000000000001 #x000fffffffffffff #x0010000000000000 #x3ff0000000000000 #x7fefffffffffffff #x7ff0000000000000 #xfff0000000000000 #x7ff8123456789abc) for i from 0 do
        (add (format nil "double_~d" i) (ccl::double-float-from-bits (ldb (byte 32 32) bits) (ldb (byte 32 0) bits))))
      (add "empty_string" "") (add "unicode_string" (coerce (mapcar #'code-char '(0 65 #x1f642 #x10ffff)) 'string))
      (add "empty_vector" #())
      (loop for (type values) in '((bit (1 0 1 1 0 1 0 0 1)) ((unsigned-byte 8) (0 255 17)) ((signed-byte 8) (-128 127 0))
               ((unsigned-byte 16) (0 65535 256)) ((signed-byte 16) (-32768 32767 0))
               ((unsigned-byte 32) (0 4294967295 2147483648)) ((signed-byte 32) (-2147483648 2147483647 0))
               (fixnum (-536870912 536870911 7))
               (single-float (0.0f0 -0.0f0 1.0f0)) (double-float (0.0d0 -0.0d0 1.0d0))
               ((complex single-float) (#c(1.0f0 -0.0f0) #c(-1.0f0 2.0f0)))
               ((complex double-float) (#c(1.0d0 -0.0d0) #c(-1.0d0 2.0d0))))
            for i from 0 do
        (add (format nil "vec_~d" i) (make-array (length values) :element-type type :initial-contents values))
        (add (format nil "empty_vec_~d" i) (make-array 0 :element-type type))))
    (dolist (row cases)
      (format t "POOL-COMPILING ~a~%" (car row))
      (let* ((result (compile-call-form (cdr row) (car row) (mapcar #'car cases)))
             (all (cons result (getf result :children)))
             (fn (compile nil (cdr row)))
             (vals (cond ((equal (car row) "tail_pool") (multiple-value-list (funcall fn (make-list 40))))
                         ((equal (car row) "mutate_pool") (multiple-value-list (funcall fn (cons 7 nil))))
                         ((member (car row) '("captured_apply" "flet_constant") :test #'equal) (multiple-value-list (funcall fn 17)))
                         ((equal (car row) "grandchild") (multiple-value-list (funcall (funcall (funcall fn)))))
                         ((equal (car row) "captured") (multiple-value-list (funcall (funcall fn 17))))
                         ((equal (car row) "closure") (multiple-value-list (funcall (funcall fn))))
                         (t (multiple-value-list (funcall fn))))))
        (push (cons (car row) vals) native)
        (dolist (module all)
          (push module modules)
          (with-open-file (s (concatenate 'string out (getf module :name) ".wat") :direction :output :if-exists :error)
            (write-string (getf module :wat) s)))))
    (setq modules (nreverse modules) native (nreverse native))
    (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
      (write-char #\[ s)
      (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"top\":~a}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false")))
      (write-char #\] s))
    (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error)
      (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
    (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
      (write-pool-graph s (mapcar (lambda (x) (coerce (cdr x) 'vector)) native))))
)
(let ((refusals nil))
  (dolist (source '("(lambda (x) (case x (nil 1) (t 2)))"
                    "(lambda () (list 1 2))"
                    "(lambda () (the fixnum 3))"
                    "(lambda () 1) (lambda () 2)"))
    (handler-case (progn (compile-call-module source "refused" nil)
                         (error "Unexpected source admission: ~a" source))
      (unsupported-wasm32-code (c)
        (push (string-downcase (symbol-name (unsupported-operation c))) refusals))))
  (dolist (object (list (list :unowned) (make-array '(2 2) :initial-element 0)))
    (handler-case (progn (with-output-to-string (s) (write-pool-graph s (list object)))
                         (error "Unexpected object admission"))
      (unsupported-wasm32-code (c)
        (push (string-downcase (symbol-name (unsupported-operation c))) refusals))))
  (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "refusals.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for reason in (nreverse refusals) for i from 0 do
      (unless (zerop i) (write-char #\, s)) (format s "~s" reason))
    (write-char #\] s)))
(let ((probe (compile-primitive-module "(lambda (p) (%header-word p))" "header_probe" '(:node) :u32)))
 (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "header_probe.wat") :direction :output :if-exists :error)
  (write-string (getf probe :wat) s)))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
