(in-package "WASM32-COMPILER")
(defvar *pool-symbol-owners* nil)
(defun write-pool-graph (stream roots)
  (let ((seen (make-hash-table :test #'eq)) (objects (make-array 0 :adjustable t :fill-pointer 0)))
    (labels ((value (x)
               (cond ((null x) (write-string "{\"kind\":\"singleton\",\"value\":\"nil\"}" stream))
                     ((eq x t) (write-string "{\"kind\":\"singleton\",\"value\":\"t\"}" stream))
                     ((and (integerp x) (<= -536870912 x 536870911)) (format stream "{\"kind\":\"integer\",\"value\":~s}" (format nil "~d" x)))
                     ((characterp x) (format stream "{\"kind\":\"character\",\"value\":~d}" (char-code x)))
                     ((symbolp x) (let ((owner (cdr (assoc x *pool-symbol-owners* :test #'eq))))
                       (unless owner (refuse :pool-symbol-owner))
                       (format stream "{\"symbol\":~s}" owner)))
                     (t (multiple-value-bind (index found) (gethash x seen)
                          (unless found
                            (when (>= (length objects) 65536) (refuse :pool-object-budget))
                            (setq index (vector-push-extend x objects)) (setf (gethash x seen) index))
                          (format stream "{\"ref\":\"o~d\"}" index)))))
             (float-bits (x)
               (if (typep x 'single-float)
                 (string-downcase (format nil "~8,'0x" (logand #xffffffff (ccl::single-float-bits x))))
                 (multiple-value-bind (hi lo) (ccl::double-float-bits x)
                   (string-downcase (format nil "~8,'0x~8,'0x" (logand #xffffffff hi) (logand #xffffffff lo))))))
             (array-values (x writer)
               (write-char #\[ stream)
               (dotimes (i (length x)) (unless (zerop i) (write-char #\, stream)) (funcall writer (aref x i)))
               (write-char #\] stream))
             (node (x)
               (cond ((consp x) (write-string "{\"kind\":\"cons\",\"car\":" stream) (value (car x))
                                (write-string ",\"cdr\":" stream) (value (cdr x)) (write-char #\} stream))
                     ((integerp x) (format stream "{\"kind\":\"integer\",\"value\":~s}" (format nil "~d" x)))
                     ((floatp x) (format stream "{\"kind\":~s,\"value\":~s}" (if (typep x 'single-float) "single-float" "double-float") (float-bits x)))
                     ((typep x 'simple-string) (write-string "{\"kind\":\"string\",\"value\":" stream)
                        (array-values x (lambda (c) (princ (char-code c) stream))) (write-char #\} stream))
                     ((typep x 'simple-vector) (write-string "{\"kind\":\"general-vector\",\"elements\":" stream)
                        (array-values x #'value) (write-char #\} stream))
                     ((and (typep x 'simple-array) (= (array-rank x) 1))
                      (let* ((type (array-element-type x))
                             (kind (cdr (assoc type '((bit . "bit") ((unsigned-byte 8) . "u8") ((signed-byte 8) . "s8")
                               ((unsigned-byte 16) . "u16") ((signed-byte 16) . "s16") ((unsigned-byte 32) . "u32")
                               ((signed-byte 32) . "s32") (fixnum . "fixnum") (single-float . "single-float")
                               (double-float . "double-float") ((complex single-float) . "complex-single-float")
                               ((complex double-float) . "complex-double-float")) :test #'equal))))
                        (unless kind (refuse :pool-array-type))
                        (format stream "{\"kind\":\"vector\",\"type\":~s,\"elements\":" kind)
                        (array-values x (lambda (v)
                          (cond ((eq type 'bit) (princ v stream))
                                ((integerp v) (format stream "~s" (format nil "~d" v)))
                                ((floatp v) (format stream "~s" (float-bits v)))
                                ((complexp v) (format stream "[~s,~s]" (float-bits (realpart v)) (float-bits (imagpart v)))))))
                        (write-char #\} stream)))
                     (t (refuse :pool-object-type)))))
      (write-string "{\"version\":1,\"roots\":" stream)
      (array-values (coerce roots 'vector) #'value)
      (write-string ",\"objects\":[" stream)
      (loop for i from 0 while (< i (length objects)) do
        (unless (zerop i) (write-char #\, stream))
        (format stream "{\"id\":\"o~d\",\"value\":" i) (node (aref objects i)) (write-char #\} stream))
      (write-string "]}" stream))))
