/*
 * WASM subprims stand-ins (C)
 *
 * These are placeholders so the JS host can install a complete subprims table.
 * Real implementations can later override table entries with handwritten WASM.
 *
 * NOTE: Some subprims are implemented in the kernel or smoke tests and
 * are intentionally omitted here to avoid duplicate symbols.
 */

#ifdef WASM32
#include "lisp.h"
#include "lisp-exceptions.h"
#include "wasm-subprims-map.h"

#define DECL_SUBPRIM(name) \
  __attribute__((used, visibility("default"), export_name(#name))) void name(void)
#define SUBPRIM_STUB(name) \
  DECL_SUBPRIM(name) { Bug(NULL, "WASM subprim not implemented: %s", #name); }

SUBPRIM_STUB(_SPfix_nfn_entrypoint)
SUBPRIM_STUB(_SPbuiltin_plus)
SUBPRIM_STUB(_SPbuiltin_minus)
SUBPRIM_STUB(_SPbuiltin_times)
SUBPRIM_STUB(_SPbuiltin_div)
SUBPRIM_STUB(_SPbuiltin_eq)
SUBPRIM_STUB(_SPbuiltin_ne)
SUBPRIM_STUB(_SPbuiltin_gt)
SUBPRIM_STUB(_SPbuiltin_ge)
SUBPRIM_STUB(_SPbuiltin_lt)
SUBPRIM_STUB(_SPbuiltin_le)
SUBPRIM_STUB(_SPbuiltin_eql)
SUBPRIM_STUB(_SPbuiltin_length)
SUBPRIM_STUB(_SPbuiltin_seqtype)
SUBPRIM_STUB(_SPbuiltin_assq)
SUBPRIM_STUB(_SPbuiltin_memq)
SUBPRIM_STUB(_SPbuiltin_logbitp)
SUBPRIM_STUB(_SPbuiltin_logior)
SUBPRIM_STUB(_SPbuiltin_logand)
SUBPRIM_STUB(_SPbuiltin_ash)
SUBPRIM_STUB(_SPbuiltin_negate)
SUBPRIM_STUB(_SPbuiltin_logxor)
SUBPRIM_STUB(_SPbuiltin_aref1)
SUBPRIM_STUB(_SPbuiltin_aset1)
SUBPRIM_STUB(_SPfuncall)
SUBPRIM_STUB(_SPmkcatch1v)
SUBPRIM_STUB(_SPmkcatchmv)
SUBPRIM_STUB(_SPmkunwind)
SUBPRIM_STUB(_SPbind)
SUBPRIM_STUB(_SPconslist)
SUBPRIM_STUB(_SPconslist_star)
/* _SPmakes32 provided elsewhere */
SUBPRIM_STUB(_SPmakeu32)
/* _SPfix_overflow provided elsewhere */
SUBPRIM_STUB(_SPmakeu64)
SUBPRIM_STUB(_SPmakes64)
SUBPRIM_STUB(_SPmvpass)
SUBPRIM_STUB(_SPvalues)
SUBPRIM_STUB(_SPnvalret)
SUBPRIM_STUB(_SPthrow)
SUBPRIM_STUB(_SPnthrowvalues)
SUBPRIM_STUB(_SPnthrow1value)
SUBPRIM_STUB(_SPbind_self)
SUBPRIM_STUB(_SPbind_nil)
SUBPRIM_STUB(_SPbind_self_boundp_check)
SUBPRIM_STUB(_SPrplaca)
SUBPRIM_STUB(_SPrplacd)
SUBPRIM_STUB(_SPgvset)
SUBPRIM_STUB(_SPset_hash_key)
SUBPRIM_STUB(_SPstore_node_conditional)
SUBPRIM_STUB(_SPset_hash_key_conditional)
SUBPRIM_STUB(_SPstkconslist)
SUBPRIM_STUB(_SPstkconslist_star)
SUBPRIM_STUB(_SPmkstackv)
SUBPRIM_STUB(_SPsetqsym)
SUBPRIM_STUB(_SPprogvsave)
SUBPRIM_STUB(_SPstack_misc_alloc)
SUBPRIM_STUB(_SPgvector)
SUBPRIM_STUB(_SPfitvals)
SUBPRIM_STUB(_SPnthvalue)
SUBPRIM_STUB(_SPdefault_optional_args)
SUBPRIM_STUB(_SPopt_supplied_p)
SUBPRIM_STUB(_SPheap_rest_arg)
SUBPRIM_STUB(_SPreq_heap_rest_arg)
SUBPRIM_STUB(_SPheap_cons_rest_arg)
SUBPRIM_STUB(_SPcheck_fpu_exception)
SUBPRIM_STUB(_SPdiscard_stack_object)
SUBPRIM_STUB(_SPksignalerr)
SUBPRIM_STUB(_SPstack_rest_arg)
SUBPRIM_STUB(_SPreq_stack_rest_arg)
SUBPRIM_STUB(_SPstack_cons_rest_arg)
SUBPRIM_STUB(_SPcall_closure)
SUBPRIM_STUB(_SPspreadargz)
SUBPRIM_STUB(_SPtfuncallgen)
SUBPRIM_STUB(_SPtfuncallslide)
SUBPRIM_STUB(_SPjmpsym)
SUBPRIM_STUB(_SPtcallsymgen)
SUBPRIM_STUB(_SPtcallsymslide)
SUBPRIM_STUB(_SPtcallnfngen)
SUBPRIM_STUB(_SPtcallnfnslide)
SUBPRIM_STUB(_SPmisc_ref)
SUBPRIM_STUB(_SPsubtag_misc_ref)
SUBPRIM_STUB(_SPmakestackblock)
SUBPRIM_STUB(_SPmakestackblock0)
SUBPRIM_STUB(_SPmakestacklist)
SUBPRIM_STUB(_SPstkgvector)
SUBPRIM_STUB(_SPmisc_alloc)
SUBPRIM_STUB(_SPatomic_incf_node)
/* _SPunused1 provided elsewhere */
/* _SPunused2 provided elsewhere */
SUBPRIM_STUB(_SPrecover_values)
SUBPRIM_STUB(_SPinteger_sign)
SUBPRIM_STUB(_SPsubtag_misc_set)
SUBPRIM_STUB(_SPmisc_set)
SUBPRIM_STUB(_SPspread_lexprz)
SUBPRIM_STUB(_SPreset)
SUBPRIM_STUB(_SPmvslide)
SUBPRIM_STUB(_SPsave_values)
SUBPRIM_STUB(_SPadd_values)
SUBPRIM_STUB(_SPmisc_alloc_init)
SUBPRIM_STUB(_SPstack_misc_alloc_init)
SUBPRIM_STUB(_SPpopj)
SUBPRIM_STUB(_SPudiv64by32)
SUBPRIM_STUB(_SPgetu64)
SUBPRIM_STUB(_SPgets64)
SUBPRIM_STUB(_SPspecref)
SUBPRIM_STUB(_SPspecrefcheck)
SUBPRIM_STUB(_SPspecset)
SUBPRIM_STUB(_SPgets32)
SUBPRIM_STUB(_SPgetu32)
SUBPRIM_STUB(_SPmvpasssym)
SUBPRIM_STUB(_SPunbind)
SUBPRIM_STUB(_SPunbind_n)
SUBPRIM_STUB(_SPunbind_to)
SUBPRIM_STUB(_SPprogvrestore)
SUBPRIM_STUB(_SPbind_interrupt_level_0)
SUBPRIM_STUB(_SPbind_interrupt_level_m1)
SUBPRIM_STUB(_SPbind_interrupt_level)
SUBPRIM_STUB(_SPunbind_interrupt_level)
SUBPRIM_STUB(_SParef2)
SUBPRIM_STUB(_SParef3)
SUBPRIM_STUB(_SPaset2)
SUBPRIM_STUB(_SPaset3)
SUBPRIM_STUB(_SPkeyword_bind)
SUBPRIM_STUB(_SPudiv32)
SUBPRIM_STUB(_SPsdiv32)
SUBPRIM_STUB(_SPeabi_ff_call_simple)
SUBPRIM_STUB(_SPdebind)
SUBPRIM_STUB(_SPeabi_callback)
SUBPRIM_STUB(_SPeabi_ff_callhf)
SUBPRIM_STUB(_SPwasm_macro_apply_stub)
SUBPRIM_STUB(_SPwasm_udf_stub)

#undef SUBPRIM_STUB
#undef DECL_SUBPRIM

#endif
