;;; Appended to the API witness. Native weak keys model anchor reachability;
;;; the target uses the product owner queue and the fixture's real destructor.
(in-package "CCL")
#-wasm32-target
(progn
  (defvar *ff-native-request* (symbol-function '%wasm-host-process-request))
  (defvar *ff-native-watches* nil)
  (defun ff-native-request (selector operation payload)
    (case operation
      (8 (let* ((handle (svref payload 0)) (anchor (svref payload 1))
                (table (make-hash-table :test 'eq :weak :key)))
           (if (or (not (consp anchor)) (assoc handle *ff-native-watches*)) -1
             (progn (setf (gethash anchor table) t)
                    (push (cons handle table) *ff-native-watches*) 0))))
      (9 (let ((count 0))
           (dolist (watch (reverse *ff-native-watches*))
             (let* ((buffer (gethash (car watch) *fa-tokens*))
                    (lib (svref buffer 1)))
               (when (and (zerop (hash-table-count (cdr watch)))
                          (svref buffer 3) (svref lib 1))
                 (let ((status (funcall *ff-native-request* 15 4 (car watch))))
                   (when (minusp status) (return-from ff-native-request status))
                   (incf count)))))
           count))
      (t (funcall *ff-native-request* selector operation payload))))
  (setf (symbol-function '%wasm-host-process-request) #'ff-native-request))

(defvar *ff-anchor* nil)
(defun ff-row (name value) (format t "FF-ROW ~A ~S~%" name value))
(defun ff-prepare (library retain)
  (let* ((handle (allocate-wasm-buffer library 8)) (anchor (cons 41 43)))
    (finalize-wasm-buffer handle anchor)
    (when retain (setq *ff-anchor* anchor))
    handle))
(defun ff-collect (library)
  #-wasm32-target (gc)
  (wasm-call library "echo" 0 0 0.0f0 0.0d0)
  nil)
(defun ff-releases (library) (wasm-call library "releases"))

(let* ((library (open-wasm-library "example"))
       (before (ff-releases library))
       (handle (ff-prepare library t)))
  (ff-collect library)
  (ff-row 'held (list (drain-wasm-finalizers) (car *ff-anchor*) (cdr *ff-anchor*)
                     (- (ff-releases library) before)))
  (ff-collect library)
  (ff-row 'moved-twice (list (drain-wasm-finalizers) (car *ff-anchor*)))
  (setq *ff-anchor* nil)
  (ff-collect library)
  (ff-row 'queued (- (ff-releases library) before))
  (ff-row 'released (list (drain-wasm-finalizers) (- (ff-releases library) before)
                         (release-wasm-buffer handle) (drain-wasm-finalizers))))
(let* ((library (open-wasm-library "example")) (before (ff-releases library))
       (handle (ff-prepare library t)))
  (release-wasm-buffer handle)
  (setq *ff-anchor* nil)
  (ff-collect library)
  (ff-row 'explicit-first (list (drain-wasm-finalizers) (- (ff-releases library) before))))
(let* ((library (open-wasm-library "example")) (before (ff-releases library))
       (handle (ff-prepare library nil)))
  (ff-collect library)
  (release-wasm-buffer handle)
  (ff-row 'explicit-queued (list (drain-wasm-finalizers) (- (ff-releases library) before))))
(let* ((library (open-wasm-library "example")) (handle (ff-prepare library t)))
  (ff-row 'duplicate (handler-case (finalize-wasm-buffer handle (cons 1 2))
                       (error () :caught)))
  (release-wasm-buffer handle)
  (setq *ff-anchor* nil)
  (ff-collect library))
(let* ((library (open-wasm-library "example")) (handle (allocate-wasm-buffer library 8)))
  (ff-row 'bad-anchor (handler-case (finalize-wasm-buffer handle nil) (error () :caught)))
  (release-wasm-buffer handle))
;; The API witness already retired its other names. Use two fresh declarations.
(let* ((library (open-wasm-library "final-close")) (handle (ff-prepare library nil)))
  (ff-collect library)
  (close-wasm-library library)
  (ff-row 'closed (list (drain-wasm-finalizers) (release-wasm-buffer handle))))
(let* ((library (open-wasm-library "final-trap"))
       (first (ff-prepare library nil)) (second (ff-prepare library nil)))
  (ff-collect library)
  (wasm-call library "mode" 1)
  (ff-row 'destructor-trap
          (list (handler-case (drain-wasm-finalizers)
                  (error (condition) (second (simple-condition-format-arguments condition))))
                (release-wasm-buffer first) (release-wasm-buffer second)
                (drain-wasm-finalizers))))
(format t "FF-PASS~%")
