# Each mutant must fail its named semantic case, not only a refusal message.
MUTANTS = [
 ('foreign-service.mjs','fixnum','word%4===0,\'FIXNUM\'','true,\'FIXNUM\'','service-fixnum-size'),
 ('foreign-service.mjs','object-tag','(h&255)===tag&&','','service-object-tag'),
 ('foreign-service.mjs','object-body-span','p+4+n*(tag===199?1:4)<=memory.buffer.byteLength','true','service-body-span'),
 ('foreign-service.mjs','token-kind',"value?.kind===kind",'value','service-buffer-as-library'),
 ('foreign-service.mjs','open-capacity','capacity();const library=libraries.open(name)','const library=libraries.open(name)','service-open-capacity'),
 ('foreign-service.mjs','float32-header',"type==='f32'?271:791", "type==='f32'?527:791",'service-scalars-moving-0'),
 ('foreign-service.mjs','float64-header',"type==='f32'?271:791", "type==='f32'?271:535",'service-scalars-moving-0'),
 ('collector-owner.mjs','weak-update',"row.word=word;",';','finalizer-moving-0'),
 ('collector-owner.mjs','weak-enqueue',"this.#finalizerQueue.add(row);",';','finalizer-moving-0'),
 ('collector-owner.mjs','weak-remove',"if(word===0){row.state='queued';this.#finalizers.delete(row);", "if(word===0){row.state='queued';",'finalizer-moving-0'),
 ('collector-owner.mjs','cancel-watching','this.#finalizers.delete(row);this.#finalizerQueue.delete(row);','this.#finalizerQueue.delete(row);','finalizer-cancel'),
 ('collector-owner.mjs','cancel-queued','this.#finalizers.delete(row);this.#finalizerQueue.delete(row);','this.#finalizers.delete(row);','finalizer-explicit-true'),
 ('collector-owner.mjs','cancel-collecting',"need(!this.#busy,'finalizer collecting');",';','finalizer-cancel-collecting'),
 ('collector-owner.mjs','cancel-once',"row.state==='done'||row.state==='cancelled'", "row.state==='done'",'finalizer-cancel'),
 ('collector-owner.mjs','drain-foreign',"need(!this.#foreign&&!this.#boundary&&!this.#busy&&!this.#drainingFinalizers", "need(!this.#boundary&&!this.#busy&&!this.#drainingFinalizers",'finalizer-drain-foreign'),
 ('collector-owner.mjs','drain-boundary',"need(!this.#foreign&&!this.#boundary&&!this.#busy&&!this.#drainingFinalizers", "need(!this.#foreign&&!this.#busy&&!this.#drainingFinalizers",'finalizer-drain-safepoint'),
 ('collector-owner.mjs','drain-reentry','&&!this.#drainingFinalizers','', 'finalizer-reentry'),
 ('collector-owner.mjs','drain-state',"Atomics.load(new Int32Array(this.#memory.buffer),(this.tcr+32)/4)===2,'finalizer thread'", "true,'finalizer thread'",'finalizer-drain-state'),
 ('collector-owner.mjs','one-batch','for(const row of [...this.#finalizerQueue])','for(const row of this.#finalizerQueue)','finalizer-batch'),
 ('collector-owner.mjs','dequeue',"if(!this.#finalizerQueue.delete(row))continue;",';','finalizer-failure-no-retry'),
 ('collector-owner.mjs','finalizer-action',"typeof action==='function','finalizer action'", "true,'finalizer action'",'finalizer-refuse-action'),
 ('collector-owner.mjs','finalizer-object-identity','&&this.validObject(word)','', 'finalizer-object-interior'),
 ('collector-owner.mjs','finalizer-heap-start','word-tag>=active.start','true','finalizer-object-truth'),
 ('collector-owner.mjs','finalizer-lowtag','(tag===1||tag===6)','true','finalizer-object-fixnum'),
 ('collector-owner.mjs','finalizer-async',"!(value&&typeof value.then==='function'),'finalizer synchronous'", "true,'finalizer synchronous'",'finalizer-async'),
 ('foreign-module.mjs','release-cancels','h.active=false;live.delete(h);h.finalizer?.cancel();','h.active=false;live.delete(h);','finalizer-explicit-true'),
 ('foreign-module.mjs','retire-cancels','h.active=false;h.finalizer?.cancel();','h.active=false;','finalizer-close-true'),
 ('foreign-module.mjs','finalizer-once',"need(!h.finalizer,'FINALIZER_ONCE');",';','finalizer-once'),
 ('foreign-service.mjs','drain-payload',"need(payload()===NIL,'PAYLOAD');",';','finalizer-drain-payload'),
 ('collector.c','weak-query-error','if(s->error||(tag!=1&&tag!=6)||!inside(base,s->from,s->used))','if((tag!=1&&tag!=6)||!inside(base,s->from,s->used))','finalizer-forward-query'),
 ('collector.c','weak-query-tag','index==0xffffffffu||(tag==1)!=(objects(s)[index].scan==0xffffffffu))return 0xffffffffu;', 'index==0xffffffffu)return 0xffffffffu;', 'finalizer-forward-query'),
 ('collector.c','weak-retains-dead','return objects(s)[index].moved?objects(s)[index].moved+tag:0;', 'return forward(s,value);','finalizer-moving-0'),
 ('collector.c','weak-drops-live','return objects(s)[index].moved?objects(s)[index].moved+tag:0;', 'return 0;','finalizer-moving-0'),
 ('collector.c','weak-tag','objects(s)[index].moved+tag:0;', 'objects(s)[index].moved+6:0;','finalizer-cons'),
]
