(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (native nil)
       (cases (with-open-file (s (merge-pathnames "runtime.lisp" *load-pathname*)) (second (read s)))))
  (dolist (row cases)
    (let* ((name (first row)) (form (second row))
           (result (compile-float-call-form form name (append (mapcar #'first cases) '("gd_condition" "gd_condition_gf" "gd_condition_args")) (if (search "__unchecked" name) 0 1)))
           (fn (compile nil form))
           (specimen fn)
           (args (multiple-value-list (ccl::function-args (ccl::closure-function specimen))))
           (keys (ccl::lfun-keyvect (ccl::closure-function specimen))))
      (push (vector name (coerce (subseq args 0 5) 'vector) (copy-seq (or keys #()))) native)
      (dolist (m (cons result (getf result :children)))
        (push m modules)
        (loop for key across (aref (aref (getf m :pool) 0) 6) do
          (pushnew (cons key (concatenate 'string (package-name (symbol-package key)) "::" (symbol-name key))) *pool-symbol-owners* :key #'car :test #'eq))
        (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
  (setq modules (nreverse modules) native (nreverse native))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"top\":~a,\"captures\":~d}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false") (getf m :captures)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (with-open-file (s (concatenate 'string out "native-metadata.json") :direction :output :if-exists :error) (write-pool-graph s native)))
(defun fp-printed (x)
 (cond ((null x) "NIL") ((eq x t) "T") ((integerp x) (format nil "~d" x))
 ((consp x) (concatenate 'string "cons:" (fp-printed (car x))))
 ((typep x 'single-float) (let ((b (logand #xffffffff (ccl::single-float-bits x)))) (if (and (= (ldb (byte 8 23) b) 255) (not (zerop (ldb (byte 23 0) b)))) "nan" (string-downcase (format nil "f32:~8,'0x" b)))))
 ((typep x 'double-float) (multiple-value-bind (hi lo) (ccl::double-float-bits x) (let ((b (logior (ash (logand #xffffffff hi) 32) (logand #xffffffff lo)))) (if (and (= (ldb (byte 11 52) b) 2047) (not (zerop (ldb (byte 52 0) b)))) "nan" (string-downcase (format nil "f64:~16,'0x" b))))))
 (t (error "Unexpected native value ~s" x))))
(defun fp-mode (mask)
 (ccl:set-fpu-mode :rounding-mode :nearest :invalid (logbitp 0 mask) :division-by-zero (logbitp 1 mask) :overflow (logbitp 2 mask) :underflow (logbitp 3 mask) :inexact (logbitp 4 mask)))
(fp-mode 0)
(let* ((rows (with-open-file (s (merge-pathnames "runtime.lisp" *load-pathname*)) (second (read s))))
       (functions (mapcar (lambda (r) (cons (first r) (compile nil (if (string= (first r) "h_collect")
         `(lambda (a b) (flet ((/ (a b) (if (zerop b) (error (make-condition 'division-by-zero :operation '/ :operands (list a b))) (cl:/ a b)))) ,@(cddr (second r))))
         (second r))))) rows))
       (cases (with-open-file (s (merge-pathnames "cases.lisp" *load-pathname*)) (read s))))
 (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-results.txt") :direction :output :if-exists :error)
  (with-open-file (a (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-args.txt") :direction :output :if-exists :error)
   (dolist (c cases)
    (fp-mode 0)
    (let ((args (mapcar #'eval (second c))) (values nil))
     (format a "~{~a~^,~}~%" (mapcar #'fp-printed args))
     (unwind-protect
      (progn (fp-mode (third c)) (setq values (multiple-value-list (apply (cdr (assoc (first c) functions :test #'equal)) args))))
      (fp-mode 0))
     (format s "~{~a~^,~}~%" (mapcar #'fp-printed values)))))))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "source-refusals.txt") :direction :output :if-exists :error)
 (dolist (form '((lambda (x) (float x)) (lambda (x y) (float x y)) (lambda (x) (+ x)) (lambda (x) (/ x 1 2))))
  (let ((failed nil)) (handler-case (compile-float-call-form form "refused" nil) (error (e) (setq failed t) (format s "~a~%" e))) (unless failed (error "Float source escaped ~s" form))))
 (dolist (form '((lambda (x) (float x 1.0s0)) (lambda (x y) (/ x y)) (lambda () (quote floating-point-overflow))))
  (let ((failed nil)) (handler-case (compile-call-form form "default-refused" nil) (error (e) (setq failed t) (format s "~a~%" e))) (unless failed (error "Float default admission escaped ~s" form)))))
(load (merge-pathnames "class-shapes.lisp" *load-pathname*))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
