(in-package :ccl)
;; One snapshot across all heap areas. No name-based filtering and no forced GC.
;; Keep discovered objects alive before resolving their owning reference paths.
(setf (get 'heap-census :snapshot)
 (without-gcing
  (let ((tables nil) (populations nil))
   (%map-areas (lambda (o)
     (cond ((and (hash-table-p o) (hash-table-weak-p o)) (push o tables))
           ((typep o 'population) (push o populations)))))
   (list (mapcar (lambda (tab) (list tab (hash-table-count tab))) tables)
         (mapcar (lambda (pop) (list pop (population.type pop) (length (population-contents pop))
                   (if (logbitp $population_termination-bit (population.type pop)) (length (population.termination-list pop)) 0))) populations)))))
;; Resolve paths after capture. Compiling this larger reporting form can itself
;; allocate a temporary lock; it must not change the captured membership counts.
(without-gcing
 (let ((tables (mapcar #'car (first (get 'heap-census :snapshot))))
       (populations (mapcar #'car (second (get 'heap-census :snapshot)))))
  (flet ((global (name) (and (boundp name) (symbol-value name)))
         (capture (fn var)
           (let ((row (assoc var (closure-closed-over-values (fdefinition fn)))))
             (assert row) (second row))))
   (let ((owners
          (list
           (list "level-0/l0-def.lisp:38" "CCL::*LFUN-NAMES*" (global '*lfun-names*))
           (list "level-0/l0-symbol.lisp:237" "BINDING-INDEX-SYMBOL/capture/BINDING-INDEX-REVERSE-MAP" (capture 'binding-index-symbol 'binding-index-reverse-map))
           (list "level-0/l0-misc.lisp:500" "CCL::%DOCUMENTATION" (global '%documentation))
           (list "level-1/l1-aprims.lisp:262" "CCL::%SETF-FUNCTION-NAMES%" (global '%setf-function-names%))
           (list "level-1/l1-aprims.lisp:263" "CCL::%SETF-FUNCTION-NAME-INVERSES%" (global '%setf-function-name-inverses%))
           (list "level-1/l1-utils.lisp:689" "CCL::%LAMBDA-LISTS%" (global '%lambda-lists%))
           (list "level-1/l1-clos-boot.lisp:246" "ENSURE-SLOT-ID/capture/SLOT-ID-HASH" (capture 'ensure-slot-id 'slot-id-hash))
           (list "level-1/l1-clos-boot.lisp:832" "CCL::%DEFGENERIC-METHODS%" (global '%defgeneric-methods%))
           (list "level-1/l1-clos-boot.lisp:930" "CCL::*EQL-METHODS-HASHES*/CDR" (cdr *eql-methods-hashes*))
           (list "level-1/l1-clos.lisp:296" "CCL::*OPTIMIZED-DEPENDENTS*" (global '*optimized-dependents*))
           (list "level-1/l1-dcode.lisp:731" "INTERN-EQL-SPECIALIZER/capture/EQL-SPECIALIZERS-HASH" (capture 'intern-eql-specializer 'eql-specializers-hash))
           (list "level-1/l1-dcode.lisp:739" "CCL::*NO-APPLICABLE-METHOD-HASH*" (global '*no-applicable-method-hash*))
           (list "level-1/l1-dcode.lisp:919" "CCL::*COMBINED-METHODS*" (global '*combined-methods*))
           (list "level-1/l1-dcode.lisp:1092" "CCL::*EFFECTIVE-METHOD-GFS*" (global '*effective-method-gfs*))
           (list "level-1/l1-symhash.lisp:893" "CCL::*PACKAGE-LOCAL-NICKNAMES*" (global '*package-local-nicknames*))
           (list "level-1/l1-symhash.lisp:894" "CCL::*PACKAGE-LOCALLY-NICKNAMED-BY*" (global '*package-locally-nicknamed-by*))
           (list "lib/foreign-types.lisp:80" "CCL::*HOST-FTD*/FTD-ORDINAL-TYPES" (ftd-ordinal-types *host-ftd*))
           (list "lib/foreign-types.lisp:80" "CCL::*TARGET-FTD*/FTD-ORDINAL-TYPES" (ftd-ordinal-types *target-ftd*))
           (list "lib/describe.lisp:216" "INSPECTOR::*BOGUS-OBJECT-HASH*" (global 'inspector::*bogus-object-hash*))
           (list "lib/encapsulate.lisp:52" "CCL::*ENCAPSULATION-TABLE*" (global '*encapsulation-table*))
           (list "lib/edit-callers.lisp:108" "CCL::*FUNCTION-PARENT-TABLE*" (global '*function-parent-table*))
           (list "lib/ppc-backtrace.lisp:669" "CCL::*BRANCH-TREE-HASH*" (global '*branch-tree-hash*)))))
    (format t "TOTAL|~d|~d|~d|~d~%" (length tables) (reduce #'+ (first (get 'heap-census :snapshot)) :key #'second :initial-value 0)
            (length populations) (reduce #'+ (second (get 'heap-census :snapshot)) :key #'third :initial-value 0))
    (loop for tab in tables for id from 0 do
     (format t "TABLE|~d|~a|~a|~d~%" id (hash-table-test tab) (hash-table-weak-p tab) (second (assoc tab (first (get 'heap-census :snapshot)))))
     (let ((matches (remove-if-not (lambda (r) (eq (third r) tab)) owners)))
      (assert matches)
      (dolist (r matches) (format t "TABLE-OWNER|~d|~a|~a~%" id (first r) (second r)))))
    (dolist (r owners)
     (when (hash-table-p (third r)) (assert (member (third r) tables :test #'eq)))
     (unless (hash-table-p (third r)) (format t "NO-TABLE|~a|~a~%" (first r) (second r))))
    ;; Reverse join: the declared owner paths must also be present in the walk.
    (dolist (name '(%system-locks% *lisp-thread-population* %all-gfs% *termination-population*))
     (assert (member (global name) populations :test #'eq)))
    (maphash (lambda (name mci) (declare (ignore name))
               (dolist (i '(2 3)) (assert (member (svref mci i) populations :test #'eq))))
             *method-combination-info*)
    (loop for pop in populations for id from 0 do
     (let ((snapshot (assoc pop (second (get 'heap-census :snapshot)))))
      (format t "POP|~d|~d|~d|~d~%" id (second snapshot) (third snapshot) (fourth snapshot)))
     (let ((found nil))
      (dolist (r (list (list '%system-locks% "level-0/nfasload.lisp:1212")
                      (list '*lisp-thread-population* "level-1/l1-lisp-threads.lisp:240")
                      (list '%all-gfs% "level-1/l1-dcode.lisp:392")
                      (list '*termination-population* "level-1/l1-lisp-threads.lisp:1035")))
       (when (eq (global (first r)) pop)
        (setf found t) (format t "POP-OWNER|~d|~a|CCL::~a~%" id (second r) (first r))))
      (maphash (lambda (name mci)
        (dolist (index '(2 3))
         (when (eq (svref mci index) pop)
          (setf found t)
          (format t "POP-OWNER|~d|library/lispequ.lisp:1166|CCL::*METHOD-COMBINATION-INFO*/~a/~d~%" id name index))))
       *method-combination-info*)
      (assert found)))))))
(quit)
