(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(load (merge-pathnames "extra.lisp" *load-pathname*))
(load (merge-pathnames "cases.lisp" *load-pathname*))

(defun core-json-value (x s)
  (when (and (ccl::istructp x) (not (gethash x *witness-nodes*)))
    (setf (gethash x *witness-nodes*)
          (cons 'istruct (cons (cons (ccl::istruct-type-name x) nil)
                              (loop for i from 1 below (ccl::uvsize x) collect (ccl::%svref x i))))))
  (cond ((gethash x *witness-raw*)
         (let ((raw (gethash x *witness-raw*)))
           (format s "{\"raw\":{\"tag\":~d,\"words\":[" (car raw))
           (loop for word in (cdr raw) for i from 0 do
             (unless (zerop i) (write-char #\, s)) (princ word s))
           (write-string "]}}" s)))
        ((gethash x *witness-nodes*)
         (let* ((description (gethash x *witness-nodes*))
                (kind (car description))
                (fields (loop for original in (cdr description) for i from 0
                              collect (cond ((and (member kind '(istruct struct)) (zerop i)) original)
                                            ((and (eq kind 'lock) (zerop i)) original)
                                            ((and (eq kind 'vectorh) (= i 4))
                                             (dpb wasm32::subtag-simple-vector (byte 8 8) (ccl::%svref x i)))
                                            (t (ccl::%svref x i)))))
                (tag (symbol-value (intern (concatenate 'string "SUBTAG-" (symbol-name kind)) "WASM32"))))
           (format s "{\"node\":{\"tag\":~d,\"fields\":[" tag)
           (loop for field in fields for i from 0 do
             (unless (zerop i) (write-char #\, s)) (core-json-value field s))
           (write-string "]}}" s)))
        ((null x) (write-string "null" s))
        ((eq x t) (write-string "true" s))
        ((and (integerp x) (<= (- (ash 1 29)) x (1- (ash 1 29)))) (princ x s))
        ((integerp x) (format s "{\"integer\":\"~d\"}" x))
        ((typep x 'single-float)
         (format s "{\"single\":~d}" (logand #xffffffff (ccl::single-float-bits x))))
        ((typep x 'double-float)
         (multiple-value-bind (hi lo) (ccl::double-float-bits x)
           (format s "{\"double\":[~d,~d]}" (logand #xffffffff hi) (logand #xffffffff lo))))
        ((functionp x) (format s "{\"function\":~s}" (frontend-owner (ccl::function-name x))))
        ((characterp x) (format s "{\"character\":~d}" (char-code x)))
        ((stringp x) (write-string "{\"string\":" s) (frontend-json-string x s) (write-char #\} s))
        ((gethash x *witness-symbols*)
         (format s "{\"symbol\":~s,\"flags\":~d}" (frontend-owner x) (ccl::%symbol-bits x)))
        ((symbolp x) (format s "{\"symbol\":~s}" (frontend-owner x)))
        ((consp x) (write-char #\[ s) (core-json-value (car x) s) (write-char #\, s)
         (core-json-value (cdr x) s) (write-char #\] s))
        ((ccl::ratiop x) (write-string "{\"ratio\":[" s) (core-json-value (numerator x) s)
         (write-char #\, s) (core-json-value (denominator x) s) (write-string "]}" s))
        ((complexp x) (write-string "{\"complex\":[" s) (core-json-value (realpart x) s)
         (write-char #\, s) (core-json-value (imagpart x) s) (write-string "]}" s))
        ((typep x 'bit-vector) (format s "{\"bits\":~s}" (map 'string (lambda (b) (if (zerop b) #\0 #\1)) x)))
        ((typep x '(simple-array (unsigned-byte 8) (*)))
         (write-string "{\"octets\":[" s)
         (loop for n across x for i from 0 do (unless (zerop i) (write-char #\, s)) (princ n s))
         (write-string "]}" s))
        ((simple-vector-p x)
         (write-string "{\"vector\":[" s)
         (dotimes (i (length x)) (unless (zerop i) (write-char #\, s)) (core-json-value (svref x i) s))
         (write-string "]}" s))
        (t (error "Unsupported oracle result ~s" x))))

(defun core-copy-input (input)
  (let ((seen (make-hash-table :test #'eq)))
    (labels ((copy (x)
               (or (gethash x seen)
                   (cond ((and (gethash x *witness-nodes*)
                               (not (eq (car (gethash x *witness-nodes*)) 'lock)))
                          (let* ((description (gethash x *witness-nodes*))
                                 (fields (loop for i below (length (cdr description)) collect
                                           (if (and (member (car description) '(istruct struct)) (zerop i))
                                             (ccl::%svref x i) (copy (ccl::%svref x i)))))
                                 (object (apply #'ccl::%gvector (ccl::typecode x) fields)))
                            (setf (gethash object *witness-nodes*) description)
                            object))
                         ((consp x)
                          (let ((cell (cons nil nil)))
                            (setf (gethash x seen) cell
                                  (car cell) (copy (car x)) (cdr cell) (copy (cdr x)))
                            cell))
                         ((or (stringp x) (typep x '(simple-array (unsigned-byte 8) (*)))) (copy-seq x))
                         ((simple-vector-p x)
                          (let ((v (make-array (length x))))
                            (setf (gethash x seen) v)
                            (dotimes (i (length x)) (setf (svref v i) (copy (svref x i))))
                            v))
                         (t x)))))
      (copy input))))

(defun core-native-function (name)
  (when (member name '(eql ccl::fulltag ccl::lisptag ccl::typecode ccl::assq))
    (return-from core-native-function (fdefinition name)))
  (or (gethash name *core-native-functions*)
      (let ((form (gethash name *core-native-forms*)))
        (unless form (error "No native source for ~s" name))
        (setf (gethash name *core-native-functions*)
              (ccl::compile-named-function (bootstrap-function-form form) :name name)))))

(defun core-execute-corpus (out)
  (let ((by-name (make-hash-table :test #'eq)) (duplicates nil) (closed nil) (static nil) (modules nil) (rows nil))
    (dolist (row *core-candidates*)
      (let* ((name (second (first row))) (m (second row)))
        (when (gethash name by-name) (pushnew name duplicates))
        (setf (getf m :source-name) name (gethash name by-name) m)))
    ;; The file compiler's result has the real file-local macro environment.
    (dolist (m *core-modules*)
      (when (getf m :source-name) (setf (gethash (getf m :source-name) by-name) m)))
    (setf (gethash 'eql by-name)
          (list :name "runtime_eql" :source-name 'eql :pool #() :symbols nil
                :primitive t :wat (with-open-file (s (merge-pathnames "eql-adapter.wat" *load-pathname*))
                                    (let ((text (make-string (file-length s))))
                                      (read-sequence text s) text))))
    (maphash (lambda (name m)
               (unless (member name duplicates)
                 (push name closed))) by-name)
    (loop for next = (remove-if (lambda (name)
                                 (some (lambda (callee) (not (member callee closed)))
                                       (getf (gethash name by-name) :dependencies))) closed)
          until (equal next closed) do (setq closed next))
    (setq static (remove-if (lambda (name) (getf (gethash name by-name) :dynamic-call)) closed))
    (loop for next = (remove-if (lambda (name)
                                 (some (lambda (callee) (not (member callee static)))
                                       (getf (gethash name by-name) :dependencies))) static)
          until (equal next static) do (setq static next))
    (with-open-file (s (concatenate 'string out "operator-visits.sexp") :direction :output :if-exists :error)
      (let ((*print-pretty* nil))
        (prin1 (sort (loop for name being the hash-keys of by-name using (hash-value module)
                           collect (list name (getf module :dependencies) (getf module :operators)))
                     #'string< :key (lambda (row) (format nil "~s" (first row)))) s)))
    (with-open-file (s (concatenate 'string out "operator-visits.json") :direction :output :if-exists :error)
      (write-char #\[ s)
      (loop for m in (sort (copy-list *core-modules*) #'string< :key (lambda (m) (getf m :name))) for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"module\":~s,\"source\":~s,\"operators\":[" (getf m :name) (getf m :source-file))
        (loop for (op . count) in (getf m :operators) for j from 0 do
          (unless (zerop j) (write-char #\, s))
          (format s "[~s,~d]" (symbol-name op) count))
        (write-string "]}" s))
      (write-char #\] s))
    (setq closed (sort closed #'string< :key #'symbol-name))
    (with-open-file (s (concatenate 'string out "closed.json") :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (loop for name in closed for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (multiple-value-bind (inputs covered) (core-inputs name)
          (when (and (member (getf (gethash name by-name) :source-file) '("ccl:level-0;l0-pred.lisp" "ccl:level-0;l0-utils.lisp") :test #'equal) (not covered))
            (error "Missing native input table for closed file definition ~s" name))
          (when covered
            (push (list name (gethash name by-name) inputs) rows))
          (format s "{\"package\":~s,\"name\":~s,\"inputs\":~a,\"static\":~a}" (package-name (symbol-package name))
                  (symbol-name name) (if covered "true" "false") (if (member name static) "true" "false"))))
      (write-char #\] s))
    (setq rows (nreverse rows))
    ;; Include the transitive dependencies of every executed definition.
    (let ((needed (append '(core-node-size core-access core-struct-access core-slot-access) (mapcar #'first rows))))
      (labels ((functions (x)
                 (cond ((functionp x) (pushnew (ccl::function-name x) needed))
                       ((consp x) (functions (car x)) (functions (cdr x))))))
        (dolist (row rows) (functions (third row))))
      (loop for n = (length needed) do
        (dolist (name (copy-list needed))
          (dolist (callee (getf (gethash name by-name) :dependencies)) (pushnew callee needed)))
        while (/= n (length needed)))
      (dolist (name (sort needed #'string< :key #'symbol-name))
        (let ((m (or (gethash name by-name) (error "Missing input callable ~s" name))))
          (dolist (child (cons m (getf m :children))) (push child modules)))))
    (setq modules (nreverse modules))
    (with-open-file (s (concatenate 'string out "executed-operators.json")
                       :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (loop for (name module inputs) in rows for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"cases\":~d,\"operators\":[" (symbol-name name) (length inputs))
        (loop for (op . count) in (getf module :operators) for j from 0 do
          (unless (zerop j) (write-char #\, s))
          (format s "[~s,~d]" (symbol-name op) count))
        (write-string "]}" s))
      (write-char #\] s))
    (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (loop for m in modules for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"primitive\":~a,\"symbols\":[" (getf m :name) (if (getf m :primitive) "true" "false"))
        (loop for (symbol wire) in (getf m :symbols) for j from 0 do
          (unless (zerop j) (write-char #\, s)) (format s "[~s,~s]" wire (frontend-owner symbol)))
        (write-string "],\"function\":" s)
        (if (getf m :source-name) (format s "~s" (frontend-owner (getf m :source-name))) (write-string "null" s))
        (format s "}"))
      (write-char #\] s))
    (dolist (m modules)
      (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :supersede)
        (write-string (getf m :wat) s)))
    (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :supersede)
      (let ((roots (append (mapcar (lambda (m) (getf m :pool)) modules)
                           (list ccl::%type-error-typespecs%))))
        (frontend-pool-owners roots) (write-pool-graph s roots)))
    (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (let ((n 0))
        (dolist (row rows)
          (destructuring-bind (name module inputs) row
            (dolist (input inputs)
              (let* ((args (core-copy-input input))
                     (function (core-native-function name))
                     (environment (witness-environment name))
                     (globals-after nil)
                     (values (let ((ccl::*loading-file-source-file* nil) (*print-level* 7) (*print-length* 9)
                                   (ccl::*print-string-length* 11) (ccl::*istruct-cells* nil))
                               (call-with-witness-environment environment (lambda ()
                                 (prog1 (multiple-value-list (apply function args))
                                   (setq globals-after (mapcar (lambda (x) (cons (car x) (symbol-value (car x)))) environment))))))))
                (unless (zerop n) (write-char #\, s)) (incf n)
                (format s "{\"name\":~s,\"definition\":~s,\"args\":[" (getf module :name) (symbol-name name))
                (loop for arg in input for i from 0 do (unless (zerop i) (write-char #\, s)) (core-json-value arg s))
                (write-string "],\"values\":[" s)
                (loop for value in values for i from 0 do (unless (zerop i) (write-char #\, s)) (core-json-value value s))
                (write-string "],\"after\":[" s)
                (loop for arg in args for i from 0 do (unless (zerop i) (write-char #\, s)) (core-json-value arg s))
                (write-string "],\"globals\":" s) (core-json-value environment s)
                (write-string ",\"globalsAfter\":" s) (core-json-value globals-after s)
                (write-string "}" s))))))
      (write-char #\] s))
    (with-open-file (s (concatenate 'string out "target-layout.json") :direction :output :if-exists :error)
      (let ((native (funcall (core-native-function 'core-node-size))))
        (assert (= native 8))
        (format s "{\"name\":\"core_node_size\",\"native\":[~d],\"target\":[~d]}" native wasm32::node-size)))
    (frontend-write-owners out)))
(core-execute-corpus (ccl:getenv "POOL_OUTPUT"))
