;;; Observe untouched host front-end IR for two source-rebuilt expanders.
(defpackage :ccl-lexical-callbacks (:use :cl))
(in-package :ccl-lexical-callbacks)
(defvar *records* nil)
(defparameter *probes*
  '(("literal" (lambda (xs) (mapcar (lambda (x) (+ x 1)) xs)))
    ("flet" (lambda (xs) (flet ((stepper (x) (+ x 1))) (mapcar #'stepper xs))))
    ("parameter" (lambda (callback xs) (mapcar callback xs)))
    ("assigned" (lambda (other xs) (let ((callback (lambda (x) (+ x 1))))
                                      (setq callback other) (mapcar callback xs))))
    ("captured-write" (lambda (other xs) (let ((callback (lambda (x) (+ x 1))))
      (flet ((replace-it () (setq callback other))) (replace-it) (mapcar callback xs)))))
    ("shadowed" (lambda (callback xs) (declare (ignore callback))
      (let ((callback (lambda (x) (+ x 2)))) (mapcar callback xs))))
    ("closed" (lambda (offset xs) (mapcar (lambda (x) (+ x offset)) xs)))
    ("sequential-scope" (lambda (callback xs)
      (let* ((result (mapcar callback xs)) (callback (lambda (x) (+ x 3))))
        (values result callback))))))
(defun obj (&rest fields) (apply #'ccl-source-expanders::obj fields))
(defun ident (x) (ccl-source-expanders::ident x))
(defun ir (x)
  (cond
    ((ccl::acode-p x)
     (let ((op (ccl::acode-operator-name (ccl::acode-operator x))))
       (obj "node" (ident x) "operator" (ccl-source-expanders::label op)
            "operator_id" (logand (ccl::acode-operator x) ccl::operator-id-mask)
            "operands" (if (member op '(ccl::immediate ccl::fixnum ccl::nil ccl::t))
                         (obj "literal" :true) (ir (ccl::acode-operands x))))))
    ((typep x 'ccl::var)
     (obj "variable" (ident (ccl::nx-root-var x))
          "assigned" (if (logbitp ccl::$vbitsetq (ccl::nx-var-bits (ccl::nx-root-var x))) :true :false)
          "name" (ccl-source-expanders::label (ccl::var-name (ccl::nx-root-var x)))))
    ((typep x 'ccl::afunc) (obj "function" (ident x)))
    ((consp x) (obj "cons" (list (ir (car x)) (ir (cdr x)))))
    ((null x) :null)
    ((or (integerp x) (stringp x)) x)
    ((symbolp x) (obj "symbol" (ccl-source-expanders::label x)))
    (t (obj "opaque" (ccl-source-expanders::label (type-of x))))))
(defun function-ir (afunc)
  (obj "function_id" (ident afunc) "name" (ccl-source-expanders::label (ccl::afunc-name afunc))
       "ir" (ir (ccl::afunc-acode afunc))
       "children" (mapcar #'function-ir (ccl::afunc-inner-functions afunc))))
(defun probes ()
  (ccl-census-descriptions::with-descriptions
    (lambda () (ccl-census-stub::with-target-state
      (lambda ()
        (mapcar (lambda (spec)
          (let ((afunc (ccl-census-stub::capture-lambda (second spec) 'lexical-probe)))
            (obj "name" (first spec) "form" (ccl-source-expanders::syntax (second spec))
                 "flow" (function-ir afunc) "observation" (ccl-startup-census::function-observation afunc))))
          *probes*))))))
(defun with-observer (thunk)
  (let* ((host ccl::*host-backend*)
         (old (ccl::backend-p2-compile host)) (owner ccl:*current-process*))
    (unwind-protect
      (progn
        (setf (ccl::backend-p2-compile host)
          (lambda (afunc &rest args)
            (let ((key (when (eq owner ccl:*current-process*)
                         (ccl-source-expanders::field (first ccl-census-macros::*sources*) "key"))))
              (if (member key '("compiler/nx-basic.lisp:26548" "compiler/optimizers.lisp:13586") :test #'equal)
                (let ((flow (function-ir afunc))
                      (observation (ccl-startup-census::function-observation afunc)))
                  (multiple-value-prog1 (apply old afunc args)
                    (push (obj "source" key "source_record" (first ccl-census-macros::*sources*)
                               "native_function_id" (ident (ccl::afunc-lfun afunc))
                               "observation" observation "flow" flow) *records*)))
                (apply old afunc args)))))
        (funcall thunk))
      (setf (ccl::backend-p2-compile host) old))))
(defun run ()
  (let* ((*records* nil) (host ccl::*host-backend*) (old (ccl::backend-p2-compile host))
         (tag (gensym)))
    (unless (eq :escaped (catch tag (with-observer (lambda () (throw tag :escaped)))))
      (error "FLOW-ESCAPE-FAILED"))
    (unless (eq (ccl::backend-p2-compile host) old) (error "FLOW-NONLOCAL-RESTORATION"))
    (with-observer #'ccl-target-setf::run)
    (unless (eq (ccl::backend-p2-compile host) old) (error "FLOW-OBSERVER-NOT-RESTORED"))
    (with-open-file (out (ccl:getenv "CCL_FLOW_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
      (ccl-startup-census::json
        (obj "version" 1 "records" (reverse *records*) "probes" (probes) "observer_restored" :true
             "nonlocal_observer_restored" :true "ir_modified" :false "global_definitions_changed" :false) out)
      (terpri out))))
