(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("hash_gc" (lambda (get put gc table key)
                   (let ((value (cons 19 23)))
                    (funcall put table key value)
                    (multiple-value-bind (v present) (funcall get table key nil)
                     (funcall gc nil nil nil)
                     (values (eq v (funcall get table key nil)) present (car v) (cdr v))))))
                ("hash_gc_values" (lambda (get gc table key)
                   (multiple-value-bind (v p) (unwind-protect (funcall get table key nil) (funcall gc nil nil nil))
                    (values (car v) (cdr v) p))))
                ("hash_dynamic" (lambda (operation receiver table key value) (multiple-value-call receiver (funcall operation table key value))))
                ("hash_dynamic_indirect" (lambda (operation receiver table key value) (multiple-value-call receiver (if key (funcall operation table key value) (funcall operation table nil value)))))
                ("hash_receiver" (lambda (&optional value present) (values value present)))
                ("hash_call" (lambda (operation table key value) (funcall operation table key value)))
                ("hash_values" (lambda (operation table key value) (multiple-value-bind (v p) (funcall operation table key value) (values v p))))
                ("hash_preserve" (lambda (operation table key value) (multiple-value-prog1 (funcall operation table key value) (eq key value))))
                ("hash_apply" (lambda (operation table key value) (apply operation (cons table (cons key (cons value nil)))))))))
 (dolist (row cases)
  (let ((result (compile-call-form (second row) (first row) (mapcar #'first cases))))
   (dolist (m (cons result (getf result :children)))
    (push m modules)
    (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
 (let* ((table (make-hash-table :test 'eq)) (key (cons 7 nil))
        (get (lambda (table key default) (gethash key table default)))
        (put (lambda (table key value) (setf (gethash key table) value)))
        (gc (lambda (a b c) (declare (ignore a b c)) (ccl:gc)))
        (first (multiple-value-list (funcall (compile nil (second (assoc "hash_gc" cases :test #'equal))) get put gc table key)))
        (second (multiple-value-list (funcall (compile nil (second (assoc "hash_gc_values" cases :test #'equal))) get gc table key))))
  (with-open-file (s (concatenate 'string out "native-moving.json") :direction :output :if-exists :error)
   (format s "[")
   (loop for values in (list first second) for i from 0 do
    (unless (zerop i) (format s ",")) (format s "[")
    (loop for v in values for j from 0 do (unless (zerop j) (format s ",")) (format s "~d" (cond ((eq v t) 77838) ((null v) 77825) (t (* v 4)))))
    (format s "]")) (format s "]")))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
