(in-package :ccl)

;;; Small semantic witnesses supplement the unchanged source definitions.
;;; None of these definitions is counted in bootstrap throughput.
(defparameter *frontend-cases*
  '(("macro_scope"
     (lambda (x)
       (macrolet ((pick (form) `(car ,form)))
         (symbol-macrolet ((value (pick x)))
           (let ((value (cdr x)))
             (values value (pick x)))))))
    ("setf_order"
     (lambda (x)
       (let ((log nil))
         (setf (car (progn (push 1 log) x))
               (progn (push 2 log) 7))
         (values x log))))
    ("setf_value"
     (lambda (x)
       (values (setf (car x) (cdr x)) x)))
    ("setf_cdr"
     (lambda (x)
       (values (setf (cdr x) (car x)) x)))
    ("cond_values"
     (lambda (x)
       (cond ((car x) (values (car x) (cdr x)))
             (t (values)))))
    ("case_nil"
     (lambda (x)
       (case x
         (nil 1)
         (t 2))))
    ("typed_values"
     (lambda (x)
       (the (values t t) (values x (cdr x)))))
    ("not_eq"
     (lambda (x)
       (values (not (eq (car x) (cdr x))) (not x) (not (not x)))))
    ("defaults"
     (lambda (x &optional (y (when x (car x))))
       (declare (ignorable x))
       y))
    ("local_macro"
     (lambda (x)
       (macrolet ((choose (y) `(if ,y 17 23)))
         (flet ((choose (y) (car y)))
           (choose x)))))
    ("target_word"
     (lambda () target::node-size))))

(defparameter *bootstrap-value* nil)
(defparameter *bootstrap-other* nil)

(setq *frontend-cases*
      (append *frontend-cases*
        '(("quote_symbol" (lambda (x) (values 'type-error (eq x 'type-error))))
          ("quote_list" (lambda (x) (declare (ignore x)) '(ccl::hello :world type-error)))
          ("quote_identity" (lambda (x) (declare (ignore x))
                              (eq (car '(ccl::hello)) 'ccl::hello)))
          ("quote_keyword" (lambda (x) (values :|mixed Name| (eq x :|mixed Name|))))
          ("quote_closure" (lambda (x)
                             (let ((f (lambda () (eq x 'type-error)))) (funcall f))))
          ("special_read" (lambda (x) (declare (ignore x)) *read-base*))
          ("special_bind" (lambda (x)
                            (values (let ((*bootstrap-value* x)) *bootstrap-value*)
                                    *bootstrap-value*)))
          ("special_set" (lambda (x)
                           (let ((*bootstrap-value* x))
                             (setq *bootstrap-value* (cons x x)) *bootstrap-value*)))
          ("special_throw" (lambda (x)
                             (values (catch 'done
                                       (let ((*bootstrap-value* x))
                                         (unwind-protect (throw 'done *bootstrap-value*)
                                           (setq *bootstrap-value* nil))))
                                     *bootstrap-value*)))
          ("special_closure" (lambda (x)
                               (let ((f (lambda () *bootstrap-value*)))
                                 (values (let ((*bootstrap-value* x)) (funcall f))
                                         (funcall f)))))
          ("special_parallel" (lambda (x)
                                (let ((*bootstrap-value* x)
                                      (*bootstrap-other* *bootstrap-value*))
                                  (values *bootstrap-value* *bootstrap-other*))))
          ("special_sequential" (lambda (x)
                                  (let* ((*bootstrap-value* x)
                                         (*bootstrap-other* *bootstrap-value*))
                                    (values *bootstrap-value* *bootstrap-other*))))
          ("special_parameter" (lambda (*bootstrap-value* &optional
                                          (y *bootstrap-value*))
                                 (values *bootstrap-value* y)))
          ("special_progv" (lambda (x)
                             (progv '(*bootstrap-value*) (cons x nil)
                               (setq *bootstrap-value* (cons *bootstrap-value* x))
                               *bootstrap-value*)))
          ("or_values" (lambda (x) (or (values x 99) (values nil 2 3 4 5))))
          ("or_zero" (lambda (x) (declare (ignore x)) (or (values) (values))))
          ("or_last_zero" (lambda (x) (or x (values))))
          ("or_order" (lambda (x)
                         (let ((log nil))
                           (values (or (progn (push 1 log) nil)
                                       (progn (push 2 log) x)
                                       (progn (push 3 log) (cons 4 5)))
                                   log))))
          ("or_nonlocal" (lambda (x)
                            (catch 'done (or nil (throw 'done (values x 9)) 3))))
          ("or_tail" (lambda (x)
                        (labels ((walk (l) (or (null l) (walk (cdr l)))))
                          (walk x)))))))

(in-package :wasm32-compiler)
(setq *extra-inputs*
      '(("quote_symbol" (type-error) (:other))
        ("quote_list" (nil)) ("quote_identity" (nil))
        ("quote_keyword" (:|mixed Name|) (nil))
        ("quote_closure" (type-error) (:other))
        ("special_read" (nil))
        ("special_bind" ((1 . 2)) (nil) (3))
        ("special_set" ((1 . 2)) (nil) (3))
        ("special_throw" ((1 . 2)) (nil) (3))
        ("special_closure" ((1 . 2)) (nil) (3))
        ("special_parallel" ((1 . 2)) (nil) (3))
        ("special_sequential" ((1 . 2)) (nil) (3))
        ("special_parameter" ((1 . 2)) (nil) (3))
        ("special_progv" ((1 . 2)) (nil) (3))
        ("or_values" (nil) ((1 . 2)) (3))
        ("or_zero" (nil)) ("or_last_zero" (nil) (t))
        ("or_order" (nil) ((1 . 2)) (3))
        ("or_nonlocal" ((1 . 2)) (nil) (3))
        ("or_tail" (nil) ((1 2 3 4 5)))
        ("default_print_level" (:default) (nil) (3))
        ("default_print_length" (:default) (nil) (3))
        ("bitp" (nil) (0) (1) (2) ((1 . 2)))))

(in-package :ccl)
(defun bootstrap-collect () (gc) nil)
(push '("collector_probe" (lambda () nil) bootstrap-collect) *frontend-cases*)
(dolist (row
         '(("or_collect" (lambda (x)
                            (let ((y (cons 'type-error x)))
                              (or (progn (bootstrap-collect) nil) y))))
           ("special_collect" (lambda (x)
                                 (let ((*bootstrap-value* (cons 'type-error x)))
                                   (bootstrap-collect)
                                   *bootstrap-value*)))
           ("pool_collect" (lambda (x)
                              (declare (ignore x))
                              (let ((literal '#2=(type-error :world)))
                                (bootstrap-collect)
                                (eq literal '#2#))))
           ("quote_cycle" (lambda (x)
                             (declare (ignore x))
                             (let ((literal '#1=(type-error . #1#)))
                               (bootstrap-collect)
                               (values (eq literal (cdr literal)) (car literal)))))))
  (push row *frontend-cases*))
(let ((a (make-symbol "SAME")) (b (make-symbol "SAME")))
  (push `("quote_uninterned" (lambda (x)
                                (declare (ignore x))
                                (values (eq ',a ',b) (eq ',a ',a))))
        *frontend-cases*))
(push '("quote_packages" (lambda (x)
                            (declare (ignore x))
                            (values (eq 'ccl::same 'wasm32-compiler::same)
                                    'ccl::same 'wasm32-compiler::same))) *frontend-cases*)
(in-package :wasm32-compiler)
(setq *extra-inputs*
      (append '(("collector_probe" ())
                ("or_collect" ((1 . 2)) (nil))
                ("special_collect" ((1 . 2)) (nil))
                ("pool_collect" (nil))
                ("quote_cycle" (nil))
                ("quote_uninterned" (nil))
                ("quote_packages" (nil))) *extra-inputs*))
