(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(load (merge-pathnames "measure.lisp" *load-pathname*))
(load (merge-pathnames "controls.lisp" *load-pathname*))
(load (merge-pathnames "legacy.lisp" *load-pathname*))
(load (merge-pathnames "extra.lisp" *load-pathname*))
(defvar *frontend-directory* (make-pathname :name nil :type nil :defaults *load-pathname*))

(defun frontend-json-value (x s)
  (cond ((null x) (write-string "null" s))
        ((eq x t) (write-string "true" s))
        ((integerp x) (princ x s))
        ((symbolp x) (format s "{\"symbol\":~s}" (frontend-owner x)))
        ((consp x)
         (write-char #\[ s)
         (frontend-json-value (car x) s)
         (write-char #\, s)
         (frontend-json-value (cdr x) s)
         (write-char #\] s))
        (t (error "Unexpected oracle value ~s" x))))

(let* ((out (ccl:getenv "POOL_OUTPUT"))
       (chunks (with-open-file (s (merge-pathnames "source-chunks.lisp" *frontend-directory*))
                 (second (read s))))
       (modules nil)
       (selected '(ccl::memq ccl::append-2 ccl::adjoin-eq ccl::union-eq ccl::loading-file-source-file ccl::default-print-level ccl::default-print-length ccl::bitp))
       (rows nil))
  (frontend-controls out)
  (frontend-legacy out)
  (measure-frontend chunks out)
  (dolist (name selected)
    (let* ((record (find name *frontend-functions* :key (lambda (r) (second (third r)))))
           (form (third record)))
      (assert form)
      (push (list (substitute #\_ #\- (string-downcase (symbol-name name))) form name) rows)))
  (call-with-target
   (lambda () (load (merge-pathnames "entry-cases.lisp" *frontend-directory*))))
  (with-open-file (s (concatenate 'string out "original-definitions.lisp") :direction :output :if-exists :error)
    (let ((*package* (find-package "CCL")) (*print-circle* t))
      (dolist (row (reverse rows)) (pprint (second row) s))))
  (setq rows (append (nreverse rows) ccl::*frontend-cases*))
  (let ((links (loop for row in rows when (third row) collect (list (third row) (first row)))))
    (dolist (row rows)
      (let ((result (call-with-target
                     (lambda ()
                       (if (equal (first row) "target_word")
                         (compile-bootstrap-source "(lambda () target::node-size)" "target_word" nil)
                         (compile-bootstrap-form (second row) (first row) links))))))
        (dolist (m (cons result (getf result :children)))
          (push m modules)
          (with-open-file (s (concatenate 'string out (getf m :name) ".wat")
                             :direction :output :if-exists :error)
            (write-string (getf m :wat) s))))))
  (setq modules (nreverse modules))
  (with-open-file (s (concatenate 'string out "originals.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for name in selected for i from 0 do
      (unless (zerop i) (write-char #\, s)) (format s "~s" (symbol-name name)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (format s "[")
    (loop for m in modules for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"symbols\":[" (getf m :name))
      (loop for (symbol wire) in (getf m :symbols) for j from 0 do
        (unless (zerop j) (write-char #\, s))
        (format s "[~s,~s]" wire (frontend-owner symbol)))
      (format s "],\"function\":")
      (let ((row (find (getf m :name) rows :key #'first :test #'equal)))
        (if (third row) (format s "~s" (frontend-owner (third row))) (write-string "null" s)))
      (format s "}"))
    (format s "]"))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error)
    (let ((roots (mapcar (lambda (m) (getf m :pool)) modules)))
      (frontend-pool-owners roots)
      (write-pool-graph s roots)))
  
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
    (format s "[")
    (let ((count 0))
      (dolist (row rows)
        (let* ((name (first row))
               (fn (if (third row) (fdefinition (third row)) (compile nil (second row))))
               (inputs (cond ((string= name "memq") '((1 nil) (1 (1 2)) (2 (1 2 3)) (4 (1 2))))
                             ((member name '("append_2" "union_eq") :test #'equal)
                              '((nil nil) ((1 2) nil) (nil (3 4)) ((1 2) (2 3))))
                             ((string= name "adjoin_eq") '((1 nil) (1 (1 2)) (3 (1 2))))
                             ((string= name "case_nil") '((nil) (1) (t)))
                             ((member name '("target_word" "loading_file_source_file") :test #'equal) '(()))
                             ((assoc name *extra-inputs* :test #'equal) (cdr (assoc name *extra-inputs* :test #'equal)))
                             (t '(((1 . 2)) ((nil . 3)) ((4 . 4)))))))
          (dolist (input inputs)
            (let ((args (copy-tree input)))
              (unless (zerop count) (write-char #\, s))
              (incf count)
              (format s "{\"name\":~s,\"args\":[" name)
              (loop for arg in args for i from 0 do
                (unless (zerop i) (write-char #\, s))
                (frontend-json-value arg s))
              (format s "],\"values\":[")
              (loop for value in (let ((ccl::*loading-file-source-file* nil) (*print-level* 7) (*print-length* 9))
                                                     (multiple-value-list (apply fn args))) for i from 0 do
                (unless (zerop i) (write-char #\, s))
                (frontend-json-value value s))
              (format s "],\"after\":[")
              (loop for arg in args for i from 0 do
                (unless (zerop i) (write-char #\, s))
                (frontend-json-value arg s))
              (format s "]}")))))
    (format s "]"))))
(frontend-write-owners (ccl:getenv "POOL_OUTPUT"))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
