(in-package :wasm32-compiler)
(defvar *extra-inputs* nil)

(defun frontend-owner (symbol)
  (or (cdr (assoc symbol *pool-symbol-owners*))
      (let ((name (format nil "s~d" (length *pool-symbol-owners*))))
        (push (cons symbol name) *pool-symbol-owners*)
        name)))

(defun frontend-pool-owners (roots)
  (let ((seen (make-hash-table :test #'eq)))
    (labels ((walk (x)
               (unless (gethash x seen)
                 (setf (gethash x seen) t)
                 (cond ((and (symbolp x) x (not (eq x t))) (frontend-owner x))
                       ((consp x) (walk (car x)) (walk (cdr x)))
                       ((simple-vector-p x) (map nil #'walk x))))))
      (mapc #'walk roots))))

(defun frontend-write-owners (out)
  (with-open-file (s (concatenate 'string out "symbols.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for (symbol . id) in (reverse *pool-symbol-owners*) for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (format s "{\"id\":~s,\"name\":~s,\"package\":" id (symbol-name symbol))
      (if (symbol-package symbol) (format s "~s" (package-name (symbol-package symbol)))
          (write-string "null" s))
      (format s "}"))
    (write-char #\] s)))
