(in-package "CL-USER")
(defvar *repr-native-functions* nil)
(defvar *repr-sources*)
(defvar *repr-cases*)
(defun repr-token (value objects)
  (cond ((null value) "nil") ((eq value t) "t")
        ((integerp value) value)
        ((position value objects :test #'eq) (format nil "n~d" (position value objects :test #'eq)))
        (t (error "Unrepresented native value"))))
(defun repr-json-token (stream value)
  (if (integerp value) (princ value stream) (format stream "~s" value)))
(defun repr-native-case (stream case)
  (destructuring-bind (id name nodes inputs) case
    (let* ((objects (make-array (length nodes))) (fn (cdr (assoc name *repr-native-functions* :test #'equal))))
      (dotimes (i (length nodes)) (setf (aref objects i) (cons nil nil)))
      (labels ((decode (v)
                 (cond ((equal v "nil") nil) ((equal v "t") t)
                       ((stringp v) (aref objects (parse-integer v :start 1))) (t v))))
        (loop for pair in nodes for i from 0 do
          (rplaca (aref objects i) (decode (first pair)))
          (rplacd (aref objects i) (decode (second pair))))
      (format stream "{\"id\":~s," id)
      (handler-case
          (let ((values (multiple-value-list (apply fn (mapcar #'decode inputs)))))
            (assert (= (length values) 1)) (format stream "\"status\":\"RETURN\",\"value\":")
            (repr-json-token stream (repr-token (first values) objects)))
        (type-error (c) (format stream "\"status\":\"TYPE_ERROR\",\"datum\":")
          (repr-json-token stream (repr-token (type-error-datum c) objects))
          (format stream ",\"expected_kind\":~d" (if (subtypep (type-error-expected-type c) 'cons) 2 1))))
      (format stream ",\"nodes\":[")
      (dotimes (i (length nodes))
        (unless (zerop i) (write-char #\, stream)) (write-char #\[ stream)
        (repr-json-token stream (repr-token (car (aref objects i)) objects)) (write-char #\, stream)
        (repr-json-token stream (repr-token (cdr (aref objects i)) objects)) (write-char #\] stream))
      (write-string "]}" stream)))))
(let ((out (ccl:getenv "REPR_OUTPUT")))
  (load (ccl:getenv "REPR_CASES"))
  (defparameter *repr-native-functions* nil)
  (dolist (entry *repr-sources*)
    (destructuring-bind (name source) entry
      (push (cons name (compile nil (read-from-string source))) *repr-native-functions*)
      (let ((module (wasm32-compiler::compile-module source name)))
        (assert (= (getf module :arity) 3))
        (with-open-file (s (concatenate 'string out name ".wat") :direction :output :if-exists :error)
          (write-string (getf module :wat) s)))))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for row in *repr-cases* for i from 0 do
      (unless (zerop i) (write-char #\, s)) (repr-native-case s row))
    (write-char #\] s))
  (format t "S1-REPRESENTATION-COMPILE-PASS~%") (ccl:quit))
