;;; Native oracle models the declared fixture; target runs the product service.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0))))
#-wasm32-target
(progn
 (defvar *fa-next* 1)
 (defvar *fa-tokens* (make-hash-table))
 (defvar *fa-names* (make-hash-table :test 'equal))
 (defun fa-native-token (value)
   (prog1 *fa-next* (setf (gethash *fa-next* *fa-tokens*) value) (incf *fa-next*)))
 (defun %wasm-host-process-request (selector operation payload)
   (assert (= selector 15))
   (flet ((token (id) (gethash id *fa-tokens*)))
    (case operation
      (0 (or (gethash payload *fa-names*)
             (if (member payload '("example" "trap" "destructor" "primary" "close") :test #'equal)
               (setf (gethash payload *fa-names*) (fa-native-token (vector :library t 0 0))) -1)))
      (1 (setf (svref (token payload) 1) nil) 0)
      (2 (let* ((lib (token (svref payload 0))) (name (svref payload 1)) (a (svref payload 2)) (status 0) result)
           (unless (svref lib 1) (return-from %wasm-host-process-request -1))
           (cond ((equal name "echo") (setq result a))
                 ((equal name "mode") (setf (svref lib 3) (svref a 0)) (setq result #()))
                 ((equal name "releases") (setq result (vector (svref lib 2))))
                 ((equal name "run")
                  (let* ((range (token (svref a 0))) (buffer (token (svref range 1)))
                         (bytes (svref buffer 2)) (offset (svref range 2)) (n (svref a 1)) (mode (svref a 2)))
                    (unless (svref buffer 3) (return-from %wasm-host-process-request -1))
                    (case mode
                      (1 (setq status -3))
                      (2 (setf (svref lib 1) nil) (setq status -2))
                      (t (unless (zerop n) (incf (aref bytes offset)))
                         (setq result (vector (loop for i from offset below (+ offset n) sum (aref bytes i))))))))
                 (t (setq status -1)))
           (setf (svref payload 3) result) status))
      (3 (let ((lib (token (svref payload 0))) (n (svref payload 1)))
           (if (and (svref lib 1) (plusp n) (<= n 65536))
             (fa-native-token (vector :buffer lib (make-array n :element-type '(unsigned-byte 8) :initial-element 0) t)) -1)))
      (4 (let* ((buffer (token payload)) (lib (svref buffer 1)))
           (if (and (svref buffer 3) (svref lib 1))
             (progn (setf (svref buffer 3) nil) (incf (svref lib 2))
                    (if (zerop (svref lib 3)) 1 (progn (setf (svref lib 1) nil) -2))) 0)))
      (5 (let ((buffer (token (svref payload 0))))
           (if (svref buffer 3) (fa-native-token (vector :range (svref payload 0) (svref payload 1))) -1)))
      ((6 7) (let* ((buffer (token (svref payload 0))) (offset (svref payload 1)) (bytes (svref payload 2)) (storage (svref buffer 2)))
               (if (and (svref buffer 3) (svref (svref buffer 1) 1) (<= (+ offset (length bytes)) (length storage)))
                 (progn (if (= operation 6) (replace storage bytes :start1 offset) (replace bytes storage :start2 offset)) 0) -1)))
      (t -1)))))

(defvar *fa-binding* :outside)
(defun fa-bytes ()
  (make-array 8 :element-type '(unsigned-byte 8) :initial-contents '(65 195 169 240 159 140 141 0)))
(defun fa-row (name value) (format t "FA-ROW ~A ~S~%" name value))
(defun fa-success (library)
  (let* ((bytes (fa-bytes)) (alias (cons bytes bytes)) (closure (lambda () bytes)) (*fa-binding* bytes))
    (with-wasm-buffer (h library 16)
      (write-wasm-buffer h bytes 4)
      (let* ((result (wasm-call library "run" (wasm-buffer-range h 4) 8 0))
             (copy (read-wasm-buffer h 8 4)))
        (list result (coerce copy 'list) (eq (car alias) bytes) (eq (cdr alias) bytes)
              (eq (funcall closure) bytes) (eq *fa-binding* bytes) (coerce bytes 'list))))))
(defun fa-failure (name mode destructor)
  (let ((library (open-wasm-library name)) (cleanups 0) (bytes (fa-bytes)))
    (let ((*fa-binding* bytes))
      (list (handler-case
              (unwind-protect
                (with-wasm-buffer (a library 16)
                  (with-wasm-buffer (b library 16)
                    (write-wasm-buffer a bytes)
                    (wasm-call library "mode" destructor)
                    (wasm-call library "run" (wasm-buffer-range a) 8 mode)))
                (incf cleanups))
              (error (condition)
                (list :caught (second (simple-condition-format-arguments condition)))))
            cleanups (eq *fa-binding* bytes)))))
(let ((library (open-wasm-library "example")))
  (fa-row 'open-once (= library (open-wasm-library "example")))
  (fa-row 'scalars (multiple-value-list (wasm-call library "echo" -2147483648 -9223372036854775808 1.5f0 -0.0d0)))
  (fa-row 'scalar-max (multiple-value-bind (a b c d)
                           (wasm-call library "echo" 2147483647 9223372036854775807 -0.0f0 1.25d0)
                         (list a b (eql c -0.0f0) (eql d 1.25d0))))
  (fa-row 'copy-moving (fa-success library))
  (fa-row 'values (multiple-value-list (with-wasm-buffer (h library 16) (values 11 12 nil))))
  (fa-row 'nonlocal (block out (with-wasm-buffer (h library 16) (return-from out :escaped))))
  (fa-row 'recoverable (fa-failure "example" 1 0))
  (fa-row 'after-exception (fa-success library))
  (let* ((h (allocate-wasm-buffer library 8)) (r (wasm-buffer-range h)))
    (fa-row 'release (list (release-wasm-buffer h) (release-wasm-buffer h)))
    (fa-row 'stale-range (handler-case (wasm-call library "run" r 0 0) (error () :caught))))
  (fa-row 'bad-size (handler-case (allocate-wasm-buffer library 0) (error () :caught)))
  (fa-row 'missing-export (handler-case (wasm-call library "absent") (error () :caught)))
  (fa-row 'releases (wasm-call library "releases")))
(fa-row 'trap (fa-failure "trap" 2 0))
(fa-row 'destructor (fa-failure "destructor" 0 1))
(fa-row 'primary (fa-failure "primary" 1 1))
(let* ((library (open-wasm-library "close")) (h (allocate-wasm-buffer library 8)))
  (close-wasm-library library)
  (fa-row 'close-release (release-wasm-buffer h))
  (fa-row 'closed-call (handler-case (wasm-call library "releases") (error () :caught))))
(fa-row 'missing-library (handler-case (open-wasm-library "absent") (error () :caught)))
(fa-row 'binding *fa-binding*)
(write-line "FA-PASS")
