(in-package :ccl)
(load (getenv "PN_LOWER"))
(dolist (row
 '(("short" (lambda (p x) (pushnew x)))
   ("place-arity" (lambda (p x) (pushnew x (population-data p x))))
   ("extra-option" (lambda (p x) (pushnew x (population-data p) :test #'eq :test #'eq)))
   ("key" (lambda (p x) (pushnew x (population-data p) :key #'car)))
   ("test-not" (lambda (p x) (pushnew x (population-data p) :test-not #'eq)))
   ("place" (lambda (p x) (pushnew x (car p))))
   ("shadow" (lambda (p x) (flet ((eq (a b) t)) (pushnew x (population-data p) :test #'eq))))))
 (let ((refused nil))
  (handler-case (lower-population-pushnew (second row)) (error () (setq refused t)))
  (unless refused (error "pushnew admission ~a" (first row)))))
(format t "PUSHNEW-ADMISSION-PASS~%")
(quit)
