(in-package :ccl)
(defparameter *population-consumer-cases*
 '(("pn_duplicate" (lambda (p a b log) (let ((old (population-data p))) (values (eq (pushnew a (population-data p)) old) (population-data p)))))
   ("pn_new" (lambda (p a b log) (let ((x (cons 41 43)) (old (population-data p))) (let ((answer (pushnew x (population-data p)))) (values (eq answer (population-data p)) (eq (cdr answer) old) (eq (car answer) x))))))
   ("pn_twice" (lambda (p a b log) (let ((x (cons 41 43))) (pushnew x (population-data p)) (let ((old (population-data p))) (values (eq (pushnew x (population-data p)) old) old)))))
   ("pn_equal_cons" (lambda (p a b log) (pushnew (cons 17 23) (population-data p))))
   ("pn_effects" (lambda (p a b log) (pushnew (progn (rplaca log (cons 7 (car log))) a) (population-data (progn (rplaca log (cons 9 (car log))) p))) (car log)))
   ("pn_empty" (lambda (p a b log) (setf (population-data p) nil) (pushnew a (population-data p))))
   ("pn_nil" (lambda (p a b log) (pushnew nil (population-data p)) (let ((old (population-data p))) (values (eq (pushnew nil (population-data p)) old) old))))
   ("pn_integer" (lambda (p a b log) (pushnew 12345678901234567890 (population-data p)) (let ((old (population-data p))) (values (eq (pushnew 12345678901234567890 (population-data p)) old) old))))
   ("pn_float" (lambda (p a b log) (pushnew 2.0d0 (population-data p)) (let ((old (population-data p))) (values (eq (pushnew 2.0d0 (population-data p)) old) old))))
   ("pn_eq" (lambda (p a b log) (pushnew a (population-data p) :test #'eq)))
   ("pn_test_nil" (lambda (p a b log) (pushnew a (population-data p) :test nil)))
   ("pn_predicate" (lambda (p a b log) (pushnew (cons 17 99) (population-data p) :test (lambda (x y) (rplaca log (cons 3 (car log))) (eq (car x) (car y))))))
   ("pn_collect" (lambda (p a b log) (pushnew a (population-data p) :test (lambda (x y) (pop_gc nil nil nil) (eq x y)))))
   ("pn_place_collect" (lambda (p a b log) (pushnew (cons 41 43) (population-data (progn (pop_gc nil nil nil) p)))))
   ("pn_cleanup" (lambda (p a b log) (unwind-protect (pop_gc nil nil nil) (pushnew a (population-data p)))))
   ("pn_exit" (lambda (p a b log) (catch '17 (pushnew a (population-data p) :test (lambda (x y) (throw '17 (eq x y)))))))
   ("pn_test_order" (lambda (p a b log) (pushnew (progn (rplaca log (cons 7 (car log))) a) (population-data (progn (rplaca log (cons 9 (car log))) p)) :test (progn (rplaca log (cons 11 (car log))) (lambda (x y) (eq x y)))) (car log)))))
