;; Each record's source is read only after the complete target context is active.
(word-width (lambda () #.target::nbits-in-word))
(fixnum-shift (lambda () #.target::fixnumshift))
(cons-tag (lambda () #.target::fulltag-cons))
(misc-tag (lambda () #.target::fulltag-misc))
(reader-feature (lambda () #+wasm32-target :wasm #-wasm32-target :wrong-host))
(reader-width (lambda () #+32-bit-target 32 #-32-bit-target 64))
(borrowed-native-feature (lambda () #+x8632-target :wrong-host #-x8632-target :isolated))
(host-feature (lambda () #+x8664-target :wrong-host #-x8664-target :isolated))
(macro-capture (lambda () (ccl-census-stub::captured-width)))
(natural-access (lambda (p) (ccl::%get-natural p)))
(fixnum-boundary (lambda () 536870912))
(b-arguments (lambda (a b c d e) (census-sink a b c d e)))
(lexical-call (lambda (x) (flet ((local (y) (declare (notinline local)) (census-sink y))) (declare (notinline local)) (local x))))
(dynamic-call (lambda (fn x) (funcall fn x)))
