;;; First production backend slice. Unsupported acode is refused, never sent to a native pass 2.
(defpackage "WASM32-COMPILER" (:use "CL"))
(defpackage "WASM32-OS" (:use))
(in-package "WASM32-COMPILER")
(defvar *module-result-tag* nil)
(defvar *module-name* nil)
(defvar *required-vars* nil)
(define-condition unsupported-wasm32-code (error)
  ((operation :initarg :operation :reader unsupported-operation))
  (:report (lambda (c s) (format s "WASM32 lowering not implemented: ~s" (unsupported-operation c)))))
(defun refuse (operation) (error 'unsupported-wasm32-code :operation operation))
(defun wasm32-pass2 (afunc &rest ignored)
  (declare (ignore ignored))
  (unless *module-result-tag* (refuse :native-fasl-publication))
  (let* ((ir (ccl::afunc-acode afunc)) (args (ccl::acode-operands ir)))
    (unless (and (eq (ccl::acode-operator-name (ccl::acode-operator ir)) 'ccl::lambda-list)
                 (null (second args)) (null (third args)) (null (fourth args))
                 (equal (fifth args) '(nil nil)))
      (refuse :lambda-list))
    (let* ((*required-vars* (first args))
           (body (emit-expression (sixth args)))
           (arity (length *required-vars*))
           (wat (format nil "(module~% (import ~s ~s (memory 1 32769 shared))~% (import ~s ~s (global $tcr i32))~% (func (export ~s) (param $self i32) (param $nargs i32) (result i32 i32) (local $value i32)~%  (if (i32.ne (local.get $nargs) (i32.const ~d)) (then unreachable))~%  (local.set $value ~a)~%  (i32.store (i32.load offset=~d (global.get $tcr)) (local.get $value))~%  (i32.store offset=~d (global.get $tcr) (i32.const 1))~%  (local.get $value) (i32.const 1)))~%"
             "env" "memory" "env" "tcr" "entry" arity body wasm32::tcr.mv_base wasm32::tcr.mv_count)))
      (throw *module-result-tag* (list :version 1 :name *module-name* :arity arity :wat wat)))))
(defun emit-expression (ir)
  (unless (ccl::acode-p ir) (refuse :malformed-acode))
  (let ((op (ccl::acode-operator-name (ccl::acode-operator ir)))
        (args (ccl::acode-operands ir)))
    (case op
      ((nil) (format nil "(i32.const ~d)" wasm32::canonical-nil-value))
      ((t) (format nil "(i32.const ~d)" wasm32::canonical-t-value))
      (ccl::fixnum
       (let ((n (first args)))
         (unless (<= wasm32::target-most-negative-fixnum n wasm32::target-most-positive-fixnum) (refuse :fixnum-range))
         (format nil "(i32.const ~d)" (ash n wasm32::fixnumshift))))
      (ccl::immediate
       (cond ((null (first args)) (format nil "(i32.const ~d)" wasm32::canonical-nil-value))
             ((eq (first args) t) (format nil "(i32.const ~d)" wasm32::canonical-t-value))
             (t (refuse :heap-constant))))
      (ccl::lexical-reference
       (let ((index (position (first args) *required-vars* :test #'eq)))
         (unless index (refuse :non-argument-lexical))
         (format nil "(i32.load offset=~d (i32.load offset=~d (global.get $tcr)))" (* 4 index) wasm32::tcr.vsp)))
      (ccl::if
       (format nil "(if (result i32) (i32.ne ~a (i32.const ~d)) (then ~a) (else ~a))"
         (emit-expression (first args)) wasm32::canonical-nil-value
         (emit-expression (second args)) (emit-expression (third args))))
      (t (refuse op)))))
;;; The next unused three-bit CPU discriminator; no existing target changes.
(defconstant ccl::platform-cpu-wasm32 (ash 4 3))
(defconstant ccl::platform-os-wasm 7)
(defvar *backend*
  (ccl::make-backend :name :wasm32 :num-arg-regs 0 :target-arch-name :wasm32
    :target-arch wasm32::*target-arch* :target-platform (logior ccl::platform-cpu-wasm32 ccl::platform-os-wasm ccl::platform-word-size-32) :target-os :wasm
    :target-specific-features '(:wasm-target :wasm32-target :32-bit-target :little-endian-target)
    :target-fasl-pathname (make-pathname :type "w32fsl")
    :p2-dispatch #() :p2-compile 'wasm32-pass2 :p2-vinsn-templates (make-hash-table :test #'eq)
    :target-foreign-type-data (ccl::make-ftd :interface-package-name "WASM32-OS" :attributes '(:bits-per-word 32))))
(when (and (ccl::find-backend :wasm32) (not (eq *backend* (ccl::find-backend :wasm32))))
  (error "Conflicting WASM32 backend"))
(when (find (ccl::backend-target-platform *backend*) ccl::*known-backends* :key #'ccl::backend-target-platform :test #'=)
  (unless (member *backend* ccl::*known-backends*) (error "WASM32 platform discriminator collision")))
(pushnew *backend* ccl::*known-backends* :key #'ccl::backend-name)
(defun call-with-target (thunk)
  (let* ((ccl::*target-backend* *backend*) (ccl::*fasl-target* :wasm32)
         (*features* (ccl::setup-target-features *backend* *features*)))
    (ccl::with-cross-compilation-target (:wasm32) (funcall thunk))))
;;; Until target macro/helper qualification is integrated, the source API admits
;;; only the syntax this leaf slice implements. Pass-2 refusal alone is too late:
;;; a host compiler macro can fold an unsupported call to an apparently safe IR
;;; constant. This is a declared subset boundary, not an implementation of TYPEP.
(defun validate-leaf-source (form)
  (let ((budget 4096) (active (make-hash-table :test #'eq)))
    (labels ((items (x)
               (let ((seen (make-hash-table :test #'eq)) (result nil))
                 (loop while (consp x) do
                   (when (or (gethash x seen) (minusp (decf budget))) (refuse :source-shape))
                   (setf (gethash x seen) t) (push (car x) result) (setq x (cdr x)))
                 (when x (refuse :source-shape)) (nreverse result)))
             (literal (x)
               (or (null x) (eq x t)
                   (and (integerp x) (<= wasm32::target-most-negative-fixnum x wasm32::target-most-positive-fixnum))))
             (walk (x vars depth)
               (when (or (> depth 128) (minusp (decf budget))) (refuse :source-shape))
               (cond ((literal x) t)
                     ((and (symbolp x) (member x vars :test #'eq)) t)
                     ((consp x)
                      (when (gethash x active) (refuse :source-shape))
                      (setf (gethash x active) t)
                      (unwind-protect
                        (let ((xs (items x)))
                          (cond ((and (eq (car xs) 'if) (member (length xs) '(3 4)))
                                 (dolist (part (cdr xs)) (walk part vars (1+ depth))))
                                ((and (eq (car xs) 'quote) (= (length xs) 2) (literal (second xs))) t)
                                (t (refuse :source-subset))))
                        (remhash x active)))
                     (t (refuse :source-subset)))))
      (let ((parts (items form)))
        (unless (and (= (length parts) 3) (eq (first parts) 'lambda)) (refuse :source-subset))
        (let ((vars (items (second parts))))
          (unless (and (every (lambda (v) (and (symbolp v) v (not (eq v t)) (not (keywordp v))
                                                (not (member v lambda-list-keywords)))) vars)
                       (= (length vars) (length (remove-duplicates vars :test #'eq))))
            (refuse :source-subset))
          (walk (third parts) vars 0))))))
(defun compile-module (source-text name)
  (unless (and (stringp source-text) (stringp name)) (error "Source and logical name must be strings"))
  (call-with-target
    (lambda ()
      (let* ((*module-result-tag* (gensym "WASM32-PASS2")) (*module-name* name)
             (*package* (find-package "WASM32-COMPILER")) (*read-eval* nil))
        (multiple-value-bind (form end) (read-from-string source-text)
          (unless (every (lambda (c) (find c '(#\Space #\Tab #\Newline #\Return))) (subseq source-text end))
            (error "Trailing source after the lambda"))
          (validate-leaf-source form)
          (catch *module-result-tag*
            (ccl::compile-named-function form :name name :target :wasm32 :policy ccl::*default-compiler-policy*)
            (error "WASM32 pass 2 failed to publish a module")))))))
(provide "WASM32-BACKEND")
