(in-package :cl-user)
(defun census-literal (xs) (mapcar (lambda (x) (+ x 1)) xs))
(defun census-flet (xs) (flet ((stepper (x) (+ x 1))) (mapcar #'stepper xs)))
(defun census-parameter (callback xs) (mapcar callback xs))
(defun census-assigned (other xs)
  (let ((callback (lambda (x) (+ x 1)))) (setq callback other) (mapcar callback xs)))
(defun census-captured-write (other xs)
  (let ((callback (lambda (x) (+ x 1))))
    (flet ((replace-it () (setq callback other))) (replace-it) (mapcar callback xs))))
(defun census-shadowed (callback xs)
  (declare (ignore callback)) (let ((callback (lambda (x) (+ x 2)))) (mapcar callback xs)))
(defun census-closed (offset xs) (mapcar (lambda (x) (+ x offset)) xs))
(defun census-sequential-scope (callback xs)
  (let* ((result (mapcar callback xs)) (callback (lambda (x) (+ x 3)))) (values result callback)))
