(in-package :cl-user)
(progn
  (defun census-first (x) (+ x 1))
  (defun census-second (x) (census-first x)))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defmacro census-twice (x) `(+ ,x ,x))
  (deftype census-small () '(signed-byte 30)))
(defun census-expanded (x) (census-twice x))
(defun census-deferred () (load-time-value (list :deferred)))
(defun census-local-macro (x)
  (macrolet ((plus-one (x) `(+ ,x 1))) (plus-one x)))
(defstruct census-pair left right)
(defclass census-cell () ((value :initarg :value :accessor census-value)))
(defmethod census-method ((x census-cell)) (census-value x))
(ccl::include "included.lisp")
#+wasm-target (defun census-wasm-feature () :wasm)
#-wasm-target (defun census-native-feature () :native)
(eval-when (:compile-toplevel)
  (unless (equal (macroexpand-1 '(census-twice 3)) '(+ 3 3))
    (error "SOURCE-MACRO-NOT-INSTALLED")))
