;;; Census-only file compiler sink. No target instructions or FASL writer.
(defpackage :ccl-source-closure (:use :cl))
(in-package :ccl-source-closure)
(defvar *captures* nil)
(defvar *guards* nil)
(defvar *forms* nil)
(defvar *form-stack* nil)
(defvar *next-form* 0)
(defvar *owner* nil)
(defvar *active* nil)
(defvar *sink-backend* nil)
(defvar *host-effects* nil)
(defvar *macro-events* nil)
(defvar *native-compilations* nil)
(defvar *read-inputs* nil)
(defvar *gaps* nil)
(declaim (special *layout-facts* *layout-values* *layout-fields* *layout-macros*))
(declaim (ftype (function (t) *) with-data-layout))
(defvar *mode* "normal")
(defun obj (&rest xs) (apply #'ccl-source-traversal::obj xs))
(defun label (x) (ccl-source-traversal::label x))
(defun ident (x) (ccl-startup-census::dependency-id x))
(defun field (x key) (ccl-source-traversal::field x key))
(defun (setf field) (value x key)
  (loop for tail on (cdr x) by #'cddr when (equal (car tail) key)
        do (setf (cadr tail) value) (return-from field value))
  (error "CENSUS-MISSING-FIELD ~a" key))

(defun source-location ()
  (obj "file" (if (boundp 'ccl::*loading-file-source-file*)
                  (label ccl::*loading-file-source-file*) :null)
       "position" (if (and (boundp 'ccl::*fcomp-stream-position*)
                            (integerp ccl::*fcomp-stream-position*))
                       ccl::*fcomp-stream-position* :null)))

(defun native-code (function)
  ;; U1 X86 code-words counts the complete unboxed code prefix. Copy it with
  ;; the same primitive used by %COPY-FUNCTION; never decode pointer constants.
  (let* ((size (* 8 (ccl::%function-code-words function)))
         (bytes (make-array size :element-type '(unsigned-byte 8)))
         (hex (make-string (* 2 size))) (digits "0123456789abcdef"))
    (ccl::%copy-ivector-to-ivector (ccl::%function-to-function-vector function) 0 bytes 0 size)
    (dotimes (i size hex)
      (setf (char hex (* 2 i)) (char digits (ash (aref bytes i) -4))
            (char hex (1+ (* 2 i))) (char digits (logand (aref bytes i) 15))))))

(defun native-emissions (root)
  (let ((pending (list root)) (rows nil))
    (loop while pending for afunc = (pop pending) do
      (let ((fn (ccl::afunc-lfun afunc)))
        (push (obj "function_id" (ident afunc)
                   "native_function_id" (if (functionp fn) (ident fn) :null)
                   "code" (if (functionp fn) (native-code fn) :null)) rows))
      (setf pending (append (ccl::afunc-inner-functions afunc) pending)))
    (nreverse rows)))

(defun flow-graph (root)
  ;; Flat graph: list length and nesting do not consume the Lisp/JSON stack.
  ;; Opaque runtime objects stay explicit dependencies, not invented contents.
  (let ((pending (list root)) (seen (make-hash-table :test #'eq)) (rows nil))
    (labels ((ref (x)
               (cond ((null x) :null)
                     ((or (integerp x) (stringp x)) x)
                     ((symbolp x) (obj "symbol" (label x) "identity" (ident x)))
                     (t (unless (gethash x seen) (push x pending)) (obj "ref" (ident x))))))
      (loop while pending for x = (pop pending) do
        (unless (gethash x seen)
          (setf (gethash x seen) t)
          (push
            (cond
              ((ccl::acode-p x)
               (obj "id" (ident x) "kind" "acode"
                    "operator" (label (ccl::acode-operator-name (ccl::acode-operator x)))
                    "operator_id" (logand (ccl::acode-operator x) ccl::operator-id-mask)
                    "operands" (ref (ccl::acode-operands x))))
              ((typep x 'ccl::afunc)
               (obj "id" (ident x) "kind" "function" "name" (label (ccl::afunc-name x))
                    "body" (ref (ccl::afunc-acode x))
                    "children" (mapcar #'ref (ccl::afunc-inner-functions x))))
              ((typep x 'ccl::var)
               (obj "id" (ident x) "kind" "variable" "root" (ident (ccl::nx-root-var x))
                    "name" (label (ccl::var-name x))
                    "assigned" (if (logbitp ccl::$vbitsetq (ccl::nx-var-bits (ccl::nx-root-var x))) :true :false)))
              ((consp x) (obj "id" (ident x) "kind" "cons" "car" (ref (car x)) "cdr" (ref (cdr x))))
              ((functionp x)
               (obj "id" (ident x) "kind" (if (assoc x *guards* :test #'eq) "capture-guard" "native-function")
                    "function_id" (if (assoc x *guards* :test #'eq) (ident (cdr (assoc x *guards* :test #'eq))) :null)
                    "name" (label x)))
              (t (obj "id" (ident x) "kind" "opaque-object" "type" (label (type-of x))))) rows)))
      (obj "root" (ident root) "objects" (nreverse rows)))))

(defun with-routing (thunk)
  ;; Same identity-qualified selection as the reviewed router, without recursive
  ;; serialization of every expansion. Source positions and callable identities
  ;; carry dependencies; function IR is captured separately as a flat graph.
  (let* ((old *macroexpand-hook*)
         (*macroexpand-hook*
          (lambda (fn form env)
            (let* ((sequence (prog1 ccl-source-expanders::*next-event* (incf ccl-source-expanders::*next-event*)))
                   (entry (find-if (lambda (r) (and (consp form) (eq (car form) (first r))
                                                   (eq fn (fourth r)))) ccl-source-expanders::*registry*))
                   (selected (if entry (third entry) fn)) (completed nil) (result nil))
              (unwind-protect
                (progn (setf result (funcall old selected form env) completed t) result)
                (push (obj "sequence" sequence "operator" (if (consp form) (label (car form)) :null)
                           "source_location" (source-location) "form_stack" (reverse *form-stack*)
                           "source" (if entry (fifth entry) :null)
                           "original_id" (ident fn) "selected_id" (ident selected)
                           "native_note" (ccl-source-expanders::note fn)
                           "backend" (label (ccl::backend-name ccl::*target-backend*))
                           "returned_input" (if (and completed (eq result form)) :true :false)
                           "completed" (if completed :true :false)) *macro-events*))))))
    (funcall thunk)))

(defun capture-pass2 (afunc &rest ignored)
  (declare (ignore ignored))
  (unless (and *active* (eq *owner* ccl:*current-process*)
               (eq ccl::*target-backend* *sink-backend*))
    (error "CENSUS-SINK-CONTEXT"))
  (let* ((ordinal (length *guards*))
         (guard (lambda (&rest args)
                  (declare (ignore args))
                  (error "CENSUS-CODE-EXECUTION-FORBIDDEN ~d" ordinal)))
         (record (obj "ordinal" ordinal "guard_id" (ident guard)
                      "prior_gaps" (mapcar (lambda (r) (field r "form")) (reverse *gaps*))
                      "form_stack" (reverse *form-stack*) "source" (source-location)
                      "owner_id" (if (typep ccl::*nx-current-function* 'ccl::afunc)
                                     (ident ccl::*nx-current-function*) :null)
                      "function" (ccl-startup-census::function-observation afunc)
                      "flow" (flow-graph afunc))))
    (push (cons guard afunc) *guards*)
    (push record *captures*)
    ;; FCOMP-NAMED-FUNCTION's U1 contract says this result is for FASL only,
    ;; never to be funcalled. Distinct refusal functions preserve identities.
    ;; The file compiler's compile-time evaluator explicitly uses HOST instead.
    (setf (ccl::afunc-lfun afunc) guard)
    (when (equal *mode* "execute-guard") (funcall guard))
    afunc))

(defun with-observers (thunk)
  (let* ((ccl::*warn-if-redefine-kernel* nil)
         (old-form (fdefinition 'ccl::fcomp-form))
         (old-read (fdefinition 'ccl::fcomp-read-loop))
         (old-hook *macroexpand-hook*)
         (old-eval (fdefinition 'ccl::%compile-time-eval))
         (old-dump (fdefinition 'ccl::fasl-scan-forms-and-dump-file))
         (old-p2 (ccl::backend-p2-compile *sink-backend*))
         (*owner* ccl:*current-process*) (*active* t))
    (unwind-protect
      (progn
        (setf (ccl::backend-p2-compile *sink-backend*)
          (lambda (afunc &rest args)
            (if (and *active* (not (eq *sink-backend* ccl::*host-backend*)))
              (apply #'capture-pass2 afunc args)
              ;; Native collection is observation only: forward file functions
              ;; AND compiler helpers through the untouched native pass 2.
              ;; Their actual function identities can then join FCOMP outputs.
              (let ((record (let ((*gensym-counter* *gensym-counter*))
                              (obj "source" (source-location)
                                   "owner_id" (if (typep ccl::*nx-current-function* 'ccl::afunc)
                                                  (ident ccl::*nx-current-function*) :null)
                                   "role" (if (eq ccl::*load-time-eval-token* ccl::cfasl-load-time-eval-sym)
                                              "file-function" "compiler-helper")
                                   "function" (ccl-startup-census::function-observation afunc)
                                   "flow" (flow-graph afunc)))))
                (multiple-value-prog1 (apply old-p2 afunc args)
                  (nconc record (list "native_function_id" (ident (ccl::afunc-lfun afunc))))
                  (nconc record (list "emissions" (native-emissions afunc)))
                  (push record *native-compilations*))))))
        (setf (fdefinition 'ccl::fasl-scan-forms-and-dump-file)
              (lambda (&rest args)
                (declare (ignore args)) (error "CENSUS-FASL-PUBLICATION-FORBIDDEN")))
        (setf (fdefinition 'ccl::fcomp-read-loop)
          (lambda (filename orig-file orig-offset env mode)
            (unless (eq *owner* ccl:*current-process*) (error "CENSUS-OBSERVER-THREAD"))
            (let ((record (obj "filename" (namestring (pathname filename))
                               "mode" (label mode) "completed" :false)))
              (push record *read-inputs*)
              (multiple-value-prog1 (funcall old-read filename orig-file orig-offset env mode)
                (setf (field record "completed") :true)))))
        (setf (fdefinition 'ccl::fcomp-form)
          (lambda (form env processing-mode)
            (unless (eq *owner* ccl:*current-process*) (error "CENSUS-OBSERVER-THREAD"))
            (let* ((sequence (incf *next-form*)) (*form-stack* (cons sequence *form-stack*))
                   (record (obj "sequence" sequence "parent" (or (second *form-stack*) :null)
                                "source" (source-location)
                                "operator" (if (consp form) (label (car form)) :null)
                                "name" (if (and (consp form) (consp (cdr form))) (label (second form)) :null)
                                "mode" (label processing-mode) "completed" :false)))
              (push record *forms*)
              (flet ((forward ()
                       (multiple-value-prog1 (funcall old-form form env processing-mode)
                         (setf (field record "completed") :true))))
                (if (and (equal *mode* "continue") (null (cdr *form-stack*)))
                  (handler-case (forward)
                    (error (e)
                      (let ((gap (obj "form" sequence "source" (source-location)
                                      "type" (label (type-of e)) "message" (princ-to-string e))))
                        ;; Later reads may be useful observations, but their
                        ;; compile-time environment depends on this failed form.
                        (push gap *gaps*) nil)))
                  (forward))))))
        (setf (fdefinition 'ccl::%compile-time-eval)
          (lambda (form env)
            (unless (eq *owner* ccl:*current-process*) (error "CENSUS-OBSERVER-THREAD"))
            (let ((record (obj "source" (source-location) "form_stack" (reverse *form-stack*)
                               "operator" (if (consp form) (label (car form)) :null)
                               "completed" :false)))
              (push record *host-effects*)
              ;; U1 executes this form on HOST. Do not feed that host compiler
              ;; source expanders whose layout constants were read for Wasm.
              (let ((*macroexpand-hook* old-hook) (*active* nil))
                (multiple-value-prog1 (funcall old-eval form env)
                  (setf (field record "completed") :true))))))
        (funcall thunk))
      (setf (fdefinition 'ccl::fcomp-form) old-form
            (fdefinition 'ccl::fcomp-read-loop) old-read
            (fdefinition 'ccl::%compile-time-eval) old-eval
            (fdefinition 'ccl::fasl-scan-forms-and-dump-file) old-dump
            (ccl::backend-p2-compile *sink-backend*) old-p2))))

(defun with-sink-target (thunk)
  (if (eq *sink-backend* ccl-census-stub::*backend*)
    (ccl-census-descriptions::with-descriptions
      (lambda () (with-data-layout (lambda () (with-observers
        (lambda () (ccl-census-stub::with-target-state thunk)))))))
    (let ((ccl::*target-backend* ccl::*host-backend*)
          (ccl::*fasl-target* (ccl::backend-name ccl::*host-backend*))
          (*features* (ccl::setup-target-features ccl::*host-backend* *features*)))
      (ccl::with-cross-compilation-target ((ccl::backend-name ccl::*host-backend*))
        (with-observers thunk)))))

(defun prepare-expanders ()
  ;; Reuse the reviewed private routing and target-sensitive corrections.
  ;; Subsequent source-defined macros remain separately observed dependencies.
  (ccl-source-expanders::prepare)
  (flet ((source (path name) (ccl-target-helpers::read-form path name)))
    (let* ((helper (source "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
           (range (source "compiler/nx0.lisp" "defun nx1-target-fixnump"))
           (eql-form (source "compiler/optimizers.lisp" "define-compiler-macro eql"))
           (typep-form (source "compiler/nx0.lisp" "defun nx-form-typep"))
           (form-type (source "compiler/nx0.lisp" "defun nx-form-type"))
           (target-type (source "compiler/nx-basic.lisp" "defun nx-target-type"))
           (lookup (source "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
           (stream (source "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
           (vector (source "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
           (macro (source "compiler/optimizers.lisp" "define-compiler-macro typep"))
           (optimizer (source "compiler/optimizers.lisp" "defun optimize-typep")))
      (ccl-source-expanders::with-compiler-observation
        (lambda ()
          (setf (third (ccl-target-helpers::compiler-entry 'eql))
                (ccl-target-types::build helper range eql-form typep-form form-type target-type "normal")
                (third (ccl-target-helpers::compiler-entry 'ccl::basic-stream-p))
                (ccl-target-helpers::build-stream lookup stream)
                (third (ccl-target-helpers::compiler-entry 'vectorp))
                (ccl-target-helpers::build-stream lookup vector)
                (third (ccl-target-helpers::compiler-entry 'typep))
                (ccl-target-aliases::build macro optimizer target-type)
                (third (find-if (lambda (r) (and (eq (first r) 'setf) (equal (second r) "macro")))
                               ccl-source-expanders::*registry*)) (ccl-target-setf::build))
          (let ((dispatcher (ccl-target-dispatch::build)))
            (dolist (r ccl-source-expanders::*registry*)
              (when (equal (second r) "architecture-dispatch") (setf (third r) dispatcher)))))))))

(defun compile-input (path)
  ;; Bind the front-end state from U1 %COMPILE-FILE, stopping before FASL scan.
  (let* ((ccl::*fasl-deferred-warnings* nil) (ccl::*fasl-save-local-symbols* nil)
         (ccl::*save-source-locations* t) (ccl::*fasl-save-doc-strings* nil)
         (ccl::*fasl-save-definitions* nil) (ccl::*fasl-break-on-program-errors* t)
         (ccl::*fcomp-warnings-header* nil) (*compile-file-pathname* path)
         (*compile-file-truename* (truename path)) (*package* *package*) (*readtable* (copy-readtable))
         (*compile-print* nil) (*compile-verbose* nil)
         (ccl::*fasl-backend* ccl::*target-backend*)
         (ccl::*fasl-target-big-endian* nil)
         (ccl::*fasl-compile-time-env* (ccl::new-lexical-environment (ccl::new-definition-environment)))
         (ccl::*fcomp-external-format* :utf-8) (ccl::*fasl-setf-name-alias-alist* nil)
         (ccl::*outstanding-deferred-warnings* (ccl::%defer-warnings nil))
         (defenv (ccl::new-definition-environment)) (env (ccl::new-lexical-environment defenv)))
    (rplacd (ccl::defenv.type defenv) ccl::*outstanding-deferred-warnings*)
    (setf (ccl::defenv.defined defenv) (ccl::deferred-warnings.defs ccl::*outstanding-deferred-warnings*))
    (ccl::fcomp-file (namestring path) (namestring path) nil env)))

(defun run ()
  (let* ((*captures* nil) (*guards* nil) (*forms* nil) (*next-form* 0) (*host-effects* nil) (*macro-events* nil) (*gaps* nil)
         (*native-compilations* nil)
         (*read-inputs* nil)
         (path (pathname (ccl:getenv "CCL_CLOSURE_SOURCE")))
         (*mode* (or (ccl:getenv "CCL_CLOSURE_MODE") "normal"))
         (*sink-backend* (if (equal *mode* "native") ccl::*host-backend* ccl-census-stub::*backend*))
         (status "INCOMPLETE") (problem :null) (outputs nil) (context nil)
         (native-checks nil)
         (before (ccl-source-traversal::state))
         (names '(ccl::fcomp-form ccl::fcomp-read-loop ccl::%compile-time-eval ccl::fasl-scan-forms-and-dump-file))
         (definitions (mapcar #'fdefinition names))
         (old-pass2 (ccl::backend-p2-compile *sink-backend*)))
    (unless (equal *mode* "native") (prepare-expanders))
    (handler-case
      (with-sink-target
        (lambda ()
          (setf context (ccl-source-traversal::context))
          (when (equal *mode* "dump") (ccl::fasl-scan-forms-and-dump-file nil "forbidden"))
          (setf outputs (with-routing (lambda () (compile-input path)))
                status (if *gaps* "INCOMPLETE" "CAPTURED"))))
      (error (e) (setf problem (obj "type" (label (type-of e)) "message" (princ-to-string e)))))
    (unless (and (equal before (ccl-source-traversal::state))
                 (every #'eq definitions (mapcar #'fdefinition names))
                 (eq old-pass2 (ccl::backend-p2-compile *sink-backend*)))
      (error "CENSUS-OBSERVER-NOT-RESTORED"))
    (when (and (equal *mode* "native") (equal status "CAPTURED")
               (equal (ccl:getenv "CCL_CLOSURE_CORPUS") "yes"))
      (dolist (case '(("CENSUS-FIRST" 41 42) ("CENSUS-LOCAL-MACRO" 41 42) ("CENSUS-EXPANDED" 20 40)))
        (let* ((name (find-symbol (first case) "CL-USER"))
               ;; U1 xdump/faslenv.lisp: $fasl-defun = 35. Boot unbinds
               ;; this compiler constant; do not borrow an image value for it.
               (row (find-if (lambda (r) (and (= (car r) 35)
                                              (functionp (second r))
                                              (eq (ccl:function-name (second r)) name))) outputs))
               (value (if row (funcall (second row) (second case)) (error "NATIVE-CORPUS-OUTPUT-MISSING"))))
          (unless (eql value (third case)) (error "NATIVE-CORPUS-RESULT"))
          (push (obj "name" (label name) "input" (second case) "result" value) native-checks))))
    (with-open-file (out (ccl:getenv "CCL_CLOSURE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
      (ccl-startup-census::json
        (obj "version" 1 "status" status "problem" problem "context" context
             "forms" (reverse *forms*) "captures" (reverse *captures*)
             "gaps" (reverse *gaps*) "eof_reached" (if (or (equal status "CAPTURED") (and *gaps* (eq problem :null))) :true :false)
             "compile_time_effects" (reverse *host-effects*)
             "native_compilations" (reverse *native-compilations*)
             "read_inputs" (reverse *read-inputs*)
             "native_checks" (reverse native-checks)
             "layout_source" (reverse *layout-facts*)
             "layout_constants" (mapcar (lambda (r) (obj "name" (car r) "value" (cdr r))) (reverse *layout-values*))
             "layout_fields" (reverse *layout-fields*)
             "layout_macros" (reverse *layout-macros*)
             "output_opcodes" (mapcar #'car outputs)
             "output_graph" (if outputs (flow-graph outputs) :null)
             "expansions" (sort (copy-list *macro-events*) #'< :key (lambda (r) (field r "sequence")))
             "observer_restored" :true "wasm_code_emitted" :false
             "fasl_written" :false "macro_environment_qualified" :false) out)
      (terpri out))
    (format t "CENSUS-FILE ~a ~d captures ~d native compilations ~d forms~%"
            status (length *captures*) (length *native-compilations*) (length *forms*))))
