(in-package :ccl-source-closure)
(defun layout-probes ()
  (let ((rows nil))
    (ccl-census-descriptions::with-descriptions
      (lambda () (with-data-layout
        (lambda ()
          (let ((table (arch::target-target-macros
                         (ccl::backend-target-arch ccl-census-stub::*backend*))))
            (dolist (form '((ccl::%make-sfloat) (ccl::%make-dfloat) (ccl::%numerator :x)
                            (ccl::%denominator :x) (ccl::immediate-p-macro :x)
                            (ccl::hashed-by-identity :x) (ccl::symptr->symvector :x)
                            (ccl::symvector->symptr :x)))
              (let ((names (make-hash-table :test #'eq)))
                (labels ((convert (value)
                           (cond ((null value) :null) ((integerp value) value)
                                 ((symbolp value)
                                  (if (symbol-package value) (label value)
                                    (or (gethash value names)
                                        (setf (gethash value names) (format nil "LOCAL-~d" (hash-table-count names))))))
                                 ((listp value) (mapcar #'convert value))
                                 (t (error "LAYOUT-PROBE-OBJECT")))))
                  (push (obj "form" (convert form)
                             "expansion" (convert (funcall (gethash (car form) table) form nil))) rows)))))))))
    (with-open-file (out (ccl:getenv "CCL_CLOSURE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
      (ccl-startup-census::json (nreverse rows) out) (terpri out))))
