(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let ((out (ccl:getenv "POOL_OUTPUT")) (modules nil))
 (dolist (row '(("host_image" (lambda (symbol value done) (multiple-value-prog1 (set symbol value) (rplaca done 301))))
               ("host_arguments" (lambda (symbol value done) (multiple-value-prog1 (set symbol value) (rplaca done 302))))
               ("host_readback" (lambda (image arguments done) (multiple-value-prog1 (values (symbol-value image) (symbol-value arguments)) (rplaca done 303))))))
  (let ((m (compile-call-form (second row) (first row) nil)))
   (assert (null (getf m :children))) (push m modules)
   (with-open-file(s(concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error)(write-string(getf m :wat)s))))
 (setq modules(nreverse modules))
 (with-open-file(s(concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[")(loop for m in modules for i from 0 do(unless(zerop i)(format s ","))(format s "{\"name\":~s}"(getf m :name)))(format s "]"))
 (with-open-file(s(concatenate 'string out "pools.json") :direction :output :if-exists :error)(write-pool-graph s(mapcar(lambda(m)(getf m :pool))modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
