;;; Observation only, in a disposable native U1 process. No saved image/FASL.
(defpackage :ccl-registry-flow (:use :cl)
  (:import-from :ccl-startup-census #:object #:json)
  (:import-from :ccl-dispatch-registry #:oid #:fn #:field #:snapshot #:name-data #:name-key))
(in-package :ccl-registry-flow)
(defvar *events* nil)
(defvar *serial* 0)
(defvar *parents* nil)
(defvar *phase* "setup")
(defvar *owner* nil)
(defvar *touched* (make-hash-table :test #'eq))
(defvar *mode* "observed")
(declaim (ftype (function (t) *) native-code flow-graph))

(defun live-state (gf)
  ;; Allocation selects an initial dcode before the standard GF slots are bound.
  (let ((unbound (loop for slot in (list ccl::sgf.name ccl::sgf.methods ccl::sgf.method-combination)
                       when (eq (ccl::%svref (ccl::gf.slots gf) slot) (ccl::%slot-unbound-marker))
                       collect slot)))
    (if unbound
      (object "status" "UNINITIALIZED" "gf" (fn gf) "unbound_slots" unbound
              "dcode" (fn (ccl::%gf-dcode gf)) "methods" :null)
      (snapshot gf))))

(defun record (kind &rest fields)
  (unless (eq *owner* ccl:*current-process*) (error "REGISTRY-FLOW-THREAD"))
  (let ((row (apply #'object "sequence" (incf *serial*) "kind" kind
                    "phase" *phase* "parent" (or (car *parents*) :null) fields)))
    (push row *events*) row))

(defun method-state (m)
  (object "id" (oid m) "owner" (if (ccl::%method.gf m) (fn (ccl::%method.gf m)) :null)
          "function" (fn (ccl::%method.function m))
          "qualifiers" (mapcar #'name-data (ccl::%method.qualifiers m))
          "specializers" (mapcar #'oid (ccl::%method.specializers m))))

(defun mutation (kind gf method target thunk)
  (unless (gethash gf *touched*) (setf (gethash gf *touched*) (live-state gf)))
  (let* ((entry (record (concatenate 'string kind "-enter")
                        "state" (live-state gf)
                        "method" (if method (method-state method) :null)
                        "method_code" (if method (native-code (ccl::closure-function (ccl::%method.function method))) :null)
                        "target" (if target (fn target) :null)))
         (*parents* (cons (field entry "sequence") *parents*)) (completed nil))
    (unwind-protect
        (multiple-value-prog1 (funcall thunk) (setf completed t))
      (record (concatenate 'string kind "-leave") "entry" (field entry "sequence")
              "completed" (if completed :true :false) "state" (live-state gf)
              "method" (if method (method-state method) :null)))))

(defun emissions (root)
  (let ((pending (list root)) (rows nil))
    (loop while pending for a = (pop pending) do
      (let ((f (ccl::afunc-lfun a)))
        (push (object "afunc" (oid a) "function" (if (functionp f) (fn f) :null)
                      "code" (if (functionp f) (native-code f) :null)) rows))
      (setf pending (append (ccl::afunc-inner-functions a) pending)))
    (nreverse rows)))

(defun with-observation (thunk)
  (let* ((backend ccl::*host-backend*) (p2 (ccl::backend-p2-compile backend))
         (names '(ccl::%add-standard-method-to-standard-gf
                  ccl::%remove-standard-method-from-containing-gf ccl::%set-gf-dcode))
         (originals (mapcar #'fdefinition names))
         (ccl::*warn-if-redefine-kernel* nil) (*owner* ccl:*current-process*))
    (unwind-protect
        (progn
          (setf (ccl::backend-p2-compile backend)
            (lambda (afunc &rest args)
              (unless (eq ccl::*target-backend* backend) (error "REGISTRY-FLOW-BACKEND"))
              (let* ((entry (let ((*gensym-counter* *gensym-counter*))
                              (record "compile-enter" "flow" (flow-graph afunc))))
                     (*parents* (cons (field entry "sequence") *parents*))
                     (completed nil))
                (unwind-protect
                    (multiple-value-prog1 (apply p2 afunc args) (setf completed t))
                  (record "compile-leave" "entry" (field entry "sequence")
                          "completed" (if completed :true :false)
                          "emissions" (emissions afunc))))))
          (setf (fdefinition (first names))
            (lambda (gf method)
              (if (equal *mode* "omit-add") (funcall (first originals) gf method)
                (mutation "add" gf method nil (lambda () (funcall (first originals) gf method))))))
          (setf (fdefinition (second names))
            (lambda (method)
              (mutation "remove" (ccl::%method.gf method) method nil
                        (lambda () (funcall (second originals) method)))))
          (setf (fdefinition (third names))
            (lambda (gf dcode)
              (mutation "dcode" gf nil dcode (lambda () (funcall (third originals) gf dcode)))))
          (funcall thunk))
      (setf (ccl::backend-p2-compile backend) p2)
      (loop for name in names for old in originals do (setf (fdefinition name) old)))
    (unless (and (eq p2 (ccl::backend-p2-compile backend))
                 (every #'eq originals (mapcar #'fdefinition names)))
      (error "REGISTRY-FLOW-NOT-RESTORED"))))

(defun semantic-state (gf)
  ;; Taken after restoring the observer, for a no-observer reference comparison.
  ;; Names/signatures select comparison rows only; they never create IR joins.
  (object "name" (name-data (ccl:function-name gf))
          "methods" (mapcar (lambda (m)
             (object "qualifiers" (mapcar #'name-data (ccl::%method.qualifiers m))
                     "specializers" (mapcar (lambda (s)
                       (if (typep s 'ccl::eql-specializer)
                         (let ((v (ccl:eql-specializer-object s)))
                           (object "eql" (if (integerp v) v (name-data v))))
                         (name-data (class-name s)))) (ccl::%method.specializers m))
                     "code" (native-code (ccl::closure-function (ccl::%method.function m)))))
                           (ccl::%gf-methods gf))))

(defun semantic-inventory ()
  (let ((rows nil))
    (dolist (gf (ccl::population-data ccl::%all-gfs%))
      (unless (eq (ccl::%svref (ccl::gf.slots gf) ccl::sgf.methods) (ccl::%slot-unbound-marker))
        (push (semantic-state gf) rows)))
    (sort rows #'string< :key (lambda (r) (with-output-to-string (s) (json (field r "name") s))))))

(defun corpus (path)
  (let ((*phase* "describe") (*gensym-counter* 100000)) (load path :verbose nil :print nil))
  (let ((*phase* "probe") (*gensym-counter* 200000))
    (eval '(defgeneric route (x)))
    (eval '(defmethod route ((x t)) (declare (ignore x)) (values 10 11)))
    (eval '(defmethod route ((x integer)) (declare (ignore x)) (values 20 21)))
    (eval '(defmethod route ((x integer)) (declare (ignore x)) (values 30 31)))
    (let ((gf (fdefinition 'route)))
      (flet ((call (name)
               (let ((values (multiple-value-list (funcall gf 3))))
                 (unless (equal values '(30 31)) (error "REGISTRY-FLOW-CALL ~a" name))
                 (when *owner* (record "call" "name" name "gf" (fn gf) "values" values)))))
        (call "replacement") (call "warm-replacement"))
      (remove-method gf (find-method gf nil (list (find-class 'integer))))
      (let ((values (multiple-value-list (funcall gf 3))))
        (unless (equal values '(10 11)) (error "REGISTRY-FLOW-REMOVAL"))
        (when *owner* (record "call" "name" "removed-specialization" "gf" (fn gf) "values" values))))))

(defun exceptional-restoration ()
  (let* ((backend ccl::*host-backend*) (old-p2 (ccl::backend-p2-compile backend))
         (names '(ccl::%add-standard-method-to-standard-gf
                  ccl::%remove-standard-method-from-containing-gf ccl::%set-gf-dcode))
         (old (mapcar #'fdefinition names)))
    (unless (eq :escaped (catch 'restoration
                          (with-observation (lambda () (throw 'restoration :escaped)))))
      (error "REGISTRY-FLOW-ESCAPE"))
    (unless (and (eq old-p2 (ccl::backend-p2-compile backend))
                 (every #'eq old (mapcar #'fdefinition names)))
      (error "REGISTRY-FLOW-EXCEPTION-RESTORATION"))
    :true))

(defun export-state (path unit mode)
  (let* ((*mode* mode) (ccl::*warn-if-redefine-kernel* nil) (before (semantic-inventory)))
    (if (equal mode "reference") (corpus unit) (with-observation (lambda () (corpus unit))))
    (let* ((after (semantic-inventory))
           (changed (remove-if (lambda (r) (member r before :test #'equal)) after))
           (initial nil) (final nil))
      (maphash (lambda (gf old) (push old initial) (push (live-state gf) final)) *touched*)
      (flet ((ordered (rows) (sort rows #'< :key (lambda (r) (field r "gf")))))
        (with-open-file (s path :direction :output :if-exists :error :external-format :utf-8)
          (json (object "version" 1 "namespace" "same-execution-native-registry-flow"
                        "mode" mode "events" (nreverse *events*)
                        "initial" (ordered initial) "final" (ordered final)
                        "functions" (ccl-dispatch-registry::function-records)
                        "initial_method_codes" before "changed_methods" changed "observer_restored" :true
                        "exceptional_restoration" (exceptional-restoration)
                        "old_build_identity_join" :false "exhaustive_callee_bound" :false) s)
          (terpri s))))
  (format t "REGISTRY-FLOW-PASS events=~d~%" *serial*)))
