(in-package :ccl)
;; Untouched native consumers, not copies of the proposed accessor bodies.
(dolist (type '(:list :alist))
 (let* ((a (cons 17 23)) (b (cons 31 37))
        (input (if (eq type :list) (list a b) (list (cons a b))))
        (p (make-population :type type :initial-contents input))
        (contents (population-contents p)))
  (assert (eq (population-type p) type))
  (assert (not (eq contents input)))
  (if (eq type :list)
   (progn (assert (eq (car contents) a)) (assert (eq (cadr contents) b)))
   (progn (assert (not (eq (car contents) (car input))))
          (assert (eq (caar contents) a)) (assert (eq (cdar contents) b))))
  (dolist (replacement (list nil (list a) (cons a b)))
   (assert (equal (multiple-value-list (setf (population-contents p) replacement)) (list replacement)))
   (assert (eq (population-contents p) replacement)))
  (let ((cycle (cons a nil)))
   (setf (cdr cycle) cycle)
   (assert (eq (setf (population-contents p) cycle) cycle))
   (assert (eq (population-contents p) cycle)))
  (let ((before (population-contents p)) (caught nil))
   (handler-case (setf (population-contents p) 7) (type-error () (setf caught t)))
   (assert caught) (assert (eq (population-contents p) before)))
  (format t "POPULATION|~(~a~)|~d|copy-spine|member-identity|nil|proper|dotted|cycle|type-refusal~%" type (population.type p))))
(quit)
