(module
  (type $B (func (param i32 i32) (result i32 i32)))
  (type $tail (func (param i32 i32 i32) (result i32 i32)))
  (import "loader" "install" (func $install (param i32)))
  (import "loader" "slot" (global $slot i32))
  (import "loader" "table" (table $entries 0 funcref))
  (import "loader" "tail_table" (table $tails 0 funcref))
  (func (export "entry") (type $B) (param $self i32) (param $count i32) (result i32 i32)
    (call $install (global.get $slot))
    (return_call_indirect $entries (type $B) (local.get $self) (local.get $count) (global.get $slot)))
  (func (export "tail_entry") (type $tail) (param $self i32) (param $count i32) (param $context i32) (result i32 i32)
    (call $install (global.get $slot))
    (return_call_indirect $tails (type $tail) (local.get $self) (local.get $count) (local.get $context) (global.get $slot)))
)
