;;; The same ordinary source is compiled for native CCL and wasm32.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0)))
  (proclaim '(notinline fx-note fx-identity fx-collect fx-add fx-generic)))

(defun fx-add (x y) (declare (fixnum x y)) (+ x y))
(defun fx-sub (x y) (declare (fixnum x y)) (- x y))
(defun fx-mul (x y) (declare (fixnum x y)) (* x y))
(defun fx-fit (x y) (declare (fixnum x y)) (the fixnum (+ x y)))
(defun fx-less (x y) (declare (fixnum x y)) (< x y))
(defun fx-identity (x) (declare (fixnum x)) x)
(defun fx-generic (x y) (+ x y))
(defun fx-generic-sub (x y) (- x y))
(defun fx-generic-mul (x y) (* x y))
(defun fx-generic-less (x y) (< x y))
(defun fx-generic-eql (x y) (eql x y))
(defun fx-bits (x y)
  (declare (fixnum x y))
  (values (logand x y) (logior x y) (logxor x y) (lognot x)))
(defun fx-loop (n x)
  (declare (fixnum n x))
  (let ((sum 0))
    (declare (fixnum sum))
    (dotimes (i n sum) (setq sum (the fixnum (+ sum x))))))
(defun fx-last-index (n)
  (declare (fixnum n))
  (dotimes (i n i)))
(defun fx-assign (x y)
  (declare (fixnum x y))
  (values (setq x (the fixnum (+ x y))) x (fx-identity x)))
(defun fx-bindings (x y)
  (declare (fixnum x y))
  (let ((x y) (y x))
    (declare (fixnum x y))
    (let* ((a (the fixnum (+ x y))) (b (the fixnum (- a x))))
      (declare (fixnum a b))
      (multiple-value-bind (p q) (values a b)
        (declare (fixnum p q))
        (if (> p q) (setq p (the fixnum (- p q)))
          (setq p (the fixnum (+ p q))))
        (values p q)))))
(defun fx-captured (x)
  (declare (fixnum x))
  (let ((step (lambda () (incf x))))
    (funcall step) (funcall step) x))
(defvar *fx-special* 0)
(defun fx-special (x)
  (declare (fixnum x))
  (let ((*fx-special* x))
    (declare (fixnum *fx-special*))
    (incf *fx-special*) *fx-special*))
(defvar *fx-order* nil)
(defun fx-note (name value) (push name *fx-order*) value)
(defun fx-order (x y)
  (declare (fixnum x y))
  (setq *fx-order* nil)
  (+ (the fixnum (fx-note :left x)) (the fixnum (fx-note :right y))))
(defun fx-mutation-order (x)
  (declare (fixnum x))
  (+ x (setq x (the fixnum (+ x 1)))))
(defun fx-collect (value)
  #+wasm32-target (write-line "EB-GC")
  #-wasm32-target (gc)
  value)
(defun fx-moving (x pair vector)
  (declare (fixnum x))
  (dotimes (i 4)
    ;; The left arithmetic operand survives collection during the right one;
    ;; unrelated references must still be rooted and reloaded by their owner.
    (setq x (the fixnum (+ x (the fixnum (fx-collect 3)))))
    (assert (eq pair (svref vector 0)))
    (assert (eq (svref vector 0) (svref vector 1)))
    (assert (equal pair '(17 . 23))))
  (values x pair))
(defun fx-moving-generic (x)
  ;; A boxed, undeclared left operand needs its root during the later call.
  (+ x (fx-collect 3)))
(defun fx-control (n)
  (declare (fixnum n))
  (let ((sum 0) (cleanups 0))
    (declare (fixnum sum cleanups))
    (block done
      (dotimes (i n)
        (unwind-protect
            (progn (when (= i 3) (return-from done))
                   (incf sum i))
          (incf cleanups))))
    (values sum cleanups)))
(defun fx-safe (x y)
  (declare (optimize (safety 3)) (fixnum x y))
  (+ x y))
(defun fx-safe-result (x y)
  (declare (optimize (safety 3)) (fixnum x y))
  (the (integer -100 100) (+ x y)))
(defun fx-error-order (x y)
  (declare (optimize (safety 3)))
  (setq *fx-order* nil)
  (+ (fx-note :left x) (fx-note :right y)))

(defun fx-row (name value)
  ;; READY's printer does not yet format floats. Compare their exact bits.
  (when (typep value 'double-float)
    (multiple-value-bind (hi lo) (double-float-bits value)
      (setq value (list :double (logand #xffffffff hi) (logand #xffffffff lo)))))
  (format t "FX-ROW ~s ~s~%" name value))
;;; Explicit wasm32 boundaries also fit the native reference's fixnums.
;;; Compare numeric answers, since the targets have different fixnum widths.
(let ((inputs '((0 0) (1 -1) (-7 3) (536870911 1) (-536870912 -1)
                (536870911 536870911) (-536870912 -536870912)
                (-536870912 1) (536870911 -1) (32768 65536))))
  (dolist (name '(fx-add fx-sub fx-mul fx-less fx-generic fx-generic-sub
                 fx-generic-mul fx-generic-less fx-generic-eql))
    (dolist (args inputs) (fx-row name (apply name args)))))
(dolist (args '((0 0) (7 3) (-7 3) (536870911 -536870912)))
  (fx-row 'bits (multiple-value-list (apply #'fx-bits args))))
(fx-row 'fit (fx-fit -7 3))
(dolist (n '(-7 0 1 2 9 1000))
  (fx-row 'loop (fx-loop n 3))
  (fx-row 'last-index (fx-last-index n)))
(fx-row 'assign (multiple-value-list (fx-assign 7 3)))
(fx-row 'bindings (multiple-value-list (fx-bindings 7 3)))
(fx-row 'captured (fx-captured 7))
(fx-row 'special (fx-special 7))
(fx-row 'order (fx-order 7 3))
(assert (equal *fx-order* '(:right :left)))
(fx-row 'mutation-order (fx-mutation-order 7))
(fx-row 'control (multiple-value-list (fx-control 10)))
(fx-row 'safe (fx-safe 536870911 1))
(fx-row 'safe-result (fx-safe-result 7 3))
(fx-row 'generic-float (fx-generic 1.5d0 0.5d0))
(fx-row 'generic-bignum (fx-generic 1152921504606846976 3))
(fx-row 'generic-less (fx-generic-less 1.5d0 2.5d0))
(fx-row 'eql-float (fx-generic-eql 1.5d0 1.5d0))
(fx-row 'eql-symbol (fx-generic-eql :same :same))
(let* ((pair (cons 17 23)) (vector (vector pair pair)))
  (multiple-value-bind (value returned) (fx-moving 7 pair vector)
    (assert (eq pair returned))
    (fx-row 'moving value)))
(fx-row 'moving-float (fx-moving-generic (fx-generic 1.5d0 0.5d0)))
(fx-row 'moving-bignum (fx-moving-generic (fx-generic 1152921504606846976 3)))
(assert (handler-case (progn (fx-safe :bad 1) nil) (type-error () t)))
(assert (handler-case (progn (fx-safe-result 99 99) nil) (type-error () t)))
(let ((pair (cons 17 23)))
  (assert (handler-case (progn (fx-error-order pair 1) nil)
            (type-error (condition) (eq (type-error-datum condition) pair)))))
(assert (equal *fx-order* '(:right :left)))
;;; The checked register boundary also refuses an invalid low-safety
;;; declaration; native behavior for that invalid declaration is not asserted.
#+wasm32-target
(assert (handler-case (progn (funcall 'fx-identity :bad) nil) (type-error () t)))
(fx-row 'recovery (fx-add 7 3))
(format t "FX-PASS~%")
