(in-package :cl-user)
(declaim (optimize (debug 3) (speed 0) (safety 3)))
(defun dependency-self (n)
  (declare (optimize (debug 0) (speed 3) (safety 1)))
  (if (zerop n) 0 (1+ (dependency-self (1- n)))))
(defun dependency-locals (x)
  (list (flet ((same (y) (+ y 11))) (declare (notinline same)) (same x))
        (flet ((same (y) (+ y 22))) (declare (notinline same)) (same x))))
(defun dependency-indirect (f x) (funcall f x))
(defun dependency-capture (x) (lambda (y) (+ x y)))
(defun dependency-mutual (n)
  (labels ((left (x) (if (zerop x) :left (right (1- x))))
           (right (x) (if (zerop x) :right (left (1- x)))))
    (declare (notinline left right))
    (left n)))
