(in-package :wasm32-compiler)

;;; Admission precedes publishing any image root. These are the native class
;;; and method fields, not a parallel catalogue maintained by the owner.
(defun ready-image-status (image)
  (dolist (entry (svref image 11))
    (let ((class (cdr entry)))
      (unless (ccl::%standard-instance-p class)
        (return-from ready-image-status :class-shape))
      (unless (and (consp (ccl::%class.cpl class))
                   (eq (car (ccl::%class.cpl class)) class))
        (return-from ready-image-status :class-cpl))
      (let ((wrapper (ccl::%class.own-wrapper class)))
        (unless (and wrapper (eq (ccl::%wrapper-class wrapper) class))
          (return-from ready-image-status :class-wrapper))
        (when (eql (ccl::%wrapper-hash-index wrapper) 0)
          (return-from ready-image-status :obsolete-wrapper)))))
  (dolist (gf (cons (symbol-function 'ccl::eql-specializer-object)
                   (append (svref image 8)
                           (loop for entry in (first (svref image 12)) collect (car entry)))))
    (unless (eq (ccl::%gf-method-combination gf)
                ccl::*standard-method-combination*)
      (return-from ready-image-status :method-combination))
    (dolist (method (ccl::%gf-methods gf))
      (unless (functionp (ccl::%method-function method))
        (return-from ready-image-status :method-function))))
  t)

;;; Directed admission checks restore the source image after every mutation.
;;; This entry is a qualification caller, not part of the startup worklist.
(defun ready-image-refusals (image)
  (let* ((entry (car (svref image 11)))
         (class (cdr entry))
         (wrapper (ccl::%class.own-wrapper class))
         (gf (car (svref image 8)))
         (method (car (ccl::%gf-methods gf))))
    (macrolet ((check (place value)
                 `(let ((old ,place))
                    (unwind-protect
                        (progn (setf ,place ,value) (ready-image-status image))
                      (setf ,place old)))))
      (list (check (cdr entry) nil)
            (check (ccl::%class.cpl class) nil)
            (check (ccl::%class.cpl class) (list nil))
            (check (ccl::%class.own-wrapper class) nil)
            (check (ccl::%wrapper-class wrapper) nil)
            (check (ccl::%wrapper-hash-index wrapper) 0)
            (check (ccl::sgf.method-combination gf) nil)
            (check (ccl::%method.function method) nil)
            (ready-image-status image)))))

;;; Exercise the public function cells, not the compiler's direct-call
;;; substitution. Those cells must use the admitted table implementation too.
(defun ready-table-bindings (image)
  (declare (ignore image))
  (let ((table (ccl::%wasm-make-class-table 4))
        (keys nil)
        (sum 0))
    (dotimes (i 20)
      (let ((key (cons i nil)))
        (push key keys)
        (funcall (symbol-function 'ccl::puthash) key table i))
      (when (zerop (logand i 3)) (core-collect)))
    (dolist (key keys)
      (multiple-value-bind (value found) (funcall (symbol-function 'gethash) key table)
        (unless found (error "A READY table binding lost a key."))
        (incf sum value)))
    (let ((removed (funcall (symbol-function 'remhash) (car keys) table)))
      (core-collect)
      (multiple-value-bind (value found)
          (funcall (symbol-function 'gethash) (car keys) table :absent)
        (funcall (symbol-function 'clrhash) table)
        (core-collect)
        (multiple-value-bind (empty present)
            (funcall (symbol-function 'gethash) (cadr keys) table :empty)
          (values sum removed value found empty present))))))

;;; Resource fallback returns a string; it does not print to a stream. Exercise
;;; the unchanged CCL path with no resource entries, including a negative code.
(defun ready-resource-strings (image)
  (declare (ignore image))
  (let ((ccl::*error-format-strings* nil))
    (values (ccl::%rsc-string 0)
            (ccl::%rsc-string 987654)
            (ccl::%rsc-string -37))))

(defun ready-string-contract (image)
  (declare (ignore image))
  (let ((function (symbol-function 'make-string))
        (trace nil))
    (list (funcall function 0 :initial-element #\x)
          (funcall function 1 :initial-element #\x)
          (funcall function 30 :initial-element #\x)
          (funcall function 33 :initial-element #\x)
          (funcall function
                   (progn (push :size trace) (core-collect) 3)
                   :element-type (progn (push :type trace) 'base-char)
                   :initial-element (progn (push :fill trace) (core-collect) #\z))
          (nreverse trace)
          (handler-case (funcall function 2 :initial-element 7)
            (type-error () :bad-character)))))

;;; This is the top-level radix-table initializer in l0-int.lisp. The input
;;; driver checks its body against that source form before compiling probes.
(defun ready-integer-print-tables (image)
  (declare (ignore image))
  (do* ((b (make-array 37 :initial-element nil))
        (f (make-array 37 :initial-element nil))
        (base 2 (1+ base)))
       ((= base 37) (setq ccl::*base-power* b ccl::*fixnum-power--1* f))
    (do ((power-1 -1 (1+ power-1))
         (new-divisor base (* new-divisor base))
         (divisor 1 new-divisor))
        ((not (ccl::fixnump new-divisor))
         (setf (aref b base) divisor)
         (setf (aref f base) power-1))))
  t)

(defun ready-integer-strings (image)
  (declare (ignore image))
  (let ((results nil))
    (dolist (integer '(0 1 -1 536870911 536870912 -536870912 -536870913
                      1152921504606846976 -1152921504606846976
                      #x51ad9826be1f03647905acfe123456789abcdef
                      #x-51ad9826be1f03647905acfe123456789abcdef))
      (dolist (radix '(2 8 10 16 36))
        (let ((string (ccl::%integer-to-string integer radix)))
          (core-collect)
          (push string results))))
    (nreverse results)))

(defun ready-list-callees (image)
  (declare (ignore image))
  (let* ((tail (list 'c 'd))
         (list (list* 'a 'b tail))
         (dotted (cons 'a (cons 'b 'end)))
         (sum 0)
         (visited nil))
    (let ((prefix (funcall (symbol-function 'ldiff) list tail))
          (dotted-copy (funcall (symbol-function 'ldiff) dotted 'not-a-tail))
          (numbers (list 1 2 3 4)))
      (core-collect)
      (let ((answer (funcall (symbol-function 'mapc) (lambda (x y)
                           (incf sum (+ x y))
                           (push x visited)
                           (core-collect))
                         numbers '(10 20 30))))
        (list prefix dotted-copy (eq answer numbers) sum
              (nreverse visited) (eq (cddr list) tail)
              (mapcar (lambda (x y) (core-collect) (+ x y)) numbers '(10 20 30))
              (maplist (lambda (tail) (core-collect) (length tail)) numbers)
              (eq numbers (mapl (lambda (tail) (core-collect) (car tail)) numbers))
              (mapcan (lambda (n) (core-collect) (list n (- n))) numbers)
              (mapcon (lambda (tail) (core-collect) (list (length tail))) numbers))))))

(defun ready-class-protocol (image)
  (declare (ignore image))
  (let* ((class (find-class 'cpl-derived))
         (gf (symbol-function 'make-instance))
         (answers nil)
         (original-class-dependents (ccl::%class.dependents class))
         (original-gf-dependents (ccl::sgf.dependents gf)))
    ;; Invoke projected generic functions through their installed cells.
    ;; The oracle uses the real native metaobjects, so restore their lists.
    (unwind-protect
        (progn
          (setf (ccl::%class.dependents class) nil
                (ccl::sgf.dependents gf) nil)
          (dolist (object (list class gf))
            (funcall (symbol-function 'ccl::add-dependent) object :first)
            (funcall (symbol-function 'ccl::add-dependent) object :second)
            (funcall (symbol-function 'ccl::add-dependent) object :first)
            (core-collect)
            (let ((seen nil))
              (funcall (symbol-function 'ccl::map-dependents) object
                (lambda (dependent) (core-collect) (push dependent seen)))
              (push (nreverse seen) answers))
            (funcall (symbol-function 'ccl::remove-dependent) object :second)
            (core-collect)
            (let ((seen nil))
              (funcall (symbol-function 'ccl::map-dependents) object
                (lambda (dependent) (push dependent seen)))
              (push (nreverse seen) answers)))
          (push (funcall (symbol-function 'class-name) class) answers)
          (push (eq (funcall (symbol-function 'ccl::class-own-wrapper) class) (ccl::%class.own-wrapper class)) answers)
          (push (mapcar (symbol-function 'class-name) (funcall (symbol-function 'ccl::class-direct-superclasses) class)) answers)
          (push (not (null (ccl::memq class (funcall (symbol-function 'ccl::class-direct-subclasses) (find-class 'cpl-diamond))))) answers)
          (push (mapcar (lambda (slot) (list (funcall (symbol-function 'ccl:slot-definition-name) slot)
                                            (funcall (symbol-function 'ccl::slot-definition-allocation) slot)))
                        (funcall (symbol-function 'ccl:class-slots) class)) answers)
          (push (funcall (symbol-function 'ccl::generic-function-name) gf) answers)
          ;; TYPEP must recognize both NX1 truth constants and still evaluate
          ;; its operand exactly once, including a collection.
          (let ((count 0))
            (push (list (typep (progn (incf count) (core-collect) gf) t)
                        (typep (progn (incf count) (core-collect) gf) nil)
                        count) answers))
          (let ((name (slot-value gf 'ccl::name)))
            (unwind-protect
                (progn
                  (setf (slot-value gf 'ccl::name) :ready-temporary)
                  (core-collect)
                  (push (list (slot-boundp gf 'ccl::name)
                              (funcall (symbol-function 'ccl::generic-function-name) gf))
                        answers))
              (setf (slot-value gf 'ccl::name) name)))
          (push (equal (funcall (symbol-function 'ccl::generic-function-methods) gf) (ccl::%gf-methods gf)) answers)
          (push (funcall (symbol-function 'ccl::generic-function-lambda-list) gf) answers)
          (push (mapcar (symbol-function 'class-name) (funcall (symbol-function 'ccl::compute-class-precedence-list) class)) answers)
          (push (mapcar (lambda (entry) (list (car entry) (funcall (third entry))))
                        (funcall (symbol-function 'ccl::compute-default-initargs) class)) answers)
          (let* ((count 19)
                 (closure (lambda () (incf count))))
            (core-collect)
            (push (list (funcall (symbol-function 'class-name) (class-of #'identity))
                        (funcall (symbol-function 'class-name) (class-of closure))
                        (funcall (symbol-function 'class-name) (class-of (ccl::%method-function (car (ccl::%gf-methods gf)))))
                        (funcall (symbol-function 'class-name) (class-of gf))
                        (funcall closure)) answers))
          (nreverse answers))
      (setf (ccl::%class.dependents class) original-class-dependents
            (ccl::sgf.dependents gf) original-gf-dependents))))

(defun ready-slot-errors (image)
  (declare (ignore image))
  (let ((object (make-condition 'cpl-derived)))
    (list
      (handler-case
          (funcall (symbol-function 'ccl::update-dependent)
                   (find-class 'cpl-derived) :dependent)
        (ccl::no-applicable-method-exists (condition)
          (let ((arguments (slot-value condition 'ccl::args)))
            (list (eq (slot-value condition 'ccl::gf)
                      (symbol-function 'ccl::update-dependent))
                  (eq (car arguments) (find-class 'cpl-derived))
                  (cadr arguments)))))
      (handler-case (slot-value object 'not-a-slot)
        (simple-error (condition)
          (let ((arguments (funcall (symbol-function 'simple-condition-format-arguments) condition)))
            (list (funcall (symbol-function 'simple-condition-format-control) condition)
                  (eq (car arguments) object) (cadr arguments)))))
      (progn
        ;; Use the admitted slot setter; the marker is CCL's real unbound value.
        (setf (slot-value object 'payload) (ccl::%slot-unbound-marker))
        (core-collect)
        (handler-case (slot-value object 'payload)
          (unbound-slot (condition)
            (list (slot-value condition 'ccl::name)
                  (eq (slot-value condition 'ccl::instance) object)))))
      (handler-bind
          ((unbound-slot (lambda (condition)
                           (declare (ignore condition))
                           (core-collect)
                           (invoke-restart 'use-value 31))))
        (let ((value (slot-value object 'payload)))
          (list value (slot-boundp object 'payload))))
      (progn
        (setf (slot-value object 'payload) 29)
        (core-collect)
        (slot-value object 'payload)))))

(defun ready-integer-magnitude (image)
  (declare (ignore image))
  (let ((answers nil))
    (dolist (n '(0 1 -1 536870911 -536870911 536870912 -536870912
                 536870913 -536870913 1152921504606846976 -1152921504606846976
                 #x51ad9826be1f03647905acfe123456789abcdef
                 #x-51ad9826be1f03647905acfe123456789abcdef))
      (let ((magnitude (ccl::%integer-abs n)))
        (core-collect)
        (push (list magnitude (gcd) (gcd n) (gcd n magnitude)
                    (gcd (* n 15) (* n 21) (* n 33)) (eq n magnitude)) answers)))
    (nreverse answers)))

;;; The native package-table probe uses its real (vector . counts) shape.
;;; Supply the hash residues explicitly so collision and wrap paths do not
;;; depend on the host's word-sized string hash.
(defun ready-symbol-lookup (image)
  (declare (ignore image))
  (let* ((vector (make-array 8 :initial-element 0))
         (table (cons vector (cons 2 6)))
         (answers nil))
    (setf (svref vector 6) :alpha
          (svref vector 0) -1
          (svref vector 2) :beta)
    (dolist (entry '(("ALPHA" 5) ("BETA" 4) ("MISSING" 7)
                     ("ALPHABET" 5) ("ALPHA" 4) ("beta" 4) ("" 0)))
      (core-collect)
      (push (multiple-value-list
             (ccl::%get-hashed-htab-symbol (car entry) (cadr entry) table 6 2))
            answers))
    (setf (svref vector 6) -1)
    (core-collect)
    (push (multiple-value-list (ccl::%get-hashed-htab-symbol "ALPHA" 5 table 6 2))
          answers)
    (setf (svref vector 0) :alpha)
    (core-collect)
    (push (multiple-value-list (ccl::%get-hashed-htab-symbol "ALPHA" 5 table 6 2))
          answers)
    (nreverse answers)))

(defun ready-bit-vectors (image &optional boundary index value)
  ;; The owner uses this entry to check malformed raw input before a store.
  (when boundary
    (return-from ready-bit-vectors
      (if (eq boundary t)
        (setf (sbit image index) value)
        (make-array index :element-type 'bit :initial-element value))))
  (let ((answers nil))
    (dolist (n '(0 1 7 8 9 31 32 33 63 64 65 257))
      (dolist (initial '(0 1))
        (let* ((bits (make-array n :element-type 'bit :initial-element initial))
               (before (loop for i below n collect (sbit bits i))))
          (declare (type simple-bit-vector bits))
          (dotimes (i n)
            (setf (sbit bits i) (logand (+ i initial) 1)))
          (core-collect)
          (when (> n 0)
            (setf (ccl::uvref bits (1- n)) initial))
          (push (list n before (loop for i below n collect (aref bits i))) answers))))
    (let ((bits (make-array 8 :element-type 'bit :initial-element 1)))
      (dolist (index '(-1 8 0.5d0))
        (push (handler-case (sbit bits index) (error () :bad-index)) answers))
      (dolist (value '(2 -1 nil #\x))
        (push (handler-case (setf (sbit bits 3) value) (error () :bad-bit)) answers))
      (push (loop for i below 8 collect (sbit bits i)) answers))
    (dolist (vector (list nil (vector 1 0) "10"))
      (push (handler-case (sbit vector 0) (error () :bad-vector)) answers))
    (dolist (value '(2 nil))
      (push (handler-case (make-array 9 :element-type 'bit :initial-element value)
              (error () :bad-initial)) answers))
    (let ((bits (make-array 33 :element-type 'bit)) (seen nil))
      (setf (sbit (progn (push :vector seen) (core-collect) bits)
                  (progn (push :index seen) (core-collect) 32))
            (progn (push :value seen) (core-collect) 1))
      (push (list (nreverse seen) (sbit bits 32) (sbit bits 31)) answers))
    ;; Use the native ordinal-based representation on real projected classes.
    (let* ((cpl (funcall (symbol-function 'ccl:compute-class-precedence-list)
                        (find-class 'cpl-derived)))
           (bits (ccl::make-cpl-bits cpl)))
      (core-collect)
      (push (list (length bits)
                  (mapcar (lambda (class) (sbit bits (ccl::%class-ordinal class))) cpl)
                  (ccl::make-cpl-bits nil)) answers))
    ;; Native DELETE allocates a bit map before copying the surviving cells.
    (dolist (backwards '(nil t))
      (let ((vector (vector 0 2 1 2 3 2 4 2 9)) (seen nil))
        (let ((answer (delete 2 vector :start 1 :end 8 :from-end backwards
                             :test (lambda (item value)
                                     (core-collect)
                                     (push value seen)
                                     (eql item value)))))
          (push (list (coerce answer 'list) (nreverse seen)) answers))))
    (nreverse answers)))

(defun ready-type-methods (image)
  (declare (ignore image))
  (let* ((class1 (make-array 16 :initial-element nil))
         (class2 (make-array 16 :initial-element nil))
         (a (ccl::%istruct 'ccl::named-ctype class1 nil 'a))
         (b (ccl::%istruct 'ccl::named-ctype class1 nil 'b))
         (c (ccl::%istruct 'ccl::named-ctype class2 nil 'c))
         (ccl::*empty-type* nil)
         (ccl::*wild-type* nil)
         (trace nil)
         (answers nil))
    (flet ((simple (x y)
             (core-collect)
             (push (list :simple (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values t t))
           (left (x y)
             (core-collect)
             (push (list :left (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values nil t))
           (right (x y)
             (core-collect)
             (push (list :right (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values nil nil)))
      (setf (ccl::type-class-simple-= class1) #'simple
            (ccl::type-class-simple-subtypep class1) #'simple)
      (push (mapcar (lambda (x) (not (null (ccl::ctype-p x))))
                    (list a b c nil 17 "not a ctype" (cons nil nil)))
            answers)
      (push (multiple-value-list (ccl::type= a a)) answers)
      (push (multiple-value-list (ccl::csubtypep a a)) answers)
      (push (multiple-value-list (ccl::type= a b)) answers)
      (push (multiple-value-list (ccl::csubtypep a b)) answers)
      ;; No complex method: the native macro's default is (VALUES NIL T).
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (setf (ccl::type-class-complex-= class1) #'left
            (ccl::type-class-complex-subtypep-arg1 class1) #'left)
      ;; TYPE= reverses arguments for the left method; CSUBTYPEP does not.
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (setf (ccl::type-class-complex-= class2) #'right
            (ccl::type-class-complex-subtypep-arg2 class2) #'right)
      ;; The right complex method has precedence over the left one.
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (let* ((cell (ccl::%svref a 0))
             (old (ccl::istruct-cell-info cell))
             (classes nil))
        (unwind-protect
            (progn
              (ccl::set-istruct-cell-info cell nil)
              (core-collect)
              (push (ccl::%class.name (class-of a)) classes)
              (ccl::set-istruct-cell-info cell
                (ccl::%class.own-wrapper (find-class 'ccl::named-ctype)))
              (core-collect)
              (push (ccl::%class.name (class-of a)) classes)
              (push (ccl::%class.name (class-of (ccl::%istruct 'ready-unclassified nil))) classes))
          (ccl::set-istruct-cell-info cell old))
        (list (nreverse answers) (nreverse trace) (nreverse classes))))))

;;; The selected image already contains initialized classes and method bodies.
;;; Reset host-lifetime state, publish its roots, and select uncached dispatch.
(defun ready-initialize (image)
  (unless (eq (ready-image-status image) t)
    (error "The READY image is not finalized."))
  (core-condition-prepare image)
  #+wasm32-target
  (progn
    (let* ((old ccl::*class-table*)
           (length (length old))
           (copy (make-array length :initial-element nil)))
      (ccl::%copy-gvector-to-gvector old 0 copy 0 length)
      (setq ccl::*class-table* copy
            ccl::*istruct-class* (find-class 'ccl::internal-structure)))
    (setq ccl::*string-output-stream-class* (find-class 'ccl::string-output-stream)
          ccl::*string-output-stream-class-wrapper*
            (ccl::%class.own-wrapper ccl::*string-output-stream-class*))
    (setf (svref ccl::*class-table* target::subtag-basic-stream)
          #'(lambda (stream)
              (ccl::%wrapper-class (ccl::basic-stream.wrapper stream))))
    ;; Native lock classification selects by the lock's kind cell. Resolve
    ;; the already loaded classes rather than importing native closures.
    (setf (svref ccl::*class-table* target::subtag-lock)
          #'(lambda (lock)
              (find-class
               (case (ccl::%svref lock target::lock.kind-cell)
                 (ccl::recursive-lock 'ccl::recursive-lock)
                 (ccl::read-write-lock 'ccl::read-write-lock)
                 (t 'ccl:lock)))))
    ;; D1 uses native bits without a separate native trampoline object.
    ;; Only GFs have the side vector; inherited-cell counts identify closures.
    (setf (svref ccl::*class-table* target::subtag-function)
          #'(lambda (function)
              (let ((bits (ccl::lfun-bits function)))
                (declare (fixnum bits))
                (cond ((logbitp ccl::$lfbits-gfn-bit bits)
                       (ccl::%wrapper-class (ccl::gf.instance.class-wrapper function)))
                      ((not (zerop (ldb ccl::$lfbits-numinh bits)))
                       (find-class 'ccl::compiled-lexical-closure))
                      ((logbitp ccl::$lfbits-method-bit bits)
                       (find-class 'ccl::method-function))
                      ((logbitp ccl::$lfbits-cm-bit bits)
                       (find-class 'ccl::combined-method))
                      (t (find-class 'compiled-function))))))
    ;; Native l1-clos-boot class-table initializer, reader-checked by the driver.
    (setf (svref ccl::*class-table* target::subtag-istruct)
          #'(lambda (i)
              (let* ((cell (ccl::%svref i 0))
                     (wrapper (ccl::istruct-cell-info cell)))
                (if wrapper
                  (ccl::%wrapper-class wrapper)
                  (or (find-class (ccl::istruct-cell-name cell) nil)
                      ccl::*istruct-class*))))))
  (ready-integer-print-tables image)
  (let ((gfs (cons (symbol-function 'ccl::eql-specializer-object) (svref image 8))))
    (dolist (entry (first (svref image 12)))
      (pushnew (car entry) gfs :test #'eq))
    (setq ccl::%all-gfs% (ccl::%cons-population gfs)
          ccl::*enable-automatic-termination* nil
          ccl::*%periodic-tasks%* nil))
  (values (length (ccl::population.data ccl::%all-gfs%))
          ccl::*enable-automatic-termination*
          ccl::*%periodic-tasks%*))

(defun ready-check (image)
  (let ((count 0))
    (dolist (entry (svref image 11))
      (unless (eq (find-class (car entry)) (cdr entry))
        (error "The class image lost a class cell."))
      (incf count))
    (let ((gfs (ccl::population.data ccl::%all-gfs%)))
      (dolist (gf (cons (symbol-function 'ccl::eql-specializer-object) (svref image 8)))
        (unless (ccl::memq gf gfs) (error "A projected generic function was lost.")))
      (dolist (entry (first (svref image 12)))
        (unless (ccl::memq (car entry) gfs) (error "An invalidation generic function was lost."))))
    (unless (and (not ccl::*enable-automatic-termination*)
                 (not ccl::*%periodic-tasks%*))
      (error "The image startup roots are not initialized."))
    (multiple-value-bind (sum removed value found empty present)
        (ready-table-bindings image)
      (unless (and (= sum 190) removed (eq value :absent) (not found)
                   (eq empty :empty) (not present))
        (error "The READY public table bindings failed.")))
    (unless (equal (ready-string-contract image)
                   '("" "x" "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "zzz"
                     (:size :type :fill) :bad-character))
      (error "READY string allocation contract failed."))
    (multiple-value-bind (zero positive negative) (ready-resource-strings image)
      (unless (and (equal zero "Error #0")
                   (equal positive "Error #987654")
                   (equal negative "Error #-37"))
        (error "READY resource-string fallback failed.")))
    (core-collect)
    (let ((condition (make-condition 'cpl-derived)))
      (values count
              (length (ccl::population.data ccl::%all-gfs%))
              (slot-value condition 'payload)
              (slot-value condition 'other)
              (handler-case (error "READY condition dispatch")
                (simple-error () :caught))))))

(defun ready-start (image)
  (ready-initialize image)
  (core-collect)
  (ready-check image))

;;; Exercise native ABS through its real NUMBER-CASE expansion, including
;;; its newly admitted scalar-complex primitive branches. Results expose only
;;; components, so the observer never needs a second complex representation.
(defun ready-numeric-sequences (image &optional operation a b)
  (declare (ignore image))
  (when operation
    (return-from ready-numeric-sequences
      (ready-complex-primitive operation a b)))
  (let ((answers nil))
    (dolist (number (list 0 1 -1 -536870912 536870911
                         (- (ash 1 70)) (1- (ash 1 130))
                         -0.0f0 -3.5f0 0.0d0 -3.5d0))
      (core-collect)
      (push (abs number) answers))
    (dolist (pair '((3.0f0 4.0f0) (-3.0f0 4.0f0) (0.0f0 -0.0f0)
                    (3.0d0 4.0d0) (-3.0d0 4.0d0) (0.0d0 -0.0d0)))
      (let ((trace nil))
        (let ((number (complex (progn (push :real trace) (core-collect) (car pair))
                               (progn (push :imaginary trace) (core-collect) (cadr pair)))))
          (core-collect)
          (push (list (realpart number) (imagpart number)
                      (abs number) (nreverse trace)) answers))))
    ;; COUNT forces SIMPLE-VECTOR-DELETE through ABS at its early exit.
    (dolist (backwards '(nil t))
      (dolist (count '(0 1 2 3 20))
        (dolist (bounds '((0 9) (1 8) (3 3)))
          (let ((vector (vector 0 2 1 2 3 2 4 2 9)) (seen nil))
            (let ((result (delete 2 vector :start (car bounds) :end (cadr bounds)
                                  :count count :from-end backwards
                                  :test (lambda (item value)
                                          (push value seen)
                                          (core-collect)
                                          (eql item value)))))
              (core-collect)
              (push (list (coerce result 'list) (nreverse seen)) answers))))))
    (nreverse answers)))

;;; A non-allocating entry around primitive refusals; unlike the main
;;; numerical witness it creates no lexical capture cells before admission.
(defun ready-complex-primitive (operation a b)
  (case operation
        (1 (ccl::%make-complex-single-float a b))
        (2 (ccl::%make-complex-double-float a b))
        (3 (ccl::%complex-single-float-realpart a))
        (4 (ccl::%complex-single-float-imagpart a))
        (5 (ccl::%complex-double-float-realpart a))
        (6 (ccl::%complex-double-float-imagpart a))))

;;; These are the same public calls and cleanup expansion used by WRITE-STRING.
;;; No native lock pointer crosses the image boundary: both machines allocate
;;; a fresh lock. Collection occurs while it is held recursively.
(defun ready-recursive-locks (image)
  (declare (ignore image))
  (let ((lock (ccl:make-lock "READY printer"))
        (other (ccl:make-lock "Independent"))
        (flag (ccl:make-lock-acquisition))
        (trace nil))
    (list
     (ccl::recursive-lock-p lock)
     (ccl::lock-name lock)
     (ccl:grab-lock lock flag)
     (ccl:lock-acquisition-status flag)
     (progn (core-collect) (ccl:try-lock lock))
     (ccl:release-lock lock)
     (ccl:release-lock lock)
     (catch 'done
       (ccl:with-lock-grabbed (lock)
         (push :outer trace)
         (core-collect)
         (ccl:with-lock-grabbed (lock)
           (push :inner trace)
           (ccl:with-lock-grabbed (other)
             (push :other trace)
             (core-collect)
             (throw 'done :unwound)))))
     (handler-case
         (ccl:with-lock-grabbed (lock)
           (core-collect)
           (error "READY lock cleanup"))
       (error () :caught))
     (progn (ccl:clear-lock-acquisition-status flag)
            (ccl:lock-acquisition-status flag))
     (ccl:try-lock lock flag)
     (ccl:lock-acquisition-status flag)
     (ccl:release-lock lock)
     (ccl:try-lock other)
     (ccl:release-lock other)
     (handler-case (ccl:release-lock lock)
       (ccl::not-lock-owner () :not-owner))
     (handler-case (ccl:grab-lock lock t)
       (type-error () :bad-flag))
     (ccl:try-lock lock)
     (ccl:release-lock lock)
     (nreverse trace))))

(defun ready-lock-operation (operation lock flag)
  (case operation
    (1 (ccl:make-lock "READY state"))
    (2 (ccl:grab-lock lock flag))
    (3 (ccl:try-lock lock flag))
    (4 (ccl:release-lock lock))
    (5 (handler-case (progn (ccl:grab-lock lock flag) :acquired)
         (error () :refused)))
    (6 (handler-case (progn (ccl:release-lock lock) :released)
         (error () :refused)))))


;;; Construct the native stream and ioblock layouts without an OS descriptor
;;; or the optional thread-local recycle pool. The public writers and extractor
;;; below are CCL's unchanged definitions, compiled in their file environments.
(defun ready-string-output (image)
  (declare (ignore image))
  (let* ((class (find-class 'ccl::string-output-stream))
         (stream (ccl::gvector :basic-stream
                   (ccl::%class.own-wrapper class)
                   (logior (ash 1 ccl::basic-stream-flag.open-character)
                           (ash 1 ccl::basic-stream-flag.open-output))
                   nil nil))
         (lock (ccl:make-lock "READY string output"))
         (block (ccl::make-string-output-stream-ioblock
                  :stream stream :string (make-string 0)
                  :write-char-function 'ccl::string-output-stream-ioblock-write-char
                  :write-simple-string-function 'ccl::string-output-stream-ioblock-write-simple-string
                  :outbuf-lock lock))
         (answers nil))
    (setf (ccl::basic-stream.state stream) block)
    (push (mapcar #'(lambda (cell)
                      (list (ccl::class-cell-name cell)
                            (eq cell (ccl::find-class-cell
                                      (ccl::class-cell-name cell) nil))))
                  (ccl::%svref block 0)) answers)
    (push (write-char #\? stream) answers)
    (dolist (string (list "" "a" (string #\Newline) "after newline" "λ雪"))
      (push (eq (write-string string stream) string) answers)
      (core-collect)
      (push (ccl::ioblock-charpos block) answers))
    (push (write-char #\! stream) answers)
    (push (write-string "<slice>" stream :start 1 :end 6) answers)
    (core-collect)
    (ccl::write-simple-string "[simple]" stream 1 7)
    (push (get-output-stream-string stream) answers)
    (push (get-output-stream-string stream) answers)
    ;; Grow an empty buffer via WRITE-CHAR, and a nonempty one via WRITE-STRING.
    (dotimes (i 90) (write-char (code-char (+ 65 (mod i 26))) stream))
    (core-collect)
    (push (get-output-stream-string stream) answers)
    (push (handler-case (write-string "bad bounds" stream :start 99)
            (error () :bad-bounds)) answers)
    (let ((source "λ雪abc")
          (destination (make-string 5 :initial-element #\.)))
      (ready-ivector-copy source 4 destination 0 16)
      (write-string destination stream)
      (push (get-output-stream-string stream) answers)
      (ready-ivector-copy destination 0 destination 4 16)
      (push destination answers))
    ;; The integer printer now takes its output branch through WRITE-STRING.
    (dolist (radix '(2 10 16 36))
      (dolist (integer '(0 -37 536870911 -536870912 1267650600228229401496703205377 -1267650600228229401496703205377))
        (ccl::%pr-integer integer radix stream)
        (core-collect)
        (push (get-output-stream-string stream) answers)))
    (setf (ccl::ioblock-device block) nil)
    (push (handler-case (write-string "closed" stream)
            (ccl::stream-is-closed-error () :closed)) answers)
    (setf (ccl::ioblock-device block) -1)
    ;; A declining callback unwinds through the real output-lock cleanup.
    (setf (ccl::ioblock-write-simple-string-function block)
          #'(lambda (block string start count)
              (declare (ignore block string start count))
              (core-collect)
              (throw 'ready-output :unwound)))
    (push (catch 'ready-output (write-string "unwind" stream)) answers)
    (setf (ccl::ioblock-write-simple-string-function block)
          'ccl::string-output-stream-ioblock-write-simple-string)
    (push (ccl:try-lock lock) answers)
    (ccl:release-lock lock)
    (push (handler-case (ccl:release-lock lock)
            (ccl::not-lock-owner () :unowned)) answers)
    (write-string "reused" stream)
    (push (get-output-stream-string stream) answers)
    (nreverse answers)))


;;; DEFSTRUCT declares target fixnum slots as (SIGNED-BYTE 30). Exercise the
;;; entire word boundary, including values that must take the bignum path.
(defun ready-type-widths (image)
  (declare (ignore image))
  (let ((answers nil))
    (dolist (value (list -536870913 -536870912 -1 0 268435455 268435456
                        536870911 536870912 1073741823 nil t "x" #\x 1.0d0))
      (push (list (typep value '(signed-byte 30))
                  (typep value '(unsigned-byte 29))
                  (typep value '(unsigned-byte 28))
                  (handler-case (ccl:require-type value '(signed-byte 30))
                    (type-error (condition)
                      (list :type-error (funcall (symbol-function 'type-error-datum) condition)
                            (funcall (symbol-function 'type-error-expected-type) condition)))))
            answers)
      (core-collect))
    (nreverse answers)))


;;; Byte offsets, including overlap, are the native ivector copy contract.
(defun ready-ivector-copy (source from destination to count)
  (ccl::%copy-ivector-to-ivector source from destination to count))

;;; The public constructor and CLOSE use native methods and the native pool.
;;; Bind the pool for the entire extent, just as CCL's thread startup does.
(defun ready-stream-constructors (image)
  (declare (ignore image))
  (let ((ccl::%string-output-stream-ioblocks% (ccl::%cons-pool nil))
        (answers nil))
    (dolist (type '(character ccl::base-character standard-char))
      (let* ((stream (make-string-output-stream :element-type type))
             (block (ccl::basic-stream.state stream)))
        (push (open-stream-p stream) answers)
        (write-string "λ雪" stream)
        (write-char #\Newline stream)
        (core-collect)
        (push (get-output-stream-string stream) answers)
        (push (get-output-stream-string stream) answers)
        (push (close stream) answers)
        (push (close stream) answers)
        (push (open-stream-p stream) answers)
        (push (eq block (ccl::pool.data ccl::%string-output-stream-ioblocks%)) answers)
        (push (handler-case (write-char #\! stream)
                (ccl::stream-is-closed-error () :closed)) answers)
        (let ((next (make-string-output-stream)))
          (push (eq block (ccl::basic-stream.state next)) answers)
          (push (get-output-stream-string next) answers)
          (push (ccl::ioblock-charpos (ccl::basic-stream.state next)) answers)
          (write-string "fresh" next)
          (push (get-output-stream-string next) answers)
          (close next :abort t))))
    ;; Closing under a different thread-local pool may not publish into it.
    (let* ((stream (make-string-output-stream))
           (block (ccl::basic-stream.state stream))
           (owner ccl::%string-output-stream-ioblocks%))
      (let ((ccl::%string-output-stream-ioblocks% (ccl::%cons-pool nil)))
        (core-collect)
        (close stream)
        (push (null (ccl::pool.data ccl::%string-output-stream-ioblocks%)) answers))
      (push (not (eq block (ccl::pool.data owner))) answers))
    ;; Native GC clears POOL.DATA; CORE-COLLECT is normally an oracle no-op,
    ;; so force native GC at this one representation-sensitive observation.
    (let ((stream (make-string-output-stream)))
      (write-string "collected pool" stream)
      (close stream)
      #+wasm32-target (core-collect)
      #-wasm32-target (ccl:gc)
      (push (null (ccl::pool.data ccl::%string-output-stream-ioblocks%)) answers)
      (let ((next (make-string-output-stream)))
        (write-string "after pool GC" next)
        (push (get-output-stream-string next) answers)
        (close next)))
    ;; Simultaneously live streams may not share the recycled ioblock.
    (let* ((a (make-string-output-stream)) (b (make-string-output-stream)))
      (push (not (eq (ccl::basic-stream.state a) (ccl::basic-stream.state b))) answers)
      (write-string "a" a) (write-string "b" b)
      (core-collect)
      (push (list (get-output-stream-string a) (get-output-stream-string b)) answers)
      (close a) (close b))
    (push (with-output-to-string (stream)
            (write-string "macro" stream) (core-collect) (write-char #\! stream)) answers)
    (let ((saved nil))
      (push (catch 'stream-exit
              (with-output-to-string (stream)
                (setq saved stream)
                (write-string "discard" stream)
                (core-collect)
                (throw 'stream-exit :unwound))) answers)
      (push (open-stream-p saved) answers)
      (push (handler-case
                (with-output-to-string (stream)
                  (setq saved stream) (core-collect) (error "constructor cleanup"))
              (error () :caught)) answers)
      (push (open-stream-p saved) answers))
    (push (with-output-to-string (stream nil :element-type 'character)
            (write-string "after cleanup" stream)) answers)
    (nreverse answers)))

(defun ready-thread-value (symbol)
  #+wasm32-target (ccl::%wasm-thread-local-value symbol)
  #-wasm32-target
  (let ((location (ccl::%tcr-binding-location (ccl::%current-tcr) symbol)))
    (and location (ccl::%fixnum-ref location))))

(defun ready-thread-values (image)
  (declare (ignore image))
  (let ((answers nil)
        (old (symbol-value '*core-host-events*)))
    (unwind-protect
        (progn
          (setf (symbol-value '*core-host-events*) :global)
          (push (ready-thread-value '*core-host-events*) answers)
          (let ((*core-host-events* :outer))
            (push (ready-thread-value '*core-host-events*) answers)
            (let ((*core-host-events* nil))
              (core-collect)
              (push (ready-thread-value '*core-host-events*) answers))
            (push (ready-thread-value '*core-host-events*) answers)
            (push (catch 'binding-exit
                    (let ((*core-host-events* :inner))
                      (core-collect)
                      (throw 'binding-exit
                        (ready-thread-value '*core-host-events*)))) answers)
            (push (ready-thread-value '*core-host-events*) answers))
          (push (ready-thread-value '*core-host-events*) answers)
          (push (symbol-value '*core-host-events*) answers)
          (nreverse answers))
      (setf (symbol-value '*core-host-events*) old))))

;;; The remaining SUBTYPEP environment is an explicit READY boundary.
(defun ready-stream-element-type (type)
  (handler-case (make-string-output-stream :element-type type)
    (error () :bad-element-type)))
