(in-package :wasm32-compiler)

;;; Admission precedes publishing any image root. These are the native class
;;; and method fields, not a parallel catalogue maintained by the owner.
(defun ready-image-status (image)
  (dolist (entry (svref image 11))
    (let ((class (cdr entry)))
      (unless (ccl::%standard-instance-p class)
        (return-from ready-image-status :class-shape))
      (unless (and (consp (ccl::%class.cpl class))
                   (eq (car (ccl::%class.cpl class)) class))
        (return-from ready-image-status :class-cpl))
      (let ((wrapper (ccl::%class.own-wrapper class)))
        (unless (and wrapper (eq (ccl::%wrapper-class wrapper) class))
          (return-from ready-image-status :class-wrapper))
        (when (eql (ccl::%wrapper-hash-index wrapper) 0)
          (return-from ready-image-status :obsolete-wrapper)))))
  (dolist (gf (cons (symbol-function 'ccl::eql-specializer-object)
                   (append (svref image 8)
                           (loop for entry in (first (svref image 12)) collect (car entry)))))
    (unless (eq (ccl::%gf-method-combination gf)
                ccl::*standard-method-combination*)
      (return-from ready-image-status :method-combination))
    (dolist (method (ccl::%gf-methods gf))
      (unless (functionp (ccl::%method-function method))
        (return-from ready-image-status :method-function))))
  t)

;;; Directed admission checks restore the source image after every mutation.
;;; This entry is a qualification caller, not part of the startup worklist.
(defun ready-image-refusals (image)
  (let* ((entry (car (svref image 11)))
         (class (cdr entry))
         (wrapper (ccl::%class.own-wrapper class))
         (gf (car (svref image 8)))
         (method (car (ccl::%gf-methods gf))))
    (macrolet ((check (place value)
                 `(let ((old ,place))
                    (unwind-protect
                        (progn (setf ,place ,value) (ready-image-status image))
                      (setf ,place old)))))
      (list (check (cdr entry) nil)
            (check (ccl::%class.cpl class) nil)
            (check (ccl::%class.cpl class) (list nil))
            (check (ccl::%class.own-wrapper class) nil)
            (check (ccl::%wrapper-class wrapper) nil)
            (check (ccl::%wrapper-hash-index wrapper) 0)
            (check (ccl::sgf.method-combination gf) nil)
            (check (ccl::%method.function method) nil)
            (ready-image-status image)))))

;;; Exercise the public function cells, not the compiler's direct-call
;;; substitution. Those cells must use the admitted table implementation too.
(defun ready-table-bindings (image)
  (declare (ignore image))
  (let ((table (ccl::%wasm-make-class-table 4))
        (keys nil)
        (sum 0))
    (dotimes (i 20)
      (let ((key (cons i nil)))
        (push key keys)
        (funcall (symbol-function 'ccl::puthash) key table i))
      (when (zerop (logand i 3)) (core-collect)))
    (dolist (key keys)
      (multiple-value-bind (value found) (funcall (symbol-function 'gethash) key table)
        (unless found (error "A READY table binding lost a key."))
        (incf sum value)))
    (let ((removed (funcall (symbol-function 'remhash) (car keys) table)))
      (core-collect)
      (multiple-value-bind (value found)
          (funcall (symbol-function 'gethash) (car keys) table :absent)
        (funcall (symbol-function 'clrhash) table)
        (core-collect)
        (multiple-value-bind (empty present)
            (funcall (symbol-function 'gethash) (cadr keys) table :empty)
          (values sum removed value found empty present))))))

;;; Resource fallback returns a string; it does not print to a stream. Exercise
;;; the unchanged CCL path with no resource entries, including a negative code.
(defun ready-resource-strings (image)
  (declare (ignore image))
  (let ((ccl::*error-format-strings* nil))
    (values (ccl::%rsc-string 0)
            (ccl::%rsc-string 987654)
            (ccl::%rsc-string -37))))

(defun ready-string-contract (image)
  (declare (ignore image))
  (let ((function (symbol-function 'make-string))
        (trace nil))
    (list (funcall function 0 :initial-element #\x)
          (funcall function 1 :initial-element #\x)
          (funcall function 30 :initial-element #\x)
          (funcall function 33 :initial-element #\x)
          (funcall function
                   (progn (push :size trace) (core-collect) 3)
                   :element-type (progn (push :type trace) 'base-char)
                   :initial-element (progn (push :fill trace) (core-collect) #\z))
          (nreverse trace)
          (handler-case (funcall function 2 :initial-element 7)
            (type-error () :bad-character)))))

;;; This is the top-level radix-table initializer in l0-int.lisp. The input
;;; driver checks its body against that source form before compiling probes.
(defun ready-integer-print-tables (image)
  (declare (ignore image))
  (do* ((b (make-array 37 :initial-element nil))
        (f (make-array 37 :initial-element nil))
        (base 2 (1+ base)))
       ((= base 37) (setq ccl::*base-power* b ccl::*fixnum-power--1* f))
    (do ((power-1 -1 (1+ power-1))
         (new-divisor base (* new-divisor base))
         (divisor 1 new-divisor))
        ((not (ccl::fixnump new-divisor))
         (setf (aref b base) divisor)
         (setf (aref f base) power-1))))
  t)

(defun ready-integer-strings (image)
  (declare (ignore image))
  (let ((results nil))
    (dolist (integer '(0 1 -1 536870911 536870912 -536870912 -536870913
                      1152921504606846976 -1152921504606846976
                      #x51ad9826be1f03647905acfe123456789abcdef
                      #x-51ad9826be1f03647905acfe123456789abcdef))
      (dolist (radix '(2 8 10 16 36))
        (let ((string (ccl::%integer-to-string integer radix)))
          (core-collect)
          (push string results))))
    (nreverse results)))

(defun ready-list-callees (image)
  (declare (ignore image))
  (let* ((tail (list 'c 'd))
         (list (list* 'a 'b tail))
         (dotted (cons 'a (cons 'b 'end)))
         (sum 0)
         (visited nil))
    (let ((prefix (funcall (symbol-function 'ldiff) list tail))
          (dotted-copy (funcall (symbol-function 'ldiff) dotted 'not-a-tail))
          (numbers (list 1 2 3 4)))
      (core-collect)
      (let ((answer (funcall (symbol-function 'mapc) (lambda (x y)
                           (incf sum (+ x y))
                           (push x visited)
                           (core-collect))
                         numbers '(10 20 30))))
        (list prefix dotted-copy (eq answer numbers) sum
              (nreverse visited) (eq (cddr list) tail))))))

(defun ready-type-methods (image)
  (declare (ignore image))
  (let* ((class1 (make-array 16 :initial-element nil))
         (class2 (make-array 16 :initial-element nil))
         (a (ccl::%istruct 'ccl::named-ctype class1 nil 'a))
         (b (ccl::%istruct 'ccl::named-ctype class1 nil 'b))
         (c (ccl::%istruct 'ccl::named-ctype class2 nil 'c))
         (ccl::*empty-type* nil)
         (ccl::*wild-type* nil)
         (trace nil)
         (answers nil))
    (flet ((simple (x y)
             (core-collect)
             (push (list :simple (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values t t))
           (left (x y)
             (core-collect)
             (push (list :left (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values nil t))
           (right (x y)
             (core-collect)
             (push (list :right (ccl::named-ctype-name x) (ccl::named-ctype-name y)) trace)
             (values nil nil)))
      (setf (ccl::type-class-simple-= class1) #'simple
            (ccl::type-class-simple-subtypep class1) #'simple)
      (push (multiple-value-list (ccl::type= a a)) answers)
      (push (multiple-value-list (ccl::csubtypep a a)) answers)
      (push (multiple-value-list (ccl::type= a b)) answers)
      (push (multiple-value-list (ccl::csubtypep a b)) answers)
      ;; No complex method: the native macro's default is (VALUES NIL T).
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (setf (ccl::type-class-complex-= class1) #'left
            (ccl::type-class-complex-subtypep-arg1 class1) #'left)
      ;; TYPE= reverses arguments for the left method; CSUBTYPEP does not.
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (setf (ccl::type-class-complex-= class2) #'right
            (ccl::type-class-complex-subtypep-arg2 class2) #'right)
      ;; The right complex method has precedence over the left one.
      (push (multiple-value-list (ccl::type= a c)) answers)
      (push (multiple-value-list (ccl::csubtypep a c)) answers)
      (let* ((cell (ccl::%svref a 0))
             (old (ccl::istruct-cell-info cell))
             (classes nil))
        (unwind-protect
            (progn
              (ccl::set-istruct-cell-info cell nil)
              (core-collect)
              (push (ccl::%class.name (class-of a)) classes)
              (ccl::set-istruct-cell-info cell
                (ccl::%class.own-wrapper (find-class 'ccl::named-ctype)))
              (core-collect)
              (push (ccl::%class.name (class-of a)) classes)
              (push (ccl::%class.name (class-of (ccl::%istruct 'ready-unclassified nil))) classes))
          (ccl::set-istruct-cell-info cell old))
        (list (nreverse answers) (nreverse trace) (nreverse classes))))))

;;; The selected image already contains initialized classes and method bodies.
;;; Reset host-lifetime state, publish its roots, and select uncached dispatch.
(defun ready-initialize (image)
  (unless (eq (ready-image-status image) t)
    (error "The READY image is not finalized."))
  (core-condition-prepare image)
  #+wasm32-target
  (progn
    (let* ((old ccl::*class-table*)
           (length (length old))
           (copy (make-array length :initial-element nil)))
      (ccl::%copy-gvector-to-gvector old 0 copy 0 length)
      (setq ccl::*class-table* copy
            ccl::*istruct-class* (find-class 'ccl::internal-structure)))
    ;; Native l1-clos-boot class-table initializer, reader-checked by the driver.
    (setf (svref ccl::*class-table* target::subtag-istruct)
          #'(lambda (i)
              (let* ((cell (ccl::%svref i 0))
                     (wrapper (ccl::istruct-cell-info cell)))
                (if wrapper
                  (ccl::%wrapper-class wrapper)
                  (or (find-class (ccl::istruct-cell-name cell) nil)
                      ccl::*istruct-class*))))))
  (ready-integer-print-tables image)
  (let ((gfs (cons (symbol-function 'ccl::eql-specializer-object) (svref image 8))))
    (dolist (entry (first (svref image 12)))
      (pushnew (car entry) gfs :test #'eq))
    (setq ccl::%all-gfs% (ccl::%cons-population gfs)
          ccl::*enable-automatic-termination* nil
          ccl::*%periodic-tasks%* nil))
  (values (length (ccl::population.data ccl::%all-gfs%))
          ccl::*enable-automatic-termination*
          ccl::*%periodic-tasks%*))

(defun ready-check (image)
  (let ((count 0))
    (dolist (entry (svref image 11))
      (unless (eq (find-class (car entry)) (cdr entry))
        (error "The class image lost a class cell."))
      (incf count))
    (let ((gfs (ccl::population.data ccl::%all-gfs%)))
      (dolist (gf (cons (symbol-function 'ccl::eql-specializer-object) (svref image 8)))
        (unless (ccl::memq gf gfs) (error "A projected generic function was lost.")))
      (dolist (entry (first (svref image 12)))
        (unless (ccl::memq (car entry) gfs) (error "An invalidation generic function was lost."))))
    (unless (and (not ccl::*enable-automatic-termination*)
                 (not ccl::*%periodic-tasks%*))
      (error "The image startup roots are not initialized."))
    (multiple-value-bind (sum removed value found empty present)
        (ready-table-bindings image)
      (unless (and (= sum 190) removed (eq value :absent) (not found)
                   (eq empty :empty) (not present))
        (error "The READY public table bindings failed.")))
    (unless (equal (ready-string-contract image)
                   '("" "x" "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "zzz"
                     (:size :type :fill) :bad-character))
      (error "READY string allocation contract failed."))
    (multiple-value-bind (zero positive negative) (ready-resource-strings image)
      (unless (and (equal zero "Error #0")
                   (equal positive "Error #987654")
                   (equal negative "Error #-37"))
        (error "READY resource-string fallback failed.")))
    (core-collect)
    (let ((condition (make-condition 'cpl-derived)))
      (values count
              (length (ccl::population.data ccl::%all-gfs%))
              (slot-value condition 'payload)
              (slot-value condition 'other)
              (handler-case (error "READY condition dispatch")
                (simple-error () :caught))))))

(defun ready-start (image)
  (ready-initialize image)
  (core-collect)
  (ready-check image))
