(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(load (merge-pathnames "selection.lisp" *load-pathname*))
(load (merge-pathnames "cases.lisp" *load-pathname*))
(defparameter *config-globals* '(ccl::*host-page-size* ccl::*ticks-per-second* ccl::*ns-per-tick*
 ccl::*initial-listener-default-control-stack-size* ccl::*initial-listener-default-value-stack-size*
 ccl::*initial-listener-default-temp-stack-size* ccl::*spin-lock-tries* ccl::*spin-lock-timeouts*))
(defun json-val (s x)
 (cond ((null x)(write-string "\"nil\"" s)) ((integerp x)(format s "~d" x))
  ((eq x 'ccl::*spin-lock-timeouts*)(write-string "\"CCL::*SPIN-LOCK-TIMEOUTS*\"" s))
  ((listp x)(write-char #\[ s)(loop for v in x for i from 0 do (unless (zerop i)(write-char #\, s))(json-val s v))(write-char #\] s))
  (t(error "Unexpected value ~s" x))))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (sources nil) (modules nil))
 (with-open-file (s (concatenate 'string out "source-forms.lisp") :direction :output :if-exists :error)
  (dolist (row *config-selection*)
   (destructuring-bind (name source position module) row
    (declare (ignore module))
    (let* ((*package* (find-package "CCL")) (symbol (find-symbol name "CCL"))
      (form (with-open-file (f source)(file-position f position)(read f)))
      (registry (if (eq (first form) 'ccl::def-load-pointers) ccl::*lisp-user-pointer-functions* ccl::*lisp-system-pointer-functions*)))
     (assert (eq symbol (second form)))
     (assert (= 1 (count symbol registry :key #'ccl::function-name)))
     (push form sources)(print (list name source position form) s)))))
 (setq sources (nreverse sources))
 ;; Each external read is replaced once; every other native form remains intact.
 ;; The source formulas, not the port owner, supply all arithmetic and writes.
 (with-open-file (trace (concatenate 'string out "adapted-native-forms.lisp") :direction :output :if-exists :error)
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
   (let ((saved (mapcar #'symbol-value *config-globals*)))
    (unwind-protect
     (progn
      (write-char #\[ s)
      (loop for case in *config-cases* for ci from 0 do
       (unless (zerop ci)(write-char #\, s))(write-char #\[ s)
       (destructuring-bind (page ticks cpu stack defaults) case
        (loop for sentinel in '(37 91) for ri from 0 do
         (unless (zerop ri)(write-char #\, s))(write-char #\[ s)
         (dolist (g *config-globals*)(set g sentinel))
         (loop for g in (subseq *config-globals* 3 6) for v in defaults do (set g v))
         (loop for form in sources for i from 0 do
          (unless (zerop i)(write-char #\, s))
          (let* ((body (if (eq (car form) 'ccl::defloadvar) (list `(setq ,(second form) ,(third form))) (cdddr form)))
                 (target (case i
                  (0 '(ccl::get-page-size))
                  (1 (let ((v (third form))) (assert (and (eq (car v) 'max)(eql (second v) 1000))) (third v)))
                  (2 nil)
                  (3 '(ccl::%get-kernel-global 'ccl::stack-size))
                  (4 '(ccl::cpu-count))))
                 (replacement (nth i (list page ticks nil stack cpu))) (count 0))
           (labels ((rewrite (x)
             (cond ((and target (equal x target))(incf count) replacement)
              ((consp x)(cons (rewrite (car x))(rewrite (cdr x)))) (t x))))
            (let ((new (rewrite body)))
             (assert (= count (if (= i 2) 0 1)))
             (print (list ci sentinel i `(lambda () ,@new)) trace)
             (let* ((f (compile nil `(lambda () ,@new))) (values (multiple-value-list (funcall f))))
              (format s "{\"values\":")(json-val s values)
              (format s ",\"globals\":")(json-val s (mapcar #'symbol-value *config-globals*))(write-char #\} s))))))
         (write-char #\] s)))
       (write-char #\] s))
      (write-char #\] s))
     (loop for g in *config-globals* for v in saved do (set g v)))
    (assert (equal saved (mapcar #'symbol-value *config-globals*))))))
 (dolist (row '( ("config_5564" . (lambda (symbol value done) (multiple-value-prog1 (set symbol value)(rplaca done 101))))
  ("config_6151" . (lambda (symbol value done) (multiple-value-prog1 (set symbol value)(rplaca done 102))))
  ("config_6150" . (lambda (symbol value done) (multiple-value-prog1 (set symbol value)(rplaca done 103))))
  ("config_6127" . (lambda (cs vs ts active size half done) (multiple-value-prog1 (if active (progn (set cs size)(set vs size)(set ts half)) nil)(rplaca done 104))))
  ("config_5566" . (lambda (tries timeouts cpu done) (multiple-value-prog1 (progn (set tries (if (eq cpu 1) 1 1024))(set timeouts 0) timeouts)(rplaca done 105))))
  ("preflight" . (lambda (s0 s1 s2 s3 s4 s5 s6 s7 done) (multiple-value-prog1 (values (symbol-value s0)(symbol-value s1)(symbol-value s2)(symbol-value s3)(symbol-value s4)(symbol-value s5)(symbol-value s6)(symbol-value s7))(rplaca done 100))))
  ("workload" . (lambda (s0 s1 s2 s3 s4 s5 s6 s7 done) (multiple-value-prog1 (values (symbol-value s0)(symbol-value s1)(symbol-value s2)(symbol-value s3)(symbol-value s4)(symbol-value s5)(symbol-value s6)(symbol-value s7))(rplaca done 106))))))
  (let ((m (compile-call-form (cdr row)(car row) nil)))
   (assert (null (getf m :children))) (push m modules)
   (with-open-file (s (concatenate 'string out (car row) ".wat") :direction :output :if-exists :error)(write-string (getf m :wat) s))))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (write-char #\[ s)(loop for m in modules for i from 0 do (unless (zerop i)(write-char #\, s))(format s "{\"name\":~s}" (getf m :name)))(write-char #\] s))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error)(write-pool-graph s (mapcar (lambda(m)(getf m :pool)) modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
