(in-package :wasm32-compiler)

(defun namespace-abi-cases ()
  (list
   (mapcar (lambda (test)
             (let ((table (make-hash-table :test test :size 0)))
               (setf (gethash 'first table) 11
                     (gethash 'second table) nil)
               (let ((before (list (hash-table-count table)
                                   (multiple-value-list (gethash 'second table :missing))
                                   (multiple-value-list (gethash 'absent table :missing)))))
                 (setf (gethash 'first table) 31)
                 (let ((sum 0))
                   (maphash (lambda (key value) (declare (ignore key))
                              (when value (incf sum value))) table)
                   (list test before sum (remhash 'second table)
                         (remhash 'second table) (hash-table-count table)
                         (eq table (clrhash table)) (hash-table-count table))))))
           '(eq eql equal equalp))
   (let ((table (make-hash-table :test 'equal)))
     (setf (gethash (list "same" 17) table) 42)
     (list (gethash (list (copy-seq "same") 17) table)
           (= (sxhash (list "same" 17)) (sxhash (list (copy-seq "same") 17)))))
   (mapcar (lambda (entry)
             (destructuring-bind (type initial replacement) entry
               (let ((vector (make-array 4 :element-type type :initial-element initial)))
                 (setf (aref vector 2) replacement)
                 (list type (coerce vector 'list)))))
           '(((unsigned-byte 8) 255 0) ((signed-byte 8) -128 127)
             ((unsigned-byte 16) 65535 0) ((signed-byte 16) -32768 32767)
             ((unsigned-byte 32) 4294967295 2147483648)
             ((signed-byte 32) -2147483648 2147483647)
             (fixnum -100 100)))
   (let ((source (make-array 16 :element-type '(unsigned-byte 8)))
         (destination (make-array 4 :element-type '(unsigned-byte 32))))
     (dotimes (i 16) (setf (aref source i) (+ 128 i)))
     (ccl::%copy-ivector-to-ivector source 0 destination 0 16)
     (list (coerce destination 'list)
           (progn (ccl::%copy-ivector-to-ivector source 0 source 3 10)
                  (coerce source 'list))
           (progn (ccl::%copy-ivector-to-ivector source 3 source 0 10)
                  (coerce source 'list))))))
