(in-package :wasm32-compiler)

(defun namespace-file-error (function)
  (handler-case (list :returned (funcall function))
    (file-error (condition)
      (list (type-of condition) (namestring (file-error-pathname condition))))))

(defun namespace-binary-cases ()
  (vector
   (list :paths
         (namestring (truename ""))
         (namestring (probe-file "sub/../a.bin"))
         (namestring (probe-file "../other/a.bin"))
         (namestring (probe-file "λ.lisp"))
         (namestring (probe-file "sub/"))
         (probe-file "missing"))
   (list :missing
         (open "missing" :element-type '(unsigned-byte 8) :if-does-not-exist nil)
         (namespace-file-error (lambda () (truename "missing")))
         (namespace-file-error (lambda () (open "missing" :element-type '(unsigned-byte 8)))))
   (list :empty
         (with-open-file (stream "empty" :element-type '(unsigned-byte 8))
           (let ((buffer (make-array 4 :element-type '(unsigned-byte 8) :initial-element 219)))
             (list (file-length stream) (file-position stream)
                   (read-byte stream nil :end) (read-sequence buffer stream :start 1)
                   buffer (file-position stream)
                   (handler-case (read-byte stream)
                     (end-of-file (condition)
                       (list (type-of condition) (eq stream (stream-error-stream condition)))))))))
   (list :independent
         (with-open-file (left "a.bin" :element-type '(unsigned-byte 8))
           (with-open-file (right "a.bin" :element-type '(unsigned-byte 8))
             (list (read-byte left) (read-byte left) (read-byte right)
                   (file-position left) (file-position right)))))
   (list :integer-streams
         (mapcar
          (lambda (type)
            (with-open-file (stream "a.bin" :element-type type)
              (let ((buffer (make-array 12 :element-type type :initial-element 19)))
                (list type (stream-element-type stream) (file-length stream)
                      (read-sequence buffer stream :start 1 :end 11)
                      (coerce buffer 'list) (file-position stream)
                      (read-byte stream nil :end)
                      (file-position stream :start) (read-byte stream)))))
          '((signed-byte 8) (unsigned-byte 16) (signed-byte 16)
            (unsigned-byte 32) (signed-byte 32))))
   (list :large
         (let ((ccl::*elements-per-buffer* 16384))
           (with-open-file (stream "large.bin" :element-type '(unsigned-byte 8))
             (let ((buffer (make-array 9007 :element-type '(unsigned-byte 8) :initial-element 219)))
               (list (file-length stream)
                     (read-sequence buffer stream :start 3 :end 9005)
                     buffer (file-position stream) (read-byte stream nil :end)
                     (file-position stream 8127) (read-byte stream) (read-byte stream)
                     (file-position stream 2047) (read-byte stream) (read-byte stream)
                     (file-position stream :end) (read-byte stream nil :end)
                     (file-position stream :start) (read-byte stream))))))
   (list :unwind
         (let ((stream nil))
           (list (catch 'done
                   (with-open-file (s "a.bin" :element-type '(unsigned-byte 8))
                     (setq stream s)
                     (throw 'done (read-byte s))))
                 (open-stream-p stream)
                 (handler-case (read-byte stream)
                   (stream-error (condition)
                     (list (type-of condition) (eq stream (stream-error-stream condition)))))
                 (close stream)))))
)
