(in-package :wasm32-compiler)
(let* ((*core-modules* (copy-list *core-modules*))
       (*core-records* (copy-list *core-records*)) (*core-files* (copy-list *core-files*))
       (*validation-wire-prefix* "namespace") (*b-cpl-conditions* t) (*b-allocation-retry* t)
       (out (ccl:getenv "PROBE_OUTPUT")))
  (core-compile-file "ccl:level-0;l0-array.lisp")
  (core-compile-file "ccl:level-1;sysutils.lisp")
  (core-compile-file "ccl:level-1;l1-symhash.lisp")
  (core-compile-file "ccl:level-1;l1-utils.lisp")
  (core-compile-file "ccl:level-1;l1-unicode.lisp")
  (core-compile-file "ccl:level-1;l1-dcode.lisp")
  (core-compile-file "ccl:level-1;l1-sort.lisp")
  (core-compile-file "ccl:lib;sequences.lisp")
  (core-compile-file "ccl:lib;lists.lisp")
  (core-compile-file "ccl:lib;streams.lisp")
  (core-compile-file "ccl:lib;defstruct.lisp")
  (core-compile-file "ccl:compiler;dll-node.lisp")
  (core-compile-file "ccl:lib;foreign-types.lisp")
  (load (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "methods.lisp"))
  (let ((forms (call-with-target #'namespace-method-forms))
        (file (concatenate 'string (ccl:getenv "PROBE_OUTPUT") "methods.lisp")))
    (with-open-file (s file :direction :output :if-exists :supersede)
      (let ((*print-circle* t) (*print-readably* t))
        (write '(in-package :wasm32-compiler) :stream s)
        (dolist (form forms) (terpri s) (write form :stream s))))
    (core-compile-file file))
  (load (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "type-startup.lisp"))
  (let ((file (concatenate 'string out "type-startup.lisp")))
    (with-open-file (s file :direction :output :if-exists :supersede)
      (let ((*print-circle* t) (*print-readably* t))
        (write '(in-package :wasm32-compiler) :stream s)
        (terpri s) (write (namespace-type-startup-form) :stream s)))
    (core-compile-file file))
  (load (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "foreign-startup.lisp"))
  (let ((file (concatenate 'string out "foreign-startup.lisp")))
    (with-open-file (s file :direction :output :if-exists :supersede)
      (let ((*print-circle* t) (*print-readably* t))
        (write '(in-package :wasm32-compiler) :stream s)
        (terpri s) (write (namespace-foreign-startup-form) :stream s)))
    (core-compile-file file))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "foreign-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "binary-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "character-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "readonly-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "abi-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "boundary-cases.lisp"))
  (core-compile-file (concatenate 'string (ccl:getenv "NAMESPACE_SOURCE") "probes.lisp"))
  (with-open-file (s (concatenate 'string out "records.sexp") :direction :output :if-exists :supersede)
    (let ((*print-pretty* nil)) (prin1 (reverse *core-records*) s)))
  (let* ((public (make-hash-table :test #'equal))
         (definition-records
           (loop for (file records) in *core-files* append
             (loop for record in (reverse records)
                   when (and (consp record) (eq (car record) ccl::$fasl-defun))
                     collect (second record))))
         (definitions
           (let ((names nil))
            (loop for reference in definition-records
                 for wire = (if (wasm32-function-reference-p reference)
                              (second (assoc (wasm32-function-reference-cell reference)
                                             *namespace-load-references*))
                              (and (consp reference) (eq (car reference) :wasm-module)
                                   (second reference)))
                 for record = (and wire (find wire *core-records* :key #'third :test #'equal))
                 for name = (and record (ccl::maybe-setf-function-name (second record)))
                 when (and record (not (member name names)))
                   collect (progn (push name names) record))))
         (seen nil)
         (named (remove-if-not (lambda (m)
                    (let* ((source (getf m :source-name))
                           (name (and source
                                      (or (symbolp source) (ccl::setf-function-name-p source))
                                      (ccl::maybe-setf-function-name source))))
                      (and name
                           (find (getf m :name) definitions :key #'third :test #'equal)
                           (not (member name seen)) (push name seen)
                           (setf (gethash (getf m :name) public) t)))) *core-modules*))
         (all (loop for m in (reverse named) append (cons m (getf m :children)))))
    (with-open-file (s (concatenate 'string out "public-definitions.json") :direction :output :if-exists :supersede)
      (let ((seen nil))
        (ccl::namespace-json
         (coerce (loop for record in definitions
                       for name = (ccl::maybe-setf-function-name (second record))
                       unless (member name seen) collect
                         (progn (push name seen)
                           (vector (frontend-owner name) (third record) (eq (fourth record) :admitted))))
                 'vector) s)))
    (let ((initializers
            (remove-if-not
             (lambda (m)
               (and (null (getf m :source-name))
                    (or (and (equal (getf m :source-file) "ccl:level-0;l0-def.lisp")
                             (member 'ccl::%fhave (getf m :dependencies)))
                        (and (equal (getf m :source-file) "ccl:level-1;l1-streams.lisp")
                             (member 'ccl:make-lock (getf m :dependencies))
                             (member 'ccl::%defun (getf m :dependencies))))))
             (reverse *core-modules*))))
      (assert (= (length initializers) 4))
      (with-open-file (s (concatenate 'string out "initializers.json") :direction :output :if-exists :supersede)
        (ccl::namespace-json (coerce (mapcar (lambda (m) (getf m :name)) initializers) 'vector) s))
      (dolist (m initializers) (setq all (append all (cons m (getf m :children))))))
    ;; QLFUN references identify emitted functions even when they have no
    ;; public name. Retain the exact referenced code and its nested closures.
    (let ((pending (copy-list all)))
      (loop while pending do
        (let ((m (pop pending)))
          (dolist (binding (getf m :symbols))
            (let* ((reference (assoc (first binding) *namespace-load-references*))
                   (wire (second reference)))
              (when (and wire (not (find wire all :key (lambda (m) (getf m :name)) :test #'equal)))
                (let ((target (find wire *core-modules* :key (lambda (m) (getf m :name)) :test #'equal)))
                  (assert target)
                  (dolist (code (cons target (getf target :children)))
                    (push code all) (push code pending)))))))))
    (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (loop for m in all for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"primitive\":false,\"cplMode\":true,\"function\":" (getf m :name))
        (if (gethash (getf m :name) public)
          (format s "~s" (frontend-owner (ccl::maybe-setf-function-name (getf m :source-name))))
          (write-string "null" s))
        (write-string ",\"symbols\":[" s)
        (loop for (symbol wire) in (getf m :symbols) for j from 0 do
          (unless (zerop j) (write-char #\, s))
          (format s "[~s,~s]" wire (frontend-owner symbol)))
        (write-string "]}" s))
      (write-char #\] s))
    (dolist (m all)
      (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :supersede)
        (write-string (getf m :wat) s)))
    (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :supersede)
      (let ((roots (mapcar (lambda (m) (getf m :pool)) all)))
        (frontend-pool-owners roots) (write-pool-graph s roots)))
    (let ((image (cpl-image 'cpl-left)))
      (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :supersede)
        (format s "[{\"definition\":\"NAMESPACE-CHECK\",\"name\":~s,\"args\":[" (getf (find 'namespace-check named :key (lambda (m) (getf m :source-name))) :name))
        (core-json-value image s)
        (write-string "],\"values\":[],\"after\":[],\"globals\":null,\"globalsAfter\":null}]" s)))
    (with-open-file (s (concatenate 'string out "load-bindings.json") :direction :output :if-exists :supersede)
      (ccl::namespace-json
       (coerce (loop for (cell wire) in *namespace-load-references*
                     collect (vector (frontend-owner cell) wire)) 'vector) s))
    (with-open-file (s (concatenate 'string out "setf-bindings.json") :direction :output :if-exists :supersede)
      (ccl::namespace-json
       (coerce (loop for (symbol . id) in (copy-list *pool-symbol-owners*)
                     for name = (gethash symbol ccl::%setf-function-name-inverses%)
                     when name collect (vector (frontend-owner name) id)) 'vector) s))
    (frontend-write-owners out)
    (format t "NAMESPACE-EXTENSION-PASS ~d~%" (length all))))
(ccl:quit)
