(defpackage :wasm32-compiler (:use :cl))
(in-package :ccl)
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "../namespace-primitives/json.lisp"))
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "probes.lisp"))

(defun namespace-native-value (value stream)
  (cond ((and (integerp value) (not (<= -536870912 value 536870911)))
         (format stream "{\"integer\":\"~d\"}" value))
        ((or (null value) (eq value t) (integerp value))
         (namespace-json value stream))
        ((consp value)
         (write-char #\[ stream)
         (namespace-native-value (car value) stream)
         (write-char #\, stream)
         (namespace-native-value (cdr value) stream)
         (write-char #\] stream))
        ((symbolp value)
         (write-string "{\"symbol\":" stream)
         (namespace-json (concatenate 'string (package-name (symbol-package value)) "::" (symbol-name value)) stream)
         (write-char #\} stream))
        ((stringp value)
         (let* ((root (getenv "NAMESPACE_ROOT"))
                (path (if (and (>= (length value) (length root))
                               (string= root value :end2 (length root)))
                        (subseq value (length root)) value)))
           (write-string "{\"string\":" stream)
           (namespace-json path stream)
           (write-char #\} stream)))
        ((characterp value)
         (format stream "{\"character\":~d}" (char-code value)))
        ((typep value '(simple-array (unsigned-byte 8) (*)))
         (write-string "{\"octets\":" stream)
         (namespace-json value stream)
         (write-char #\} stream))
        ((simple-vector-p value)
         (write-string "{\"vector\":[" stream)
         (dotimes (i (length value))
           (unless (zerop i) (write-char #\, stream))
           (namespace-native-value (svref value i) stream))
         (write-string "]}" stream))
        (t (error "Unsupported namespace observation: ~s" value))))

(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "binary-cases.lisp"))
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "character-cases.lisp"))
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "readonly-cases.lisp"))
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "abi-cases.lisp"))
(load (concatenate 'string (getenv "NAMESPACE_SOURCE") "foreign-cases.lisp"))

;; Run the native implementation with the already registered Wasm ABI's
;; 32-bit word size. This descriptor has no interface database directory.
(defun wasm32-compiler::namespace-foreign-initialize ()
  (setq *host-ftd* (make-ftd :interface-package-name "WASM32-OS"
                           :attributes '(:bits-per-word 32)))
  (install-standard-foreign-types *host-ftd*)
  t)

(let ((*host-ftd* *host-ftd*))
  (with-open-file (s (concatenate 'string (getenv "NAMESPACE_NATIVE") ".foreign")
                     :direction :output :if-exists :supersede)
    (namespace-native-value (wasm32-compiler::namespace-foreign-check) s)
    (terpri s)))

(cwd (concatenate 'string (getenv "NAMESPACE_ROOT") "/ccl/"))
(setup-initial-translations)
(setq *default-pathname-defaults* (native-to-directory-pathname (current-directory-name)))
(let ((values (multiple-value-list (wasm32-compiler::namespace-check nil))))
  (with-open-file (s (getenv "NAMESPACE_NATIVE") :direction :output :if-exists :supersede)
    (write-char #\[ s)
    (loop for value in values for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (namespace-native-value value s))
    (write-char #\] s) (terpri s)))
(ccl:quit)
