(in-package :wasm32-compiler)
(defun namespace-smoke-check (image)
  (declare (ignore image))
  (let ((*default-pathname-defaults*
          (ccl::native-to-directory-pathname (ccl::current-directory-name)))
        (ccl::*elements-per-buffer* 2048)
        (ccl::*canonical-line-termination-conventions* '((:unix . nil))))
    (list (namestring (probe-file "a.bin"))
          (probe-file "absent")
          (namestring (truename "./a.bin"))
          (with-open-file (s "a.bin" :element-type '(unsigned-byte 8))
            (let ((buffer (make-array 12 :element-type '(unsigned-byte 8) :initial-element 219)))
              (list (streamp s) (stream-element-type s) (open-stream-p s)
                    (file-length s) (read-byte s)
                    (read-sequence buffer s :start 2 :end 10)
                    (coerce buffer 'list) (file-position s)
                    (file-position s 0) (read-byte s)))))))

(defun namespace-check (image)
  (list (namespace-smoke-check image) (namespace-binary-cases)
        (namespace-character-cases) (namespace-readonly-cases)
        (namespace-abi-cases)))
