;;;-*- Mode: Lisp; Package: CCL -*-
;;;
;;; Minimal WASM32 backend stub.

(in-package "CCL")

(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "NXENV")
  (require "WASMENV"))

(defun wasm2-unimplemented (&rest args)
  (declare (ignore args))
  (error "WASM backend codegen is not implemented yet."))

(defvar *wasm2-specials* nil)

(next-nx-defops)
(let* ((newsize (%i+ (next-nx-num-ops) 10))
       (old *wasm2-specials*)
       (oldsize (if old (length old) 0)))
  (unless (>= oldsize newsize)
    (let* ((v (make-array newsize :initial-element #'wasm2-unimplemented)))
      (dotimes (i oldsize (setq *wasm2-specials* v))
        (setf (svref v i) (svref old i))))))

(defun wasm2-form (seg vreg xfer form)
  (let* ((op (acode-operator form)))
    (apply (svref *wasm2-specials* (%ilogand operator-id-mask op))
           seg vreg xfer (acode-operands form))))

(eval-when (:compile-toplevel :execute :load-toplevel)
  (defmacro defwasm2 (name locative arglist &body forms)
    (multiple-value-bind (body decls)
        (parse-body forms nil t)
      (destructuring-bind (seg dest control &rest other-args) arglist
        (let* ((fun `(nfunction ,name
                      (lambda (,seg ,dest ,control ,@other-args) ,@decls
                        (block ,name ,@body)))))
          `(progn
             (record-source-file ',name 'function)
             (svset *wasm2-specials* (%ilogand #.operator-id-mask (%nx1-operator ,locative)) ,fun)))))))

(defwasm2 wasm2-nil nil (seg vreg xfer)
  (declare (ignore seg vreg xfer))
  (wasm2-emit-constant-return (target-nil-value))
  nil)

(defwasm2 wasm2-t t (seg vreg xfer)
  (declare (ignore seg vreg xfer))
  (wasm2-emit-constant-return (target-t-value))
  nil)

(defwasm2 wasm2-fixnum fixnum (seg vreg xfer value)
  (declare (ignore seg vreg xfer))
  (wasm2-emit-constant-return value)
  nil)

(defwasm2 wasm2-fixnum-add-no-overflow fixnum-add-no-overflow (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-add)
  nil)

(defwasm2 wasm2-fixnum-add-overflow fixnum-add-overflow (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-add)
  nil)

(defwasm2 wasm2-fixnum-sub-no-overflow fixnum-sub-no-overflow (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-sub)
  nil)

(defwasm2 wasm2-fixnum-sub-overflow fixnum-sub-overflow (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-sub)
  nil)

(defwasm2 wasm2-%i+ %i+ (seg vreg xfer x y &optional overflow)
  (declare (ignore seg vreg xfer x y overflow))
  (wasm2-emit-fixnum-add)
  nil)

(defwasm2 wasm2-%i- %i- (seg vreg xfer x y &optional overflow)
  (declare (ignore seg vreg xfer x y overflow))
  (wasm2-emit-fixnum-sub)
  nil)

(defwasm2 wasm2-%i* %i* (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-mul)
  nil)

(defwasm2 wasm2-fixnum-ash fixnum-ash (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-ash)
  nil)

(defwasm2 wasm2-%ilogand2 %ilogand2 (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-logand)
  nil)

(defwasm2 wasm2-%ilogior2 %ilogior2 (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-logior)
  nil)

(defwasm2 wasm2-%ilogxor2 %ilogxor2 (seg vreg xfer x y)
  (declare (ignore seg vreg xfer x y))
  (wasm2-emit-fixnum-logxor)
  nil)

(defwasm2 wasm2-%ilognot %ilognot (seg vreg xfer x)
  (declare (ignore seg vreg xfer x))
  (wasm2-emit-fixnum-lognot)
  nil)

(defwasm2 wasm2-%ineg %ineg (seg vreg xfer x)
  (declare (ignore seg vreg xfer x))
  (wasm2-emit-fixnum-neg)
  nil)

(defwasm2 wasm2-%%ineg %%ineg (seg vreg xfer x)
  (declare (ignore seg vreg xfer x))
  (wasm2-emit-fixnum-neg)
  nil)

(defwasm2 wasm2-fixnum-overflow fixnum-overflow (seg vreg xfer form)
  (destructuring-bind (op n0 n1) (acode-unwrapped-form form)
    (backend-use-operator op seg vreg xfer n0 n1 (make-nx-t))))

(defwasm2 wasm2-immediate immediate (seg vreg xfer value)
  (declare (ignore seg vreg xfer))
  (wasm2-emit-constant-return value)
  nil)

(defwasm2 wasm2-progn progn (seg vreg xfer forms)
  (if forms
    (progn
      (dolist (form (butlast forms))
        (wasm2-form seg nil nil form))
      (wasm2-form seg vreg xfer (car (last forms))))
    (wasm2-form seg vreg xfer (make-acode (%nx1-operator nil)))))

(defvar *wasm2-cur-afunc* nil)
(defvar *wasm2-vstack* 0)
(defvar *wasm2-cstack* 0)
(defvar *wasm2-target-fixnum-shift* 0)
(defvar *wasm2-target-node-shift* 0)
(defvar *wasm2-target-bits-in-word* 0)
(defvar *wasm2-target-node-size* 0)
(defvar *wasm2-ir* nil)

(defun wasm2-emit (opcode &rest operands)
  (push (cons opcode operands) *wasm2-ir*)
  nil)

(defun wasm2-emit-constant-return (value)
  (wasm2-emit :const value)
  (wasm2-emit :set-arg-z)
  (wasm2-emit :set-nargs 1)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-add ()
  (wasm2-emit :fixnum-add)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-sub ()
  (wasm2-emit :fixnum-sub)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-mul ()
  (wasm2-emit :fixnum-mul)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-ash ()
  (wasm2-emit :fixnum-ash)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-logand ()
  (wasm2-emit :fixnum-logand)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-logior ()
  (wasm2-emit :fixnum-logior)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-logxor ()
  (wasm2-emit :fixnum-logxor)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-lognot ()
  (wasm2-emit :fixnum-lognot)
  (wasm2-emit :return)
  nil)

(defun wasm2-emit-fixnum-neg ()
  (wasm2-emit :fixnum-neg)
  (wasm2-emit :return)
  nil)

(defconstant +wasm-const-entry-index+ 202)
(defconstant +wasm-const-export-name+ "ccl_const_entry")
(defconstant +wasm-const-module-version+ 1)
(defconstant +wasm-fixnum-add-entry-index+ 204)
(defconstant +wasm-fixnum-add-export-name+ "ccl_fixnum_add_entry")
(defconstant +wasm-fixnum-add-module-version+ 1)
(defconstant +wasm-fixnum-sub-entry-index+ 205)
(defconstant +wasm-fixnum-sub-export-name+ "ccl_fixnum_sub_entry")
(defconstant +wasm-fixnum-sub-module-version+ 1)
(defconstant +wasm-fixnum-mul-entry-index+ 206)
(defconstant +wasm-fixnum-mul-export-name+ "ccl_fixnum_mul_entry")
(defconstant +wasm-fixnum-mul-module-version+ 1)
(defconstant +wasm-fixnum-ash-entry-index+ 207)
(defconstant +wasm-fixnum-ash-export-name+ "ccl_fixnum_ash_entry")
(defconstant +wasm-fixnum-ash-module-version+ 1)
(defconstant +wasm-fixnum-logand-entry-index+ 208)
(defconstant +wasm-fixnum-logand-export-name+ "ccl_fixnum_logand_entry")
(defconstant +wasm-fixnum-logand-module-version+ 1)
(defconstant +wasm-fixnum-logior-entry-index+ 209)
(defconstant +wasm-fixnum-logior-export-name+ "ccl_fixnum_logior_entry")
(defconstant +wasm-fixnum-logior-module-version+ 1)
(defconstant +wasm-fixnum-logxor-entry-index+ 210)
(defconstant +wasm-fixnum-logxor-export-name+ "ccl_fixnum_logxor_entry")
(defconstant +wasm-fixnum-logxor-module-version+ 1)
(defconstant +wasm-fixnum-lognot-entry-index+ 211)
(defconstant +wasm-fixnum-lognot-export-name+ "ccl_fixnum_lognot_entry")
(defconstant +wasm-fixnum-lognot-module-version+ 1)
(defconstant +wasm-fixnum-neg-entry-index+ 212)
(defconstant +wasm-fixnum-neg-export-name+ "ccl_fixnum_neg_entry")
(defconstant +wasm-fixnum-neg-module-version+ 1)

(defun wasm2-push-u8 (vec byte)
  (vector-push-extend (logand byte #xff) vec)
  vec)

(defun wasm2-emit-uleb (vec value)
  (let ((v value))
    (loop
      (let* ((byte (logand v #x7f))
             (rest (ash v -7)))
        (if (zerop rest)
          (progn
            (wasm2-push-u8 vec byte)
            (return))
          (progn
            (wasm2-push-u8 vec (logior byte #x80))
            (setf v rest)))))))
  vec)

(defun wasm2-emit-sleb32 (vec value)
  (let ((v value))
    (loop
      (let* ((byte (logand v #x7f))
             (sign-bit (logand byte #x40))
             (rest (ash v -7))
             (done (or (and (zerop rest) (zerop sign-bit))
                       (and (= rest -1) (not (zerop sign-bit))))))
        (when (not done)
          (setf byte (logior byte #x80)))
        (wasm2-push-u8 vec byte)
        (when done
          (return))
        (setf v rest))))
  vec)

(defun wasm2-emit-bytes (vec bytes)
  (dolist (b bytes vec)
    (wasm2-push-u8 vec b)))

(defun wasm2-emit-string (vec string)
  (let* ((octets (map 'vector #'char-code string)))
    (wasm2-emit-uleb vec (length octets))
    (dotimes (i (length octets) vec)
      (wasm2-push-u8 vec (aref octets i)))))

(defun wasm2-section (id contents)
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-push-u8 out id)
    (wasm2-emit-uleb out (length contents))
    (dotimes (i (length contents) out)
      (wasm2-push-u8 out (aref contents i)))))

(defun wasm2-const-module-bytes (const-value)
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    ;; Module header
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    ;; Types: [0] (i32) -> (), [1] () -> ()
    (wasm2-emit-uleb types 2)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x7f)
    (wasm2-emit-uleb types 0)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    ;; Imports: ccl.wasm_return_constant (func type 0)
    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_constant")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    ;; Function section: one function of type 1
    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 1)

    ;; Export: ccl_const_entry -> func index 1 (after import)
    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-const-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    ;; Code: local decls = 0, body = i32.const <value>; call 0; end
    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0) ; locals
      (wasm2-push-u8 body #x41)
      (wasm2-emit-sleb32 body (logand const-value #xffffffff))
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-add-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_add")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-add-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-sub-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_sub")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-sub-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-mul-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_mul")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-mul-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-ash-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_ash")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-ash-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-logand-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_logand")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-logand-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-logior-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_logior")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-logior-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-logxor-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_logxor")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-logxor-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-lognot-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_lognot")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-lognot-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-fixnum-neg-module-bytes ()
  (let* ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (types (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (imports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (funcs (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (exports (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (code (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (wasm2-emit-bytes out '(0 #x61 #x73 #x6d 1 0 0 0))

    (wasm2-emit-uleb types 1)
    (wasm2-push-u8 types #x60)
    (wasm2-emit-uleb types 0)
    (wasm2-emit-uleb types 0)

    (wasm2-emit-uleb imports 1)
    (wasm2-emit-string imports "ccl")
    (wasm2-emit-string imports "wasm_return_fixnum_neg")
    (wasm2-push-u8 imports 0)
    (wasm2-emit-uleb imports 0)

    (wasm2-emit-uleb funcs 1)
    (wasm2-emit-uleb funcs 0)

    (wasm2-emit-uleb exports 1)
    (wasm2-emit-string exports +wasm-fixnum-neg-export-name+)
    (wasm2-push-u8 exports 0)
    (wasm2-emit-uleb exports 1)

    (let* ((body (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x10)
      (wasm2-emit-uleb body 0)
      (wasm2-push-u8 body #x0b)
      (wasm2-emit-uleb code 1)
      (wasm2-emit-uleb code (length body))
      (dotimes (i (length body))
        (wasm2-push-u8 code (aref body i))))

    (dolist (section (list (wasm2-section 1 types)
                           (wasm2-section 2 imports)
                           (wasm2-section 3 funcs)
                           (wasm2-section 7 exports)
                           (wasm2-section 10 code))
                     out)
      (dotimes (i (length section))
        (wasm2-push-u8 out (aref section i))))))

(defun wasm2-box-fixnum (value)
  (ash value *wasm2-target-fixnum-shift*))

(defun wasm2-make-const-function (entry-index const-value &optional (lfun-bits 0))
  (let* ((entry-fixnum (wasm2-box-fixnum entry-index))
         (function (%alloc-misc 4 target::subtag-function)))
    (setf (uvref function 0) entry-fixnum
          (uvref function 1) entry-fixnum
          (uvref function 2) const-value
          (uvref function 3) lfun-bits)
    function))

(defun wasm2-const-ir-value (ir)
  (when (and (= (length ir) 4)
             (eq (caar ir) :const)
             (eq (caar (cdr ir)) :set-arg-z)
             (eq (caar (cddr ir)) :set-nargs)
             (eq (caar (cdddr ir)) :return))
    (values (cadar ir) t)))

(defun wasm2-fixnum-add-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-add)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-sub-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-sub)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-mul-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-mul)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-ash-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-ash)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-logand-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-logand)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-logior-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-logior)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-logxor-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-logxor)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-lognot-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-lognot)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-fixnum-neg-ir-p (ir)
  (and (= (length ir) 2)
       (eq (caar ir) :fixnum-neg)
       (eq (caar (cdr ir)) :return)))

(defun wasm2-const-lfun-bits (afunc)
  (let* ((lambda-form (afunc-lambdaform afunc)))
    (when (and (consp lambda-form) (consp (cdr lambda-form)))
      (or (encode-lambda-list (cadr lambda-form)) 0))))

(defun wasm2-compile (afunc &optional lambda-form)
  (declare (ignore lambda-form))
  (dolist (a (afunc-inner-functions afunc))
    (unless (afunc-lfun a)
      (wasm2-compile a (afunc-lambdaform a))))
  (let* ((*wasm2-cur-afunc* afunc)
         (*wasm2-vstack* 0)
         (*wasm2-cstack* 0)
         (*wasm2-target-fixnum-shift* (arch::target-fixnum-shift (backend-target-arch *target-backend*)))
         (*wasm2-target-node-shift* (arch::target-word-shift (backend-target-arch *target-backend*)))
         (*wasm2-target-bits-in-word* (arch::target-nbits-in-word (backend-target-arch *target-backend*)))
         (*wasm2-target-node-size* (arch::target-lisp-node-size (backend-target-arch *target-backend*)))
         (*backend-vinsns* (backend-p2-vinsn-templates *target-backend*))
         (*backend-node-regs* wasm-node-regs)
         (*backend-node-temps* wasm-temp-node-regs)
         (*available-backend-node-temps* wasm-temp-node-regs)
         (*backend-imm-temps* wasm-imm-regs)
         (*available-backend-imm-temps* wasm-imm-regs)
         (*backend-fp-temps* wasm-temp-fp-regs)
         (*available-backend-fp-temps* wasm-temp-fp-regs)
         (*backend-crf-temps* wasm-cr-fields)
         (*available-backend-crf-temps* wasm-cr-fields)
         (*wasm2-ir* nil))
    (declare (ignore *wasm2-cur-afunc* *wasm2-vstack* *wasm2-cstack*
                     *wasm2-target-fixnum-shift* *wasm2-target-node-shift*
                     *wasm2-target-bits-in-word* *wasm2-target-node-size*
                     *backend-vinsns* *backend-node-regs* *backend-node-temps*
                     *available-backend-node-temps* *backend-imm-temps*
                     *available-backend-imm-temps* *backend-fp-temps*
                     *available-backend-fp-temps* *backend-crf-temps*
                     *available-backend-crf-temps*))
    (backend-apply-acode (afunc-acode afunc) nil nil $backend-return)
    (let* ((ir (nreverse *wasm2-ir*)))
      (multiple-value-bind (const-value const-p) (wasm2-const-ir-value ir)
        (setf (afunc-lfun-info afunc)
              (list* 'wasm-ir ir
                   (if const-p
                     (list* 'wasm-const-value const-value
                            'wasm-entry-index +wasm-const-entry-index+
                            (afunc-lfun-info afunc))
                     (afunc-lfun-info afunc))))
        (when const-p
          (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
            (setf (afunc-argsword afunc) bits)
            (setf (afunc-lfun afunc)
                  (wasm2-make-const-function +wasm-const-entry-index+ const-value bits))
            (setf (afunc-lfun-info afunc)
                  (list* 'wasm-module-bytes (wasm2-const-module-bytes const-value)
                         'wasm-module-export +wasm-const-export-name+
                         'wasm-module-version +wasm-const-module-version+
                         (afunc-lfun-info afunc))))
          (return-from wasm2-compile afunc))))
      (when (wasm2-fixnum-add-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-add-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-add-module-bytes)
                       'wasm-module-export +wasm-fixnum-add-export-name+
                       'wasm-module-version +wasm-fixnum-add-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc)))
      (when (wasm2-fixnum-sub-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-sub-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-sub-module-bytes)
                       'wasm-module-export +wasm-fixnum-sub-export-name+
                       'wasm-module-version +wasm-fixnum-sub-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc)))
      (when (wasm2-fixnum-mul-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-mul-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-mul-module-bytes)
                       'wasm-module-export +wasm-fixnum-mul-export-name+
                       'wasm-module-version +wasm-fixnum-mul-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-ash-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-ash-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-ash-module-bytes)
                       'wasm-module-export +wasm-fixnum-ash-export-name+
                       'wasm-module-version +wasm-fixnum-ash-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-logand-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-logand-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-logand-module-bytes)
                       'wasm-module-export +wasm-fixnum-logand-export-name+
                       'wasm-module-version +wasm-fixnum-logand-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-logior-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-logior-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-logior-module-bytes)
                       'wasm-module-export +wasm-fixnum-logior-export-name+
                       'wasm-module-version +wasm-fixnum-logior-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-logxor-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-logxor-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-logxor-module-bytes)
                       'wasm-module-export +wasm-fixnum-logxor-export-name+
                       'wasm-module-version +wasm-fixnum-logxor-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-lognot-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-lognot-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-lognot-module-bytes)
                       'wasm-module-export +wasm-fixnum-lognot-export-name+
                       'wasm-module-version +wasm-fixnum-lognot-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
      (when (wasm2-fixnum-neg-ir-p ir)
        (let* ((bits (or (wasm2-const-lfun-bits afunc) 0)))
          (setf (afunc-argsword afunc) bits)
          (setf (afunc-lfun afunc)
                (wasm2-make-const-function +wasm-fixnum-neg-entry-index+ 0 bits))
          (setf (afunc-lfun-info afunc)
                (list* 'wasm-module-bytes (wasm2-fixnum-neg-module-bytes)
                       'wasm-module-export +wasm-fixnum-neg-export-name+
                       'wasm-module-version +wasm-fixnum-neg-module-version+
                       (afunc-lfun-info afunc))))
        (return-from wasm2-compile afunc))
    (wasm2-unimplemented)))

(provide "WASM2")
