"""Materialize the transitive startup walk without module membership fan-outs."""
from collections import Counter
from copy import deepcopy
from pathlib import Path
from payloads import read,save,require
from bodies import make,apply,node,edge
from seed_graph import snapshot,SNAP,BODY
HERE=Path(__file__).resolve().parent


def run(a):
    a.output.mkdir(parents=True,exist_ok=False)
    require(read(a.walk/'summary.json')['status']=='PASS','STARTUP_TRANSITIVE_WALK')
    reached={tuple(x) for x in read(a.walk/'reached.json.gz')};codes={i for k,i in reached if k=='function'}
    selection=read(a.bodies/'selection.json');selection['requested']=sorted(codes)
    fs={f['id']:f for f in read(a.bodies/'functions.json.gz')}
    selection['literal_instances']=[dict(owner=i,instance=x['function'],prototype=fs[x['function']]['prototype'])
        for i in sorted(codes) for x in fs[i]['literals'] if isinstance(x,dict) and 'function' in x and x['function']!=fs[x['function']]['prototype']]
    seed=snapshot(selection,fs);base=read(a.base)
    current=dict(base,nodes=seed['nodes'],edges=seed['edges'],seeds=seed['roots'],observed_modules=[],unobserved_modules=[],initializers=[],
        profile=base['profile']+'; transitive native startup body projection, not an accepted census',
        seed_review='Approved revision-2 recipe, actual same-process roots; binding and registry lifetimes remain open.')
    matches=[m for m in read(a.walk/'matches.json.gz') if m['bootstrap_code'] in codes]
    ir=read(a.walk/'ir.json.gz');deferred=read(a.bodies/'deferred.json.gz')['placeholders']
    delta=make(current,matches,ir['functions'],ir['calls'],deferred=deferred,namespace=BODY,
               anchor_prefix=SNAP+'function:',anchor_evidence='startup-live/body/',references=ir['references'])
    current=apply(current,delta);ids={n['id'] for n in current['nodes']};links=[]
    for b in read(a.walk/'bindings.json.gz'):
        ident=BODY+'binding:'+str(b['symbol']);require(ident in ids,'STARTUP_TRANSITIVE_CELL')
        initial=b['initial']
        if initial and initial['role']=='FUNCTION':
            target=SNAP+'function:'+str(initial['prototype']);require(target in ids,'STARTUP_TRANSITIVE_VALUE')
            links.append(edge(ident,[target],'startup-live/cell-initial/'+str(b['symbol'])))
        # Keep the unresolved value-version edge generated by the body tool.
        require(any(e['from']==ident and e['resolution']=='unresolved' for e in current['edges']),
                'STARTUP_TRANSITIVE_FUTURE_ERASED')
    current['edges']+=links
    runtime=read(a.walk/'runtime-bodies.json.gz');ns=[];es=[];replacements=[]
    for r in runtime:
        code=r['function'];ident=SNAP+'runtime:'+str(code);ev='startup-live/runtime/'+str(code)
        ns.append(node(ident,ev,'Observed native '+r['kind']+'; target code and data qualification remain open.',True))
        replacements.append(edge(SNAP+'function:'+str(code),[ident],'startup-live/body/'+str(code),'compile'))
        for d in r['transfers']:
            for t in d['transfers']:
                if t['kind'] in ('LOCAL_LABEL','RETURN'):continue
                key=str(d['definition'])+'/'+str(t['parsed'])
                target=ident+':transfer:'+key
                ns.append(node(target,ev+'/transfer/'+key,t['kind']+' requires explicit target lowering.',True))
                es.append(edge(ident,[target],ev+'/uses/'+key))
                if t['kind'].startswith('UNRESOLVED'):
                    es.append(edge(target,[],ev+'/targets/'+key,complete=False))
    current=apply(current,dict(nodes=ns,edges=es,replacements=replacements));ids.update(n['id'] for n in ns)
    for state in read(a.walk/'registry-snapshots.json.gz'):
        ident=SNAP+'registry:'+str(state['gf']);require(ident not in ids,'STARTUP_TRANSITIVE_REGISTRY_DUPLICATE');ids.add(ident)
        current['nodes'].append(node(ident,'startup-live/registry/'+str(state['gf']),
            'Exact initial methods and dcode; caches, class state and later registrations remain unbounded.',True))
        current['edges'].append(edge(SNAP+'function:'+str(state['gf']),[ident],'startup-live/registry-use/'+str(state['gf'])))
        targets={fs[state['dcode']]['prototype']}|{fs[m['function']]['prototype'] for m in state['methods']}
        require(targets<=codes,'STARTUP_TRANSITIVE_METHOD_POPULATION')
        current['edges'].append(edge(ident,[SNAP+'function:'+str(i) for i in targets],'startup-live/registry-values/'+str(state['gf'])))
        current['edges'].append(edge(ident,[],'startup-live/registry-future/'+str(state['gf']),complete=False))
    from support import load_module
    check=load_module('startup_transitive_contract',HERE.parents[3]/'doc/WASM/tools/check-census.py').validate
    errors=check(current);bad=[e for e in errors if not e.startswith(('unresolved reachable edge from ','unimplemented reachable node '))]
    require(not bad,'STARTUP_TRANSITIVE_STRUCTURE '+str(bad[:3]))
    require(not ({n['id'] for n in base['nodes']}&ids),'STARTUP_TRANSITIVE_COLLISION')
    combined=dict(base,nodes=base['nodes']+current['nodes'],edges=base['edges']+current['edges'],seeds=base['seeds']+current['seeds'])
    save(a.output/'seed-graph.json.gz',current);save(a.output/'census.json.gz',combined)
    missing=[e for e in current['edges'] if e['evidence'].startswith('startup-live/body/') and e['resolution']=='unresolved']
    summary=dict(status='PASS',native_functions=len(codes),source_bodies=len(matches),runtime_bodies=len(runtime),
        unresolved_body_edges=len(missing),initial_function_cells=len(links),nodes=len(current['nodes']),edges=len(current['edges']),
        census_status='BLOCKED',historical_roots_retired=0,exhaustive_binding_versions=False)
    save(a.output/'summary.json',summary);print(summary,flush=True)


if __name__=='__main__':
    import argparse,traceback
    p=argparse.ArgumentParser(description=__doc__)
    for n in ('walk','bodies','base','output'):p.add_argument('--'+n,type=Path,required=True)
    a=p.parse_args()
    try:run(a)
    except BaseException:
        if a.output.exists():
            (a.output/'failure.txt').write_text(traceback.format_exc());(a.output/'seed_transitive_graph.py').write_bytes(Path(__file__).read_bytes())
        raise
