(in-package "CL-USER")
(defvar *closure-identities*)
(defvar *call-refusals*) (defvar *call-sources*) (defvar *call-cases*) (defvar *call-functions*)
(defun call-token (value objects)
  (cond ((null value) "nil") ((eq value t) "t") ((keywordp value) (concatenate 'string ":" (string-downcase (symbol-name value)))) ((integerp value) value)
        ((symbolp value) (concatenate 'string "s:" (string-downcase (symbol-name value))))
        ((rassoc value *call-functions* :test #'eq) (concatenate 'string "f:" (car (rassoc value *call-functions* :test #'eq))))
        ((functionp value)
         (or (cdr (assoc value *closure-identities* :test #'eq))
             (let ((name (format nil "c~d" (length *closure-identities*))))
               (push (cons value name) *closure-identities*) name)))
        ((position value objects :test #'eq) (format nil "n~d" (position value objects :test #'eq)))
        ((consp value) (format nil "n~d" (vector-push-extend value objects)))
        (t (error "Unknown value ~s" value))))
(defun call-json-token (s value) (if (integerp value) (princ value s) (format s "~s" value)))
(defun call-native-case-raw (s row)
  (destructuring-bind (id name nodes args) row
    (let ((*closure-identities* nil) (objects (make-array (length nodes) :adjustable t :fill-pointer (length nodes))) (values nil) (status "RETURN"))
      (dotimes (i (length nodes)) (setf (aref objects i) (cons nil nil)))
      (labels ((decode (v)
                 (cond ((equal v "nil") nil) ((equal v "t") t)
                       ((and (stringp v) (eql (char v 0) #\:)) (intern (string-upcase (subseq v 1)) "KEYWORD"))
                       ((and (stringp v) (eql (char v 0) #\n)) (aref objects (parse-integer v :start 1)))
                       ((and (stringp v) (eql (char v 0) #\s)) (intern (string-upcase (subseq v 2)) "WASM32-COMPILER"))
                       ((stringp v) (cdr (assoc (subseq v 2) *call-functions* :test #'equal))) (t v))))
        (loop for pair in nodes for i from 0 do (setf (car (aref objects i)) (decode (first pair)) (cdr (aref objects i)) (decode (second pair))))
        (handler-case
            (setq values (multiple-value-list (apply (cdr (assoc name *call-functions* :test #'equal)) (mapcar #'decode args))))
          (type-error (c) (setq status (if (subtypep 'function (type-error-expected-type c)) "DESIGNATOR" "TYPE")))
          (undefined-function () (setq status "DESIGNATOR"))
          (control-error () (setq status "CONTROL"))
          (program-error () (setq status "ARITY"))))
      (format s "{\"id\":~s,\"status\":~s,\"values\":[" id status)
      (loop for value in values for i from 0 do (unless (zerop i) (write-char #\, s)) (call-json-token s (call-token value objects)))
      (write-string "],\"nodes\":[" s)
      (loop for i from 0 while (< i (length objects)) do (unless (zerop i) (write-char #\, s)) (write-char #\[ s)
        (call-json-token s (call-token (car (aref objects i)) objects)) (write-char #\, s)
        (call-json-token s (call-token (cdr (aref objects i)) objects)) (write-char #\] s))
      (write-string "]}" s))))
(defun call-native-case (s row)
  (let* ((bindings (fifth row))
         (saved (mapcar (lambda (pair) (let ((symbol (intern (string-upcase (first pair)) "WASM32-COMPILER"))) (cons symbol (symbol-function symbol)))) bindings)))
    (unwind-protect
      (progn
        (dolist (pair bindings) (setf (symbol-function (intern (string-upcase (first pair)) "WASM32-COMPILER")) (cdr (assoc (second pair) *call-functions* :test #'equal))))
        (call-native-case-raw s (subseq row 0 4)))
      (dolist (pair saved) (setf (symbol-function (car pair)) (cdr pair))))))
(load (merge-pathnames "root-contracts.lisp" *load-pathname*))
(let ((out (ccl:getenv "CALL_OUTPUT")))
  (load (ccl:getenv "CALL_CASES")) (setq *call-functions* nil)
  (let ((*package* (find-package "WASM32-COMPILER")))
    (dolist (row *call-sources*)
      (let ((fn (compile nil (read-from-string (second row)))))
        (setf (symbol-function (intern (string-upcase (first row)) *package*)) fn)
        (push (cons (first row) fn) *call-functions*))))
  (with-open-file (*root-contract-stream* (concatenate 'string out "root-ir.json") :direction :output :if-exists :error)
   (let ((*root-contract-first* t))
    (write-char #\[ *root-contract-stream*)
  (with-open-file (index (concatenate 'string out "entries.json") :direction :output :if-exists :error)
    (write-char #\[ index)
    (let ((first t))
      (dolist (row *call-sources*)
        (let ((module (compile-with-root-witness (second row) (first row) (mapcar #'first *call-sources*))))
          (dolist (entry (cons module (getf module :children)))
            (unless first (write-char #\, index)) (setq first nil)
            (format index "{\"name\":~s,\"parent\":~s,\"bound_words\":~d,\"captures\":~d}" (getf entry :name) (first row) (getf entry :bound-words) (getf entry :captures))
            (with-open-file (s (concatenate 'string out (getf entry :name) ".wat") :direction :output :if-exists :error) (write-string (getf entry :wat) s))))))
    (write-char #\] index))
    (write-char #\] *root-contract-stream*)))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
    (write-char #\[ s) (loop for c in *call-cases* for i from 0 do (unless (zerop i) (write-char #\, s)) (call-native-case s c)) (write-char #\] s))
  (with-open-file (s (concatenate 'string out "refusals.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for (name source) in *call-refusals* for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (let ((refused nil))
        (handler-case (wasm32-compiler::compile-call-module source name (mapcar #'first *call-sources*))
          (wasm32-compiler::unsupported-wasm32-code () (setq refused t)))
        (assert refused) (format s "{\"name\":~s,\"status\":\"REJECTED\"}" name)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "observe_entry.wat") :direction :output :if-exists :error)
    (write-string "(module (import \"env\" \"entry\" (func $entry (param i32 i32) (result i32 i32))) (import \"env\" \"observe\" (func $observe (param i32))) (func (export \"entry\") (param $self i32) (param $n i32) (result i32 i32) (call $observe (local.get $self)) (return_call $entry (local.get $self) (local.get $n))))" s))
  (with-open-file (s (concatenate 'string out "observe_tail.wat") :direction :output :if-exists :error)
    (write-string "(module (import \"env\" \"entry\" (func $entry (param i32 i32 i32) (result i32 i32))) (import \"env\" \"observe\" (func $observe (param i32 i32 i32))) (func (export \"entry\") (param $self i32) (param $n i32) (param $context i32) (result i32 i32) (call $observe (local.get $self) (local.get $n) (local.get $context)) (return_call $entry (local.get $self) (local.get $n) (local.get $context))))" s))
  (format t "S1-B-CALL-COMPILE-PASS~%") (ccl:quit))
