(in-package :wasm32-compiler)
(defparameter *native-cpu-source*
 (let ((*package* (find-package "CCL")))
  (with-open-file (s "level-1/linux-files.lisp")
   (file-position s CPU_SOURCE_POSITION) (read s))))
(assert (and (eq (first *native-cpu-source*) 'defun)
             (eq (second *native-cpu-source*) 'ccl::cpu-count)
             (null (third *native-cpu-source*))
             (= (length *native-cpu-source*) 4)))
(let* ((body (fourth *native-cpu-source*)) (write (third body)))
 (assert (and (= (length body) 3) (eq (first body) 'or)
              (eq (second body) 'ccl::*cpu-count*) (= (length write) 3)
              (eq (first write) 'setq) (eq (second write) 'ccl::*cpu-count*))))
(defun cpu-with-owner-value (cpu)
 (let ((body (copy-tree (fourth *native-cpu-source*))))
  (setf (third (third body)) cpu) body))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "cpu-source.lisp") :direction :output :if-exists :error)
 (print *native-cpu-source* s))
;; Independent witness: untouched registered callback in the pinned image.
;; No rebinding of CPU-COUNT or substitutions on this path.
(let* ((matches (remove-if-not (lambda (f)(eq (ccl::function-name f) 'ccl::spin-count)) ccl::*lisp-user-pointer-functions*))
       (globals '(ccl::*cpu-count* ccl::*spin-lock-tries* ccl::*spin-lock-timeouts*))
       (saved (mapcar #'symbol-value globals)))
 (assert (= (length matches) 1))
 (unwind-protect
  (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-cpu-probe.json") :direction :output :if-exists :error)
   (write-char #\[ s)
   (loop for cache in '(nil 1 2) for i from 0 do
    (unless (zerop i)(write-char #\, s))
    (set 'ccl::*cpu-count* cache)(set 'ccl::*spin-lock-tries* 37)(set 'ccl::*spin-lock-timeouts* 91)
    (let* ((returned (multiple-value-list (funcall (first matches)))) (cpu ccl::*cpu-count*))
     (assert (and (integerp cpu)(plusp cpu)))
     (when cache (assert (eql cache cpu)))
     (assert (equal returned '(ccl::*spin-lock-timeouts*)))
     (assert (= ccl::*spin-lock-tries* (if (= cpu 1) 1 1024)))
     (assert (= ccl::*spin-lock-timeouts* 0))
     (format s "{\"cache_before\":")(json-val s cache)
     (format s ",\"values\":")(json-val s returned)
     (format s ",\"globals\":")(json-val s (mapcar #'symbol-value globals))(write-char #\} s)))
   (write-char #\] s))
  (loop for g in globals for v in saved do(set g v)))
 (assert (equal saved (mapcar #'symbol-value globals))))
