#!/usr/bin/env python3
"""Use the immutable reviewed code capture; change only owner admission."""
import argparse,hashlib,importlib.util,json,shutil,subprocess,sys
from pathlib import Path
from derive import HERE,BASE,owner,harness,replace
ROOT=HERE.parents[3];PARENT='2026-09-20-stage1-initialization-r1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
def save(p,v):p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
def command(args,log):
 save(log.with_suffix('.command.json'),list(map(str,args)))
 with log.open('w') as f:subprocess.run(list(map(str,args)),stdout=f,stderr=subprocess.STDOUT,check=True,timeout=120)
def load(name):
 spec=importlib.util.spec_from_file_location('init_'+name,BASE/(name+'.py'));m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
def run(e,out):
 out.mkdir(parents=True,exist_ok=False);p=e/PARENT
 for n,h in read(p/'source-pins.json').items():assert sha(ROOT/n)==h,n
 for row in read(p/'packet.json')['files']:assert sha(p/row['path'])==row['sha256'],row['path']
 for t in read(p/'toolchain.json')['tools']:assert sha(Path(t['path']))==t['sha256']
 # Unchanged generated bytes and native answers come from the reviewed packet.
 for name in ['compiled','malformed']:shutil.copytree(p/'execution'/name,out/name)
 for f in (p/'execution').iterdir():
  if f.is_file() and f.suffix in ['.mjs','.wasm']:shutil.copy(f,out/f.name)
 shutil.copy(ROOT/'doc/WASM/contracts/tcr.v2.json',out/'tcr.json')
 (out/'owner.mjs').write_text(owner());(out/'check.mjs').write_text(harness());shutil.copy(HERE/'directed.mjs',out/'directed.mjs')
 command(['/usr/local/bin/node',out/'check.mjs',out,out/'execution.json'],out/'execution.log')
 assert read(out/'execution.json')==read(p/'execution/execution.json'),'inherited outcomes'
 load('controls').run(out,command,read,save)
 assessment=load('assess');save(out/'assessment.json',assessment.check(out));save(out/'publication-controls.json',assessment.controls(out))
 command(['/usr/local/bin/node',out/'directed.mjs',out,out/'directed.json'],out/'directed.log')
 faults=[
  ('missing-capacity',"table.length>=l.tableCapacity&&tail_table.length>=l.tableCapacity",'true','actual table'),
  ('missing-tail-capacity','tail_table.length>=l.tableCapacity','true','actual table 8/0'),
  ('missing-fresh',"need(Atomics.load(state,i)===0,'CONTROL_NOT_FRESH');",';','dirty fresh byte 8'),
  ('missing-reserved',"need(Atomics.load(state,i)===0,'CONTROL_RESERVED');",';','dirty ready process byte 4'),
 ]
 results=[]
 for name,old,new,why in faults:
  d=out/'new-faults'/name;d.mkdir(parents=True)
  for f in out.iterdir():
   if f.is_file() and (f.suffix in ['.mjs','.wasm'] or f.name=='tcr.json'):shutil.copy(f,d/f.name)
  shutil.copytree(out/'compiled',d/'compiled')
  (d/'owner.mjs').write_text(replace(owner(),old,new))
  command(['/usr/local/bin/node','--check',d/'owner.mjs'],d/'syntax.log')
  try:command(['/usr/local/bin/node',d/'directed.mjs',d,d/'directed.json'],d/'fault.log')
  except subprocess.CalledProcessError:assert why in (d/'fault.log').read_text(),(name,(d/'fault.log').read_text()[-2500:])
  else:raise AssertionError(name+' escaped')
  results.append(dict(name=name,status='REJECTED',diagnostic=why))
 save(out/'new-controls.json',results)
 x=read(out/'directed.json');assert x['status']=='PASS' and [r['base'] for r in x['rows']]==[4194304,2147483648]
 for r in x['rows']:
  assert r['counts']==dict(table=20,fresh=124,reserved=160,phase=4)
  assert r['callbacks']==2 and r['larger_tables'] and r['failed_worker_terminal']
  assert r['races']==[dict(mode=m,callbacks=1,admitted=1,refused=2) for m in ['process','worker']]
 save(out/'summary.json',dict(status='PASS',inherited=read(out/'assessment.json'),owner_faults=10,publication_controls=7,new_faults=4,directed_refusals=sum(sum(r['counts'].values()) for r in x['rows']),race_workers=12,races=4,scope='Owner admission only. Compiler, native answers and five generated modules reused by reviewed packet hash; inherited outcomes identical.'))
 for n,h in read(p/'source-pins.json').items():assert sha(ROOT/n)==h,n
 print(json.dumps(read(out/'summary.json'),indent=2))
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--evidence',type=Path,required=True);a.add_argument('--output',type=Path,required=True);v=a.parse_args();run(v.evidence.resolve(),v.output.resolve())
