(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(
         ("seed_map" (lambda (done state mode previous output) (if (eq (car previous) 0) (progn (rplaca state 1) (rplaca done 101) (values (car state) (car done))) (rplaca nil 0))))
         ("seed_fatal" (lambda (done state mode previous output) (if (eq (car previous) 101) (progn (rplaca state 2) (rplaca mode 1) (rplaca done 102) (values (car state) (car done))) (rplaca nil 0))))
         ("seed_install" (lambda (done state mode previous output) (if (eq (car previous) 102) (progn (rplaca state 3) (rplaca done 103) (values (car state) (car done))) (rplaca nil 0))))
         ("define_one" (lambda (done state mode previous output) (if (eq (car previous) 103) (progn (rplaca state 4) (rplaca done 104) (values (car state) (car done))) (rplaca nil 0))))
         ("define_two" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn (rplaca state 5) (rplaca done 105) (values (car state) (car done))) (rplaca nil 0))))
         ("define_three" (lambda (done state mode previous output) (if (eq (car previous) 105) (progn (rplaca state 6) (rplaca done 106) (values (car state) (car done))) (rplaca nil 0))))
         ("define_four" (lambda (done state mode previous output) (if (eq (car previous) 106) (progn (rplaca state 7) (rplaca done 107) (values (car state) (car done))) (rplaca nil 0))))
         ("activate" (lambda (done state mode previous output) (if (eq (car previous) 107) (progn (rplaca state 8) (rplaca mode 2) (rplaca done 108) (values (car state) (car done))) (rplaca nil 0))))
         ("workload" (lambda (done state mode previous output) (if (eq (car previous) 108) (progn (rplaca state 9) (rplaca output (car state)) (rplacd output (car mode)) (rplaca done 109) (values (car state) (car done))) (rplaca nil 0))))
         ("wrong_completion" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn (rplaca state 5) (rplaca done 999) (values (car state) (car done))) (rplaca nil 0))))
         ("no_completion" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn (rplaca state 5) nil (values (car state) (car done))) (rplaca nil 0))))
         ("no_effect" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn nil (rplaca done 105) (values (car state) (car done))) (rplaca nil 0))))
         ("clobber_previous" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn (rplaca state 5) (rplaca done 105) (rplaca previous 0) (values (car state) (car done))) (rplaca nil 0))))
         ("raises" (lambda (done state mode previous output) (if (eq (car previous) 104) (progn (rplaca state 5) (rplaca nil 0) (values (car state) (car done))) (rplaca nil 0)))))))
 (dolist (row cases)
  (let ((result (compile-call-form (second row) (first row) (mapcar #'first cases))))
   (dolist (m (cons result (getf result :children)))
    (push m modules)
    (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
 (let ((state (cons 0 nil)) (mode (cons 0 nil)) (output (cons 0 0)) (previous (cons 0 nil)))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
   (format s "[")
   (loop for row in (subseq cases 0 9) for i from 0 do
    (unless (zerop i) (format s ","))
    (let* ((done (cons 0 nil))
           (v (multiple-value-list (funcall (compile nil (second row)) done state mode previous output))))
     (format s "{\"values\":[~d,~d],\"state\":~d,\"mode\":~d,\"output\":[~d,~d]}" (first v) (second v) (car state) (car mode) (car output) (cdr output))
     (setq previous done)))
   (format s "]"))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
