;;; Private, bounded DEFTYPE expansion before target membership/canonicalization.
(defpackage :ccl-target-aliases (:use :cl))
(in-package :ccl-target-aliases)
(defvar *aliases* nil)
(defvar *trace* nil)
(defvar *mode* "normal")
(defun obj (&rest xs) (apply #'ccl-target-helpers::obj xs))
(defun syntax (x) (ccl-target-helpers::syntax x))
(defun current-phase () ccl-target-predicates::*phase*)
(defun prepare-aliases ()
  (ccl-census-stub::with-target-state
   (lambda ()
    (let ((*package* (find-package :ccl-target-aliases)) (*read-eval* nil))
     (with-open-file (in (ccl:getenv "CCL_ALIAS_SOURCE") :external-format :utf-8)
      (loop for form = (read in nil :eof) until (eq form :eof) collect
       (progn
        (unless (and (eq (car form) 'deftype) (not (gethash (second form) ccl::%deftype-expanders%)))
          (error "ALIAS-SOURCE-BOUND"))
        ;; U1 EXPAND-TYPE-MACRO uses this parser and '*' optional default.
        ;; Install only in the dynamically copied table; no %DEFTYPE side effects.
        (let* ((lambda-form (ccl::parse-macro-internal (second form) (third form) (cdddr form) nil '*))
               (fn (ccl-census-macros::native-function lambda-form)))
          (setf (gethash (second form) ccl::%deftype-expanders%) fn)
          (push (cons (second form) fn) *aliases*)
          (obj "form" (syntax form) "reader" (ccl-source-traversal::context)
               "compiled" (ccl-target-helpers::bool (functionp fn)) "lambda" (syntax lambda-form))))))))))
(defun normalize-type (type leaf env)
  (let ((fuel 32))
   (labels ((walk (x ancestors depth)
     (when (> depth 64) (error "ALIAS-TYPE-DEPTH"))
     (when (member x ancestors :test #'equal) (error "ALIAS-CYCLE"))
     (let* ((name (if (consp x) (car x) x)) (entry (assoc name *aliases*))
            (answer
              (cond (entry
                     (when (minusp (decf fuel)) (error "ALIAS-EXPANSION-LIMIT"))
                     (let* ((expanded (funcall (cdr entry) (if (consp x) x (list x)) env))
                            (result (if (equal *mode* "translate-first") expanded
                                      (walk expanded (cons x ancestors) (1+ depth)))))
                       (push (obj "phase" (current-phase) "event" ccl-target-predicates::*event*
                                  "input" (syntax x) "expanded" (syntax expanded)
                                  "result" (syntax result)) *trace*)
                       result))
                    ((and (consp x) (not (equal *mode* "shallow"))
                          (member (car x) (if (equal *mode* "member-data") '(or and not member) '(or and not))))
                     (cons (car x) (mapcar (lambda (a) (walk a (cons x ancestors) (1+ depth))) (cdr x))))
                    (t (ccl-target-predicates::translate x leaf)))))
       answer)))
    (walk (if (equal *mode* "translate-first") (ccl-target-predicates::translate type leaf) type) nil 0))))
(defun build (macro optimizer target-type)
  (let ((leaf (copy-tree (cdr target-type)))
        (local (copy-tree (cdr optimizer))))
    (setf (first leaf) 'leaf-target-type)
    (setf (cddr local)
          `((let ((answer (block ccl::optimize-typep ,@(cddr local))))
              (ccl-target-predicates::row "OPTIMIZE-TYPEP" "thing" (syntax ccl::thing) "type" (syntax ccl::type)
                   "answer" (syntax answer)) answer)))
    (ccl-census-macros::native-function
     `(lambda (form env)
        (let ((ccl-target-predicates::*event* (1- ccl-source-expanders::*next-event*)))
          (flet ((native-typep (thing type environment) (cl:typep thing type environment))
                 (native-known (type environment whine) (ccl::specifier-type-if-known type environment :whine whine)))
          (labels (,leaf
                   (cl:typep (thing type &optional environment)
                     (let* ((target-type (normalize-type type #'leaf-target-type environment))
                            (answer (native-typep thing target-type environment)))
                       (ccl-target-predicates::row "TYPEP" "thing" (syntax thing) "type" (syntax type)
                            "target_type" (syntax target-type) "answer" (ccl-target-helpers::bool answer)) answer))
                   (ccl::specifier-type-if-known (type environment &key whine)
                     (let* ((target-type (if (equal *mode* "optimizer-leak")
                                             (ccl-target-predicates::translate type #'leaf-target-type)
                                             (normalize-type type #'leaf-target-type environment)))
                            (answer (native-known target-type environment whine)))
                       (ccl-target-predicates::row "SPECIFIER-TYPE-IF-KNOWN" "type" (syntax type) "target_type" (syntax target-type)
                            "known" (ccl-target-helpers::bool answer)
                            "canonical" (if answer (syntax (ccl::type-specifier answer)) :null)) answer))
                   (ccl::optimize-ctypep (thing ctype) (ccl-target-predicates::ctype-guard thing ctype))
                   ,local)
            (funcall (function ,(ccl::parse-macro-1 (second macro) (third macro) (cdddr macro))) form env))))))))

(defparameter *cases*
 '(("small-max" 536870911 target-small)
   ("small-boxed" 536870912 target-small)
   ("small-min" -536870912 target-small)
   ("small-negative-boxed" -536870913 target-small)
   ("large-boxed" 536870912 target-large)
   ("large-immediate" 536870911 target-large)
   ("chain-boxed" 536870912 small-chain)
   ("nested-or-boxed" 536870912 maybe-small)
   ("nested-or-symbol" :foo maybe-small)
   ("nested-not-boxed" 536870912 outside-small)
   ("parameter-small" 536870912 (choose-number))
   ("parameter-large" 536870912 (choose-number t))
   ("member-literal" target-small literal-small)
   ("explicit-wide" 536870912 explicit-wide)
   ("outer-or" 536870912 (or symbol target-small))
   ("outer-not" 536870912 (not target-small))))
(defparameter *optimizer-cases*
 '(("recursive-or" (or symbol target-small))
   ("expanded-or" maybe-small)
   ("recursive-and" (and integer (not target-small)))
   ("chain" small-chain)
   ("parameter" (choose-number t))))
(defun optimizer-probes (entry)
  (loop for (name type) in *optimizer-cases* collect
   (let* ((ccl-target-predicates::*phase* name)
          (ccl-source-expanders::*next-event* 0)
          (input `(typep ccl::x ',type))
          (expanded (funcall (third entry) input nil))
          ;; Native evaluation witnesses the expansion's semantics only, not Wasm lowering.
          (fn (ccl-census-macros::native-function `(lambda (ccl::x) ,expanded))))
     (obj "name" name "type" (syntax type) "input" (syntax input) "expanded" (syntax expanded)
          "values" (mapcar #'syntax '(-536870913 -536870912 536870911 536870912 :foo))
          "answers" (mapcar (lambda (v) (ccl-target-helpers::bool (funcall fn v)))
                            '(-536870913 -536870912 536870911 536870912 :foo))))))
(defun refusal-probes (entry)
  (let ((*mode* "normal"))
   (loop for type in '(cyclic growing) collect
    (let ((ccl-target-predicates::*phase* (symbol-name type)) (ccl-source-expanders::*next-event* 0))
     (handler-case
       (progn (funcall (third entry) `(typep '0 ',type) nil) (error "ALIAS-REFUSAL-ESCAPED"))
       (error (e) (obj "type" (syntax type) "reason" (princ-to-string e))))))))
(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (ccl-source-expanders::*registry* nil) (ccl-source-expanders::*compiled* nil)
        (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
        (ccl-source-expanders::*literals* nil) (ccl-target-helpers::*sources* nil)
        (ccl-target-helpers::*calls* nil) (ccl-target-types::*trace* nil)
        (ccl-target-predicates::*trace* nil) (ccl-target-predicates::*mode* "normal")
        (*aliases* nil) (*trace* nil) (*mode* (or (ccl:getenv "CCL_ALIAS_MODE") "normal"))
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
        (original-table ccl::%deftype-expanders%)
        (names '(typep ccl::specifier-type-if-known ccl::optimize-typep ccl::optimize-ctypep ccl::nx-target-type ccl::type-expand ccl::%deftype)))
   (let ((globals (mapcar #'fdefinition names)) (saved-entries nil) (result nil))
    (maphash (lambda (k v) (push (cons k v) saved-entries)) original-table)
    (ccl-source-expanders::prepare)
    (dolist (r (reverse ccl-source-expanders::*registry*)) (ccl-target-helpers::ident (third r)) (ccl-target-helpers::ident (fourth r)))
    (let ((ccl::%deftype-expanders% (make-hash-table :test #'eq)))
     (maphash (lambda (k v) (setf (gethash k ccl::%deftype-expanders%) v)) original-table)
     (unwind-protect
      (flet ((source (path name) (ccl-target-helpers::read-form path name)))
       (let* ((helper (source "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
              (range (source "compiler/nx0.lisp" "defun nx1-target-fixnump"))
              (eql-form (source "compiler/optimizers.lisp" "define-compiler-macro eql"))
              (typep-form (source "compiler/nx0.lisp" "defun nx-form-typep"))
              (form-type (source "compiler/nx0.lisp" "defun nx-form-type"))
              (target-type (source "compiler/nx-basic.lisp" "defun nx-target-type"))
              (lookup (source "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
              (stream (source "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
              (vector (source "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
              (macro (source "compiler/optimizers.lisp" "define-compiler-macro typep"))
              (optimizer (source "compiler/optimizers.lisp" "defun optimize-typep"))
              (entry (ccl-target-helpers::compiler-entry 'typep)) (compiled nil))
        ;; Retain the actual U1 constructor/expansion definitions as provenance.
        (source "level-1/l1-typesys.lisp" "defmacro deftype")
        (source "level-1/l1-typesys.lisp" "defun expand-type-macro")
        (source "level-1/l1-typesys.lisp" "defun type-expand")
        (let ((definitions (prepare-aliases)))
         (ccl::clear-type-cache)
         (ccl-source-expanders::with-compiler-observation
          (lambda ()
           (setf (third (ccl-target-helpers::compiler-entry 'eql))
                 (ccl-target-types::build helper range eql-form typep-form form-type target-type "normal")
                 (third (ccl-target-helpers::compiler-entry 'ccl::basic-stream-p)) (ccl-target-helpers::build-stream lookup stream)
                 (third (ccl-target-helpers::compiler-entry 'vectorp)) (ccl-target-helpers::build-stream lookup vector)
                 compiled (if (equal *mode* "prior") (ccl-target-predicates::build macro optimizer target-type)
                            (build macro optimizer target-type))
                 (third entry) compiled)))
         (let ((ccl-target-predicates::*phase* "dumplisp")) (ccl-source-expanders::with-routing #'ccl-census-descriptions::run))
         (ccl-census-descriptions::with-descriptions
          (lambda () (ccl-census-stub::with-target-state
           (lambda ()
            (let* ((probes (mapcar #'ccl-target-predicates::probe *cases*))
                   (optimizer-probes (optimizer-probes entry))
                   ;; Refusals always use the bounded corrected implementation.
                   (refusals (refusal-probes (list 'typep "compiler-macro" (build macro optimizer target-type)))))
             (setf result
              (obj "version" 1 "definitions" definitions "sources" (reverse ccl-target-helpers::*sources*)
                   "probes" probes "optimizer_probes" optimizer-probes "refusals" refusals
                   "alias_trace" (reverse *trace*) "trace" (reverse ccl-target-predicates::*trace*)
                   "events" ccl-source-expanders::*events*
                   "selected_id" (ccl-target-helpers::ident compiled)
                   "macro_environment_qualified" :false "graph_edges_replaced" 0))))))))))
      (ccl::clear-type-cache)))
    (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                 (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                 (every #'eq globals (mapcar #'fdefinition names))
                 (eq original-table ccl::%deftype-expanders%)
                 (= (hash-table-count original-table) (length saved-entries))
                 (every (lambda (e) (eq (cdr e) (gethash (car e) original-table))) saved-entries))
      (error "ALIAS-STATE-NOT-RESTORED"))
    (setf result (append result (list "restored" :true)))
    (with-open-file (out (ccl:getenv "CCL_ALIAS_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
      (ccl-startup-census::json result out) (terpri out)))))
