;;; The same definitions and observations run through the native and target compilers.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0)))
  (proclaim '(notinline cc-zero cc-one cc-two cc-three cc-four cc-five cc-six
              cc-sixteen cc-values cc-collect cc-first cc-identity cc-fail
              cc-middle cc-outer cc-tail cc-pool cc-optional cc-rest cc-key)))
(defun cc-zero () 0)
(defun cc-one (a) a)
(defun cc-two (a b) (+ a b))
(defun cc-three (a b c) (+ a b c))
(defun cc-four (a b c d) (+ a b c d))
(defun cc-five (a b c d e) (+ a b c d e))
(defun cc-six (a b c d e f) (+ a b c d e f))
(defun cc-sixteen (a b c d e f g h i j k l m n o p)
  (+ a b c d e f g h i j k l m n o p))
(defun cc-values (n) (values-list (loop for i below n collect i)))
;; Direct public-boundary probes use explicit caller-owned result budgets.
(defun cc-v0 () (values))
(defun cc-v1 () (values 0))
(defun cc-v4 () (values 0 1 2 3))
(defun cc-v5 () (values 0 1 2 3 4))
(defun cc-v64 ()
  (values 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
          16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
          32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
          48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63))
(defun cc-identity (x) x)
(defun cc-first (x y) (declare (ignore y)) x)
(defun cc-collect (x)
  #+wasm32-target (write-line "EB-GC")
  #-wasm32-target (gc)
  x)
(defun cc-moving-arguments (pair)
  (let ((answer (cc-first (cons pair pair) (cc-collect nil))))
    (and (eq (car answer) pair) (eq (cdr answer) pair))))
(defun cc-moving-return (pair)
  (let ((answer (cc-identity (cons pair pair))))
    (cc-collect nil)
    (and (eq (car answer) pair) (eq (cdr answer) pair))))
(defun cc-pool (collect)
  (let ((before nil) (same t))
    (dotimes (i 2)
      (let ((value '#(101 202 303)))
        (when before (setq same (eq before value)))
        (setq before value))
      (when (and collect (= i 0)) (cc-collect nil)))
    (values same (svref before 2))))
(defun cc-optional (a &optional (b 10 supplied)) (list a b supplied))
(defun cc-rest (a &rest more) (cons a more))
(defun cc-key (&key (a 1) (b 2)) (list a b))
(defun cc-fail () (error "CC witness"))
(defun cc-middle () (1+ (cc-fail)))
(defun cc-outer () (1+ (cc-middle)))
(defun cc-tail (n a)
  (declare (fixnum n a))
  (if (= n 0) a (cc-tail (1- n) (1+ a))))
(defun cc-depth (n)
  (declare (fixnum n))
  (if (= n 0) 0
      (let ((answer (cc-depth (1- n))))
        (declare (fixnum answer))
        (the fixnum (1+ answer)))))
(defun cc-row (name value) (format t "CC-ROW ~s ~s~%" name value))
(defun cc-condition (function args)
  (handler-case (apply function args)
    (undefined-function (c) (list :undefined (cell-error-name c)))
    (type-error (c) (list :type (type-error-datum c)))
    (program-error () :arity)))

(loop for f in '(cc-zero cc-one cc-two cc-three cc-four cc-five cc-six cc-sixteen)
      for n in '(0 1 2 3 4 5 6 16)
      do (let ((args (loop for i from 1 to n collect i)))
           (cc-row f (apply f args))
           (when (> n 0) (cc-row :few (cc-condition f (cdr args))))
           (cc-row :many (cc-condition f (cons 0 args)))))
(cc-row :undefined (cc-condition 'cc-not-defined nil))
(cc-row :designator (cc-condition 123 nil))
(cc-row :optional (cc-optional 3))
(cc-row :optional (cc-optional 3 4))
(cc-row :rest (cc-rest 1 2 3 4 5))
(cc-row :key (cc-key :b 9 :a 7))
(cc-row :apply (apply #'cc-six 1 2 '(3 4 5 6)))
(dotimes (i 3)
  (setf (symbol-function 'cc-redefined) (if (oddp i) #'cc-two #'cc-first))
  (cc-row :redefinition (funcall 'cc-redefined 17 23)))
(dolist (n '(0 1 4 5 64))
  (cc-row :list (multiple-value-list (cc-values n)))
  ;; The static target reservation is intentionally bounded. Its 64-value
  ;; kind-3 refusal is exercised by the low-level boundary fixture.
  (when (< n 64)
    (cc-row :scalar (cc-values n))
    (cc-row :bind (multiple-value-bind (a b c d e) (cc-values n) (list a b c d e)))
    (cc-values n)
    (cc-row :discard (cc-two 17 23)))
  (cc-row :forward (multiple-value-call #'list (cc-values n))))
(dotimes (i 2)
  (let ((clean nil))
    (cc-row :unwind
      (handler-case (unwind-protect (cc-outer) (cc-collect nil) (setq clean t))
        (simple-error () :caught)))
    (cc-row :cleanup clean)
    (cc-row :recovery (cc-two 17 23))))
(let ((pair (cons 41 43)))
  ;; The first argument must already be rooted when the second collects.
  (cc-row :argument (cc-moving-arguments pair))
  (cc-row :return (cc-moving-return pair))
  (let* ((inner (lambda () pair))
         (outer (lambda () (funcall inner))))
    (cc-collect nil)
    (cc-row :closures (eq (funcall outer) pair)))
  (multiple-value-bind (a b c d e)
      (values pair pair pair pair pair)
    (cc-collect nil)
    (cc-row :retained (and (eq a pair) (eq b pair) (eq c pair) (eq d pair) (eq e pair))))
  (let ((retained (multiple-value-list (values-list (make-list 64 :initial-element pair)))))
    (cc-collect nil)
    (cc-row :dynamic-retained
      (and (= (length retained) 64) (every (lambda (x) (eq x pair)) retained))))
  (cc-row :pool (multiple-value-list (cc-pool t)))
  (let ((make (lambda (x) (lambda () (cc-collect nil) (list x '#(5 7))))))
    (cc-row :closure-pool (funcall (funcall make 11)))))
(cc-row :tail (cc-tail 100000 0))
(write-line "CC-PASS")
