;;; Host compilation only. Every FASL will be loaded by the target reader.
(in-package "CCL")
(load "ccl:compiler;WASM32;wasm32-bundle.lisp")

(defun bootstrap-load-modules ()
  ;; Read the native loader's selected target forms; do not duplicate its
  ;; ordered load list in the producer, including l1-boot-2's nested loads.
  (wasm32-compiler::call-with-target
   (lambda ()
     (let ((modules '(level-1)))
       (labels ((source (name)
                  (with-open-file (stream name)
                    (loop for form = (read stream nil stream) until (eq form stream)
                          do (visit form))))
                (module (name)
                  (push (intern (string-upcase name) "CCL") modules)
                  (when (string-equal name "l1-boot-2")
                    (source "ccl:level-1;l1-boot-2.lisp")))
                (visit (form)
                  (when (consp form)
                    (cond ((member (car form) '(quote function defun defmethod defmacro)) nil)
                          ((and (member (car form) '(l1-load bin-load require))
                                (stringp (cadr form)))
                           (module (cadr form)))
                          ((and (member (car form) '(l1-load-provide bin-load-provide))
                                (stringp (caddr form)))
                           (module (caddr form)))
                          ((eq (car form) 'macrolet) (mapc #'visit (cddr form)))
                          (t (mapc #'visit (cdr form)))))))
         (source "ccl:level-1;level-1.lisp"))
       (nreverse modules)))))

(let* ((backend (find-xload-backend :wasm32))
       (prior (backend-xload-info-compile-file-function backend))
       (out (getenv "LOADER_OUTPUT"))
       (rows nil)
       (stop nil))
  (unwind-protect
       (progn
         (setf (backend-xload-info-compile-file-function backend)
               (lambda (source &rest options &key output-file &allow-other-keys)
                 (declare (ignore options))
                 (let* ((name (enough-namestring (truename source) (truename "ccl:")))
                        (stem (pathname-name source))
                        (records (concatenate 'string out stem ".records.json"))
                        (saved (concatenate 'string out stem ".w32fsl")))
                   (format t "~&TARGET-BUNDLE ~a~%" name)
                   (multiple-value-bind (path record warnings modules)
                       (handler-bind ((error (lambda (condition)
                                              (format t "~&COMPILER-ERROR ~a: ~a~%" name condition)
                                              (print-call-history :count 30))))
                         (wasm32-compiler::wasm32-compile-bundle-records source saved records))
                     (declare (ignore record))
                     (when output-file (copy-file path output-file :if-exists :supersede))
                     (push (list :object (cons "source" name) (cons "stem" stem)
                                 (cons "path" (concatenate 'string "/ccl/"
                                               (cond ((string= stem "level-1") "")
                                                     ((search "level-1/" name) "l1-fasls/")
                                                     (t "bin/"))
                                               stem ".w32fsl"))
                                 (cons "modules" (length modules))) rows)
                     (values path modules warnings nil)))))
         (handler-case
             (with-cross-compilation-target (:wasm32)
               (target-compile-modules
                (or (let ((selection (getenv "LOADER_MODULES")))
                      (when selection (let ((*read-eval* nil)) (read-from-string selection))))
                    (remove-duplicates (bootstrap-load-modules) :from-end t))
                :wasm32 t))
           (error (condition) (setq stop (format nil "~a" condition))))
         (with-open-file (s (concatenate 'string out "bundles.json")
                            :direction :output :if-exists :supersede)
           (wasm32-compiler::wasm32-bundle-json
            (list :object (cons "files" (coerce (reverse rows) 'vector))
                  (cons "compilation_stop" stop)) s)))
    (setf (backend-xload-info-compile-file-function backend) prior)))
(quit)
