;; Reversible diagnostic wrapper: retain the first failing B entry and rethrow
;; the original exception. No Lisp state or binding is changed.
(module
 (import "env" "memory" (memory 1 32769 shared))
 (import "env" "tcr" (global $tcr i32))
 (import "trace" "code" (global $code i32))
 (import "trace" "failed" (func $failed (param i32 i32 i32 i32)))
 (import "trace" "entered" (func $entered (param i32 i32 i32 i32) (result i32)))
 (import "trace" "returned" (func $returned (param i32 i32 i32)))
 (import "trace" "entry" (func $entry (param i32 i32) (result i32 i32)))
 (import "trace" "tail_entry" (func $tail (param i32 i32 i32) (result i32 i32)))
 (func (export "entry") (param $self i32) (param $count i32) (result i32 i32)
  (local $exception exnref) (local $args i32) (local $token i32) (local $value i32) (local $n i32)
  (local.set $args (i32.load offset=64 (global.get $tcr)))
  (local.set $token (call $entered (global.get $code) (local.get $self) (local.get $count) (local.get $args)))
  (block $failed (result exnref)
   (try_table (catch_all_ref $failed)
    (call $entry (local.get $self) (local.get $count))
    (local.set $n) (local.set $value)
    (call $returned (local.get $token) (local.get $value) (local.get $n))
    (local.get $value) (local.get $n) return)
   unreachable)
  (local.set $exception)
  (call $failed (global.get $code) (local.get $self) (local.get $count) (local.get $args))
  (throw_ref (local.get $exception)))
 (func (export "tail_entry") (param $self i32) (param $count i32) (param $context i32) (result i32 i32)
  (local $exception exnref) (local $args i32) (local $token i32) (local $value i32) (local $n i32)
  (local.set $args (i32.load offset=64 (global.get $tcr)))
  (local.set $token (call $entered (global.get $code) (local.get $self) (local.get $count) (local.get $args)))
  (block $failed (result exnref)
   (try_table (catch_all_ref $failed)
    (call $tail (local.get $self) (local.get $count) (local.get $context))
    (local.set $n) (local.set $value)
    (call $returned (local.get $token) (local.get $value) (local.get $n))
    (local.get $value) (local.get $n) return)
   unreachable)
  (local.set $exception)
  (call $failed (global.get $code) (local.get $self) (local.get $count) (local.get $args))
  (throw_ref (local.get $exception))))
