;;; Native applies the same Lisp containment wrapper; only the foreign library
;;; and service transport are modeled. Target uses real Wasm indirect calls.
(in-package "CCL")
#-wasm32-target
(progn
 (defvar *fc-base-request* (symbol-function '%wasm-host-process-request))
 (defvar *fc-after* 0)
 (defvar *fc-saved* nil)
 (defun fc-native-request (selector operation payload)
   (case operation
    (12 (fa-native-token (vector :callback (svref payload 0) (svref payload 2) t)))
    (13 (let ((row (gethash payload *fa-tokens*)))
          (prog1 (if (svref row 3) 1 0) (setf (svref row 3) nil))))
    (2 (let* ((name (svref payload 1)) (args (svref payload 2)))
         (if (and (>= (length name) 3) (equal (subseq name 0 3) "cb-"))
           (cond
            ((equal name "cb-after") (setf (svref payload 3) (vector *fc-after*)) 0)
            ((equal name "cb-saved") (setf (svref payload 3) (vector -1)) 0)
            (t (let ((row (gethash (svref args 0) *fa-tokens*)))
                 (unless (and row (eq (svref row 0) :callback) (svref row 3))
                   (return-from fc-native-request -1))
                 (setq *fc-saved* row)
                 (let ((result (funcall (svref row 2) (subseq args 1))))
                   (when (and result (equal name "cb-twice"))
                     (setq result (funcall (svref row 2) (subseq args 1))))
                   (when (member name '("cb-call" "cb-twice") :test #'equal) (incf *fc-after*))
                   (setf (svref payload 3) result)
                   (cond ((equal name "cb-trap") -2) ((null result) -4) (t 0))))))
           (funcall *fc-base-request* selector operation payload))))
    (t (funcall *fc-base-request* selector operation payload))))
 (setf (symbol-function '%wasm-host-process-request) #'fc-native-request))

(defun fc-row (name value) (format t "FC-ROW ~A ~S~%" name value))
(defun fc-collect () #+wasm32-target (%wasm-host-process-request 16 0 nil) #-wasm32-target (gc))
(defvar *fc-binding* :outside)
(let* ((library (open-wasm-library "example"))
       (cell (list 40))
       (callback (register-wasm-callback library "integer"
                   (lambda (x) (fc-collect) (+ x (car cell))))))
  (fc-row 'closure (wasm-call library "cb-call" callback 2))
  (setf (car cell) 41)
  (fc-collect)
  (fc-row 'moved (wasm-call library "cb-call" callback 3))
  (fc-row 'twice (wasm-call library "cb-twice" callback 4))
  (fc-row 'deregister (list (deregister-wasm-callback callback)
                            (deregister-wasm-callback callback)))
  (fc-row 'stale (handler-case (wasm-call library "cb-call" callback 1)
                  (error () :caught)))
  (fc-row 'saved (wasm-call library "cb-saved" 9)))
(let* ((library (open-wasm-library "example"))
       (callback (register-wasm-callback library "scalars" #'values)))
  (fc-row 'scalars
    (multiple-value-bind (a b c d)
        (wasm-call library "cb-scalars" callback -2147483648 -9223372036854775808 1.5f0 -0.0d0)
      (list a b (= c 1.5f0) (minusp (float-sign d)))))
  (deregister-wasm-callback callback))
(let* ((library (open-wasm-library "example")) (calls 0) (cleanups 0)
       (callback (register-wasm-callback library "integer"
                  (lambda (x) (declare (ignore x))
                    (let ((*fc-binding* :inside))
                      (unwind-protect (progn (incf calls) (error "callback error"))
                        (fc-collect) (incf cleanups)))))))
  (fc-row 'error (handler-case (wasm-call library "cb-twice" callback 2) (error () :caught)))
  (fc-row 'error-cleanup (list calls cleanups *fc-binding*))
  (fc-row 'after-error (wasm-call library "cb-after"))
  (deregister-wasm-callback callback))
(let ((library (open-wasm-library "example")) (cleanups 0) callback)
  (fc-row 'throw
    (catch 'fc-outside
      (setq callback (register-wasm-callback library "integer"
                       (lambda (x) (unwind-protect (throw 'fc-outside (list x x))
                                     (fc-collect) (incf cleanups)))))
      (handler-case (wasm-call library "cb-call" callback 7) (error () :contained))))
  (fc-row 'throw-cleanup cleanups)
  (deregister-wasm-callback callback))
(let ((library (open-wasm-library "example")) callback)
  (fc-row 'return-from
    (block outside
      (setq callback (register-wasm-callback library "integer"
                       (lambda (x) (return-from outside x))))
      (handler-case (wasm-call library "cb-call" callback 9) (error () :contained))))
  (deregister-wasm-callback callback))
(let* ((library (open-wasm-library "example")) (called 0)
       (callback (register-wasm-callback library "void" (lambda () (incf called) (values)))))
  (fc-row 'void (list (multiple-value-list (wasm-call library "cb-void" callback)) called))
  (deregister-wasm-callback callback))
(fc-row 'not-function (handler-case (register-wasm-callback (open-wasm-library "example") "integer" 42)
                        (error () :caught)))
(let* ((library (open-wasm-library "example"))
       (callback (register-wasm-callback library "integer"
                   (let ((data (list 100 200)))
                     (lambda (x) (fc-collect) (+ x (car data) (cadr data)))))))
  (fc-collect)
  (fc-row 'registration-only-root (wasm-call library "cb-call" callback 7))
  (deregister-wasm-callback callback))
(format t "FC-PASS~%")
