;;; Exercise the shared dispatcher with every existing target and with Wasm.
;;; Mock compilation records the call boundary; real compilation follows.
(in-package "CCL")
(in-development-mode
(let* ((names '(compile-file find-module needs-compile-p find-xload-backend))
       (saved (mapcar #'symbol-function names))
       (backend (find-xload-backend :wasm32))
       (compiler (backend-xload-info-compile-file-function backend))
       (targets '(:linuxppc32 :darwinppc32 :darwinppc64 :linuxppc64 :darwinx8632
                  :linuxx8664 :darwinx8664 :freebsdx8664 :solarisx8664 :win64
                  :linuxx8632 :win32 :solarisx8632 :freebsdx8632 :linuxarm :androidarm :darwinarm
                  :wasm32))
       (calls nil)
       (rows nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'find-module)
               (lambda (module target)
                 (assert (eq module 'loader-dispatch-test))
                 (assert (member target targets))
                 (values #p"result.fasl" '(#p"input.lisp")))
               (symbol-function 'needs-compile-p)
               (lambda (fasl sources force)
                 (assert (equal fasl #p"result.fasl"))
                 (assert (equal sources '(#p"input.lisp")))
                 force)
               (symbol-function 'find-xload-backend)
               (lambda (target)
                 (assert (eq target :wasm32))
                 backend)
               (symbol-function 'compile-file)
               (lambda (source &key output-file verbose target)
                 (push (list :native source output-file verbose target) calls))
               (backend-xload-info-compile-file-function backend)
               (lambda (source &key output-file verbose target)
                 (push (list :wasm source output-file verbose target) calls)))
         (dolist (target targets)
           (setq calls nil)
           (assert (target-compile-modules 'loader-dispatch-test target t))
           (assert (equal calls (list (list (if (eq target :wasm32) :wasm :native)
                                            #p"input.lisp" #p"result.fasl" t target))))
           (setq calls nil)
           (assert (target-compile-modules '(loader-dispatch-test) target nil))
           (assert (null calls))
           (push (list :object (cons "target" (string target))
                       (cons "dispatch" t) (cons "unchanged_input_skipped" t)) rows)))
    (mapc (lambda (name function) (setf (symbol-function name) function)) names saved)
    (setf (backend-xload-info-compile-file-function backend) compiler))
  (with-open-file (stream (concatenate 'string (getenv "LOADER_OUTPUT") "dispatch.json")
                          :direction :output :if-exists :error)
    (wasm32-json (list :object (cons "status" "PASS") (cons "rows" (reverse rows))) stream)
    (terpri stream))))
(quit)
