;;; Inspect retained function-cell wrappers after the legacy export is closed.
(defpackage :ccl-boot-wrappers (:use :cl))
(in-package :ccl-boot-wrappers)

(defun field (object name)
  (loop for (key value) on (cdr object) by #'cddr
        when (string= key name) return value))
(defun obj (&rest fields) (apply #'ccl-startup-census::object fields))
(defun marker () (ccl::%sym-global-value 'ccl::%macro-code%))
(defun handlers () (ccl::%sym-global-value 'ccl::*nx1-alphatizers*))
(defun wrapper-kind (value)
  (unless (and (typep value 'simple-vector) (= (length value) 2))
    (error "WRAPPER-LAYOUT"))
  (unless (eql (svref value 0) (marker)) (error "WRAPPER-DISPATCH"))
  (cond ((ccl::lfunp (svref value 1)) "macro-wrapper")
        ((symbolp (svref value 1)) "special-wrapper")
        (t (error "WRAPPER-PAYLOAD"))))

(defun native-controls ()
  (let ((cases (list (list "WRAPPER-LAYOUT" (vector (marker)))
                     (list "WRAPPER-DISPATCH" (vector 0 #'identity))
                     (list "WRAPPER-PAYLOAD" (vector (marker) 42)))))
    (dolist (case cases)
      (handler-case (progn (wrapper-kind (second case)) (error "CONTROL-ESCAPED"))
        (error (condition)
          (unless (search (first case) (princ-to-string condition)) (error condition))
          (format t "NATIVE-CONTROL-REJECTED ~a~%" (first case)))))))

(defun inspect-wrappers (identities descriptions describe identify legacy-limit)
  (let* ((inverse (make-hash-table :test #'eql))
         (used (make-hash-table :test #'eql))
         (wrappers nil) (oracle nil) (seen (make-hash-table :test #'eq))
         (state (ccl::%sym-global-value 'ccl::*boot-census-state*))
         (table (handlers)) (table-id (funcall identify table)))
    (maphash (lambda (value id) (setf (gethash id inverse) value)) identities)
    (labels ((ref (x)
               (let ((id (funcall describe x))) (setf (gethash id used) t) id)))
      ;; First derive the export from the legacy opaque descriptors, in ID order.
      (loop for id from 1 to legacy-limit for description = (gethash id descriptions)
            when (and description (equal (field description "kind") "opaque")) do
        (let* ((value (gethash id inverse)) (kind (wrapper-kind value))
               (payload (svref value 1))
               (handler (when (equal kind "special-wrapper") (gethash payload table))))
          (when (and (equal kind "special-wrapper") (not (functionp handler)))
            (error "SPECIAL-HANDLER-MISSING"))
          (push (obj "id" id "kind" kind "dispatch_value" (svref value 0)
                     "payload" (ref payload) "handler" (if handler (ref handler) :null)) wrappers)))
      ;; Independent literal-slot oracle starts at the original binding events,
      ;; not at descriptors or the wrapper rows just generated.
      (dolist (event (reverse (third state)))
        (when (member (second event) '(:binding-installed :binding-removing))
          (dolist (value (cdr (third event)))
            (unless (or (eq value ccl::%unbound-function%) (symbolp value) (functionp value)
                        (gethash value seen))
              (setf (gethash value seen) t)
              (unless (and (typep value 'simple-vector) (= (length value) 2)) (error "ORACLE-LAYOUT"))
              (let* ((payload (aref value 1)) (macro (functionp payload))
                     (handler (unless macro (gethash payload table))))
                (unless (and (eql (aref value 0) (marker)) (or macro (symbolp payload)))
                  (error "ORACLE-CONTENT"))
                (unless (or macro (functionp handler)) (error "ORACLE-HANDLER"))
                (push (obj "wrapper" (or (gethash value identities) (error "ORACLE-WRAPPER-ID"))
                           "slot0" (aref value 0)
                           "slot1" (or (gethash payload identities) (error "ORACLE-PAYLOAD-ID"))
                           "slot1_kind" (if macro "function" "symbol")
                           "handler" (if macro :null (or (gethash handler identities) (error "ORACLE-HANDLER-ID"))))
                      oracle))))))
      (let ((result (obj "version" 1 "legacy_identity_limit" legacy-limit
                         "identity_limit" (hash-table-count identities)
                         "descriptor_time" "Retained image after boot handoff; no historical mutation or handler-execution claim."
                         "dispatch_value" (marker) "fixnum_shift" x8664::fixnumshift
                         "raw_dispatch_word" (ash (marker) x8664::fixnumshift) "handler_table" table-id
                         "wrappers" (nreverse wrappers)
                         "oracle" (sort oracle #'< :key (lambda (r) (field r "wrapper")))
                         "objects" (loop for id in (sort (loop for id being the hash-keys of used collect id) #'<)
                                         collect (gethash id descriptions)))))
        (native-controls)
        (with-open-file (out (ccl:getenv "CCL_WRAPPER_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
          (ccl-startup-census::json result out) (terpri out))
        (format t "WRAPPERS-EXPORTED ~d~%" (hash-table-count seen))))))

(defun run ()
  (cl-user::export-boot-census :after-export #'inspect-wrappers))
