    (defun core-cpl-select (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)))
        (core-collect)
        (handler-case (progn (signal condition) :unhandled)
          (cpl-diamond () :diamond)
          (cpl-left () :left)
          (cpl-right () :right)
          (error () :error))))

    (defun core-cpl-decline (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)) (trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (push :outer trace))))
          (handler-bind ((cpl-left (lambda (c)
                                     (declare (ignore c))
                                     (core-collect)
                                     (push :left trace)))
                         (cpl-right (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (push :right trace))))
            (signal condition)))
        (reverse trace)))

    (defun core-cpl-types (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)))
        (core-collect)
        (values (typep condition 'cpl-left)
                (typep condition 'cpl-right)
                (typep condition 'cpl-diamond)
                (typep condition 'error)
                (typep condition 'warning))))

    (defun core-cpl-restart (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)) (cleaned nil))
        (values
          (handler-bind ((condition (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (invoke-restart 'use-value 37))))
            (restart-case
                (unwind-protect (error condition)
                  (core-collect)
                  (setq cleaned t))
              (use-value (value) value)))
          cleaned)))

    (defun core-cpl-construct (image)
      (core-condition-prepare image)
      (let ((condition (make-condition 'type-error :datum (list 17)
                                                 :expected-type 'integer)))
        (core-collect)
        (handler-case (error condition)
          (cpl-left () :wrong)
          (type-error (c)
            (core-collect)
            (values (type-error-datum c) (type-error-expected-type c)
                    (typep c 'error))))))

    (defun core-cpl-resignal (image)
      (core-condition-prepare image)
      (let ((trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (core-collect)
                                    (push :outer trace))))
          (handler-bind ((condition (lambda (c)
                                      (push :inner trace)
                                      (signal c)
                                      (core-collect)
                                      (push :returned trace))))
            (signal (svref image 2))))
        (reverse trace)))

    (defun core-condition-prepare (image)
      #+wasm32-target
      (setq ccl::*class-table* (svref image 0)
            ccl::%find-classes% (svref image 3)
            ccl::*initialization-invalidation-alist* (first (svref image 12))
            ccl::*standard-class-wrapper* (second (svref image 12))
            ccl::*standard-effective-slot-definition-class-wrapper* (third (svref image 12))
            ccl::*error-format-strings* (fourth (svref image 12))
            ccl::*eql-specializer-class* (svref image 4)
            ccl::*standard-class-class* (svref image 5)
            ccl::*standard-generic-function-class* (find-class 'standard-generic-function)
            ccl::*clos-initialization-functions* nil)
      #+wasm32-target (ccl::compute-dcode #'ccl::eql-specializer-object)
      #+wasm32-target
      (dolist (gf (svref image 8)) (ccl::compute-dcode gf))
      image)

    (defun core-condition-create (image)
      (core-condition-prepare image)
      (let ((condition (apply #'make-condition (svref image 6) (svref image 7))))
        (core-collect)
        (values (typep condition 'condition) (typep condition 'error)
                (typep condition 'warning) (slot-value condition 'payload))))

    (defun core-condition-signal-string (image)
      (core-condition-prepare image)
      (handler-case (signal "condition ~s" (progn (core-collect) (list 19)))
        (simple-condition (condition)
          (core-collect)
          (values (simple-condition-format-control condition)
                  (simple-condition-format-arguments condition)))))

    (defun core-condition-signal-symbol (image)
      (core-condition-prepare image)
      (handler-case (signal 'cpl-diamond :payload (progn (core-collect) (list 29)))
        (cpl-left (condition)
          (core-collect)
          (values (slot-value condition 'payload) (typep condition 'cpl-right)))))

    (defun core-condition-spread (image)
      (core-condition-prepare image)
      (let ((arguments (list :datum (list 17) :expected-type 'integer)))
        (core-collect)
        (handler-case (apply #'error 'type-error arguments)
          (type-error (condition)
            (core-collect)
            (values (type-error-datum condition) (type-error-expected-type condition))))))

    (defun core-condition-initargs (image)
      (core-condition-prepare image)
      (handler-case
          (let ((condition (apply #'make-condition 'cpl-left (svref image 7))))
            (core-collect)
            (values :made (slot-value condition 'payload)))
        (program-error () :bad-initargs)))

    (defun core-condition-slots (image)
      (core-condition-prepare image)
      (let ((condition (make-condition 'cpl-left)))
        (core-collect)
        (setf (slot-value condition 'payload) (list 31))
        (core-collect)
        (values (slot-value condition 'payload) (slot-boundp condition 'payload))))

    (defun core-condition-unlisted (image)
      (core-condition-prepare image)
      (handler-case
          (error 'ccl::simple-destructuring-error :format-control "unlisted ~s"
                                                :format-arguments (list 47))
        (ccl::simple-destructuring-error (condition)
          (core-collect)
          (values (simple-condition-format-control condition)
                  (simple-condition-format-arguments condition)
                  (typep condition 'program-error)))))

    (defun core-condition-cerror (image)
      (core-condition-prepare image)
      (let ((payload nil) (cleaned nil))
        (values
          (handler-bind ((cpl-left (lambda (condition)
                                    (setq payload (slot-value condition 'payload))
                                    (core-collect)
                                    (invoke-restart 'continue))))
            (unwind-protect (cerror "Continue" 'cpl-diamond :payload (list 53))
              (setq cleaned t)))
          payload cleaned)))

    (defun core-condition-indirect (image)
      (core-condition-prepare image)
      (let ((signaller (car (list #'signal))) (effects nil))
        (handler-bind ((simple-condition
                         (lambda (condition)
                           (core-collect)
                           (push (simple-condition-format-arguments condition) effects))))
          (funcall signaller "indirect ~s" (progn (push :argument effects) 59)))
        effects))

    (defun core-condition-class-cell (image)
      (core-condition-prepare image)
      (let* ((cell (gethash 'cpl-other ccl::%find-classes%))
             (old (ccl::class-cell-class cell)))
        (unwind-protect
            (progn
              (setf (ccl::class-cell-class cell) (find-class 'cpl-left))
              (core-collect)
              (let ((condition (make-condition 'cpl-other)))
                (values (slot-value condition 'payload)
                        (typep condition 'cpl-other))))
          (setf (ccl::class-cell-class cell) old))))

    (defun core-condition-table-store (image)
      (core-condition-prepare image)
      (let ((table (svref image 3)) (trace nil) (value (list 71)))
        (values
          (eq (setf (gethash (progn (push :key trace) :new-cell)
                            (progn (push :table trace) table)
                            (progn (push :default trace) :unused))
                    (progn (core-collect) (push :value trace) value))
              value)
          (progn (core-collect) (gethash :new-cell table))
          (nth-value 1 (gethash :new-cell table))
          (reverse trace))))

    (defun core-condition-new-cell (image)
      (core-condition-prepare image)
      (let ((ccl::%find-classes% (svref image 3)))
        (let* ((missing (ccl::find-class-cell 'new-class nil))
               (cell (ccl::find-class-cell 'new-class t)))
          (core-collect)
          (setf (ccl::class-cell-class cell) (find-class 'cpl-left))
          (core-collect)
          (let ((condition (make-condition (find-class 'new-class) :payload (list 73))))
            (values missing (ccl::class-cell-name cell)
                    (eq cell (ccl::find-class-cell 'new-class t))
                    (slot-value condition 'payload)
                    (typep condition 'cpl-left))))))

    (defun core-condition-rebuild-cells (image)
      (core-condition-prepare image)
      (let ((ccl::%find-classes% (svref image 3)) (count 0) (fresh t))
        (dolist (entry (svref image 11))
          (let ((old (ccl::find-class-cell (car entry) nil))
                (cell (ccl::make-class-cell (car entry))))
            (setf (ccl::class-cell-class cell) (cdr entry)
                  (gethash (car entry) ccl::%find-classes%) cell)
            (unless (and (not (eq old cell))
                         (eq (ccl::find-class-cell (car entry) nil) cell))
              (setq fresh nil))
            (incf count)))
        (core-collect)
        (dolist (entry (svref image 11))
          (unless (eq (find-class (car entry)) (cdr entry)) (setq fresh nil)))
        (let ((condition (make-condition 'cpl-derived)))
          (values fresh count (slot-value condition 'payload)
                  (slot-value condition 'other)))))

    (defun core-condition-table-read-only (image)
      (core-condition-prepare image)
      (let ((table (svref image 3)))
        (unwind-protect
            (progn
              (setf (ccl::nhash.read-only table) t)
              (handler-case (setf (gethash :not-written table) 79)
                (error () :read-only)))
          (setf (ccl::nhash.read-only table) nil))))

    (defun core-condition-table-grow (image)
      (core-condition-prepare image)
      (let* ((ccl::%find-classes% (svref image 3))
             (names (svref image 10))
             (class (find-class 'cpl-derived))
             (count 0) (good t))
        (dolist (name names)
          (let ((cell (ccl::find-class-cell name t)))
            (setf (ccl::class-cell-class cell) class)
            (incf count)
            (when (zerop (logand count 127)) (core-collect))))
        (core-collect)
        (dolist (name names)
          (unless (eq (find-class name) class) (setq good nil)))
        ;; Remove across the enlarged vector, collect with tombstones, restore.
        (dolist (name names)
          (unless (remhash name ccl::%find-classes%) (setq good nil)))
        (core-collect)
        (dolist (name names)
          (when (remhash name ccl::%find-classes%) (setq good nil))
          (setf (ccl::class-cell-class (ccl::find-class-cell name t)) class))
        (core-collect)
        (dolist (name names)
          (unless (eq (find-class name) class) (setq good nil)))
        (let ((condition (make-condition (find-class (car names)))))
          (values good count (slot-value condition 'payload)
                  (slot-value condition 'other)))))

    (defun core-condition-table-remove (image)
      (core-condition-prepare image)
      (let ((table (svref image 3)) (trace nil) (value (list 83)))
        (setf (gethash :remove-me table) value)
        (core-collect)
        (let* ((present (gethash :remove-me table))
               (removed (remhash (progn (push :key trace) :remove-me)
                                 (progn (push :table trace) table))))
          (core-collect)
          (multiple-value-bind (missing found) (gethash :remove-me table :missing)
            (values (eq present value) removed missing found
                    (remhash :remove-me table) (reverse trace))))))

    (defun core-condition-remove-read-only (image)
      (core-condition-prepare image)
      (let ((table (svref image 3)))
        (unwind-protect
            (progn
              (setf (ccl::nhash.read-only table) t)
              (handler-case (remhash 'cpl-left table)
                (error () :read-only)))
          (setf (ccl::nhash.read-only table) nil))))

    ;; Target-only constructor probe; native has a different owner prefix.
    (defun core-condition-eq-vector (count)
      (ccl::%alloc-misc count 74))

    (defun core-condition-own-table (image)
      (core-condition-prepare image)
      (let* ((original (svref image 3))
             (ccl::%find-classes% (ccl::%wasm-make-class-table 4))
             (good t) (count 0))
        ;; Start without a projected vector or cell. The source class objects
        ;; supply identities; everything holding them here is target allocated.
        (dolist (entry (svref image 11))
          (let ((cell (ccl::find-class-cell (car entry) t)))
            (setf (ccl::class-cell-class cell) (cdr entry))
            (incf count)
            (when (zerop (logand count 63)) (core-collect))))
        (setf (svref image 3) ccl::%find-classes%)
        (core-collect)
        (dolist (entry (svref image 11))
          (unless (and (eq (find-class (car entry)) (cdr entry))
                       (not (eq (gethash (car entry) original)
                                (gethash (car entry) ccl::%find-classes%))))
            (setq good nil)))
        (let* ((name (ccl::class-cell-name (gethash 'cpl-left original)))
               (cell (ccl::find-class-cell name nil)))
          (unless (remhash name ccl::%find-classes%) (setq good nil))
          (core-collect)
          (when (find-class name nil) (setq good nil))
          (setf (gethash name ccl::%find-classes%) cell))
        (core-collect)
        (let ((condition (make-condition 'cpl-derived)))
          (values good count (slot-value condition 'payload)
                  (slot-value condition 'other)))))

    (defun core-condition-table-clear (image)
      (core-condition-prepare image)
      (let ((table (svref image 3)) (good t))
        (unless (eq table (clrhash table)) (setq good nil))
        (core-collect)
        (dolist (entry (svref image 11))
          (when (nth-value 1 (gethash (car entry) table)) (setq good nil)))
        (setf (gethash :after-clear table) (list 89))
        (core-collect)
        (values good (gethash :after-clear table)
                (nth-value 1 (gethash :after-clear table)))))

    (defun core-condition-implicit-type (image datum)
      (core-condition-prepare image)
      (let ((ccl::%find-classes% (ccl::%wasm-make-class-table 4)) (cleaned nil))
        (dolist (entry (svref image 11))
          (setf (ccl::class-cell-class (ccl::find-class-cell (car entry) t)) (cdr entry)))
        (core-collect)
        (values
          (handler-case (unwind-protect (car datum) (setq cleaned t))
            (type-error (condition)
              (core-collect)
              (list (eq (type-error-datum condition) datum)
                    (type-error-expected-type condition)
                    (eq (class-of condition) (find-class 'type-error)))))
          cleaned)))

    (defun core-condition-implicit-divide (image numerator denominator)
      (core-condition-prepare image)
      (handler-case (truncate numerator denominator)
        (division-by-zero (condition)
          (core-collect)
          (values (eq (class-of condition) (find-class 'division-by-zero))
                  (typep condition 'arithmetic-error)))))

    (defun core-condition-implicit-unbound (image)
      (core-condition-prepare image)
      (progv '(cpl-unbound-variable) nil
        (locally (declare (special cpl-unbound-variable))
          (handler-case cpl-unbound-variable
            (unbound-variable (condition)
              (core-collect)
              (values (eq (cell-error-name condition) 'cpl-unbound-variable)
                      (eq (class-of condition) (find-class 'unbound-variable))))))))

    (defun core-condition-implicit-undefined (image name)
      (core-condition-prepare image)
      (values
        (handler-case (fdefinition name)
          (undefined-function (condition)
            (core-collect)
            (and (eq (cell-error-name condition) name)
                 (eq (class-of condition) (find-class 'undefined-function)))))
        (handler-case (funcall name)
          (undefined-function (condition)
            (core-collect)
            (and (eq (cell-error-name condition) name)
                 (typep condition 'undefined-function))))))

    (defun core-condition-implicit-float (image large zero negative)
      (core-condition-prepare image)
      (values
        (handler-case (exp large)
          (floating-point-overflow (condition)
            (core-collect)
            (eq (class-of condition) (find-class 'floating-point-overflow))))
        (handler-case (ccl::%double-float-log! zero (ccl::%make-dfloat))
          (division-by-zero (condition)
            (core-collect)
            (eq (class-of condition) (find-class 'division-by-zero))))
        (handler-case (ccl::%double-float-sqrt! negative (ccl::%make-dfloat))
          (floating-point-invalid-operation (condition)
            (core-collect)
            (eq (class-of condition) (find-class 'floating-point-invalid-operation))))))
