(in-package :wasm32-compiler)

(load (merge-pathnames "witnesses.lisp" *load-pathname*))
(load (merge-pathnames "inputs.lisp" *load-pathname*))

(defvar *funcallable-inputs* (make-hash-table :test #'eq))

(defun funcallable-input (value)
  (let ((gf (make-instance 'standard-generic-function :name 'funcallable-witness)))
    (setf (ccl::%svref (ccl::gf.slots gf) 1) value
          (ccl::%svref (ccl::gf.slots gf) 2) (list value)
          (ccl::%svref (ccl::gf.slots gf) 3) (vector value))
    (setf (gethash gf *funcallable-inputs*) t)
    gf))

(defun prior-inputs (name)
  (let ((s (symbol-name name)))
    (cond
      ((member s '("%GENERIC-FUNCTION-NAME" "%GENERIC-FUNCTION-METHOD-COMBINATION"
                   "%GENERIC-FUNCTION-METHOD-CLASS") :test #'equal)
       (values (mapcar (lambda (x) (list (funcallable-input x)))
                       '(nil t 7 -9 :funcallable "name" (1 . 2))) t))
      ((equal s "CORE-GF-IDENTITY") (values '((7) ((1 . 2))) t))
      ((member s '("%DOUBLE-FLOAT+-2!" "%DOUBLE-FLOAT--2!"
                   "%DOUBLE-FLOAT*-2!" "%DOUBLE-FLOAT/-2!") :test #'equal)
       (values '((1.5d0 2.0d0 99.0d0) (-7.0d0 3.0d0 99.0d0)
                 (-0.0d0 2.0d0 99.0d0) (0.0d0 -2.0d0 99.0d0)
                 (1.0d100 1.0d-100 99.0d0)) t))
      ((member s '("CORE-HYPER-ACOSH-CONDITION64" "CORE-HYPER-ATANH-CONDITION64") :test #'equal)
       (values '((-2.0d0) (-1.0d0) (0.0d0) (1.0d0) (2.0d0)) t))
      ((member s '("CORE-HYPER-ACOSH-CONDITION32" "CORE-HYPER-ATANH-CONDITION32") :test #'equal)
       (values '((-2.0s0) (-1.0s0) (0.0s0) (1.0s0) (2.0s0)) t))
      ((equal s "CORE-ARCH-RATIO")
       (values '((1/3) (-7/11) (1152921504606846976/1152921504606846977)) t))
      ((equal s "CORE-ARCH-IDENTITY")
       (values '((nil) (7) (-7) (#\A) ((1 . 2)) (#(1 2)) (1.5d0)) t))
      ((equal s "CORE-ARCH-SYMBOL-IDENTITY")
       (values '((nil) (t) (:arch-symbol)) t))
      ((equal s "CORE-ARCH-DOUBLE")
       (values '((0.0d0) (-0.0d0) (1.5d0) (-1.0d200) (1.0d-200)) t))
      ((equal s "CORE-ARCH-SINGLE")
       (values '((0.0s0) (-0.0s0) (1.5s0) (-1.0s20) (1.0s-20)) t))
      ((equal s "CORE-ARCH-COPY-ORDER")
       (values '((1.5d0 7.0d0) (-0.0d0 3.0d0)) t))
      ((equal s "CORE-ARCH-STACK-SINGLE")
       (values '((0) (1) (-7) (16777217) (1.5d0)) t))
      ((equal s "%MAYBE-MAKE-RATIO")
       (values '((1 3 nil) (-7 11 1/3) (536870911 536870912 nil)
                 (1152921504606846976 1152921504606846977 7)) t))
      ((equal s "%FIXNUM-DFLOAT")
       (values '((0) (1) (-1) (536870911) (-536870912)
                 (0 7.0d0) (37 7.0d0)) t))
      ((equal s "%FIXNUM-SFLOAT")
       (values '((0) (1) (-1) (16777217) (536870911) (-536870912)) t))
      ((equal s "MULTIPLY-FIXNUMS")
       (values (loop for a in '(0 1 -1 32767 32768 -32768 536870911 -536870912)
                     append (loop for b in '(0 1 -1 32768 536870911 -536870912)
                                  collect (list a b))) t))
      ((equal s "UPGRADED-COMPLEX-PART-TYPE")
       (values '((integer) (rational) (real) (single-float) (double-float)
                 ((integer 0 10)) ((or single-float double-float))) t))
      ((equal s "CORE-ASSQ-IDENTITY") (values '((nil) (:a) (7) ("key") ((1 . 2))) t))
      ((equal s "CORE-SIGNED-ZERO-LITERAL") (values '((-0.0d0) (0.0d0) (1.0d0) (-1.0d0)) t))
      ((equal s "CORE-SIGNED-ZERO-VARIABLE") (values '((-0.0d0 0) (0.0d0 0) (-0.0d0 0.0d0) (0.0d0 -0.0d0)) t))
      ((equal s "CORE-LDB") (values '((0) (1) (255) (256) (65535) (-1) (-536870912) (536870911)) t))
      ((equal s "CORE-LOGICAL-ERROR") (values '((nil) (#\A) ((1 . 2)) (1.5d0)) t))
      ((member s '("BASE-STRING-P" "BIT-VECTOR-P") :test #'equal)
       (values '((nil) (7) ("") ("λ😁") (#*101) (#())) t))
      ((member s '("CORE-REGISTER" "CORE-SYMBOL-STATE") :test #'equal)
       (values (list (list (make-symbol "STATE") '(1 2)) (list (make-symbol "STATE") 7)) t))
      ((equal s "SET-ISTRUCT-CELL-INFO") (values '(((cell) 7) ((cell . :old) (:new))) t))
      ((member s '("SEQUENCE-TYPE" "DISPLACED-ARRAY-P" "ARRAY-DISPLACEMENT" "%ARRAY-IS-HEADER" "ARRAY-DIMENSIONS" "ARRAY-RANK" "ARRAY-TOTAL-SIZE" "ARRAY-HAS-FILL-POINTER-P" "ADJUSTABLE-ARRAY-P") :test #'equal)
       (values '((#()) (#(1 2 3)) ("") ("λ😁") (#*101)) t))
      ((member s '("PATHNAMEP" "LOGICAL-PATHNAME-P" "HASH-TABLE-P" "READTABLEP" "RANDOM-STATE-P" "RESTARTP" "LISP-THREAD-P" "SEMAPHOREP"
                   "ARRAY-CTYPE-P" "CLASS-CTYPE-P" "CONS-CTYPE-P" "CONSTANT-CTYPE-P" "FOREIGN-CTYPE-P" "FUNCTION-CTYPE-P" "HAIRY-CTYPE-P" "INTERSECTION-CTYPE-P" "MEMBER-CTYPE-P" "NAMED-CTYPE-P" "NEGATION-CTYPE-P" "NUMERIC-CTYPE-P" "UNION-CTYPE-P" "UNKNOWN-CTYPE-P" "VALUES-CTYPE-P") :test #'equal)
       (values '((nil) (7) (:symbol) ((1 . 2)) (#(1 2)) ("abc")) t))
      ((equal s "LAST") (values '((nil) ((1 2 3)) ((1 2 3) 0) ((1 2 3) 2) ((1 . 2) 5)) t))
      ((member s '("NTH" "NTHCDR") :test #'equal) (values '((0 nil) (0 (1 2 3)) (2 (1 2 3)) (5 (1 2))) t))
      ((equal s "ALT-LIST-LENGTH") (values '((nil) ((1 2 3)) ((1 2 . 3))) t))
      ((equal s "GET-PROPERTIES") (values '((nil (:a)) ((:a 1 :b 2) (:b)) ((:a 1 :b 2) (:c :a))) t))
      ((equal s "ADJOIN-ASSQ") (values '((:a nil 7) (:a ((:a . 1) (:b . 2)) 9) (:c ((:a . 1)) 9)) t))
      ((equal s "VALID-CHAR-CODE-P") (values '((-1) (0) (65) (55295) (55296) (57343) (57344) (1114111) (1114112)) t))
      ((equal s "SCHAR") (values '(("abc" 0) ("λ😁" 1)) t))
      ((equal s "SET-SCHAR") (values '(("abc" 1 #\Z) ("λ😁" 0 #\A)) t))
      ((equal s "%SET-SCHARCODE") (values '(("abc" 1 #\Z) ("λ😁" 0 #\A)) t))
      ((equal s "%STR-MEMBER") (values '((#\a "abc") (#\Z "abc") (#\λ "aλb" 1 2)) t))
      ((equal s "%VECTOR-MEMBER") (values '((7 #()) (7 #(1 7 3)) (:a #(:a :b)) (7 #(1 2))) t))
      ((equal s "%STRING=") (values '(("abc" "abc" 0 3) ("xabc" "abc" 1 4) ("abc" "abd" 0 3)) t))
      ((equal s "BYTE") (values '((0 0) (8 0) (8 8) (16 3)) t))
      ((equal s "ASSEQL") (values '((1 nil) (1 (nil (1 . :a) (2 . :b))) (1/3 ((1/3 . :ratio))) (9 ((1 . 2)))) t))
      ((equal s "PROPER-LIST-P") (values '((nil) ((1)) ((1 2 3)) ((1 . 2)) (7)) t))
      ((equal s "PROPER-SEQUENCE-P") (values '((nil) ((1 2)) ("abc") (#(1 2)) (#*101) (7)) t))
      ((equal s "STRINGP") (values '((nil) (7) ("") ("λ😁") (#(1 2)) (#\A)) t))
      ((member s '("SYMBOL-BINDING-INDEX" "PROCLAIMED-SPECIAL-P" "%SYMBOL-BITS") :test #'equal)
       (values (list (list (make-symbol "FRESH"))) t))
      ((member s '("%SET-SYM-VALUE" "%SET-SYM-GLOBAL-VALUE") :test #'equal)
       (values (list (list (make-symbol "VALUE") 7) (list (make-symbol "VALUE") '(1 2))) t))
      ((equal s "%SET-SYMBOL-PACKAGE") (values (list (list (make-symbol "PKG") nil)) t))
      ((equal s "COMPILER-SPECIAL-FORM-P") (values '((quote) (dependency-ordinary)) t))
      ((equal s "CONTAINS-NON-T-SPECIALIZER?") (values '((nil) ((:not-a-class))) t))
      ((equal s "NHASH.VECTOR-SIZE") (values '((#(0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0)) (#(1 2 3 4 5 6 7 8 9 10 11 12 13 14))) t))
      ((member s '("LISPTAG" "FULLTAG") :test #'equal) (values '((0) (8) (-8)) t))
      ((equal s "MERGE-LISTS*-NO-KEY")
       (values (list (list nil '(1 2) (core-native-function 'core-less)) (list '(1 3 5) '(2 4) (core-native-function 'core-less)) (list '(1 2) '(1 3) (core-native-function 'core-less))) t))
      ((equal s "REGISTER-ISTRUCT-CELL") (values '((dependency-new-cell) (:dependency-cell)) t))
      ((equal s "LENGTH") (values (append '((nil) ((1)) ((1 2 3)) (#()) (#(1 2)) ("") ("λ😁") (#*101)) (list (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9)) (list (make-list 100 :initial-element 7)))) t))
      ((equal s "SYMBOL-PACKAGE") (values (list (list (make-symbol "NO-PACKAGE"))) t))
      ((equal s "TYPECODE") (values '((0) (4) (-4) (536870908) (-536870912)) t))
      ((member s '("CORE-ASSQ" "ASSQ") :test #'equal) (values '((nil (nil (nil . 9))) (:a nil) (:a (nil (:a . 1) (:b . 2))) (:missing ((:a . 1))) (:a ((:a . 1) (:a . 2)))) t))
      ((equal s "CORE-LOGICAL") (values '((0 0) (1 2) (-1 7) (-536870912 536870911) (255 15)) t))
      ((equal s "CORE-SUBTRACT-CALL") (values '((1 2 3) (-536870912 1 -1) (1152921504606846976 7 9) (1.5d0 2.0d0 3.0d0)) t))
      ((member s '("CORE-TYPE-TESTS" "CORE-REQUIRE-INTEGER" "CORE-BADARG") :test #'equal)
       (values '((nil) (t) (0) (7) (-1) (128) (256) (1152921504606846976) (1/3) (1.5d0) (#\A) ("abc") ((1 . 2)) (#(1 2))) t))
      ((member s '("CORE-INTEGER-DIVIDE" "CORE-DIVIDE-ORDER") :test #'equal)
       (values '((6 3) (0 3) (-6 3) (6 -3) (-6 -3) (1 1)
                 (-536870912 -1) (536870911 1) (1073741824 2)
                 (1152921504606846976 1073741824)
                 (-1152921504606846976 -1073741824)
                 (1329227995784915872903807060280344576 1152921504606846976)
                 (6 3.0d0) (6.0s0 3)) t))
      ((equal s "CORE-DIVIDE-ZERO")
       (values '((6 0) (1152921504606846976 0) (nil 3) (6 nil)) t))
      ((equal s "BOUNDP") (values (append '((nil) (t) (:execution-value)) (list (list (make-symbol "UNBOUND")))) t))
      ((member s '("%SYM-VALUE" "%SYM-GLOBAL-VALUE") :test #'equal)
       (values '((nil) (t) (:execution-value)) t))
      ((member s '("LOCKP" "RECURSIVE-LOCK-P" "READ-WRITE-LOCK-P" "NATIVE-CLASS-P") :test #'equal)
       (values '((nil) (t) (7) ((1 . 2)) (#(1 2)) ("ordinary")) t))
      ((equal s "FROZEN-DEFINITION-P") (values '((7) ((1 . 2)) (execution-unfrozen-symbol)) t))
      ((equal s "CONSTANT-SYMBOL-P") (values '((7) ((1 . 2)) (execution-unfrozen-symbol)) t))
      ((equal s "GETF-TEST")
       (values (list (list nil :a #'eq) (list '(:a 1 :b 2) :b #'eq)
                     (list '(:a 1) :missing #'eq 99) (list '(1/3 :found) 1/3 #'eql)) t))
      ((equal s "RASSOC")
       (values (list (list 2 '(nil (1 . 2) (3 . 4)))
                     (list 9 '((1 . 2))) (list 1/3 '((:a . 1/3)))
                     (list 2 '((1 . 2) (3 . 4)) :test #'eq)) t))
      ((member s '("ANY/TYPE" "EVERY/TYPE") :test #'equal)
       (values (list (list #'eql 2 nil) (list #'eql 2 '(1 2 3))
                     (list #'eql 2 '(2 2)) (list #'eql 9 '(1 2))) t))
      ((equal s "MOVE-STRING-BYTES")
       (values '(("" "" 0 0 0) ("abc" "....." 0 1 3)
                 ("xλ😁y" "...." 1 0 2) ("abc" "XYZ" 2 2 1)) t))
      ((member s '("%SHORT-FLOAT-ZEROP" "%DOUBLE-FLOAT-ZEROP") :test #'equal)
       (values (mapcar (lambda (x) (list (coerce x (if (equal s "%SHORT-FLOAT-ZEROP") 'single-float 'double-float)))) '(0 -0.0d0 1 -1 1/2)) t))
      ((equal s "LIST-LENGTH") (values '((nil) ((1)) ((1 2)) ((1 2 3)) ((1 2 3 4 5 6))) t))
      ((equal s "BYTE-MASK") (values '((0) (1) (7) (29) (30) (64) (127)) t))
      ((equal s "%SIMPLE-STRING=")
       (values '(("" "" 0 0 0 0) ("abc" "xabcx" 0 1 3 4) ("abc" "abd" 0 0 3 3) ("λ😁" "λ😁" 0 0 2 2) ("abc" "ab" 0 0 3 2)) t))
      ((member s '("UTF-8-OCTETS-IN-STRING" "UTF-16-OCTETS-IN-STRING") :test #'equal)
       (values '(("" 0 0) ("abc" 0 3) ("λ😁" 0 2) ("abc" 2 1) ("xλ😁y" 1 3)) t))
      ((equal s "CLONE-TYPE-CLASS-METHODS")
       (values '((#(nil nil) #(1 2)) (#(nil nil :a (1 . 2)) #(0 0 0 0))) t))
      ((equal s "CMP-ARGS-OLD-ARGS") (values '((nil nil 0) ((1 2) (1 2) 2) ((1 3) (1 2) 2) ((1 3) (1 2) 1)) t))
      ((equal s "FIND-STR-PATTERN") (values '(("ab" "xxabyy" 0 0 2 6) ("ab" "aa" 0 0 2 2) ("λ😁" "xλ😁" 0 0 2 3)) t))
      ((equal s "FUNCALL") (values (list (list #'identity 7) (list #'car '(1 2)) (list #'list 1 2)) t))
      ((equal s "APPLY") (values (list (list #'identity '(7)) (list #'list 1 '(2)) (list #'list 1 2 '(3 4))) t))
      ((equal s "CORE-EQL") (values '((1 1) (1 2) (nil nil) (nil (nil)) (1.5s0 1.5d0) (1.5d0 1.5d0) (1/3 1/3) (1152921504606846976 1152921504606846976)) t))
      ((equal s "UNION-EQL") (values '((nil nil) ((1 2) (2 3)) ((1.5d0 1152921504606846976) (1.5d0 7))) t))
      ((equal s "EQUAL-BUT-NO-CAR-RECURSION") (values '((nil nil) ((1 2) (1 2)) ((1 2) (1 3)) (1 2) ((1) nil)) t))
      ((equal s "CPL-INDEX") (values '((1 nil) (1 (1 2)) (2 (1 2 3)) (9 (1 2))) t))
      ((equal s "NEGATE-HI-LO") (values '((0 0) (1 0) (0 1) (7 12)) t))
      ((equal s "FLATTEN-METHOD-LAMBDA-LIST") (values '((nil) ((x (y integer) &optional (z 3))) ((x &aux (z 4)))) t))
      ((equal s "CANONICAL-COMPLEX") (values '((7 0) (1 2) (1/3 2/3)) t))
      ((equal s "ENCODE-FILE-RANGE") (values '((0 0) (1 20) (100 20000) (100000 100100)) t))
      ((equal s "%QUO-1") (values '((1) (-1) (1.0d0) (2.0d0) (-4.0s0)) t))
      ((member s '("%SHORT-FLOAT-PLUSP" "%DOUBLE-FLOAT-PLUSP") :test #'equal)
       (values (mapcar (lambda (x) (list (coerce x (if (equal s "%SHORT-FLOAT-PLUSP") 'single-float 'double-float)))) '(-1 0 1)) t))
      ((equal s "%NEXT-METHOD-P") (values '(((nil nil)) ((nil (1))) ((nil (1 2)))) t))
      ((equal s "%STD-DEVICE-COMPONENT") (values '((nil nil) (:unspecific nil) ("disk" nil) ("disk" :unspecific) ("disk" "host")) t))
      ((equal s "SOURCE-NOTE-FILENAME") (values '((nil) ("test.lisp")) t))
      ((equal s "%REAL-PRINT-STREAM") (values '((:explicit-stream)) t))
      ((equal s "POINTERP") (values '((nil) (7) ((1 . 2))) t))
      ((member s '("MEMBER-TEST" "MEMBER-TEST-NOT") :test #'equal)
       (values (list (list 1 nil #'eql) (list 2 '(1 2 3) #'eql) (list 2 '(1 2 3) #'eq)) t))
      ((member s '("ASSOC-TEST" "ASSOC-TEST-NOT") :test #'equal)
       (values (list (list 1 nil #'eql) (list 2 '(nil (1 . 2) (2 . 3)) #'eql)) t))
      ((member s '("1+" "1-") :test #'equal)
       (values '((0) (1) (-1) (536870911) (-536870912) (1152921504606846976) (1.5s0) (-2.5d0)) t))
      ((equal s "CORE-BYTE-STORE")
       (values (loop for (i v) in '((3 2) (0 255) (1 0) (2 128))
                     collect (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9) i v)) t))
      ((equal s "CORE-POSITIVE-LOOP") (values '((0) (1) (3) (7)) t))
      ((equal s "CORE-IZEROP") (values '((0) (1) (-1) (-536870912) (536870911)) t))
      ((equal s "CORE-NUMERIC-IR") (values '((1.5d0 2.0d0) (-1.5s0 2.0s0) (2.0d0 2.0d0)
                 (6 3) (-6 3) (-536870912 -1)
                 (1329227995784915872903807060280344576 1152921504606846976)) t))
      ((equal s "CORE-ZERO") (values '((0) (1) (-1) (0.0s0) (-0.0d0) (1.5d0) (1152921504606846976)) t))
      ((equal s "CORE-BYTE-ORDER") (values (list (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9))) t))
      ((member s '("CORE-COMPUTED-CALL" "CORE-COMPUTED-INNER" "CORE-COMPUTED-APPLY" "CORE-COMPUTED-INNER-APPLY") :test #'equal) (values (list (list #'identity 7) (list #'car '(1 2))) t))
      ((equal s "SYMBOL-NAME") (values '((nil) (t) (:library-test) (library-test-symbol)) t))
      ((equal s "SYMBOL-PLIST") (values '((library-test-symbol)) t))
      ((equal s "GET") (values '((library-test-symbol :absent) (library-test-symbol :absent 7)) t))
      ((equal s "PUT") (values '((library-put-symbol :key (1 . 2))) t))
      ((member s '("NEED-CHAR-CODE" "UTF-16-CHARACTER-SIZE-IN-OCTETS") :test #'equal)
       (values '((#\Null) (#\A) (#\u+1000) (#\u+1f601)) t))
      ((equal s "REQUIRE-NUMARG") (values '((#\A 1) (#\B 0)) t))
      ((equal s "REQUIRE-NO-NUMARG") (values '((#\A nil)) t))
      ((equal s "CORE-ILOGNOT") (values '((0) (-1) (7) (-536870912) (536870911)) t))
      ((equal s "CORE-FIXNUM-LESS") (values '((-1 0) (0 -1) (1 1) (-536870912 536870911)) t))
      ((equal s "%COPY-U8-TO-STRING")
       (values (loop for (src dst n) in '((0 0 4) (0 4 0) (1 0 3) (0 1 3) (3 3 1) (4 4 0))
                     collect (list (make-array 4 :element-type '(unsigned-byte 8)
                                                 :initial-contents '(0 65 128 255))
                                   src (copy-seq "....") dst n)) t))
      ((equal s "%COPY-STRING-TO-U8")
       (values (loop for (src dst n) in '((0 1 3) (0 0 0) (1 0 2) (2 3 1) (3 4 0) (0 0 3))
                     collect (list "Aλ😁" src
                                   (make-array 4 :element-type '(unsigned-byte 8) :initial-element 99)
                                   dst n)) t))
      ((member s '("CORE-FORMAT-ERROR" "CORE-FORMAT-SIGNAL" "CORE-FORMAT-COLLECT" "CORE-TYPE-ERROR" "CORE-FORMAT-ORDER" "CORE-FORMAT-DECLINE" "CORE-SIMPLE-INITARGS") :test #'equal)
       (values '((nil) ((1 . 2)) (7) ("string")) t))
      ((equal s "CORE-DYNAMIC-FORMAT") (values '(("one ~s" (1 . 2)) ("two ~a" 7)) t))
      ((equal s "CORE-SCHAR") (values '(("abc" 0) ("abc" 2) ("λ😁" 1)) t))
      ((equal s "CORE-SET-CHAR") (values '(("abc" 0 #\Z) ("λ😁" 1 #\A)) t))
      ((equal s "CORE-CHAR-CODE") (values '((#\Null) (#\A) (#\u+1000) (#\u+1f601)) t))
      ((equal s "CORE-CODE-CHAR") (values '((0) (65) (55295) (55296) (57343) (57344) (128513) (1114111)) t))
      ((member s '("CORE-GVECTOR" "CORE-STRUCT" "CORE-SLOT" "CORE-CLEANUP" "CORE-TRANSFER") :test #'equal)
       (values '(((1 . 2)) ((3 4))) t))
      ((equal s "CORE-REF") (values '((#((1 . 2) (3 . 4)))) t))
      ((equal s "CORE-SET") (values '((#((1 . 2) 7) (3 . 4))) t))
      ((member s '("FUNCTIONP" "LFUNP") :test #'equal)
       (values (list (list nil) (list 7) (list #'car) (list '(1 2))) t))
      ;; Symbols have a dedicated tag on x86-64, but are node vectors on D1.
      ;; Compare representation predicates only on their shared domain here.
      ((member s '("GVECTORP" "MISCOBJP" "UVECTORP" "IVECTORP") :test #'equal)
       (values '((nil) (0) (-1) ((1 . 2)) (#\A) ("abc") (#(1 2)) (#*101)) t))
      ((member s '("SYMBOLP" "SYMBOL-ARG-P" "NON-NIL-SYMBOL-P" "NON-NIL-SYMBOLP"
                   "CONSP" "LISTP" "ARRAYP" "VECTORP" "SEQUENCEP" "ATOM"
                   "FIXNUMP" "BIGNUMP" "INTEGERP" "RATIOP" "RATIONALP" "REALP" "NUMBERP"
                   "SHORT-FLOAT-P" "DOUBLE-FLOAT-P" "FLOATP" "COMPLEXP"
                   "COMPLEX-SINGLE-FLOAT-P" "COMPLEX-DOUBLE-FLOAT-P"
                   "SIMPLE-BASE-STRING-P" "SIMPLE-STRING-P" "SIMPLE-VECTOR-P" "SIMPLE-BIT-VECTOR-P"
                   "CHARACTERP" "BASE-CHAR-P" "EXTENDED-CHAR-P" "PACKAGEP" "STRUCTUREP"
                   "ISTRUCTP" "ISTRUCT-TYPE-NAME" "BASIC-STREAM-P" "STANDARD-INSTANCE-P"
                   "MACPTRP" "DEAD-MACPTR-P" "GVECTORP" "IVECTORP" "MISCOBJP" "UVECTORP"
                   "FUNCTIONP" "LFUNP" "BITP" "UNSIGNED-BYTE-P"
                   "UNSIGNED-BYTE-8-P" "SIGNED-BYTE-8-P" "UNSIGNED-BYTE-16-P" "SIGNED-BYTE-16-P"
                   "UNSIGNED-BYTE-32-P" "SIGNED-BYTE-32-P" "QUOTED-FORM-P" "LAMBDA-EXPRESSION-P")
               :test #'equal)
       (values (mapcar (lambda (x) (if (equal s "SYMBOL-ARG-P") (list x t) (list x)))
                       '(nil t 0 1 -1 127 128 255 256 32767 65536 -536870912 536870911
                         1208925819614629174706176 -1208925819614629174706176
                         1/3 -5/7 #c(1/3 2/3) 0.0s0 -1.5s0 0.0d0 3.25d0 :test (1 . 2) (1 2 3) #\A #\u+1000 "abc" #(1 2) #*101)) t))
      ((member s '("%REQUIRE-TYPE-BUILTIN" "%REQUIRE-TYPE-CLASS-CELL" "STRUCTURE-TYPEP" "ISTRUCT-TYPEP") :test #'equal)
       (values '((nil nil) (7 :type) (:test :type) ((1 2) :type)) t))
      ((member s '("EQ" "MAX-2" "MIN-2" "%IMAX" "%IMIN" "/=-2" ">=-2" "<=-2") :test #'equal)
       (values (append '((1 1) (-7 3) (9 4) (0 -1))
                       (unless (member s '("EQ" "%IMAX" "%IMIN") :test #'equal)
                         '((1.5d0 2.5d0) (-3.0s0 1) (1208925819614629174706176 7)))) t))
      ((member s '("CAR" "CDR" "CAAR" "CADR" "CDAR" "CDDR" "CAAAR" "CAADR" "CADAR" "CADDR" "CDAAR" "CDADR" "CDDAR" "CDDDR") :test #'equal)
       (values '((nil) ((((1 . 2) . (3 . 4)) . ((5 . 6) . (7 . 8))))) t))
      ((member s '("COPY-TREE" "IDENTITY") :test #'equal)
       (values '((nil) (7) ((1 (2 . 3) 4))) t))
      ((member s '("MEMQ" "ADJOIN-EQ" "CPL-MEMQ") :test #'equal)
       (values '((1 nil) (1 (1 2)) (2 (1 2 3)) (4 (1 2))) t))
      ((member s '("MEMEQL" "ADJOIN-EQL") :test #'equal)
       (values '((1 nil) (2 (1 2 3)) (1/3 (2/3 1/3)) (#\A (#\B #\A))
                 (1152921504606846976 (1 1152921504606846976))) t))
      ((equal s "%PL-SEARCH") (values '(((1 2 3 4) 1) ((1 2 3 4) 3) ((1 2) 7) (nil 1)) t))
      ((member s '("APPEND-2" "UNION-EQ" "NRECONC") :test #'equal)
       (values '((nil nil) ((1 2) nil) (nil (3 4)) ((1 2) (3 4))) t))
      ((equal s "APPEND") (values '(nil ((1 2)) ((1 2) (3 4) (5 6))) t))
      ((equal s "LIST") (values '(nil (1) (1 2 3)) t))
      ((equal s "LIST*") (values '((nil) (1 2) (1 2 (3 4))) t))
      ((member s '("LIST-REVERSE" "LIST-NREVERSE" "FINAL-CONS") :test #'equal)
       (values '((nil) ((1)) ((1 2 3))) t))
      ((equal s "NREMOVE") (values '((1 (1 2 1 3)) (7 (1 2 3))) t))
      ((equal s "REMOVE-FROM-ALIST") (values '((1 ((1 . 2) (3 . 4))) (7 ((1 . 2)))) t))
      ((equal s "HEAP-AREA-NAME") (values (loop for n from 0 to 12 collect (list n)) t))
      ((equal s "FIND-BUILTIN-CELL") (values '((integer) (:absent) (nil t)) t))
      ((equal s "INDEX->VECTOR-INDEX") (values '((0) (1) (7)) t))
      ((member s '("%SIMPLE-FASL-INIT-BUFFER" "CHARACTER-ENCODED-IN-SINGLE-OCTET"
                   "TWO-OCTETS-PER-CHARACTER" "FOUR-OCTETS-PER-CHARACTER") :test #'equal)
       (values '((nil) (#\A) (#\u+1000)) t))
      ((member s '("8-BIT-FIXED-WIDTH-OCTETS-IN-STRING" "UCS-2-OCTETS-IN-STRING" "UCS-4-OCTETS-IN-STRING"
                   "8-BIT-FIXED-WIDTH-LENGTH-OF-VECTOR-ENCODING" "8-BIT-FIXED-WIDTH-LENGTH-OF-MEMORY-ENCODING") :test #'equal)
       (values '((nil 1 8) (nil 7 3) (nil 3 3)) t))
      ((member s '("DEF-INFO.LFBITS" "DEF-INFO.KEYVECT" "DEF-INFO.FILE" "DEF-INFO.METHODS" "DEF-INFO.MACRO-P"
                   "DEF-INFO.FUNCTION-P" "DEF-INFO.DEFTYPE" "DEF-INFO.DEFTYPE-TYPE") :test #'equal)
       (values '((nil) (#(12 :key :file (:methods 1 2))) (#((12 . :source) :key :file (ccl::macro)))) t))
      ((equal s "DEF-INFO-METHOD.KEYVECT") (values '(((((:a :b) . :file))) (((7 . :file)))) t))
      ((equal s "DEF-INFO-METHOD.FILE") (values '((((7 . :file))) (((nil . :other)))) t))
      ((equal s "BOOTSTRAPPING-RECORD-SOURCE-FILE") (values '((nil) (7 nil)) t))
      ((equal s "SLOT-ID-LOOKUP-NO-SLOTS") (values '((nil nil) (7 :test)) t))
      ((equal s "%TYPE-ERROR-TYPE") (values '((:test) ((integer 0 7)) (0) (4) (16) (27)) t))
      ((equal s "%MAKE-RATIO") (values '((1 3) (-5 7)) t))
      ((equal s "%MAKE-COMPLEX") (values '((1 3) (-5 7)) t))
      ((member s '("DEFAULT-PRINT-LEVEL" "DEFAULT-PRINT-LENGTH" "DEFAULT-PRINT-STRING-LENGTH") :test #'equal)
       (values '((:default) (nil) (7)) t))
      ((member s '("LOADING-FILE-SOURCE-FILE"
                   "PRELOAD-ALL-FUNCTIONS" "LISP-IMPLEMENTATION-TYPE") :test #'equal)
       (values '(nil) t))
      (t (values nil nil)))))

(defparameter *funcallable-prior-executions*
  '("%%STR-MEMBER" "%ARRAY-HEADER-SIMPLE-P" "%ARRAY-HEADER-SUBTYPE" "%ARRAY-INDEX" "%ARRAY-IS-HEADER" "%BADARG" "%BIG-ENDIAN-U8-REF-U16" "%BIG-ENDIAN-U8-REF-U32" "%CHAR-CODE-CASE-FOLD" "%CHAR-CODE-DOWNCASE" "%CHAR-CODE-UPCASE" "%CHARACTER-ATTRIBUTE" "%CONS-DEF-INFO-METHOD" "%COPY-STRING-TO-U8" "%COPY-U8-TO-STRING" "%DOUBLE-FLOAT*-2!" "%DOUBLE-FLOAT+-2!" "%DOUBLE-FLOAT--2!" "%DOUBLE-FLOAT-ACOS!" "%DOUBLE-FLOAT-ASIN!" "%DOUBLE-FLOAT-ATAN!" "%DOUBLE-FLOAT-ATAN2!" "%DOUBLE-FLOAT-COS!" "%DOUBLE-FLOAT-COSH!" "%DOUBLE-FLOAT-EXP!" "%DOUBLE-FLOAT-EXPT!" "%DOUBLE-FLOAT-LOG!" "%DOUBLE-FLOAT-PLUSP" "%DOUBLE-FLOAT-SIN!" "%DOUBLE-FLOAT-SINH!" "%DOUBLE-FLOAT-TAN!" "%DOUBLE-FLOAT-TANH!" "%DOUBLE-FLOAT-ZEROP" "%DOUBLE-FLOAT/-2!" "%EARLY-PREPARE-TO-DESTRUCTURE" "%EPUSHVAL" "%FILE-KIND" "%FIXNUM-DFLOAT" "%FIXNUM-SFLOAT" "%GET-READTABLE-CHAR" "%GROW-HASH-TABLE-IN-PLACE-P" "%IMAX" "%IMIN" "%INVALID-METHOD-ERROR" "%IOBLOCK-INPUT-FILE-LENGTH" "%IOBLOCK-UNTYI" "%KERNEL-GLOBAL-OFFSET-FORM" "%KEYWORD-PRESENT-P" "%LIST-TO-UVECTOR" "%LITTLE-ENDIAN-U8-REF-U16" "%LITTLE-ENDIAN-U8-REF-U32" "%MAKE-COMPLEX" "%MAKE-FOREIGN-CTYPE" "%MAKE-MEMBER-CTYPE" "%MAKE-RATIO" "%MAKE-RESTART" "%MAYBE-MAKE-RATIO" "%MISC-REF" "%MISC-SET" "%NEXT-METHOD-P" "%NON-EMPTY-ENVIRONMENT-P" "%PATH-MEM" "%PATH-MEM-LAST" "%PATH-MEM-LAST-QUOTED" "%PATH-ONE-QUOTED-P" "%PATH-QUOTED-P" "%PATHNAME-HOST" "%PATHNAME-VERSION" "%PKG-REF-FIND-PACKAGE" "%PL-SEARCH" "%PROCLAIM-SPECIAL" "%PROGVRESTORE" "%PV-MAP-LOOKUP" "%QUO-1" "%REAL-PRINT-STREAM" "%SCHARCODE" "%SET-FILL-POINTER" "%SET-SCHARCODE" "%SET-SIMPLE-ARRAY-P" "%SET-SYM-GLOBAL-VALUE" "%SET-SYM-VALUE" "%SET-SYMBOL-PACKAGE" "%SHORT-FLOAT-PLUSP" "%SHORT-FLOAT-ZEROP" "%SIMPLE-FASL-INIT-BUFFER" "%SIMPLE-STRING=" "%STD-DEVICE-COMPONENT" "%STR-MEMBER" "%STRING=" "%SYM-GLOBAL-VALUE" "%SYM-VALUE" "%SYMBOL-BITS" "%TYPE-ERROR-TYPE" "%VECTOR-MEMBER" "%VECTOR-OUTPUT-STREAM-CLOSE" "*" "*%SAVED-METHOD-VAR%*" "+" "-" "/" "/=" "/=-2" "1+" "1-" "8-BIT-FIXED-WIDTH-LENGTH-OF-MEMORY-ENCODING" "8-BIT-FIXED-WIDTH-LENGTH-OF-VECTOR-ENCODING" "8-BIT-FIXED-WIDTH-OCTETS-IN-STRING" "<" "<=" "<=-2" "=" ">" ">=" ">=-2" "ADD-ACCESSOR-TYPES" "ADD-FORMAT-CHAR" "ADD-TO-ALIST" "ADJOIN-ASSQ" "ADJOIN-EQ" "ADJOIN-EQL" "ADJUSTABLE-ARRAY-P" "ALIST-ADJOIN" "ALT-LIST-LENGTH" "ANY/TYPE" "APPEND" "APPEND-2" "APPLY" "ARRAY-CTYPE-P" "ARRAY-DATA-OFFSET-SUBTYPE" "ARRAY-DIMENSIONS" "ARRAY-DISPLACEMENT" "ARRAY-ELEMENT-SUBTYPE" "ARRAY-ELEMENT-TYPE" "ARRAY-HAS-FILL-POINTER-P" "ARRAY-RANK" "ARRAY-TOTAL-SIZE" "ARRAYP" "ASSEQL" "ASSOC-TEST" "ASSOC-TEST-NOT" "ASSQ" "ATOM" "BASE-CHAR-P" "BASE-STRING-P" "BASIC-STREAM-P" "BIGNUMP" "BIT-VECTOR-P" "BITP" "BOOTSTRAPPING-RECORD-SOURCE-FILE" "BOUNDP" "BYTE" "BYTE-MASK" "CAAAR" "CAADR" "CAAR" "CADAR" "CADDR" "CADR" "CANONICAL-COMPLEX" "CAR" "CDAAR" "CDADR" "CDAR" "CDDAR" "CDDDR" "CDDR" "CDR" "CHAR-DOWNCASE" "CHAR-UPCASE" "CHARACTER-ENCODED-IN-SINGLE-OCTET" "CHARACTERP" "CHEAP-CONS" "CHEAP-COPY-LIST" "CHEAP-FREE-LIST" "CHEAP-LIST" "CHECK-SEQUENCE-BOUNDS" "CLASS-CTYPE-P" "CLEAR-GF-DISPATCH-TABLE" "CLEAR-LOCK-ACQUISITION-STATUS" "CLEAR-SEMAPHORE-NOTIFICATION-STATUS" "CLONE-TYPE-CLASS-METHODS" "CMP-ARGS-OLD-ARGS" "COERCE-TO-VALUES" "COMMAND-LINE-ARGUMENTS" "COMPILE-FILE-ENVIRONMENT-P" "COMPILER-SPECIAL-FORM-P" "COMPLEX-ARRAY-P" "COMPLEX-DOUBLE-FLOAT-P" "COMPLEX-SINGLE-FLOAT-P" "COMPLEXP" "CONGRUENT-LFBITS-P" "CONS-CTYPE-P" "CONS-PATHNAME" "CONSP" "CONSTANT-CTYPE-P" "CONSTANT-SYMBOL-P" "CONTAINS-NON-T-SPECIALIZER?" "COPY-TREE" "CORE-ARCH-COPY-ORDER" "CORE-ARCH-DOUBLE" "CORE-ARCH-IDENTITY" "CORE-ARCH-RATIO" "CORE-ARCH-SINGLE" "CORE-ARCH-SYMBOL-IDENTITY" "CORE-ASSQ" "CORE-ASSQ-IDENTITY" "CORE-AUX" "CORE-BADARG" "CORE-BYTE-ORDER" "CORE-BYTE-STORE" "CORE-CHAR-CODE" "CORE-CLEANUP" "CORE-CODE-CHAR" "CORE-COERCE-DOUBLE" "CORE-COERCE-SINGLE" "CORE-COMPUTED-APPLY" "CORE-COMPUTED-CALL" "CORE-COMPUTED-INNER" "CORE-COMPUTED-INNER-APPLY" "CORE-DIVIDE-ORDER" "CORE-DIVIDE-ZERO" "CORE-DYNAMIC-FORMAT" "CORE-EQL" "CORE-FIXNUM-LESS" "CORE-FORMAT-COLLECT" "CORE-FORMAT-DECLINE" "CORE-FORMAT-ERROR" "CORE-FORMAT-ORDER" "CORE-FORMAT-SIGNAL" "CORE-GLOBAL-CELL" "CORE-GVECTOR" "CORE-HOST-ACTION" "CORE-HOST-COUNT" "CORE-HOST-CPU-CACHE" "CORE-HOST-CPU-WARM" "CORE-HOST-ENV" "CORE-HOST-TIME" "CORE-HOST-TIMED-CALLER" "CORE-HOST-WAIT-CALLER" "CORE-HYPER-ACOSH-CONDITION32" "CORE-HYPER-ACOSH-CONDITION64" "CORE-HYPER-ATANH-CONDITION32" "CORE-HYPER-ATANH-CONDITION64" "CORE-ILOGNOT" "CORE-INTEGER-DIVIDE" "CORE-IZEROP" "CORE-LDB" "CORE-LEXPR" "CORE-LEXPR-ZERO" "CORE-LIBM-ACOS32" "CORE-LIBM-ACOS64" "CORE-LIBM-ACOSH32" "CORE-LIBM-ACOSH64" "CORE-LIBM-ASIN32" "CORE-LIBM-ASIN64" "CORE-LIBM-ASINH32" "CORE-LIBM-ASINH64" "CORE-LIBM-ATAN232" "CORE-LIBM-ATAN264" "CORE-LIBM-ATAN32" "CORE-LIBM-ATAN64" "CORE-LIBM-ATANH32" "CORE-LIBM-ATANH64" "CORE-LIBM-COS32" "CORE-LIBM-COS64" "CORE-LIBM-COSH32" "CORE-LIBM-COSH64" "CORE-LIBM-EXP32" "CORE-LIBM-EXP64" "CORE-LIBM-EXPT32" "CORE-LIBM-EXPT64" "CORE-LIBM-LOG32" "CORE-LIBM-LOG64" "CORE-LIBM-SIN32" "CORE-LIBM-SIN64" "CORE-LIBM-SINH32" "CORE-LIBM-SINH64" "CORE-LIBM-TAN32" "CORE-LIBM-TAN64" "CORE-LIBM-TANH32" "CORE-LIBM-TANH64" "CORE-LIST-STAR" "CORE-LOG-CONDITION" "CORE-LOGBITP" "CORE-LOGICAL" "CORE-LOGICAL-ERROR" "CORE-MAKE-LIST" "CORE-MAKE-OCTETS" "CORE-MAKE-STRING" "CORE-MAKE-VECTOR" "CORE-MINUS1" "CORE-NATURAL-LEFT" "CORE-NATURAL-RIGHT" "CORE-NTH-VALUE" "CORE-NUMERIC-IR" "CORE-POSITIVE-LOOP" "CORE-REF" "CORE-REGISTER" "CORE-REQUIRE-INTEGER" "CORE-RETRY-LIST" "CORE-RETRY-VECTOR" "CORE-S16" "CORE-S32" "CORE-S8" "CORE-SCHAR" "CORE-SET" "CORE-SET-CHAR" "CORE-SHIFT-LEFT-DOMAIN" "CORE-SHIFT-RIGHT-DOMAIN" "CORE-SHIFT-SIGNED-DOMAIN" "CORE-SHIFTS" "CORE-SIGNED-ZERO-LITERAL" "CORE-SIGNED-ZERO-VARIABLE" "CORE-SIMPLE-INITARGS" "CORE-SLOT" "CORE-STRUCT" "CORE-SUBTRACT-CALL" "CORE-SYMBOL-STATE" "CORE-TRANSCEND-CONDITION" "CORE-TRANSCEND-DESTINATION" "CORE-TRANSFER" "CORE-TYPE-ERROR" "CORE-TYPE-TESTS" "CORE-U16" "CORE-U32" "CORE-UVREF" "CORE-UVSET" "CORE-UVSET-CHECKED" "CORE-VECTOR" "CORE-WORD-AND-MASK" "CORE-WORD-OR-MASK" "CORE-WORD-XOR-MASK" "CORE-ZERO" "CPL-INDEX" "CPL-MEMQ" "CPU-COUNT" "CYGPATH" "DEAD-MACPTR-P" "DECODE-FILE-RANGE" "DEF-INFO-METHOD.FILE" "DEF-INFO-METHOD.KEYVECT" "DEF-INFO.DEFTYPE" "DEF-INFO.DEFTYPE-TYPE" "DEF-INFO.FILE" "DEF-INFO.FUNCTION-P" "DEF-INFO.KEYVECT" "DEF-INFO.LFBITS" "DEF-INFO.MACRO-P" "DEF-INFO.METHODS" "DEFAULT-PRINT-LENGTH" "DEFAULT-PRINT-LEVEL" "DEFAULT-PRINT-STRING-LENGTH" "DEFINITION-ENVIRONMENT" "DISPLACED-ARRAY-P" "DOUBLE-FLOAT-P" "ENCODE-FILE-RANGE" "EQ" "EQUAL-BUT-NO-CAR-RECURSION" "EVENT-TICKS" "EVERY/TYPE" "EXTENDED-CHAR-P" "EXTERNAL-ENTRY-POINT-P" "FILL-POINTER" "FINAL-CONS" "FIND-GF-DISPATCH-TABLE-INDEX" "FIND-NAMED-PERIODIC-TASK" "FIND-STR-PATTERN" "FIXNUMP" "FLATTEN-METHOD-LAMBDA-LIST" "FLOAT" "FLOAT-FORMAT-MAX" "FLOAT-FORMAT-NAME" "FLOATP" "FOREIGN-CTYPE-P" "FOUR-OCTETS-PER-CHARACTER" "FREE-CONS" "FROZEN-DEFINITION-P" "FULLTAG" "FUNCALL" "FUNCTION-CTYPE-P" "FUNCTION-TYPE-NARGS" "FUNCTIONP" "GC-RETAIN-PAGES" "GC-RETAINING-PAGES" "GC-VERBOSE" "GC-VERBOSE-P" "GET" "GET-*PRINT-BASE*" "GET-*PRINT-CASE*" "GET-MACRO-CHARACTER" "GET-PROPERTIES" "GET-TYPE-PREDICATE" "GET-UNIVERSAL-TIME" "GETENV" "GETF" "GETF-TEST" "GVECTORP" "HAIRY-CTYPE-P" "HASH-TABLE-P" "HEAP-AREA-NAME" "HI-LO-FRACTION-P" "IDENTITY" "INDEX->VECTOR-INDEX" "INIT-CLASS-CELL-INSTANTIATOR" "INPUT-STREAM-ARG" "INSTALL-IOBLOCK-INPUT-LINE-TERMINATION" "INSTALL-IOBLOCK-OUTPUT-LINE-TERMINATION" "INTEGER-DECODE-DENORM-SHORT-FLOAT" "INTEGERP" "INTERSECTION-CTYPE-P" "INVALID-HASH-KEY-P" "IOBLOCK-ELEMENTS-TO-OCTETS" "IOBLOCK-INPOS" "IOBLOCK-NO-BINARY-INPUT" "IOBLOCK-NO-BINARY-OUTPUT" "IOBLOCK-NO-CHAR-INPUT" "IOBLOCK-NO-CHAR-OUTPUT" "IOBLOCK-OCTETS-TO-ELEMENTS" "IOBLOCK-OUTPOS" "ISTRUCT-TYPE-NAME" "ISTRUCT-TYPEP" "ISTRUCTP" "IVECTORP" "LAMBDA-EXPRESSION-P" "LAST" "LDB32" "LENGTH" "LFUNP" "LISP-IMPLEMENTATION-TYPE" "LISP-THREAD-P" "LISPTAG" "LIST" "LIST*" "LIST-LENGTH" "LIST-NREVERSE" "LIST-REVERSE" "LISTP" "LOADING-FILE-SOURCE-FILE" "LOCK-ACQUISITION-STATUS" "LOCK-FREE-HASH-TABLE-COUNT" "LOCKP" "LOGAND" "LOGICAL-PATHNAME-P" "LOGIOR" "LOGXOR" "LOWER-CASE-P" "LSH" "MACPTRP" "MAKE-APPLICATION-ERROR-HANDLER" "MAKE-CLASS-CTYPE" "MAKE-CONSTANT-CTYPE" "MAKE-FUNCTION-CTYPE" "MAKE-HAIRY-CTYPE" "MAKE-INTERSECTION-CTYPE" "MAKE-KEY-INFO" "MAKE-NEGATION-CTYPE" "MAKE-NUMERIC-CTYPE-PREDICATE" "MAKE-RESTART" "MAKE-UNKNOWN-CTYPE" "MAKE-VALUES-CTYPE" "MASK-FIELD" "MAX" "MAX-2" "MEMBER-CTYPE-P" "MEMBER-TEST" "MEMBER-TEST-NOT" "MEMEQL" "MEMQ" "MERGE-LISTS*-NO-KEY" "MIN" "MIN-2" "MISCOBJP" "MISSING-TYPE-METHOD" "MOVE-STRING-BYTES" "MULTIPLY-FIXNUMS" "NAMED-CTYPE-P" "NATIVE-CLASS-P" "NEED-CHAR-CODE" "NEED-USE-EQL" "NEGATE-HI-LO" "NEGATION-CTYPE-P" "NEW-DEFINITION-ENVIRONMENT" "NEW-LEXICAL-ENVIRONMENT" "NHASH.VECTOR-SIZE" "NON-NIL-SYMBOL-P" "NON-NIL-SYMBOLP" "NOT-IN-CURRENT-PROCESS" "NOTE-VARIABLE-INFO" "NRECONC" "NREMOVE" "NTH" "NTHCDR" "NUMBERP" "NUMERIC-CTYPE-P" "NUMERIC-TYPES-ADJACENT" "OBJECT-IN-APPLICATION-HEAP-P" "PACKAGEP" "PATH-STR-MATCH-P" "PATH-STR-SUB" "PATHNAMEP" "PERIODIC-TASK-INTERVAL" "PL-SEARCH" "PLISTP" "POINTERP" "PRELOAD-ALL-FUNCTIONS" "PROCESS-SINGLE-SELECTION" "PROCLAIMED-IGNORE-P" "PROCLAIMED-SPECIAL-P" "PROPER-LIST-P" "PROPER-SEQUENCE-P" "PUT" "PV-MAP-LOOKUP" "QUOTED-FORM-P" "RANDOM-STATE-P" "RASSOC" "RATIONALP" "RATIOP" "READ-WRITE-LOCK-P" "READ-WRITE-LOCK-PTR" "READTABLE-ARG" "READTABLEP" "REALP" "RECURSIVE-LOCK-P" "RECURSIVE-LOCK-PTR" "REGISTER-ISTRUCT-CELL" "REMOVE-FROM-ALIST" "REQUIRE-GLOBAL-SYMBOL" "REQUIRE-NO-NUMARG" "REQUIRE-NUMARG" "RESTARTP" "ROTATE-HASH-CODE" "SCHAR" "SEMAPHORE-NOTIFICATION-STATUS" "SEMAPHOREP" "SEQUENCE-TYPE" "SEQUENCEP" "SET-*%SAVED-METHOD-VAR%*" "SET-EVENT-TICKS" "SET-ISTRUCT-CELL-INFO" "SET-SCHAR" "SET-TYPE-PREDICATE" "SETPROP" "SHORT-FLOAT-P" "SHUTDOWN-LISP-THREADS" "SIGNAL-SEMAPHORE" "SIGNED-BYTE-16-P" "SIGNED-BYTE-32-P" "SIGNED-BYTE-8-P" "SIMPLE-ARRAY-P" "SIMPLE-BASE-STRING-P" "SIMPLE-BIT-VECTOR-P" "SIMPLE-STRING-P" "SIMPLE-VECTOR-P" "SLOT-ID-LOOKUP-NO-SLOTS" "SORT-LIST-ERROR" "SOURCE-NOTE-FILENAME" "SPARSE-VECTOR-REF" "SPECIALIZED-ELEMENT-TYPE-MAYBE" "STANDARD-INSTANCE-P" "STRING-INPUT-STREAM-CHARACTER-READ-VECTOR" "STRING-INPUT-STREAM-IOBLOCK-PEEK-CHAR" "STRING-INPUT-STREAM-IOBLOCK-READ-CHAR" "STRING-INPUT-STREAM-IOBLOCK-UNREAD-CHAR" "STRINGP" "STRUCTURE-TYPEP" "STRUCTUREP" "SYMBOL-ARG" "SYMBOL-ARG-P" "SYMBOL-BINDING-INDEX" "SYMBOL-NAME" "SYMBOL-PACKAGE" "SYMBOL-PLIST" "SYMBOLP" "THREAD-EXHAUSTED-P" "THREAD-PRESET" "THREAD-TOTAL-RUN-TIME" "TIMED-WAIT-ON-SEMAPHORE" "TOKEN2INT" "TOPLEVEL" "TRUNCATING-STRING-OUTPUT-STREAM-IOBLOCK-WRITE-CHAR" "TRUNCATING-STRING-OUTPUT-STREAM-IOBLOCK-WRITE-SIMPLE-STRING" "TRUNCATING-STRING-OUTPUT-STREAM-TRUNCATED-P" "TWO-OCTETS-PER-CHARACTER" "TYPE-CLASS-OR-LOSE" "TYPE-MIGHT-CONTAIN-OTHER-TYPES-P" "TYPECODE" "UCS-2-OCTETS-IN-STRING" "UCS-4-OCTETS-IN-STRING" "UCS-4-STREAM-DECODE" "UNDEFINE-CONSTANT" "UNION-CTYPE-P" "UNION-EQ" "UNION-EQL" "UNKNOWN-CTYPE-P" "UNSIGNED-BYTE-16-P" "UNSIGNED-BYTE-32-P" "UNSIGNED-BYTE-8-P" "UNSIGNED-BYTE-P" "UPGRADED-COMPLEX-PART-TYPE" "USING-LINEAR-SCAN" "UTF-16-CHARACTER-SIZE-IN-OCTETS" "UTF-16-OCTETS-IN-STRING" "UTF-8-OCTETS-IN-STRING" "UVECTORP" "VALID-CHAR-CODE-P" "VALUES-CTYPE-P" "VALUES-TYPE-TYPES" "VECTOR" "VECTOR-INDEX->INDEX" "VECTORP" "WAIT-ON-SEMAPHORE" "WASM-HOST-SERVICE" "WHITESPACEP" "YIELD"))

(defvar *funcallable-deferred-inputs* nil)

(defun core-inputs (name)
  ;; Old speculative class-cell recipes did not run while their dependencies
  ;; were missing. A closed call graph does not make NIL a native class cell.
  (when (and (find name *core-records* :key #'second)
             (equal (first (find name *core-records* :key #'second)) "ccl:level-1;l1-clos-boot.lisp")
             (not (member (symbol-name name) *funcallable-prior-executions* :test #'equal))
             (not (member name '(ccl::%generic-function-name
                                 ccl::%generic-function-method-combination
                                 ccl::%generic-function-method-class))))
    (pushnew name *funcallable-deferred-inputs*)
    (return-from core-inputs (values nil nil)))
  (multiple-value-bind (members present) (witness-inputs name)
    (multiple-value-bind (previous covered) (prior-inputs name)
(multiple-value-bind (new tested) (more-inputs name)
        (values (append members previous new) (or present covered tested))))))
