(in-package :wasm32-compiler)

;; Compile through CCL's file environment with the integrated wasm32 backend.
;; No native image object is copied into the target.
(setq *pool-symbol-owners* nil)
(let* ((out (ccl:getenv "FILES_OUTPUT"))
       (source (ccl:getenv "FILES_SOURCE"))
       (*core-modules* nil) (*core-records* nil) (*core-files* nil)
       (*validation-wire-prefix* "file")
       (*b-cpl-conditions* nil))
  (core-compile-file (concatenate 'string source "w32-files.lisp"))
  (core-compile-file (concatenate 'string source "callers.lisp"))
  (dolist (row *core-records*)
    (unless (eq (fourth row) :admitted) (error "File primitive refused: ~s" row)))
  (let ((modules (remove-if-not (lambda (m) (getf m :source-name)) (reverse *core-modules*))))
    (assert (= (length modules) 12))
    (with-open-file (s (concatenate 'string out "modules.json")
                       :direction :output :if-exists :supersede)
      (write-char #\[ s)
      (loop for m in modules for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"definition\":~s,\"function\":~s,\"symbols\":["
                (getf m :name) (symbol-name (getf m :source-name))
                (frontend-owner (getf m :source-name)))
        (loop for (symbol wire) in (getf m :symbols) for j from 0 do
          (unless (zerop j) (write-char #\, s))
          (format s "[~s,~s]" wire (frontend-owner symbol)))
        (write-string "],\"dependencies\":[" s)
        (loop for symbol in (getf m :dependencies) for j from 0 do
          (unless (zerop j) (write-char #\, s))
          (unless (or (eq symbol 'ccl::%wasm-file-request)
                      (find symbol modules :key (lambda (x) (getf x :source-name))))
            (error "Missing file primitive callee: ~s" symbol))
          (format s "~s" (symbol-name symbol)))
        (write-string "]}" s))
      (write-char #\] s))
    (dolist (m modules)
      (with-open-file (s (concatenate 'string out (getf m :name) ".wat")
                         :direction :output :if-exists :supersede)
        (write-string (getf m :wat) s)))
    (with-open-file (s (concatenate 'string out "pools.json")
                       :direction :output :if-exists :supersede)
      (let ((roots (mapcar (lambda (m) (getf m :pool)) modules)))
        (frontend-pool-owners roots)
        (write-pool-graph s roots)))
    (frontend-owner 'ccl::%wasm-file-request)
    (frontend-write-owners out)
    (format t "NAMESPACE-COMPILE-PASS ~d~%" (length modules))))
(ccl:quit)
