(in-package :ccl)
(defun namespace-json (value stream)
  (cond ((null value) (write-string "null" stream))
        ((eq value t) (write-string "true" stream))
        ((stringp value)
         (write-char #\" stream)
         (loop for char across value
               for code = (char-code char)
               do (case char
                    (#\" (write-string "\\\"" stream))
                    (#\\ (write-string "\\\\" stream))
                    (t (if (< code 32)
                         (format stream "\\u~4,'0x" code)
                         (write-char char stream)))))
         (write-char #\" stream))
        ((vectorp value)
         (write-char #\[ stream)
         (dotimes (i (length value))
           (unless (zerop i) (write-char #\, stream))
           (namespace-json (aref value i) stream))
         (write-char #\] stream))
        ((integerp value) (format stream "~d" value))
        (t (error "Unencodable result ~s" value))))

