(in-package :ccl)
(load (concatenate 'string (getenv "FILES_SOURCE") "json.lisp"))
(defvar *files-root* (getenv "NAMESPACE_ROOT"))
(defun files-path (path) (concatenate 'string *files-root* path))
(defun files-read (fd buffer count)
  (%stack-block ((pointer (max 1 count)))
    (dotimes (i count) (setf (%get-unsigned-byte pointer i) (aref buffer i)))
    (let ((result (fd-read fd pointer count)))
      (dotimes (i count) (setf (aref buffer i) (%get-unsigned-byte pointer i)))
      result)))

;; Only the macptr/octet-vector ABI differs. All file operations below call
;; the untouched native primitives, including close during nonlocal cleanup.
(defun files-read-close (path buffer)
  (let ((fd (fd-open path 0)))
    (unwind-protect
        (values (files-read fd buffer 3) (fd-tell fd) (fd-size fd))
      (fd-close fd))))
(load (concatenate 'string (getenv "FILES_SOURCE") "callers.lisp"))
(cwd (files-path "/ccl/"))

(let ((handles (make-hash-table :test 'equal)) (rows nil)
      (cases (with-open-file (s (getenv "FILES_CASES")) (read s))))
  (unwind-protect
      (dolist (row cases)
        (destructuring-bind (op &rest args) row
          (let ((value nil) (name (first args)))
            (cond
              ((equal op "open")
               (let ((fd (fd-open (files-path (second args)) (or (third args) 0))))
                 (setf (gethash name handles) fd)
                 (setq value (if (minusp fd) fd t))))
              ((member op '("read" "read-cap") :test #'equal)
               (let ((buffer (make-array (second args) :element-type '(unsigned-byte 8)
                                         :initial-element 219)))
                 (setq value (vector (files-read (gethash name handles) buffer (second args)) buffer))
                 (when (equal op "read-cap")
                   (setq value (vector (aref value 0) buffer (fd-tell (gethash name handles)))))))
              ((equal op "seek") (setq value (vector (fd-lseek (gethash name handles) (second args) (third args)))))
              ((equal op "tell") (setq value (vector (fd-tell (gethash name handles)))))
              ((equal op "size") (setq value (vector (fd-size (gethash name handles)))))
              ((equal op "close") (setq value (vector (fd-close (gethash name handles)))))
              ((equal op "realpath")
               (let ((path (%realpath (if (equal name "") "" (files-path name)))))
                 (setq value (vector (and path (subseq path (length *files-root*)))))))
              ((equal op "kind")
               (let ((kind (%unix-file-kind (files-path name))))
                 (setq value (vector (and kind (concatenate 'string ":" (symbol-name kind)))))))
              ((equal op "read-close")
               (let ((buffer (make-array 8 :element-type '(unsigned-byte 8) :initial-element 219)))
                 (setq value (coerce (append (multiple-value-list (files-read-close (files-path name) buffer))
                                            (list buffer)) 'vector))))
              ((equal op "unwind-close")
               (setq value (vector (fd-close (namespace-unwind-close (files-path name))))))
              ((equal op "effects")
               (let* ((cell (cons nil nil)) (fd (namespace-open-effects (files-path name) cell)))
                 (setq value (vector (>= fd 0) (car cell) (cdr cell))) (fd-close fd)))
              ((equal op "write") nil)
              (t (error "Unknown file case: ~s" row)))
            (unless (or (equal op "write") (and (equal op "open") (eql (third args) 1)))
              (push (vector op (coerce args 'vector) value) rows)))))
    ;; Stale descriptors are deliberately re-closed in the trace. End-of-run
    ;; cleanup is harmless even when a native descriptor has been recycled.
    (maphash (lambda (name fd) (declare (ignore name)) (when (>= fd 0) (fd-close fd))) handles))
  (with-open-file (s (getenv "FILES_NATIVE") :direction :output :if-exists :supersede :external-format :utf-8)
    (namespace-json (coerce (nreverse rows) 'vector) s) (terpri s)))
(ccl:quit)
