#!/usr/bin/env python3
"""Retain and replay generated namespace primitives without retaining caches."""
from pathlib import Path
import argparse
import json
import shutil
from run import HERE,c,storage,run,execution_inputs
RECORDS=('execution.json','native.json','controls.json','faults.json','audit176.json')

def generated(out):
    return {str(p.relative_to(out)):c.sha(p) for p in sorted(out.rglob('*'))
            if p.is_file() and ((p.parent==out/'compiled' and p.suffix in ('.wat','.wasm','.bin'))
              or (p.parent==out/'compiled' and p.name in ('modules.json','symbols.json','pools.json','pool-roots.json'))
              or (p.parent==out and p.suffix=='.wasm'))}

def retain(out,packet):
    summary=c.read(out/'summary.json')
    assert summary['status']=='PASS' and summary['fresh_compilation']
    assert summary['execution_inputs']==execution_inputs()
    packet.mkdir()
    for name in (*RECORDS,'summary.json','cases.json'):
        shutil.copyfile(out/name,packet/name)
    shutil.copyfile(out/'compiled/compile-completion.json',packet/'compile-completion.json')
    shutil.copytree(HERE,packet/'source',ignore=shutil.ignore_patterns('__pycache__'))
    shutil.copytree(out/'faults',packet/'faults')
    for p in out.glob('*.log'):shutil.copyfile(p,packet/p.name)
    shutil.copyfile(out/'compiled/compile.log',packet/'compile.log')
    if (out/'development').exists():shutil.copytree(out/'development',packet/'development')
    qualification=c.read(c.ROOT/'doc/WASM/stage1/integration-stream-constructors.json')['qualification']
    c.verify_files(c.ROOT,qualification['source_identity'])
    c.save(packet/'native-reuse.json',dict(mode='UNCHANGED_PRODUCT_SOURCE',new_execution=False,
        integration_record='doc/WASM/stage1/integration-stream-constructors.json',
        integration_sha256=c.sha(c.ROOT/'doc/WASM/stage1/integration-stream-constructors.json'),
        qualification=qualification))
    c.save(packet/'generated.json',generated(out))
    c.save(packet/'pins.json',execution_inputs())
    c.save(packet/'packet.json',dict(id='STAGE1-NAMESPACE-PRIMITIVES-R2',files=c.inventory(packet),slot_credit=False))
    c.verify_files(packet,c.read(packet/'packet.json')['files'])
    shutil.rmtree(storage.workspace(out))
    return dict(status='PASS',new_execution=False,output_deleted=True)

def verify(packet,out):
    c.verify_files(packet,c.read(packet/'packet.json')['files'])
    assert c.read(packet/'pins.json')==execution_inputs(),'Use the recorded source commit'
    with storage.lease([out]):
        run(out)
        for name in RECORDS:assert c.read(packet/name)==c.read(out/name),name
        assert generated(out)==c.read(packet/'generated.json'),'generated bytes'
        expected=c.read(packet/'summary.json');actual=c.read(out/'summary.json')
        assert {k:v for k,v in expected.items() if k!='times'}=={k:v for k,v in actual.items() if k!='times'}
    return dict(status='PASS',new_execution=True,comparisons=actual['comparisons'],controls=actual['controls'],faults=actual['faults'],times=actual['times'])

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('command',choices=['retain','verify']);p.add_argument('packet',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
    storage.gc()
    if a.command=='retain':
        with storage.lease([a.output]):result=retain(a.output.resolve(),a.packet.resolve())
    else:result=verify(a.packet.resolve(),a.output.resolve())
    print(json.dumps(result,sort_keys=True))
