(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(load (merge-pathnames "selection.lisp" *load-pathname*))
(defun reset-json-value (s value)
  (cond ((null value) (format s "\"nil\"")) ((eq value t) (format s "\"t\""))
        ((integerp value) (format s "~d" value)) (t (error "Unexpected reset value ~s" value))))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (callbacks nil))
  (with-open-file (source-log (concatenate 'string out "source-forms.lisp") :direction :output :if-exists :error)
    (dolist (row *reset-selection*)
      (destructuring-bind (name source position expected module) row
        (let* ((symbol (find-symbol name "CCL"))
               (*package* (find-package "CCL"))
               (form (with-open-file (s source) (file-position s position) (read s)))
               (value (cond ((eq (first form) 'ccl::defloadvar)
                             (assert (eq (second form) symbol)) (third form))
                            ((eq (first form) 'ccl::def-ccl-pointers)
                             (assert (and (eq (second form) symbol) (null (third form)) (= (length form) 4)))
                             (assert (equal (fourth form) `(setq ,symbol nil))) nil)
                            (t (error "Not a reset source ~s" form))))
               (matches (remove-if-not (lambda (f) (eq (ccl::function-name f) symbol)) ccl::*lisp-system-pointer-functions*)))
          (assert (member value '(nil t 0))) (assert (eql value expected))
          (assert (= (length matches) 1))
          (push (list symbol (first matches) value) callbacks)
          (print (list name source position form) source-log)
          ;; Explicit replacement for the native static SETQ: owner admission
          ;; requires binding index zero, so SET selects the global value cell.
          ;; Completion is generated only after the real store has returned.
          (let* ((*package* (find-package "WASM32-COMPILER"))
                 (function `(lambda (symbol done) (multiple-value-prog1 (set symbol ,value) (rplaca done ,(+ 101 (length modules))))))
                 (result (compile-call-form function module nil)))
            (assert (null (getf result :children)))
            (push result modules)
            (with-open-file (s (concatenate 'string out module ".wat") :direction :output :if-exists :error) (write-string (getf result :wat) s)))))))
  (setq modules (nreverse modules) callbacks (nreverse callbacks))
  (let* ((vars (loop for i below (length callbacks) collect (intern (format nil "S~d" i))))
         (work `(lambda (,@vars done) (multiple-value-prog1 (values ,@(mapcar (lambda (v) `(symbol-value ,v)) vars)) (rplaca done 200))))
         (pre '(lambda (symbol done) (multiple-value-prog1 (symbol-value symbol) (rplaca done 100)))))
    (dolist (row (list (list "preflight" pre) (list "workload" work)))
      (let ((result (compile-call-form (second row) (first row) nil)))
        (assert (null (getf result :children)))
        (setq modules (append modules (list result)))
        (with-open-file (s (concatenate 'string out (first row) ".wat") :direction :output :if-exists :error) (write-string (getf result :wat) s)))))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error)
    (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (let ((saved (mapcar (lambda (r) (symbol-value (first r))) callbacks)))
    (unwind-protect
      (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
        (format s "[")
        (loop for sentinel in '(37 91) for round from 0 do
          (unless (zerop round) (format s ",")) (format s "[")
          (dolist (r callbacks) (set (first r) sentinel))
          (loop for r in callbacks for i from 0 do
            (unless (zerop i) (format s ","))
            (let ((values (multiple-value-list (funcall (second r)))))
              (assert (equal values (list (third r))))
              (format s "{\"values\":[") (reset-json-value s (first values))
              (format s "],\"globals\":[")
              (loop for r2 in callbacks for j from 0 do (unless (zerop j) (format s ",")) (reset-json-value s (symbol-value (first r2))))
              (format s "]}")))
          (format s "]"))
        (format s "]"))
      (loop for r in callbacks for old in saved do (set (first r) old)))
    (assert (equal saved (mapcar (lambda (r) (symbol-value (first r))) callbacks)))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
