;;; Read existing tables only: never resolve an entry point or open a library.
(in-package :ccl-startup-census)
(defun foreign-field (row name)
  (loop for (key value) on (cdr row) by #'cddr when (string= key name) return value))
(defun inspect-foreign-surface (path)
  (when ccl::*startup-census-hook* (error "Requires an unobserved clean image"))
  (let ((kernel nil) (entrypoints nil) (variables nil) (libraries nil))
    (do-symbols (symbol (find-package (arch::target-package-name
                                      (ccl::backend-target-arch ccl::*host-backend*))))
      (when (and (<= 14 (length (symbol-name symbol)))
                 (string= "KERNEL-IMPORT-" (symbol-name symbol) :end2 14)
                 (boundp symbol))
        (push (object "name" (symbol-name symbol) "offset" (symbol-value symbol)) kernel)))
    (labels ((container (value)
               (cond ((null value) :null)
                     ((ccl::istruct-typep value 'ccl::shlib)
                      (object "soname" (label-of (ccl::shlib.soname value))
                              "pathname" (label-of (ccl::shlib.pathname value))))
                     (t (object "opaque_type" (label-of (type-of value)))))))
      (when ccl::*eeps*
        (maphash (lambda (key value)
                   (push (object "key" (label-of key) "name" (ccl::eep.name value)
                                 "resolved" (if (ccl::eep.address value) :true :false)
                                 "container" (container (ccl::eep.container value))) entrypoints)) ccl::*eeps*))
      (when ccl::*fvs*
        (maphash (lambda (key value)
                   (push (object "key" (label-of key) "name" (ccl::fv.name value)
                                 "type" (label-of (ccl::fv.type value))
                                 "resolved" (if (ccl::fv.addr value) :true :false)
                                 "container" (container (ccl::fv.container value))) variables)) ccl::*fvs*))
      (dolist (value ccl::*shared-libraries*) (push (container value) libraries)))
    (with-open-file (stream path :direction :output :if-exists :error :external-format :utf-8)
      (json (object "version" 1 "backend" (label-of (ccl::backend-name ccl::*host-backend*))
                    "kernel_imports" (sort kernel #'< :key (lambda (r) (foreign-field r "offset")))
                    "entrypoints" (sort entrypoints #'string< :key (lambda (r) (foreign-field r "name")))
                    "foreign_variables" (sort variables #'string< :key (lambda (r) (foreign-field r "name")))
                    "libraries" libraries
                    "scope" "Existing native image tables, not a bound on arbitrary future foreign calls or a Wasm implementation.") stream)
      (terpri stream))
    (format t "FOREIGN-INVENTORY-COMPLETE~%")))
