;;; Structured, identity-bearing observation. Never changes a compiler object.
;;; Load the existing observer and dependency helpers before this file.
(defpackage :ccl-rich-census (:use :cl)
  (:import-from :ccl-startup-census #:object #:json #:label-of #:dependency-id))
(in-package :ccl-rich-census)

(defvar *stream* nil)
(defvar *sequence* 0)
(defvar *busy* nil)
(defvar *lock* (ccl:make-lock "rich census event ordering"))
(defvar *frames* (make-hash-table :test #'eq :weak :key))
(defvar *counts* (make-hash-table :test #'equal))
(defvar *setter-origins* (make-hash-table :test #'eq :weak :key))
(defvar *handler-operators* (make-hash-table :test #'eq :weak :key))
(defvar *refresh-handlers* t)
(defvar *cold-armed* nil)

(defun write-json-string (value stream)
  ;; Preserve the reviewed encoding byte for byte, but write ordinary text in
  ;; spans. Calling WRITE-CHAR for every source character dominated collection.
  (declare (type string value))
  (write-char #\" stream)
  (let ((start 0) (end (length value)))
    (dotimes (i end)
      (let ((c (char value i)))
        (when (or (char= c #\") (char= c #\\) (< (char-code c) 32))
          (when (< start i) (write-string value stream :start start :end i))
          (case c
            (#\" (write-string "\\\"" stream))
            (#\\ (write-string "\\\\" stream))
            (t (format stream "\\u~4,'0x" (char-code c))))
          (setq start (1+ i)))))
    (when (< start end) (write-string value stream :start start :end end)))
  (write-char #\" stream))

(defun write-json (value stream)
  (cond ((eq value :null) (write-string "null" stream))
        ((eq value :true) (write-string "true" stream))
        ((eq value :false) (write-string "false" stream))
        ((stringp value) (write-json-string value stream))
        ((integerp value) (princ value stream))
        ((and (consp value) (eq (car value) :object))
         (write-char #\{ stream)
         (loop for (key val) on (cdr value) by #'cddr for first = t then nil do
           (unless first (write-char #\, stream))
           (write-json-string key stream) (write-char #\: stream) (write-json val stream))
         (write-char #\} stream))
        ((listp value)
         (write-char #\[ stream)
         (loop for item in value for first = t then nil do
           (unless first (write-char #\, stream)) (write-json item stream))
         (write-char #\] stream))
        (t (error "Not a census JSON value: ~s" value))))

(defun emission-context ()
  ;; Read the actual stack and evaluated dispatch table. No native target source
  ;; or handler is patched, wrapped or replaced. Tail-elided frames cannot be
  ;; reconstructed and are explicitly reported as unavailable.
  (when *refresh-handlers*
    (clrhash *handler-operators*)
    (loop for fn across (ccl::backend-p2-dispatch ccl::*target-backend*) for id from 0
          when (functionp fn) do (push id (gethash (ccl::closure-function fn) *handler-operators*)))
    (setf *refresh-handlers* nil))
  (let ((frames nil))
    (ccl:map-call-frames
     (lambda (frame context)
       (let* ((fn (ccl::frame-function frame context))
              (ids (and fn (gethash (ccl::closure-function fn) *handler-operators*))))
         (when ids
           (push (object "function" (dependency-id fn) "code" (code-id fn)
                         "operators" ids) frames)))))
    (object "handler_frames" (nreverse frames)
            "scope" "Live dispatch frames only; tail-elided frames are unavailable")))

(defun code-id (function)
  (dependency-id (ccl::closure-function function)))

(defun inventory (stage)
  (let ((*busy* t) (functions nil) (seen (make-hash-table :test #'eq)))
    (ccl::%map-lfuns (lambda (fn) (push fn functions)))
    (ccl:with-lock-grabbed (*lock*)
      (emit-locked :inventory-enter (object "stage" stage) ccl::*current-process* nil)
      (dolist (fn functions)
        (let ((literals nil))
          (ccl::%map-lfimms fn (lambda (value) (when (functionp value) (push (code-id value) literals))))
          (emit-locked :resident-function
                       (object "stage" stage "function" (describe-value fn)
                               "literal_functions" (remove-duplicates literals)) ccl::*current-process* nil)))
      (labels ((binding (sym)
                 (unless (gethash sym seen)
                   (setf (gethash sym seen) t)
                   (when (fboundp sym)
                     (emit-locked :resident-binding (object "stage" stage "binding"
                                                            (describe-value (list sym (fboundp sym))))
                                  ccl::*current-process* nil)))))
        (do-all-symbols (sym) (binding sym))
        (maphash (lambda (original cell) (declare (ignore original)) (binding cell)) ccl::%setf-function-names%))
      (emit-locked :inventory-return (object "stage" stage) ccl::*current-process* nil))))

(defun source-description (function)
  (let ((note (ccl:function-source-note function)))
    (object "name" (label-of (ccl:function-name function))
            "source" (if note (label-of (ccl::source-note-filename note)) :null)
            "position" (if note (ccl::source-note-start-pos note) :null))))

(defun describe-value (value &optional (deep t))
  ;; Object graphs are flat records with references, not recursively printed
  ;; forms. Mutable objects may have a new snapshot under the same ID in a later
  ;; event. Symbols retain identity even if two uninterned SETF names print alike.
  (let ((todo nil) (seen (make-hash-table :test #'eq)) (rows nil))
    (labels ((ref (x &optional (expand deep))
               (cond ((null x) (object "atom" "nil"))
                     ((integerp x) (object "integer" x))
                     ((characterp x) (object "character" (char-code x)))
                     ((stringp x) (object "string" x))
                     (t (unless (gethash x seen)
                          (setf (gethash x seen) t)
                          (push (cons x expand) todo))
                        (object "ref" (dependency-id x)))))
             (children (xs) (mapcar #'ref xs)))
      (let ((root (ref value)))
        (loop while todo for work = (pop todo) for x = (car work) for expand = (cdr work)
              for id = (dependency-id x) do
          (push
           (cond
             ((symbolp x)
              (object "id" id "kind" "symbol" "name" (symbol-name x)
                      "package" (if (symbol-package x) (package-name (symbol-package x)) :null)
                      "setter_of" (let ((original (gethash x ccl::%setf-function-name-inverses%)))
                                    (if original (label-of original) :null))))
             ((functionp x)
              (object "id" id "kind" "function" "code" (code-id x)
                      "description" (source-description x)))
             ((ccl::acode-p x)
              (object "id" id "kind" "acode" "operator" (ccl::acode-operator x)
                      "operator_id" (logand (ccl::acode-operator x) ccl::operator-id-mask)
                      "operands" (if expand (ref (ccl::acode-operands x)) :null)
                      "expanded" (if expand :true :false)))
             ((typep x 'ccl::afunc)
              (object "id" id "kind" "afunc" "name" (ref (ccl::afunc-name x))
                      "parent" (if (ccl::afunc-parent x) (dependency-id (ccl::afunc-parent x)) :null)
                      "body" (if expand (ref (ccl::afunc-acode x)) :null)
                      "children" (children (ccl::afunc-inner-functions x))
                      "function" (if (ccl::afunc-lfun x) (ref (ccl::afunc-lfun x)) :null)))
             ((typep x 'ccl::var)
              (object "id" id "kind" "variable" "name" (ref (ccl::var-name x))
                      "root" (dependency-id (ccl::nx-root-var x))))
             ((consp x)
              (object "id" id "kind" "cons" "car" (if expand (ref (car x)) :null)
                      "cdr" (if expand (ref (cdr x)) :null) "expanded" (if expand :true :false)))
             ((typep x 'simple-vector)
              (object "id" id "kind" "simple-vector" "length" (length x)
                      "elements" (if expand (loop for item across x collect (ref item)) nil)
                      "expanded" (if expand :true :false)))
             ((pathnamep x) (object "id" id "kind" "pathname" "namestring" (namestring x)))
             (t
              ;; Lexical environments, classes, register descriptors, unboxed
              ;; vectors, etc. are explicitly opaque, not silently omitted or
              ;; printed back as executable source. Their identities survive.
              (object "id" id "kind" "opaque" "type" (label-of (type-of x)))))
           rows))
        (object "root" root "objects" (nreverse rows))))))

(defun current-function-id ()
  (cond ((and (boundp 'ccl::*x862-cur-afunc*) (typep ccl::*x862-cur-afunc* 'ccl::afunc))
         (dependency-id ccl::*x862-cur-afunc*))
        ((and (boundp 'ccl::*nx-current-function*)
           (typep ccl::*nx-current-function* 'ccl::afunc))
         (dependency-id ccl::*nx-current-function*)) (t :null)))

(defun operator-id (value)
  (let ((op (cond ((ccl::acode-p value) (ccl::acode-operator value))
                  ((and (consp value) (integerp (car value))) (car value))
                  ((null value) (gethash 'nil ccl::*nx1-operators*))
                  ((eq value t) (gethash 't ccl::*nx1-operators*)))))
    (if op (logand op ccl::operator-id-mask) :null)))

(defun phase-family (phase)
  (case phase
    ((:compile-initializer-enter :compile-initializer-return :compile-initializer-abort) :compile)
    ((:expander-enter :expander-return :expander-abort) :expander)
    ((:fasl-effect-enter :fasl-effect-return :fasl-effect-abort) :fasl)
    ((:fasl-function-enter :fasl-function-return :fasl-function-abort) :fasl-function)
    ((:load-effect-call :load-effect-value :load-effect-abort) :load-call)
    ((:lower-enter :lower-leave) :lower)
    ((:startup-enter :startup-return) :startup)))

(defun entry-p (phase)
  (member phase '(:compile-initializer-enter :expander-enter :fasl-effect-enter :fasl-function-enter
                 :load-effect-call :lower-enter :startup-enter)))

(defun emit-locked (phase payload process parent &optional context)
  (let ((kind (string-downcase (symbol-name phase))))
    (incf (gethash kind *counts* 0))
    (write-json (object "version" 2 "sequence" (incf *sequence*) "kind" kind
                  "process" (dependency-id process) "parent" (or parent :null)
                  "source" (if *compile-file-truename* (namestring *compile-file-truename*) :null)
                  "source_position" (if (and (boundp 'ccl::*fcomp-stream-position*)
                                               (integerp ccl::*fcomp-stream-position*))
                                        ccl::*fcomp-stream-position* :null)
                  "loading_source" (if (boundp 'ccl::*loading-file-source-file*)
                                       (label-of ccl::*loading-file-source-file*) :null)
                  "function" (current-function-id) "context" (or context :null)
                  "payload" payload) *stream*)
    (terpri *stream*)))

(defun observe (phase value)
  (when *cold-armed*
    (unless (eq phase :startup-enter) (return-from observe))
    (setf *cold-armed* nil
          *stream* (open (or (ccl:getenv "CCL_RICH_EVENTS") (error "Missing cold event path"))
                         :direction :output :if-exists :error :external-format :utf-8
                         :sharing :external))
    (let ((*busy* t))
      (ccl:with-lock-grabbed (*lock*)
        (emit-locked :snapshot (ccl-startup-census::snapshot) ccl::*current-process* nil))))
  (unless *busy*
    (let ((*busy* t) (*gensym-counter* *gensym-counter*)
          (process ccl::*current-process*))
      (ccl:with-lock-grabbed (*lock*)
        (let* ((stack (gethash process *frames*)) (family (phase-family phase))
               (entry (entry-p phase)) (parent (cadar stack))
               (context (when (eq phase :vinsn-emitted) (emission-context)))
               (payload
                (cond
                  ((eq phase :vinsn-emitted)
                   (let ((template (ccl::vinsn-template value)))
                     (object "template" (label-of (ccl::vinsn-template-name template))
                             "template_id" (dependency-id template)
                             "attributes" (ccl::vinsn-template-attributes template)
                             "parts" (describe-value (ccl::vinsn-variable-parts value)))))
                  ((eq phase :lower-enter)
                   (object "operator_id" (operator-id value) "value" (describe-value value nil)))
                  ((eq phase :lower-leave) (object "operator_id" (operator-id value)))
                  ((member phase '(:frontend :before-pass2))
                   (object "function" (ccl-startup-census::function-observation value)
                           "ir" (describe-value value)))
                  ((eq phase :function-materialized) (describe-value value nil))
                  ((member phase '(:startup-enter :startup-return))
                   (object "designator" (describe-value value)
                           "function" (describe-value (if (symbolp value) (symbol-function value) value))))
                  (t (describe-value value)))))
          (when (and family (not entry))
            (unless (and stack (eq family (caar stack)))
              (error "Census event nesting mismatch: ~s ~s" phase stack))
            (setf parent (cadar stack)))
          (emit-locked phase payload process parent context)
          (when (member phase '(:compile-initializer-return :fasl-effect-return))
            (setf *refresh-handlers* t))
          (cond (entry (push (list family *sequence* (if (eq family :lower) (operator-id value) :null))
                             (gethash process *frames*)))
                (family (pop (gethash process *frames*)))))))))

(defun start (path)
  (when *stream* (error "Rich census already active"))
  (setf *stream* (open path :direction :output :if-exists :error :external-format :utf-8)
        *sequence* 0)
  (clrhash *frames*) (clrhash *counts*) (clrhash *setter-origins*)
  (setf *refresh-handlers* t)
  (maphash (lambda (original cell) (setf (gethash cell *setter-origins*) original)) ccl::%setf-function-names%)
  (let ((*busy* t))
    (ccl:with-lock-grabbed (*lock*)
      (emit-locked :snapshot (ccl-startup-census::snapshot) ccl::*current-process* nil)))
  (inventory "before")
  (setf ccl::*startup-census-hook* #'observe))

(defun finish ()
  (setf ccl::*startup-census-hook* nil)
  (inventory "after")
  (let ((*busy* t))
    (ccl:with-lock-grabbed (*lock*)
      (maphash (lambda (process frames)
                 (when frames (error "Unfinished census frames in ~s: ~s" process frames))) *frames*)
      (emit-locked :complete (object "events_before_complete" *sequence*
                                    "counts" (loop for name being the hash-keys of *counts*
                                                   using (hash-value count) collect (object "kind" name "count" count)))
                   ccl::*current-process* nil)
      (finish-output *stream*) (close *stream*) (setf *stream* nil)))
  (format t "RICH-CENSUS-COMPLETE~%"))

(defun prepare-image (path)
  (when *stream* (error "Cannot save with an active observation stream"))
  (clrhash *frames*) (clrhash *counts*)
  (setf *sequence* 0 *cold-armed* t *refresh-handlers* t
        ccl::*startup-census-hook* #'observe)
  (ccl:save-application path :prepend-kernel nil))
