(in-package :cl-user)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (assert (equal *rich-state* '(:l0)))
  (push :l1 *rich-state*)
  (defun rich-version () 1)
  (defvar *rich-old-l1* nil)
  (setq *rich-old-l1* #'rich-version)
  (defmacro rich-macro (x) `(+ ,x 20)))
(defun rich-expanded-l1 (x) (rich-macro x))
(defun (setf rich-slot) (value box) (setf (car box) value))
