(in-package :cl-user)
(defun run-rich-probe (directory &optional (mode "normal"))
  (let ((*gensym-counter* 100000))
    ;; Compile-time state and load-time state each traverse the real dependency
    ;; chain. Reset between the two executions, not between prerequisites.
    (dolist (name '("probe-l0" "probe-l1" "probe-l2"))
      (compile-file (merge-pathnames (concatenate 'string name ".lisp") directory)))
    (dolist (name (cond ((equal mode "omit-l1") '("probe-l0" "probe-l2"))
                        ((equal mode "reorder") '("probe-l0" "probe-l2" "probe-l1"))
                        (t '("probe-l0" "probe-l1" "probe-l2"))))
      (load (merge-pathnames (concatenate 'string name ".dx64fsl") directory))))
  (assert (equal *rich-state* '(:l2 :l1 :l0)))
  (assert (= (funcall *rich-old-l0*) 0))
  (assert (= (funcall *rich-old-l1*) 1))
  (assert (= (rich-version) 2))
  (assert (= (rich-expanded-l0 1) 11))
  (assert (= (rich-expanded-l1 1) 21))
  (assert (= (rich-expanded-l2 1) 31))
  (assert (= (rich-symbol-macro 2) 5))
  (assert (= (rich-compiler-macro) 6))
  (assert (= (rich-indirect #'1+ 6) 7))
  (assert (equal (multiple-value-list (rich-values 7)) '(7 8 -7)))
  (assert (= *rich-load-value* 47))
  (let ((box (list 0))) (setf (rich-slot box) 91) (assert (= (car box) 91)))
  (format t "RICH-PROBE-PASS~%"))
