(in-package :cl-user)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (assert (equal *rich-state* '(:l1 :l0)))
  (push :l2 *rich-state*)
  (defun rich-version () 2)
  (defmacro rich-macro (x) `(+ ,x 30)))
(defun rich-expanded-l2 (x) (rich-macro x))
(defun rich-indirect (function value) (funcall function value))
(defparameter *rich-load-value* 47)
