;;; Real state prerequisites and definition replacements, not logger counters.
(in-package :cl-user)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defvar *rich-state* nil)
  (setq *rich-state* (list :l0))
  (defun rich-version () 0)
  (defvar *rich-old-l0* nil)
  (setq *rich-old-l0* #'rich-version)
  (defmacro rich-macro (x) `(+ ,x 10))
  (defun rich-hinted (x) (+ x 2))
  (define-compiler-macro rich-hinted (&whole whole x)
    (if (integerp x) (+ x 2) whole)))
(defun rich-expanded-l0 (x) (rich-macro x))
(defun rich-symbol-macro (x) (symbol-macrolet ((y (+ x 3))) y))
(defun rich-compiler-macro () (rich-hinted 4))
(defun rich-values (x) (values x (1+ x) (- x)))
