;;; Ordinary source, compiled unchanged by the native and target compilers.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0)))
  (proclaim '(notinline da-car da-cdr da-list-car da-list-cdr da-vector
              da-fixed da-bounded da-safe-car da-safe-vector da-slow-policy
              da-inner-safe da-checked-the da-collect da-note)))

(defun da-car (x) (declare (cons x)) (car x))
(defun da-cdr (x) (declare (cons x)) (cdr x))
(defun da-list-car (x) (declare (list x)) (car x))
(defun da-list-cdr (x) (declare (list x)) (cdr x))
(defun da-vector (v i) (declare (simple-vector v) (fixnum i)) (svref v i))
(defun da-fixed (v i) (declare (type (simple-vector 4) v) (fixnum i)) (svref v i))
(defun da-bounded (v i)
  (declare (type (simple-vector 4) v) (type (integer 0 3) i))
  (svref v i))
(defun da-masked (v i)
  (declare (type (simple-vector 4) v) (fixnum i))
  (svref v (the (integer 0 3) (logand i 3))))
(defun da-safe-car (x) (declare (optimize (safety 3)) (cons x)) (car x))
(defun da-safe-vector (v i)
  (declare (optimize (safety 3)) (type (simple-vector 4) v) (type (integer 0 3) i))
  (svref v i))
(defun da-slow-policy (x)
  (declare (optimize (speed 0) (safety 1)) (cons x)) (car x))
(defun da-inner-safe (x)
  (declare (cons x))
  (locally (declare (optimize (safety 3))) (car x)))
(defun da-inner-trust (x)
  (declare (optimize (safety 3)))
  (locally (declare (optimize (speed 3) (safety 1)) (cons x)) (car x)))
(defun da-checked-the (x)
  (declare (optimize (safety 3))) (car (the cons x)))
(defun da-vector-types (x)
  (list (typep x '(simple-vector)) (typep x '(simple-vector *))
        (typep x '(simple-vector 0)) (typep x '(simple-vector 4))))
(defun da-collect (value)
  #+wasm32-target (write-line "EB-GC")
  #-wasm32-target (gc)
  value)
(defvar *da-order* nil)
(defun da-note (name value) (push name *da-order*) value)
(defun da-order (v)
  (declare (type (simple-vector 4) v))
  (svref (the (simple-vector 4) (da-note :vector v))
         (the (integer 0 3) (da-note :index 2))))
(defun da-mutate (v replacement)
  (declare (type (simple-vector 4) v replacement))
  (svref v (progn (setq v replacement) 1)))
(defun da-captured (v replacement)
  (declare (type (simple-vector 4) v replacement))
  (let ((change (lambda () (setq v replacement))))
    (svref v (progn (funcall change) 2))))
(defvar *da-vector* nil)
(defun da-special (v replacement)
  (declare (type (simple-vector 4) v replacement))
  (let ((*da-vector* v))
    (declare (type (simple-vector 4) *da-vector*))
    (svref *da-vector* (progn (setq *da-vector* replacement) 3))))
(defun da-moving-stable (v)
  (declare (type (simple-vector 4) v))
  (svref v (the (integer 0 3) (da-collect 2))))
(defun da-moving-computed (pair)
  (svref (the (simple-vector 4) (vector pair pair pair pair))
         (the (integer 0 3) (da-collect 1))))
(defun da-moving-mutable (v)
  (declare (type (simple-vector 4) v))
  (let ((original v))
    (prog1 (svref v (the (integer 0 3) (da-collect 3)))
      (setq v (vector original original original original)))))
(defun da-moving-car (pair)
  (car (the cons (da-collect pair))))
(defun da-many-values (pair v)
  (declare (cons pair) (type (simple-vector 4) v))
  (values (car pair) (cdr pair) (svref v 3)))
(defun da-row (name value) (format t "DA-ROW ~s ~s~%" name value))

(let ((pair (cons 17 23)) (v (vector 10 20 30 40)))
  (dolist (name '(da-car da-cdr da-list-car da-list-cdr da-safe-car
                 da-slow-policy da-inner-safe da-inner-trust da-checked-the))
    (da-row name (funcall name pair)))
  (da-row 'nil-car (da-list-car nil))
  (da-row 'nil-cdr (da-list-cdr nil))
  (dolist (name '(da-vector da-fixed da-bounded da-masked da-safe-vector))
    (dotimes (i 4) (da-row name (funcall name v i))))
  (dolist (i '(-536870912 -1 4 536870911))
    (da-row 'masked (da-masked v i)))
  (da-row 'values (multiple-value-list (da-many-values pair v)))
  (setq *da-order* nil)
  (da-row 'order (da-order v))
  (assert (equal *da-order* '(:index :vector)))
  (let ((replacement (vector 100 200 300 400)))
    (da-row 'mutation (da-mutate v replacement))
    (da-row 'capture (da-captured v replacement))
    (da-row 'special (da-special v replacement)))
  (let ((refs (vector pair pair pair pair)))
    (dotimes (i 2)
      (dolist (name '(da-moving-stable da-moving-mutable))
        (assert (eq pair (funcall name refs))))
      (assert (eq pair (da-moving-computed pair)))
      (da-row 'moving-car (da-moving-car pair)))))
;;; Invalid declarations are exercised only where policy requires checks.
(dolist (name '(da-safe-car da-slow-policy da-inner-safe da-checked-the))
  (da-row 'type-error
    (handler-case (progn (funcall name 7) nil) (type-error () t))))
(dolist (args '((#(1 2 3 4) -1) (#(1 2 3 4) 4) (#(1 2 3 4) 0.5d0)
                ((1 2 3 4) 0) (#(1 2 3) 0) (#() 0) (#*1010 0) (nil 0)))
  (da-row 'safe-error
    (handler-case (progn (apply #'da-safe-vector args) nil) (error () t))))
(dolist (name '(da-vector da-fixed))
  (dolist (i '(-536870912 -1 4 536870911))
    (da-row 'bounds
      (handler-case (progn (funcall name #(1 2 3 4) i) nil) (error () t)))))
(da-row 'empty-bounds
  (handler-case (progn (da-vector #() 0) nil) (error () t)))
(dolist (x (list #(1 2 3 4) #() #(1) nil '(1 2 3 4) #*1010
                (make-array 4 :adjustable t :initial-element 1)))
  (da-row 'vector-types (da-vector-types x)))
(da-row 'recovery (da-bounded #(1 2 3 4) 3))
(format t "DA-PASS~%")
