import fs from 'node:fs';import assert from 'node:assert/strict';
import {PACKAGING,signatures,validate,compile,publish} from './bundle.mjs';
import {entryRanges} from './ranges.mjs';import {inspect} from './binary.mjs';
const dir=process.argv[2],read=n=>JSON.parse(fs.readFileSync(dir+'/'+n)),bytes=n=>fs.readFileSync(dir+'/full/'+n+'.wasm'),template=n=>fs.readFileSync(dir+'/templates/'+n+'.wasm'),save=(n,x)=>fs.writeFileSync(dir+'/'+n,JSON.stringify(x,null,2)+'\n');
const d2=read('materialization.json'),mods=read('modules.json'),versions=read('versions.json');
const bundle={version:1,packaging:PACKAGING,...versions,modules:mods.map((m,i)=>{const x=inspect(bytes(m.name)),ranges=entryRanges(bytes(m.name));return {name:m.name,code_id:i+1,slot:i+1,generation:m.generation??1,...versions,d2:d2.modules[m.name],entries:['entry','tail_entry'].map(role=>({role,export:role,table:role==='entry'?'public':'tail',function_index:x.exports.find(e=>e.name===role).index,signature:signatures[role],range:ranges.find(e=>e.role===role)}))};})};
const expected={...versions,modules:mods.map((m,i)=>[m.name,i+1,m.generation??1]),table_capacity:mods.length+1,reserved_slots:[0]};
assert(validate(bundle,expected,bytes));save('bundle.json',bundle);save('expected.json',expected);
const controls=[];function bad(name,edit,reason){const b=structuredClone(bundle);edit(b);assert.throws(()=>validate(b,expected,bytes),e=>e.message===reason,name);controls.push({name,reason});}
bad('omitted-module',b=>b.modules.pop(),'INVENTORY');bad('reordered-code-map',b=>b.modules.reverse(),'INVENTORY');bad('logical-code-id',b=>b.modules[0].code_id=99,'INVENTORY');bad('generation',b=>b.modules[0].generation=0,'INVENTORY');bad('reserved-slot',b=>b.modules[0].slot=0,'SLOT');bad('duplicate-slot',b=>b.modules[1].slot=b.modules[0].slot,'SLOT');bad('slot-capacity',b=>b.modules[0].slot=expected.table_capacity,'SLOT');bad('abi',b=>b.abi.version++,'VERSIONS');bad('layout',b=>b.modules[0].layout={version:9},'MODULE_VERSIONS');bad('role',b=>b.modules[0].entries[0].table='tail','ROLE');bad('function-index',b=>b.modules[0].entries[0].function_index++,'ROLE');bad('signature',b=>b.modules[0].entries[0].signature.params.pop(),'SIGNATURE');bad('body-range',b=>b.modules[0].entries[0].range.end--,'RANGE');bad('binary-digest',b=>b.modules[0].d2.outputs.full.binary_sha256='0'.repeat(64),'BINARY');bad('entry-omission',b=>b.modules[0].entries.pop(),'ENTRY_COUNT');bad('packaging-version',b=>b.packaging='merge-silently','PACKAGING');
const memory=new WebAssembly.Memory({initial:16,maximum:32769,shared:true}),table=new WebAssembly.Table({element:'anyfunc',initial:expected.table_capacity}),tail=new WebAssembly.Table({element:'anyfunc',initial:expected.table_capacity});
function imports(name){const x=inspect(bytes(name)),result={};for(const i of x.imports){const ns=result[i.module]??={};ns[i.name]=i.kind==='memory'?memory:i.kind==='table'?(i.name==='tail_table'?tail:table):i.kind==='tag'?new WebAssembly.Tag({parameters:i.signature.params}):0;}return result;}
const compiled=compile(bundle,expected,bytes,template,d2.policy),before=new Uint8Array(memory.buffer).slice();
assert.throws(()=>publish(compiled,n=>({...imports(n),env:{}}),table,tail),WebAssembly.LinkError);assert.deepEqual(new Uint8Array(memory.buffer),before);for(let i=0;i<expected.table_capacity;i++)assert.equal(table.get(i),null);controls.push({name:'failed-instantiation-no-publication',reason:'LinkError'});
const setter=tail.set.bind(tail);let injected=false;tail.set=(slot,value)=>{if(slot===2&&value!==null&&!injected){injected=true;throw Error('PUBLICATION_FAULT');}return setter(slot,value);};
assert.throws(()=>publish(compiled,imports,table,tail),e=>e.message==='PUBLICATION_FAULT');tail.set=setter;
for(let i=0;i<expected.table_capacity;i++){assert.equal(table.get(i),null,'rollback-public');assert.equal(tail.get(i),null,'rollback-tail');}controls.push({name:'mid-publication-rollback',reason:'PUBLICATION_FAULT'});
const ready=publish(compiled,imports,table,tail);assert.deepEqual(new Uint8Array(memory.buffer),before);assert.equal(table.get(0),null);assert.equal(tail.get(0),null);assert.throws(()=>publish(compiled,imports,table,tail),e=>e.message==='OCCUPIED');controls.push({name:'occupied-slots',reason:'OCCUPIED'});
for(const {record:m,instance}of ready){assert.equal(table.get(m.slot),instance.exports.entry);assert.equal(tail.get(m.slot),instance.exports.tail_entry);}
// ID and slot are independent: use a reversed, still bijective slot assignment.
const permuted=structuredClone(bundle);permuted.modules.forEach((m,i)=>m.slot=mods.length-i);assert(validate(permuted,expected,bytes));
save('checks.json',{status:'PASS',modules:mods.length,entries:2*mods.length,controls,permuted_slots:mods.length,publication_preserves_memory:true});
