(in-package "CL-USER")
(defvar *root-contract-stream*)
(defvar *root-contract-first* t)
(defun record-root-ir (root name)
  (let ((functions nil) (counter 0) (ids (make-hash-table :test #'eq)))
    (labels ((collect (f)
               (push (cons f (if (eq f root) name (format nil "~a_inner_~d" name (incf counter)))) functions)
               (dolist (child (reverse (ccl::afunc-inner-functions f))) (collect child)))
             (id (var)
               (let ((v (ccl::nx-root-var var)))
                 (or (gethash v ids) (setf (gethash v ids) (hash-table-count ids)))))
             (numbers (values) (format *root-contract-stream* "[~{~d~^,~}]" (mapcar #'id (remove nil values))))
             (walk (form visitor)
               (cond ((ccl::acode-p form)
                      (funcall visitor (ccl::acode-operator-name (ccl::acode-operator form)) (ccl::acode-operands form))
                      (mapc (lambda (x) (walk x visitor)) (ccl::acode-operands form)))
                     ((consp form) (mapc (lambda (x) (walk x visitor)) form)))))
      (collect root) (setq functions (nreverse functions))
      (dolist (entry functions)
        (let* ((f (car entry)) (args (ccl::acode-operands (ccl::afunc-acode f)))
               (required (first args))
               (base (remove nil (append (first (second args)) (third (second args)) (list (third args)) (second (fourth args)) (third (fourth args)))))
               (assigned nil) (bindings nil) (calls nil))
          (walk (ccl::afunc-acode f)
            (lambda (op a)
              (case op
                ((cl:let cl:let* cl:flet cl:labels cl:multiple-value-bind)
                 (setq base (append base (first a)))
                 (when (member op '(cl:flet cl:labels))
                   (loop for v in (first a) for target in (second a) do (push (cons target v) bindings))))
                (ccl::lambda-bind (setq base (append base (second a) (remove nil (list (third a))) (first (fifth a)))))
                (ccl::setq-lexical (push (first a) assigned))
                (ccl::lexical-function-call (push (first a) calls)))))
          (unless *root-contract-first* (write-char #\, *root-contract-stream*)) (setq *root-contract-first* nil)
          (format *root-contract-stream* "{\"name\":~s,\"unit\":~s,\"parent\":~a,\"required\":"
            (cdr entry) name (let ((parent (cdr (assoc (ccl::afunc-parent f) functions :test #'eq)))) (if parent (format nil "~s" parent) "null")))
          (numbers required) (write-string ",\"base\":" *root-contract-stream*) (numbers base)
          (write-string ",\"assigned\":" *root-contract-stream*) (numbers assigned)
          (write-string ",\"inherited\":" *root-contract-stream*) (numbers (ccl::afunc-inherited-vars f))
          (write-string ",\"calls\":[" *root-contract-stream*)
          (loop for target in (reverse calls) for i from 0 do
            (unless (zerop i) (write-char #\, *root-contract-stream*))
            (format *root-contract-stream* "~s" (or (cdr (assoc target functions :test #'eq)) (error "Unknown local target"))))
          (write-string "],\"function_bindings\":[" *root-contract-stream*)
          (loop for (target . var) in (reverse bindings) for i from 0 do
            (unless (zerop i) (write-char #\, *root-contract-stream*))
            (format *root-contract-stream* "{\"function\":~s,\"variable\":~d}" (cdr (assoc target functions :test #'eq)) (id var)))
          (write-string "]}" *root-contract-stream*))))))
(defun compile-with-root-witness (source name links)
  (let ((original (symbol-function 'wasm32-compiler::b-call-pass2)))
    (unwind-protect
      (progn
        (setf (symbol-function 'wasm32-compiler::b-call-pass2)
          (lambda (root) (record-root-ir root name) (funcall original root)))
        (wasm32-compiler::compile-call-module source name links))
      (setf (symbol-function 'wasm32-compiler::b-call-pass2) original))))
