(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("reset_db" (lambda (op head ht dt done) (multiple-value-prog1 (funcall op head ht dt) (rplaca done 401))))
                ("reset_db_cleanup" (lambda (op head ht dt done) (unwind-protect (funcall op head ht dt) (rplaca done 402))))
                ("reset_db_receiver" (lambda (&optional x y) (values x y)))
                ("reset_db_dynamic" (lambda (op recv head ht dt done) (multiple-value-prog1 (multiple-value-call recv (funcall op head ht dt)) (rplaca done 403)))))))
 (let* ((*package* (find-package "CCL"))
        (form (with-open-file (s "lib/db-io.lisp") (file-position s 28364)(read s)))
        (matches (remove-if-not (lambda(f)(eq(ccl::function-name f)'ccl::reset-db-files)) ccl::*lisp-system-pointer-functions*))
        (setters '(ccl::interface-dir-constants-interface-db-file ccl::interface-dir-functions-interface-db-file ccl::interface-dir-records-interface-db-file ccl::interface-dir-types-interface-db-file ccl::interface-dir-vars-interface-db-file ccl::interface-dir-objc-classes-interface-db-file ccl::interface-dir-objc-methods-interface-db-file)))
  (assert (= (length matches) 1))
  (assert (equal form `(ccl::def-ccl-pointers ccl::reset-db-files () (ccl::do-interface-dirs (ccl::d) (setf ,@(loop for f in setters append (list (list f 'ccl::d) nil)))))))
  (with-open-file(s (concatenate 'string out "native-source.lisp") :direction :output :if-exists :error)(print form s))
  (with-open-file(s (concatenate 'string out "native.json") :direction :output :if-exists :error)
   (write-char #\[ s)
   (loop for count in '(0 1 2 7 31 128) for ci from 0 do
    (unless(zerop ci)(write-char #\, s))
    (let* ((ccl::*target-ftd* (ccl::make-ftd)) (head(ccl::ftd-dirlist ccl::*target-ftd*))
           (nodes(loop for i below count collect(ccl::make-interface-dir :name (+ 100 i) :subdir (+ 500 i)))))
     (assert (= (ccl::uvsize head) 4))
     (loop for node in nodes for i from 0 do
      (assert (= (ccl::uvsize node) 12))
      (assert (= (ccl::uvref node 3) (+ 100 i)))(assert (= (ccl::uvref node 4) (+ 500 i)))
      (loop for getter in setters for slot from 5 do
       (funcall(fdefinition `(setf ,getter)) (+ (* i 16) slot) node)
       (assert(= (ccl::uvref node slot) (+ (* i 16) slot))))
      (ccl::append-dll-node node head))
     (let ((before(loop for n in nodes collect(list(ccl::dll-node-pred n)(ccl::dll-node-succ n)(ccl::interface-dir-name n)(ccl::interface-dir-subdir n)))))
      (assert(equal(multiple-value-list(funcall(first matches))) '(nil)))
      (loop for node in nodes for fields in before do
       (assert(equal fields(list(ccl::dll-node-pred node)(ccl::dll-node-succ node)(ccl::interface-dir-name node)(ccl::interface-dir-subdir node))))
       (loop for getter in setters do(assert(null(funcall getter node)))))
      (assert(eq head(ccl::ftd-dirlist ccl::*target-ftd*))))
     (format s "{\"count\":~d,\"header_words\":4,\"node_words\":12,\"cleared_slots\":[5,6,7,8,9,10,11],\"values\":[77825],\"links_preserved\":true,\"metadata_preserved\":true}" count)))
   (write-char #\] s)))
 (dolist(row cases)
  (let((m(compile-call-form(second row)(first row)(mapcar #'first cases))))
   (assert(null(getf m :children)))(push m modules)
   (with-open-file(s(concatenate 'string out(first row)".wat") :direction :output :if-exists :error)(write-string(getf m :wat)s))))
 (setq modules(nreverse modules))
 (with-open-file(s(concatenate 'string out"modules.json") :direction :output :if-exists :error)
  (write-char #\[ s)(loop for m in modules for i from 0 do(unless(zerop i)(write-char #\, s))(format s "{\"name\":~s}"(getf m :name)))(write-char #\] s))
 (with-open-file(s(concatenate 'string out"pools.json") :direction :output :if-exists :error)(write-pool-graph s(mapcar(lambda(m)(getf m :pool))modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
