(in-package :census-finite-probes)

(defun constructor-source ()
  (with-open-file (in (translate-logical-pathname "ccl:l1;l1-clos-boot.lisp"))
    (let ((*package* (find-package :ccl)))
      (loop for start = (file-position in) for form = (read in nil :eof)
            until (eq form :eof)
            when (and (consp form) (eq (car form) 'defun) (eq (cadr form) 'constantly))
            return (values form start (file-position in))
            finally (error "CONSTRUCTOR-SOURCE-MISSING")))))

(defun constructor-run ()
  (let ((*captures* nil) (checks nil)
        (old (ccl::backend-p2-compile ccl::*host-backend*)))
    (multiple-value-bind (source start end) (constructor-source)
      (let* ((*case* "constructor-source")
             (private (with-observer (lambda () (compile nil (cons 'lambda (cddr source))))))
             (samples (list nil t 7 (list :mutable) "string" #'1+)))
        (dolist (value samples)
          (dolist (factory (list private #'constantly))
            (let* ((result (funcall factory value))
                   (prototype (cond ((null value) #'ccl::false) ((eq value t) #'ccl::true)
                                    (t #'ccl::constant-ref)))
                   (n (ccl::%function-code-words prototype)))
              (unless (and (functionp result) (= n (ccl::%function-code-words result))
                           (string= (ccl-resident-bodies::payload-hex result n)
                                    (ccl-resident-bodies::payload-hex prototype n))
                           (every (lambda (args) (equal (multiple-value-list (apply result args)) (list value)))
                                  '(nil (1) (1 2 3) (1 2 3 4 5 6 7 8))))
                (error "CONSTRUCTOR-RETURN-BODY-OR-VALUES")))))
        ;; Two copies must keep their data independent. A function-valued
        ;; constant is returned as data, never invoked by CONSTANT-REF.
        (let* ((a (list :a)) (b (list :b)) (fa (funcall private a)) (fb (funcall private b)))
          (setf (car a) :changed)
          (unless (and (eq a (funcall fa)) (eq b (funcall fb)) (equal b '(:b)))
            (error "CONSTRUCTOR-CAPTURE-INDEPENDENCE")))
        (dolist (spec
                 '(("constant-nil" (lambda () (let ((callee (constantly nil))) (funcall callee 1 2 3 4))) (nil) (nil))
                   ("constant-true" (lambda () (let ((callee (constantly t))) (funcall callee))) (nil) (t))
                   ("constant-number" (lambda () (let ((callee (constantly 7))) (funcall callee))) (nil) (7))
                   ("constant-argument" (lambda (x) (let ((callee (constantly x))) (eq x (funcall callee)))) ((17) (nil) (t)) (t t t))
                   ("constant-conditional" (lambda (flag) (let ((callee (if flag (constantly nil) (constantly t)))) (funcall callee))) ((nil) (t)) (t nil))
                   ("constructor-shadow" (lambda (x) (flet ((constantly (ignored) (declare (ignore ignored)) x))
                                                       (let ((callee (constantly nil))) (funcall callee 3)))) ((1+)) (4))))
          (destructuring-bind (name form inputs expected) spec
            (let* ((*case* name) (fn (with-observer (lambda () (compile nil form))))
                   (actual (mapcar (lambda (args) (apply fn args)) inputs)))
              (unless (equal actual expected) (error "CONSTRUCTOR-PROBE ~s" name))
              (push (obj "name" name "values" (mapcar (lambda (v) (if (eq v t) :true v)) actual)) checks))))
        (unless (eq old (ccl::backend-p2-compile ccl::*host-backend*)) (error "CONSTRUCTOR-OBSERVER-RESTORE"))
        (with-open-file (out (ccl:getenv "FINITE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
          (ccl-startup-census::json
           (obj "captures" (reverse *captures*) "checks" (reverse checks)
                "source_start" start "source_end" end "snapshot" (ccl-startup-census::snapshot)
                "factory_checks" 12 "restored" :true) out)
          (terpri out))))))
