(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (native nil)
       (cases '(("make" (lambda (x) (lambda (&optional (new nil supplied)) (if supplied (setq x new) x))))
                ("one" (lambda () 7)) ("two" (lambda () 7)) ("replacement" (lambda () 23))
                ("call0" (lambda (f) (funcall f))) ("call1" (lambda (f x) (funcall f x)))
                ("keyword" (lambda (&key ((:alias x) 7)) x)) ("call2" (lambda (f x y) (funcall f x y))))))
  (dolist (row cases)
    (let* ((name (first row)) (form (second row))
           (result (compile-metadata-call-form form name (mapcar #'first cases)))
           (fn (compile nil form))
           (specimen (if (equal name "make") (funcall fn 19) fn))
           (args (multiple-value-list (ccl::function-args (ccl::closure-function specimen))))
           (keys (ccl::lfun-keyvect (ccl::closure-function specimen))))
      (push (vector name (coerce (subseq args 0 5) 'vector) (copy-seq (or keys #()))) native)
      (dolist (m (cons result (getf result :children)))
        (push m modules)
        (loop for key across (aref (aref (getf m :pool) 0) 6) do
          (pushnew (cons key (concatenate 'string (package-name (symbol-package key)) "::" (symbol-name key))) *pool-symbol-owners* :key #'car :test #'eq))
        (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
  (setq modules (nreverse modules) native (nreverse native))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"top\":~a,\"captures\":~d}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false") (getf m :captures)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (with-open-file (s (concatenate 'string out "native-metadata.json") :direction :output :if-exists :error) (write-pool-graph s native)))
;; Real package symbols and CCL function-cell replacement; no target model.
(let* ((a (make-package "BINDING-A" :use nil)) (b (make-package "BINDING-B" :use nil))
       (f (intern "F" a)) (g (intern "F" b)) (alias (intern "ALIAS" a)) (lower (intern "f" a))
       (make (compile nil '(lambda (x) (lambda (&optional (new nil supplied)) (if supplied (setq x new) x))))))
  (unwind-protect
    (let* ((one (compile nil '(lambda () 7))) (two (compile nil '(lambda () 7)))
           (x (funcall make 19)) (y (funcall make 41)))
      (setf (symbol-function f) x (symbol-function g) y (symbol-function alias) x (symbol-function lower) two)
      (let* ((old (symbol-function f))
             (before (vector (funcall f) (funcall g) (funcall alias) (funcall lower)))
             (mutate (vector (funcall f 31) (funcall alias) (funcall g))))
        (setf (symbol-function f) one)
        (let ((replace (vector (funcall f) (funcall old) (funcall alias) (funcall g))))
          (setf (symbol-function f) (compile nil '(lambda () 23)))
          (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-behavior.json") :direction :output :if-exists :error)
            (write-pool-graph s (list (vector before mutate replace (vector (funcall f) (funcall old 37) (funcall alias) (funcall g) (funcall lower)))))))))
    (delete-package a) (delete-package b)))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
