(in-package :wasm32-compiler)

(defvar *witness-raw* (make-hash-table :test #'eq))

(defvar *witness-symbols* (make-hash-table :test #'eq))

(defvar *witness-nodes* (make-hash-table :test #'eq))

(defun witness-node (kind fields)
  ;; The native allocator constructs the reference object. The target receives
  ;; the same tagged field sequence, with its own subtag and canonical symbols.
  (let* ((constant (intern (concatenate 'string "SUBTAG-" (symbol-name kind)) "X8664"))
         (object (apply #'ccl::%gvector (symbol-value constant) fields)))
    (setf (gethash object *witness-nodes*) (cons kind fields))
    object))

(defun witness-istruct (name &optional (fields '(nil nil nil nil nil)))
  (let ((object (witness-node 'istruct (cons (ccl::register-istruct-cell name) fields))))
    ;; The native registration cell's metadata is host compiler state. Both
    ;; predicates use the cell identity, with its name retained in the fixture.
    (setf (gethash object *witness-nodes*) (cons 'istruct (cons (cons name nil) fields)))
    object))

(defun witness-array (&optional (fill 2))
  (let* ((object (make-array 4 :initial-element 7 :fill-pointer fill :adjustable t))
         (fields (loop for i below 5 collect (ccl::%svref object i))))
    (setf (fifth fields) (dpb wasm32::subtag-simple-vector (byte 8 8) (fifth fields))
          (gethash object *witness-nodes*) (cons 'vectorh fields))
    object))

(defun witness-lock (rw)
  (let ((object (if rw (ccl:make-read-write-lock) (ccl:make-lock "witness"))))
    (setf (gethash object *witness-nodes*)
          (cons 'lock (list nil (ccl::%svref object 1) 0 "witness" nil nil)))
    object))

(defun witness-symbol (bit)
  (let ((symbol (make-symbol "WITNESS")))
    (ccl::%symbol-bits symbol (ash 1 bit))
    (setf (gethash symbol *witness-symbols*) t)
    symbol))

(defun witness-inputs (name)
  (let ((s (symbol-name name)))
    (cond
      ((member s '("CONSTANT-SYMBOL-P" "FROZEN-DEFINITION-P" "PROCLAIMED-SPECIAL-P") :test #'equal)
       (values (list (list (witness-symbol
                            (cond ((equal s "CONSTANT-SYMBOL-P") ccl::$sym_vbit_const)
                                  ((equal s "FROZEN-DEFINITION-P") ccl::$sym_fbit_frozen)
                                  (t ccl::$sym_vbit_special))))
                     (list (make-symbol "ORDINARY"))) t))
      ((member s '("COMMAND-LINE-ARGUMENTS" "GET-*PRINT-BASE*" "GET-*PRINT-CASE*" "PERIODIC-TASK-INTERVAL" "*%SAVED-METHOD-VAR%*") :test #'equal)
       (values '(()) t))
      ((equal s "SET-*%SAVED-METHOD-VAR%*") (values '((:new) ((1 2))) t))
      ((equal s "GC-RETAIN-PAGES") (values '((nil) (t)) t))
      ((equal s "GC-VERBOSE") (values '((nil) (t) (t nil) (nil t)) t))
      ((equal s "MAKE-APPLICATION-ERROR-HANDLER") (values '((nil :batch) (nil :interactive)) t))
      ((equal s "PROCLAIMED-IGNORE-P") (values '((ccl::witness-ignored) (ccl::witness-other)) t))
      ((equal s "TYPE-CLASS-OR-LOSE") (values '((ccl::constant) (ccl::hairy)) t))
      ((member s '("MAKE-CONSTANT-CTYPE" "MAKE-NEGATION-CTYPE") :test #'equal)
       (values '(() (:type integer) (:type (integer 0 7))) t))
      ((member s '("MAKE-HAIRY-CTYPE" "MAKE-UNKNOWN-CTYPE") :test #'equal)
       (values '(() (:specifier (satisfies member)) (:specifier symbol :enumerable nil)) t))
      ((equal s "MAKE-CLASS-CTYPE") (values '((:fixture-class) ((1 2))) t))
      ((member s '("COMPLEX-SINGLE-FLOAT-P" "COMPLEX-DOUBLE-FLOAT-P") :test #'equal)
       (let* ((single (equal s "COMPLEX-SINGLE-FLOAT-P"))
              (object (if single #c(1.0s0 2.0s0) #c(1.0d0 2.0d0))))
         (setf (gethash object *witness-raw*)
               (if single '(71 0 1065353216 1073741824) '(79 0 0 1072693248 0 1073741824)))
         (values (list (list object)) t)))
      ((member s '("MACPTRP" "POINTERP" "DEAD-MACPTR-P") :test #'equal)
       (let ((object (ccl::%null-ptr)) (dead (equal s "DEAD-MACPTR-P")))
         (when dead (ccl::%macptr->dead-macptr object))
         (setf (gethash object *witness-raw*) (list (if dead 39 31) 0 0 0))
         (values (list (list object)) t)))
      ((member s '("MAKE-VALUES-CTYPE" "MAKE-FUNCTION-CTYPE") :test #'equal)
       (values '(() (:required (integer symbol) :optional (string) :rest t)
                 (:required (integer) :keyp t :keywords ((:x . integer)) :allowp t)) t))
      ((equal s "%MAKE-MEMBER-CTYPE") (values '((nil) ((1 2 :a))) t))
      ((equal s "%MAKE-FOREIGN-CTYPE") (values '((:int) (:double)) t))
      ((equal s "%MAKE-RESTART") (values (list (list 'continue #'identity nil nil nil)) t))
      ((equal s "MAKE-RESTART") (values (list (list nil 'continue #'identity)) t))
      ((member s '("%PATHNAME-HOST" "%PATHNAME-VERSION") :test #'equal)
       (values (list (list (make-pathname :name "witness" :type "lisp" :version :newest))) t))
      ((equal s "MAKE-KEY-INFO")
       (values '(() (:name :x :type integer) (:name :y :type (integer 0 7))) t))
      ((equal s "NEW-LEXICAL-ENVIRONMENT") (values '(() (nil)) t))
      ((equal s "NEW-DEFINITION-ENVIRONMENT") (values '(() (eval) (compile)) t))
      ((equal s "READTABLE-ARG") (values (list (list (witness-istruct 'ccl::readtable))) t))
      ((equal s "%PATH-MEM") (values '(("x" "abcx") ("xy" "abc" ) ("bc" "abcd" 1 3)) t))
      ((equal s "INPUT-STREAM-ARG") (values (list (list (witness-node 'basic-stream '(nil nil nil nil)))) t))
      ((equal s "FLOAT-FORMAT-MAX") (values '((single-float double-float) (double-float single-float) (single-float single-float)) t))
      ((equal s "%NON-EMPTY-ENVIRONMENT-P")
       (values (list (list (witness-istruct 'ccl::lexical-environment '(nil (x) nil nil nil nil nil)))
                     (list (witness-istruct 'ccl::lexical-environment '(nil nil nil nil nil nil nil)))) t))
      ((equal s "NATIVE-CLASS-P")
       (values (list (list (witness-node 'instance '(7 nil nil))) (list nil)) t))
      ((equal s "%%STR-MEMBER") (values '((#\a "abc") (#\λ "xλy") (#\z "abc")) t))
      ((equal s "%EARLY-PREPARE-TO-DESTRUCTURE") (values '((nil) ((1 2) :ignored) ((1 . 2))) t))
      ((equal s "DECODE-FILE-RANGE") (values '((nil) (0) (16389) ((1 . 20000))) t))
      ((equal s "TOKEN2INT") (values '(("123" 0 3 10) ("-17" 0 3 10) ("ff" 0 2 16) ("+42" 0 3 10)) t))
      ((equal s "SYMBOL-ARG") (values '((nil) (t) (:member)) t))
      ((equal s "CHECK-SEQUENCE-BOUNDS") (values '(((1 2 3) 0 nil) ("abc" 1 3) (#(1 2) 2 2)) t))
      ((equal s "FLOAT-FORMAT-NAME") (values '((1.0s0) (-0.0d0)) t))
      ((equal s "MASK-FIELD") (values '((255 65535) (15 35) (-1 77)) t))
      ((equal s "GET-TYPE-PREDICATE") (values (list (list (make-symbol "NO-PREDICATE"))) t))
      ((equal s "SET-TYPE-PREDICATE") (values (list (list (make-symbol "PREDICATE") #'identity)) t))
      ((equal s "%PROCLAIM-SPECIAL") (values (list (list (make-symbol "SPECIAL") t) (list (make-symbol "SPECIAL") nil)) t))
      ((equal s "%SET-FILL-POINTER") (values (list (list (witness-array 0) 3) (list (witness-array 4) 0)) t))
      ((equal s "TYPE-MIGHT-CONTAIN-OTHER-TYPES-P")
       (values (loop for name in '(ccl::hairy-ctype ccl::negation-ctype ccl::union-ctype ccl::intersection-ctype ccl::numeric-ctype)
                     collect (list (witness-istruct name))) t))
      ((equal s "FUNCTION-TYPE-NARGS")
       (values (list (list (witness-istruct 'ccl::function-ctype '(nil nil (a b) (c) nil nil nil nil nil nil)))
                     (list (witness-istruct 'ccl::function-ctype '(nil nil (a) nil t nil nil nil nil nil)))) t))
      ((equal s "VALUES-TYPE-TYPES")
       (values (list (list (witness-istruct 'ccl::values-ctype '(nil nil (a b) (c) nil nil nil nil)) :default)
                     (list (witness-istruct 'ccl::values-ctype '(nil nil (a) nil :rest nil nil nil)) :default)) t))
      ((member s '("LOCKP" "RECURSIVE-LOCK-P" "READ-WRITE-LOCK-P") :test #'equal)
       (values (list (list (witness-lock nil)) (list (witness-lock t)) (list nil)) t))
      ((member s '("%ARRAY-IS-HEADER" "ADJUSTABLE-ARRAY-P" "ARRAY-HAS-FILL-POINTER-P" "FILL-POINTER") :test #'equal)
       (values (list (list (witness-array 0)) (list (witness-array 2)) (list (witness-array 4))) t))
      ((member s '("ARRAY-CTYPE-P" "CLASS-CTYPE-P" "CONS-CTYPE-P" "CONSTANT-CTYPE-P"
                   "FOREIGN-CTYPE-P" "FUNCTION-CTYPE-P" "HAIRY-CTYPE-P" "INTERSECTION-CTYPE-P"
                   "MEMBER-CTYPE-P" "NAMED-CTYPE-P" "NEGATION-CTYPE-P" "NUMERIC-CTYPE-P"
                   "UNION-CTYPE-P" "UNKNOWN-CTYPE-P" "VALUES-CTYPE-P"
                   "HASH-TABLE-P" "READTABLEP" "RANDOM-STATE-P" "RESTARTP" "LISP-THREAD-P"
                   "PATHNAMEP" "LOGICAL-PATHNAME-P" "SEMAPHOREP" "EXTERNAL-ENTRY-POINT-P") :test #'equal)
       (let* ((type (intern (cond ((equal s "PATHNAMEP") "PATHNAME")
                                 ((equal s "LISP-THREAD-P") "LISP-THREAD")
                                 ((equal s "READTABLEP") "READTABLE")
                                 ((equal s "RESTARTP") "RESTART")
                                 ((equal s "SEMAPHOREP") "SEMAPHORE")
                                 (t (subseq s 0 (- (length s) 2)))) "CCL"))
              (object (witness-istruct type)))
         (unless (funcall (fdefinition name) object) (error "Member recipe for ~s (~s) failed" name type))
         (values (list (list object) (list nil) (list 7)
                       (list (witness-istruct 'ccl::witness-other))) t)))
      ((member s '("ISTRUCTP" "ISTRUCT-TYPE-NAME") :test #'equal)
       (values (list (list (witness-istruct 'ccl::witness-structure)) (list nil)) t))
      ((equal s "ISTRUCT-TYPEP")
       (let ((p (witness-istruct 'ccl::witness-structure)))
         (values (list (list p 'ccl::witness-structure) (list p 'ccl::witness-other)) t)))
      ((member s '("STRUCTUREP" "STRUCTURE-TYPEP") :test #'equal)
       (let ((p (witness-node 'struct (list '(ccl::witness-child ccl::witness-parent) '(1 . 2) 7))))
         (values (if (equal s "STRUCTUREP") (list (list p) (list nil))
                   (list (list p 'ccl::witness-child) (list p 'ccl::witness-parent) (list p 'ccl::witness-other))) t)))
      ((equal s "STANDARD-INSTANCE-P")
       (values (list (list (witness-node 'instance '(nil nil 100000))) (list nil)) t))
      ((equal s "PACKAGEP")
       (values (list (list (witness-node 'package '("WITNESS" nil nil nil nil nil nil nil))) (list nil)) t))
      ((equal s "BASIC-STREAM-P")
       (values (list (list (witness-node 'basic-stream '(nil nil nil nil))) (list nil)) t))
      ((equal s "QUOTED-FORM-P") (values '(((quote 7)) ((quote nil)) ((list 7)) (nil)) t))
      ((equal s "LAMBDA-EXPRESSION-P") (values '(((lambda (x) x)) ((lambda () nil)) ((quote 7)) (nil)) t))
      ((member s '("%REQUIRE-TYPE-BUILTIN" "%REQUIRE-TYPE-CLASS-CELL") :test #'equal)
       (values '((7 nil) ((1 . 2) nil) (nil nil)) t))
      ((equal s "SEQUENCE-TYPE") (values '((nil) ((1 2)) (#(1 2)) ("abc")) t))
      (t (values nil nil)))))

(defun witness-environment (name)
  (let ((s (symbol-name name)))
    (cond ((equal s "COMMAND-LINE-ARGUMENTS") '((ccl::*command-line-argument-list* . ("ccl" "--batch"))))
          ((equal s "GET-*PRINT-BASE*") '((*print-base* . 16)))
          ((equal s "GET-*PRINT-CASE*") '((*print-case* . :downcase)))
          ((equal s "PERIODIC-TASK-INTERVAL") '((ccl::*periodic-task-interval* . 0.3s0)))
          ((member s '("GC-RETAIN-PAGES" "GC-VERBOSE") :test #'equal) '((ccl::*gc-event-status-bits* . 0)))
          ((equal s "MAKE-APPLICATION-ERROR-HANDLER") '((ccl::*app-error-handler-mode* . nil)))
          ((member s '("*%SAVED-METHOD-VAR%*" "SET-*%SAVED-METHOD-VAR%*") :test #'equal)
           '((ccl::%saved-method-var% . :old)))
          ((equal s "PROCLAIMED-IGNORE-P") '((ccl::*nx-proclaimed-ignore* . ((ccl::witness-ignored . t)))))
          ((equal s "MAKE-CLASS-CTYPE") '((ccl::*class-type-class* . :class)))
          ((member s '("MAKE-CONSTANT-CTYPE" "MAKE-NEGATION-CTYPE" "MAKE-HAIRY-CTYPE" "MAKE-UNKNOWN-CTYPE" "TYPE-CLASS-OR-LOSE" "MAKE-VALUES-CTYPE" "MAKE-FUNCTION-CTYPE" "%MAKE-MEMBER-CTYPE" "%MAKE-FOREIGN-CTYPE") :test #'equal)
           '((ccl::*type-classes* . ((values . :values) (function . :function) (member . :member) (ccl::foreign . :foreign) (ccl::constant . :constant) (ccl::negation . :negation) (ccl::hairy . :hairy)))))
          (t nil))))

(defun call-with-witness-environment (environment function)
  ;; Some startup globals are deliberately unbindable (DEFGLOBAL). Preserve
  ;; their real cells in this disposable oracle, including on a native error.
  (let ((saved (mapcar (lambda (entry) (list (car entry) (boundp (car entry))
                                           (and (boundp (car entry)) (symbol-value (car entry))))) environment)))
    (unwind-protect
        (progn
          (dolist (entry environment) (set (car entry) (core-copy-input (cdr entry))))
          (funcall function))
      (dolist (entry saved)
        (if (second entry) (set (first entry) (third entry)) (makunbound (first entry)))))))
