(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases '(("process_init" (lambda (cell) (rplaca cell 7) (rplacd cell 9) (values (car cell) (cdr cell))))
                ("worker_init" (lambda (reader cell id) (rplaca cell id) (rplacd cell 11) (funcall reader cell)))
                ("read_cell" (lambda (cell) (values (car cell) (cdr cell))))
                ("mutate" (lambda (cell) (rplaca cell 31) (rplacd cell 37) (values (car cell) (cdr cell))))
                ("call_reader" (lambda (reader cell) (funcall reader cell))))))
 (dolist (row cases)
  (let ((result (compile-call-form (second row) (first row) (mapcar #'first cases))))
   (dolist (m (cons result (getf result :children)))
    (push m modules)
    (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
 (let ((cell (cons nil nil)))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
   (format s "[")
   (loop for (name args) in (list (list "process_init" (list cell)) (list "mutate" (list cell)) (list "read_cell" (list cell)) (list "worker_init" (list (compile nil (second (assoc "read_cell" cases :test #'equal))) (cons nil nil) 2))) for i from 0 do
    (unless (zerop i) (format s ","))
    (let ((v (multiple-value-list (apply (compile nil (second (assoc name cases :test #'equal))) args))))
     (format s "[~d,~d]" (first v) (second v))))
   (format s "]"))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
