(in-package :cl-user)
(defun ll19-json-string (stream string)
  (write-char #\" stream)
  (loop for c across string do
    (case c
      (#\" (write-string "\\\"" stream))
      (#\\ (write-string "\\\\" stream))
      (#\Newline (write-string "\\n" stream))
      (#\Return (write-string "\\r" stream))
      (#\Tab (write-string "\\t" stream))
      (t (write-char c stream))))
  (write-char #\" stream))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-condition-classes.json") :direction :output :if-exists :error)
  (write-char #\[ s)
  (loop for name in '(condition simple-condition simple-error type-error control-error simple-warning program-error ccl::simple-program-error undefined-function unbound-variable storage-condition error ccl::no-applicable-method-exists arithmetic-error division-by-zero floating-point-invalid-operation floating-point-overflow floating-point-underflow floating-point-inexact stream-error end-of-file file-error package-error ccl::simple-package-error ccl::stream-is-closed-error ccl::bad-slot-type ccl::inactive-restart ccl::restart-failure)
        for i from 0 for instance = (make-condition name) do
    (unless (zerop i) (write-char #\, s))
    (write-string "{\"name\":" s) (ll19-json-string s (symbol-name name))
    (write-string ",\"cpl\":[" s)
    (loop for class in (ccl:class-precedence-list (find-class name)) for j from 0 do
      (unless (zerop j) (write-char #\, s))
      (ll19-json-string s (symbol-name (class-name class))))
    (write-char #\] s)
    (write-string ",\"slots\":[" s)
    (loop for slot in (ccl:class-slots (find-class name)) for j from 0 for symbol = (ccl:slot-definition-name slot) do
      (unless (zerop j) (write-char #\, s))
      (write-string "{\"name\":" s) (ll19-json-string s (symbol-name symbol))
      (write-string ",\"default\":" s)
      (cond ((not (slot-boundp instance symbol)) (write-string "{\"unbound\":true}" s))
            ((null (slot-value instance symbol)) (write-string "null" s))
            ((stringp (slot-value instance symbol)) (ll19-json-string s (slot-value instance symbol)))
            (t (error "Unqualified condition slot default ~s" symbol)))
      (write-char #\} s))
    (write-string "]}" s))
  (write-string "]" s))
