(in-package :wasm32-compiler)
(defun b-restart-list (forms)
  (reduce (lambda (a b) `(cons ,a ,b)) forms :from-end t :initial-value nil))
(defun b-expand-restart (form walk lambda-list)
  (let* ((casep (eq (car form) 'restart-case))
         (clauses (if casep (cddr form) (second form)))
         (block (gensym "RESTART-BLOCK")) (tag (gensym "RESTART-TAG"))
         (packet (gensym "RESTART-VALUES")) (bindings nil) (dispatch nil))
    (loop for clause in clauses for index from 0 do
      (unless (and (consp clause) (and (symbolp (first clause)) (first clause)) (>= (length clause) 2)) (refuse :b-restart-clause))
      (pushnew (first clause) *b-restart-names*)
      ;; Owner-registered keyword names for the initial interface; arbitrary
      ;; package symbol installation belongs to the symbol namespace unit.
      (when (and casep (keywordp (third clause))) (refuse :b-restart-options))
      (unless (or casep (= (length clause) 2)) (refuse :b-restart-options))
      (let* ((name (gensym "RESTART")) (args (gensym "RESTART-ARGS"))
             (action (if casep `(lambda (&rest ,args) (throw ,tag (cons ,index ,args))) (funcall walk (second clause)))))
        (push (list name `(%wasm-make-restart (quote ,(first clause)) ,(if casep `(function ,action) action))) bindings)
        (when casep
          (push `(if (eq (car ,packet) ,index)
                   (apply (function (lambda ,(funcall lambda-list (second clause)) ,@(mapcar walk (cddr clause)))) (cdr ,packet))) dispatch))))
    (setq bindings (nreverse bindings) dispatch (nreverse dispatch))
    (if casep
      `(block ,block
         (let* ((,tag (cons nil nil))
                (,packet (let* (,@bindings
                                (ccl::%restarts% (cons ,(b-restart-list (mapcar #'first bindings)) ccl::%restarts%)))
                           (catch ,tag (return-from ,block ,(funcall walk (second form)))))))
           ,(reduce (lambda (item rest) `(if ,(second item) ,(third item) ,rest)) dispatch :from-end t :initial-value nil)))
      `(let* (,@bindings (ccl::%restarts% (cons ,(b-restart-list (mapcar #'first bindings)) ccl::%restarts%)))
         ,@(mapcar walk (cddr form))))))
(defun b-restart-call (name forms)
  (setq *b-restart-used* t)
  (unless (case name (%wasm-make-restart (= (length forms) 2))
                    (%wasm-find-restart (<= 1 (length forms) 2))
                    (%wasm-restart-name (= (length forms) 1))
                    (%wasm-invoke-restart (>= (length forms) 1))) (refuse :b-restart-arity))
  (let ((*b-tail-position* nil))
    (b-frame (length forms)
      (lambda (root)
        (with-output-to-string (s)
          (loop for f in forms for i from 0 do (format s "(i32.store offset=~d ~a ~a)" (+ 8 (* 4 i)) root (b-scalar f)))
          (flet ((arg (i) (b-wat "(i32.load offset=~d ~a)" (+ 8 (* 4 i)) root)))
            (if (eq name '%wasm-invoke-restart)
              (write-string (b-call nil (list (loop for i from 1 below (length forms) collect (make-b-raw-code :text (arg i))) nil)
                                   (b-wat "(i32.load offset=12 (call $restart_base (call $restart_find ~a (i32.const 1) (local.get $top))))" (arg 0))) s)
              (write-string (b-multiple (make-b-raw-code :text
                 (case name
                   (%wasm-make-restart (b-wat "(call $restart_make ~a ~a (local.get $top))" (arg 0) (arg 1)))
                   (%wasm-find-restart
                    (when (= (length forms) 2) (refuse :b-restart-condition-association))
                    (b-wat "(call $restart_find ~a (i32.const 0) (local.get $top))" (arg 0)))
                   (%wasm-restart-name (b-wat "(i32.load offset=8 (call $restart_base ~a))" (arg 0)))))) s))))))))
(defun b-restart-runtime ()
  (pushnew "restart_type" *b-symbols* :test #'equal)
  (let ((registry (b-special-symbol 'ccl::%restarts%)))
    (b-wat "
(func $restart_base (param $x i32) (result i32)
 (local $p i32)
 (local.set $p (call $object_base (local.get $x) (i32.const 32) (i32.const 1666)))
 (if (i32.ne (i32.load offset=4 (local.get $p)) (global.get $symbol_restart_type)) (then (throw $call_error (i32.const 4))))
 (local.get $p))
(func $restart_make (param $name i32) (param $action i32) (param $top i32) (result i32) (local $p i32)
 (local.set $p (i32.load offset=48 (global.get $tcr)))
 (if (i32.or (i32.and (local.get $p) (i32.const 7)) (i32.lt_u (local.get $p) (i32.load offset=56 (global.get $tcr)))) (then (throw $call_error (i32.const 6))))
 (if (i64.gt_u (i64.add (i64.extend_i32_u (local.get $p)) (i64.const 32)) (i64.extend_i32_u (i32.load offset=52 (global.get $tcr)))) (then (throw $call_error (i32.const 6))))
 (call $span (local.get $p) (i32.const 32))
 (i32.store (local.get $p) (i32.const 1666))
 (i32.store offset=4 (local.get $p) (global.get $symbol_restart_type))
 (i32.store offset=8 (local.get $p) (local.get $name))
 (i32.store offset=12 (local.get $p) (local.get $action))
 (i32.store offset=16 (local.get $p) (i32.const 77825))
 (i32.store offset=20 (local.get $p) (i32.const 77825))
 (i32.store offset=24 (local.get $p) (i32.const 77825))
 (i32.store offset=28 (local.get $p) (i32.const 77825))
 (i32.store offset=48 (global.get $tcr) (i32.add (local.get $p) (i32.const 32)))
 (i32.add (local.get $p) (i32.const 6)))
(func $restart_find (param $name i32) (param $required i32) (param $top i32) (result i32)
 (local $clusters i32) (local $items i32) (local $restart i32) (local $base i32)
 (local.set $clusters (call $special_read ~a))
 (block $absent (loop $clusters_loop
  (br_if $absent (i32.eq (local.get $clusters) (i32.const 77825)))
  (local.set $items (i32.load offset=4 (call $handler_cons (local.get $clusters))))
  (block $cluster_done (loop $items_loop
   (br_if $cluster_done (i32.eq (local.get $items) (i32.const 77825)))
   (local.set $restart (i32.load offset=4 (call $handler_cons (local.get $items))))
   (local.set $base (call $restart_base (local.get $restart)))
   (if (i32.or (i32.eq (local.get $name) (local.get $restart)) (i32.eq (local.get $name) (i32.load offset=8 (local.get $base)))) (then (return (local.get $restart))))
   (local.set $items (i32.load (call $handler_cons (local.get $items)))) (br $items_loop)))
  (local.set $clusters (i32.load (call $handler_cons (local.get $clusters)))) (br $clusters_loop)))
 (if (local.get $required) (then (call $implicit_error (i32.const 8) (local.get $top)) unreachable))
 (i32.const 77825))" registry)))
(defun b-restart-symbol (symbol)
  (when (eq symbol 'or) (pushnew "expected_or" *b-symbols* :test #'equal) (return-from b-restart-symbol "(global.get $symbol_expected_or)"))
  (when (eq symbol 'function) (pushnew "expected_function" *b-symbols* :test #'equal) (return-from b-restart-symbol "(global.get $symbol_expected_function)"))
  (unless (and (symbolp symbol) symbol (symbol-package symbol)) (refuse :b-restart-symbol))
  (let ((name (with-output-to-string (s)
                (write-string "restart_name_" s)
                (loop for c across (package-name (symbol-package symbol)) do (format s "~6,'0x" (char-code c)))
                (write-char #\_ s)
                (loop for c across (symbol-name symbol) do (format s "~6,'0x" (char-code c))))))
    (pushnew name *b-symbols* :test #'equal)
    (b-wat "(global.get $symbol_~a)" name)))
