(func $stack_guard (param $end i64) (param $top i32) (param $kind i32)
 (local $base i32) (local $limit i32) (local $reserve i32) (local $flags i32) (local $exception exnref)
 (if (i32.eq (local.get $kind) (i32.const 18))
  (then (local.set $base (i32.load offset=68 (global.get $tcr))) (local.set $limit (i32.load offset=72 (global.get $tcr))))
  (else (if (i32.eq (local.get $kind) (i32.const 19))
   (then (local.set $base (i32.load offset=80 (global.get $tcr))) (local.set $limit (i32.load offset=84 (global.get $tcr))))
   (else (local.set $base (i32.load offset=92 (global.get $tcr))) (local.set $limit (i32.load offset=96 (global.get $tcr)))))))
 (local.set $reserve (i32.load offset=100 (global.get $tcr)))
 (if (i32.or (i32.and (i32.or (local.get $base) (i32.or (local.get $limit) (local.get $reserve))) (i32.const 15))
             (i32.or (i32.gt_u (local.get $base) (local.get $limit)) (i32.gt_u (local.get $reserve) (i32.sub (local.get $limit) (local.get $base))))) (then (throw $call_error (if (result i32) (i32.eq (local.get $kind) (i32.const 19)) (then (i32.const 13)) (else (i32.const 2))))))
 (if (i64.gt_u (i64.extend_i32_u (local.get $limit)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))) (then (throw $call_error (if (result i32) (i32.eq (local.get $kind) (i32.const 19)) (then (i32.const 13)) (else (i32.const 2))))))
 (if (i64.gt_u (local.get $end) (i64.extend_i32_u (local.get $limit))) (then (throw $call_error (if (result i32) (i32.eq (local.get $kind) (i32.const 19)) (then (i32.const 13)) (else (i32.const 2))))))
 (if (i64.lt_u (local.get $end) (i64.extend_i32_u (local.get $base))) (then (throw $call_error (if (result i32) (i32.eq (local.get $kind) (i32.const 19)) (then (i32.const 13)) (else (i32.const 2))))))
 (local.set $flags (i32.load offset=180 (global.get $tcr)))
 (if (i32.and (i32.ne (local.get $reserve) (i32.const 0)) (i32.eqz (i32.and (local.get $flags) (i32.const 1)))) (then
  (if (i64.gt_u (local.get $end) (i64.extend_i32_u (i32.sub (local.get $limit) (local.get $reserve)))) (then
   (i32.store offset=180 (global.get $tcr) (i32.or (local.get $flags) (i32.const 1)))
   (block $stack_failed (result exnref) (try_table (catch_all_ref $stack_failed)
    (call $implicit_error (local.get $kind) (local.get $top)) unreachable) unreachable)
   (local.set $exception)
   (i32.store offset=180 (global.get $tcr) (local.get $flags))
   (throw_ref (local.get $exception)))))))
(func $control_push (param $record i32) (param $top i32) (local $p i32)
 (if (i32.eqz (i32.load offset=92 (global.get $tcr))) (then (return)))
 (local.set $p (i32.load offset=88 (global.get $tcr)))
 (if (i32.or (i32.and (local.get $p) (i32.const 15)) (i32.lt_u (local.get $p) (i32.load offset=92 (global.get $tcr)))) (then (throw $call_error (i32.const 2))))
 (call $stack_guard (i64.add (i64.extend_i32_u (local.get $p)) (i64.const 16)) (local.get $top) (i32.const 20))
 (i32.store (local.get $p) (local.get $record))
 (i32.store offset=4 (local.get $p) (i32.const 1129533489))
 (i32.store offset=8 (local.get $p) (i32.const 0)) (i32.store offset=12 (local.get $p) (i32.const 0))
 (i32.store offset=88 (global.get $tcr) (i32.add (local.get $p) (i32.const 16))))
(func $control_pop (param $record i32) (local $p i32)
 (if (i32.eqz (i32.load offset=92 (global.get $tcr))) (then (return)))
 (local.set $p (i32.load offset=88 (global.get $tcr)))
 (if (i32.or (i32.and (local.get $p) (i32.const 15)) (i32.le_u (local.get $p) (i32.load offset=92 (global.get $tcr)))) (then (throw $call_error (i32.const 2))))
 (local.set $p (i32.sub (local.get $p) (i32.const 16))) (call $span (local.get $p) (i32.const 16))
 (if (i32.or (i32.ne (i32.load (local.get $p)) (local.get $record)) (i32.ne (i32.load offset=4 (local.get $p)) (i32.const 1129533489))) (then (throw $call_error (i32.const 2))))
 (i32.store offset=88 (global.get $tcr) (local.get $p)))
