;;; No upstream definitions, source forms or compiler IR are overwritten.
(defpackage :ccl-kernel-resource (:use :cl))
(defvar wasm-census-services::*kernel-resource-name* nil)
(defvar wasm-census-services::*kernel-resource-ready* nil)
(in-package :ccl-kernel-resource)
(defun obj (&rest xs) (apply #'ccl-source-traversal::obj xs))
(defun field (x key) (ccl-source-traversal::field x key))
(defun bool (x) (if x :true :false))
(defun label (x) (ccl-source-traversal::label x))
(defun snapshot (x)
  (cond ((stringp x) (copy-seq x)) ((null x) :null)
        ((integerp x) x) ((eq x t) :true)
        (t (error "REFERENCE-RESULT-SHAPE"))))

(defun read-forms (text package)
  (let ((*package* (find-package package)) (*read-eval* nil) (eof (list nil)) (result nil))
    (with-input-from-string (s text)
      (loop for form = (read s nil eof) until (eq form eof) do (push form result)))
    (nreverse result)))

(defun reference (forms replacement)
  ;; Host compilation is explicit and limited to the reference LABELS closure.
  (ccl-census-macros::native-function
    `(lambda ()
       (labels (,@(mapcar #'cdr forms) ,(cdr replacement))
         (list #'wasm-census-services::install-kernel-resource #'ccl::kernel-path)))))

(defun probe (name thunk)
  (let ((values nil) (problem :null) (kind :null) (status "RETURNED"))
    (handler-case (setf values (mapcar #'snapshot (multiple-value-list (funcall thunk))))
      (error (e) (setf status "ERROR" problem (princ-to-string e) kind (label (type-of e)))))
    (obj "name" name "status" status "values" values "error" problem "error_type" kind
         "ready" (bool wasm-census-services::*kernel-resource-ready*)
         "stored" (snapshot wasm-census-services::*kernel-resource-name*))))

(defun exercise (factory)
  (destructuring-bind (install lookup) (funcall factory)
    (let ((rows nil))
      (let ((wasm-census-services::*kernel-resource-name* nil)
            (wasm-census-services::*kernel-resource-ready* nil)
            (resource (copy-seq "bundle:/bootstrap/ccl.image")))
        (push (probe "before-install" lookup) rows)
        (push (probe "install" (lambda () (funcall install resource))) rows)
        (push (probe "lookup" lookup) rows)
        (setf (char resource 0) #\X)
        (push (probe "caller-input-mutated" lookup) rows)
        (push (probe "returned-string-mutated"
                     (lambda () (let ((answer (funcall lookup))) (setf (char answer 0) #\Y))
                       (funcall lookup))) rows)
        (push (probe "second-install" (lambda () (funcall install "bundle:/replacement"))) rows)
        (push (probe "after-second-install" lookup) rows))
      (dolist (case (list (list "invalid-number" 42) (list "invalid-empty" "")
                         (list "invalid-nul" (coerce (list #\a (code-char 0) #\b) 'string))))
        (let ((wasm-census-services::*kernel-resource-name* nil)
              (wasm-census-services::*kernel-resource-ready* nil))
          (push (probe (first case) (lambda () (funcall install (second case)))) rows)
          (push (probe (concatenate 'string (first case) "-retry")
                       (lambda () (funcall install "bundle:/retry") (funcall lookup))) rows)))
      (let ((wasm-census-services::*kernel-resource-name* nil)
            (wasm-census-services::*kernel-resource-ready* nil))
        (push (probe "opaque-unicode-name"
                     (lambda () (funcall install "bundle:/a/../λ image") (funcall lookup))) rows))
      (nreverse rows))))

(defun run ()
  (let* ((path (pathname (ccl:getenv "CCL_TRAVERSE_SOURCE")))
         (text (ccl-source-traversal::source-text path))
         (replacement-path (pathname (ccl:getenv "CCL_RESOURCE_REPLACEMENT")))
         (replacement-text (ccl-source-traversal::source-text replacement-path))
         (service-text (ccl-source-traversal::source-text (pathname (ccl:getenv "CCL_RESOURCE_SERVICE"))))
         (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
         (names '(ccl::kernel-path wasm-census-services::install-kernel-resource wasm-census-services::kernel-resource-identity))
         (bindings (mapcar #'fboundp names))
         (old-pass2 (ccl::backend-p2-compile ccl-census-stub::*backend*))
         (before-name wasm-census-services::*kernel-resource-name*)
         (before-ready wasm-census-services::*kernel-resource-ready*)
         (original nil) (replacement nil) (context nil))
    (multiple-value-bind (index tail eof) (ccl-source-traversal::index-source text nil)
      (declare (ignore tail eof))
      (let ((entry (nth 11 index)))
        (unless (and (= (field entry "ordinal") 12) (= (field entry "start") 12716)
                     (= (field entry "end") 13142) (equal (field entry "name") "CCL::KERNEL-PATH"))
          (error "KERNEL-SOURCE-BOUNDARY"))
        (ccl-census-descriptions::with-descriptions
          (lambda () (ccl-census-stub::with-target-state
            (lambda ()
              (setf context (ccl-source-traversal::context)
                    original (first (ccl-source-traversal::traverse path text (list entry))))
              (let ((replacement-index (ccl-source-traversal::index-source replacement-text nil)))
                (unless (= (length replacement-index) 1) (error "REPLACEMENT-FORM-COUNT"))
                (setf replacement (first (ccl-source-traversal::traverse replacement-path replacement-text replacement-index))))))))
        (let* ((forms (read-forms service-text "WASM-CENSUS-SERVICES"))
               (target-form (first (read-forms replacement-text "CCL")))
               (rows (exercise (reference forms target-form))))
          (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                       (eq old-pass2 (ccl::backend-p2-compile ccl-census-stub::*backend*))
                       (every #'eq bindings (mapcar #'fboundp names))
                       (eq before-name wasm-census-services::*kernel-resource-name*)
                       (eq before-ready wasm-census-services::*kernel-resource-ready*))
            (error "RESOURCE-STATE-NOT-RESTORED"))
          (with-open-file (out (ccl:getenv "CCL_RESOURCE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
            (ccl-startup-census::json
              (obj "version" 1 "contract" "KERNEL-RESOURCE-IDENTITY" "target" context
                   "source" (obj "path" "lib/dumplisp.lisp" "entry" entry
                                 "text" (subseq text (field entry "start") (field entry "end")))
                   "original" original "replacement" replacement
                   "replacement_text" replacement-text "service_text" service-text
                   "reference_cases" rows "state_restored" :true "source_bindings_unchanged" :true
                   "target_runtime_implemented" :false "native_reference_only" :true) out)
            (terpri out))
          (format t "KERNEL-RESOURCE-COMPLETE ~d~%" (length rows)))))))
