;;; Ordinary Lisp through both file compilers; raw bits are the comparison.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0)))
  (proclaim '(notinline fu-collect fu-identity fu-note fu-mutate)))

(defmacro fu-arithmetic (name type operation)
  `(defun ,name (x y)
     (declare (type ,type x y))
     (,operation x y)))
(fu-arithmetic fu-dadd double-float +)
(fu-arithmetic fu-dsub double-float -)
(fu-arithmetic fu-dmul double-float *)
(fu-arithmetic fu-ddiv double-float /)
(fu-arithmetic fu-sadd single-float +)
(fu-arithmetic fu-ssub single-float -)
(fu-arithmetic fu-smul single-float *)
(fu-arithmetic fu-sdiv single-float /)

(defvar *fu-order* nil)
(defvar *fu-special* 0.0d0)
(defun fu-note (name value) (push name *fu-order*) value)
(defun fu-identity (x) x)
(defun fu-mutate (destination value)
  (declare (double-float destination value))
  (%setf-double-float destination value))
(defun fu-mutating-call (x y)
  (declare (double-float x y))
  (fu-mutate x y)
  x)
(defun fu-collect ()
  #+wasm32-target (write-line "EB-GC")
  #-wasm32-target (gc)
  0.5d0)

(defun fu-moving (x pair)
  (declare (double-float x))
  (let ((sum 0.0d0))
    (declare (double-float sum))
    (dotimes (i 4)
      (setq sum (+ sum x (the double-float (fu-collect))))
      (assert (= (car pair) 17)))
    (values sum pair x)))
(defun fu-captured (x)
  (declare (double-float x))
  (let ((sum 0.0d0))
    (declare (double-float sum))
    (let ((step (lambda () (incf sum x))))
      (funcall step) (funcall step) sum)))
(defun fu-special (x)
  (declare (double-float x))
  (let ((*fu-special* x))
    (declare (double-float *fu-special*))
    (incf *fu-special* x)
    *fu-special*))
(defun fu-assign (x y)
  (declare (double-float x y))
  (let ((sum x))
    (declare (double-float sum))
    (values (setq sum (+ sum y)) sum (fu-identity sum))))
(defun fu-bindings (x y)
  (declare (double-float x y))
  (let ((x y) (y x))
    (declare (double-float x y))
    (let* ((a (+ x y)) (b (- a x)))
      (declare (double-float a b))
      (multiple-value-bind (p q) (values a b)
        (declare (double-float p q))
        (if (> p q) (setq p (- p q)) (setq p (+ p q)))
        (+ p q)))))
(defun fu-order (x y)
  (declare (double-float x y))
  (+ (the double-float (fu-note :left x))
     (the double-float (fu-note :right y))))
(defun fu-round-single (x y)
  (declare (single-float x y))
  (- (+ x y) x))
(defun fu-round-double (x y)
  (declare (double-float x y))
  (- (+ x y) x))
(defun fu-safe (x y)
  (declare (double-float x y) (optimize (safety 3)))
  (/ x y))
(defun fu-safe-local (x y)
  (declare (double-float x y))
  (locally (declare (optimize (safety 3))) (/ x y)))
(defun fu-unsafe-local (x y)
  (declare (double-float x y) (optimize (safety 3)))
  (locally (declare (optimize (safety 1))) (/ x y)))

(defun fu-bits (x)
  (etypecase x
    (single-float
     (let ((bits (logand #xffffffff (single-float-bits x))))
       (if (and (= (ldb (byte 8 23) bits) 255)
                (not (zerop (ldb (byte 23 0) bits))))
         '(:single :nan) (list :single bits))))
    (double-float
     (multiple-value-bind (hi lo) (double-float-bits x)
       (setq hi (logand #xffffffff hi) lo (logand #xffffffff lo))
       (if (and (= (ldb (byte 11 20) hi) 2047)
                (not (zerop (logior (ldb (byte 20 0) hi) lo))))
         '(:double :nan) (list :double hi lo))))))
(defun fu-row (name values)
  (format t "FU-ROW ~s ~s~%" name (mapcar #'fu-bits values)))

;;; The ARM policy selected for Wasm omits FP exception checks at safety 1.
;;; Mask the native hardware while comparing these unchecked operations.
#-wasm32-target
(set-fpu-mode :rounding-mode :nearest :invalid nil :division-by-zero nil
              :overflow nil :underflow nil :inexact nil)
(let ((double-inputs
        (list (list 1.5d0 0.5d0) (list -2.5d0 0.25d0)
              (list -0.0d0 0.0d0) (list 0.0d0 -0.0d0)
              (list least-positive-double-float 2.0d0)
              (list least-positive-normalized-double-float 0.5d0)
              (list most-positive-double-float 2.0d0)
              (list 1.0d0 0.0d0) (list 0.0d0 0.0d0)))
      (single-inputs
        (list (list 1.5f0 0.5f0) (list -2.5f0 0.25f0)
              (list -0.0f0 0.0f0) (list 0.0f0 -0.0f0)
              (list least-positive-single-float 2.0f0)
              (list least-positive-normalized-single-float 0.5f0)
              (list most-positive-single-float 2.0f0)
              (list 1.0f0 0.0f0) (list 0.0f0 0.0f0))))
  (dolist (name '(fu-dadd fu-dsub fu-dmul fu-ddiv))
    (dolist (args double-inputs) (fu-row name (list (apply name args)))))
  (dolist (name '(fu-sadd fu-ssub fu-smul fu-sdiv))
    (dolist (args single-inputs) (fu-row name (list (apply name args))))))
(fu-row 'round-single (list (fu-round-single 16777216.0f0 1.0f0)))
(fu-row 'round-double (list (fu-round-double 9007199254740992.0d0 1.0d0)))
(assert (zerop (fu-round-single 16777216.0f0 1.0f0)))
(assert (zerop (fu-round-double 9007199254740992.0d0 1.0d0)))
(fu-row 'assign (multiple-value-list (fu-assign 1.5d0 0.5d0)))
(fu-row 'bindings (list (fu-bindings 1.5d0 0.5d0)))
(fu-row 'captured (list (fu-captured 1.5d0)))
(fu-row 'special (list (fu-special 1.5d0)))
(fu-row 'order (list (fu-order 1.5d0 0.5d0)))
(assert (equal *fu-order* '(:right :left)))
(let ((destination (fu-dadd (fu-identity 0.0d0) (fu-identity 1.5d0))))
  (fu-row 'mutating-call (list (fu-mutating-call destination 0.5d0) destination)))
(let ((pair (cons 17 23)))
  (multiple-value-bind (sum returned x) (fu-moving 1.5d0 pair)
    (assert (eq pair returned))
    (assert (= sum 8.0d0))
    (fu-row 'moving (list sum x))))
(fu-row 'unsafe-local (list (fu-unsafe-local 1.0d0 0.0d0)))

#-wasm32-target
(set-fpu-mode :invalid t :division-by-zero t :overflow t)
(dolist (name '(fu-safe fu-safe-local))
  (assert (handler-case (progn (funcall name 1.0d0 0.0d0) nil)
            (division-by-zero (condition)
              (and (eq (arithmetic-error-operation condition) '/)
                   (equal (arithmetic-error-operands condition) '(1.0d0 0.0d0))))))
  (dolist (row (list (list 0.0d0 0.0d0 'floating-point-invalid-operation)
                    (list most-positive-double-float least-positive-double-float
                          'floating-point-overflow)))
    (assert (handler-case (progn (funcall name (first row) (second row)) nil)
              (arithmetic-error (condition)
                (and (typep condition (third row))
                     (eq (arithmetic-error-operation condition) '/)
                     (equal (arithmetic-error-operands condition)
                            (list (first row) (second row)))))))))
(assert (handler-case (progn (fu-safe :bad 1.0d0) nil) (type-error () t)))
;;; Wrong declarations are not a native low-safety comparison. The Wasm
;;; unboxing boundary deliberately retains a checked type refusal.
#+wasm32-target
(assert (handler-case (progn (funcall 'fu-dadd :bad 1.0d0) nil) (type-error () t)))
(fu-row 'after-errors (list (fu-dadd 1.5d0 0.5d0)))
(format t "FU-PASS~%")
