;;; Observe U1 object serialization. No shared source or compiler binding changes.
(defpackage :ccl-target-objects (:use :cl))
(in-package :ccl-target-objects)
(defvar *loaded* nil)
(defun obj (&rest xs) (apply #'ccl-target-helpers::obj xs))
(defun bool (x) (ccl-target-helpers::bool x))
(defun field (x key) (ccl-source-traversal::field x key))
(defun syntax (x) (ccl-source-expanders::syntax x))
(defun file (name)
  (merge-pathnames (concatenate 'string name ".dx64fsl")
                  (pathname (concatenate 'string (ccl:getenv "CCL_OBJECT_DIRECTORY") "/"))))
(defun dump-objects (name cell pair)
  ;; The real native scanner calls MAKE-LOAD-FORM and ISTRUCT-CELL-P.
  ;; Only data is written: no fixture function enters this FASL.
  (when (probe-file (file name)) (error "OBJECT-OUTPUT-EXISTS"))
  (let ((ccl::*target-backend* ccl::*host-backend*)
        (ccl::*fasl-backend* ccl::*host-backend*)
        (ccl::*fasl-target* (ccl::backend-name ccl::*host-backend*))
        (ccl::*fasl-setf-name-alias-alist* nil))
    (ccl::fasl-scan-forms-and-dump-file
     ;; $FASL-DEFPARAMETER = 39 in pinned xdump/faslenv.lisp; its compile-time
     ;; constant is not bound in the clean saved image.
     (list (list 39 '*loaded* (list cell pair cell) nil)) (file name))))
(defun copied-classes ()
  (let ((table (make-hash-table :test #'eq)))
    (maphash (lambda (k v) (setf (gethash k table) v)) ccl::%find-classes%) table))
(defun observe-load (name file-name expected-cell expected-pair original-cell original-pair)
  (let ((*loaded* nil))
    (load (file file-name) :verbose nil :print nil)
    (let ((cell (first *loaded*)) (pair (second *loaded*)))
      (obj "name" name "file" (concatenate 'string file-name ".dx64fsl")
           "length" (length *loaded*) "class_cell" (bool (typep cell 'ccl::class-cell))
           "class_name" (if (typep cell 'ccl::class-cell) (syntax (ccl::class-cell-name cell)) :null)
           "class_registered" (bool (eq cell (gethash 'ccl::ioblock ccl::%find-classes%)))
           "class_expected" (bool (eq cell expected-cell))
           "class_original" (bool (eq cell original-cell))
           "class_empty" (bool (and (typep cell 'ccl::class-cell) (null (ccl::class-cell-class cell))))
           "shared_class" (bool (eq cell (third *loaded*)))
           "restart_name" (if (consp pair) (syntax (car pair)) :null)
           "restart_registered" (bool (eq pair (assoc 'restart ccl::*istruct-cells*)))
           "restart_expected" (bool (eq pair expected-pair))
           "restart_original" (bool (eq pair original-pair))
           "restart_empty" (bool (and (consp pair) (null (cdr pair))))))))
(defun roundtrips (cell pair)
  (let ((rows nil))
    (push (observe-load "original" "objects" cell pair cell pair) rows)
    (let* ((ccl::%find-classes% (copied-classes))
           (ccl::*istruct-cells* (remove 'restart ccl::*istruct-cells* :key #'car))
           (fresh-cell (ccl::make-class-cell 'ccl::ioblock))
           ;; Defeat REGISTER-ISTRUCT-CELL's compiler macro here: the point is
           ;; to call the registry function under this dynamic private list.
           (fresh-pair (funcall (fdefinition 'ccl::register-istruct-cell) 'restart)))
      (setf (gethash 'ccl::ioblock ccl::%find-classes%) fresh-cell)
      (dolist (name '("fresh" "fresh-repeat"))
        (push (observe-load name "objects" fresh-cell fresh-pair cell pair) rows))
      (dolist (name '("wrong-class" "wrong-restart" "unregistered" "unevaluated"))
        (push (observe-load name name fresh-cell fresh-pair cell pair) rows)))
    (let ((ccl::%find-classes% (copied-classes))
          (ccl::*istruct-cells* (remove 'restart ccl::*istruct-cells* :key #'car)))
      (remhash 'ccl::ioblock ccl::%find-classes%)
      (push (observe-load "absent" "objects" nil nil cell pair) rows)
      (push (observe-load "created-repeat" "objects"
                          (gethash 'ccl::ioblock ccl::%find-classes%)
                          (assoc 'restart ccl::*istruct-cells*) cell pair) rows))
    (nreverse rows)))
(defun object-witness ()
  (let* ((literals ccl-source-expanders::*literals*)
         (class (find 'ccl::class-cell literals :key (lambda (r) (type-of (car r)))))
         (wrapper (find 'ccl::class-wrapper literals :key (lambda (r) (type-of (car r)))))
         (cell (car class)) (pair (assoc 'restart ccl::*istruct-cells*))
         (classes ccl::%find-classes%) (pairs ccl::*istruct-cells*)
         (saved (loop for k being the hash-keys of classes using (hash-value v) collect (cons k v)))
         (pair-values (mapcar (lambda (p) (cons p (cdr p))) pairs)))
    (unless (and class wrapper (eq cell (gethash 'ccl::ioblock classes))
                 (eq (cdr pair) (car wrapper)) (ccl::istruct-cell-p pair))
      (error "ACTUAL-OBJECT-JOIN"))
    (dump-objects "objects" cell pair)
    ;; The changed payload remains an actual registered cell in a private list.
    (dolist (spec '(("empty-payload" nil) ("sentinel-payload" :must-not-be-serialized)))
      (let* ((p (cons 'restart (second spec)))
             (ccl::*istruct-cells* (cons p (remove 'restart pairs :key #'car))))
        (unless (ccl::istruct-cell-p p) (error "METAMORPHIC-NOT-REGISTERED"))
        (dump-objects (first spec) cell p)))
    (dump-objects "wrong-class" (ccl::make-class-cell 'ccl::not-ioblock) pair)
    (let* ((p (cons 'ccl::not-restart nil)) (ccl::*istruct-cells* (cons p pairs)))
      (dump-objects "wrong-restart" cell p))
    (dump-objects "unregistered" cell (cons 'restart nil))
    (dump-objects "unevaluated" (make-load-form cell) pair)
    (let ((rows (roundtrips cell pair)))
      (unless (and (eq classes ccl::%find-classes%) (eq pairs ccl::*istruct-cells*)
                   (= (length saved) (hash-table-count classes))
                   (every (lambda (r) (eq (cdr r) (gethash (car r) classes))) saved)
                   (every (lambda (r) (eq (cdr r) (cdr (car r)))) pair-values))
        (error "OBJECT-REGISTRY-NOT-RESTORED"))
      (obj "class_literal_id" (field (cdr class) "id")
           "wrapper_literal_id" (field (cdr wrapper) "id")
           "class_registry_join" :true "wrapper_registry_join" :true
           "class_creation_form" (syntax (make-load-form cell))
           "registered_restart" (syntax pair) "roundtrips" rows "registry_restored" :true))))

(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (ccl-source-expanders::*registry* nil) (ccl-source-expanders::*compiled* nil)
        (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
        (ccl-source-expanders::*literals* nil) (ccl-target-helpers::*sources* nil)
        (ccl-target-helpers::*calls* nil) (ccl-target-types::*trace* nil) (ccl-target-predicates::*trace* nil)
        (ccl-target-aliases::*trace* nil) (ccl-target-aliases::*aliases* nil)
        (ccl-target-predicates::*mode* "normal") (ccl-target-aliases::*mode* "normal")
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
        (names '(typep ccl::specifier-type-if-known ccl::optimize-typep ccl::optimize-ctypep ccl::nx-target-type)))
   (let ((globals (mapcar #'fdefinition names)))
    (ccl-source-expanders::prepare)
    (dolist (r (reverse ccl-source-expanders::*registry*)) (ccl-target-helpers::ident (third r)) (ccl-target-helpers::ident (fourth r)))
    (flet ((source (path name) (ccl-target-helpers::read-form path name)))
     (let* ((helper (source "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
            (range (source "compiler/nx0.lisp" "defun nx1-target-fixnump"))
            (eql-form (source "compiler/optimizers.lisp" "define-compiler-macro eql"))
            (typep-form (source "compiler/nx0.lisp" "defun nx-form-typep"))
            (form-type (source "compiler/nx0.lisp" "defun nx-form-type"))
            (target-type (source "compiler/nx-basic.lisp" "defun nx-target-type"))
            (lookup (source "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
            (stream (source "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
            (vector (source "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
            (macro (source "compiler/optimizers.lisp" "define-compiler-macro typep"))
            (optimizer (source "compiler/optimizers.lisp" "defun optimize-typep"))
            (entry (ccl-target-helpers::compiler-entry 'typep)) (compiled nil))
       (ccl-source-expanders::with-compiler-observation
        (lambda ()
         (setf (third (ccl-target-helpers::compiler-entry 'eql))
               (ccl-target-types::build helper range eql-form typep-form form-type target-type "normal")
               (third (ccl-target-helpers::compiler-entry 'ccl::basic-stream-p)) (ccl-target-helpers::build-stream lookup stream)
               (third (ccl-target-helpers::compiler-entry 'vectorp)) (ccl-target-helpers::build-stream lookup vector)
               compiled (ccl-target-aliases::build macro optimizer target-type)
               (third entry) compiled)))
       (let ((ccl-target-predicates::*phase* "dumplisp")) (ccl-source-expanders::with-routing #'ccl-census-descriptions::run))
       (let ((witness (object-witness)))
         (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                      (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                      (every #'eq globals (mapcar #'fdefinition names))) (error "OBJECT-STATE-NOT-RESTORED"))
         (with-open-file (out (ccl:getenv "CCL_OBJECT_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
           (ccl-startup-census::json
            (obj "version" 1 "events" (sort (copy-list ccl-source-expanders::*events*) #'<
                                              :key (lambda (e) (field e "sequence")))
                 "literals" (mapcar #'cdr (reverse ccl-source-expanders::*literals*))
                 "witness" witness "restored" :true "native_data_only" :true
                 "wasm_materialization" "NOT_RUN" "macro_environment_qualified" :false
                 "graph_edges_replaced" 0) out) (terpri out))))))))
