    (defun core-cpl-select (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((condition (svref image 2)))
        (core-collect)
        (handler-case (progn (signal condition) :unhandled)
          (cpl-diamond () :diamond)
          (cpl-left () :left)
          (cpl-right () :right)
          (error () :error))))

    (defun core-cpl-decline (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((condition (svref image 2)) (trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (push :outer trace))))
          (handler-bind ((cpl-left (lambda (c)
                                     (declare (ignore c))
                                     (core-collect)
                                     (push :left trace)))
                         (cpl-right (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (push :right trace))))
            (signal condition)))
        (reverse trace)))

    (defun core-cpl-types (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((condition (svref image 2)))
        (core-collect)
        (values (typep condition 'cpl-left)
                (typep condition 'cpl-right)
                (typep condition 'cpl-diamond)
                (typep condition 'error)
                (typep condition 'warning))))

    (defun core-cpl-restart (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((condition (svref image 2)) (cleaned nil))
        (values
          (handler-bind ((condition (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (invoke-restart 'use-value 37))))
            (restart-case
                (unwind-protect (error condition)
                  (core-collect)
                  (setq cleaned t))
              (use-value (value) value)))
          cleaned)))

    (defun core-cpl-construct (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((condition (make-condition 'type-error :datum (list 17)
                                                 :expected-type 'integer)))
        (core-collect)
        (handler-case (error condition)
          (cpl-left () :wrong)
          (type-error (c)
            (core-collect)
            (values (type-error-datum c) (type-error-expected-type c)
                    (typep c 'error))))))

    (defun core-cpl-resignal (image)
      #+wasm32-target (setq ccl::*class-table* (svref image 0))
      (let ((trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (core-collect)
                                    (push :outer trace))))
          (handler-bind ((condition (lambda (c)
                                      (push :inner trace)
                                      (signal c)
                                      (core-collect)
                                      (push :returned trace))))
            (signal (svref image 2))))
        (reverse trace)))
