(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
 (cases '(("reset_winners" (lambda (operation table done) (multiple-value-prog1 (funcall operation table nil nil) (rplaca done 301))))
 ("clear_apply" (lambda (operation table done) (multiple-value-prog1 (apply operation (cons table (cons nil (cons nil nil)))) (rplaca done 302))))
 ("clear_values" (lambda (operation table done) (multiple-value-bind (x y) (funcall operation table nil nil) (rplaca done 303) (values x y))))
 ("clear_receiver" (lambda (&optional x y) (values x y)))
 ("clear_direct" (lambda (operation receiver table done) (multiple-value-prog1 (multiple-value-call receiver (funcall operation table nil nil)) (rplaca done 304))))
 ("clear_indirect" (lambda (operation receiver table done) (multiple-value-prog1 (multiple-value-call receiver (if table (funcall operation table nil nil) (funcall operation nil nil nil))) (rplaca done 305))))
 ("clear_cleanup" (lambda (operation table done) (unwind-protect (funcall operation table nil nil) (rplaca done 306)))))))
 ;; Bind the exact startup registration form and execute its unmodified
 ;; registered function, dynamically substituting only the owned table.
 (let* ((*package* (find-package "CCL"))
        (form (with-open-file (f "compiler/nx.lisp") (file-position f 8001) (read f)))
        (matches (remove-if-not (lambda (f)(eq (ccl::function-name f) 'ccl::reset-winners)) ccl::*lisp-system-pointer-functions*)))
  (assert (equal form '(ccl::def-ccl-pointers ccl::reset-winners () (clrhash ccl::*stack-access-winners*))))
  (assert (= (length matches) 1))
  (with-open-file (s (concatenate 'string out "native-source.lisp") :direction :output :if-exists :error)(print form s))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
   (write-char #\[ s)
   (loop for count in '(0 1 3 4 7 8 31 64 255 256) for ci from 0 do
    (unless (zerop ci)(write-char #\, s))
    (let* ((ccl::*stack-access-winners* (make-hash-table :test 'eq))
           (table ccl::*stack-access-winners*) (keys (loop repeat count collect (cons 7 nil))))
     (loop for k in keys for j from 0 do (setf (gethash k table) (cons j k)))
     (loop for k in keys for j from 0 when (oddp j) do(remhash k table))
     (let ((returned (multiple-value-list (funcall (first matches)))))
      (assert (and (= (length returned) 1)(eq (first returned) table)(eq table ccl::*stack-access-winners*)))
      (assert (zerop (hash-table-count table)))
      (dolist (k keys)(assert (null (nth-value 1 (gethash k table))))))
     ;; Run every generated calling form against a native CLR leaf too.
     (format s "{\"initial\":~d,\"count\":0,\"same\":true,\"forms\":[" count)
     (loop for row in cases unless (equal (first row) "clear_receiver") do
      (unless (equal (first row) "reset_winners")(write-char #\, s))
      (setf (gethash 'probe table) 91)
      (let* ((done (cons 0 nil)) (name (first row))
             (op (lambda (h k v)(declare(ignore k v))(assert(eq h table))(funcall (first matches))))
             (receiver (compile nil (second (assoc "clear_receiver" cases :test #'equal))))
             (function (compile nil (second row)))
             (result (multiple-value-list (apply function (if (member name '("clear_direct" "clear_indirect") :test #'equal) (list op receiver table done) (list op table done))))))
       (assert (eq (first result) table))(assert (every #'null (rest result)))(assert (zerop (hash-table-count table)))
       (format s "{\"name\":~s,\"count\":~d,\"done\":~d,\"same\":true,\"second_nil\":true}" name (length result) (car done))))
     (write-string "]}" s)))
   (write-char #\] s)))
 (dolist (row cases)
  (let ((m (compile-call-form (second row)(first row)(mapcar #'first cases))))
   (assert(null(getf m :children)))(push m modules)
   (with-open-file (s (concatenate 'string out (first row) ".wat") :direction :output :if-exists :error)(write-string (getf m :wat) s))))
 (setq modules(nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (write-char #\[ s)(loop for m in modules for i from 0 do(unless(zerop i)(write-char #\, s))(format s "{\"name\":~s}"(getf m :name)))(write-char #\] s))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error)(write-pool-graph s(mapcar(lambda(m)(getf m :pool)) modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
