(in-package :ccl)
;; Selected scaffold only. Admission runs before normalization can rename data.
(defun admit-population-consumer (form)
 (labels ((api (x) (member x '(population-contents population-data population-type)))
          (variable (x) (when (api x) (error "population API variable unsupported")))
          (has-api (x) (if (atom x) (api x) (unless (eq (car x) 'quote) (some #'has-api x))))
          (body (forms) (mapc #'walk forms))
          (parameters (xs)
           (dolist (x xs)
            (if (atom x) (variable x)
             (progn (variable (if (consp (car x)) (second (car x)) (car x)))
                    (when (cdr x) (walk (second x))) (when (cddr x) (variable (third x)))))))
          (walk (x)
           (cond ((atom x) (variable x)) ((eq (car x) 'quote) nil)
            ((member (car x) '(macrolet symbol-macrolet)) (error "population local macro unsupported"))
            ((eq (car x) 'lambda) (parameters (second x)) (body (cddr x)))
            ((member (car x) '(let let*))
             (dolist (b (second x)) (variable (if (atom b) b (car b))) (when (consp b) (walk (second b))))
             (body (cddr x)))
            ((member (car x) '(flet labels))
             (dolist (d (second x))
              (when (api (car d)) (error "population API shadow unsupported"))
              (parameters (second d)) (body (cddr d)))
             (body (cddr x)))
            ((eq (car x) 'multiple-value-bind) (mapc #'variable (second x)) (body (cddr x)))
            ((and (eq (car x) 'setf) (> (length x) 3)
                  (loop for (place value) on (cdr x) by #'cddr thereis (has-api place)))
             (error "multi-place population SETF unsupported"))
            ((and (member (car x) '(pushnew pop)) (has-api (cdr x))) (error "population PUSHNEW/POP unsupported"))
            ((and (eq (car x) 'funcall) (consp (second x))
                  (eq (car (second x)) 'function) (consp (second (second x)))
                  (eq (car (second (second x))) 'setf) (api (second (second (second x)))))
             (unless (= (length x) 4) (error "population setter arity unsupported")) (body (cddr x)))
            ((eq (car x) 'function)
             (cond ((and (consp (second x)) (eq (car (second x)) 'setf) (api (second (second x))))
                    (error "population setter reference unsupported"))
                   ((and (consp (second x)) (eq (car (second x)) 'lambda)) (walk (second x)))))
            (t (body (cdr x))))))
  (walk form)) form)
