(in-package :ccl)
(load (getenv "POP_CASES"))
(load (getenv "POP_OLD"))
(defparameter *old-pop-lower* #'lower-population-consumer)
(load (getenv "POP_NEW"))
(defun pop-alpha (x)
 (let ((seen (make-hash-table :test 'eq)) (next 0))
  (labels ((walk (x) (cond ((consp x) (cons (walk (car x)) (walk (cdr x))))
                         ((and (symbolp x) x (null (symbol-package x)))
                          (or (gethash x seen) (setf (gethash x seen) (list :gensym (incf next)))))
                         (t x)))) (walk x))))
(with-open-file (s (getenv "POP_REPORT") :direction :output :if-exists :error)
 (format s "{\"positive\":[")
 (loop for row in *population-consumer-cases* for i from 0 do
  (assert (equal (pop-alpha (funcall *old-pop-lower* (second row))) (pop-alpha (lower-population-consumer (second row)))))
  (unless (zerop i) (format s ",")) (format s "~s" (first row)))
 (format s "],\"refusals\":[")
 (loop for (name form why) in
  '(("flet" (lambda (p) (flet ((population-contents (x) x)) (population-contents p))) "population API shadow unsupported")
    ("labels" (lambda (p) (labels ((population-data (x) x)) (population-data p))) "population API shadow unsupported")
    ("setf-first" (lambda (p cell) (setf (population-data p) cell (cdr cell) nil)) "multi-place population SETF unsupported")
    ("setf-second" (lambda (p cell) (setf (cdr cell) (population-data p) (population-data p) cell)) "multi-place population SETF unsupported")
    ("macrolet" (lambda (p) (macrolet ((population-data (x) x)) (population-data p))) "population local macro unsupported")
    ("symbol-macrolet" (lambda (p) (symbol-macrolet ((population-data p)) population-data)) "population local macro unsupported")
    ("parameter" (lambda (population-data) population-data) "population API variable unsupported")
    ("let-variable" (lambda (p) (let ((population-data p)) population-data)) "population API variable unsupported")
    ("supplied-variable" (lambda (&optional (p nil population-data)) p) "population API variable unsupported")
    ("setter-reference" (lambda () #'(setf population-contents)) "population setter reference unsupported")
    ("setter-arity" (lambda (p) (funcall #'(setf population-contents) p)) "population setter arity unsupported")
    ("pushnew" (lambda (p gf) (pushnew gf (population-data p))) "population PUSHNEW/POP unsupported")
    ("pop" (lambda (p) (pop (population-data p))) "population PUSHNEW/POP unsupported"))
  for i from 0 do
   (let ((condition (handler-case (progn (lower-population-consumer form) nil) (error (e) e))))
    (assert (and condition (search why (princ-to-string condition))) () "admission ~a" name))
   (unless (zerop i) (format s ",")) (format s "~s" name))
 (format s "]}"))
(quit)
