(in-package :wasm32-compiler)

(defun core-inputs (name)
  (let ((s (symbol-name name)))
    (cond
      ((member s '("BOUNDP" "%SYM-VALUE" "%SYM-GLOBAL-VALUE") :test #'equal)
       (values '((nil) (t) (:execution-value)) t))
      ((member s '("LOCKP" "RECURSIVE-LOCK-P" "READ-WRITE-LOCK-P" "NATIVE-CLASS-P") :test #'equal)
       (values '((nil) (t) (7) ((1 . 2)) (#(1 2)) ("ordinary")) t))
      ((equal s "FROZEN-DEFINITION-P") (values '((7) ((1 . 2)) (execution-unfrozen-symbol)) t))
      ((equal s "CONSTANT-SYMBOL-P") (values '((7) ((1 . 2)) (execution-unfrozen-symbol)) t))
      ((equal s "GETF-TEST")
       (values (list (list nil :a #'eq) (list '(:a 1 :b 2) :b #'eq)
                     (list '(:a 1) :missing #'eq 99) (list '(1/3 :found) 1/3 #'eql)) t))
      ((equal s "RASSOC")
       (values (list (list 2 '(nil (1 . 2) (3 . 4)))
                     (list 9 '((1 . 2))) (list 1/3 '((:a . 1/3)))
                     (list 2 '((1 . 2) (3 . 4)) :test #'eq)) t))
      ((member s '("ANY/TYPE" "EVERY/TYPE") :test #'equal)
       (values (list (list #'eql 2 nil) (list #'eql 2 '(1 2 3))
                     (list #'eql 2 '(2 2)) (list #'eql 9 '(1 2))) t))
      ((equal s "MOVE-STRING-BYTES")
       (values '(("" "" 0 0 0) ("abc" "....." 0 1 3)
                 ("xλ😁y" "...." 1 0 2) ("abc" "XYZ" 2 2 1)) t))
      ((member s '("%SHORT-FLOAT-ZEROP" "%DOUBLE-FLOAT-ZEROP") :test #'equal)
       (values (mapcar (lambda (x) (list (coerce x (if (equal s "%SHORT-FLOAT-ZEROP") 'single-float 'double-float)))) '(0 -0.0d0 1 -1 1/2)) t))
      ((equal s "LIST-LENGTH") (values '((nil) ((1)) ((1 2)) ((1 2 3)) ((1 2 3 4 5 6))) t))
      ((equal s "BYTE-MASK") (values '((0) (1) (7) (29) (30) (64) (127)) t))
      ((equal s "%SIMPLE-STRING=")
       (values '(("" "" 0 0 0 0) ("abc" "xabcx" 0 1 3 4) ("abc" "abd" 0 0 3 3) ("λ😁" "λ😁" 0 0 2 2) ("abc" "ab" 0 0 3 2)) t))
      ((member s '("UTF-8-OCTETS-IN-STRING" "UTF-16-OCTETS-IN-STRING") :test #'equal)
       (values '(("" 0 0) ("abc" 0 3) ("λ😁" 0 2) ("abc" 2 1) ("xλ😁y" 1 3)) t))
      ((equal s "CLONE-TYPE-CLASS-METHODS")
       (values '((#(nil nil) #(1 2)) (#(nil nil :a (1 . 2)) #(0 0 0 0))) t))
      ((equal s "CMP-ARGS-OLD-ARGS") (values '((nil nil 0) ((1 2) (1 2) 2) ((1 3) (1 2) 2) ((1 3) (1 2) 1)) t))
      ((equal s "FIND-STR-PATTERN") (values '(("ab" "xxabyy" 0 0 2 6) ("ab" "aa" 0 0 2 2) ("λ😁" "xλ😁" 0 0 2 3)) t))
      ((equal s "FUNCALL") (values (list (list #'identity 7) (list #'car '(1 2)) (list #'list 1 2)) t))
      ((equal s "APPLY") (values (list (list #'identity '(7)) (list #'list 1 '(2)) (list #'list 1 2 '(3 4))) t))
      ((equal s "CORE-EQL") (values '((1 1) (1 2) (nil nil) (nil (nil)) (1.5s0 1.5d0) (1.5d0 1.5d0) (1/3 1/3) (1152921504606846976 1152921504606846976)) t))
      ((equal s "UNION-EQL") (values '((nil nil) ((1 2) (2 3)) ((1.5d0 1152921504606846976) (1.5d0 7))) t))
      ((equal s "EQUAL-BUT-NO-CAR-RECURSION") (values '((nil nil) ((1 2) (1 2)) ((1 2) (1 3)) (1 2) ((1) nil)) t))
      ((equal s "CPL-INDEX") (values '((1 nil) (1 (1 2)) (2 (1 2 3)) (9 (1 2))) t))
      ((equal s "NEGATE-HI-LO") (values '((0 0) (1 0) (0 1) (7 12)) t))
      ((equal s "FLATTEN-METHOD-LAMBDA-LIST") (values '((nil) ((x (y integer) &optional (z 3))) ((x &aux (z 4)))) t))
      ((equal s "CANONICAL-COMPLEX") (values '((7 0) (1 2) (1/3 2/3)) t))
      ((equal s "ENCODE-FILE-RANGE") (values '((0 0) (1 20) (100 20000) (100000 100100)) t))
      ((equal s "%QUO-1") (values '((1.0d0) (2.0d0) (-4.0s0)) t))
      ((member s '("%SHORT-FLOAT-PLUSP" "%DOUBLE-FLOAT-PLUSP") :test #'equal)
       (values (mapcar (lambda (x) (list (coerce x (if (equal s "%SHORT-FLOAT-PLUSP") 'single-float 'double-float)))) '(-1 0 1)) t))
      ((equal s "%NEXT-METHOD-P") (values '(((nil nil)) ((nil (1))) ((nil (1 2)))) t))
      ((equal s "%STD-DEVICE-COMPONENT") (values '((nil nil) (:unspecific nil) ("disk" nil) ("disk" :unspecific) ("disk" "host")) t))
      ((equal s "SOURCE-NOTE-FILENAME") (values '((nil) ("test.lisp")) t))
      ((equal s "%REAL-PRINT-STREAM") (values '((:explicit-stream)) t))
      ((equal s "POINTERP") (values '((nil) (7) ((1 . 2))) t))
      ((member s '("MEMBER-TEST" "MEMBER-TEST-NOT") :test #'equal)
       (values (list (list 1 nil #'eql) (list 2 '(1 2 3) #'eql) (list 2 '(1 2 3) #'eq)) t))
      ((member s '("ASSOC-TEST" "ASSOC-TEST-NOT") :test #'equal)
       (values (list (list 1 nil #'eql) (list 2 '(nil (1 . 2) (2 . 3)) #'eql)) t))
      ((member s '("1+" "1-") :test #'equal)
       (values '((0) (1) (-1) (536870911) (-536870912) (1152921504606846976) (1.5s0) (-2.5d0)) t))
      ((equal s "CORE-BYTE-STORE")
       (values (loop for (i v) in '((3 2) (0 255) (1 0) (2 128))
                     collect (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9) i v)) t))
      ((equal s "CORE-POSITIVE-LOOP") (values '((0) (1) (3) (7)) t))
      ((equal s "CORE-IZEROP") (values '((0) (1) (-1) (-536870912) (536870911)) t))
      ((equal s "CORE-NUMERIC-IR") (values '((1.5d0 2.0d0) (-1.5s0 2.0s0) (2.0d0 2.0d0)) t))
      ((equal s "CORE-ZERO") (values '((0) (1) (-1) (0.0s0) (-0.0d0) (1.5d0) (1152921504606846976)) t))
      ((equal s "CORE-BYTE-ORDER") (values (list (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9))) t))
      ((member s '("CORE-COMPUTED-CALL" "CORE-COMPUTED-INNER" "CORE-COMPUTED-APPLY" "CORE-COMPUTED-INNER-APPLY") :test #'equal) (values (list (list #'identity 7) (list #'car '(1 2))) t))
      ((equal s "SYMBOL-NAME") (values '((nil) (t) (:library-test) (library-test-symbol)) t))
      ((equal s "SYMBOL-PLIST") (values '((library-test-symbol)) t))
      ((equal s "GET") (values '((library-test-symbol :absent) (library-test-symbol :absent 7)) t))
      ((equal s "PUT") (values '((library-put-symbol :key (1 . 2))) t))
      ((member s '("NEED-CHAR-CODE" "UTF-16-CHARACTER-SIZE-IN-OCTETS") :test #'equal)
       (values '((#\Null) (#\A) (#\u+1000) (#\u+1f601)) t))
      ((equal s "REQUIRE-NUMARG") (values '((#\A 1) (#\B 0)) t))
      ((equal s "REQUIRE-NO-NUMARG") (values '((#\A nil)) t))
      ((equal s "CORE-ILOGNOT") (values '((0) (-1) (7) (-536870912) (536870911)) t))
      ((equal s "CORE-FIXNUM-LESS") (values '((-1 0) (0 -1) (1 1) (-536870912 536870911)) t))
      ((equal s "%COPY-U8-TO-STRING")
       (values (loop for (src dst n) in '((0 0 4) (0 4 0) (1 0 3) (0 1 3) (3 3 1) (4 4 0))
                     collect (list (make-array 4 :element-type '(unsigned-byte 8)
                                                 :initial-contents '(0 65 128 255))
                                   src (copy-seq "....") dst n)) t))
      ((equal s "%COPY-STRING-TO-U8")
       (values (loop for (src dst n) in '((0 1 3) (0 0 0) (1 0 2) (2 3 1) (3 4 0) (0 0 3))
                     collect (list "Aλ😁" src
                                   (make-array 4 :element-type '(unsigned-byte 8) :initial-element 99)
                                   dst n)) t))
      ((member s '("CORE-FORMAT-ERROR" "CORE-FORMAT-SIGNAL" "CORE-FORMAT-COLLECT" "CORE-TYPE-ERROR" "CORE-FORMAT-ORDER" "CORE-FORMAT-DECLINE" "CORE-SIMPLE-INITARGS") :test #'equal)
       (values '((nil) ((1 . 2)) (7) ("string")) t))
      ((equal s "CORE-DYNAMIC-FORMAT") (values '(("one ~s" (1 . 2)) ("two ~a" 7)) t))
      ((equal s "CORE-SCHAR") (values '(("abc" 0) ("abc" 2) ("λ😁" 1)) t))
      ((equal s "CORE-SET-CHAR") (values '(("abc" 0 #\Z) ("λ😁" 1 #\A)) t))
      ((equal s "CORE-CHAR-CODE") (values '((#\Null) (#\A) (#\u+1000) (#\u+1f601)) t))
      ((equal s "CORE-CODE-CHAR") (values '((0) (65) (55295) (55296) (57343) (57344) (128513) (1114111)) t))
      ((member s '("CORE-GVECTOR" "CORE-STRUCT" "CORE-SLOT" "CORE-CLEANUP" "CORE-TRANSFER") :test #'equal)
       (values '(((1 . 2)) ((3 4))) t))
      ((equal s "CORE-REF") (values '((#((1 . 2) (3 . 4)))) t))
      ((equal s "CORE-SET") (values '((#((1 . 2) 7) (3 . 4))) t))
      ((member s '("FUNCTIONP" "LFUNP") :test #'equal)
       (values (list (list nil) (list 7) (list #'car) (list '(1 2))) t))
      ;; Symbols have a dedicated tag on x86-64, but are node vectors on D1.
      ;; Compare representation predicates only on their shared domain here.
      ((member s '("GVECTORP" "MISCOBJP" "UVECTORP" "IVECTORP") :test #'equal)
       (values '((nil) (0) (-1) ((1 . 2)) (#\A) ("abc") (#(1 2)) (#*101)) t))
      ((member s '("SYMBOLP" "SYMBOL-ARG-P" "NON-NIL-SYMBOL-P" "NON-NIL-SYMBOLP"
                   "CONSP" "LISTP" "ARRAYP" "VECTORP" "SEQUENCEP" "ATOM"
                   "FIXNUMP" "BIGNUMP" "INTEGERP" "RATIOP" "RATIONALP" "REALP" "NUMBERP"
                   "SHORT-FLOAT-P" "DOUBLE-FLOAT-P" "FLOATP" "COMPLEXP"
                   "COMPLEX-SINGLE-FLOAT-P" "COMPLEX-DOUBLE-FLOAT-P"
                   "SIMPLE-BASE-STRING-P" "SIMPLE-STRING-P" "SIMPLE-VECTOR-P" "SIMPLE-BIT-VECTOR-P"
                   "CHARACTERP" "BASE-CHAR-P" "EXTENDED-CHAR-P" "PACKAGEP" "STRUCTUREP"
                   "ISTRUCTP" "ISTRUCT-TYPE-NAME" "BASIC-STREAM-P" "STANDARD-INSTANCE-P"
                   "MACPTRP" "DEAD-MACPTR-P" "GVECTORP" "IVECTORP" "MISCOBJP" "UVECTORP"
                   "FUNCTIONP" "LFUNP" "BITP" "UNSIGNED-BYTE-P"
                   "UNSIGNED-BYTE-8-P" "SIGNED-BYTE-8-P" "UNSIGNED-BYTE-16-P" "SIGNED-BYTE-16-P"
                   "UNSIGNED-BYTE-32-P" "SIGNED-BYTE-32-P" "QUOTED-FORM-P" "LAMBDA-EXPRESSION-P")
               :test #'equal)
       (values (mapcar (lambda (x) (if (equal s "SYMBOL-ARG-P") (list x t) (list x)))
                       '(nil t 0 1 -1 127 128 255 256 32767 65536 -536870912 536870911
                         1208925819614629174706176 -1208925819614629174706176
                         1/3 -5/7 #c(1/3 2/3) 0.0s0 -1.5s0 0.0d0 3.25d0 :test (1 . 2) (1 2 3) #\A #\u+1000 "abc" #(1 2) #*101)) t))
      ((member s '("%REQUIRE-TYPE-BUILTIN" "%REQUIRE-TYPE-CLASS-CELL" "STRUCTURE-TYPEP" "ISTRUCT-TYPEP") :test #'equal)
       (values '((nil nil) (7 :type) (:test :type) ((1 2) :type)) t))
      ((member s '("EQ" "MAX-2" "MIN-2" "%IMAX" "%IMIN" "/=-2" ">=-2" "<=-2") :test #'equal)
       (values (append '((1 1) (-7 3) (9 4) (0 -1))
                       (unless (member s '("EQ" "%IMAX" "%IMIN") :test #'equal)
                         '((1.5d0 2.5d0) (-3.0s0 1) (1208925819614629174706176 7)))) t))
      ((member s '("CAR" "CDR" "CAAR" "CADR" "CDAR" "CDDR" "CAAAR" "CAADR" "CADAR" "CADDR" "CDAAR" "CDADR" "CDDAR" "CDDDR") :test #'equal)
       (values '((nil) ((((1 . 2) . (3 . 4)) . ((5 . 6) . (7 . 8))))) t))
      ((member s '("COPY-TREE" "IDENTITY") :test #'equal)
       (values '((nil) (7) ((1 (2 . 3) 4))) t))
      ((member s '("MEMQ" "ADJOIN-EQ" "CPL-MEMQ") :test #'equal)
       (values '((1 nil) (1 (1 2)) (2 (1 2 3)) (4 (1 2))) t))
      ((member s '("MEMEQL" "ADJOIN-EQL") :test #'equal)
       (values '((1 nil) (2 (1 2 3)) (1/3 (2/3 1/3)) (#\A (#\B #\A))
                 (1152921504606846976 (1 1152921504606846976))) t))
      ((equal s "%PL-SEARCH") (values '(((1 2 3 4) 1) ((1 2 3 4) 3) ((1 2) 7) (nil 1)) t))
      ((member s '("APPEND-2" "UNION-EQ" "NRECONC") :test #'equal)
       (values '((nil nil) ((1 2) nil) (nil (3 4)) ((1 2) (3 4))) t))
      ((equal s "APPEND") (values '(nil ((1 2)) ((1 2) (3 4) (5 6))) t))
      ((equal s "LIST") (values '(nil (1) (1 2 3)) t))
      ((equal s "LIST*") (values '((nil) (1 2) (1 2 (3 4))) t))
      ((member s '("LIST-REVERSE" "LIST-NREVERSE" "FINAL-CONS") :test #'equal)
       (values '((nil) ((1)) ((1 2 3))) t))
      ((equal s "NREMOVE") (values '((1 (1 2 1 3)) (7 (1 2 3))) t))
      ((equal s "REMOVE-FROM-ALIST") (values '((1 ((1 . 2) (3 . 4))) (7 ((1 . 2)))) t))
      ((equal s "HEAP-AREA-NAME") (values (loop for n from 0 to 12 collect (list n)) t))
      ((equal s "FIND-BUILTIN-CELL") (values '((integer) (:absent) (nil t)) t))
      ((equal s "INDEX->VECTOR-INDEX") (values '((0) (1) (7)) t))
      ((member s '("%SIMPLE-FASL-INIT-BUFFER" "CHARACTER-ENCODED-IN-SINGLE-OCTET"
                   "TWO-OCTETS-PER-CHARACTER" "FOUR-OCTETS-PER-CHARACTER") :test #'equal)
       (values '((nil) (#\A) (#\u+1000)) t))
      ((member s '("8-BIT-FIXED-WIDTH-OCTETS-IN-STRING" "UCS-2-OCTETS-IN-STRING" "UCS-4-OCTETS-IN-STRING"
                   "8-BIT-FIXED-WIDTH-LENGTH-OF-VECTOR-ENCODING" "8-BIT-FIXED-WIDTH-LENGTH-OF-MEMORY-ENCODING") :test #'equal)
       (values '((nil 1 8) (nil 7 3) (nil 3 3)) t))
      ((member s '("DEF-INFO.LFBITS" "DEF-INFO.KEYVECT" "DEF-INFO.FILE" "DEF-INFO.METHODS" "DEF-INFO.MACRO-P"
                   "DEF-INFO.FUNCTION-P" "DEF-INFO.DEFTYPE" "DEF-INFO.DEFTYPE-TYPE") :test #'equal)
       (values '((nil) (#(12 :key :file (:methods 1 2))) (#((12 . :source) :key :file (ccl::macro)))) t))
      ((equal s "DEF-INFO-METHOD.KEYVECT") (values '(((((:a :b) . :file))) (((7 . :file)))) t))
      ((equal s "DEF-INFO-METHOD.FILE") (values '((((7 . :file))) (((nil . :other)))) t))
      ((equal s "BOOTSTRAPPING-RECORD-SOURCE-FILE") (values '((nil) (7 nil)) t))
      ((equal s "SLOT-ID-LOOKUP-NO-SLOTS") (values '((nil nil) (7 :test)) t))
      ((equal s "%TYPE-ERROR-TYPE") (values '((:test) ((integer 0 7))) t))
      ((equal s "%MAKE-RATIO") (values '((1 3) (-5 7)) t))
      ((equal s "%MAKE-COMPLEX") (values '((1 3) (-5 7)) t))
      ((member s '("DEFAULT-PRINT-LEVEL" "DEFAULT-PRINT-LENGTH" "DEFAULT-PRINT-STRING-LENGTH") :test #'equal)
       (values '((:default) (nil) (7)) t))
      ((member s '("LOADING-FILE-SOURCE-FILE"
                   "PRELOAD-ALL-FUNCTIONS" "LISP-IMPLEMENTATION-TYPE") :test #'equal)
       (values '(nil) t))
      (t (values nil nil)))))
