(in-package :wasm32-compiler)

(defun input-structure (object)
  (setf (gethash object *witness-nodes*)
        (cons 'struct (cons (list (type-of object))
                           (loop for i from 1 below (ccl::uvsize object)
                                 collect (ccl::%svref object i)))))
  object)

(defun input-ioblock (shift sharing)
  (input-structure (ccl::make-ioblock :element-shift shift :sharing sharing)))


(defvar *input-fixnum-vectors* (make-hash-table :test #'eq))
(defun input-fixnum-vector (values)
  (let ((v (make-array (length values) :element-type '(signed-byte 30) :initial-contents values)))
    (setf (gethash v *input-fixnum-vectors*) t)
    v))

(defun input-sparse-vector (&optional (default 7))
  (let ((vector (ccl::make-sparse-vector #x110000 t default)))
    (setf (ccl::sparse-vector-ref vector 0) 9
          (ccl::sparse-vector-ref vector 32) ccl::$cht_wsp
          (ccl::sparse-vector-ref vector 257) 11
          (ccl::sparse-vector-lock vector) nil)
    (input-structure vector)))

(defun input-readtable ()
  (witness-istruct 'readtable
    (list (input-sparse-vector ccl::$cht_cnst)
          (input-structure (ccl::%make-sparse-vector :size #x110000 :element-type t
                                                    :default nil :table #(nil) :lock nil))
          :upcase)))

(defun recipe-stream (&optional info)
  (witness-node 'basic-stream (list nil 0 nil info)))

(defun recipe-array (dimensions)
  (let* ((array (make-array dimensions :initial-element 7 :adjustable t))
         (fields (loop for i below (ccl::uvsize array) collect (ccl::%svref array i))))
    (setf (gethash array *witness-nodes*) (cons 'arrayh fields))
    array))

(defun recipe-output (text index)
  (input-structure
    (ccl::make-string-output-stream-ioblock
      :stream (recipe-stream) :string (copy-seq text) :index index :charpos 3)))

(defun recipe-hash (count deleted)
  (let ((hash (make-hash-table :test #'eq :size 32)))
    (dotimes (i (+ count deleted)) (setf (gethash i hash) (+ i 17)))
    (dotimes (i deleted) (remhash (+ count i) hash))
    (let* ((v (ccl::nhash.vector hash))
           (fields (loop for i below (ccl::uvsize v) collect (ccl::%svref v i))))
      (assert (= (ccl::nhash.vector.count v) count))
      ;; The exclusive and lock-free representations interpret the deleted
      ;; count alike for these readers. Bind each threshold independently.
      (setf (nth 0 fields) 0 (nth 1 fields) 0 (nth 2 fields) 0
            (nth 6 fields) nil (nth 7 fields) deleted (nth 8 fields) count)
      (let ((wrapper (make-list 15)))
        (setf (nth 1 wrapper) 0
              (nth 3 wrapper) (witness-node 'hash-vector fields))
        (witness-istruct 'hash-table wrapper)))))

(defun more-inputs (name)
  (let ((s (symbol-name name)))
    (cond
      ((equal s "TOPLEVEL") (values '(()) t))
      ((equal s "UNDEFINE-CONSTANT")
       (values (loop for value in '(nil 7 (1 . 2)) collect
                     (list (make-symbol "RECIPE-UNBIND") value)) t))
      ((equal s "MAKE-NUMERIC-CTYPE-PREDICATE")
       (values (loop for (class low high) in '((integer -3 7) (integer 0 0)
                                              (integer nil 7) (float 0 7))
                     collect (list (witness-istruct 'ccl::numeric-ctype
                                     (list nil nil class nil nil low high nil))
                                   '(-4 -3 -1 0 1 7 8 nil 0.0d0 1152921504606846976))) t))
      ((member s '("%ARRAY-HEADER-SUBTYPE" "%SET-SIMPLE-ARRAY-P") :test #'equal)
       (values (list (list (witness-array 0)) (list (witness-array 4))) t))
      ((equal s "%ARRAY-INDEX")
       (values (loop for indices in '((0 0) (0 2) (1 0) (1 2) (2 0) (-1 0) (0 nil))
                     collect (cons (recipe-array '(2 3)) indices)) t))
      ((equal s "ARRAY-ELEMENT-SUBTYPE")
       (values (list (list (witness-array) #(7)) (list #(1 2) #(3))
                     (list "abc" "") (list #*101 #*0)) t))
      ((equal s "ARRAY-DATA-OFFSET-SUBTYPE")
       (values (list (list (witness-array)) (list #(1 2)) (list "aλz") (list #*101)) t))
      ((equal s "%FILE-KIND")
       (values '((nil) (0) (16384) (16877) (32768) (33188) (4096)
                 (40960) (49152) (8192) (24576)) t))
      ((equal s "NEED-USE-EQL")
       ;; Single floats and host-only fixnums differ in representation. These
       ;; rows use the shared identity/equality domain and real boxed numbers.
       (values (mapcar #'list '(nil t 0 7 -7 536870911 -536870912
                                1208925819614629174706176 1/3 #c(1/3 2/3)
                                0.0d0 -2.5d0 #\a (1 . 2) "text")) t))
      ((equal s "INVALID-HASH-KEY-P")
       (values (mapcar #'list (list (ccl::%unbound-marker) (ccl::%slot-unbound-marker)
                                    nil 0 7 '(1 . 2))) t))
      ((equal s "FIND-GF-DISPATCH-TABLE-INDEX")
       (values (loop for hashes in '(nil (1) (1 2) (1 2 3) (1 2 3 4) (0 2)) collect
                     (let* ((dt (make-array (+ ccl::%gf-dispatch-table-first-data 10)
                                            :initial-element nil))
                            (new (witness-istruct 'ccl::class-wrapper (cons 1 (make-list 11)))))
                       (setf (ccl::%gf-dispatch-table-mask dt) 3
                             (svref dt (+ ccl::%gf-dispatch-table-first-data 8)) (ccl::%unbound-marker))
                       (loop for hash in hashes for i from 0 do
                         (setf (ccl::%gf-dispatch-table-ref dt (* i 2))
                               (witness-istruct 'ccl::class-wrapper (cons hash (make-list 11)))
                               (ccl::%gf-dispatch-table-ref dt (1+ (* i 2))) :method))
                       (list dt new))) t))
      ((equal s "CLEAR-GF-DISPATCH-TABLE")
       (values (loop for n in '(0 2 4 8) collect
                     (list (make-array (+ ccl::%gf-dispatch-table-first-data n 2)
                                       :initial-element :occupied))) t))
      ((member s '("LOCK-FREE-HASH-TABLE-COUNT" "%GROW-HASH-TABLE-IN-PLACE-P") :test #'equal)
       (values (loop for (count deleted) in '((0 0) (1 0) (1 1) (4 2) (4 3) (7 3) (7 4))
                     collect (list (recipe-hash count deleted))) t))
      ((equal s "CYGPATH")
       (values '(("") ("relative/path") ("/tmp/λ") ("C:\\a\\b")) t))
      ((equal s "THREAD-PRESET")
       (values (loop for args in '(nil (1) ((2 . 3) "arg")) collect
                     (list* (witness-istruct 'ccl::lisp-thread (make-list 11))
                            #'identity args)) t))
      ((equal s "%PROGVRESTORE")
       (values '((nil) (((ccl::recipe-a . 7)))
                 (((ccl::recipe-a . (1 . 2)) (ccl::recipe-b . nil)))
                 (((ccl::recipe-a . 7) (ccl::recipe-a . 9)))) t))
      ((equal s "TRUNCATING-STRING-OUTPUT-STREAM-TRUNCATED-P")
       (values (loop for info in '(nil (:truncated nil) (:truncated t) (:x 7 :truncated t))
                     collect (list (recipe-stream info))) t))
      ((equal s "TRUNCATING-STRING-OUTPUT-STREAM-IOBLOCK-WRITE-CHAR")
       (values (loop for (text index char) in '(("...." 0 #\a) ("...." 2 #\Newline)
                                               ("...." 3 #\λ) ("...." 4 #\z) ("" 0 #\a))
                     collect (list (recipe-output text index) char)) t))
      ((equal s "TRUNCATING-STRING-OUTPUT-STREAM-IOBLOCK-WRITE-SIMPLE-STRING")
       (values (loop for (text index source start count) in
                     '(("...." 0 "abc" 0 3) ("...." 3 "λz" 0 2)
                       ("...." 0 "x\ny" 1 1) ("...." 4 "z" 0 1) ("" 0 "" 0 0))
                     collect (list (recipe-output text index) source start count)) t))
      ((equal s "STRING-INPUT-STREAM-CHARACTER-READ-VECTOR")
       (values (loop for (text index limit start end) in
                     '(("aλz" 0 3 0 3) ("aλz" 1 2 1 4) ("aλz" 3 3 0 3)
                       ("" 0 0 0 0) ("abc" 0 3 1 1))
                     collect (list (input-structure
                                    (ccl::make-string-input-stream-ioblock
                                      :string text :index index :end limit))
                                   (make-string 4 :initial-element #\.) start end)) t))
      ((member s '("CORE-WORD-AND-MASK" "CORE-WORD-XOR-MASK" "CORE-WORD-OR-MASK") :test #'equal)
       (values '((0) (1) (65535) (65536) (536870911) (536870912)
                 (2147483647) (2147483648) (4294967295)) t))
      ((equal s "CORE-MINUS1")
       (values '((0) (1) (-1) (536870911) (-536870912) (1152921504606846976)
                 (0.0d0) (-0.0d0) (1.5d0) (-2.5s0)) t))
      ((member s '("%DOUBLE-FLOAT-SIN!" "%DOUBLE-FLOAT-TAN!" "%DOUBLE-FLOAT-ASIN!"
                  "%DOUBLE-FLOAT-ATAN!" "%DOUBLE-FLOAT-SINH!" "%DOUBLE-FLOAT-TANH!"
                  "%DOUBLE-FLOAT-COS!" "%DOUBLE-FLOAT-COSH!" "%DOUBLE-FLOAT-EXP!") :test #'equal)
       (values (list (list 0.0d0 (ccl::%double-float 17))
                     (list -0.0d0 (ccl::%double-float 19))) t))
      ((member s '("%DOUBLE-FLOAT-LOG!" "%DOUBLE-FLOAT-ACOS!") :test #'equal)
       (values (list (list 1.0d0 (ccl::%double-float 17))) t))
      ((equal s "%DOUBLE-FLOAT-ATAN2!")
       (values (list (list 0.0d0 1.0d0 (ccl::%double-float 17))
                     (list -0.0d0 1.0d0 (ccl::%double-float 19))) t))
      ((equal s "%DOUBLE-FLOAT-EXPT!")
       (values (loop for (x y) in '((2.0d0 3.0d0) (2.0d0 -2.0d0) (-2.0d0 3.0d0) (2.0d0 0.0d0))
                     collect (list x y (ccl::%double-float 17))) t))
      ((member s '("CORE-SHIFT-LEFT-DOMAIN" "CORE-SHIFT-RIGHT-DOMAIN" "CORE-SHIFT-SIGNED-DOMAIN") :test #'equal)
       (values (loop for n in '(0 1 2 7 15 28 29 30 31) append
                     (loop for x in '(-536870912 -4 -1 0 1 7 536870911) collect (list n x))) t))

      ((equal s "INTEGER-DECODE-DENORM-SHORT-FLOAT")
       (values (loop for m in '(1 2 3 65535 4194304 8388607) append
                     (list (list m 1) (list m -1))) t))
      ((equal s "PV-MAP-LOOKUP")
       (let ((map (input-structure
                   (ccl::make-pv-map :keys (input-fixnum-vector '(1 7 256))
                                     :values (input-fixnum-vector '(11 17 1256))))))
         (values (loop for code in '(0 1 6 7 8 256 257) collect (list code map)) t)))
      ((equal s "PATH-STR-MATCH-P")
       (values '(("" "" 0 0 0 0) ("abc" "abc" 0 0 3 3)
                 ("abc" "ABC" 0 0 3 3) ("abc" "abd" 0 0 3 3)
                 ("abc" "ab" 0 0 3 2) ("ab" "abc" 0 0 2 3)) t))
      ((equal s "ADD-ACCESSOR-TYPES")
       (values '((nil nil) ((:a) (x y)) ((:a :b) #(first second))
                 ((:a :b :a) (one two three))) t))
      ((equal s "CONS-PATHNAME")
       (values '(((:absolute "tmp") "a" "lisp" :unspecific nil nil)
                 ((:relative) "b" nil :unspecific :newest nil)
                 ((:absolute "src") "C" "LISP" "CCL" :newest nil)) t))
      ((equal s "NOTE-VARIABLE-INFO")
       (values (append '((x :info nil))
                       (list (list 'x '(:special integer)
                          (witness-istruct 'ccl::lexical-environment
                            (list (witness-istruct 'ccl::definition-environment
                                    (list '(compile-file) nil nil nil nil nil nil nil nil nil nil nil nil))
                                  nil nil nil nil nil nil))))) t))
      ((equal s "CORE-TRANSCEND-DESTINATION") (values '((0.0d0) (0.5d0) (-2.0d0)) t))
      ((member s '("CORE-TRANSCEND-CONDITION" "CORE-LOG-CONDITION") :test #'equal) (values '((0.0d0) (-1.0d0) (1.0d0)) t))
      ((equal s "%KERNEL-GLOBAL-OFFSET-FORM")
       (values '((0) (16) ((quote foo)) (foo)) t))
      ((equal s "VECTOR-INDEX->INDEX") (values '((14) (16) (30) (100)) t))
      ((equal s "ROTATE-HASH-CODE") (values '((0) (1) (7) (8) (65535) (536870911)) t))
      ((member s '("DEFINITION-ENVIRONMENT" "COMPILE-FILE-ENVIRONMENT-P") :test #'equal)
       (values (list (list nil)
                     (list (witness-istruct 'ccl::lexical-environment
                              (list (witness-istruct 'ccl::definition-environment
                                      (list '(compile-file) nil nil nil nil nil nil nil nil nil nil nil nil))
                                    nil nil nil nil nil nil)))
                     (list (witness-istruct 'ccl::lexical-environment
                              (list nil nil nil nil nil nil nil)))) t))
      ((equal s "%CHARACTER-ATTRIBUTE")
       (values (loop for char in '(#\Null #\Space #\A #\U+0101 #\λ #\🙂)
                     collect (list char (input-sparse-vector))) t))
      ((member s '("%GET-READTABLE-CHAR" "GET-MACRO-CHARACTER") :test #'equal)
       (values (loop for char in '(#\Space #\A #\λ #\🙂) collect (list char (input-readtable))) t))
      ((equal s "WHITESPACEP") (values '((#\Space) (#\A) (#\λ) (#\🙂)) t))
      ((equal s "ADD-FORMAT-CHAR") (values '((#\a :handler) (#\Z nil) (#\Null :zero)) t))
      ((equal s "PATH-STR-SUB")
       (values '(("*" "" 0 0 1 0) ("*" "abc" 0 0 1 3)
                 ("abc" "abc" 0 0 3 3) ("ab" "ac" 0 0 2 2)
                 ("a*" "abc" 0 0 2 3)) t))
      ((eql (search "CORE-LIBM-" s) 0)
       (let* ((single (search "32" s))
              (kind (if single 'single-float 'double-float))
              (operation (subseq s 10 (- (length s) 2)))
              (inputs (cond ((equal operation "ASINH") '((-1.0d20) (-100) (-2) (-0.5) (-0.0d0) (0) (0.5) (2) (100) (1.0d20)))
                            ((equal operation "ACOSH") '((1) (1.00000011920928955078125d0) (1.125) (2) (100) (1.0d20)))
                            ((equal operation "ATANH") '((-0.999999940395355224609375d0) (-0.5) (-0.0d0) (0) (0.5) (0.999999940395355224609375d0)))
                            ((equal operation "EXPT") '((2 3) (4 0.5) (0 2) (-2 3) (1.25 2.5)))
                            ((equal operation "ATAN2") '((0 1) (1 0) (-1 -1) (0.5 0.25)))
                            ((equal operation "LOG") '((1) (2) (0.5) (10)))
                            ((member operation '("ACOS" "ASIN") :test #'equal) '((-1) (-0.5) (0) (0.5) (1)))
                            (t '((-2) (-0.5) (0) (0.5) (2))))))
         (values (mapcar (lambda (args) (mapcar (lambda (x) (coerce x kind)) args)) inputs) t)))

      ((member s '("%SINGLE-FLOAT" "%DOUBLE-FLOAT" "FLOAT" "ABS" "PHASE" "%NEGATE") :test #'equal)
       (values '((0) (1) (-1) (536870911) (-536870912) (1.25s0) (-2.5d0) (-0.0d0)) t))
      ((member s '("CORE-COERCE-SINGLE" "CORE-COERCE-DOUBLE") :test #'equal)
       (values '((0) (7) (-7) (536870912) (1.25s0) (-2.5d0)) t))
      ((member s '("CORE-NATURAL-LEFT" "CORE-NATURAL-RIGHT") :test #'equal)
       (values '((0) (1) (255) (65535) (536870911)) t))
      ((member s '("%BIG-ENDIAN-U8-REF-U32" "%LITTLE-ENDIAN-U8-REF-U32") :test #'equal)
       (values (loop for xs in '((0 0 0 0) (0 0 0 1) (127 255 255 255) (128 0 0 0) (255 255 255 255))
                     collect (list (make-array 4 :element-type '(unsigned-byte 8) :initial-contents xs) 0)) t))
      ((equal s "%CHAR-CODE-CASE-FOLD")
       (values (loop for code in '(0 64 65 90 97 122 127 128 255 955 128578)
                     collect (list code (subseq ccl::*upper-to-lower* 0 128))) t))
      ((member s '("%CHAR-CODE-UPCASE" "%CHAR-CODE-DOWNCASE") :test #'equal)
       (values (mapcar #'list '(0 64 65 90 97 122 127 128 255 955 128578)) t))
      ((member s '("CHAR-UPCASE" "CHAR-DOWNCASE" "LOWER-CASE-P") :test #'equal)
       (values (mapcar #'list '(#\Null #\A #\Z #\a #\z #\Space #\λ #\Λ #\ß #\🙂)) t))
      ((member s '("%PATH-MEM-LAST" "%PATH-MEM-LAST-QUOTED" "%PATH-ONE-QUOTED-P") :test #'equal)
       (values '((":" "") (":" "abc") (":" "a:b:c") (":" "a\\:b") (":" "a\\\\:b") ("ab" "axb" 1 3)) t))
      ((equal s "%PATH-QUOTED-P")
       (values '(("" 0 0) ("abc" 2 0) ("a\\:b" 2 0) ("a\\\\:b" 3 0) ("a\\\\\\:b" 4 0)) t))
      ((equal s "%PV-MAP-LOOKUP")
       (values (loop for code in '(-1 0 1 7 8 9 10 100)
                     collect (list code (input-fixnum-vector '(0 7 9 100))
                                   (input-fixnum-vector '(17 -7 99 1)))) t))
      ((equal s "CONGRUENT-LFBITS-P")
       (values '((0 0) (1 1) (1 2) (256 256) (0 256) (65536 0) (65536 65536)) t))
      ((member s '("GC-RETAINING-PAGES" "GC-VERBOSE-P") :test #'equal) (values '(()) t))
      ((equal s "PROCESS-SINGLE-SELECTION")
       (values '((nil) (7) ((defvar x)) ((defvar x 7)) ((defparameter x 9))) t))
      ((equal s "%CONS-DEF-INFO-METHOD")
       (values '((0 nil nil nil) (0 #(:a :b) (:before) (integer)) (65536 #(:key) nil (t))) t))
      ((equal s "SPARSE-VECTOR-REF")
       (let ((v (ccl::make-sparse-vector 1000 t 7)))
         (setf (ccl::sparse-vector-ref v 0) 9 (ccl::sparse-vector-ref v 257) 11)
         (setf (ccl::sparse-vector-lock v) nil)
         (input-structure v)
         (values (mapcar (lambda (i) (list v i)) '(0 1 255 256 257 999)) t)))
      ((equal s "REQUIRE-GLOBAL-SYMBOL") (values (list (list (witness-symbol ccl::$sym_vbit_global))) t))
      ((equal s "ARRAY-ELEMENT-TYPE")
       (values (mapcar #'list (list #(1 2) "abc" (make-array 2 :element-type '(unsigned-byte 8))
                                    (make-array 2 :element-type '(signed-byte 16)) (make-array 2 :element-type '(unsigned-byte 32))
                                    (witness-array 2))) t))
      ((equal s "LDB32")
       (values '((0 0 0 0) (1 2 4 0) (32767 65535 8 12) (-1 -1 16 0) (4660 22136 16 16)) t))
      ((equal s "%LIST-TO-UVECTOR")
       (values '((nil nil) (nil (1 2 3))) t))
      ((member s '("COMPLEX-ARRAY-P" "SIMPLE-ARRAY-P") :test #'equal)
       (values (append '((nil) (7) (#(1 2)) ("abc")) (list (list (witness-array 2)))) t))
      ((equal s "DISPLACED-ARRAY-P") (values (list (list #(1 2)) (list "abc") (list (witness-array 2))) t))
      ((member s '("CORE-S8" "CORE-U16" "CORE-S16" "CORE-U32" "CORE-S32") :test #'equal)
       (let* ((row (assoc s '(("CORE-S8" (signed-byte 8) (-128 -1 0 127))
                             ("CORE-U16" (unsigned-byte 16) (0 255 256 65535))
                             ("CORE-S16" (signed-byte 16) (-32768 -129 0 32767))
                             ("CORE-U32" (unsigned-byte 32) (0 536870911 536870912 2147483648 4294967295))
                             ("CORE-S32" (signed-byte 32) (-2147483648 -536870913 -536870912 536870911 536870912 2147483647))) :test #'equal))
              (v (make-array (length (third row)) :element-type (second row) :initial-contents (third row))))
         (values (loop for i below (length v) collect (list v i)) t)))
      ((equal s "CORE-GLOBAL-CELL") (values '((nil) (7) ((1 . 2))) t))
      ((equal s "CORE-UVSET-CHECKED") (values (list (list #(1 2) 1 7)) t))
      ((member s '("+" "*") :test #'equal)
       (values '(() (7) (2 3) (1 2 3 4) (-7 9 2) (536870911 1)) t))
      ((equal s "-") (values '((7) (-7) (9 2) (20 3 7) (0 -536870912)) t))
      ((equal s "/") (values '((1) (-1) (6 3) (12 2 3) (7.5d0 2.5d0) (-12 2 3)) t))
      ((member s '("<" "<=" "=" "/=" ">" ">=") :test #'equal)
       (values '((1) (1 2) (2 1) (2 2) (1 2 3) (3 2 1) (1 2 1) (0 536870911 536870912)) t))
      ((member s '("LOGAND" "LOGIOR" "LOGXOR") :test #'equal)
       (values '(() (7) (3 5) (7 15 31) (-1 255) (-7 -11 19)) t))
      ((member s '("MAX" "MIN") :test #'equal)
       (values '((1) (1 3 2) (-9 -3 -7) (7 2.0d0 5)) t))
      ((equal s "VECTOR") (values '(() (7) (1 nil "text") ((1 . 2) (3 . 4))) t))
      ((equal s "%ARRAY-HEADER-SIMPLE-P")
       (values (list (list (witness-array 0)) (list (witness-array 2))) t))
      ((equal s "CORE-AUX") (values '((1) ((2 . 3)) (7 9) (7 nil)) t))
      ((equal s "CORE-LEXPR-ZERO") (values '(() (1 2)) t))
      ((equal s "CORE-LEXPR") (values '(() (1) ((2 . 3) "last") (1 2 3 4)) t))
      ((member s '("CORE-LIST-STAR" "CORE-VECTOR") :test #'equal)
       (values '((nil nil) (1 2) ((1 . 2) (3 . 4))) t))
      ((member s '("CORE-MAKE-VECTOR" "CORE-MAKE-LIST" "CORE-RETRY-VECTOR" "CORE-RETRY-LIST") :test #'equal)
       (values (loop for n in '(0 1 2 3 17) append
                     (loop for x in '(nil 7 (1 . 2)) collect (list n x))) t))
      ((equal s "CORE-MAKE-STRING") (values '((0 #\a) (1 #\Z) (2 #\λ) (7 #\Space)) t))
      ((equal s "CORE-MAKE-OCTETS") (values '((0 0) (1 255) (2 17) (17 9)) t))
      ((equal s "CORE-NTH-VALUE")
       (values (loop for i in '(0 1 2 3 7) collect (list i '(1 . 2))) t))
      ((member s '("CORE-UVREF" "%MISC-REF") :test #'equal)
       (values (loop for v in (list #(1 (2 . 3) nil) "aλz" (make-array 3 :element-type '(unsigned-byte 8) :initial-contents '(0 17 255))) append
                     (loop for i below 3 collect (list v i))) t))
      ((member s '("CORE-UVSET" "%MISC-SET") :test #'equal)
       (values (list (list #(1 2 3) 2 '(7 . 8)) (list (copy-seq "abc") 1 #\λ)
                     (list (make-array 4 :element-type '(unsigned-byte 8) :initial-element 9) 3 2)) t))
      ((equal s "CORE-SHIFTS")
       (values (loop for n in '(0 1 2 7 15) append
                     (loop for x in '(0 1 7 1023) collect (list n x))) t))
      ((equal s "CORE-LOGBITP")
       (values (loop for i in '(0 1 7 28 29 30 60) append
                     (loop for x in '(0 1 -1 536870911 -536870912) collect (list i x))) t))
      ((member s '("%BIG-ENDIAN-U8-REF-U16" "%LITTLE-ENDIAN-U8-REF-U16") :test #'equal)
       (values (loop for i below 3 collect
                     (list (make-array 4 :element-type '(unsigned-byte 8) :initial-contents '(0 17 128 255)) i)) t))
      ((equal s "PLISTP") (values '((nil) (7) ((:a 1)) ((:a 1 :b 2)) ((:a))) t))
      ((equal s "SETPROP")
       (values '((nil :a 1) ((:a 1 :b 2) :a 9) ((:a 1 :b 2) :c (3 . 4))) t))
      ((member s '("ADD-TO-ALIST" "ALIST-ADJOIN") :test #'equal)
       (values '((:a 1 nil) (:a 1 ((:a . 1))) (:a 2 ((:a . 1))) (:b 7 ((:a . 1)))) t))
      ((member s '("GETF" "%KEYWORD-PRESENT-P") :test #'equal)
       (values '((nil :x) ((:a nil :b 7) :a) ((:a 1 :b 7) :b) ((:a 1) :x)) t))
      ((equal s "PL-SEARCH") (values '((nil :a) ((:a 1 :b 2) :a) ((:a 1 :b 2) :b) ((:a 1) :c)) t))
      ((equal s "LSH") (values '((0 7) (1 0) (7 3) (1024 -3) (77 -9)) t))
      ((equal s "HI-LO-FRACTION-P") (values '((0 0 0) (1 0 0) (7 9 4) (3 7 27) (0 1 29)) t))
      ((equal s "%SCHARCODE") (values '(("abc" 0) ("λ🙂" 1)) t))
      ((member s '("CORE-HOST-CPU-CACHE" "CORE-HOST-CPU-WARM") :test #'equal)
       (values (list (list (core-native-function 'ccl::cpu-count))) t))
      ((equal s "CORE-HOST-WAIT-CALLER")
       (values (list (list (core-native-function 'ccl:wait-on-semaphore) :semaphore)) t))
      ((equal s "CORE-HOST-TIMED-CALLER")
       (values (list (list (core-native-function 'ccl:timed-wait-on-semaphore) :semaphore)) t))
      ((equal s "CORE-HOST-ENV") (values '(("PRESENT") ("MISSING")) t))
      ((member s '("CORE-HOST-COUNT" "CORE-HOST-TIME" "CORE-HOST-ACTION") :test #'equal)
       (values '(()) t))
      ((equal s "GETENV") (values '(("PRESENT") ("MISSING") (7)) t))
      ((member s '("GET-UNIVERSAL-TIME" "CPU-COUNT" "YIELD") :test #'equal) (values '(()) t))
      ((equal s "WASM-HOST-SERVICE") (values '((:missing)) t))
      ((equal s "SIGNAL-SEMAPHORE") (values '((:semaphore)) t))
      ((equal s "WAIT-ON-SEMAPHORE") (values '((:semaphore) (:semaphore :flag "waiting")) t))
      ((equal s "TIMED-WAIT-ON-SEMAPHORE") (values '((:semaphore 0) (:semaphore 3 :notification)) t))
      ((equal s "%IOBLOCK-INPUT-FILE-LENGTH")
       (values (loop for n in '(0 1 4096) append
                     (loop for new in '(nil 17) collect
                           (list (input-structure (ccl::make-file-ioblock :fileeof n)) new))) t))
      ((equal s "THREAD-EXHAUSTED-P")
       (values (list (list nil)
                     (list (witness-istruct 'ccl::lisp-thread (cons nil (make-list 10))))
                     (list (witness-istruct 'ccl::lisp-thread (cons 7 (make-list 10))))) t))
      ((equal s "THREAD-TOTAL-RUN-TIME")
       (values (list (list nil) (list (witness-istruct 'ccl::lisp-thread (cons 7 (make-list 10))))) t))
      ((equal s "SHUTDOWN-LISP-THREADS") (values '(()) t))
      ((equal s "INIT-CLASS-CELL-INSTANTIATOR")
       (values (list (list nil) (list (witness-istruct 'ccl::class-cell '(:class nil :old :extra)))) t))
      ((equal s "%PKG-REF-FIND-PACKAGE")
       (values (loop for value in '(nil :package (1 . 2)) collect
                     (list (witness-istruct 'ccl::package-ref (list "reference" value)))) t))
      ((equal s "SPECIALIZED-ELEMENT-TYPE-MAYBE")
       (values (loop for (a b) in '((integer fixnum) (character character) (nil t)) collect
                     (list (witness-istruct 'ccl::array-ctype (list nil nil '* nil a b nil)))) t))
      ((equal s "%VECTOR-OUTPUT-STREAM-CLOSE")
       (values (loop for (count offset) in '((0 0) (3 0) (3 1) (4 4)) collect
                     (list nil (input-structure (ccl::make-vector-output-stream-ioblock
                                :displaced (witness-array 0) :displacement offset
                                :outbuf (input-structure (ccl::make-io-buffer :count count)))))) t))
      ((equal s "NOT-IN-CURRENT-PROCESS") (values '((:current :reset) (:other :reset)) t))
      ((equal s "MISSING-TYPE-METHOD") (values '(() (nil) (:method 7)) t))
      ((equal s "SORT-LIST-ERROR") (values '(()) t))
      ((equal s "%INVALID-METHOD-ERROR") (values '((nil "bad") (:method "bad ~s" 7)) t))
      ((equal s "%BADARG") (values '((7 symbol) (nil integer) ("text" cons)) t))
      ((member s '("IOBLOCK-NO-BINARY-INPUT" "IOBLOCK-NO-BINARY-OUTPUT"
                   "IOBLOCK-NO-CHAR-INPUT" "IOBLOCK-NO-CHAR-OUTPUT") :test #'equal)
       (values (list (list (input-ioblock 0 nil)) (list (input-ioblock 0 nil) 7 8)) t))
      ((member s '("RECURSIVE-LOCK-PTR" "READ-WRITE-LOCK-PTR") :test #'equal)
       (values (loop for pointer in '(nil 0 7) collect
                     (list (witness-node 'lock
                             (list pointer (if (equal s "RECURSIVE-LOCK-PTR")
                                             'ccl::recursive-lock 'ccl::read-write-lock)
                                   0 "input lock" nil nil)))) t))
      ((equal s "%IOBLOCK-UNTYI")
       (values (loop for char in '(#\a #\Newline #\Null #\U+03BB) collect
                     (list (input-ioblock 0 nil) char)) t))
      ((member s '("IOBLOCK-INPOS" "IOBLOCK-OUTPOS") :test #'equal)
       (values (loop for index in '(0 1 31) collect
                     (let ((buffer (input-structure (ccl::make-io-buffer :idx index :count (+ index 4)))))
                       (list (input-structure (ccl::make-ioblock :inbuf buffer :outbuf buffer))))) t))
      ((member s '("STRING-INPUT-STREAM-IOBLOCK-READ-CHAR"
                   "STRING-INPUT-STREAM-IOBLOCK-PEEK-CHAR") :test #'equal)
       (values (loop for (text index) in '(("" 0) ("a" 0) ("a" 1) ("aλz" 1) ("aλz" 3))
                     collect (list (input-structure
                                    (ccl::make-string-input-stream-ioblock
                                     :string text :index index :end (length text))))) t))
      ((equal s "STRING-INPUT-STREAM-IOBLOCK-UNREAD-CHAR")
       (values (loop for (text index) in '(("a" 1) ("aλz" 2) ("aλz" 3))
                     collect (list (input-structure
                                    (ccl::make-string-input-stream-ioblock
                                     :string text :index index :end (length text)))
                                   (char text (1- index)))) t))
      ((equal s "%EPUSHVAL")
       (values (loop for push in '(nil t) append
                     (loop for val in '(nil 17 (1 . 2)) collect
                           (list (witness-istruct 'ccl::faslstate
                                   (list "input" (make-array 3 :initial-element nil)
                                         1 nil nil nil nil nil nil 0 0 push nil nil)) val))) t))
      ((equal s "CHEAP-CONS") (values '((nil nil) (1 (2 3)) ((1 2) :tail)) t))
      ((member s '("FREE-CONS" "CHEAP-COPY-LIST" "CHEAP-FREE-LIST") :test #'equal)
       (values '((nil) ((1)) ((1 2 3)) ((1 2 . :tail))) t))
      ((equal s "CHEAP-LIST") (values '(() (1) (1 nil :three)) t))
      ((equal s "OBJECT-IN-APPLICATION-HEAP-P") (values '((nil) (0) (7) ((1 . 2))) t))
      ((equal s "USING-LINEAR-SCAN") (values '(()) t))
      ((equal s "UCS-4-STREAM-DECODE")
       (values '((0 nil nil) (65 nil nil) (255 nil nil) (65535 nil nil)) t))
      ((member s '("LOCK-ACQUISITION-STATUS" "CLEAR-LOCK-ACQUISITION-STATUS"
                   "SEMAPHORE-NOTIFICATION-STATUS" "CLEAR-SEMAPHORE-NOTIFICATION-STATUS") :test #'equal)
       (let ((kind (if (search "SEMAPHORE" s) 'ccl::semaphore-notification 'ccl::lock-acquisition)))
         (values (loop for value in '(nil t :waiting (1 2))
                       collect (list (witness-istruct kind (list value)))) t)))
      ((member s '("IOBLOCK-OCTETS-TO-ELEMENTS" "IOBLOCK-ELEMENTS-TO-OCTETS") :test #'equal)
       (values (loop for shift in '(0 1 2 3) append
                    (loop for n in '(0 1 7 8 65) collect
                          (list (input-ioblock shift nil) n))) t))
      ((member s '("INSTALL-IOBLOCK-INPUT-LINE-TERMINATION"
                   "INSTALL-IOBLOCK-OUTPUT-LINE-TERMINATION") :test #'equal)
       (values (loop for sharing in '(nil :private :lock) append
                    (loop for mode in '(nil :cr :crlf :unicode)
                          collect (list (input-ioblock 0 sharing) mode))) t))
      ((equal s "COERCE-TO-VALUES")
       (values (list (list (witness-istruct 'ccl::values-ctype '(nil nil (integer) nil t nil nil nil)))
                     (list (witness-istruct 'ccl::named-ctype '(nil nil integer)))) t))
      ((equal s "MAKE-INTERSECTION-CTYPE")
       (values '((nil nil) (t (integer symbol))) t))
      ((equal s "NUMERIC-TYPES-ADJACENT")
       (values (loop for (low high) in '((nil 3) (3 nil) (3 4) (3 5) ((3) 3) (3 (3)))
                     collect (list (witness-istruct 'ccl::numeric-ctype (list nil nil 'integer nil nil nil low nil))
                                   (witness-istruct 'ccl::numeric-ctype (list nil nil 'integer nil nil high nil nil)))) t))
      ((member s '("EVENT-TICKS" "FIND-NAMED-PERIODIC-TASK") :test #'equal)
       (values (if (equal s "EVENT-TICKS") '(()) '((:first) (:second) (:missing))) t))
      ((equal s "SET-EVENT-TICKS") (values '((0) (1) (32767)) t))
      (t (values nil nil)))))

(defun more-environment (name)
  (let ((s (symbol-name name)))
    (cond ((equal s "FIND-GF-DISPATCH-TABLE-INDEX")
                 '((ccl::*obsolete-wrapper* . :obsolete) (ccl::*gf-dispatch-bug* . :bug)))
 ((equal s "%PROGVRESTORE") '((ccl::recipe-a . :old-a) (ccl::recipe-b . :old-b)))


      ((equal s "ADD-ACCESSOR-TYPES") '((ccl::*def-accessor-types* . nil)))
      ((equal s "PATH-STR-MATCH-P")
       (list (cons 'ccl::*pathname-escape-character* #\\)
             (cons 'ccl::*case-sensitive-filesystem* t)))
      ((equal s "WHITESPACEP") (list (cons '*readtable* (input-readtable))))
      ((equal s "ADD-FORMAT-CHAR")
       (list (cons 'ccl::*format-char-table* (make-array 128 :initial-element nil))
             (cons 'ccl::*lower-to-upper* (subseq ccl::*lower-to-upper* 0 1024))))
      ((equal s "PATH-STR-SUB") '((ccl::*pathname-escape-character* . #\\)))

      ((member s '("%CHAR-CODE-UPCASE" "%CHAR-CODE-DOWNCASE" "CHAR-UPCASE" "CHAR-DOWNCASE" "LOWER-CASE-P") :test #'equal)
       (list (cons 'ccl::*lower-to-upper* (subseq ccl::*lower-to-upper* 0 1024))
             (cons 'ccl::*upper-to-lower* (subseq ccl::*upper-to-lower* 0 1024))))
      ((member s '("%PATH-MEM-LAST" "%PATH-MEM-LAST-QUOTED" "%PATH-ONE-QUOTED-P" "%PATH-QUOTED-P") :test #'equal)
       '((ccl::*pathname-escape-character* . #\\)))
      ((member s '("GC-RETAINING-PAGES" "GC-VERBOSE-P") :test #'equal)
       (list (cons 'ccl::*gc-event-status-bits* (logior (ash 1 ccl::$gc-retain-pages-bit) (ash 1 ccl::$gc-verbose-bit)))))
      ((equal s "PROCESS-SINGLE-SELECTION") '((ccl::*always-eval-user-defvars* . t)))
      ((equal s "%CONS-DEF-INFO-METHOD") '((ccl::*loading-file-source-file* . "recipe.lisp")))
      ((equal s "CORE-GLOBAL-CELL") '((*core-global* . nil)))
      ((or (host-os-name-p name) (eql (search "CORE-HOST-" s) 0))
       (list (cons '*core-host-events* nil) (cons 'ccl::*cpu-count* nil)
             (cons 'ccl::*wasm-host-services*
                   (list (cons :getenv (core-native-function 'core-host-env))
                         (cons :cpu-count (core-native-function 'core-host-count))
                         (cons :universal-time (core-native-function 'core-host-time))
                         (cons :signal-semaphore (core-native-function 'core-host-action))
                         (cons :wait-on-semaphore (core-native-function 'core-host-action))
                         (cons :timed-wait-on-semaphore (core-native-function 'core-host-action))
                         (cons :yield (core-native-function 'core-host-action))))))
      ((equal s "NOT-IN-CURRENT-PROCESS") '((ccl::*current-process* . :current)))
      ((equal s "SPECIALIZED-ELEMENT-TYPE-MAYBE") '((ccl::*use-implementation-types* . t)))
      ((member s '("CHEAP-CONS" "FREE-CONS" "CHEAP-COPY-LIST" "CHEAP-LIST" "CHEAP-FREE-LIST") :test #'equal)
       (list (cons 'ccl::*cons-pool* (witness-node 'pool (list '(nil nil nil nil))))))
      ((equal s "USING-LINEAR-SCAN") '((ccl::*backend-use-linear-scan* . t)))
      ((member s '("COERCE-TO-VALUES" "MAKE-INTERSECTION-CTYPE") :test #'equal)
       '((ccl::*type-classes* . ((values . :values) (intersection . :intersection)))))
      ((member s '("EVENT-TICKS" "SET-EVENT-TICKS" "FIND-NAMED-PERIODIC-TASK") :test #'equal)
       (let* ((first (witness-istruct 'ccl::periodic-task
                      (list (witness-istruct 'ccl::ptaskstate '(0 7 nil 0)) :first nil)))
              (second (witness-istruct 'ccl::periodic-task
                       (list (witness-istruct 'ccl::ptaskstate '(0 9 nil 0)) :second nil))))
         (if (equal s "FIND-NAMED-PERIODIC-TASK")
           (list (cons 'ccl::*%periodic-tasks%* (list first second)))
           (list (cons 'ccl::*event-dispatch-task* first))))))))

(defun host-guarded-p (name)
  (member (symbol-name name)
          '("STREAM-IS-CLOSED" "SIGNAL-PACKAGE-ERROR" "GETENV" "WASM-HOST-SERVICE" "NOT-IN-CURRENT-PROCESS" "MISSING-TYPE-METHOD" "SORT-LIST-ERROR"
            "%INVALID-METHOD-ERROR" "%BADARG" "IOBLOCK-NO-BINARY-INPUT"
            "IOBLOCK-NO-BINARY-OUTPUT" "IOBLOCK-NO-CHAR-INPUT" "IOBLOCK-NO-CHAR-OUTPUT")
          :test #'equal))
