;;; Ordinary functions keep keyword names in their accepted arity metadata.
(defun bootstrap-function-keyvect (forms)
  (unless (= (length forms) 1) (refuse :function-keyvect-arity))
  (bootstrap-operands forms
    (lambda (values)
      (let ((function (temporary)) (pool (temporary)) (arity (temporary))
            (keys (temporary)) (header (temporary)))
        (with-output-to-string (s)
          (format s "(local.set ~a (call $object_base ~a (i32.const 32) (i32.const 1578)))"
                  function (first values))
          ;; A funcallable's class wrapper must never become a key vector.
          (write-string (b-condition (b-wat "(i32.ne (i32.load (local.get ~a)) (i32.const 1578))" function) 4) s)
          (format s "(local.set ~a (i32.load offset=24 (local.get ~a)))" pool function)
          (write-string (b-condition (b-wat "(i32.ne (i32.and (local.get ~a) (i32.const 7)) (i32.const 6))" pool) 4) s)
          (format s "(local.set ~a (i32.sub (local.get ~a) (i32.const 6)))
                     (call $span (local.get ~a) (i32.const 12))
                     (local.set ~a (i32.load (local.get ~a)))" pool pool pool header pool)
          (write-string (b-condition (b-wat "(i32.or (i32.ne (i32.and (local.get ~a) (i32.const 255)) (i32.const 250)) (i32.lt_u (local.get ~a) (i32.const 762)))" header header) 4) s)
          (write-string (b-condition (b-wat "(i32.ne (i32.load offset=16 (local.get ~a)) (i32.load offset=4 (local.get ~a)))" function pool) 4) s)
          (format s "(local.set ~a (call $object_base (i32.load offset=16 (local.get ~a)) (i32.const 32) (i32.const 2042)))" arity function)
          (write-string (b-condition (b-wat "(i32.ne (i32.load offset=4 (local.get ~a)) (i32.const 4))" arity) 4) s)
          (dolist (offset '(8 12))
            (write-string (b-condition (b-wat "(i32.or (i32.and (i32.load offset=~d (local.get ~a)) (i32.const 3)) (i32.lt_s (i32.load offset=~d (local.get ~a)) (i32.const 0)))" offset arity offset arity) 4) s))
          (dolist (offset '(16 20 24))
            (write-string (b-condition (b-wat "(i32.and (i32.ne (i32.load offset=~d (local.get ~a)) (i32.const 77825)) (i32.ne (i32.load offset=~d (local.get ~a)) (i32.const 77838)))" offset arity offset arity) 4) s))
          (format s "(local.set ~a (i32.load offset=28 (local.get ~a)))" keys arity)
          (write-string (b-condition (b-wat "(i32.ne (i32.and (local.get ~a) (i32.const 7)) (i32.const 6))" keys) 4) s)
          (format s "(call $span (i32.sub (local.get ~a) (i32.const 6)) (i32.const 4))
                     (local.set ~a (i32.load (i32.sub (local.get ~a) (i32.const 6))))" keys header keys)
          (write-string (b-condition (b-wat "(i32.ne (i32.and (local.get ~a) (i32.const 255)) (i32.const 250))" header) 4) s)
          (format s "(call $span (i32.sub (local.get ~a) (i32.const 6)) (i32.add (i32.const 4) (i32.shl (i32.shr_u (local.get ~a) (i32.const 8)) (i32.const 2))))" keys header)
          (write-string (b-condition (b-wat "(i32.and (i32.eq (i32.load offset=20 (local.get ~a)) (i32.const 77825)) (i32.ne (local.get ~a) (i32.const 250)))" arity header) 4) s)
          (format s "(if (result i32) (i32.eq (i32.load offset=20 (local.get ~a)) (i32.const 77825)) (then (i32.const 77825)) (else (local.get ~a)))" arity keys))))))
