// The runner derives setup.mjs from the reviewed constructor harness, changing
// only its test entry and root declarations. Runtime and generated bytes persist.
import fs from 'node:fs';import assert from 'node:assert/strict';
import {setup} from './setup.mjs';
const output=process.argv[4],rows=[];
for(const high of [false,true]){
 const s=setup(high);const {get,set,load,store,owner,entries,handles,ROOT,OUT,memory,external,mods}=s;
 function invoke(name,args=[],self=handles[name]){set(116,0);set(120,OUT);set(124,OUT+64);set(64,ROOT+8);set(128,ROOT);store(ROOT+4,args.length);args.forEach((v,i)=>store(ROOT+8+4*i,v));const r=entries[name](self,args.length);return Array.from({length:r[1]},(_,i)=>load(OUT+4*i));}
 function clear(){store(ROOT+4,0);set(116,0);}
 function collect(){const base=get(56),end=get(52),before=get(48)-base;const r=owner.atSafepoint(o=>o.collect());assert.equal(r.reclaimed,before-(get(48)-get(56)),'independent reclaimed bytes');new Uint8Array(memory.buffer,base,end-base).fill(0xdd);return r;}
 const make=n=>invoke('pair',[4*n,4*(n+1)])[0];
 // Each declared family is the ONLY path to its own generated object.
 for(const [i,kind] of ['module-constants','callbacks','registry','host'].entries()){store(external+4*i,make(401+i*10));clear();}
 store(1024+188,make(451));clear();
 // Callback registry contains a real generated closure and its captured cons.
 const capture=make(461);store(external+16,capture);const callback=invoke('make_reader',[load(external+16)])[0];store(external+4,callback);store(external+16,77825);clear();
 const before=Array.from({length:4},(_,i)=>load(external+4*i));const raw=make(499);store(external+128,raw);clear();const first=collect();
 assert.equal(first.reclaimed,16,'superseded callback datum and unrooted scalar are dead');
 for(const i of [0,2,3]){assert.notEqual(load(external+4*i),before[i],'root moved '+i);assert.deepEqual(invoke('read_pair',[load(external+4*i)]),[4*(401+i*10),4*(402+i*10)],'generated root value '+i);clear();}
 assert.equal(load(external+128),raw,'tag-like non-root word is untouched');
 assert.notEqual(load(external+4),before[1],'callback root moved');
 const fn=load(external+4),child=mods[load(fn-2)/4-1].name;assert.deepEqual(invoke(child,[],fn),[4*461],'generated callback closure after movement');clear();
 assert.deepEqual(invoke('read_pair',[load(1024+188)]),[4*451,4*452]);clear();
 // Actual result count, not reserved capacity, keeps all three cons values.
 const values=invoke('many_values');const resultMove=collect();const moved=Array.from({length:get(116)},(_,i)=>load(OUT+4*i));assert.equal(moved.length,3);assert(moved.every((x,i)=>x!==values[i]),'active values moved');for(const [i,p] of moved.entries()){assert.equal(load(p+3),[97,103,109][i]*4);assert.equal(load(p-1),[101,107,113][i]*4);}clear();
 // A deliberately invalid interior tagged word in a real root is refused;
 // the same numeric bits in undeclared raw storage do not become a root.
 const saved=load(external);store(external,load(external+4)+8);const state=[get(48),get(56),get(52),load(external)];assert.throws(()=>owner.atSafepoint(o=>o.collect()),/collection refused 3/);assert.deepEqual([get(48),get(56),get(52),load(external)],state);store(external,saved);
 const repeated=collect();for(const i of [0,2,3])assert.equal(load(load(external+4*i)+3),4*(401+i*10));
 rows.push({high,status:'PASS',families:['module-constants','callbacks','registry','host','next_method_context','multiple-values'],callbackInvoked:true,first,resultMove,repeated,rawUnchanged:true,interiorRefused:true});
}
fs.writeFileSync(output,JSON.stringify({status:'PASS',rows},null,2)+'\n');
