;;; Source macro/compiler-macro bodies, without global definition installation.
(defpackage :ccl-source-expanders (:use :cl))
(in-package :ccl-source-expanders)
(defvar *selection* nil)
(defvar *registry* nil)
(defvar *events* nil)
(defvar *next-event* 0)
(defvar *compiled* nil)
(defvar *literals* nil)
(defvar *mode* "normal")
(defvar *probe* nil)
(defun obj (&rest fields) (apply #'ccl-source-traversal::obj fields))
(defun field (x k) (ccl-source-traversal::field x k))
(defun label (x) (ccl-source-traversal::label x))
(defun ident (x) (ccl-startup-census::dependency-id x))
(defun note (fn)
  (let ((n (ccl:function-source-note fn)))
    (obj "source" (if n (namestring (ccl::source-note-filename n)) :null)
         "position" (if n (ccl::source-note-start-pos n) :null))))

(defun syntax (x)
  (cond ((null x) :null)
        ((consp x) (obj "cons" (list (syntax (car x)) (syntax (cdr x)))))
        ((symbolp x) (if (symbol-package x) (obj "symbol" (label x))
                      (obj "symbol" (label x) "identity" (ident x))))
        ((or (integerp x) (stringp x)) x)
        (t (unless (assoc x *literals* :test #'eq)
             (push (cons x (obj "id" (ident x) "type" (label (type-of x))
                               "name" (cond ((eq (type-of x) 'ccl::class-cell) (label (ccl::class-cell-name x)))
                                            ((eq (type-of x) 'ccl::class-wrapper) (label (class-name (ccl::%wrapper-class x))))
                                            (t :null))
                               "disposition" "UNQUALIFIED_NATIVE_LITERAL")) *literals*))
           (obj "object_ref" (ident x)))))

(defun ir (x)
  (cond ((ccl::acode-p x)
         (obj "operator" (label (ccl::acode-operator-name (ccl::acode-operator x)))
              "operands" (ir (ccl::acode-operands x))))
        ((consp x) (obj "cons" (list (ir (car x)) (ir (cdr x)))))
        (t (syntax x))))

(defun with-compiler-observation (thunk)
  (let* ((host ccl::*host-backend*) (old (ccl::backend-p2-compile host)) (owner ccl:*current-process*))
    (unwind-protect
      (progn
        (setf (ccl::backend-p2-compile host)
              (lambda (afunc &rest args)
                ;; Read actual IR before pass 2 mutates it; forward every value.
                (if (not (eq owner ccl:*current-process*)) (apply old afunc args)
                (let ((record (ccl-startup-census::function-observation afunc)))
                  (multiple-value-prog1 (apply old afunc args)
                    (push (cons (ccl::afunc-lfun afunc) record) *compiled*))))))
        (funcall thunk))
      (setf (ccl::backend-p2-compile host) old))))

(defun read-source (path start)
  (let* ((text (ccl-source-traversal::source-text
                (merge-pathnames path (pathname (concatenate 'string (ccl:getenv "CCL_DEFAULT_DIRECTORY") "/")))))
         (*package* (find-package "CCL")) (*read-eval* nil))
    (multiple-value-bind (form end) (read-from-string text t nil :start start)
      (let ((key (format nil "~a:~d" path start)))
        (push (obj "key" key "path" path "start" start "end" end
                   "text" (subseq text start end) "reader" (ccl-source-traversal::context))
              ccl-census-macros::*sources*)
        (values form key)))))

(defun register (name role fn old key)
  (unless (and (functionp fn) (functionp old) (not (eq fn old))
               (assoc fn *compiled* :test #'eq)
               (not (find-if (lambda (r) (and (eq name (first r)) (equal role (second r)))) *registry*)))
    (error "SOURCE-EXPANDER-BINDING-INVALID ~s ~s" name role))
  (push (list name role fn old key) *registry*))

(defun prepare ()
  (with-compiler-observation
    (lambda ()
      (ccl-census-macros::prepare)
      (dolist (r (reverse ccl-census-macros::*registry*))
        (register (first r) "macro" (second r) (third r) (fourth r)))
      (let ((cache nil))
        (ccl-census-stub::with-target-state
          (lambda ()
            (dolist (s *selection*)
              (destructuring-bind (name role path start) s
                (let* ((key (format nil "~a:~d" path start)) (fn (cdr (assoc key cache :test #'equal)))
                       (old (if (equal role "compiler-macro") (compiler-macro-function name) (macro-function name))))
                  (unless fn
                    (multiple-value-bind (form source-key) (read-source path start)
                      (unless (and (equal key source-key)
                                   (eq (car form) (cond ((equal role "macro") 'defmacro)
                                                       ((equal role "compiler-macro") 'define-compiler-macro)
                                                       (t 'defun)))
                                   (eq (second form) (if (equal role "architecture-dispatch") 'ccl::backend-arch-macroexpand name)))
                        (error "SOURCE-EXPANDER-FORM-MISMATCH"))
                      (setf fn (ccl-census-macros::native-function
                                 (if (equal role "architecture-dispatch") `(lambda ,@(cddr form))
                                   (ccl::parse-macro-1 (second form) (third form) (cdddr form)))))
                      (push (cons key fn) cache)))
                  (register name role fn old key))))))))))

(defun with-routing (thunk)
  (let* ((old-hook *macroexpand-hook*)
         (*macroexpand-hook*
           (lambda (fn form env)
             (let* ((sequence (prog1 *next-event* (incf *next-event*)))
                    (entry (find-if (lambda (r) (and (eq (car form) (first r))
                                                     (or (equal *mode* "name-only") (eq fn (fourth r))))) *registry*))
                    (selected (if (and entry (not (equal *mode* "inherited"))
                                       (not (and (equal *mode* "bypass-if") (eq (car form) 'if))))
                                (third entry) fn))
                    (input (syntax form)) (result nil) (problem :null) (completed nil))
               (unwind-protect
                 (handler-bind ((error (lambda (e) (setf problem (princ-to-string e)))))
                   (setf result
                     (if (and (equal *mode* "host-layout") (eq (car form) 'ccl::basic-stream-p))
                       (let ((ccl::*target-backend* ccl::*host-backend*)) (funcall old-hook selected form env))
                       (funcall old-hook selected form env)))
                   (when (and *probe* (equal *mode* "copy-no-change") (eq result form))
                     (setf result (copy-tree result)))
                   (setf completed t)
                   result)
                 (push (obj "sequence" sequence "operator" (label (car form))
                            "role" (if entry (second entry) "UNMATCHED")
                            "source" (if entry (fifth entry) :null)
                            "original_id" (ident fn) "selected_id" (ident selected)
                            "native_note" (note fn) "context" (ccl-source-traversal::context)
                            "input" input "output" (if completed (syntax result) :null)
                            "returned_input" (if (and completed (eq result form)) :true :false)
                            "status" (if completed "RETURNED" "ESCAPED") "problem" problem) *events*))))))
    (funcall thunk)))

(defun helper-bindings (observation)
  (let ((rows nil))
    (labels ((visit (f)
               (dolist (call (append (field f "calls") (field f "function_references")))
                 (dolist (target (field (field call "dependency") "targets"))
                   (when (equal (field target "kind") "global-binding")
                     (let* ((*package* (find-package "CCL"))
                            (name (read-from-string (field target "name")))
                            (fn (fboundp name)))
                       (push (obj "site_id" (field call "site_id") "name" (field target "name")
                                  "function_id" (if (functionp fn) (ident fn) :null)
                                  "note" (if (functionp fn) (note fn) :null)
                                  "disposition" "UNQUALIFIED_NATIVE_HELPER") rows)))))
               (dolist (child (field f "inner_functions")) (visit child))))
      (visit observation))
    (nreverse rows)))

(defun probes ()
  (let ((*events* nil) (*next-event* 0) (*literals* nil) (*probe* t) (rows nil))
    (labels ((expanded (name form)
               (let ((r (find-if (lambda (r) (and (eq name (first r)) (equal (second r) "compiler-macro"))) *registry*)))
                 (unless r (error "PROBE-BINDING-MISSING"))
                 (let ((value (funcall *macroexpand-hook* (fourth r) form nil)))
                   (push (obj "name" (label name) "output" (syntax value)
                              "returned_input" (if (eq value form) :true :false)) rows))))
             (captured (name form)
               (push (obj "name" name "ir"
                          (ir (ccl::afunc-acode
                            (ccl-census-stub::capture-lambda form 'ccl::source-expander-probe)))) rows)))
      (ccl-census-descriptions::with-descriptions
        (lambda ()
          (ccl-census-stub::with-target-state
            (lambda ()
              (with-routing
                (lambda ()
                  (expanded 'let* '(let* ((ccl::a 1)) ccl::a))
                  (expanded 'progn '(progn 7))
                  (expanded 'ccl::basic-stream-p '(ccl::basic-stream-p ccl::a))
                  (captured "local-shadow" '(lambda () (macrolet ((dotimes (&rest args) (declare (ignore args)) 42))
                                                            (dotimes (ccl::i 3) ccl::i))))
                  (captured "target-layout" '(lambda () (ccl::basic-stream-p nil)))
                  (let* ((cell (assoc :basic-stream (arch::target-uvector-subtags wasm-census::*census-arch*)))
                         (old (cdr cell)))
                    (unwind-protect
                      (progn (setf (cdr cell) 122)
                        (expanded 'ccl::basic-stream-p '(ccl::basic-stream-p ccl::a))
                        (captured "alternate-layout" '(lambda () (ccl::basic-stream-p nil))))
                      (setf (cdr cell) old))))))))))
    (nreverse rows)))

(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (*registry* nil) (*compiled* nil) (*events* nil) (*next-event* 0) (*literals* nil)
        (*mode* (or (ccl:getenv "CCL_EXPANDER_MODE") "normal"))
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*)))
    (prepare)
    ;; Allocate both callable IDs before choosing a route, so reference/source
    ;; traces share an identity namespace independent of which is invoked.
    (dolist (r (reverse *registry*)) (ident (third r)) (ident (fourth r)))
    (let ((tag (gensym)))
      (unless (eq :escaped (catch tag (with-compiler-observation (lambda () (throw tag :escaped)))))
        (error "COMPILER-OBSERVER-ESCAPE-FAILED"))
      (unless (eq :escaped (catch tag (with-routing (lambda () (throw tag :escaped)))))
        (error "EXPANDER-HOOK-ESCAPE-FAILED")))
    (let ((probe-results (probes)))
    (with-routing #'ccl-census-descriptions::run)
    (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                 (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                 (every (lambda (r) (eq (fourth r) (if (equal (second r) "compiler-macro")
                                                    (compiler-macro-function (first r)) (macro-function (first r))))) *registry*))
      (error "SOURCE-EXPANDER-STATE-NOT-RESTORED"))
    (with-open-file (out (ccl:getenv "CCL_EXPANDER_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
      (ccl-startup-census::json
        (obj "version" 1 "sources" (nreverse ccl-census-macros::*sources*)
             "registry" (loop for r in (reverse *registry*) for observation = (cdr (assoc (third r) *compiled* :test #'eq)) collect
                            (obj "operator" (label (first r)) "role" (second r) "source" (fifth r)
                                 "original_id" (ident (fourth r)) "selected_id" (ident (third r))
                                 "native_note" (note (fourth r)) "compiled_function" observation
                                 "helpers" (helper-bindings observation)))
             "events" (sort *events* #'< :key (lambda (e) (field e "sequence")))
             "literals" (mapcar #'cdr (reverse *literals*)) "probes" probe-results
             "restored" :true "native_pass2_restored" :true "bindings_unchanged" :true
             "macro_environment_qualified" :false "graph_edges_replaced" 0) out)
      (terpri out)))))
