(in-package "CL-USER")
(defvar wasm32-compiler::*reference-memory*)
(defvar *conversion-modules*) (defvar *conversion-cases*) (defvar *conversion-refusals*)
(let ((out (ccl:getenv "CONVERSION_OUTPUT")) (functions nil))
  (load (ccl:getenv "CONVERSION_CASES"))
  (load (ccl:getenv "CONVERSION_REFERENCE"))
  (dolist (entry *conversion-modules*)
    (destructuring-bind (name source arguments result) entry
      (let* ((*package* (find-package "WASM32-COMPILER"))
             (fn (compile nil (read-from-string source)))
             (module (wasm32-compiler::compile-primitive-module source name arguments result)))
        (push (cons name fn) functions)
        (with-open-file (s (concatenate 'string out name ".wat") :direction :output :if-exists :error)
          (write-string (getf module :wat) s)))))
  (with-open-file (s (concatenate 'string out "native.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for (id name args memory) in *conversion-cases* for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (let ((wasm32-compiler::*reference-memory* (make-hash-table)) (value nil))
        (dolist (pair memory) (setf (gethash (first pair) wasm32-compiler::*reference-memory*) (second pair)))
        (let ((failure (catch 'wasm32-compiler::reference-refusal
                         (setq value (logand #xffffffff
                           (apply (cdr (assoc name functions :test #'equal))
                             (loop for a in args for kind in (third (assoc name *conversion-modules* :test #'equal))
                               collect (if (eq kind :s32) (wasm32-compiler::reference-signed a) a))))) 0)))
          (format s "{\"id\":~s,\"expected\":{\"value\":~a,\"error\":~d},\"after\":[" id (if (zerop failure) value "null") failure)
          (loop for address in (sort (loop for k being the hash-keys of wasm32-compiler::*reference-memory* collect k) #'<) for j from 0 do
            (unless (zerop j) (write-char #\, s))
            (format s "[~d,~d]" address (gethash address wasm32-compiler::*reference-memory*)))
          (write-string "]}" s))))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "refusals.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for (name source args result) in *conversion-refusals* for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (let ((refused nil))
        (handler-case (wasm32-compiler::compile-primitive-module source name args result)
          (wasm32-compiler::unsupported-wasm32-code () (setq refused t)))
        (assert refused) (format s "{\"name\":~s,\"status\":\"REJECTED\"}" name)))
    (write-char #\] s))
  (format t "S1-CONVERSIONS-COMPILE-PASS~%") (ccl:quit))
