;;; Independent mathematical reference over numeric words and a sparse memory
;;; model. No native heap address is presented as a wasm32 pointer.
(in-package "WASM32-COMPILER")
(defvar *reference-memory*)
(defun reference-refuse (n) (throw 'reference-refusal n))
(defun reference-need (p n) (unless p (reference-refuse n)))
(defun reference-word (p) (gethash p *reference-memory* 0))
(defun reference-span (p n) (reference-need (<= 0 p (+ p n) (* 32769 65536)) 4))
(defun reference-signed (n) (if (logbitp 31 n) (- n (expt 2 32)) n))
(defun %box-s32 (n) (reference-need (<= (- (expt 2 29)) n (1- (expt 2 29))) 1) (logand #xffffffff (* n 4)))
(defun %unbox-fixnum (n) (reference-need (zerop (mod n 4)) 2) (/ (reference-signed n) 4))
(defun %address-fixnum (n) (reference-need (< n (expt 2 29)) 1) (* n 4))
(defun %fixnum-address (n) (let ((v (%unbox-fixnum n))) (reference-need (>= v 0) 1) v))
(defun %tag-misc (n) (reference-need (zerop (mod n 8)) 3) (+ n 6))
(defun %untag-misc (n) (reference-need (= (mod n 8) 6) 2) (- n 6))
(defun %effective-address (n d) (let ((r (+ n d))) (reference-need (<= 0 r #xffffffff) 4) r))
(defun %header-word (n) (let ((p (%untag-misc n))) (reference-span p 4) (reference-word p)))
(defun %array-bytes (n width)
  (reference-need (and (< n (expt 2 24)) (plusp width)) 1)
  (let ((bytes (* n width))) (reference-need (<= bytes #xffffffff) 4) bytes))
(defun reference-registry (r)
  (reference-span r 12)
  (let ((first (reference-word r)) (next (reference-word (+ r 4))) (limit (reference-word (+ r 8))))
    (reference-need (<= first next limit (expt 2 29)) 7) (values first next limit)))
(defun %issue-code (r)
  (multiple-value-bind (first next limit) (reference-registry r)
    (declare (ignore first)) (reference-need (< next limit) 6)
    (setf (gethash (+ r 4) *reference-memory*) (1+ next)) (* next 4)))
(defun %validate-code (n r)
  (multiple-value-bind (first next limit) (reference-registry r)
    (declare (ignore limit)) (reference-need (and (zerop (mod n 4)) (< n (expt 2 31))) 2)
    (reference-need (<= first (/ n 4) (1- next)) 5) n))
(defun %code-index (n) (/ n 4))
(defun %validate-slot (n kind signature role r)
  (reference-span r 8) (reference-need (= kind 3) 9)
  (let ((capacity (reference-word r)) (reserved (reference-word (+ r 4))))
    (reference-need (<= reserved capacity 8) 7) (reference-need (< n capacity) 7)
    (reference-need (>= n reserved) 8)
    (let ((entry (+ r 8 (* 8 n))))
      (reference-span entry 8)
      (reference-need (and (plusp signature) (= (reference-word entry) signature)) 10)
      (reference-need (and (plusp role) (= (reference-word (+ entry 4)) role)) 11)
      (reference-need (member n '(4 5)) 12) n)))
(defun %slot-index (n) n)
