(in-package :wasm32-compiler)
(defvar *frontend-reader-ran* nil)

(defun frontend-controls (out)
  (let ((rows nil))
    (flet ((refused (name source links &optional (package "CCL"))
             (let ((answer (frontend-outcome
                            (lambda () (compile-bootstrap-source source name links package)))))
               (when (equal answer "admitted") (error "Control admitted: ~a" name))
               (push (list name answer) rows))))
      (refused "trailing" "(lambda () nil) 7" nil)
      (let ((*frontend-reader-ran* nil))
        (refused "read_eval"
                 "#.(progn (setq wasm32-compiler::*frontend-reader-ran* t) '(lambda () nil))" nil)
        (assert (null *frontend-reader-ran*)))
      (refused "missing_package" "(lambda () nil)" nil "NO-SUCH-BOOTSTRAP-PACKAGE")
      (refused "entry_not_list" "(lambda () nil)" '(7))
      (refused "entry_short" "(lambda () nil)" '((ccl::memq)))
      (refused "entry_long" "(lambda () nil)" '((ccl::memq "a" 7)))
      (refused "identity_nil" "(lambda () nil)" '((nil "a")))
      (refused "wire_not_string" "(lambda () nil)" '((ccl::memq 7)))
      (refused "wire_empty" "(lambda () nil)" '((ccl::memq "")))
      (refused "wire_long" "(lambda () nil)" (list (list 'ccl::memq (make-string 65 :initial-element #\a))))
      (refused "duplicate_identity" "(lambda () nil)" '((ccl::memq "a") (ccl::memq "b")))
      (refused "duplicate_wire_name" "(lambda () nil)" '((ccl::memq "a") (ccl::append-2 "a")))
      (refused "unsafe_wire_name" "(lambda () nil)" '((ccl::memq "a\"b")))
      (refused "compound_identity" "(lambda () nil)" '(((setf car) "a")))
      (refused "unknown_call" "(lambda (x) (uninstalled-bootstrap-call x))" nil)
      (refused "checked_type" "(lambda (x) (declare (optimize (safety 3))) (the fixnum x))" nil)
      (refused "nested_load_time"
               "(lambda () (macrolet ((later () '(load-time-value (list 1)))) (later)))" nil)
      (let ((ccl::*compiler-macros* (make-hash-table :test #'eq)))
        (setf (gethash 'ccl::bootstrap-host-fold ccl::*compiler-macros*)
              (lambda (form env) (declare (ignore form env)) 999))
        (refused "host_compiler_macro" "(lambda () (bootstrap-host-fold))" nil))
      (refused "unsupported_ir" "(lambda (x) (load-time-value (list 1)))" nil))
    ;; The old mode must retain its narrower source boundary.
    (dolist (form '((lambda (x) (when x x)) (lambda (x) (case x (nil 1) (t 2)))
                    (lambda (x) (the list x))))
      (let ((answer (frontend-outcome (lambda () (compile-call-form form "old" nil)))))
        (assert (not (equal answer "admitted")))
        (push (list "legacy-refusal" answer) rows)))
    (with-open-file (s (concatenate 'string out "admission.json") :direction :output :if-exists :error)
      (format s "[")
      (loop for (name answer) in (nreverse rows) for i from 0 do
        (unless (zerop i) (write-char #\, s))
        (format s "{\"name\":~s,\"refusal\":~s}" name answer))
      (format s "]"))))
