;;; Private source-derived numeric/layout helpers for the census, no global rebinding.
(defpackage :ccl-target-helpers (:use :cl))
(in-package :ccl-target-helpers)
(defvar *sources* nil)
(defvar *calls* nil)
(defvar *phase* nil)
(defvar *event* nil)
(defvar *mode* "normal")
(defun obj (&rest x) (apply #'ccl-source-expanders::obj x))
(defun label (x) (ccl-source-expanders::label x))
(defun ident (x) (ccl-source-expanders::ident x))
(defun syntax (x)
  (cond ((floatp x) (multiple-value-bind (significand exponent sign) (integer-decode-float x)
                     (obj "float" (label (type-of x)) "significand" significand "exponent" exponent "sign" sign)))
        ((consp x) (obj "cons" (list (syntax (car x)) (syntax (cdr x)))))
        (t (ccl-source-expanders::syntax x))))
(defun bool (x) (if x :true :false))
(defun read-form (path name &optional host)
  (flet ((get-form ()
           (let* ((text (ccl-source-traversal::source-text
                         (merge-pathnames path (pathname (concatenate 'string (ccl:getenv "CCL_DEFAULT_DIRECTORY") "/")))))
                  (marker (concatenate 'string "(" name " ")) (start (search marker text))
                  (*package* (find-package "CCL")) (*read-eval* nil))
             (unless (and start (not (search marker text :start2 (1+ start)))) (error "HELPER-SOURCE-NOT-UNIQUE"))
             (multiple-value-bind (form end) (read-from-string text t nil :start start)
               (push (obj "path" path "start" start "end" end "text" (subseq text start end)
                          "reader" (ccl-source-traversal::context) "host_reader" (bool host)
                          "form" (syntax form)) *sources*)
               form))))
    (if host (get-form) (ccl-census-stub::with-target-state #'get-form))))
(defun observed-helper (name input answer)
  (push (obj "helper" name "phase" *phase* "event" *event* "input" (syntax input) "answer" (bool answer)
             "target" (ccl-source-traversal::context)) *calls*)
  answer)
(defun build-eql (helper range macro &optional host-range)
  (let* ((local (copy-tree (cdr helper)))
         (body (cddr local)))
    (setf (cddr local)
          `((let ((answer (block ccl::eql-iff-eq-p ,@body)))
              (observed-helper "EQL-IFF-EQ-P" ,(first (second local)) answer))))
    (ccl-census-macros::native-function
      `(lambda (form env)
         (let ((*event* (if (equal *phase* "dumplisp") (1- ccl-source-expanders::*next-event*) :null)))
         (flet (,@(unless host-range `((ccl::fixnump ,@(cddr range)))))
           (flet (,local)
             (funcall (function ,(ccl::parse-macro-1 (second macro) (third macro) (cdddr macro))) form env))))))))
(defun build-stream (helper macro)
  (let* ((local (copy-tree (cdr helper))) (body (cddr local)))
    (setf (cddr local)
          `((let ((answer (progn ,@body)))
              (push (obj "helper" "NX-LOOKUP-TARGET-UVECTOR-SUBTAG" "phase" *phase* "event" *event*
                         "input" (syntax ,(first (second local))) "value" answer
                         "target" (ccl-source-traversal::context)) *calls*)
              answer)))
    (ccl-census-macros::native-function
      `(lambda (form env)
         (let ((*event* (if (equal *phase* "dumplisp") (1- ccl-source-expanders::*next-event*) :null)))
         (flet (,local)
           (funcall (function ,(ccl::parse-macro-1 (second macro) (third macro) (cdddr macro))) form env)))))))
(defun compiler-entry (name)
  (or (find-if (lambda (r) (and (eq name (first r)) (equal (second r) "compiler-macro"))) ccl-source-expanders::*registry*)
      (error "HELPER-MACRO-BINDING-MISSING")))
(defun operators (form)
  (let ((rows nil))
    (labels ((visit (x)
               (cond ((ccl::acode-p x)
                      (push (label (ccl::acode-operator-name (ccl::acode-operator x))) rows)
                      (visit (ccl::acode-operands x)))
                     ((consp x) (visit (car x)) (visit (cdr x))))))
      (visit form))
    (nreverse rows)))
(defun probes (eql-entry stream-entry)
  (let ((rows nil) (*phase* "probe"))
    (ccl-census-descriptions::with-descriptions
      (lambda ()
        (ccl-census-stub::with-target-state
          (lambda ()
            (dolist (spec '(("zero" 0) ("maximum-fixnum" 536870911) ("minimum-fixnum" -536870912)
                            ("positive-boxed-integer" 536870912) ("negative-boxed-integer" -536870913)
                            ("large-integer" 1152921504606846976) ("single-float" 1.0f0) ("double-float" 1.0d0)))
              (let* ((form `(eql ccl::x ,(second spec))) (result (funcall (third eql-entry) form nil))
                     (afunc (ccl-source-expanders::with-routing
                              (lambda () (ccl-census-stub::capture-lambda `(lambda (ccl::x) ,form) 'ccl::helper-probe)))))
                (push (obj "name" (first spec) "input" (syntax form) "expansion" (syntax result)
                           "returned_input" (bool (eq result form)) "operators" (operators (ccl::afunc-acode afunc))
                           "function" (ccl-startup-census::function-observation afunc)) rows)))
            (dolist (tag '(50 122))
              (let* ((pair (assoc :basic-stream (arch::target-uvector-subtags wasm-census::*census-arch*))) (old (cdr pair)))
                (unwind-protect
                  (progn
                    (setf (cdr pair) tag)
                    (let* ((form '(ccl::basic-stream-p ccl::x))
                           (result (if (equal *mode* "host-subtag")
                                     (let ((ccl::*target-backend* ccl::*host-backend*)) (funcall (third stream-entry) form nil))
                                     (funcall (third stream-entry) form nil))))
                      (push (obj "name" "stream-subtag" "tag" tag "expansion" (syntax result)) rows)))
                  (setf (cdr pair) old))))))))
    (nreverse rows)))
(defun descriptor-probes (eql-entry stream-entry)
  (let ((rows nil) (*phase* "descriptor-probe"))
    (ccl-census-descriptions::with-descriptions
      (lambda ()
        (ccl-census-stub::with-target-state
          (lambda ()
            (let* ((arch wasm-census::*census-arch*)
                   (low (arch::target-most-negative-fixnum arch))
                   (high (arch::target-most-positive-fixnum arch))
                   (subtags (arch::target-uvector-subtags arch)))
              (push (obj "name" "target-range" "word_bits" (arch::target-nbits-in-word arch)
                         "fixnum_shift" (arch::target-fixnum-shift arch) "low" low "high" high) rows)
              (unwind-protect
                (progn
                  (setf (arch::target-most-negative-fixnum arch) -8 (arch::target-most-positive-fixnum arch) 7)
                  (push (obj "name" "alternate-range" "expansion"
                             (syntax (funcall (third eql-entry) '(eql ccl::x 8) nil))) rows))
                (setf (arch::target-most-negative-fixnum arch) low (arch::target-most-positive-fixnum arch) high))
              (let ((problem nil))
                (unwind-protect
                  (progn
                    (setf (arch::target-uvector-subtags arch) (remove :basic-stream subtags :key #'car))
                    (setf problem
                      (handler-case (progn (funcall (third stream-entry) '(ccl::basic-stream-p ccl::x) nil) nil)
                        (error (e) (princ-to-string e)))))
                  (setf (arch::target-uvector-subtags arch) subtags))
                (push (obj "name" "missing-subtag" "condition" problem
                           "restored_expansion" (syntax (funcall (third stream-entry) '(ccl::basic-stream-p ccl::x) nil))) rows))
              (unless (and (= low (arch::target-most-negative-fixnum arch))
                           (= high (arch::target-most-positive-fixnum arch))
                           (eq subtags (arch::target-uvector-subtags arch)))
                (error "HELPER-DESCRIPTOR-RESTORATION")))))))
    (reverse rows)))
(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (ccl-source-expanders::*registry* nil) (ccl-source-expanders::*compiled* nil)
        (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0) (ccl-source-expanders::*literals* nil)
        (*sources* nil) (*calls* nil) (*mode* (or (ccl:getenv "CCL_HELPER_MODE") "normal"))
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
        (old-eql (fdefinition 'ccl::eql-iff-eq-p)) (old-lookup (fdefinition 'ccl::nx-lookup-target-uvector-subtag)))
    (ccl-source-expanders::prepare)
    (dolist (r (reverse ccl-source-expanders::*registry*)) (ident (third r)) (ident (fourth r)))
    (let* ((helper (read-form "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
           (host-helper (read-form "compiler/optimizers.lisp" "defun eql-iff-eq-p" t))
           (range (read-form "compiler/nx0.lisp" "defun nx1-target-fixnump"))
           (lookup (read-form "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
           (eql-form (read-form "compiler/optimizers.lisp" "define-compiler-macro eql"))
           (stream-form (read-form "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
           (vector-form (read-form "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
           (eql-entry (compiler-entry 'eql)) (stream-entry (compiler-entry 'ccl::basic-stream-p))
           (vector-entry (compiler-entry 'vectorp))
           (rebuilt nil) (wrong-reader nil) (wrong-range nil) (stream nil) (vector nil))
      (ccl-source-expanders::with-compiler-observation
        (lambda ()
          (setf rebuilt (build-eql helper range eql-form)
                wrong-reader (build-eql host-helper range eql-form)
                wrong-range (build-eql helper range eql-form t)
                stream (build-stream lookup stream-form)
                vector (build-stream lookup vector-form))))
      (dolist (fn (list rebuilt wrong-reader wrong-range stream vector)) (ident fn))
      (setf (third eql-entry) (cond ((equal *mode* "inherited") (third eql-entry))
                                    ((equal *mode* "host-reader") wrong-reader)
                                    ((equal *mode* "host-range") wrong-range) (t rebuilt)))
      (setf (third stream-entry) stream (third vector-entry) vector)
      ;; Traverse before probe-specific compilation, preserving the same native
      ;; identity-allocation prefix for source and inherited helper modes.
      (let ((*phase* "dumplisp")) (ccl-source-expanders::with-routing #'ccl-census-descriptions::run))
      (let ((probe-results
              (let ((ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
                    (ccl-source-expanders::*literals* nil))
                (append (probes eql-entry stream-entry) (descriptor-probes eql-entry stream-entry)))))
        (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                     (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                     (eq old-eql (fdefinition 'ccl::eql-iff-eq-p))
                     (eq old-lookup (fdefinition 'ccl::nx-lookup-target-uvector-subtag)))
          (error "HELPER-STATE-NOT-RESTORED"))
        (with-open-file (out (ccl:getenv "CCL_HELPER_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
          (ccl-startup-census::json
            (obj "version" 1 "sources" (reverse *sources*) "probes" probe-results
                 "calls" (reverse *calls*) "events" ccl-source-expanders::*events*
                 "selected_entries" (loop for entry in (list eql-entry stream-entry vector-entry)
                                          collect (obj "operator" (label (first entry)) "selected_id" (ident (third entry))))
                 "compiled" (loop for fn in (list rebuilt wrong-reader wrong-range stream vector)
                                  collect (obj "id" (ident fn) "function" (cdr (assoc fn ccl-source-expanders::*compiled* :test #'eq))))
                 "restored" :true "global_helpers_unchanged" :true "macro_environment_qualified" :false
                 "graph_edges_replaced" 0) out)
          (terpri out))))))
