    (defun core-cpl-select (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)))
        (core-collect)
        (handler-case (progn (signal condition) :unhandled)
          (cpl-diamond () :diamond)
          (cpl-left () :left)
          (cpl-right () :right)
          (error () :error))))

    (defun core-cpl-decline (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)) (trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (push :outer trace))))
          (handler-bind ((cpl-left (lambda (c)
                                     (declare (ignore c))
                                     (core-collect)
                                     (push :left trace)))
                         (cpl-right (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (push :right trace))))
            (signal condition)))
        (reverse trace)))

    (defun core-cpl-types (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)))
        (core-collect)
        (values (typep condition 'cpl-left)
                (typep condition 'cpl-right)
                (typep condition 'cpl-diamond)
                (typep condition 'error)
                (typep condition 'warning))))

    (defun core-cpl-restart (image)
      (core-condition-prepare image)
      (let ((condition (svref image 2)) (cleaned nil))
        (values
          (handler-bind ((condition (lambda (c)
                                      (declare (ignore c))
                                      (core-collect)
                                      (invoke-restart 'use-value 37))))
            (restart-case
                (unwind-protect (error condition)
                  (core-collect)
                  (setq cleaned t))
              (use-value (value) value)))
          cleaned)))

    (defun core-cpl-construct (image)
      (core-condition-prepare image)
      (let ((condition (make-condition 'type-error :datum (list 17)
                                                 :expected-type 'integer)))
        (core-collect)
        (handler-case (error condition)
          (cpl-left () :wrong)
          (type-error (c)
            (core-collect)
            (values (type-error-datum c) (type-error-expected-type c)
                    (typep c 'error))))))

    (defun core-cpl-resignal (image)
      (core-condition-prepare image)
      (let ((trace nil))
        (handler-bind ((condition (lambda (c)
                                    (declare (ignore c))
                                    (core-collect)
                                    (push :outer trace))))
          (handler-bind ((condition (lambda (c)
                                      (push :inner trace)
                                      (signal c)
                                      (core-collect)
                                      (push :returned trace))))
            (signal (svref image 2))))
        (reverse trace)))

    (defun core-condition-prepare (image)
      #+wasm32-target
      (setq ccl::*class-table* (svref image 0)
            ccl::%find-classes% (svref image 3)
            ccl::*initialization-invalidation-alist* (first (svref image 12))
            ccl::*standard-class-wrapper* (second (svref image 12))
            ccl::*standard-effective-slot-definition-class-wrapper* (third (svref image 12))
            ccl::*error-format-strings* (fourth (svref image 12))
            ccl::*eql-specializer-class* (svref image 4)
            ccl::*standard-class-class* (svref image 5)
            ccl::*standard-generic-function-class* (find-class 'standard-generic-function)
            ccl::*clos-initialization-functions* nil)
      #+wasm32-target (ccl::compute-dcode #'ccl::eql-specializer-object)
      #+wasm32-target
      (dolist (gf (svref image 8)) (ccl::compute-dcode gf))
      image)

    (defun core-condition-create (image)
      (core-condition-prepare image)
      (let ((condition (apply #'make-condition (svref image 6) (svref image 7))))
        (core-collect)
        (values (typep condition 'condition) (typep condition 'error)
                (typep condition 'warning) (slot-value condition 'payload))))

    (defun core-condition-signal-string (image)
      (core-condition-prepare image)
      (handler-case (signal "condition ~s" (progn (core-collect) (list 19)))
        (simple-condition (condition)
          (core-collect)
          (values (simple-condition-format-control condition)
                  (simple-condition-format-arguments condition)))))

    (defun core-condition-signal-symbol (image)
      (core-condition-prepare image)
      (handler-case (signal 'cpl-diamond :payload (progn (core-collect) (list 29)))
        (cpl-left (condition)
          (core-collect)
          (values (slot-value condition 'payload) (typep condition 'cpl-right)))))

    (defun core-condition-spread (image)
      (core-condition-prepare image)
      (let ((arguments (list :datum (list 17) :expected-type 'integer)))
        (core-collect)
        (handler-case (apply #'error 'type-error arguments)
          (type-error (condition)
            (core-collect)
            (values (type-error-datum condition) (type-error-expected-type condition))))))

    (defun core-condition-initargs (image)
      (core-condition-prepare image)
      (handler-case
          (let ((condition (apply #'make-condition 'cpl-left (svref image 7))))
            (core-collect)
            (values :made (slot-value condition 'payload)))
        (program-error () :bad-initargs)))

    (defun core-condition-slots (image)
      (core-condition-prepare image)
      (let ((condition (make-condition 'cpl-left)))
        (core-collect)
        (setf (slot-value condition 'payload) (list 31))
        (core-collect)
        (values (slot-value condition 'payload) (slot-boundp condition 'payload))))

    (defun core-condition-unlisted (image)
      (core-condition-prepare image)
      (handler-case
          (error 'ccl::simple-destructuring-error :format-control "unlisted ~s"
                                                :format-arguments (list 47))
        (ccl::simple-destructuring-error (condition)
          (core-collect)
          (values (simple-condition-format-control condition)
                  (simple-condition-format-arguments condition)
                  (typep condition 'program-error)))))

    (defun core-condition-cerror (image)
      (core-condition-prepare image)
      (let ((payload nil) (cleaned nil))
        (values
          (handler-bind ((cpl-left (lambda (condition)
                                    (setq payload (slot-value condition 'payload))
                                    (core-collect)
                                    (invoke-restart 'continue))))
            (unwind-protect (cerror "Continue" 'cpl-diamond :payload (list 53))
              (setq cleaned t)))
          payload cleaned)))

    (defun core-condition-indirect (image)
      (core-condition-prepare image)
      (let ((signaller (car (list #'signal))) (effects nil))
        (handler-bind ((simple-condition
                         (lambda (condition)
                           (core-collect)
                           (push (simple-condition-format-arguments condition) effects))))
          (funcall signaller "indirect ~s" (progn (push :argument effects) 59)))
        effects))

    (defun core-condition-class-cell (image)
      (core-condition-prepare image)
      (let* ((cell (gethash 'cpl-other ccl::%find-classes%))
             (old (ccl::class-cell-class cell)))
        (unwind-protect
            (progn
              (setf (ccl::class-cell-class cell) (find-class 'cpl-left))
              (core-collect)
              (let ((condition (make-condition 'cpl-other)))
                (values (slot-value condition 'payload)
                        (typep condition 'cpl-other))))
          (setf (ccl::class-cell-class cell) old))))
