(module
  (type $entry (func (param i32) (result i32)))
  (import "host" "observed" (func $observed (param i32)))
  (memory 1 1)
  (table 5 5 funcref)
  (func $leaf (type $entry) (param $mode i32) (result i32)
    (call $observed (i32.const 900))
    (if (i32.eq (local.get $mode) (i32.const 1)) (then unreachable))
    (if (i32.eq (local.get $mode) (i32.const 2))
      (then (drop (i32.load (i32.const 65536)))))
    (if (i32.eq (local.get $mode) (i32.const 3))
      (then (drop (i32.div_s (i32.const 1) (i32.const 0)))))
    (i32.add (local.get $mode) (i32.const @BIAS@)))
  (func $inner (type $entry) (param $mode i32) (result i32)
    (call $leaf (local.get $mode)))
  (func $outer (export "invoke") (type $entry) (param $mode i32) (result i32)
    (call $inner (local.get $mode)))
  (func $wrong (result i64) (i64.const 9))
  (func $indirect (export "indirect") (type $entry) (param $slot i32) (result i32)
    (i32.const 0) (local.get $slot) (call_indirect (type $entry)))
  (elem (i32.const 0) $leaf $inner $outer $wrong $indirect))
