(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(load (merge-pathnames "consumers.lisp" *load-pathname*))
(load (merge-pathnames "lower.lisp" *load-pathname*))
(in-package :wasm32-compiler)
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil)
       (cases (append ccl::*population-runtime-entries* (mapcar (lambda (row) (list (car row) (ccl::lower-population-consumer (cadr row)))) ccl::*population-consumer-cases*)))
       (names (append (mapcar #'car cases) '("pop_raw_get" "pop_raw_set" "pop_raw_type" "pop_gc"))))
 (with-open-file (s (concatenate 'string out "lowered.lisp") :direction :output :if-exists :error) (let ((*print-circle* t)) (pprint cases s)))
 (dolist (row cases)
  (let ((result (compile-call-form
          (sublis (mapcar (lambda (name) (cons (intern (string-upcase name) "CCL") (intern (string-upcase name) "WASM32-COMPILER"))) names) (cadr row))
          (car row) names)))
   (dolist (m (cons result (getf result :children)))
    (push m modules)
    (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
 (setq modules (nreverse modules))
 (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
  (format s "[") (loop for m in modules for i from 0 do (unless (zerop i) (format s ",")) (format s "{\"name\":~s}" (getf m :name))) (format s "]"))
 (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules))))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
