(in-package :ccl)
(defparameter *population-consumer-cases*
 '(("pc_type" (lambda (p a b log) (declare (ignore a b log)) (population-type p)))
   ("pc_contents" (lambda (p a b log) (declare (ignore a b log)) (population-contents p)))
   ("pc_set" (lambda (p a b log) (declare (ignore log)) (let ((list (cons b (cons a nil)))) (values (eq (setf (population-contents p) list) list) (eq (population-contents p) list)))))
   ("pc_push" (lambda (p a b log) (declare (ignore a log)) (push b (population-contents p))))
   ("pc_internal" (lambda (p a b log) (declare (ignore a log)) (push b (population-data p))))
   ("pc_effects" (lambda (p a b log) (declare (ignore a))
      (push (progn (rplaca log (cons 7 (car log))) b) (population-contents (progn (rplaca log (cons 9 (car log))) p)))
      (values (car log) (cdr log))))
   ("pc_set_effects" (lambda (p a b log) (declare (ignore a))
      (setf (population-contents (progn (rplaca log (cons 9 (car log))) p)) (progn (rplaca log (cons 7 (car log))) (cons b nil)))
      (values (car log) (cdr log))))
   ("pc_function" (lambda (p a b log) (declare (ignore a b log)) (funcall #'population-contents p)))
   ("pc_apply" (lambda (p a b log) (declare (ignore a b log)) (apply #'population-type (cons p nil))))
   ("pc_copy" (lambda (p a b log) (declare (ignore a b log))
      (labels ((copy-members (x) (if x (cons (car x) (copy-members (cdr x))) nil)))
       (let ((old (population-contents p))) (setf (population-contents p) (copy-members old)) (values (eq old (population-contents p)) (population-contents p))))))
   ("pc_collect" (lambda (p a b log) (declare (ignore a log))
      (let ((saved (population-contents p))) (pop_gc nil nil nil) (push b (population-contents p)) (values (eq saved (cdr (population-contents p))) (population-contents p)))))
   ("pc_closure" (lambda (p a b log) (declare (ignore a log))
      (let ((read (lambda () (population-contents p)))) (pop_gc nil nil nil) (push b (population-contents p)) (funcall read))))
   ("pc_cleanup" (lambda (p a b log) (declare (ignore a log))
      (multiple-value-prog1 (values (population-type p) (population-contents p))
       (unwind-protect (pop_gc nil nil nil) (push b (population-contents p))))))
   ("pc_exit" (lambda (p a b log) (declare (ignore a log))
      (catch '17 (unwind-protect (throw '17 (population-contents p)) (pop_gc nil nil nil) (push b (population-data p))))))
   ("pc_clear" (lambda (p a b log) (declare (ignore a b log)) (setf (population-contents p) nil)))
   ("pc_defaults" (lambda (p a b log) (declare (ignore a log))
      (flet ((add (&optional (old (population-data p))) (setf (population-data p) (cons b old)))) (add))))))
