(in-package :ccl)
;; Selected runtime-consumer lowering; not a global compiler/source admission change.
(defun lower-population-consumer (form)
 (labels ((api (x) (member x '(population-contents population-data population-type)))
          (normalize (x)
           (cond ((atom x) (if (eq x 'population-data) 'population-contents x))
                 ((eq (car x) 'quote) x) (t (mapcar #'normalize x))))
          (walk (x)
           (cond ((atom x) x) ((eq (car x) 'quote) x)
            ((and (eq (car x) 'declare) (every (lambda (d) (eq (car d) 'ignore)) (cdr x))) nil)
            ((and (member (car x) '(flet labels)) (some (lambda (d) (api (car d))) (cadr x))) (error "population API shadow unsupported"))
            ((and (member (car x) '(push setf))
                  (consp (if (eq (car x) 'push) (caddr x) (cadr x)))
                  (eq (car (if (eq (car x) 'push) (caddr x) (cadr x))) 'population-contents))
             (when (and (eq (car x) 'setf) (/= (length x) 3)) (error "multi-place population SETF unsupported"))
             (walk (macroexpand-1 x)))
            ((equal (subseq x 0 (min 2 (length x))) '(funcall #'(setf population-contents)))
             (cons 'pop_set_contents (mapcar #'walk (cddr x))))
            ((eq (car x) 'population-contents) (cons 'pop_contents (mapcar #'walk (cdr x))))
            ((eq (car x) 'population-type) (cons 'pop_kind (mapcar #'walk (cdr x))))
            ((and (eq (car x) 'function) (api (cadr x))) (list 'function (if (eq (cadr x) 'population-type) 'pop_kind 'pop_contents)))
            (t (mapcar #'walk x)))))
  (walk (normalize form))))
(defparameter *population-runtime-entries*
 '(("pop_contents" (lambda (population) (pop_raw_get population nil nil)))
   ("pop_set_contents" (lambda (value population) (pop_raw_set population value nil)))
   ("pop_kind" (lambda (population) (if (eq (pop_raw_type population nil nil) 0) :list :alist)))))
