(in-package :ccl)
(load (getenv "POP_CONSUMERS"))
(defun pop_gc (a b c) (declare (ignore a b c)) (gc) nil)
(defvar *consumer-roots* nil)
(defun population-json (x s)
 (cond ((null x) (format s "\"nil\"")) ((eq x t) (format s "\"t\""))
       ((eq x :list) (format s "\"list\"")) ((eq x :alist) (format s "\"alist\""))
       ((integerp x) (format s "~d" x))
       ((consp x) (format s "[") (population-json (car x) s) (format s ",") (population-json (cdr x) s) (format s "]"))
       (t (error "unexpected native result ~s" x))))
(with-open-file (s (getenv "POP_NATIVE") :direction :output :if-exists :error)
 (format s "[")
 (loop for type in '(:list :alist) for ti from 0 do
  (loop for row in *population-consumer-cases* for ri from 0 do
   (let* ((a (cons 17 23)) (b (cons 31 37)) (log (cons 0 0))
          (p (make-population :type type :initial-contents (if (eq type :list) (list a b) (list (cons a b)))))
          (*consumer-roots* (list p a b log))
          (values (multiple-value-list (funcall (compile nil (cadr row)) p a b log))))
    (unless (and (zerop ti) (zerop ri)) (format s ","))
    (format s "{\"name\":~s,\"type\":~s,\"values\":[" (car row) (string-downcase (symbol-name type)))
    (loop for value in values for i from 0 do (unless (zerop i) (format s ",")) (population-json value s))
    (format s "],\"contents\":") (population-json (population-contents p) s)
    (format s ",\"log\":") (population-json log s) (format s "}"))))
 (format s "]"))
(quit)
