(func $binding_index (param $symbol i32) (result i32) (local $index i32)
 (if (i32.or (i32.ne (i32.and (local.get $symbol) (i32.const 7)) (i32.const 6)) (i32.lt_u (local.get $symbol) (i32.const 6))) (then (throw $call_error (i32.const 11))))
 (if (i64.gt_u (i64.add (i64.extend_i32_u (local.get $symbol)) (i64.const 26)) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))) (then (throw $call_error (i32.const 11))))
 (if (i32.ne (i32.load (i32.sub (local.get $symbol) (i32.const 6))) (i32.const 1850)) (then (throw $call_error (i32.const 11))))
 (local.set $index (i32.load offset=22 (local.get $symbol)))
 (if (i32.or (i32.and (local.get $index) (i32.const 3)) (i32.lt_s (local.get $index) (i32.const 0))) (then (throw $call_error (i32.const 11))))
 (i32.shr_u (local.get $index) (i32.const 2)))
(func $binding_vector_check (param $base i32) (param $cap i32)
 (if (i32.or (i32.gt_u (local.get $cap) (i32.const 16777215)) (i32.and (local.get $base) (i32.const 3))) (then (throw $call_error (i32.const 11))))
 (if (i32.and (i32.ne (local.get $cap) (i32.const 0)) (i32.eqz (local.get $base))) (then (throw $call_error (i32.const 11))))
 (if (i64.gt_u (i64.add (i64.extend_i32_u (local.get $base)) (i64.mul (i64.extend_i32_u (local.get $cap)) (i64.const 4))) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16))) (then (throw $call_error (i32.const 11)))))
(func $dynamic_slot (param $symbol i32) (result i32)
 (local $index i32) (local $base i32) (local $cap i32) (local $newcap i32) (local $p i32) (local $i i32) (local $end i64)
 (local.set $index (call $binding_index (local.get $symbol)))
 (if (i32.eqz (local.get $index)) (then (throw $call_error (i32.const 11))))
 (local.set $base (i32.load offset=104 (global.get $tcr))) (local.set $cap (i32.load offset=108 (global.get $tcr)))
 (call $binding_vector_check (local.get $base) (local.get $cap))
 (if (i32.ge_u (local.get $index) (local.get $cap)) (then
  ;; No calls or polls from allocation preflight through publication. The TCR
  ;; roots the old vector throughout. Failure writes nothing; collection only
  ;; sees either complete old state or complete new state at a legal safepoint.
  (if (i32.ge_u (local.get $index) (i32.const 16777215)) (then (throw $call_error (i32.const 3))))
  (local.set $newcap (i32.const 16))
  (block $capacity_done (loop $capacity_loop
   (br_if $capacity_done (i32.gt_u (local.get $newcap) (local.get $index)))
   (local.set $newcap (i32.shl (local.get $newcap) (i32.const 1)))
   (if (i32.gt_u (local.get $newcap) (i32.const 16777215)) (then (local.set $newcap (i32.const 16777215))))
   (br $capacity_loop)))
  (local.set $p (i32.load offset=48 (global.get $tcr)))
  (local.set $end (i64.and (i64.add (i64.extend_i32_u (local.get $p)) (i64.add (i64.mul (i64.extend_i32_u (local.get $newcap)) (i64.const 4)) (i64.const 11))) (i64.const -8)))
  (if (i32.or (i32.and (local.get $p) (i32.const 7)) (i32.lt_u (local.get $p) (i32.load offset=56 (global.get $tcr)))) (then (throw $call_error (i32.const 3))))
  (if (i32.or (i64.gt_u (local.get $end) (i64.extend_i32_u (i32.load offset=52 (global.get $tcr)))) (i64.gt_u (local.get $end) (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))) (then (throw $call_error (i32.const 3))))
  ;; An owner must not alias the allocation area with its existing vector.
  (if (i32.and (i64.lt_u (i64.extend_i32_u (local.get $p)) (i64.add (i64.extend_i32_u (local.get $base)) (i64.mul (i64.extend_i32_u (local.get $cap)) (i64.const 4)))) (i64.gt_u (local.get $end) (i64.extend_i32_u (local.get $base)))) (then (throw $call_error (i32.const 11))))
  (i32.store (local.get $p) (i32.or (i32.shl (local.get $newcap) (i32.const 8)) (i32.const 250)))
  (memory.copy (i32.add (local.get $p) (i32.const 4)) (local.get $base) (i32.mul (local.get $cap) (i32.const 4)))
  (local.set $i (local.get $cap))
  (block $fill_done (loop $fill
   (br_if $fill_done (i32.ge_u (local.get $i) (local.get $newcap)))
   (i32.store (i32.add (local.get $p) (i32.add (i32.const 4) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 243))
   (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $fill)))
  (i32.store (i32.sub (i32.wrap_i64 (local.get $end)) (i32.const 4)) (i32.const 243))
  (i32.store offset=48 (global.get $tcr) (i32.wrap_i64 (local.get $end)))
  (local.set $base (i32.add (local.get $p) (i32.const 4)))
  (i32.store offset=104 (global.get $tcr) (local.get $base))
  (i32.store offset=108 (global.get $tcr) (local.get $newcap))))
 (i32.add (local.get $base) (i32.mul (local.get $index) (i32.const 4))))
(func $special_location (param $symbol i32) (result i32) (local $index i32) (local $base i32) (local $cap i32) (local $slot i32)
 (local.set $index (call $binding_index (local.get $symbol)))
 (local.set $base (i32.load offset=104 (global.get $tcr))) (local.set $cap (i32.load offset=108 (global.get $tcr)))
 (call $binding_vector_check (local.get $base) (local.get $cap))
 (if (i32.and (i32.ne (local.get $index) (i32.const 0)) (i32.lt_u (local.get $index) (local.get $cap))) (then
  (local.set $slot (i32.add (local.get $base) (i32.mul (local.get $index) (i32.const 4))))
  (if (i32.ne (i32.load (local.get $slot)) (i32.const 243)) (then (return (local.get $slot))))))
 (i32.add (local.get $symbol) (i32.const 2)))
(func $special_read (param $symbol i32) (result i32) (local $value i32)
 (local.set $value (i32.load (call $special_location (local.get $symbol))))
 (if (i32.eq (local.get $value) (i32.const 51)) (then (throw $call_error (i32.const 10)))) (local.get $value))
