export { createIdGenerator, initIdCounters, allocateId } from "./ids.mjs";
export {
  createWorkspace,
  createState,
  addTask,
  addWindow,
  addWidget,
  removeWindow,
  setActiveTask,
  archiveTask,
  closeTask,
  createSession,
  renameSession,
  openSession,
  saveSession,
  deleteSession,
  openSessionListWindow,
  refreshSessionListWindow,
  addPresentation,
  setLayout,
  setTheme,
  setThemeMode,
  initLayout,
  splitLayout,
  wrapInTabs,
  setActiveTab,
  dockLayout,
  recordEvent,
  appendRecording,
  appendRecordingEntry,
  attachRecordingAnchor,
  setRecordingEntryFolded,
  setRecordingCollapsed,
  pinWatch,
  unpinWatch,
  stageEdit,
  applyEditGroup,
  undoEditGroup,
  recordCommandInvocation,
  setCommandState,
  updateWidget,
  updateWindow,
  openInspectorWindow,
  refreshInspectorWindow,
  openTranscriptWindow,
  refreshTranscriptWindow,
  openCommandHistoryWindow,
  refreshCommandHistoryWindow,
  openProblemsWindow,
  refreshProblemsWindow,
  openCapabilityMediationWindow,
  refreshCapabilityMediationWindow,
  openDebuggerWindow,
  refreshDebuggerWindow,
  COMMAND_PALETTE_FILTER_COMMAND,
  COMMAND_PALETTE_EXECUTE_COMMAND,
  COMMAND_PALETTE_SELECT_NEXT_COMMAND,
  COMMAND_PALETTE_SELECT_PREV_COMMAND,
  COMMAND_PALETTE_EXECUTE_SELECTION_COMMAND,
  COMMAND_PALETTE_OPEN_COMMAND,
  COMMAND_PALETTE_CLOSE_COMMAND,
  KEYBINDINGS_OPEN_COMMAND,
  KEYBINDINGS_CLOSE_COMMAND,
  COMMAND_SURFACE_DISMISS_COMMAND,
  RECORDING_APPEND_COMMAND,
  RECORDING_ENTRY_APPEND_COMMAND,
  RECORDING_ANCHOR_ATTACH_COMMAND,
  RECORDING_ENTRY_FOLD_COMMAND,
  RECORDING_TOGGLE_COMMAND,
  RECORDING_COPY_AS_FORM_COMMAND,
  RECORDING_COPY_WITH_CONTEXT_COMMAND,
  RECORDING_REPLAY_AS_INPUT_COMMAND,
  RECORDING_RERUN_COMMAND,
  COMMAND_HISTORY_APPEND_COMMAND,
  COMMAND_HISTORY_OPEN_COMMAND,
  COMMAND_HISTORY_REFRESH_COMMAND,
  COMMAND_HISTORY_EXECUTE_COMMAND,
  INSPECTOR_WATCH_PIN_COMMAND,
  INSPECTOR_WATCH_UNPIN_COMMAND,
  INSPECTOR_EDIT_STAGE_COMMAND,
  INSPECTOR_EDIT_APPLY_COMMAND,
  INSPECTOR_EDIT_UNDO_COMMAND,
  TRANSCRIPT_OPEN_COMMAND,
  TRANSCRIPT_REFRESH_COMMAND,
  TRANSCRIPT_ITEM_OPEN_COMMAND,
  PROBLEMS_OPEN_COMMAND,
  PROBLEMS_REFRESH_COMMAND,
  PROBLEMS_ITEM_OPEN_COMMAND,
  DEBUGGER_RESTART_INVOKE_COMMAND,
  LIST_SELECTION_UPDATE_COMMAND,
  TASK_LIST_COMMAND,
  TASK_SWITCH_COMMAND,
  TASK_CLOSE_COMMAND,
  TASK_ARCHIVE_COMMAND,
  SESSION_LIST_COMMAND,
  SESSION_REFRESH_COMMAND,
  SESSION_CREATE_COMMAND,
  SESSION_OPEN_COMMAND,
  SESSION_SAVE_COMMAND,
  SESSION_RENAME_COMMAND,
  SESSION_DELETE_COMMAND,
  LAYOUT_SPLIT_COMMAND,
  LAYOUT_TABS_COMMAND,
  LAYOUT_DOCK_COMMAND,
  LAYOUT_SET_ACTIVE_TAB_COMMAND,
  CAPABILITY_REQUEST_COMMAND,
  CAPABILITY_GRANT_COMMAND,
  CAPABILITY_REVOKE_COMMAND,
  CAPABILITY_OPEN_PANEL_COMMAND,
  CAPABILITY_SELECT_COMMAND,
  CAPABILITY_APPROVE_COMMAND,
  CAPABILITY_DENY_COMMAND,
  CAPABILITY_AUTO_RUN_COMMAND,
  SAFE_MODE_ENABLE_COMMAND,
  SAFE_MODE_DISABLE_COMMAND,
  DOM_ESCAPE_COMMAND,
  raiseError,
  acknowledgeError,
  upsertJob,
  requestCapability,
  grantCapability,
  revokeCapability,
  evaluateCapabilityRequest,
  applyCapabilityDecision,
  autoRunCapabilityPolicy,
  setSafeMode,
  hasCapability,
  recordDomEscape,
  enqueueUiSignal,
  beginUiTurn,
  advanceUiTurn,
  yieldUiTurn,
  endUiTurn,
  setSelection,
  updateListSelection,
  setFocus,
  openCommandPaletteWindow,
  refreshCommandPaletteWindow,
  closeCommandPaletteWindow,
  openTaskListWindow,
  refreshTaskListWindow,
  applyCommandPaletteFilter,
  applyCommandPaletteSelection,
  resolveCommandPaletteSelection,
  applyCapabilityRequestSelection,
  resolveCapabilityRequestSelection,
  registerCommandPaletteCommands,
  registerTaskCommands,
  registerSessionCommands,
  registerLayoutCommands,
  registerListSelectionCommands,
  registerRecordingCommands,
  registerTranscriptCommands,
  registerCommandHistoryCommands,
  registerInspectorCommands,
  registerProblemsCommands,
  registerDebuggerCommands,
  registerCapabilityCommands,
  registerDomEscapeCommands,
  registerCommandSurfaceCommands,
  bindCommandPaletteDefaults,
  bindCommandSurfaceDefaults,
  openKeybindingWindow,
  refreshKeybindingWindow,
  closeKeybindingWindow
} from "./state.mjs";
export {
  createRegistry,
  registerCommand,
  normalizeCommand,
  getCommand,
  bindKey,
  resolveKey,
  resolveKeyWithTrace,
  registerPresentationTranslator,
  resolvePresentationCommand,
  executePresentationCommand,
  commandEnabled,
  executeCommand
} from "./commands.mjs";
export { makeContext } from "./context.mjs";
export {
  FOCUS_REASONS,
  normalizeFocusTarget,
  sameFocusTarget,
  resolveFocusTargetFromElement,
  reconcileFocus
} from "./focus.mjs";
export { normalizeLayout, createLayout } from "./layout.mjs";
export { normalizeSelection } from "./selection.mjs";
export {
  DEFAULT_THEME_TOKENS,
  DARK_THEME_TOKENS,
  LIGHT_THEME_TOKENS,
  normalizeThemeTokens,
  mergeThemeTokens,
  resolveFontString,
  themeToCssVars
} from "./theme.mjs";
export { normalizeRestart, normalizeConditionReport, RESTART_SAFETY_LEVELS } from "./conditions.mjs";
export { markPresentationStale, revalidatePresentations } from "./world-state.mjs";
export { DEFAULT_ACTIONS_BY_TYPE, buildSelectionActions } from "./selection-actions.mjs";
export {
  extractCommandOutput,
  formatClipboardText,
  dispatchCommandOutput,
  handleCommandResultEffects
} from "./command-effects.mjs";
export {
  OUTPUT_RECORDING_SCHEMA_VERSION,
  normalizeRecording,
  normalizeEntry,
  normalizeAnchor,
  createRecordingStore,
  normalizeRecordingStore,
  appendRecording as appendRecordingToStore,
  appendEntry as appendEntryToStore,
  attachAnchor as attachAnchorToStore,
  setEntryFolded as setEntryFoldedInStore,
  setRecordingCollapsed as setRecordingCollapsedInStore,
  copyAsForm,
  copyWithContext,
  replayAsInput,
  reRunRecording
} from "./recordings.mjs";
export {
  PRESENTATION_TAXONOMY_VERSION,
  PRESENTATION_TYPES,
  PRESENTATION_REQUIRED_METADATA,
  normalizePresentationType,
  validatePresentationMetadata,
  applyPresentationDefaults
} from "./presentation-taxonomy.mjs";
export {
  TYPED_COMMAND_MODEL_VERSION,
  ARG_TYPES,
  normalizeArgSpec,
  normalizeCommandSpec,
  normalizeInvocation,
  validateInvocation,
  resolveArgumentDefaults,
  materializeInvocation,
  executeTypedCommand
} from "./typed-commands.mjs";
export { createElement, createText, h, normalizeChildren } from "./vdom.mjs";
export { createRoot } from "./renderer.mjs";
export { renderWidget, renderWindow } from "./widgets.mjs";
export { createEventLog, normalizeEventLog, recordEvent as recordEventLog } from "./event-log.mjs";
export { buildScene, hitTestScene, normalizeSceneNode, flattenScene } from "../backends/canvas/scene.mjs";
export { createCanvasBackend, createCanvasRoot } from "../backends/canvas/renderer.mjs";
export { createMeasureCache } from "../backends/canvas/measure.mjs";
export { createWebGLBackend, createWebGLRoot } from "../backends/webgl/renderer.mjs";
export {
  createPersistenceManager
} from "./persistence/manager.mjs";
export {
  createSnapshot,
  restoreStateFromSnapshot,
  sanitizeState
} from "./persistence/serialize.mjs";
export {
  createMemoryStore,
  createIndexedDBStore
} from "./persistence/storage.mjs";
export { SCHEMA_VERSION as PERSISTENCE_SCHEMA_VERSION } from "./persistence/schema.mjs";
