(in-package :wasm32-compiler)
(setq *validation-phase-start* (get-internal-real-time))
(core-execute-corpus (ccl:getenv "POOL_OUTPUT"))
(validation-execute-oracle (ccl:getenv "POOL_OUTPUT"))
(validation-phase-complete "oracle")
(load (merge-pathnames "worklist.lisp" *load-pathname*))
(library-measure-worklist)
(load (merge-pathnames "foreign-scan.lisp" *load-pathname*))
(host-foreign-inventory)
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "io-constants.sexp")
                   :direction :output :if-exists :error)
  (prin1 (list wasm32::io-seek-set wasm32::io-seek-cur wasm32::io-error-interrupted
               wasm32::io-error-file-exists wasm32::io-error-system-file-limit
               wasm32::io-error-process-file-limit) s))
(load (merge-pathnames "closure-controls.lisp" *load-pathname*))
(closure-controls (ccl:getenv "POOL_OUTPUT"))
(load (merge-pathnames "extra-controls.lisp" *load-pathname*))
(format t "VALIDATION-ORACLE-PASS~%")
(ccl:quit)
