(in-package :ccl)
(in-development-mode
  (load "ccl:lib;systems.lisp")
  (load "ccl:lib;compile-ccl.lisp")
  (dolist (name '(wasm32-arch wasm32-backend))
    (multiple-value-bind (binary sources) (find-module name (backend-name *host-backend*))
      (load (compile-file (car sources) :output-file binary))))
  (load (compile-file "ccl:lib;nfcomp.lisp" :output-file "ccl:bin;nfcomp.dx64fsl"))
  (load (compile-file "ccl:xdump;xfasload.lisp" :output-file "ccl:bin;xfasload.dx64fsl"))
  (load (compile-file "ccl:xdump;xwasm32-fasload.lisp" :output-file "ccl:bin;xwasm32fasload.dx64fsl")))

(let* ((out (getenv "CROSS_LOAD_OUTPUT"))
       (source "ccl:tests;wasm;stage1;cross-load;fixture.lisp")
       (fasl (concatenate 'string out "fixture.w32fsl")))
  (with-cross-compilation-target (:wasm32)
    (let ((*target-backend* (find-backend :wasm32)))
      (multiple-value-bind (path warnings failure)
          (compile-file source :target :wasm32 :output-file fasl :save-source-locations nil)
        (declare (ignore warnings))
        (assert (and path (not failure) (probe-file path))))))
  (load (compile-file source :output-file (concatenate 'string out "native.dx64fsl")))
  (with-open-file (s (concatenate 'string out "native.json")
                     :direction :output :if-exists :error)
    (wasm32-xload-json
     (list (list (car *wasm-loader-effect*) (cdr *wasm-loader-effect*))
           (let* ((value (wasm-loader-constant)) (pair (svref value 0)))
             (list (car pair) (cdr pair) (eq pair (svref value 1))))) s))
  (format t "FASL-PUBLICATION-PASS~%"))
(load (concatenate 'string (getenv "CROSS_LOAD_SOURCE") "guards.lisp"))
(quit)
