(in-package :ccl)
(in-development-mode
  (load "ccl:lib;systems.lisp")
  (load "ccl:lib;compile-ccl.lisp")
  (dolist (name '("wasm32-arch" "wasm32-backend" "nfcomp" "xfasload" "xwasm32fasload"))
    (load (concatenate 'string "ccl:bin;" name ".dx64fsl"))))
(let ((path (getenv "CROSS_LOAD_BAD_FILE"))
      (output (getenv "CROSS_LOAD_BAD_OUTPUT"))
      (expected (getenv "CROSS_LOAD_BAD_REASON"))
      (refused nil))
  (with-cross-compilation-target (:wasm32)
    (let ((*target-backend* (find-backend :wasm32)))
      (handler-case
          (if (equal (getenv "CROSS_LOAD_DUPLICATE") "yes")
            (xfasload output path path)
            (xfasload output path))
        (wasm32-compiler::unsupported-wasm32-code (condition)
          (assert (equal expected (symbol-name (wasm32-compiler::unsupported-operation condition))))
          (setq refused t)))))
  (assert refused)
  (assert (not (probe-file output)))
  (format t "FASL-REFUSAL-PASS ~a~%" expected))
(quit)
