;;; Re-evaluate U1's shared operator declaration and installation macro in
;;; private tables, with target reader features established before reading.
;;; This qualifies IDs/flags, not foreign-target machine-code execution.
(in-package "CCL-STARTUP-CENSUS")
(defun operator-row (id entry)
  (object "id" id "name" (if entry (label-of (car entry)) :null)
          "flags" (if entry (cadr entry) 0)
          "encoded" (if entry (gethash (car entry) ccl::*nx1-operators*) :null)))
(defun read-operator-declaration ()
  (let ((*package* (find-package "CCL")))
    (with-open-file (s "ccl:compiler;nxenv.lisp")
      (loop for form = (read s nil :eof) until (eq form :eof) do
        (when (and (consp form) (eq (first form) 'defparameter)
                   (eq (second form) 'ccl::*next-nx-operators*))
          (return-from read-operator-declaration form)))))
  (error "U1 operator declaration missing"))
(let ((profiles '((:ppc32 32 :ppc-target :big-endian-target)
                  (:ppc64 64 :ppc-target :big-endian-target)
                  (:x8632 32 :x86-target :little-endian-target)
                  (:x8664 64 :x86-target :little-endian-target)
                  (:arm 32 :arm-target :little-endian-target)))
      (rows nil)
      (native (loop for entry in (reverse ccl::*next-nx-operators*) for id from 0 collect (operator-row id entry))))
  (dolist (profile profiles)
    (destructuring-bind (arch bits family endian) profile
      (let* ((*features* (append (list family endian (intern (format nil "~a-TARGET" arch) "KEYWORD")
                                      (if (= bits 32) :32-bit-target :64-bit-target))
                                (set-difference *features* (ccl::backend-target-specific-features ccl::*host-backend*))))
             (declaration (read-operator-declaration))
             (ccl::*next-nx-operators* (eval (third declaration)))
             (installer (compile nil '(lambda () (ccl::next-nx-defops))))
             (ccl::*nx1-operators* (make-hash-table :test #'eq))
             (ccl::*acode-operator-types* (make-array 279)))
        (funcall installer)
        (let ((operators (loop for entry in (reverse ccl::*next-nx-operators*) for id from 0 collect (operator-row id entry))))
          (assert (equalp operators native))
          (push (object "architecture" (label-of arch) "word_bits" bits "operators" operators) rows)))))
  (with-open-file (s (ccl:getenv "S1_OPERATORS") :direction :output :if-exists :error)
    (json (object "scope" "Shared evaluated operator identities and flags for all five existing architectures; OS variants use this same global table. Foreign-target execution not claimed."
                  "architectures" (nreverse rows)) s) (terpri s)))
(format t "S1-OPERATORS-PASS~%")
(ccl:quit)
