(in-package :wasm32-compiler)

(let ((modules (make-hash-table :test #'equal)))
  (dolist (module (append *core-modules* *condition-cpl-modules*
                         (mapcar #'second *core-candidates*)))
    (dolist (entry (cons module (getf module :children)))
      (setf (gethash (getf entry :name) modules) entry)))
  (labels ((bind-owner (symbol id)
             (when id
               (unless (symbolp symbol) (error "Invalid retained owner: ~s" id))
               (let ((by-symbol (assoc symbol *pool-symbol-owners*))
                     (by-id (rassoc id *pool-symbol-owners* :test #'equal)))
                 (when (or (and by-symbol (not (equal (cdr by-symbol) id)))
                           (and by-id (not (eq (car by-id) symbol))))
                   (error "Conflicting retained symbol identity: ~s" id))
                 (unless by-id (push (cons symbol id) *pool-symbol-owners*))))))
    (with-open-file (stream (concatenate 'string (ccl:getenv "PROBE_OUTPUT") "bindings.lisp"))
      (dolist (binding (read stream))
        (destructuring-bind (name function imports) binding
          (let ((module (or (gethash name modules)
                            (error "Missing retained module: ~s" name))))
            (when (getf module :source-name)
              (bind-owner (ccl::maybe-setf-function-name (getf module :source-name)) function))
            (dolist (import imports)
              (destructuring-bind (wire owner) import
                (let ((entry (find wire (getf module :symbols) :key #'second :test #'equal)))
                  (unless entry (error "Missing retained import: ~s ~s" name wire))
                  (bind-owner (first entry) owner))))))))))

(with-open-file (stream (concatenate 'string (ccl:getenv "PROBE_OUTPUT") "owners.lisp"))
  (loop for (name package id) in (read stream) for i from 0 do
    (let ((old (rassoc id *pool-symbol-owners* :test #'equal)))
      (if old
        (assert (and (equal name (symbol-name (car old)))
                     (equal package (and (symbol-package (car old))
                                         (package-name (symbol-package (car old)))))))
        (progn
          (push (cons (if package (intern name package) (make-symbol name)) id)
                *pool-symbol-owners*))))))

;; FRONTEND-OWNER assigns the next numeric id from this list's length. Keep
;; the original ordering as well as EQ identity before appending anything.
(setq *pool-symbol-owners*
      (sort *pool-symbol-owners* #'> :key (lambda (entry) (parse-integer (cdr entry) :start 1))))

(defvar *validation-base-count*)
(defvar *validation-base-root-count*)
(defvar *validation-base-names*)
(with-open-file (stream (concatenate 'string (ccl:getenv "PROBE_OUTPUT") "base.lisp"))
  (destructuring-bind (count roots names) (read stream)
    (setq *validation-base-count* count
          *validation-base-root-count* roots
          *validation-base-names*
          (mapcar (lambda (id)
                    (car (or (rassoc id *pool-symbol-owners* :test #'equal)
                             (error "Unknown retained function identity: ~s" id))))
                  names))))

(defun validation-definition-names (file)
  (let ((*package* *package*) (names nil))
    (labels ((definition (form)
               (unless (consp form) (error "Probe toplevel form: ~s" form))
               (case (car form)
                 (in-package (setq *package* (find-package (second form))))
                 (defun (push (second form) names))
                 ((defmacro define-symbol-macro declaim) nil)
                 (progn (mapc #'definition (cdr form)))
                 (macrolet (mapc #'definition (cddr form)))
                 (eval-when
                  (unless (member :compile-toplevel (second form))
                    (error "A probe cannot silently omit load-time work."))
                  (mapc #'definition (cddr form)))
                 (otherwise (error "Probe toplevel work has no execution entry: ~s" (car form))))))
      (with-open-file (stream file)
        (loop for form = (read stream nil stream) until (eq form stream)
              do (definition form))))
    (unless (= (length names) (length (remove-duplicates names :test #'equal)))
      (error "Repeated probe definition."))
    names))

(defun validation-image-callee-p (name cases)
  ;; A projected GF is installed from the actual image graph, not from a
  ;; standalone module. Admit a direct edge only when an explicit input
  ;; carries that very GF in its protocol; a host FBOUNDP alone is not enough.
  (and (symbolp name) (fboundp name)
       (typep (fdefinition name) 'standard-generic-function)
       (some (lambda (entry)
               (some (lambda (input)
                       (some (lambda (argument)
                               (and (simple-vector-p argument)
                                    (> (length argument) 8)
                                    (gethash argument *generic-graphs*)
                                    (member (fdefinition name) (svref argument 8))))
                             input))
                     (second entry)))
             cases)))

(defun validation-native-row (name module input environment stream)
  (let* ((arguments (core-copy-input input))
         (bindings (core-copy-input environment))
         (input-json (with-output-to-string (s)
                       (loop for arg in arguments for i from 0 do
                         (unless (zerop i) (write-char #\, s))
                         (core-json-value arg s))))
         (globals-json (with-output-to-string (s) (core-json-value bindings s)))
         (globals-after nil)
         (values (call-with-witness-environment bindings
                   (lambda ()
                     (prog1 (multiple-value-list
                              (apply (gethash name *core-native-functions*) arguments))
                       (setq globals-after
                             (mapcar (lambda (pair)
                                       (cons (car pair) (symbol-value (car pair))))
                                     bindings)))))))
    (format stream "{\"name\":~s,\"definition\":~s,\"targetOnly\":false,\"args\":[~a],\"values\":["
            (getf module :name) (symbol-name name) input-json)
    (loop for value in values for i from 0 do
      (unless (zerop i) (write-char #\, stream)) (core-json-value value stream))
    (write-string "],\"after\":[" stream)
    (loop for arg in arguments for i from 0 do
      (unless (zerop i) (write-char #\, stream)) (core-json-value arg stream))
    (format stream "],\"globals\":~a,\"globalsAfter\":" globals-json)
    (core-json-value globals-after stream)
    (write-char #\} stream)))

;;; A probe batch starts from the saved compiler environment. The submitted
;;; file is compiled by FCOMP in both modes, including its local macros.
(defun validation-probes (file inputs out class-mode)
  (let* ((*core-modules* nil) (*core-records* nil) (*core-files* nil)
         (*validation-wire-prefix* "probe")
         (*b-cpl-conditions* class-mode)
         (definitions (validation-definition-names file))
         (base-names *validation-base-names*))
    ;; FCOMP's returned functions can contain unresolved LOAD-TIME-VALUE
    ;; records. The native oracle must load a real FASL before calling them.
    (let ((fasl (compile-file file :output-file (concatenate 'string out "native.dx64fsl")
                              :verbose nil :print nil)))
      (unless fasl (error "Native probe compilation failed."))
      (load fasl :verbose nil :print nil)
      (dolist (name definitions)
        (setf (gethash name *core-native-functions*) (fdefinition name))))
    (core-compile-file file)
    (let ((modules (remove-if-not (lambda (m) (member (getf m :source-name) definitions))
                                  (nreverse *core-modules*))))
      (unless (and modules (= (length modules) (length definitions)))
        (error "The probe file has an uncompiled definition."))
      (dolist (record (remove-if-not (lambda (r) (member (second r) definitions)) *core-records*))
        (unless (eq (fourth record) :admitted)
          (error "Probe compilation refused: ~s" record)))
      (dolist (module modules)
        (let ((name (getf module :source-name)))
          (unless (and name (symbolp name)) (error "A probe needs a named definition: ~s" name))
          (when (member name base-names)
            (error "A probe may not replace a retained definition: ~s" name))
          (setf (fdefinition name) (gethash name *core-native-functions*))))
      (dolist (module modules)
        (dolist (name (getf module :dependencies))
          (when (and (symbolp name) (not (fboundp name))
                     (eq (symbol-package name) (find-package :wasm32-compiler)))
            (let ((function (gethash name *core-native-functions*)))
              (when function (setf (fdefinition name) function))))))
      (load inputs)
      (let* ((cases (funcall (or (find-symbol "VALIDATION-PROBE-CASES" :wasm32-compiler)
                                (error "Missing probe input function."))))
             (names (mapcar #'car cases))
             (needed (copy-list names))
             (all (loop for m in modules append (cons m (getf m :children)))))
        (unless (and cases (= (length names) (length (remove-duplicates names))))
          (error "Probe entries must be explicit and distinct."))
        (dolist (name names)
          (unless (find name modules :key (lambda (m) (getf m :source-name)))
            (error "Inputs name an uncompiled probe: ~s" name)))
        (loop for count = (length needed) do
          (dolist (name (copy-list needed))
            (let ((module (find name modules :key (lambda (m) (getf m :source-name)))))
              (when module
                (dolist (callee (getf module :dependencies))
                  (unless (or (member callee base-names)
                              (find callee modules :key (lambda (m) (getf m :source-name)))
                              (validation-image-callee-p callee cases))
                    (error "Missing probe dependency: ~s" callee))
                  (pushnew callee needed)))))
          until (= count (length needed)))
        (dolist (module modules)
          (unless (member (getf module :source-name) names)
            (error "Compiled probe has no explicit execution entry: ~s"
                   (getf module :source-name))))
        (when (> (+ 8 *validation-base-count* (length all)) 4352)
          (error "The probe exceeds the code registry capacity."))
        (with-open-file (s (concatenate 'string out "probe-modules.json")
                           :direction :output :if-exists :error)
          (write-char #\[ s)
          (loop for m in all for i from 0 do
            (unless (zerop i) (write-char #\, s))
            (format s "{\"name\":~s,\"primitive\":false,\"cplMode\":~a,\"poolRoot\":~d,\"symbols\":["
                    (getf m :name) (if class-mode "true" "false")
                    (+ *validation-base-root-count* i))
            (loop for (symbol wire) in (getf m :symbols) for j from 0 do
              (unless (zerop j) (write-char #\, s))
              (format s "[~s,~s]" wire (frontend-owner symbol)))
            (write-string "],\"function\":" s)
            (if (getf m :source-name)
              (format s "~s" (frontend-owner (ccl::maybe-setf-function-name (getf m :source-name))))
              (write-string "null" s))
            (write-char #\} s))
          (write-char #\] s))
        (dolist (m all)
          (with-open-file (s (concatenate 'string out (getf m :name) ".wat")
                             :direction :output :if-exists :error)
            (write-string (getf m :wat) s)))
        (with-open-file (s (concatenate 'string out "probe-pools.json")
                           :direction :output :if-exists :error)
          (let ((roots (mapcar (lambda (m) (getf m :pool)) all)))
            (frontend-pool-owners roots)
            (write-pool-graph s roots)))
        (with-open-file (s (concatenate 'string out "probe-native.json")
                           :direction :output :if-exists :error)
          (write-char #\[ s)
          (let ((first t))
            (dolist (entry cases)
              (destructuring-bind (name inputs &optional environment) entry
                (unless inputs (error "Probe has no inputs: ~s" name))
                (let ((module (find name modules :key (lambda (m) (getf m :source-name)))))
                  (dolist (input inputs)
                    (unless first (write-char #\, s)) (setq first nil)
                    (validation-native-row name module input environment s))))))
          (write-char #\] s))
        (frontend-write-owners out)
        (with-open-file (s (concatenate 'string out "probe-callers.json")
                           :direction :output :if-exists :error)
          (write-char #\[ s)
          (loop for name in names for i from 0 do
            (unless (zerop i) (write-char #\, s)) (format s "~s" (symbol-name name)))
          (write-char #\] s))
        (format t "VALIDATION-PROBES-PASS ~d entries ~d modules~%" (length cases) (length all))))))

(validation-probes (ccl:getenv "PROBE_SOURCE") (ccl:getenv "PROBE_INPUTS")
                   (ccl:getenv "PROBE_OUTPUT") (equal (ccl:getenv "PROBE_MODE") "class"))
(ccl:quit)
