export function supportWat(runtime,schema,k,slots,mut={}) {
  const f={...runtime.tcr,...schema.tcr},s=schema.state;
  const t=n=>`(i32.load offset=${f[n]} (call $tcr))`;
  const set=(n,v)=>`(i32.store offset=${f[n]} (call $tcr) ${v})`;
  const st=n=>`(i32.load offset=${s[n]} ${t('abi_state')})`;
  const ss=(n,v)=>`(i32.store offset=${s[n]} ${t('abi_state')} ${v})`;
  const params=Array.from({length:k},(_,i)=>`(param $a${i} i32)`).join(' ');
  const values=Array.from({length:k},(_,i)=>`(if (result i32) (i32.gt_u (local.get $n) (i32.const ${i})) (then (call $input (i32.const ${i}))) (else (i32.const 65)))`).join(' ');
  const cp=Object.entries(schema.checkpoints).filter(([n])=>!['root_blocks','incoming_count'].includes(n));
  const saved=['root_head','vsp','tsp','csp','mv_base','mv_owner_top','binding_depth','binding_cookie','handler_cookie','active_request','frame_head'];
  return `(module
    (import "env" "memory" (memory 8 16 shared)) (import "env" "table" (table ${slots.minimum} funcref))
    (import "kernel" "get_tcr" (func $tcr (result i32)))
    (import "kernel" "__stack_pointer" (global $sp (mut i32)))
    (import "kernel" "admit" (func $admit)) (import "kernel" "park" (func $park))
    (import "kernel" "collect" (func $collect (result i32)))
    (import "kernel" "safepoint" (func $poll))
    (import "kernel" "abi_car" (func $car (param i32) (result i32)))
    (import "kernel" "abi_cdr" (func $cdr (param i32) (result i32)))
    (import "kernel" "abi_cons" (func $cons (param i32 i32) (result i32)))
    (import "kernel" "abi_inspect" (func $inspect (param i32)))
    (import "kernel" "abi_check" (func $inspect_binding))
    (export "inspect_binding" (func $inspect_binding))
    (import "kernel" "abi_root_count" (func $rootcount (result i32)))
    (import "kernel" "suspend_request" (func $suspend (param i32 i32 i32) (result i32)))
    (import "emitted" "exit" (tag $exit (param i32)))
    (import "loader" "lookup" (func $lookup (param i32 i32) (result i32)))
    (type $G (func (param i32 i32 ${'i32 '.repeat(k)}) (result i32 i32)))
    (type $A (func (param i32 i32 i32) (result i32 i32)))
    (global $symbol (mut i32) (i32.const 0))
    (func (export "redefine") (global.set $symbol (i32.const 1)))
    (func $error (export "error") (param $code i32) (throw $exit (local.get $code)))
    (func $state (export "state") (result i32) ${t('abi_state')})
    (func $slot (export "slot") (param $frame i32) (param $i i32) (result i32)
      (i32.add (local.get $frame) (i32.add (i32.const 136) (i32.add (i32.mul (i32.div_u (local.get $i) (i32.const 8)) (i32.const 40)) (i32.mul (i32.rem_u (local.get $i) (i32.const 8)) (i32.const 4))))))
    (func $arg (export "arg") (param $frame i32) (param $i i32) (result i32)
      (i32.load (call $slot (local.get $frame) (i32.add (local.get $i) (i32.const 1)))))
    (func $self (export "self") (param $frame i32) (result i32) (i32.load offset=136 (local.get $frame)))
    (func (export "site") (param $frame i32) (param $site i32) (i32.store offset=24 (local.get $frame) (local.get $site)))
    (func $layout_car (param $p i32) (result i32)
      (if (result i32) (i32.eq (local.get $p) (i32.const 65)) (then (i32.const 65))
        (else (i32.load ${mut.swapCons?'(i32.sub (local.get $p) (i32.const 1))':'offset=3 (local.get $p)'}))))
    (func $layout_cdr (param $p i32) (result i32)
      (if (result i32) (i32.eq (local.get $p) (i32.const 65)) (then (i32.const 65)) (else (i32.load (i32.sub (local.get $p) (i32.const 1))))))
    (func (export "layout") (param $p i32) (param $mutate i32) (result i32 i32 i32 i32)
      (local $a i32) (local $d i32)
      (call $admit) (local.set $a (call $layout_car (local.get $p))) (local.set $d (call $layout_cdr (local.get $p)))
      (if (local.get $mutate) (then (i32.store offset=3 (local.get $p) (i32.const 124)) (i32.store (i32.sub (local.get $p) (i32.const 1)) (i32.const -36))))
      (call $park) (local.get $a) (local.get $d) (call $layout_car (i32.const 65)) (call $layout_cdr (i32.const 65)))
    (func $input (export "input") (param $i i32) (result i32)
      (i32.load (i32.add ${st('input')} (i32.add (i32.const 8) (i32.add (i32.mul (i32.div_u (local.get $i) (i32.const 8)) (i32.const 40)) (i32.mul (i32.rem_u (local.get $i) (i32.const 8)) (i32.const 4)))))))
    (func $spread (param $n i32) (result i32)
      (local $list i32) (local $v i32)
      (if (i32.gt_u (local.get $n) (i32.const 32)) (then (call $error (i32.const 911))))
      (local.set $list (call $input (i32.const 31)))
      (block $done (loop $list_loop
        (br_if $done (i32.eq (local.get $list) (i32.const 65)))
        (if (i32.ne (i32.and (local.get $list) (i32.const 7)) (i32.const 1)) (then (call $error (i32.const 921))))
        (if (i32.ge_u (local.get $n) (i32.const 32)) (then (call $error (i32.const 911))))
        (local.set $v (call $car (local.get $list))) (local.set $list (call $cdr (local.get $list)))
        (i32.store (i32.add ${st('input')} (i32.add (i32.const 8) (i32.add (i32.mul (i32.div_u (local.get $n) (i32.const 8)) (i32.const 40)) (i32.mul (i32.rem_u (local.get $n) (i32.const 8)) (i32.const 4))))) (local.get $v))
        (local.set $n (i32.add (local.get $n) (i32.const 1))) (br $list_loop)))
      (local.get $n))
    (func $payload (export "payload") (param $v i32) (result i32)
      (if (result i32) (i32.eq (local.get $v) (i32.const 65)) (then (i32.const 0))
       (else (if (result i32) (i32.eqz (i32.and (local.get $v) (i32.const 3))) (then (i32.shr_s (local.get $v) (i32.const 2)))
        (else (i32.shr_s (call $car (local.get $v)) (i32.const 2)))))))
    (export "car" (func $car)) (export "cdr" (func $cdr)) (export "cons" (func $cons))
    (export "inspect" (func $inspect)) (export "collect" (func $collect)) (export "poll" (func $poll))
    (func $set_result (export "set_result") (param $frame i32) (param $i i32) (param $v i32)
      (i32.store (i32.add (local.get $frame) (i32.add (i32.const 336) (i32.mul (local.get $i) (i32.const 4)))) (local.get $v)))
    (func $get_result (export "get_result") (param $frame i32) (param $i i32) (result i32)
      (i32.load (i32.add (local.get $frame) (i32.add (i32.const 336) (i32.mul (local.get $i) (i32.const 4))))))
    (func (export "temp_set") (param $frame i32) (param $i i32) (param $v i32)
      (i32.store (i32.add (local.get $frame) (i32.add (i32.const 376) (i32.mul (local.get $i) (i32.const 4)))) (local.get $v)))
    (func (export "temp_get") (param $frame i32) (param $i i32) (result i32)
      (i32.load (i32.add (local.get $frame) (i32.add (i32.const 376) (i32.mul (local.get $i) (i32.const 4))))))
    (func $count (export "count") (param $frame i32) (param $n i32)
      (if (i32.gt_u (local.get $n) (i32.const 6)) (then (call $error (i32.const 910))))
      (i32.store offset=52 (local.get $frame) (local.get $n)) (i32.store offset=112 (local.get $frame) (local.get $n)))
    (func $enter (export "enter") (param $self i32) (param $n i32) ${params} (result i32)
      (local $frame i32) (local $i i32) (local $blocks i32) (local $head i32) (local $p i32) (local $code i32) (local $roots i32)
      (if (i32.gt_u (local.get $n) (i32.const 32)) (then (call $error (i32.const 911))))
      ${Array.from({length:k},(_,i)=>`(if (i32.and (i32.le_u (local.get $n) (i32.const ${i})) (i32.ne (local.get $a${i}) (i32.const 65))) (then (call $error (i32.const 912))))`).join('\n')}
      (local.set $code (i32.shr_u (call $car (local.get $self)) (i32.const 2)))
      (local.set $blocks (i32.div_u (i32.add (local.get $n) (i32.const 8)) (i32.const 8)))
      (local.set $roots (i32.add (call $rootcount) (i32.add (local.get $blocks) (i32.const 2))))
      (if (i32.gt_u (local.get $roots) (i32.const 15)) (then (call $error (i32.const 913))))
      (local.set $frame (i32.add ${t('vsp')} (call $overflow (local.get $n))))
      (if (i32.gt_u (i32.add (local.get $frame) (i32.const 512)) ${t('stack_limit')}) (then (call $error (i32.const 914))))
      (if (i32.eq ${t('frame_serial')} (i32.const -1)) (then (call $error (i32.const 915))))
      ${set('frame_serial',`(i32.add ${t('frame_serial')} (i32.const 1))`)}
      (memory.fill (local.get $frame) (i32.const 0) (i32.const 512))
      (i32.store (local.get $frame) (i32.const 1)) (i32.store offset=4 (local.get $frame) (i32.const 512))
      (i32.store offset=8 (local.get $frame) ${t('frame_head')}) (i32.store offset=12 (local.get $frame) ${t('frame_serial')})
      (i32.store offset=16 (local.get $frame) (i32.shl (local.get $code) (i32.const 2)))
      (i32.store offset=20 (local.get $frame) (if (result i32) (i32.eq (local.get $code) (i32.const 11)) (then (i32.const 2)) (else (i32.const 1))))
      (i32.store offset=24 (local.get $frame) (i32.add (i32.mul (local.get $code) (i32.const 100)) (i32.const 1)))
      (i32.store offset=28 (local.get $frame) ${st('policy')})
      (i32.store offset=32 (local.get $frame) ${t('tsp')}) (i32.store offset=36 (local.get $frame) ${t('csp')})
      (i32.store offset=40 (local.get $frame) (local.get $code))
      (i32.store offset=44 (local.get $frame) (i32.const 136)) (i32.store offset=48 (local.get $frame) (local.get $n))
      (i32.store offset=56 (local.get $frame) (i32.add (local.get $frame) (i32.const 112)))
      ${cp.map(([name,off])=>`(i32.store offset=${off} (local.get $frame) ${t(name)})`).join('\n')}
      (i32.store offset=104 (local.get $frame) (local.get $blocks)) (i32.store offset=108 (local.get $frame) (local.get $n))
      (i32.store offset=116 (local.get $frame) (i32.add (local.get $frame) (i32.const 336)))
      (i32.store offset=120 (local.get $frame) (i32.add (local.get $frame) (i32.const 360)))
      (local.set $head ${t('root_head')})
      (loop $roots_loop
        (local.set $p (if (result i32) (i32.lt_u (local.get $i) (local.get $blocks))
          (then (i32.add (local.get $frame) (i32.add (i32.const 128) (i32.mul (local.get $i) (i32.const 40)))))
          (else (i32.add (local.get $frame) (if (result i32) (i32.eq (local.get $i) (local.get $blocks)) (then (i32.const 328)) (else (i32.const 368)))))))
        (i32.store (local.get $p) (local.get $head)) (i32.store offset=4 (local.get $p) (i32.const 8))
        ${Array.from({length:8},(_,i)=>`(i32.store offset=${8+i*4} (local.get $p) (i32.const 65))`).join(' ')}
        (local.set $head (local.get $p)) (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $roots_loop (i32.lt_u (local.get $i) (i32.add (local.get $blocks) (i32.const 2)))))
      (i32.store offset=136 (local.get $frame) (local.get $self))
      (local.set $i (i32.const 0))
      (block $copied (loop $copy
        (br_if $copied (i32.ge_u (local.get $i) (local.get $n)))
        (i32.store (call $slot (local.get $frame) (i32.add (local.get $i) (i32.const 1)))
          ${Array.from({length:k},(_,i)=>`(if (result i32) (i32.eq (local.get $i) (i32.const ${i})) (then (local.get $a${mut.swapArgs && i<2?1-i:i})) (else `).join('')}
          ${mut.dropOverflow?'(i32.const 65)':`(i32.load (i32.add ${t('vsp')} (i32.mul (i32.sub ${mut.swapArgs&&k===0?'(if (result i32) (i32.lt_u (local.get $i) (i32.const 2)) (then (i32.xor (local.get $i) (i32.const 1))) (else (local.get $i)))':'(local.get $i)'} (i32.const ${k})) (i32.const 4))))`}${'))'.repeat(k)})
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $copy)))
      ${mut.omitRoots?'':set('root_head','(local.get $head)')}
      ${set('frame_head','(local.get $frame)')} ${set('vsp','(i32.add (local.get $frame) (i32.const 512))')}
      ${ss('entry_count',`(i32.add ${st('entry_count')} (i32.const 1))`)}
      (if (i32.gt_u ${t('vsp')} ${st('peak_vsp')}) (then ${ss('peak_vsp',t('vsp'))}))
      (if (i32.gt_u (local.get $roots) ${st('peak_roots')}) (then ${ss('peak_roots','(local.get $roots)')}))
      ;; At the outer entry the original staging slots cease to retain arguments.
      (if (i32.eqz (i32.load offset=8 (local.get $frame))) (then
        (local.set $i (i32.const 0)) (loop $clear
          (i32.store (i32.add ${st('input')} (i32.add (i32.const 8) (i32.add (i32.mul (i32.div_u (local.get $i) (i32.const 8)) (i32.const 40)) (i32.mul (i32.rem_u (local.get $i) (i32.const 8)) (i32.const 4))))) (i32.const 65))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $clear (i32.lt_u (local.get $i) (i32.const 32))))))
      (local.get $frame))
    (func $overflow (export "overflow") (param $n i32) (result i32)
      (if (result i32) (i32.gt_u (local.get $n) (i32.const ${k}))
        (then (i32.and (i32.add (i32.mul (i32.sub (local.get $n) (i32.const ${k})) (i32.const 4)) (i32.const 15)) (i32.const -16))) (else (i32.const 0))))
    (func $restore (export "tail_exit") (param $frame i32)
      ;; Each physical result word has one scanner: inactive root record OR active TCR descriptor.
      (i32.store (i32.sub ${t('mv_base')} (i32.const 4)) (i32.const 6))
      (i32.store (i32.sub (i32.load offset=80 (local.get $frame)) (i32.const 4)) (i32.const ${mut.duplicateResultRoot?6:0}))
      ${cp.map(([name,off])=>mut.omitVspRestore&&name==='vsp'?'':mut.omitRootRestore&&name==='root_head'?'':set(name,`(i32.load offset=${off} (local.get $frame))`)).join('\n')}
      ${set('frame_head','(i32.load offset=8 (local.get $frame))')})
    (func $finish (export "finish") (param $frame i32) (param $n i32) (result i32 i32)
      (local $target i32) (local $i i32) (local $v i32)
      (call $count (local.get $frame) (local.get $n))
      (local.set $target (i32.load offset=80 (local.get $frame)))
      (block $done (loop $copy (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (i32.store (i32.add (local.get $target) (i32.mul (local.get $i) (i32.const 4))) ${mut.dropValues?'(i32.const 65)':'(call $get_result (local.get $frame) (local.get $i))'})
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $copy)))
      (local.set $v (if (result i32) (local.get $n) (then (i32.load (local.get $target))) (else (i32.const ${mut.zeroNotNil?0:65}))))
      (call $restore (local.get $frame)) ${set('nvalues','(local.get $n)')}
      (local.get $v) ${mut.wrongCount?'(i32.const 1)':'(local.get $n)'})
    (func $prepare (export "prepare") (param $n i32)
      (local $i i32) (local.set $i (i32.const ${k}))
      (block $done (loop $copy (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (i32.store (i32.add ${t('vsp')} (i32.mul (i32.sub (local.get $i) (i32.const ${k})) (i32.const 4))) (call $input (local.get $i)))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $copy))))
    (func $invoke (param $self i32) (param $n i32) (param $path i32) (result i32 i32)
      (local $slot i32)
      (if (i32.gt_u (local.get $n) (i32.const 32)) (then (call $error (i32.const 911))))
      (if (i32.or (i32.eq (local.get $self) (i32.const 65)) (i32.ne (i32.and (local.get $self) (i32.const 7)) (i32.const 1))) (then (call $error (i32.const 916))))
      (local.set $slot (call $lookup (i32.shr_u (call $car (local.get $self)) (i32.const 2)) (local.get $path)))
      (if (i32.eq (local.get $path) (i32.const 2)) (then
        (return_call_indirect (type $A) (local.get $self) (local.get $n) (call $tcr) (local.get $slot))))
      (call $prepare (local.get $n))
      (return_call_indirect (type $G) (local.get $self) (local.get $n) ${values} (local.get $slot)))
    (func $nested_call (export "nested_call") (param $frame i32) (param $anchor i32) (param $n i32) (result i32 i32)
      (local $self i32) (local $i i32) (local $v i32) (local $count i32)
      (local.set $self (i32.load (i32.add ${st('anchors')} (i32.mul (local.get $anchor) (i32.const 4)))))
      ${mut.staleResultCount?'':'(call $count (local.get $frame) (i32.const 0))'}
      (i32.store (i32.sub ${t('mv_base')} (i32.const 4)) (i32.const 6))
      (i32.store offset=332 (local.get $frame) (i32.const 0))
      ${set('mv_base','(i32.add (local.get $frame) (i32.const 336))')} ${set('mv_owner_top','(i32.add (local.get $frame) (i32.const 360))')} ${set('nvalues','(i32.const 0)')}
      (local.set $i (i32.const ${k}))
      (block $done (loop $copy (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (i32.store (i32.add ${t('vsp')} (i32.mul (i32.sub (local.get $i) (i32.const ${k})) (i32.const 4))) (call $arg (local.get $frame) (local.get $i)))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $copy)))
      (call_indirect (type $G) (local.get $self) (local.get $n)
        ${Array.from({length:k},(_,i)=>`(if (result i32) (i32.gt_u (local.get $n) (i32.const ${i})) (then (call $arg (local.get $frame) (i32.const ${i}))) (else (i32.const 65)))`).join(' ')}
        (call $lookup (i32.shr_u (call $car (local.get $self)) (i32.const 2)) (i32.const 0)))
      (local.set $count) (local.set $v)
      (call $count (local.get $frame) (local.get $count))
      (local.get $v) (local.get $count))
    (func $pause (export "pause") (param $frame i32) (param $opcode i32)
      (i32.store offset=24 (local.get $frame) (i32.add (i32.mul (i32.shr_u (i32.load offset=16 (local.get $frame)) (i32.const 2)) (i32.const 100))
        (if (result i32) (i32.eq (local.get $opcode) (i32.const 2)) (then (i32.const 92)) (else (i32.const 2)))))
      (call $inspect (i32.const 1))
      (drop (call $suspend (local.get $opcode) (i32.load offset=64 (call $state)) (call $self (local.get $frame))))
      (i32.store offset=24 (local.get $frame) (i32.add (i32.load offset=24 (local.get $frame)) (i32.const 1)))
      (call $inspect (i32.const 2)))
    (func (export "debugger")
      (local $parent i32) (local $index i32) (local $base i32) (local $owner i32) (local $count i32)
      (local.set $parent ${t('frame_head')}) (local.set $index (i32.load offset=64 (call $state)))
      (local.set $base ${t('mv_base')}) (local.set $owner ${t('mv_owner_top')}) (local.set $count ${t('nvalues')})
      (i32.store offset=64 (call $state) (i32.const 1))
      (call $nested_call (local.get $parent) (i32.const 2) (i32.const 2)) (drop) (drop)
      (i32.store offset=64 (call $state) (local.get $index))
      (i32.store (i32.sub ${t('mv_base')} (i32.const 4)) (i32.const 6))
      (i32.store (i32.sub (local.get $base) (i32.const 4)) (i32.const 0))
      ${set('mv_base','(local.get $base)')} ${set('mv_owner_top','(local.get $owner)')} ${set('nvalues','(local.get $count)')})
    (func (export "start") (param $anchor i32) (param $n i32) (param $path i32) (result i32 i32)
      (local $self i32) (local $v i32) (local $count i32) (local $caught i32) (local $cleanup_error i32) (local $before_sp i32)
      ${saved.map((_,i)=>`(local $saved${i} i32)`).join(' ')}
      (call $admit) (local.set $before_sp (global.get $sp))
      ${saved.map((name,i)=>`(local.set $saved${i} ${t(name)})`).join('\n')}
      ${ss('initial_vsp',t('vsp'))} ${ss('error','(i32.const 0)')}
      (i32.store ${t('tsp')} (i32.const 1980)) (i32.store ${t('csp')} (i32.const 2004))
      ${set('tsp',`(i32.add ${t('tsp')} (i32.const 4))`)} ${set('csp',`(i32.add ${t('csp')} (i32.const 4))`)}
      ${set('binding_cookie','(i32.const 1980)')} ${set('handler_cookie','(i32.const 2004)')}
      ${set('binding_depth',`(i32.add ${t('binding_depth')} (i32.const 1))`)}
      (local.set $caught (block $catch (result i32) (try_table (catch $exit $catch)
        (if (i32.eq (local.get $anchor) (i32.const -1)) (then (local.set $anchor (global.get $symbol))))
        (if (i32.ge_u (local.get $path) (i32.const 4)) (then (local.set $n (call $spread (local.get $n))) (local.set $path (i32.sub (local.get $path) (i32.const 4)))))
        (local.set $self (if (result i32) (i32.lt_u (local.get $anchor) (i32.const 8))
          (then (i32.load (i32.add ${st('anchors')} (i32.mul (local.get $anchor) (i32.const 4))))) (else (i32.const 65))))
        (if (i32.and ${st('suspend')} (i32.const 16)) (then
          (local.set $self (call $cons (call $car (local.get $self)) (call $cdr (local.get $self))))))
        (call $invoke (local.get $self) (local.get $n) (local.get $path)) (local.set $count) (local.set $v)
        (call $inspect (i32.const 3))) (i32.const 0)))
      (local.set $cleanup_error (block $catch_cleanup (result i32) (try_table (catch $exit $catch_cleanup)
        ${mut.omitCleanup?'':ss('cleanup_count',`(i32.add ${st('cleanup_count')} (i32.const 1))`)}
        (if (i32.and ${st('suspend')} (i32.const 8)) (then (call $error (i32.const 919))))) (i32.const 0)))
      (if (local.get $cleanup_error) (then (local.set $caught (local.get $cleanup_error))))
      (global.set $sp (local.get $before_sp))
      ;; No poll while discarding abandoned C/Lisp roots and restoring ownership.
      (i32.store (i32.sub ${t('mv_base')} (i32.const 4)) (i32.const 6))
      (i32.store (i32.sub (local.get $saved4) (i32.const 4)) (i32.const ${mut.duplicateResultRoot?6:0}))
      ${saved.map((name,i)=>set(name,`(local.get $saved${i})`)).join('\n')}
      (if (local.get $caught) (then
        ${ss('error','(local.get $caught)')} (local.set $v (i32.const -1)) (local.set $count (i32.const 0))
        (i32.atomic.store offset=${runtime.request.cancel_requested} (i32.load offset=${f.requests} (call $tcr)) (i32.const 1))))
      ${set('nvalues','(local.get $count)')}
      (call $park) (local.get $v) (local.get $count))
  )`;
}
