"""Independent publication accounting and native protocol/defect separation."""
import copy,hashlib,json
from pathlib import Path

def read(p):return json.loads(p.read_text())
def save(p,x):p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def need(x,why):
 if not x:raise ValueError(why)
def native(g):
 nodes={o['id']:o['value'] for o in g['objects']}
 def d(v):
  if 'ref' in v:
   n=nodes[v['ref']];return ''.join(map(chr,n['value'])) if n['kind']=='string' else list(map(d,n['elements']))
  if 'symbol' in v:return v['symbol']
  if v['kind']=='integer':return int(v['value'])
  return None if v['value']=='nil' else True
 return list(map(d,g['roots']))
NAMES=['gd_factory','gd_factory_inner_1','gd_dispatch','gd_envelope','gd_body','gd_missing','gd_missing_inner_1','gd_missing_inner_2','gd_table','gd_table_inner_1','gd_set_encapsulated','gd_update','gd_recompute','gd_remove','gd_remove_inner_1','gd_add','gd_add_inner_1','gd_raw_store','gd_method_a','gd_method_b','gd_method_c','gd_probe','gd_cleanup','gd_resignal','gd_resignal_inner_1','gd_continue','gd_continue_inner_1','gd_arity','gd_decline','gd_decline_inner_1']
FAULTS=['retain-last-dcode','omit-empty-guard','wrong-encapsulated-cell','discard-second-value','drop-envelope','lose-continue-retry','lose-condition-gf','lose-condition-args','universal-first']
LABELS=['universal','specific','table miss','remaining','empty registry','stale raw store','cleanup condition transfer','resignalled condition','continue reinstalls method','replacement remains live','table replacement','empty after table','readd after table','arity before dispatch']
ORDER=['initial empty registry','eql only','nonempty no-match','specificity after universal','method replacement']
def assess(d):
 need(d['modules']==NAMES,'module population');x=d['execution'];need(x['status']=='PASS' and [r['base'] for r in x['rows']]==[1048576,2147483648],'Worker placements')
 n=native(d['native']);order=native(d['order'])[0];flow=native(d['flow'])[0]
 need([v[0] for v in n]==[None,True] and all(v[5]==[10,11] and v[6]==[901,True,3] and v[7]==[30,31] for v in n),'native defect retained separately from required protocol')
 need(order==[[20,21],[901,True,9],[20,21],[30,31]],'native specificity and replacement')
 tagged=lambda values:[77838 if v is True else 77825 if v is None else v*4 for v in values]
 for row in x['rows']:
  need(row['status']=='PASS' and row['modules']==30,'generated population')
  need(row['classes']==d['classes'] and row['classes'][-1]['name']=='NO-APPLICABLE-METHOD-EXISTS' and [s['name'] for s in row['classes'][-1]['slots']]==['GF','ARGS'],'native condition slots')
  need(len(row['observations'])==72 and [o['error'] for o in row['observations'] if 'error' in o]==[15,15,5,5,5,5],'declined and damaged boundaries')
  need([s['encapsulated'] for s in row['scenarios']]==[False,True] and [s['traceCalls'] for s in row['scenarios']]==[0,15],'direct and encapsulated dispatch')
  for i,s in enumerate(row['scenarios']):need([s['nativeDefect'],s['required'],s['resumed']]==n[i][5:8],'native observation/protocol distinction')
  checks=row['checks'];need([c['label'] for c in checks]==LABELS*2+ORDER*2+['registry restored'],'semantic check population')
  for i in range(2):
   v=n[i];expected=[v[1],v[2],v[3],v[4],v[6],v[6],flow[0],flow[1],v[7],v[7],v[2],v[6],v[7],flow[2]]
   need([c['values'] for c in checks[i*14:(i+1)*14]]==list(map(tagged,expected)),'native generated comparisons')
  need([c['values'] for c in checks[28:]]==list(map(tagged,([n[0][6]]+order)*2+[n[0][6]])),'order and empty initial state')
  need(row['registryRefusals']==[dict(name=n,code=5) for n in ['short-registry','oversize-registry','wrong-registry-kind','missing-new-class']],'bounded class registry')
  need([r['name'] for r in row['manifest']['modules']]==NAMES,'manifest modules');need(row['installed']['modules']==NAMES,'complete installation')
  need(row['binaries']==[dict(name=n,sha256=d['binaries'][n]) for n in NAMES],'generated bytes')
  need(row['installed']['installed']==[dict(slot=i+4,event='INSTALLED',sha256=d['binaries'][n]) for i,n in enumerate(NAMES)],'installed bytes')
 need([m['name'] for m in d['mutants']]==FAULTS and all(m['status']=='REJECTED' for m in d['mutants']),'compiled fault population')
 need(d['compatibility']['status']=='PASS' and d['compatibility']['modules']==107 and d['compatibility']['comparisons']==184,'existing twelve-class condition corpus')
 return dict(status='PASS',modules=30,worker_placements=2,generated_invocations=144,semantic_comparisons=78,installed_modules=60,native_defect_modes=2,registry_refusals=8,compiled_mutants=9,inherited_modules=107,inherited_comparisons=184)
def run(x,out):
 d=dict(execution=read(x/'execution.json'),modules=[r['name'] for r in read(x/'compiled/modules.json')],native=read(x/'compiled/native-behavior.json'),order=read(x/'compiled/native-order.json'),flow=read(x/'compiled/native-flow.json'),classes=read(x/'compiled/native-condition-classes.json'),binaries={n:hashlib.sha256((x/'compiled'/(n+'.wasm')).read_bytes()).hexdigest() for n in NAMES},mutants=read(x/'mutants/controls.json'),compatibility=read(x/'compatibility/summary.json'))
 result=assess(d);controls=[]
 for name,edit in [('missing-module',lambda d:d['modules'].pop()),('missing-high-placement',lambda d:d['execution']['rows'].pop()),('lost-empty-call',lambda d:d['execution']['rows'][0]['checks'].pop()),('concealed-native-defect',lambda d:d['execution']['rows'][0]['scenarios'][0].update(nativeDefect=[901,True,3])),('lost-encapsulation',lambda d:d['execution']['rows'][0]['scenarios'].pop()),('wrong-condition-slots',lambda d:d['execution']['rows'][0]['classes'][-1]['slots'].reverse()),('lost-continue-values',lambda d:d['execution']['rows'][0]['checks'][8].update(values=[0])),('changed-installed-binary',lambda d:d['execution']['rows'][0]['installed']['installed'][0].update(sha256='0'*64)),('lost-registry-refusal',lambda d:d['execution']['rows'][0]['registryRefusals'].pop()),('lost-mutant',lambda d:d['mutants'].pop()),('lost-inherited',lambda d:d['compatibility'].update(comparisons=0))]:
  bad=copy.deepcopy(d);edit(bad)
  try:assess(bad)
  except ValueError as ex:controls.append(dict(name=name,status='REJECTED',diagnostic=str(ex)))
  else:raise ValueError(name+' escaped')
 out.mkdir();save(out/'inputs.json',d);save(out/'assessment.json',result);save(out/'controls.json',controls);return result
