(in-package :wasm32-compiler)
(load (merge-pathnames "export.lisp" *load-pathname*))
(let* ((out (ccl:getenv "POOL_OUTPUT")) (modules nil) (native nil)
       (cases (with-open-file (s (merge-pathnames "runtime.lisp" *load-pathname*)) (second (read s)))))
  (dolist (row cases)
    (let* ((name (first row)) (form (second row))
           (result (compile-metadata-call-form form name (append (mapcar #'first cases) '("gd_condition" "gd_condition_gf" "gd_condition_args"))))
           (fn (compile nil form))
           (specimen fn)
           (args (multiple-value-list (ccl::function-args (ccl::closure-function specimen))))
           (keys (ccl::lfun-keyvect (ccl::closure-function specimen))))
      (push (vector name (coerce (subseq args 0 5) 'vector) (copy-seq (or keys #()))) native)
      (dolist (m (cons result (getf result :children)))
        (push m modules)
        (loop for key across (aref (aref (getf m :pool) 0) 6) do
          (pushnew (cons key (concatenate 'string (package-name (symbol-package key)) "::" (symbol-name key))) *pool-symbol-owners* :key #'car :test #'eq))
        (with-open-file (s (concatenate 'string out (getf m :name) ".wat") :direction :output :if-exists :error) (write-string (getf m :wat) s)))))
  (setq modules (nreverse modules) native (nreverse native))
  (with-open-file (s (concatenate 'string out "modules.json") :direction :output :if-exists :error)
    (write-char #\[ s)
    (loop for m in modules for i from 0 do (unless (zerop i) (write-char #\, s))
      (format s "{\"name\":~s,\"top\":~a,\"captures\":~d}" (getf m :name) (if (assoc (getf m :name) cases :test #'equal) "true" "false") (getf m :captures)))
    (write-char #\] s))
  (with-open-file (s (concatenate 'string out "pools.json") :direction :output :if-exists :error) (write-pool-graph s (mapcar (lambda (m) (getf m :pool)) modules)))
  (with-open-file (s (concatenate 'string out "native-metadata.json") :direction :output :if-exists :error) (write-pool-graph s native)))
(load (merge-pathnames "oracle.lisp" *load-pathname*))
(load (merge-pathnames "class-shapes.lisp" *load-pathname*))
(format t "POOL-COMPILE-PASS~%")
(ccl:quit)
