;; Portable source for the initial primary-method dispatch subset. The state is
;; owned by one Worker: (methods direct encapsulated inner callable trace).
;; Its callable is a generated closure. Methods are (EQL-key-or-T . function).
'(("gd_factory" (lambda (methods dcode encapsulated trace)
   (let* ((state (cons methods (cons dcode (cons encapsulated (cons dcode (cons nil (cons trace nil)))))))
          (callable (lambda (&rest args) (apply #'gd_dispatch state args))))
     (rplaca (cdr (cdr (cdr (cdr state)))) callable)
     (values callable state))))
  ("gd_dispatch" (lambda (state x)
   (if (car (cdr (cdr state))) (gd_envelope state x) (gd_body state x))))
  ("gd_envelope" (lambda (state &rest args)
   (let ((trace (car (cdr (cdr (cdr (cdr (cdr state))))))))
     (rplaca trace (cons 1 (car trace))))
   (apply #'gd_body state args)))
  ("gd_body" (lambda (state &rest args)
   (if (car state)
     (apply (if (car (cdr (cdr state))) (car (cdr (cdr (cdr state)))) (car (cdr state))) state args)
     (apply #'gd_missing state args))))
  ("gd_missing" (lambda (state &rest args)
   (let ((gf (car (cdr (cdr (cdr (cdr state)))))))
     (restart-case (error (gd_condition gf args))
       (continue () (apply gf args))))))
  ("gd_table" (lambda (state &rest args)
   (labels ((select (methods universal)
              (if methods
                (if (eq (car (car methods)) t)
                  (select (cdr methods) (cdr (car methods)))
                  (if (eq (car (car methods)) (car args))
                    (apply (cdr (car methods)) state args)
                    (select (cdr methods) universal)))
                (if universal (apply universal state args)
                  (apply #'gd_missing state args)))))
     (select (car state) nil))))
  ("gd_set_encapsulated" (lambda (state dcode)
   (rplaca (cdr (cdr (cdr state))) dcode)
   dcode))
  ("gd_update" (lambda (state methods candidate)
   (rplaca state methods)
   (let ((next (if methods candidate #'gd_missing)))
     (if (car (cdr (cdr state)))
       (gd_set_encapsulated state next)
       (rplaca (cdr state) next)))
   state))
  ("gd_recompute" (lambda (state methods)
   (gd_update state methods
     (if methods
       (if (cdr methods) #'gd_table
         (if (eq (car (car methods)) t) (cdr (car methods)) #'gd_table))
       #'gd_missing))))
  ("gd_remove" (lambda (state method)
   (labels ((without (items)
              (if items
                (if (eq (car items) method) (cdr items)
                  (cons (car items) (without (cdr items))))
                nil)))
     (gd_recompute state (without (car state))))))
  ("gd_add" (lambda (state method)
   (labels ((without (items)
              (if items
                (if (eq (car (car items)) (car method)) (cdr items)
                  (cons (car items) (without (cdr items))))
                nil)))
     (gd_recompute state (cons method (without (car state)))))))
  ("gd_raw_store" (lambda (state candidate)
   (if (car (cdr (cdr state)))
     (gd_set_encapsulated state candidate)
     (rplaca (cdr state) candidate))
   state))
  ("gd_method_a" (lambda (state x) (values 10 11)))
  ("gd_method_b" (lambda (state x) (values 20 21)))
  ("gd_method_c" (lambda (state x) (values 30 31)))
  ("gd_probe" (lambda (gf x)
   (handler-case (funcall gf x)
     (ccl::no-applicable-method-exists (c)
       (values 901 (eq (gd_condition_gf c) gf) (car (gd_condition_args c)))))))
  ("gd_cleanup" (lambda (gf x cell)
   (handler-case (unwind-protect (funcall gf x) (rplaca cell 71))
     (ccl::no-applicable-method-exists (c)
       (values 901 (eq (gd_condition_gf c) gf) (car (gd_condition_args c)) (car cell))))))
  ("gd_resignal" (lambda (gf x)
   (handler-case
     (handler-bind ((ccl::no-applicable-method-exists (lambda (c) (error c))))
       (funcall gf x))
     (ccl::no-applicable-method-exists (c)
       (values 901 (eq (gd_condition_gf c) gf) (car (gd_condition_args c)))))))
  ("gd_continue" (lambda (gf state method x)
   (handler-bind ((ccl::no-applicable-method-exists
                   (lambda (c) (gd_add state (cons t method))
                     (invoke-restart 'continue))))
     (funcall gf x))))
  ("gd_arity" (lambda (gf)
   (handler-case (funcall gf)
     (program-error (c) 902))))
  ("gd_decline" (lambda (gf x)
   (handler-bind ((ccl::no-applicable-method-exists (lambda (c) (values))))
     (funcall gf x)))))
