;;; First source-file traversal. No target code emission or source installation.
(defpackage :ccl-source-traversal (:use :cl))
(in-package :ccl-source-traversal)

(defun obj (&rest fields) (apply #'ccl-startup-census::object fields))
(defun label (x) (ccl-startup-census::label-of x))
(defun field (x name) (loop for (k v) on (cdr x) by #'cddr when (equal k name) return v))
(defun state ()
  (list ccl::*target-backend* ccl::*fasl-target* ccl::*target-ftd* *features*
        (find-package "TARGET") (find-package "OS")))
(defun context ()
  (obj "backend" (label (ccl::backend-name ccl::*target-backend*))
       "fasl_target" (label ccl::*fasl-target*)
       "foreign_data_matches" (if (eq ccl::*target-ftd* (ccl::backend-target-foreign-type-data ccl::*target-backend*)) :true :false)
       "target_package" (package-name (find-package "TARGET"))
       "os_package" (package-name (find-package "OS"))
       "features" (sort (mapcar #'label *features*) #'string<)
       "word_bits" (arch::target-nbits-in-word (ccl::backend-target-arch ccl::*target-backend*))
       "argument_registers" (ccl::backend-num-arg-regs ccl::*target-backend*)))
(defun source-text (path)
  (with-open-file (s path :external-format :utf-8)
    (with-output-to-string (out) (loop for c = (read-char s nil nil) while c do (write-char c out)))))
(defun form-name (form)
  (when (and (consp form) (member (car form) '(defun defvar defparameter defmacro))) (second form)))

(defun index-source (text suppress)
  ;; A complete independent read precedes collection. For this first file there
  ;; are no conditional top-level forms; conditions inside bodies are retained
  ;; in their enclosing source slice. Do not use this index for general files
  ;; until their reader/effect semantics are separately qualified.
  (let ((*package* (find-package "CCL")) (*read-suppress* suppress)
        (eof (cons nil nil)) (rows nil) (ordinal 0))
    (with-input-from-string (s text)
      (loop for start = (file-position s) for form = (read s nil eof)
            for end = (file-position s) do
        (when (eq form eof)
          (return (values (nreverse rows) start end)))
        (push (obj "ordinal" (incf ordinal) "start" start "end" end
                   "operator" (if suppress :null (label (car form)))
                   "name" (if (or suppress (null (form-name form))) :null (label (form-name form)))) rows)))))

(defun traverse (path text index)
  (let* ((*package* (find-package "CCL"))
         (ccl::*compiling-file* path)
         (*compile-file-pathname* path) (*compile-file-truename* path)
         (*compile-print* nil) (*compile-verbose* nil)
         (ccl::*fasl-backend* ccl::*target-backend*)
         (ccl::*fasl-save-doc-strings* nil) (ccl::*fasl-save-definitions* nil)
         (ccl::*fasl-save-local-symbols* nil) (ccl::*fasl-break-on-program-errors* t)
         (ccl::*fasl-deferred-warnings* nil)
         (ccl::*fcomp-source-note-map* (make-hash-table :test #'eq))
         (ccl::*fcomp-output-list* nil) (ccl::*fcomp-toplevel-forms* nil)
         (ccl::*fcomp-load-time* t) (ccl::*fcomp-indentation* 0)
         (ccl::*fcomp-loading-toplevel-location* nil) (ccl::*loading-toplevel-location* nil)
         (ccl::*loading-file-source-file* (namestring path))
         (ccl::*fasl-source-file* (namestring path))
         (ccl::*fcomp-previous-position* nil) (ccl::*fcomp-stream-position* nil)
         (ccl::*fcomp-last-compile-print* (list* nil nil nil))
         (ccl::*fasl-setf-name-alias-alist* nil)
         (ccl::*fasl-compile-time-env* (ccl::new-lexical-environment (ccl::new-definition-environment)))
         (ccl::*outstanding-deferred-warnings* (ccl::%defer-warnings nil))
         (defenv (ccl::new-definition-environment)) (env (ccl::new-lexical-environment defenv))
         (rows nil) (unresolved nil)
         (mode (or (ccl:getenv "CCL_TRAVERSE_MODE") "normal")))
    (rplacd (ccl::defenv.type defenv) ccl::*outstanding-deferred-warnings*)
    (setf (ccl::defenv.defined defenv) (ccl::deferred-warnings.defs ccl::*outstanding-deferred-warnings*))
    (dolist (entry index)
      (let* ((start (field entry "start")) (end (field entry "end"))
             (form nil) (stage "read") (status nil) (problem :null) (capture :null)
             (read-context nil) (prior-unresolved (reverse unresolved))
             (macros nil) (warnings nil) (old-hook *macroexpand-hook*)
             (ccl::*fcomp-toplevel-forms* nil) (ccl::*fcomp-output-list* nil)
             (ccl::*nx-warnings* nil) (ccl::*fcomp-stream-position* start)
             (ccl::*loading-toplevel-location* nil) (ccl::*fcomp-loading-toplevel-location* nil)
             (ccl-census-stub::*capture-tag* (gensym "SOURCE-CAPTURE")))
        (handler-case
          (progn
            (flet ((read-one ()
                     (setf read-context (context))
                     (with-input-from-string (s text :start start :end end)
                       (setf form (ccl::read-recording-source s :file-name (namestring path)
                                     :map ccl::*fcomp-source-note-map* :save-source-text t)))))
              (if (equal mode "host-reader")
                (let* ((ccl::*target-backend* ccl::*host-backend*)
                       (*features* (ccl::setup-target-features ccl::*host-backend* *features*)))
                  (ccl::with-cross-compilation-target ((ccl::backend-name ccl::*host-backend*)) (read-one)))
                (read-one)))
            (unless (and (consp form) (member (car form) '(in-package defvar declaim defun)))
              (error "TOPLEVEL-KIND-NOT-QUALIFIED"))
            (setf stage "front-end")
            (let* ((*macroexpand-hook*
                    (lambda (fn call environment)
                      (let ((note (ccl:function-source-note fn)))
                        (push (obj "operator" (label (car call))
                                   "backend" (label (ccl::backend-name ccl::*target-backend*))
                                   "source" (if note (namestring (ccl::source-note-filename note)) :null)
                                   "position" (if note (ccl::source-note-start-pos note) :null)) macros))
                      (funcall old-hook fn call environment)))
                   (answer
                    (handler-bind ((warning (lambda (c) (push (princ-to-string c) warnings))))
                      (catch ccl-census-stub::*capture-tag*
                        (ccl::fcomp-form form env :not-compile-time)
                        (ccl::fcomp-compile-toplevel-forms env)
                        :completed))))
              (cond ((typep answer 'ccl::afunc)
                     (setf capture (ccl-startup-census::function-observation answer)
                           status "CAPTURED"))
                    ((eq answer :completed) (setf status "TOPLEVEL-PROCESSED"))
                    (t (error "INVALID-CAPTURE-RESULT")))))
          (error (c) (setf status "UNSUPPORTED"
                          problem (obj "stage" stage "type" (label (type-of c))
                                       "message" (princ-to-string c)))))
        (push (obj "ordinal" (field entry "ordinal") "start" start "end" end
                   "operator" (if (consp form) (label (car form)) :null)
                   "name" (if (form-name form) (label (form-name form)) :null)
                   "status" status "problem" problem "function" capture
                   "reader_context" read-context "prior_unresolved_forms" prior-unresolved
                   "macro_expansions" (nreverse macros) "warnings" (nreverse warnings)
                   "deferred_output_opcodes" (mapcar #'car (reverse ccl::*fcomp-output-list*))) rows)
        (when (equal status "UNSUPPORTED") (push (field entry "ordinal") unresolved))
        (when (and (equal mode "stop-after-first-capture") (equal status "CAPTURED")) (return))))
    (nreverse rows)))

(defun run ()
  (let* ((path (pathname (ccl:getenv "CCL_TRAVERSE_SOURCE"))) (text (source-text path))
         (before (state)) (during nil) (rows nil)
         (bindings nil))
    (multiple-value-bind (index tail-start eof) (index-source text nil)
      (multiple-value-bind (suppressed ignored suppressed-eof) (index-source text t)
        (declare (ignore ignored))
        (unless (and (= eof suppressed-eof)
                     (equal (mapcar (lambda (r) (list (field r "start") (field r "end"))) index)
                            (mapcar (lambda (r) (list (field r "start") (field r "end"))) suppressed)))
          (error "INDEPENDENT-READER-BOUNDARIES-DIFFER")))
      (dolist (r index)
        (when (equal (field r "operator") "COMMON-LISP::DEFUN")
          (let* ((*package* (find-package "CCL"))
                 (name (read-from-string (field r "name"))))
            (push (cons name (fboundp name)) bindings))))
      (ccl-census-stub::with-target-state
        (lambda ()
          (setf during (context))
          (setf rows (traverse path text index))))
      (unless (equal before (state)) (error "TARGET-STATE-NOT-RESTORED"))
      (unless (every (lambda (b) (eq (cdr b) (fboundp (car b)))) bindings)
        (error "SOURCE-FUNCTION-INSTALLED"))
      (with-open-file (out (ccl:getenv "CCL_TRAVERSE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
        (ccl-startup-census::json
          (obj "version" 1 "source" "lib/dumplisp.lisp" "characters" (length text)
               "index" index "tail_start" tail-start "eof" eof "target" during "rows" rows
               "native_state_restored" :true "source_bindings_unchanged" :true
               "scope" "Per-top-level target front-end capture. Unsupported forms and unqualified native-image macro environments remain obligations; no FASL or code installed.") out)
        (terpri out))
      (format t "SOURCE-TRAVERSAL-COMPLETE ~d/~d~%" (length rows) (length index)))))
