(in-package :ccl)
;; Observe first, before test constructors add definitions or new runtime work.
(dolist (name '(%setf-function-names% %setf-function-name-inverses% %lambda-lists% *combined-methods*))
 (let ((table (symbol-value name)))
  (assert (hash-table-p table))
  (format t "POPULATION ~a ~d ~a~%" name (hash-table-count table) (hash-table-test table))))
;; Native population API copies a list spine, and copies association pairs too.
(dolist (type '(:list :alist))
 (let* ((key (list 17)) (value (list 29))
        (source (if (eq type :list) (list key value) (list (cons key value))))
        (pop (make-population :type type :initial-contents source))
        (copy (population-contents pop)))
  (assert (eq (population-type pop) type)) (assert (not (eq copy source)))
  (if (eq type :list)
      (progn (assert (eq (car copy) key)) (assert (eq (cadr copy) value)))
      (progn (assert (not (eq (car copy) (car source))))
             (assert (eq (caar copy) key)) (assert (eq (cdar copy) value))))
  (format t "POPULATION-API ~a PASS~%" type)))
(quit)
