(load (merge-pathnames "class-shapes.lisp" *load-pathname*))
(in-package :wasm32-compiler)
(load (merge-pathnames "whole-file.lisp" *load-pathname*))
(load (merge-pathnames "legacy.lisp" *load-pathname*))
(frontend-legacy (ccl:getenv "POOL_OUTPUT"))
(load (merge-pathnames "base-measure.lisp" *load-pathname*))
(load (merge-pathnames "measure.lisp" *load-pathname*))
(call-with-target (lambda () (load "ccl:xdump;hashenv.lisp")))
(let ((chunks (with-open-file (s (merge-pathnames "chunks.lisp" *load-pathname*)) (second (read s)))))
 (setq *core-native-forms* (core-read-native-forms chunks))
 (measure-frontend chunks (ccl:getenv "POOL_OUTPUT")))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-read-skips.sexp") :direction :output :if-exists :error)
  (let ((*print-pretty* nil)) (prin1 (nreverse *core-native-read-skips*) s)))
(core-compile-file "ccl:level-0;l0-pred.lisp" t)
(core-compile-file "ccl:level-0;l0-utils.lisp" t)
(core-compile-file "ccl:level-0;l0-pred.lisp")
(core-compile-file "ccl:level-0;l0-utils.lisp")
(core-compile-file "ccl:level-0;WASM32;w32-prims.lisp")
(core-compile-file "ccl:level-0;l0-symbol.lisp" t)
(core-compile-file "ccl:level-0;l0-misc.lisp" t)
(core-compile-file "ccl:level-0;l0-symbol.lisp")
(core-compile-file "ccl:level-0;l0-misc.lisp")
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "whole-file.json") :direction :output :if-exists :error)
  (write-char #\[ s)
  (loop for (path name wire outcome dependencies) in (reverse *core-records*) for i from 0 do
    (unless (zerop i) (write-char #\, s))
    (format s "{\"file\":~s,\"module\":~s,\"name\":" path wire)
    (if name (format s "~s" (symbol-name name)) (write-string "null" s))
    (format s ",\"status\":~s,\"dependencies\":[" (if (symbolp outcome) (symbol-name outcome) (prin1-to-string outcome)))
    (loop for symbol in dependencies for j from 0 do
      (unless (zerop j) (write-char #\, s))
      (frontend-json-string (format nil "~s" symbol) s))
    (write-string "]}" s))
  (write-char #\] s))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "whole-file.sexp") :direction :output :if-exists :supersede)
 (let ((*print-circle* t) (*print-pretty* nil)) (prin1 (reverse *core-records*) s)))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "dependencies.sexp") :direction :output :if-exists :supersede)
 (let ((*print-circle* t) (*print-pretty* nil)) (prin1 (mapcar (lambda (m) (list (getf m :source-name) (getf m :dependencies))) *core-modules*) s)))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "candidates.sexp") :direction :output :if-exists :supersede)
 (let ((*print-circle* t) (*print-pretty* nil))
  (prin1 (mapcar (lambda (row) (list (second (first row)) (third (first row)) (getf (second row) :dependencies) (getf (second row) :dynamic-call))) *core-candidates*) s)))
(dolist (module *core-modules*)
 (dolist (m (cons module (getf module :children)))
  (with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") (getf m :name) ".wat") :direction :output :if-exists :supersede)
   (write-string (getf m :wat) s))))
(load (merge-pathnames "controls.lisp" *load-pathname*))
(core-controls (ccl:getenv "POOL_OUTPUT"))
(load (merge-pathnames "probes.lisp" *load-pathname*))
(let ((native-forms (core-probe-forms)))
  (call-with-target (lambda () (load (merge-pathnames "probes.lisp" *load-pathname*))))
  (core-add-probes native-forms))
(load (merge-pathnames "execute.lisp" *load-pathname*))
(load (merge-pathnames "worklist.lisp" *load-pathname*))
(library-measure-worklist)
(format t "POOL-COMPILE-PASS~%") (ccl:quit)

