;;; Generated Lisp witnesses for copied octets and cleanup after FOREIGN.
(in-package "CCL")
(eval-when (:compile-toplevel)
  (proclaim '(optimize (speed 3) (safety 1) (debug 0)))
  (proclaim '(notinline fb-request fb-call fb-success fb-failure)))
(defvar *fb-binding* :outside)
(defun fb-bytes ()
  (make-array 8 :element-type '(unsigned-byte 8)
              :initial-contents '(65 195 169 240 159 140 141 0)))
(defun fb-request (mode bytes)
  #+wasm32-target (%wasm-host-process-request 101 mode bytes)
  #-wasm32-target
  (if (zerop mode)
    (progn (incf (aref bytes 0)) (reduce #'+ bytes))
    -1))
(defun fb-call (mode bytes)
  (let ((result (fb-request mode bytes)))
    (if (minusp result) (error "Foreign buffer fixture ~D" result) result)))
(defun fb-success ()
  (let* ((bytes (fb-bytes))
         (alias (cons bytes bytes))
         (*fb-binding* bytes)
         (closure (lambda () bytes)))
    (list (fb-call 0 bytes) (eq (car alias) bytes) (eq (cdr alias) bytes)
          (eq (funcall closure) bytes) (eq *fb-binding* bytes)
          (coerce bytes 'list))))
(defun fb-failure (mode)
  (let ((bytes (fb-bytes)) (cleanups 0) (held nil))
    (let ((*fb-binding* bytes))
      (list (handler-case
                (unwind-protect (fb-call mode bytes)
                  (setq held (coerce *fb-binding* 'list))
                  (incf cleanups))
              (error () :caught))
            cleanups (eq *fb-binding* bytes) held))))
(defun fb-row (name value) (format t "FB-ROW ~A ~S~%" name value))
(fb-row 'copied-moving-bytes (fb-success))
(fb-row 'multiple-values
        (multiple-value-list
         (multiple-value-prog1 (values (list 11 12) 13 nil) (fb-success))))
(dolist (mode '(1 2 3 4)) (fb-row mode (fb-failure mode)))
(fb-row 'binding-after-cleanup *fb-binding*)
(write-line "FB-PASS")
