(module
 (import "host" "collect" (func $collect))
 (import "host" "observe" (func $observe (param i32 i32)))
 (memory (export "memory") 1 4)
 (tag $failure (param i32))
 (global $mode (mut i32) (i32.const 0))
 (global $next (mut i32) (i32.const 65528))
 (global $freed (mut i32) (i32.const 0))
 (global $releases (mut i32) (i32.const 0))
 (func (export "mode") (param i32) (global.set $mode (local.get 0)))
 (func (export "releases") (result i32) (global.get $releases))
 (func $allocate (export "allocate") (export "allocate-alias") (param $size i32) (result i32)
  (local $p i32)
  (call $collect)
  (if (i32.eq (global.get $mode) (i32.const 1)) (then (return (i32.const 0))))
  (if (i32.eq (global.get $mode) (i32.const 2)) (then (return (i32.const -8))))
  (if (i32.eq (global.get $mode) (i32.const 3)) (then (return (i32.const 65528))))
  (if (i32.eq (global.get $mode) (i32.const 4)) (then (throw $failure (i32.const 41))))
  (if (i32.eq (global.get $mode) (i32.const 5)) (then unreachable))
  (if (global.get $freed)
   (then (local.set $p (global.get $freed)) (global.set $freed (i32.const 0)))
   (else (local.set $p (global.get $next)) (global.set $next (i32.add (local.get $p) (local.get $size)))))
  (if (i32.gt_u (i32.add (local.get $p) (local.get $size)) (i32.mul (memory.size) (i32.const 65536)))
   (then (drop (memory.grow (i32.const 1)))))
  (call $observe (i32.const 0) (local.get $p))
  (local.get $p))
 (func $release (export "release") (export "release-alias") (param $p i32)
  (global.set $releases (i32.add (global.get $releases) (i32.const 1)))
  (call $observe (i32.const 1) (local.get $p))
  (call $collect)
  (if (i32.eq (global.get $mode) (i32.const 6)) (then unreachable))
  (if (i32.eq (global.get $mode) (i32.const 7)) (then (throw $failure (i32.const 42))))
  (global.set $freed (local.get $p)))
 (func $run (export "run") (export "run-alias") (param $p i32) (param $n i32) (param $mode i32) (result i32)
  (local $i i32) (local $sum i32)
  (call $collect)
  (if (i32.eq (local.get $mode) (i32.const 1)) (then (throw $failure (i32.const 43))))
  (if (i32.eq (local.get $mode) (i32.const 2)) (then unreachable))
  (if (i32.eq (local.get $mode) (i32.const 3)) (then (drop (memory.grow (i32.const 1)))))
  (if (i32.eq (local.get $mode) (i32.const 4)) (then (i32.store8 (local.get $p) (i32.const 255))))
  (if (i32.eq (local.get $mode) (i32.const 5))
   (then (i32.store8 (local.get $p) (i32.add (i32.load8_u (local.get $p)) (i32.const 1)))))
  (block $done (loop $bytes
   (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i32.add (local.get $sum) (i32.load8_u (i32.add (local.get $p) (local.get $i)))))
   (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $bytes)))
  (local.get $sum)))
