
;;; Test scaffolding constructs the target header through ordinary target
;;; accessors. Native uses MAKE-ARRAY. No production constructor is replaced.
#+wasm32-target
(defun loader-array-header (dimensions data offset)
  (let* ((rank (length dimensions))
         (array (case rank
                  (0 (%gvector target::subtag-arrayH 0 1 data offset 0))
                  (2 (%gvector target::subtag-arrayH 2 0 data offset 0 0 0))
                  (3 (%gvector target::subtag-arrayH 3 0 data offset 0 0 0 0))
                  (4 (%gvector target::subtag-arrayH 4 0 data offset 0 0 0 0 0))))
         (size 1))
    (declare (fixnum rank size))
    (setf (%svref array target::arrayH.rank-cell) rank
          (%svref array target::arrayH.data-vector-cell) data
          (%svref array target::arrayH.displacement-cell) offset
          (%svref array target::arrayH.flags-cell) 0)
    (do ((dims dimensions (cdr dims)) (axis 0 (1+ axis)))
        ((null dims))
      (declare (fixnum axis))
      (setf (%svref array (+ target::arrayH.dim0-cell axis)) (car dims))
      (setq size (* size (the fixnum (car dims)))))
    (setf (%svref array target::arrayH.physsize-cell) size)
    array))

#-wasm32-target
(defun loader-array-header (dimensions data offset)
  (make-array dimensions :element-type (array-element-type data)
              :displaced-to data :displaced-index-offset offset))

(defun loader-array-matrix ()
  (let* ((data (vector 0 1 2 3 4 5 6 7 8 9))
         (a (loader-array-header '(2 3) data 2)))
    (values (aref a 0 0) (aref a 0 2) (aref a 1 0) (aref a 1 2)
            (setf (aref a 1 1) 99) (svref data 6) (aref a 1 1))))

(defun loader-array-cube ()
  (let* ((data (vector 0 1 2 3 4 5 6 7 8 9 10 11))
         (a (loader-array-header '(2 2 3) data 0)))
    (values (aref a 0 0 0) (aref a 0 1 2) (aref a 1 0 1) (aref a 1 1 2)
            (setf (aref a 1 0 2) 77) (svref data 8))))

(defun loader-array-chain ()
  (let* ((data (vector 0 1 2 3 4 5 6 7 8 9 10 11))
         (base (loader-array-header '(2 5) data 1))
         (a (loader-array-header '(2 2) base 3)))
    (values (aref a 0 0) (aref a 1 1)
            (setf (aref a 0 1) 88) (svref data 5))))

(defun loader-array-vector-chain ()
  (let* ((data (vector 0 1 2 3 4 5 6 7 8 9))
         (base #+wasm32-target (%gvector target::subtag-vectorH 2 8 data 1 0)
               #-wasm32-target (make-array 8 :displaced-to data :displaced-index-offset 1 :fill-pointer 2))
         (a (loader-array-header '(2 2) base 2)))
    (loader-rwlock-allocate 18000)
    (values (aref a 0 0) (aref a 1 1)
            (setf (aref a 0 1) 93) (svref data 4))))

(defun loader-array-ranks ()
  (let* ((scalar (loader-array-header nil (vector 42) 0))
         (a (loader-array-header '(2 1 2 2) (vector 0 1 2 3 4 5 6 7) 0)))
    (values (aref scalar) (setf (aref scalar) 43) (aref scalar)
            (aref a 1 0 1 1) (setf (aref a 1 0 1 0) 66) (aref a 1 0 1 0))))

(defun loader-array-bits ()
  (let* ((data (make-array 64 :element-type 'bit :initial-element 0))
         (a (loader-array-header '(2 17) data 3)))
    (values (setf (aref a 1 15) 1) (sbit data 35)
            (setf (aref a 1 16) 1) (sbit data 36) (aref a 0 0))))

(defun loader-array-string ()
  (let* ((data (make-string 12 :initial-element #\a))
         (a (loader-array-header '(2 2 2) data 1)))
    (setf (aref a 1 1 1) #\Z)
    (values (char-code (aref a 0 0 0)) (char-code (aref a 1 1 1))
            (char-code (schar data 8)))))

(defun loader-array-evaluation ()
  (let* ((a (loader-array-header '(2 2) (vector 10 11 12 13) 0))
         (order 0))
    (values (setf (aref (progn (setq order (+ (* order 10) 1)) a)
                       (progn (setq order (+ (* order 10) 2)) 1)
                       (progn (setq order (+ (* order 10) 3)) 0))
                  (progn (setq order (+ (* order 10) 4)) 37))
            order (aref a 1 0))))

(defun loader-array-collection ()
  (let* ((data (vector nil nil nil nil nil nil nil nil))
         (a (loader-array-header '(2 2 2) data 0))
         (cell (cons 41 nil)))
    (setf (aref a 1 0 1) cell)
    (values (eq cell (aref a (progn (loader-rwlock-allocate 18000) 1) 0 1))
            (eq cell (setf (aref a 1 (progn (loader-rwlock-allocate 18000) 1) 0) cell))
            (eq cell (aref a 1 1 0)) (car (svref data 6)))))

(defun loader-array-integers ()
  (let* ((data #+wasm32-target (%alloc-misc 10 target::subtag-u32-vector 0)
               #-wasm32-target (make-array 10 :element-type '(unsigned-byte 32) :initial-element 0))
         (a (loader-array-header '(2 2 2) data 1))
         (signed #+wasm32-target (%alloc-misc 6 target::subtag-s16-vector 0)
                 #-wasm32-target (make-array 6 :element-type '(signed-byte 16) :initial-element 0))
         (b (loader-array-header '(2 3) signed 0)))
    (values (setf (aref a 1 1 1) 4294967295) (aref a 1 1 1) (aref data 8)
            (setf (aref b 1 1) -32768) (aref b 1 1) (aref signed 4))))

(defvar *loader-held-array* nil)
(defun loader-array-hold ()
  (let* ((data (vector nil nil nil nil))
         (a (loader-array-header '(2 2) data 0)))
    (setf (aref a 1 0) (cons 17 (cons 23 nil))
          *loader-held-array* a)
    t))
(defun loader-array-release ()
  (let* ((a *loader-held-array*) (cell (aref a 1 0)))
    (setq *loader-held-array* nil)
    (values (car cell) (cadr cell) (setf (aref a 1 1) cell) (eq cell (aref a 1 1)))))

(defun loader-array-operation (op a i j k new)
  (let ((%handlers% nil))
    (case op
      (0 (loader-array-header '(2 3) (vector 0 1 2 3 4 5 6 7 8) 1))
      (1 (%aref2 a i j))
      (2 (%aset2 a i j new))
      (3 (loader-array-header '(2 2 2) (vector 0 1 2 3 4 5 6 7 8) 1))
      (4 (%aref3 a i j k))
      (5 (%aset3 a i j k new))
      (6 (loader-array-header '(2 0) (vector) 0))
      (7 (loader-array-header '(2 3) (make-array 6 :element-type 'bit) 0))
      (8 (loader-array-header '(2 2 2) (make-string 8 :initial-element #\a) 0))
      (9 (vector 2 6 (vector 0 1 2 3 4 5) 0 0 2 3)))))
