;;; These are collector controls, not additions to the original-definition count.
(in-package :wasm32-compiler)

(ccl::defglobal *core-global* nil)

(defun core-collect () nil)

(defun core-probe-forms ()
   '((defun core-word-and-mask (x)
       (declare (type (unsigned-byte 32) x))
       (logand x #xffff0000))
     (defun core-word-xor-mask (x)
       (declare (type (unsigned-byte 32) x))
       (logxor #xffffffff x))
     (defun core-word-or-mask (x)
       (declare (type (unsigned-byte 32) x))
       (logior x #x80000000))
     (defun core-minus1 (x) (ccl::%negate x))
     (defun core-shift-left-domain (n x) (ccl::%ilsl n x))
     (defun core-shift-right-domain (n x) (ccl::%ilsr n x))
     (defun core-shift-signed-domain (n x) (ccl::%iasr n x))
     (defun core-libm-expt64 (x y) (let ((result (ccl::%double-float 0))) (ccl::%double-float-expt! x y result)))
     (defun core-libm-expt32 (x y) (let ((result (ccl::%short-float 0))) (ccl::%single-float-expt! x y result)))
     (defun core-libm-sin64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-sin! x result)))
     (defun core-libm-sin32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-sin! x result)))
     (defun core-libm-cos64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-cos! x result)))
     (defun core-libm-cos32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-cos! x result)))
     (defun core-libm-acos64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-acos! x result)))
     (defun core-libm-acos32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-acos! x result)))
     (defun core-libm-asin64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-asin! x result)))
     (defun core-libm-asin32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-asin! x result)))
     (defun core-libm-cosh64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-cosh! x result)))
     (defun core-libm-cosh32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-cosh! x result)))
     (defun core-libm-log64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-log! x result)))
     (defun core-libm-log32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-log! x result)))
     (defun core-libm-tan64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-tan! x result)))
     (defun core-libm-tan32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-tan! x result)))
     (defun core-libm-atan64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-atan! x result)))
     (defun core-libm-atan32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-atan! x result)))
     (defun core-libm-atan264 (x y) (let ((result (ccl::%double-float 0))) (ccl::%double-float-atan2! x y result)))
     (defun core-libm-atan232 (x y) (let ((result (ccl::%short-float 0))) (ccl::%single-float-atan2! x y result)))
     (defun core-libm-exp64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-exp! x result)))
     (defun core-libm-exp32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-exp! x result)))
     (defun core-libm-sinh64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-sinh! x result)))
     (defun core-libm-sinh32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-sinh! x result)))
     (defun core-libm-tanh64 (x) (let ((result (ccl::%double-float 0))) (ccl::%double-float-tanh! x result)))
     (defun core-libm-tanh32 (x) (let ((result (ccl::%short-float 0))) (ccl::%single-float-tanh! x result)))
     (defun core-coerce-single (x) (ccl::%short-float x))
     (defun core-transcend-destination (x)
       (let ((cell (list (ccl::%double-float 0))))
         (values (ccl::%double-float-sin! x (car cell)) (car cell))))
     (defun core-transcend-condition (x)
       (handler-case (ccl::%double-float-log! x (ccl::%double-float 0))
         (division-by-zero () 7)
         (floating-point-invalid-operation () 8)))
     (defun core-log-condition (x)
       (handler-case (ccl::%double-float-log! x (ccl::%double-float 0))
         (division-by-zero () 7)
         (floating-point-invalid-operation () 8)))
     (defun core-coerce-double (x) (ccl::%double-float x))
     (defun core-natural-left (x) (declare (type (unsigned-byte 32) x)) (the (unsigned-byte 32) (ash x 3)))
     (defun core-natural-right (x) (declare (type (unsigned-byte 32) x)) (ash x -3))
     (defun core-global-cell (x)
       (setq *core-global* (progn (core-collect) (cons x x)))
       (core-collect)
       *core-global*)
     (defun core-retry-vector (n x) (ccl::%alloc-misc n target::subtag-simple-vector x))
     (defun core-retry-list (n x) (make-list n :initial-element x))
     (defun core-uvset-checked (v i x) (ccl::uvset v i x))
     (defun core-s8 (v i) (declare (type (simple-array (signed-byte 8) (*)) v)) (aref v i))
     (defun core-u16 (v i) (declare (type (simple-array (unsigned-byte 16) (*)) v)) (aref v i))
     (defun core-s16 (v i) (declare (type (simple-array (signed-byte 16) (*)) v)) (aref v i))
     (defun core-u32 (v i) (declare (type (simple-array (unsigned-byte 32) (*)) v)) (aref v i))
     (defun core-s32 (v i) (declare (type (simple-array (signed-byte 32) (*)) v)) (aref v i))
     (defun core-aux (x &optional (y x yp) &aux (a (cons y yp)) (b (progn (core-collect) (car a))))
       (values x y yp a b))
     (defun core-lexpr (ccl::&lexpr args)
       (let ((n (ccl::%lexpr-count args)))
         (core-collect)
         (values n (if (zerop n) nil (ccl::%lexpr-ref args n 0))
                   (if (zerop n) nil (ccl::%lexpr-ref args n (1- n))))))
     (defun core-lexpr-zero (ccl::&lexpr args) (declare (ignore args)) (values))
     (defun core-list-star (x y)
       (list* x (progn (core-collect) y) (progn (core-collect) (cons x y))))
     (defun core-vector (x y)
       (vector x (progn (core-collect) y) x))
     (defun core-make-vector (n x)
       (ccl::%alloc-misc n target::subtag-simple-vector (progn (core-collect) x)))
     (defun core-make-string (n x)
       (ccl::%alloc-misc n target::subtag-simple-base-string x))
     (defun core-make-octets (n x)
       (ccl::%alloc-misc n target::subtag-u8-vector x))
     (defun core-make-list (n x) (make-list n :initial-element (progn (core-collect) x)))
     (defun core-nth-value (i x)
       (nth-value i (values (progn (core-collect) x) (cons x x) 7)))
     (defun core-uvref (v i) (ccl::uvref (progn (core-collect) v) i))
     (defun core-uvset (v i x)
       (values (ccl::uvset v (progn (core-collect) i) (progn (core-collect) x)) v))
     (defun core-shifts (n x)
       (values (ccl::%ilsl n x) (ccl::%iasr n x) (ccl::%ilsr n x)))
     (defun core-logbitp (i x) (logbitp i x))
     (defun core-assq-identity (key)
       (let* ((pair (cons key 7))
              (alist (list nil pair (cons key 9))))
         (values (eq pair (ccl::assq (progn (core-collect) key)
                                   (progn (core-collect) alist)))
                 (cdr (ccl::assq key alist)))))
     (defun core-signed-zero-literal (x) (- x 0))
     (defun core-signed-zero-variable (x y) (- x y))
     (defun core-byte-store (v i value)
      (declare (type (simple-array (unsigned-byte 8) (*)) v))
      (setf (aref v i) value))
    (defun core-computed-call (f x) (funcall f x))
    (defun core-computed-inner (f x) (cons (funcall f x) nil))
    (defun core-computed-apply (f x) (apply f (list x)))
    (defun core-computed-inner-apply (f x) (cons (apply f (list x)) nil))
    (defun core-eql (x y) (eql x y))
    (defun core-zero (x) (zerop x))
    (defun core-positive-loop (x)
      (do ((i x (1- i))) ((not (ccl::int>0-p i)) i)))
    (defun core-izerop (x) (declare (fixnum x)) (ccl::%izerop x))
    (defun core-numeric-ir (x y)
      (values (ccl::+-2 x y) (ccl::--2 x y) (ccl::*-2 x y) (ccl::/-2 x y)
              (ccl::<-2 x y) (ccl::<=-2 x y) (ccl::=-2 x y)
              (ccl::/=-2 x y) (ccl::>=-2 x y) (ccl::>-2 x y)))
    (defun core-byte-order (v)
      (declare (type (simple-array (unsigned-byte 8) (*)) v))
      (let ((effects nil))
        (values (setf (aref (the (simple-array (unsigned-byte 8) (*)) (progn (push 1 effects) v))
                           (progn (push 2 effects) (core-collect) 3))
                      (progn (push 3 effects) (core-collect) 2))
                effects v)))
    (defun core-ilognot (x) (ccl::%ilognot x))
    (defun core-fixnum-less (x y) (declare (fixnum x y)) (ccl::<-2 x y))
    (defun core-format-order (x)
      (let ((effects nil))
        (handler-case
            (error (progn (push 1 effects) "~s ~s")
                   (progn (push 2 effects) x)
                   (progn (push 3 effects) (core-collect) x))
          (simple-error (c)
            (values effects (simple-condition-format-arguments c))))))
    (defun core-format-decline (x)
      (let ((seen nil))
        (values (handler-bind ((simple-condition
                                (lambda (c) (setq seen (simple-condition-format-arguments c)))))
                  (signal "~s" x))
                seen)))
    (defun core-simple-initargs (x)
      (handler-case
          (error 'simple-error :format-control "~s" :format-arguments (list x)
                               :format-control "ignored")
        (simple-error (c)
          (values (simple-condition-format-control c) (simple-condition-format-arguments c)))))
    (defun core-format-error (x)
       (handler-case (error "Bad argument: ~s" x)
         (simple-error (c) (values (simple-condition-format-control c)
                                  (simple-condition-format-arguments c)))))
    (defun core-format-signal (x)
      (handler-case (signal "Notice: ~s" x)
        (simple-condition (c) (values (simple-condition-format-control c)
                                     (simple-condition-format-arguments c)))))
    (defun core-format-collect (x)
      (handler-case (error "Bad argument: ~s" (progn (core-collect) x))
        (simple-error (c)
          (core-collect)
          (values (simple-condition-format-control c)
                  (simple-condition-format-arguments c)))))
    (defun core-type-error (x)
      (handler-case (error 'type-error :datum x :expected-type 'integer)
        (type-error (c) (values (type-error-datum c) (type-error-expected-type c)))))
    (defun core-dynamic-format (control x)
      (handler-case (signal control x)
        (simple-condition (c) (values (simple-condition-format-control c)
                                     (simple-condition-format-arguments c)))))
    (defun core-schar (string index) (schar string index))
    (defun core-char-code (char) (char-code char))
    (defun core-code-char (code) (code-char code))
    (defun core-set-char (string index char) (setf (schar string index) char))
    (defun core-access (x i) (ccl::%svref x i))
    (defun core-struct-access (x) (ccl::struct-ref x 0))
    (defun core-slot-access (x) (ccl::%slot-ref x 0))
    (defun core-integer-divide (a b) (/ a b))
    (defun core-divide-order (a b)
      (let ((order nil))
        (let ((answer (/ (progn (push 1 order) a)
                         (progn (core-collect) (push 2 order) b))))
          (values answer order a b))))
    (defun core-divide-zero (a b)
      (let ((clean nil))
        (values (handler-case (unwind-protect (/ a b) (setq clean t))
                  (division-by-zero () :zero)
                  (type-error (c)
                    (list :type (type-error-datum c)
                                (type-error-expected-type c))))
                clean)))
    (defun core-register (name info)
      (let ((ccl::*istruct-cells* nil))
        (let ((cell (ccl::register-istruct-cell name)))
          (ccl::set-istruct-cell-info cell info)
          (core-collect)
          (values (eq cell (ccl::register-istruct-cell name)) (cdr cell)))))
    (defun core-symbol-state (name value)
      (values (boundp name)
              (progn (ccl::%set-sym-value name value) (core-collect)
                     (values (boundp name) (ccl::%sym-value name)))
              (ccl::%sym-global-value name)))
    (defun core-less (a b) (< a b))
    (defun core-ldb (x)
      (values (ldb (byte 8 8) x) (ldb (byte 29 0) x)
              (ldb (byte 4 50) x) (ldb (byte 0 0) x)))
    (defun core-logical-error (x)
      (handler-case (logand x 7)
        (type-error (c) (core-collect)
          (values (type-error-datum c) (type-error-expected-type c)))))
    (defun core-assq (key alist) (ccl::assq key alist))
    (defun core-logical (a b)
      (values (logand a b) (logior a b) (logand a b -1) (logior a b 16)
              (logand) (logior)))
    (defun core-subtract-call (a b c)
      (let ((order nil))
        (values (- (progn (push 1 order) a)
                   (progn (core-collect) (push 2 order) b)
                   (progn (push 3 order) c))
                (- a) order)))
    (defun core-type-tests (x)
      (values (typep x 'integer) (typep x '(integer 0 255))
              (typep x '(or null string)) (typep x '(and integer (not (eql 7))))
              (typep x '(unsigned-byte 8)) (typep x '(member nil t 7))))
    (defun core-require-integer (x)
      (handler-case (ccl::require-type (progn (core-collect) x) 'integer)
        (type-error (c) (values :type (type-error-datum c) (type-error-expected-type c)))))
    (defun core-badarg (x)
      (handler-case (ccl::%badarg x 'integer)
        (type-error (c) (core-collect) (values :type (type-error-datum c) (type-error-expected-type c)))))
    (defun core-node-size () target::node-size)
    (defun core-gvector (x)
      (ccl::%gvector target::subtag-simple-vector x (progn (core-collect) x)))
    (defun core-ref (x)
      (ccl::%svref x (progn (core-collect) 1)))
    (defun core-set (x y)
      (ccl::%svset x (progn (core-collect) 0)
                  (progn (core-collect) y))
      x)
    (defun core-struct (x)
      (let ((structure (ccl::%gvector target::subtag-struct nil x)))
        (core-collect)
        (ccl::struct-ref structure 1)))
    (defun core-slot (x)
      (ccl::%slot-ref (ccl::%gvector target::subtag-slot-vector x)
                     (progn (core-collect) 0)))
    (defun core-cleanup (x)
      (unwind-protect
          (ccl::%gvector target::subtag-simple-vector x x)
        (core-collect)))
    (defun core-transfer (x)
      (catch 'done
        (ccl::%gvector target::subtag-simple-vector
                      x (progn (core-collect) (throw 'done x)))))))

(defun core-add-probes (native-forms &optional (forms (cons '(defun core-collect () nil) (core-probe-forms))))
  (dolist (form forms)
    (let* ((name (second form))
           (wire (if (eq name 'core-collect) "collector_probe"
                     (string-downcase (substitute #\_ #\- (symbol-name name)))))
           (result (let ((*b-allocation-retry* (member name '(core-retry-vector core-retry-list))))
                     (call-with-target (lambda () (compile-bootstrap-form form wire nil))))))
      (setf (getf result :source-name) name)
      (push (list form result) *core-candidates*)
      (setf (gethash name *core-native-functions*)
            (ccl::compile-named-function
             (bootstrap-function-form (if (eq name 'core-collect) form
                                        (find name native-forms :key #'second))) :name name)))))
