;;; Generated from accepted D1 and production TCR schemas; do not edit.
(defpackage "WASM32" (:use))
(in-package "WASM32")
(cl:defconstant arrayh.data-vector 6)
(cl:defconstant arrayh.data-vector-cell 2)
(cl:defconstant arrayh.data-vector.raw-offset 12)
(cl:defconstant arrayh.dim0-cell 5)
(cl:defconstant arrayh.displacement 10)
(cl:defconstant arrayh.displacement-cell 3)
(cl:defconstant arrayh.displacement.raw-offset 16)
(cl:defconstant arrayh.flags 14)
(cl:defconstant arrayh.flags-cell 4)
(cl:defconstant arrayh.flags-cell-bits-byte (cl:byte 8 0))
(cl:defconstant arrayh.flags-cell-subtag-byte (cl:byte 8 8))
(cl:defconstant arrayh.flags.raw-offset 20)
(cl:defconstant arrayh.header -6)
(cl:defconstant arrayh.header.raw-offset 0)
(cl:defconstant arrayh.physsize 2)
(cl:defconstant arrayh.physsize-cell 1)
(cl:defconstant arrayh.physsize.raw-offset 8)
(cl:defconstant arrayh.rank -2)
(cl:defconstant arrayh.rank-cell 0)
(cl:defconstant arrayh.rank.raw-offset 4)
(cl:defconstant arrayh.size 24)
(cl:defconstant bitmap-shift 5)
(cl:defconstant canonical-nil-value 77825)
(cl:defconstant canonical-t-value 77838)
(cl:defconstant charcode-shift 8)
(cl:defconstant complex-double-float.header -6)
(cl:defconstant complex-double-float.header.raw-offset 0)
(cl:defconstant complex-double-float.imagpart 10)
(cl:defconstant complex-double-float.imagpart-high 14)
(cl:defconstant complex-double-float.imagpart-high.raw-offset 20)
(cl:defconstant complex-double-float.imagpart-low 10)
(cl:defconstant complex-double-float.imagpart-low.raw-offset 16)
(cl:defconstant complex-double-float.pad -2)
(cl:defconstant complex-double-float.pad.raw-offset 4)
(cl:defconstant complex-double-float.realpart 2)
(cl:defconstant complex-double-float.realpart-high 6)
(cl:defconstant complex-double-float.realpart-high.raw-offset 12)
(cl:defconstant complex-double-float.realpart-low 2)
(cl:defconstant complex-double-float.realpart-low.raw-offset 8)
(cl:defconstant complex-double-float.size 24)
(cl:defconstant complex-single-float.header -6)
(cl:defconstant complex-single-float.header.raw-offset 0)
(cl:defconstant complex-single-float.imagpart 6)
(cl:defconstant complex-single-float.imagpart.raw-offset 12)
(cl:defconstant complex-single-float.pad -2)
(cl:defconstant complex-single-float.pad.raw-offset 4)
(cl:defconstant complex-single-float.realpart 2)
(cl:defconstant complex-single-float.realpart.raw-offset 8)
(cl:defconstant complex-single-float.size 16)
(cl:defconstant complex.header -6)
(cl:defconstant complex.header.raw-offset 0)
(cl:defconstant complex.imagpart 2)
(cl:defconstant complex.imagpart.raw-offset 8)
(cl:defconstant complex.realpart -2)
(cl:defconstant complex.realpart.raw-offset 4)
(cl:defconstant complex.size 12)
(cl:defconstant cons-bias 1)
(cl:defconstant cons.car 3)
(cl:defconstant cons.car.raw-offset 4)
(cl:defconstant cons.cdr -1)
(cl:defconstant cons.cdr.raw-offset 0)
(cl:defconstant cons.size 8)
(cl:defconstant dnode-align-bits 3)
(cl:defconstant dnode-shift 3)
(cl:defconstant dnode-size 8)
(cl:defconstant double-float-header 791)
(cl:defconstant double-float.header -6)
(cl:defconstant double-float.header.raw-offset 0)
(cl:defconstant double-float.pad -2)
(cl:defconstant double-float.pad.raw-offset 4)
(cl:defconstant double-float.size 16)
(cl:defconstant double-float.val-high 6)
(cl:defconstant double-float.val-high.raw-offset 12)
(cl:defconstant double-float.value 2)
(cl:defconstant double-float.value.raw-offset 8)
(cl:defconstant fixnum-one 4)
(cl:defconstant fixnum-shift 2)
(cl:defconstant fixnum1 4)
(cl:defconstant fixnummask 3)
(cl:defconstant fixnumone 4)
(cl:defconstant fixnumshift 2)
(cl:defconstant fulltag-cons 1)
(cl:defconstant fulltag-even-fixnum 0)
(cl:defconstant fulltag-imm 3)
(cl:defconstant fulltag-immheader 7)
(cl:defconstant fulltag-misc 6)
(cl:defconstant fulltag-nodeheader 2)
(cl:defconstant fulltag-odd-fixnum 4)
(cl:defconstant fulltagmask 7)
(cl:defconstant illegal-marker 91)
(cl:defconstant interrupt-level-binding-index 4)
(cl:defconstant macptr-header 799)
(cl:defconstant macptr.address -2)
(cl:defconstant macptr.address.raw-offset 4)
(cl:defconstant macptr.domain 2)
(cl:defconstant macptr.domain.raw-offset 8)
(cl:defconstant macptr.header -6)
(cl:defconstant macptr.header.raw-offset 0)
(cl:defconstant macptr.size 16)
(cl:defconstant macptr.type 6)
(cl:defconstant macptr.type.raw-offset 12)
(cl:defconstant max-1-bit-constant-index 16777216)
(cl:defconstant max-16-bit-constant-index 16777216)
(cl:defconstant max-16-bit-ivector-subtag 223)
(cl:defconstant max-32-bit-constant-index 16777216)
(cl:defconstant max-32-bit-ivector-subtag 191)
(cl:defconstant max-64-bit-constant-index 16777216)
(cl:defconstant max-8-bit-constant-index 16777216)
(cl:defconstant max-8-bit-ivector-subtag 207)
(cl:defconstant max-float-subtag 23)
(cl:defconstant max-non-array-imm-subtag 159)
(cl:defconstant max-non-array-node-subtag 146)
(cl:defconstant max-numeric-subtag 26)
(cl:defconstant max-rational-subtag 10)
(cl:defconstant max-real-subtag 23)
(cl:defconstant min-16-bit-ivector-subtag 215)
(cl:defconstant min-8-bit-ivector-subtag 199)
(cl:defconstant min-cl-ivector-subtag 159)
(cl:defconstant min-float-subtag 15)
(cl:defconstant min-non-numeric-imm-subtag 31)
(cl:defconstant min-non-numeric-node-subtag 34)
(cl:defconstant min-numeric-subtag 7)
(cl:defconstant misc-bias 6)
(cl:defconstant misc-complex-dfloat-offset 2)
(cl:defconstant misc-data-offset -2)
(cl:defconstant misc-dfloat-offset 2)
(cl:defconstant misc-header-offset -6)
(cl:defconstant misc-subtag-offset -6)
(cl:defconstant nbits-in-byte 8)
(cl:defconstant nbits-in-word 32)
(cl:defconstant ncharcodebits 8)
(cl:defconstant nfixnumtagbits 2)
(cl:defconstant nilsym-offset 45)
(cl:defconstant nlisptagbits 2)
(cl:defconstant node-size 4)
(cl:defconstant ntagbits 3)
(cl:defconstant num-subtag-bits 8)
(cl:defconstant one-digit-bignum-header 263)
(cl:defconstant ratio.denom 2)
(cl:defconstant ratio.denom.raw-offset 8)
(cl:defconstant ratio.header -6)
(cl:defconstant ratio.header.raw-offset 0)
(cl:defconstant ratio.numer -2)
(cl:defconstant ratio.numer.raw-offset 4)
(cl:defconstant ratio.size 12)
(cl:defconstant single-float-header 271)
(cl:defconstant single-float.header -6)
(cl:defconstant single-float.header.raw-offset 0)
(cl:defconstant single-float.size 8)
(cl:defconstant single-float.value -2)
(cl:defconstant single-float.value.raw-offset 4)
(cl:defconstant slot-unbound-marker 83)
(cl:defconstant subtag-arrayh 234)
(cl:defconstant subtag-basic-stream 50)
(cl:defconstant subtag-bignum 7)
(cl:defconstant subtag-bit-vector 255)
(cl:defconstant subtag-character 75)
(cl:defconstant subtag-complex 26)
(cl:defconstant subtag-complex-double-float 79)
(cl:defconstant subtag-complex-double-float-vector 247)
(cl:defconstant subtag-complex-single-float 71)
(cl:defconstant subtag-complex-single-float-vector 239)
(cl:defconstant subtag-dead-macptr 39)
(cl:defconstant subtag-double-float 23)
(cl:defconstant subtag-double-float-vector 231)
(cl:defconstant subtag-fixnum-vector 183)
(cl:defconstant subtag-hash-vector 74)
(cl:defconstant subtag-illegal 91)
(cl:defconstant subtag-instance 114)
(cl:defconstant subtag-istruct 130)
(cl:defconstant subtag-macptr 31)
(cl:defconstant subtag-no-thread-local-binding 243)
(cl:defconstant subtag-package 98)
(cl:defconstant subtag-pool 82)
(cl:defconstant subtag-ratio 10)
(cl:defconstant subtag-s16-vector 223)
(cl:defconstant subtag-s32-vector 175)
(cl:defconstant subtag-s8-vector 207)
(cl:defconstant subtag-simple-base-string 191)
(cl:defconstant subtag-simple-vector 250)
(cl:defconstant subtag-single-float 15)
(cl:defconstant subtag-single-float-vector 159)
(cl:defconstant subtag-slot-unbound 83)
(cl:defconstant subtag-slot-vector 106)
(cl:defconstant subtag-struct 122)
(cl:defconstant subtag-symbol 58)
(cl:defconstant subtag-u16-vector 215)
(cl:defconstant subtag-u32-vector 167)
(cl:defconstant subtag-u8-vector 199)
(cl:defconstant subtag-unbound 51)
(cl:defconstant subtag-value-cell 138)
(cl:defconstant subtag-vectorh 242)
(cl:defconstant subtag-weak 90)
(cl:defconstant subtagmask 255)
(cl:defconstant symbol-header 1850)
(cl:defconstant symbol.binding-index 22)
(cl:defconstant symbol.binding-index.raw-offset 28)
(cl:defconstant symbol.fcell 6)
(cl:defconstant symbol.fcell.raw-offset 12)
(cl:defconstant symbol.flags 14)
(cl:defconstant symbol.flags.raw-offset 20)
(cl:defconstant symbol.header -6)
(cl:defconstant symbol.header.raw-offset 0)
(cl:defconstant symbol.package-predicate 10)
(cl:defconstant symbol.package-predicate.raw-offset 16)
(cl:defconstant symbol.plist 18)
(cl:defconstant symbol.plist.raw-offset 24)
(cl:defconstant symbol.pname -2)
(cl:defconstant symbol.pname.raw-offset 4)
(cl:defconstant symbol.size 32)
(cl:defconstant symbol.vcell 2)
(cl:defconstant symbol.vcell.raw-offset 8)
(cl:defconstant t-offset 13)
(cl:defconstant tag-fixnum 0)
(cl:defconstant tag-imm 3)
(cl:defconstant tag-list 1)
(cl:defconstant tag-misc 2)
(cl:defconstant tagmask 3)
(cl:defconstant target-most-negative-fixnum -536870912)
(cl:defconstant target-most-positive-fixnum 536870911)
(cl:defconstant tcr.active_request 152)
(cl:defconstant tcr.active_request.width 4)
(cl:defconstant tcr.alloc_base 56)
(cl:defconstant tcr.alloc_base.width 4)
(cl:defconstant tcr.alloc_limit 52)
(cl:defconstant tcr.alloc_limit.width 4)
(cl:defconstant tcr.alloc_pointer 48)
(cl:defconstant tcr.alloc_pointer.width 4)
(cl:defconstant tcr.allocation_quantum_log2 60)
(cl:defconstant tcr.allocation_quantum_log2.width 4)
(cl:defconstant tcr.c_stack_pointer 168)
(cl:defconstant tcr.c_stack_pointer.width 4)
(cl:defconstant tcr.csp 88)
(cl:defconstant tcr.csp.width 4)
(cl:defconstant tcr.csp_base 92)
(cl:defconstant tcr.csp_base.width 4)
(cl:defconstant tcr.csp_limit 96)
(cl:defconstant tcr.csp_limit.width 4)
(cl:defconstant tcr.db_link 112)
(cl:defconstant tcr.db_link.width 4)
(cl:defconstant tcr.debug_policy 196)
(cl:defconstant tcr.debug_policy.width 4)
(cl:defconstant tcr.error_service_mode 192)
(cl:defconstant tcr.error_service_mode.width 4)
(cl:defconstant tcr.foreign_descriptor 144)
(cl:defconstant tcr.foreign_descriptor.width 4)
(cl:defconstant tcr.fp_control 200)
(cl:defconstant tcr.fp_control.width 4)
(cl:defconstant tcr.frame_generation 136)
(cl:defconstant tcr.frame_generation.width 4)
(cl:defconstant tcr.frame_head 132)
(cl:defconstant tcr.frame_head.width 4)
(cl:defconstant tcr.handler_checkpoint 140)
(cl:defconstant tcr.handler_checkpoint.width 4)
(cl:defconstant tcr.lifetime_generation 8)
(cl:defconstant tcr.lifetime_generation.width 4)
(cl:defconstant tcr.mailbox_id 164)
(cl:defconstant tcr.mailbox_id.width 4)
(cl:defconstant tcr.mv_base 120)
(cl:defconstant tcr.mv_base.width 4)
(cl:defconstant tcr.mv_count 116)
(cl:defconstant tcr.mv_count.width 4)
(cl:defconstant tcr.mv_owner_top 124)
(cl:defconstant tcr.mv_owner_top.width 4)
(cl:defconstant tcr.next_method_context 188)
(cl:defconstant tcr.next_method_context.width 4)
(cl:defconstant tcr.pending 36)
(cl:defconstant tcr.pending.width 4)
(cl:defconstant tcr.registry_next 12)
(cl:defconstant tcr.registry_next.width 4)
(cl:defconstant tcr.registry_prev 16)
(cl:defconstant tcr.registry_prev.width 4)
(cl:defconstant tcr.request_block_base 156)
(cl:defconstant tcr.request_block_base.width 4)
(cl:defconstant tcr.request_count 160)
(cl:defconstant tcr.request_count.width 4)
(cl:defconstant tcr.root_head 128)
(cl:defconstant tcr.root_head.width 4)
(cl:defconstant tcr.scratch0 180)
(cl:defconstant tcr.scratch0.width 4)
(cl:defconstant tcr.scratch1 184)
(cl:defconstant tcr.scratch1.width 4)
(cl:defconstant tcr.size 256)
(cl:defconstant tcr.stack_reserve_bytes 100)
(cl:defconstant tcr.stack_reserve_bytes.width 4)
(cl:defconstant tcr.state 32)
(cl:defconstant tcr.state.width 4)
(cl:defconstant tcr.stop_generation 40)
(cl:defconstant tcr.stop_generation.width 4)
(cl:defconstant tcr.tcr_address 20)
(cl:defconstant tcr.tcr_address.width 4)
(cl:defconstant tcr.tcr_index 0)
(cl:defconstant tcr.tcr_index.width 4)
(cl:defconstant tcr.tlb_limit 108)
(cl:defconstant tcr.tlb_limit.width 4)
(cl:defconstant tcr.tlb_pointer 104)
(cl:defconstant tcr.tlb_pointer.width 4)
(cl:defconstant tcr.tls_base 172)
(cl:defconstant tcr.tls_base.width 4)
(cl:defconstant tcr.tls_size 176)
(cl:defconstant tcr.tls_size.width 4)
(cl:defconstant tcr.tsp 76)
(cl:defconstant tcr.tsp.width 4)
(cl:defconstant tcr.tsp_base 80)
(cl:defconstant tcr.tsp_base.width 4)
(cl:defconstant tcr.tsp_limit 84)
(cl:defconstant tcr.tsp_limit.width 4)
(cl:defconstant tcr.unwind_state 148)
(cl:defconstant tcr.unwind_state.width 4)
(cl:defconstant tcr.vsp 64)
(cl:defconstant tcr.vsp.width 4)
(cl:defconstant tcr.vsp_base 68)
(cl:defconstant tcr.vsp_base.width 4)
(cl:defconstant tcr.vsp_limit 72)
(cl:defconstant tcr.vsp_limit.width 4)
(cl:defconstant tcr.worker_id 4)
(cl:defconstant tcr.worker_id.width 4)
(cl:defconstant three-digit-bignum-header 775)
(cl:defconstant two-digit-bignum-header 519)
(cl:defconstant unbound-marker 51)
(cl:defconstant undefined 51)
(cl:defconstant value-cell-header 394)
(cl:defconstant value-cell.header -6)
(cl:defconstant value-cell.header.raw-offset 0)
(cl:defconstant value-cell.size 8)
(cl:defconstant value-cell.value -2)
(cl:defconstant value-cell.value.raw-offset 4)
(cl:defconstant vectorh.data-vector 6)
(cl:defconstant vectorh.data-vector.raw-offset 12)
(cl:defconstant vectorh.displacement 10)
(cl:defconstant vectorh.displacement.raw-offset 16)
(cl:defconstant vectorh.flags 14)
(cl:defconstant vectorh.flags.raw-offset 20)
(cl:defconstant vectorh.header -6)
(cl:defconstant vectorh.header.raw-offset 0)
(cl:defconstant vectorh.logsize -2)
(cl:defconstant vectorh.logsize.raw-offset 4)
(cl:defconstant vectorh.physsize 2)
(cl:defconstant vectorh.physsize.raw-offset 8)
(cl:defconstant vectorh.size 24)
(cl:defconstant word-shift 2)
(cl:defconstant word-size-in-bytes 4)
(cl:defconstant xmacptr.address -2)
(cl:defconstant xmacptr.address.raw-offset 4)
(cl:defconstant xmacptr.domain 2)
(cl:defconstant xmacptr.domain.raw-offset 8)
(cl:defconstant xmacptr.flags 10)
(cl:defconstant xmacptr.flags.raw-offset 16)
(cl:defconstant xmacptr.header -6)
(cl:defconstant xmacptr.header.raw-offset 0)
(cl:defconstant xmacptr.link 14)
(cl:defconstant xmacptr.link.raw-offset 20)
(cl:defconstant xmacptr.size 24)
(cl:defconstant xmacptr.type 6)
(cl:defconstant xmacptr.type.raw-offset 12)
(cl:defun unavailable-array-size (cl:&rest args) (cl:declare (cl:ignore args)) (cl:error "WASM32 array-size lowering not implemented"))
(cl:defun unavailable-array-type (cl:&rest args) (cl:declare (cl:ignore args)) (cl:error "WASM32 array-type lowering not implemented"))
(cl:defparameter *target-arch*
  (arch::make-target-arch :name :wasm32 :package-name "WASM32"
    :big-endian cl:nil :single-float-tag-is-subtag cl:t :symbol-tag-is-subtag cl:t
    :uvector-subtags '((:bignum . 7) (:ratio . 10) (:single-float . 15) (:double-float . 23) (:complex . 26) (:complex-single-float . 71) (:complex-double-float . 79) (:symbol . 58) (:macptr . 31) (:struct . 122) (:istruct . 130) (:pool . 82) (:population . 90) (:hash-vector . 74) (:package . 98) (:value-cell . 138) (:instance . 114) (:slot-vector . 106) (:basic-stream . 50) (:simple-string . 191) (:bit-vector . 255) (:signed-8-bit-vector . 207) (:unsigned-8-bit-vector . 199) (:signed-16-bit-vector . 223) (:unsigned-16-bit-vector . 215) (:signed-32-bit-vector . 175) (:fixnum-vector . 183) (:unsigned-32-bit-vector . 167) (:single-float-vector . 159) (:double-float-vector . 231) (:simple-vector . 250) (:complex-single-float-vector . 239) (:complex-double-float-vector . 247) (:vector-header . 242) (:array-header . 234) (:min-cl-ivector-subtag . 159))
    :car-offset cons.car
    :cdr-offset cons.cdr
    :charcode-shift charcode-shift
    :cons-tag fulltag-cons
    :double-float-tag subtag-double-float
    :fixnum-shift fixnumshift
    :fixnum-tag tag-fixnum
    :fulltag-misc fulltag-misc
    :fulltagmask fulltagmask
    :lisp-node-size node-size
    :max-1-bit-constant-index max-1-bit-constant-index
    :max-16-bit-constant-index max-16-bit-constant-index
    :max-32-bit-constant-index max-32-bit-constant-index
    :max-64-bit-constant-index max-64-bit-constant-index
    :max-8-bit-constant-index max-8-bit-constant-index
    :misc-data-offset misc-data-offset
    :misc-dfloat-offset misc-dfloat-offset
    :misc-subtag-offset misc-subtag-offset
    :most-negative-fixnum target-most-negative-fixnum
    :most-positive-fixnum target-most-positive-fixnum
    :nbits-in-word nbits-in-word
    :nil-value canonical-nil-value
    :nlisptagbits nlisptagbits
    :ntagbits ntagbits
    :null-tag fulltag-cons
    :single-float-tag subtag-single-float
    :slot-unbound-marker-value slot-unbound-marker
    :subtag-char subtag-character
    :symbol-tag subtag-symbol
    :t-offset t-offset
    :unbound-marker-value unbound-marker
    :word-shift word-shift
    :array-data-size-function #'unavailable-array-size
    :array-type-name-from-ctype-function #'unavailable-array-type))
(cl:provide "WASM32-ARCH")

(cl:in-package :wasm32)
(cl:defconstant subtag-function 42)

(cl:in-package :wasm32)

(arch::defarchmacro :wasm32 ccl::symptr->symvector (s)
  s)

(arch::defarchmacro :wasm32 ccl::symvector->symptr (s)
  s)

(cl:in-package :ccl)

(defun wasm32-array-type-name-from-ctype (ctype)
  (when (typep ctype 'ccl::array-ctype)
    (let* ((element-type (ccl::array-ctype-element-type ctype)))
      (typecase element-type
        (ccl::class-ctype
         (let* ((class (ccl::class-ctype-class element-type)))
           (if (or (eq class ccl::*character-class*)
                   (eq class ccl::*base-char-class*)
                   (eq class ccl::*standard-char-class*))
             :simple-string
             :simple-vector)))
        (ccl::numeric-ctype
         (if (eq (ccl::numeric-ctype-complexp element-type) :complex)
           (case (ccl::numeric-ctype-format element-type)
             (single-float :complex-single-float-vector)
             (double-float :complex-double-float-vector)
             (t :simple-vector))
           (case (ccl::numeric-ctype-class element-type)
             (integer
              (let* ((low (ccl::numeric-ctype-low element-type))
                     (high (ccl::numeric-ctype-high element-type)))
                (cond ((or (null low) (null high)) :simple-vector)
                      ((and (>= low 0) (<= high 1) :bit-vector))
                      ((and (>= low 0) (<= high 255)) :unsigned-8-bit-vector)
                      ((and (>= low 0) (<= high 65535)) :unsigned-16-bit-vector)
                      ((and (>= low 0) (<= high #xffffffff) :unsigned-32-bit-vector))
                      ((and (>= low -128) (<= high 127)) :signed-8-bit-vector)
                      ((and (>= low -32768) (<= high 32767) :signed-16-bit-vector))
                      ((and (>= low wasm32::target-most-negative-fixnum)
                            (<= high wasm32::target-most-positive-fixnum))
                       :fixnum-vector)
                      ((and (>= low (ash -1 31)) (<= high (1- (ash 1 31))))
                       :signed-32-bit-vector)
                      (t :simple-vector))))
             (float
              (case (ccl::numeric-ctype-format element-type)
                ((double-float long-float) :double-float-vector)
                ((single-float short-float) :single-float-vector)
                (t :simple-vector)))
             (t :simple-vector))))
        (ccl::unknown-ctype)
        (ccl::named-ctype
         (if (eq element-type ccl::*universal-type*)
           :simple-vector))
        (t nil)))))

(setf (arch::target-array-type-name-from-ctype-function wasm32::*target-arch*)
      #'wasm32-array-type-name-from-ctype)

(cl:in-package :wasm32)

;;; DEFINE-FIXEDSIZED-OBJECT publishes these indices on the native targets.
;;; D1's raw offsets already include the header; node access starts after it.
(cl:defconstant symbol.pname-cell 0)
(cl:defconstant symbol.vcell-cell 1)
(cl:defconstant symbol.fcell-cell 2)
(cl:defconstant symbol.package-predicate-cell 3)
(cl:defconstant symbol.flags-cell 4)
(cl:defconstant symbol.plist-cell 5)
(cl:defconstant symbol.binding-index-cell 6)
(cl:defconstant symbol.element-count 7)

;;; D1 node indices match the 32-bit CCL object definitions in x8632-arch.lisp.
;;; Describing a lock does not implement its kernel operations.
(cl:in-package :wasm32)
(cl:defconstant subtag-lock 66)
(cl:defconstant lock._value-cell 0)
(cl:defconstant lock.kind-cell 1)
(cl:defconstant lock.writer-cell 2)
(cl:defconstant lock.name-cell 3)
(cl:defconstant lock.whostate-cell 4)
(cl:defconstant lock.whostate-2-cell 5)
(cl:defconstant vectorH.logsize-cell 0)
(cl:defconstant vectorH.physsize-cell 1)
(cl:defconstant vectorH.data-vector-cell 2)
(cl:defconstant vectorH.displacement-cell 3)
(cl:defconstant vectorH.flags-cell 4)
(cl:defconstant arrayH.rank-cell 0)
(cl:defconstant arrayH.physsize-cell 1)
(cl:defconstant arrayH.data-vector-cell 2)
(cl:defconstant arrayH.displacement-cell 3)
(cl:defconstant arrayH.flags-cell 4)
(cl:defconstant arrayH.dim0-cell 5)
(cl:defconstant arrayH.flags-cell-subtag-byte (cl:byte 8 8))

;;; Target provider protocol; not native OS constants or implemented capabilities.
(cl:defconstant io-seek-set 0)
(cl:defconstant io-seek-cur 1)
(cl:defconstant os-seek-end 2)
(cl:defconstant os-eperm 1)
(cl:defconstant os-enoent 2)
(cl:defconstant os-esrch 3)
(cl:defconstant io-error-interrupted 4)
(cl:defconstant io-error-file-exists 17)
(cl:defconstant io-error-system-file-limit 23)
(cl:defconstant io-error-process-file-limit 24)
(cl:defconstant os-eisdir 21)
(cl:defconstant os-erange 34)
(cl:defconstant os-etimedout 110)
(cl:defconstant os-o-rdonly 0)
(cl:defconstant os-o-wronly 1)
(cl:defconstant os-o-rdwr 2)
(cl:defconstant os-o-creat 64)
(cl:defconstant os-o-excl 128)
(cl:defconstant os-o-trunc 512)
(cl:defconstant os-o-nonblock 2048)
(cl:defconstant os-path-max 4096)
(cl:defconstant os-s-ifmt 61440)
(cl:defconstant os-s-ififo 4096)
(cl:defconstant os-s-ifchr 8192)
(cl:defconstant os-s-ifdir 16384)
(cl:defconstant os-s-ifreg 32768)
(cl:defconstant os-s-iflnk 40960)
(cl:defconstant os-s-ifsock 49152)
(cl:defconstant os-ex-usage 64)
(cl:defconstant os-ex-software 70)
(cl:defconstant os-ex-oserr 71)

(cl:defpackage "WASM32-COMPILER" (:use "CL"))
(cl:in-package "WASM32-COMPILER")
;;; The native function's interleaved code/immediates are not the Wasm D1
;;; function object. Funcallable instances hold their seven Lisp immediates
;;; in a separate traced vector; ordinary functions expose no native literals.
(arch::defarchmacro :wasm32 ccl::nth-immediate (function index)
  `(ccl::%wasm-function-immediate ,function ,index))

(arch::defarchmacro :wasm32 ccl::set-nth-immediate (function index value)
  `(ccl::%wasm-set-function-immediate ,function ,index ,value))

(cl:in-package :wasm32)

(cl:defconstant single-float.element-count 1)
(cl:defconstant double-float.element-count 3)
(cl:defconstant ratio.numer-cell 0)
(cl:defconstant ratio.denom-cell 1)

(cl:in-package :wasm32-compiler)

(arch::defarchmacro :wasm32 ccl::%make-sfloat ()
  `(ccl::%alloc-misc wasm32::single-float.element-count
                    wasm32::subtag-single-float))

(arch::defarchmacro :wasm32 ccl::%make-dfloat ()
  `(ccl::%alloc-misc wasm32::double-float.element-count
                    wasm32::subtag-double-float))

(arch::defarchmacro :wasm32 ccl::%numerator (x)
  `(ccl::%svref ,x wasm32::ratio.numer-cell))

(arch::defarchmacro :wasm32 ccl::%denominator (x)
  `(ccl::%svref ,x wasm32::ratio.denom-cell))

(arch::defarchmacro :wasm32 ccl::immediate-p-macro (thing)
  (let ((tag (gensym)))
    `(let ((,tag (ccl::lisptag ,thing)))
       (declare (fixnum ,tag))
       (or (= ,tag wasm32::tag-fixnum) (= ,tag wasm32::tag-imm)))))

(arch::defarchmacro :wasm32 ccl::hashed-by-identity (thing)
  (let ((typecode (gensym)))
    `(let ((,typecode (ccl::typecode ,thing)))
       (declare (fixnum ,typecode))
       (or (= ,typecode wasm32::tag-fixnum)
           (= ,typecode wasm32::tag-imm)
           (= ,typecode wasm32::subtag-symbol)
           (= ,typecode wasm32::subtag-instance)))))

;;; Native function vectors interleave code and immediates. Returning the
;;; D1 object here would expose metadata words as native LFUN fields.
(arch::defarchmacro :wasm32 ccl::lfun-vector (function)
  (declare (ignore function))
  (refuse :function-immediate-layout))

(arch::defarchmacro :wasm32 ccl::function-to-function-vector (function)
  (declare (ignore function))
  (refuse :function-immediate-layout))

;;; Native kernel globals have no address in the portable owner. Keep this
;;; an explicit admission refusal until the corresponding owner entry exists.
(arch::defarchmacro :wasm32 ccl::%get-kernel-global (name)
  (declare (ignore name))
  (wasm32-compiler::refuse :kernel-global-capability))

(arch::defarchmacro :wasm32 ccl::%get-kernel-global-ptr (name destination)
  (declare (ignore name destination))
  (wasm32-compiler::refuse :kernel-global-capability))

;;; Keep the native 32-bit macro's binding and initialization order. The
;;; current allocator puts these objects on the moving heap; dynamic extent
;;; remains a lifetime declaration, not a claim of stack allocation.
(defmacro wasm32::with-stack-short-floats (specs &body body)
  (ccl::collect ((binds) (inits) (names))
    (dolist (spec specs)
      (let ((name (first spec)))
        (binds `(,name (ccl::%make-sfloat)))
        (names name)
        (when (second spec)
          (inits `(ccl::%short-float ,(second spec) ,name)))))
    `(let* ,(binds)
       (declare (dynamic-extent ,@(names)) (short-float ,@(names)))
       ,@(inits)
       ,@body)))
