(in-package "WASM32-COMPILER")
(let* ((out (ccl:getenv "LOADER_OUTPUT"))
       (source "ccl:tests;wasm;stage1;loader-level0;keywords.lisp")
       (record (symbol-function 'wasm32-code-record)))
  (flet ((compile-one (name)
           (multiple-value-bind (fasl modules warnings failure)
               (wasm32-compile-file source :output-file (concatenate 'string out name ".w32fsl"))
             (declare (ignore modules warnings))
             (assert (and fasl (not failure))))))
    (compile-one "keywords")
    (unwind-protect
         (dolist (kind '(:version :schema :key-vector :missing-wire :v2-keys))
           (setf (symbol-function 'wasm32-code-record)
                 (lambda (module table)
                   (let* ((result (funcall record module table))
                          (arity (third result)))
                     (case kind
                       (:version (setf (first result) 99))
                       (:schema (setf (first arity) 2))
                       (:key-vector (setf (seventh arity) ""))
                       (:missing-wire (when (plusp (length (seventh arity)))
                                        (setf (aref (seventh arity) 0) -1)))
                       (:v2-keys (setf (first result) 2)))
                     result)))
           (compile-one (string-downcase kind)))
      (setf (symbol-function 'wasm32-code-record) record)))
  ;; The old record version remains readable for its admitted empty-key scope.
  (with-open-file (s "ccl:tests;wasm;stage1;loader-level0;legacy.lisp"
                    :direction :output :if-exists :supersede)
    (write-line "(defun ccl::loader-legacy (x) (+ x 1))" s))
  (unwind-protect
       (progn
         (setf (symbol-function 'wasm32-code-record)
               (lambda (module table)
                 (let ((result (funcall record module table)))
                   (setf (first result) 2) result)))
         (multiple-value-bind (fasl modules warnings failure)
             (wasm32-compile-file "ccl:tests;wasm;stage1;loader-level0;legacy.lisp"
                                 :output-file (concatenate 'string out "legacy.w32fsl"))
           (declare (ignore modules warnings))
           (assert (and fasl (not failure)))))
    (setf (symbol-function 'wasm32-code-record) record))
  (delete-file "ccl:tests;wasm;stage1;loader-level0;legacy.lisp")
  (format t "KEYWORD-FASLS-PASS~%"))
(ccl:quit)
