(in-package "CCL")
(let* ((out (getenv "LOADER_OUTPUT"))
       (variables *wasm32-xload-parameter-variables*)
       (before (mapcar #'symbol-value variables))
       (rows nil))
  (dolist (control '(("version" "Unsupported wasm32 code record version")
                     ("schema" "Unsupported wasm32 callable metadata")
                     ("key-vector" "Unsupported wasm32 callable metadata")
                     ("missing-wire" "Missing wasm32 keyword symbol wire")
                     ("v2-keys" "Unsupported wasm32 v2 keyword metadata")))
    (destructuring-bind (name expected) control
      (let ((message (handler-case
                         (progn (wasm32-xfasload (concatenate 'string out "refused-" name "/")
                                                (concatenate 'string out name ".w32fsl")) nil)
                       (error (condition) (format nil "~a" condition)))))
        (assert (equal message expected))
        (assert (equal before (mapcar #'symbol-value variables)))
        (push (list :object (cons "name" name) (cons "message" message)
                    (cons "host_state_restored" t)) rows))))
  (wasm32-xfasload (concatenate 'string out "keywords/")
                  (concatenate 'string out "keywords.w32fsl")
                  (concatenate 'string out "legacy.w32fsl"))
  (assert (equal before (mapcar #'symbol-value variables)))
  (with-open-file (s (concatenate 'string out "keyword-controls.json")
                    :direction :output :if-exists :supersede)
    (wasm32-json (list :object (cons "status" "PASS") (cons "rows" (reverse rows))) s)
    (terpri s))
  (format t "KEYWORD-CROSS-LOAD-PASS~%"))
(quit)
