;;; A fresh process reads only the saved FASLs after their sources are removed.
(in-package "CCL")
(let* ((out (getenv "LOADER_OUTPUT"))
       (fasls (sort (directory (concatenate 'string out "inputs/*.w32fsl"))
                    #'string< :key #'namestring))
       (variables *wasm32-xload-parameter-variables*)
       (before (mapcar #'symbol-value variables)))
  (assert (= (length fasls) 2))
  (apply #'wasm32-xfasload (concatenate 'string out "prefix/")
         (append fasls (mapcar (lambda (name) (concatenate 'string out name ".w32fsl"))
                              '("package-support" "package-first" "package-second"))))
  (assert (equal before (mapcar #'symbol-value variables)))
  (format t "PREFIX-CROSS-LOAD-PASS~%"))
(quit)
