(in-package "CCL")
(defun loader-json-value (value stream)
  (cond ((null value) (write-string "null" stream))
        ((eq value t) (write-string "true" stream))
        ((integerp value) (format stream "~d" value))
        ((stringp value) (format stream "{\"string\":~s}" value))
        ((consp value)
         (write-char #\[ stream) (loader-json-value (car value) stream)
         (write-char #\, stream) (loader-json-value (cdr value) stream)
         (write-char #\] stream))
        (t (error "Unsupported native observation ~s" value))))
(load (concatenate 'string (getenv "LOADER_SOURCE") "keywords.lisp"))
(load (concatenate 'string (getenv "LOADER_SOURCE") "packages.lisp"))
(load (concatenate 'string (getenv "LOADER_SOURCE") "package-first.lisp"))
(load (concatenate 'string (getenv "LOADER_SOURCE") "package-second.lisp"))
(defun loader-legacy (x) (+ x 1))
(let* ((out (getenv "LOADER_OUTPUT"))
       (cases (with-open-file (s (concatenate 'string out "cases.lisp")) (read s))))
  (with-open-file (s (concatenate 'string out "native.json")
                    :direction :output :if-exists :supersede)
    (write-string "[" s)
    (loop for (id package name arguments) in cases for i from 0 do
      (unless (zerop i) (write-char #\, s))
      (format s "{\"id\":~s,\"values\":[" id)
      (let ((args (mapcar (lambda (x) (if (consp x) (find-symbol (third x) (second x)) x))
                          arguments)))
        (loop for value in (multiple-value-list (apply (find-symbol name package) args))
              for j from 0 do
                (unless (zerop j) (write-char #\, s))
                (loader-json-value value s)))
      (write-string "]}" s))
    (write-string "]" s) (terpri s)))
(quit)
