;;; Temporary bootstrap witness: select complete original DEFUN forms, with
;;; no body rewriting. The incomplete source files receive no file credit.
(in-package "WASM32-COMPILER")
(let* ((out (ccl:getenv "LOADER_OUTPUT"))
       (path "ccl:tests;wasm;stage1;loader-level0;package-support.lisp")
       (rows nil))
  (with-open-file (s path :direction :output :if-exists :supersede)
    (let ((*package* (find-package "CCL")) (*print-pretty* nil))
      (write '(in-package "CCL") :stream s) (terpri s)
      (call-with-target
       (lambda ()
         (dolist (group
                   '(("ccl:level-0;nfasload.lisp" ccl::package-%local-nicknames
                      find-package ccl::set-package ccl::%find-pkg ccl::pkg-arg)
                     ("ccl:level-0;l0-aprims.lisp" string)
                     ("ccl:level-0;l0-misc.lisp" length list-length)
                     ("ccl:level-0;l0-pred.lisp" ccl::sequence-type packagep
                      characterp symbolp stringp listp ccl::fixnump)
                     ("ccl:level-0;l0-array.lisp" ccl::%aref1 schar)
                     ("ccl:level-0;l0-symbol.lisp" symbol-name)
                     ("ccl:level-1;l1-symhash.lisp" package-name ccl::pkg-arg-allow-deleted)))
           (let ((found nil))
             (with-open-file (source (first group))
               (loop for form = (read source nil :end) until (eq form :end) do
                 (when (and (consp form) (eq (car form) 'defun)
                            (member (second form) (cdr group)))
                   (assert (not (member (second form) found)))
                   (push (second form) found)
                   (write form :stream s) (terpri s)
                   (when (null (set-difference (cdr group) found)) (return)))))
             (assert (null (set-difference (cdr group) found)))
             (push (list :object (cons "source" (first group))
                         (cons "definitions" (mapcar #'symbol-name (reverse found)))) rows))))))
    (with-open-file (probes (concatenate 'string (ccl:getenv "LOADER_SOURCE") "packages.lisp"))
      (loop for line = (read-line probes nil nil) while line do (write-line line s))))
  (with-open-file (s (concatenate 'string out "package-origins.json")
                    :direction :output :if-exists :supersede)
    (ccl::wasm32-json (reverse rows) s) (terpri s))
  (multiple-value-bind (fasl modules warnings failure)
      (wasm32-compile-file path :output-file (concatenate 'string out "package-support.w32fsl"))
    (declare (ignore modules warnings))
    (assert (and fasl (not failure))))
  (dolist (name '("package-first" "package-second"))
    (multiple-value-bind (fasl modules warnings failure)
        (wasm32-compile-file (concatenate 'string "ccl:tests;wasm;stage1;loader-level0;" name ".lisp")
                            :output-file (concatenate 'string out name ".w32fsl"))
      (declare (ignore modules warnings))
      (assert (and fasl (not failure))))))
(ccl:quit)
