;;; Private TYPEP helpers; no global compiler binding or source changes.
(defpackage :ccl-target-predicates (:use :cl))
(in-package :ccl-target-predicates)
(defvar *trace* nil)
(defvar *phase* nil)
(defvar *event* nil)
(defvar *mode* "normal")
(defun obj (&rest xs) (apply #'ccl-target-helpers::obj xs))
(defun syntax (x) (ccl-target-helpers::syntax x))
(defun row (helper &rest fields)
  (push (apply #'obj "helper" helper "phase" *phase* "event" *event*
               "context" (ccl-source-traversal::context) fields) *trace*))
(defun translate (type leaf)
  (let ((answer
          (cond ((equal *mode* "inherited") type)
                ((eq type 'bignum)
                 (if (equal *mode* "fixnum-only") type
                   `(and integer (not ,(funcall leaf 'fixnum)))))
                ((and (consp type) (not (equal *mode* "shallow"))
                      (member (car type) (if (equal *mode* "member-data") '(or and not member) '(or and not))))
                 (cons (car type) (mapcar (lambda (x) (translate x leaf)) (cdr type))))
                (t (funcall leaf type)))))
    (row "TARGET-TYPE" "input" (syntax type) "answer" (syntax answer))
    answer))
(defun ctype-guard (thing ctype)
  (let ((cross (not (eq ccl::*host-backend* ccl::*target-backend*))))
    (let ((answer (if (equal *mode* "host-ctype")
                    (let ((ccl::*target-backend* ccl::*host-backend*)) (ccl::optimize-ctypep thing ctype))
                    (ccl::optimize-ctypep thing ctype))))
      (row "OPTIMIZE-CTYPEP" "cross_target" (ccl-target-helpers::bool cross)
           "type" (syntax (ccl::type-specifier ctype)) "answer" (syntax answer))
      answer)))
(defun build (macro optimizer target-type)
  (let ((leaf (copy-tree (cdr target-type)))
        (local (copy-tree (cdr optimizer))))
    (setf (first leaf) 'leaf-target-type)
    (setf (cddr local)
          `((let ((answer (block ccl::optimize-typep ,@(cddr local))))
              (row "OPTIMIZE-TYPEP" "thing" (syntax ccl::thing) "type" (syntax ccl::type)
                   "answer" (syntax answer)) answer)))
    (ccl-census-macros::native-function
     `(lambda (form env)
        (let ((*event* (1- ccl-source-expanders::*next-event*)))
          (flet ((native-typep (thing type environment) (cl:typep thing type environment))
                 (native-known (type environment whine) (ccl::specifier-type-if-known type environment :whine whine)))
          (labels (,leaf
                   (cl:typep (thing type &optional environment)
                     (let* ((target-type (translate type #'leaf-target-type))
                            (answer (native-typep thing target-type environment)))
                       (row "TYPEP" "thing" (syntax thing) "type" (syntax type)
                            "target_type" (syntax target-type) "answer" (ccl-target-helpers::bool answer)) answer))
                   (ccl::specifier-type-if-known (type environment &key whine)
                     (let* ((target-type (translate type #'leaf-target-type))
                            (answer (native-known target-type environment whine)))
                       (row "SPECIFIER-TYPE-IF-KNOWN" "type" (syntax type) "target_type" (syntax target-type)
                            "known" (ccl-target-helpers::bool answer)
                            "canonical" (if answer (syntax (ccl::type-specifier answer)) :null)) answer))
                   (ccl::optimize-ctypep (thing ctype) (ctype-guard thing ctype))
                   ,local)
            (funcall (function ,(ccl::parse-macro-1 (second macro) (third macro) (cdddr macro))) form env))))))))

;; Values and types are actual Lisp input, not encoded result expectations.
(defparameter *cases*
 '(("fixnum-zero" 0 fixnum) ("fixnum-max" 536870911 fixnum) ("fixnum-min" -536870912 fixnum)
   ("fixnum-positive-boxed" 536870912 fixnum) ("fixnum-negative-boxed" -536870913 fixnum)
   ("fixnum-single-float" 1.0f0 fixnum)
   ("bignum-positive" 536870912 bignum) ("bignum-negative" -536870913 bignum)
   ("bignum-immediate" 536870911 bignum) ("bignum-large" 1152921504606846976 bignum)
   ("bignum-float" 1.0d0 bignum)
   ("or-boxed" 536870912 (or symbol fixnum))
   ("or-symbol" :foo (or symbol fixnum))
   ("not-fixnum" 536870912 (not fixnum))
   ("and-immediate" 5 (and integer fixnum))
   ("and-boxed" 536870912 (and integer (not fixnum)))
   ("bignum-complement" 536870912 (not bignum))
   ("member-fixnum-literal" fixnum (member fixnum))
   ("member-bignum-literal" bignum (member bignum))
   ("member-integer-literal" 536870912 (member 536870912))
   ("explicit-signed-31" 536870912 (signed-byte 31))
   ("explicit-bound" 536870912 (integer 536870912 536870912))))
(defun probe (case)
  (destructuring-bind (name value type) case
    (let* ((*phase* name) (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
           (form `(lambda () (typep ',value ',type)))
           (afunc (ccl-source-expanders::with-routing
                    (lambda () (ccl-census-stub::capture-lambda form 'ccl::predicate-probe)))))
      (obj "name" name "value" (syntax value) "type" (syntax type) "form" (syntax form)
           "operators" (ccl-target-helpers::operators (ccl::afunc-acode afunc))
           "ir" (ccl-source-expanders::ir (ccl::afunc-acode afunc))
           "function" (ccl-startup-census::function-observation afunc)
           "events" (reverse ccl-source-expanders::*events*)))))
(defun guard-probes ()
  (let ((*phase* "ctype-guard") (*event* :null))
    (loop for type in '((signed-byte 30) (simple-array (unsigned-byte 8) (*))) collect
      (let* ((ctype (ccl::specifier-type type)) (result (ctype-guard 'ccl::x ctype)))
        (obj "type" (syntax type) "answer" (syntax result))))))
(defun passthrough-probes (entry)
  (let ((*phase* "passthrough") (*event* :null))
    (loop for form in '((typep ccl::x ccl::type) (typep ccl::x 'fixnum ccl::env)) collect
      (let ((answer (funcall (third entry) form nil)))
        (obj "input" (syntax form) "output" (syntax answer) "same" (ccl-target-helpers::bool (eq form answer)))))))
(defun run ()
  (let ((ccl-census-macros::*sources* nil) (ccl-census-macros::*registry* nil)
        (ccl-source-expanders::*registry* nil) (ccl-source-expanders::*compiled* nil)
        (ccl-source-expanders::*events* nil) (ccl-source-expanders::*next-event* 0)
        (ccl-source-expanders::*literals* nil) (ccl-target-helpers::*sources* nil)
        (ccl-target-helpers::*calls* nil) (ccl-target-types::*trace* nil) (*trace* nil)
        (*mode* (or (ccl:getenv "CCL_PREDICATE_MODE") "normal"))
        (before (ccl-source-traversal::state)) (old-hook *macroexpand-hook*)
        (old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
        (names '(typep ccl::specifier-type-if-known ccl::optimize-typep ccl::optimize-ctypep ccl::nx-target-type)))
   (let ((globals (mapcar #'fdefinition names)))
    (ccl-source-expanders::prepare)
    (dolist (r (reverse ccl-source-expanders::*registry*)) (ccl-target-helpers::ident (third r)) (ccl-target-helpers::ident (fourth r)))
    (flet ((source (path name) (ccl-target-helpers::read-form path name)))
     (let* ((helper (source "compiler/optimizers.lisp" "defun eql-iff-eq-p"))
            (range (source "compiler/nx0.lisp" "defun nx1-target-fixnump"))
            (eql-form (source "compiler/optimizers.lisp" "define-compiler-macro eql"))
            (typep-form (source "compiler/nx0.lisp" "defun nx-form-typep"))
            (form-type (source "compiler/nx0.lisp" "defun nx-form-type"))
            (target-type (source "compiler/nx-basic.lisp" "defun nx-target-type"))
            (lookup (source "compiler/nx0.lisp" "defun nx-lookup-target-uvector-subtag"))
            (stream (source "compiler/optimizers.lisp" "define-compiler-macro basic-stream-p"))
            (vector (source "compiler/optimizers.lisp" "define-compiler-macro vectorp"))
            (macro (source "compiler/optimizers.lisp" "define-compiler-macro typep"))
            (optimizer (source "compiler/optimizers.lisp" "defun optimize-typep"))
            (entry (ccl-target-helpers::compiler-entry 'typep)) (compiled nil))
       (ccl-source-expanders::with-compiler-observation
        (lambda ()
         (setf (third (ccl-target-helpers::compiler-entry 'eql))
               (ccl-target-types::build helper range eql-form typep-form form-type target-type "normal")
               (third (ccl-target-helpers::compiler-entry 'ccl::basic-stream-p)) (ccl-target-helpers::build-stream lookup stream)
               (third (ccl-target-helpers::compiler-entry 'vectorp)) (ccl-target-helpers::build-stream lookup vector)
               compiled (build macro optimizer target-type)
               (third entry) compiled)))
       (let ((*phase* "dumplisp")) (ccl-source-expanders::with-routing #'ccl-census-descriptions::run))
       (let ((probes nil) (guards nil) (passthrough nil))
        (ccl-census-descriptions::with-descriptions
         (lambda () (ccl-census-stub::with-target-state
          (lambda () (setf guards (guard-probes) probes (mapcar #'probe *cases*) passthrough (passthrough-probes entry))))))
        (unless (and (equal before (ccl-source-traversal::state)) (eq old-hook *macroexpand-hook*)
                     (eq old-p2 (ccl::backend-p2-compile ccl::*host-backend*))
                     (every #'eq globals (mapcar #'fdefinition names))) (error "PREDICATE-STATE-NOT-RESTORED"))
        (with-open-file (out (ccl:getenv "CCL_PREDICATE_OUTPUT") :direction :output :if-exists :error :external-format :utf-8)
          (ccl-startup-census::json
           (obj "version" 1 "sources" (reverse ccl-target-helpers::*sources*) "probes" probes "guards" guards
                "passthrough" passthrough "trace" (reverse *trace*) "events" ccl-source-expanders::*events*
                "selected_id" (ccl-target-helpers::ident compiled)
                "compiled" (cdr (assoc compiled ccl-source-expanders::*compiled* :test #'eq))
                "native_ctype_helper_id" (ccl-target-helpers::ident #'ccl::optimize-ctypep)
                "literals" (mapcar #'cdr (reverse ccl-source-expanders::*literals*))
                "restored" :true "macro_environment_qualified" :false "graph_edges_replaced" 0) out)
          (terpri out))))))))
