(module
  (import "host" "probe" (func $probe (param i32)))
  (import "host" "value" (func $host (result i32)))
  (memory (export "memory") 1 4)
  (table 0 4 funcref)
  (tag $failure (param i32))
  (global $initialized (mut i32) (i32.const 0))
  (global $state (mut i32) (i32.const 0))
  (func $init (export "initialize") (export "initialize_alias")
    global.get $initialized i32.const 1 i32.add global.set $initialized
    i32.const 11 call $probe)
  (func (export "initialized") (result i32) global.get $initialized)
  (func (export "i32") (param i32) (result i32) local.get 0)
  (func (export "i64") (param i64) (result i64) local.get 0)
  (func (export "f32") (param f32) (result f32) local.get 0)
  (func (export "f64") (param f64) (result f64) local.get 0)
  (func (export "many") (param i32 i64 f32 f64) (result i32 i64 f32 f64)
    local.get 0 local.get 1 local.get 2 local.get 3)
  (func (export "void"))
  (func (export "add") (param i32) (result i32)
    global.get $state local.get 0 i32.add global.set $state global.get $state)
  (func (export "read") (result i32) i32.const 0 i32.load)
  (func (export "write") (param i32) i32.const 0 local.get 0 i32.store)
  (func (export "grow") (result i32) i32.const 1 memory.grow)
  (func (export "pages") (result i32) memory.size)
  (func (export "trap") unreachable)
  (func (export "oob") i32.const -1 i32.load drop)
  (func (export "throw") i32.const 42 throw $failure)
  (func (export "host") (result i32) call $host)
  (func (export "__proto__") (result i32) i32.const 73)
)
