(in-package "CCL")
(let* ((*xload-spaces* nil)
       (space (init-xload-space #x40000000 128 area-dynamic))
       (*xload-backend-state* (make-wasm32-xload-state :scratch space)))
  (dotimes (i 32) (setf (aref (xload-space-data space) i) (+ 1000 i)))
  (setf (xload-space-lowptr space) 64)
  (wasm32-reserve-code-record-space)
  (assert (= (xload-space-size space) 128))
  (setf (xload-space-lowptr space) 72)
  (wasm32-reserve-code-record-space)
  (assert (= (xload-space-size space) 256))
  (assert (= (xload-space-lowptr space) 72))
  (dotimes (i 32) (assert (= (aref (xload-space-data space) i) (+ 1000 i))))
  (loop for i from 32 below 64 do (assert (zerop (aref (xload-space-data space) i))))
  (setf (xload-space-lowptr space) 192)
  (wasm32-reserve-code-record-space)
  (assert (= (xload-space-size space) 512))
  (assert (= (xload-space-lowptr space) 192))
  (assert (= (xload-space-vaddr space) #x40000000))
  (dotimes (i 32) (assert (= (aref (xload-space-data space) i) (+ 1000 i))))
  (with-open-file (s (concatenate 'string (getenv "LOADER_OUTPUT") "scratch-controls.json")
                    :direction :output :if-exists :supersede)
    (write-line "{\"status\":\"PASS\",\"half_full_unchanged\":true,\"growth\":[128,256,512],\"bytes_preserved\":128,\"addresses_preserved\":true}" s)))
