(in-package :wasm32-compiler)
;; Preserve native policy-dependent error priority as data. No normalization
;; rewrites these observations into target expectations.
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-policy-errors.txt") :direction :output :if-exists :error)
 (dolist (policy '((0 3) (1 1) (2 2) (3 3) (3 0)))
  (dolist (op '(+ - * ash truncate))
   (let ((fn (compile nil `(lambda (a b) (declare (optimize (safety ,(first policy)) (speed ,(second policy))))
              (handler-case (,op a b) (type-error (e) (list :type (type-error-datum e) (type-error-expected-type e))) (division-by-zero () :zero))))))
    (dolist (args '((nil t) (t nil) (nil 0) (7 nil)))
     (format s "~s ~s ~s ~s~%" policy op args (multiple-value-list (apply fn args))))))))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "native-reader-errors.txt") :direction :output :if-exists :error)
 (dolist (name '(arithmetic-error-operation arithmetic-error-operands))
  (handler-case (funcall name (make-condition 'type-error :datum nil :expected-type 'number))
   (error (e) (format s "~s ~s~%" name (class-name (class-of e)))))))
(with-open-file (s (concatenate 'string (ccl:getenv "POOL_OUTPUT") "mode-admission.txt") :direction :output :if-exists :error)
 (dolist (symbol '(number real truncate))
  (let* ((form `(lambda () ',symbol)) (refused nil))
   (handler-case (compile-call-form form "ordinary_quote" nil)
    (error () (setq refused t)))
   (unless refused (error "Default quote admission escaped: ~s" symbol))
   (compile-integer-call-form form "numeric_quote" nil)
   (format s "~s DEFAULT-REFUSED NUMERIC-ADMITTED~%" symbol))))
